-- Auth Connection Errors Mining - 2025-11-26
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Authorization server not configured with default connection', 'authentication', 'HIGH', '[{"solution": "Navigate to Auth0 Dashboard > Tenant Settings, scroll down to Default Directory setting and enter ''Username-Password-Authentication'' for Resource Owner Password Flow", "percentage": 95}, {"solution": "Ensure the connection is capable of authenticating users by username and password before setting as default", "percentage": 85}]'::jsonb, 'Auth0 account with applications and connections created', 'Ability to make requests with user credentials without receiving authorization server error', 'Confusing Default Directory with application name, not setting the correct connection type', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/69419470/auth0-error-authorization-server-not-configured-with-default-connection', 'admin:1764192112');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Could not open a connection to your authentication agent', 'authentication', 'HIGH', '[{"solution": "Start ssh-agent with ''eval `ssh-agent -s`'' command before running ssh-add to establish the authentication agent socket", "percentage": 96}, {"solution": "On Windows Git Bash, use ''eval $(ssh-agent)'' instead of backtick syntax for proper shell interpretation", "percentage": 92}]'::jsonb, 'SSH client installed, private key file exists at ~/.ssh/id_rsa', 'ssh-add command executes without connection errors, SSH_AUTH_SOCK environment variable is set', 'Using public key file (.pub) instead of private key with ssh-add, not setting required SSH_AUTH_SOCK environment variable, shell incompatibility with eval syntax', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/17846529/could-not-open-a-connection-to-your-authentication-agent', 'admin:1764192112');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Auth0 multiple connections login realm required error', 'authentication', 'MEDIUM', '[{"solution": "Design single database connection per application and specify realm parameter in OAuth token endpoint requests, avoid attempting to authenticate across multiple connections concurrently", "percentage": 88}, {"solution": "If multiple connections required, implement loop-based authentication attempting each connection sequentially until successful match found", "percentage": 72}]'::jsonb, 'Multiple Auth0 database connections configured, understanding of OAuth realm parameter usage', 'Successful token acquisition from /oauth/token endpoint with proper realm specification, user authenticated from designated connection', 'Attempting concurrent authentication across multiple connections causing Auth0 service bottleneck, omitting realm parameter when multiple connections active, misunderstanding connection vs application relationship', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/75225387/auth-0-multiple-connections-login', 'admin:1764192112');
