INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('React Hydration Error in Next.js', 'nextjs', 'HIGH', '[{"solution": "Use useState with useEffect to check if component is mounted before rendering", "percentage": 95}, {"solution": "Check for invalid HTML nesting like p tags wrapping divs - use semantic HTML elements correctly", "percentage": 90}]'::jsonb, 'React hooks, Server-side rendering', 'No hydration mismatch errors in browser console', 'Not using useEffect for client-side detection, invalid HTML nesting', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/73162551/how-to-solve-react-hydration-error-in-nextjs', 'admin:1764222667'),

('Hydration failed because initial UI does not match server rendered content', 'nextjs', 'HIGH', '[{"solution": "Wrap problematic components with useEffect for DOM check", "percentage": 92}, {"solution": "Avoid using Window object in components - use dynamic imports with ssr false", "percentage": 88}]'::jsonb, 'React ES6+, Next.js app router', 'Page renders without hydration mismatch warnings', 'Using Window API in SSR components, Browser extensions interfering', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/71706064/react-18-hydration-failed-because-the-initial-ui-does-not-match-what-was-render', 'admin:1764222667'),

('Next.js 15 hydration failed server rendered HTML did not match', 'nextjs', 'MEDIUM', '[{"solution": "Remove conflicting browser extensions that modify DOM like VPN extensions", "percentage": 85}, {"solution": "Ensure all data between server and client render is identical", "percentage": 90}]'::jsonb, 'Browser dev tools, Next.js 15+', 'Clean console without hydration errors', 'Outdated extension interfering with Next.js rendering', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/79244952/next-js-15-0-3-hydration-failed-because-the-server-rendered-html-didnt-match-t', 'admin:1764222667'),

('getServerSideProps is not supported in app directory', 'nextjs', 'MEDIUM', '[{"solution": "Use only getServerSideProps in /pages directory, not in /app directory", "percentage": 98}, {"solution": "In app directory, use loader functions or fetch directly in server components", "percentage": 95}]'::jsonb, 'Next.js 13+ app router', 'getServerSideProps works in pages route', 'Placing getServerSideProps in app components or outside pages directory', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/76725399/nextjs-how-to-fix-getserversideprops-is-not-supported-in-app', 'admin:1764222667'),

('getServerSideProps not working in components', 'nextjs', 'MEDIUM', '[{"solution": "getServerSideProps can only be exported from page components, not from imported components", "percentage": 100}, {"solution": "Pass props from page''s getServerSideProps to child components instead", "percentage": 98}]'::jsonb, 'Page vs component structure', 'Props correctly passed from page to components', 'Using getServerSideProps in non-page components', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/64136025/nextjs-getserversideprops-not-working-into-components', 'admin:1764222667'),

('getServerSideProps 400 Bad Request error with fetch', 'nextjs', 'MEDIUM', '[{"solution": "Ensure API headers are correct and request parameters are valid", "percentage": 88}, {"solution": "Use try-catch blocks to handle fetch errors and return proper error handling", "percentage": 90}]'::jsonb, 'API knowledge, error handling', 'Successful fetch with 200 status code', 'Missing required headers, invalid request parameters, credential issues', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/66433023/nextjs-getserversideprops-error-400-bad-request', 'admin:1764222667'),

('Cannot find module next or its corresponding type declarations', 'nextjs', 'MEDIUM', '[{"solution": "Restart TypeScript server in VSCode with Cmd+Shift+P", "percentage": 85}, {"solution": "For Yarn 3 with VSCode: Run yarn dlx and select workspace version", "percentage": 92}]'::jsonb, 'TypeScript, VSCode, Yarn', 'Module resolves correctly without red squiggles', 'Not restarting TS server, Yarn 3 SDK not configured', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/69238794/cannot-find-module-next-or-its-corresponding-type-declarations', 'admin:1764222667'),

('Module not found can''t resolve in Next.js TypeScript', 'nextjs', 'MEDIUM', '[{"solution": "Delete .next directory and re-run npm run dev to rebuild cache", "percentage": 92}, {"solution": "Create empty tsconfig.json in root - Next.js will auto-populate", "percentage": 95}]'::jsonb, 'TypeScript configuration, Next.js build system', 'Build succeeds without module resolution errors', 'Stale .next cache, missing tsconfig.json', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/71433951/module-not-found-cant-resolve-next-js-typescript', 'admin:1764222667'),

('Module not found: Can''t resolve fs in Next.js application', 'nextjs', 'HIGH', '[{"solution": "Use fs only in getServerSideProps or getStaticProps, never in browser code", "percentage": 98}, {"solution": "Configure next.config.js for webpack fallback: config.resolve.fallback = { fs: false }", "percentage": 96}]'::jsonb, 'Node.js fs module knowledge, webpack config', 'No fs resolution errors in build', 'Using fs module in client-side code, missing webpack5 config', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/64926174/module-not-found-cant-resolve-fs-in-next-js-application', 'admin:1764222667'),

('Image Optimization using default loader not compatible with next export', 'nextjs', 'HIGH', '[{"solution": "Disable image optimization: add images: { unoptimized: true } to next.config.js", "percentage": 95}, {"solution": "Use third-party loader like Imgix: images: { loader: ''imgix'' }", "percentage": 92}]'::jsonb, 'next/image component, next.config.js', 'Successfully export static site without image errors', 'Using next export with optimized images, missing loader config', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/65487914/error-image-optimization-using-next-js-default-loader-is-not-compatible-with-n', 'admin:1764222667'),

('Next.js image optimization not working on production', 'nextjs', 'HIGH', '[{"solution": "Run next build followed by next start for production - not next export", "percentage": 98}, {"solution": "For static export, set unoptimized: true or use external image service", "percentage": 96}]'::jsonb, 'Image component, deployment, Next.js production', 'Images load correctly in production environment', 'Using next export instead of next start, missing image config', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/73556431/next-js-11-image-optimization-is-not-working-on-production-environment', 'admin:1764222667'),

('Next.js app won''t export due to image optimization', 'nextjs', 'MEDIUM', '[{"solution": "Images can only be optimized on-demand, not at build time", "percentage": 100}, {"solution": "Disable optimization for export: images: { unoptimized: true }", "percentage": 98}]'::jsonb, 'next export, next/image', 'Static HTML export completes successfully', 'Using next export with image optimization enabled', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/73913732/nextjs-app-wont-export-due-to-image-optimization', 'admin:1764222667'),

('Cannot handle errors in Next.js API routes', 'nextjs', 'MEDIUM', '[{"solution": "Create custom error class and async error wrapper function", "percentage": 88}, {"solution": "Use next-connect middleware package for consistent error handling", "percentage": 85}]'::jsonb, 'Error handling patterns, Express middleware', 'Consistent error responses across all API routes', 'Not centralizing error handling, missing error boundaries', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/71551876/how-to-handle-errors-in-next-js-api-routes', 'admin:1764222667'),

('Fetching Next.js API route in app directory gives 404', 'nextjs', 'MEDIUM', '[{"solution": "Use proper file naming: app/api/admin/route.js not app/api/admin/all.js", "percentage": 100}, {"solution": "Use proper signatures: export async function GET(request) {}", "percentage": 99}]'::jsonb, 'App router conventions, HTTP methods', 'API route accessible at endpoint returning correct data', 'Wrong file naming, wrong function signatures for app', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/76336930/fetching-next-js-api-route-in-the-app-directory-gives-404-not-found', 'admin:1764222667'),

('Cannot find a valid build in .next directory', 'nextjs', 'HIGH', '[{"solution": "Run next build before next start in production", "percentage": 99}, {"solution": "Ensure package.json has correct build and start scripts", "percentage": 97}]'::jsonb, 'Build process, deployment', 'Application starts successfully in production', 'Skipping build step, missing .next directory', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/50947389/nextjs-cannot-find-a-valid-build-in-the-next-directory', 'admin:1764222667'),

('Build error occurred after compiled successfully', 'nextjs', 'MEDIUM', '[{"solution": "Create missing 404.tsx page in pages directory", "percentage": 92}, {"solution": "Check webpack config is not breaking required Next.js defaults", "percentage": 88}]'::jsonb, 'Build process, page structure', 'Build completes without errors', 'Missing 404 page, corrupted webpack config', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/65775054/next-js-build-error-occurred-after-compiled-successfully', 'admin:1764222667'),

('Error and Not Found pages not displaying properly in Next.js 13', 'nextjs', 'MEDIUM', '[{"solution": "error.js is client component and won''t render on server side", "percentage": 89}, {"solution": "Use notFound() function from next/navigation to trigger 404", "percentage": 92}]'::jsonb, 'App router, error boundaries, server components', 'Custom error and 404 pages display correctly', 'Using error.js on server, throwing errors in event handlers', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/76964636/next-js-13-error-and-not-found-pages-not-displaying-properly', 'admin:1764222667'),

('Custom errors from server to client with Server Actions', 'nextjs', 'MEDIUM', '[{"solution": "Serialize error to plain object: return { error: { message } }", "percentage": 94}, {"solution": "Cannot pass Error objects from server to client - convert to JSON", "percentage": 96}]'::jsonb, 'Server actions, error serialization', 'Custom errors properly handled on client side', 'Passing Error objects directly, not serializing errors', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/77336592/how-to-throw-and-handle-custom-errors-from-server-to-client-side-in-next-js', 'admin:1764222667'),

('Next.js production mode digest error 1782794309', 'nextjs', 'MEDIUM', '[{"solution": "Return error data instead of throwing in server actions", "percentage": 91}, {"solution": "Check generateStaticParams usage - may conflict with SSR routes", "percentage": 88}]'::jsonb, 'Error handling, Server Components', 'Application runs without digest errors in production', 'Throwing errors in server actions, generateStaticParams on SSR', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/76305664/next-js-error-in-production-mode-digest-1782794309', 'admin:1764222667'),

('Error handling getInitialProps in Next.js', 'nextjs', 'MEDIUM', '[{"solution": "Use early return pattern with statusCode: return { statusCode: 500 }", "percentage": 93}, {"solution": "Render custom _error.js page based on statusCode prop", "percentage": 91}]'::jsonb, 'Error pages, getInitialProps', 'Custom error page renders for server errors', 'Not handling errors in getInitialProps, missing _error.js', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/60624532/next-js-how-to-handle-error-in-getinitialprops', 'admin:1764222667'),

('Custom error page ignored in dev mode Next.js', 'nextjs', 'LOW', '[{"solution": "Custom error page only renders in production mode environment", "percentage": 89}, {"solution": "Next.js shows error-debug page in dev for better debugging", "percentage": 100}]'::jsonb, 'Development vs production mode', 'Custom error page shows in production build', 'Testing error page in dev mode', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/49758680/nextjs-use-error-js-in-dev-mode', 'admin:1764222667'),

('Best practice handling server error and client-side error', 'nextjs', 'MEDIUM', '[{"solution": "Use Early Return pattern with statusCode for server errors", "percentage": 94}, {"solution": "Use Error Boundary in _app.js for runtime errors in components", "percentage": 91}]'::jsonb, 'Error handling patterns, Error Boundary', 'Consistent error handling across server and client', 'Mixing error handling strategies, not using Error Boundary', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/64583856/nextjs-best-practice-for-handling-server-error-and-client-side-error', 'admin:1764222667'),

('Properly handle server-side errors in Next.js 14', 'nextjs', 'MEDIUM', '[{"solution": "Let errors propagate to error.tsx boundary for handling", "percentage": 89}, {"solution": "Place error.jsx closer to error source to prevent UI issues", "percentage": 92}]'::jsonb, 'Error boundaries, App router', 'Selective error boundaries preventing UI breakage', 'Catching all errors, placing error boundary too high', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/77384190/how-to-properly-handle-server-side-errors-in-next-js-14', 'admin:1764222667'),

('Module not found importing TypeScript module in Next.js', 'nextjs', 'MEDIUM', '[{"solution": "Omit file extension in imports: import { test2 } from lib/test2", "percentage": 98}, {"solution": "Webpack compiles TS before resolving - use extensionless imports", "percentage": 97}]'::jsonb, 'TypeScript imports, webpack', 'Imports resolve correctly without file extension errors', 'Using .js extension with .ts files', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/63408148/next-js-module-not-found-when-importing-typescript-module', 'admin:1764222667'),

('Error building Next.js app - can''t resolve next/head', 'nextjs', 'MEDIUM', '[{"solution": "Run npm install after cloning to ensure all dependencies installed", "percentage": 98}, {"solution": "Check react and react-dom are in package.json dependencies", "percentage": 96}]'::jsonb, 'Package management, dependencies', 'Build succeeds with all modules resolved', 'Missing node_modules, incomplete npm install', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/58054701/error-when-building-next-js-app-cant-resolve-next-head', 'admin:1764222667'),

('Cannot find module next/headers in Next.js 12', 'nextjs', 'MEDIUM', '[{"solution": "Use next-auth@4.15.1 with Next.js 12 compatibility", "percentage": 98}, {"solution": "Update either Next.js to 13 or downgrade next-auth to compatible version", "percentage": 97}]'::jsonb, 'Version compatibility, package management', 'next-auth and Next.js versions compatible', 'Version mismatch between next-auth and Next.js', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/74339649/next-js-error-cannot-find-module-next-headers', 'admin:1764222667'),

('Unable to optimize image with middleware matcher config', 'nextjs', 'MEDIUM', '[{"solution": "Update middleware matcher: exclude _next/image and images folder", "percentage": 94}, {"solution": "Add both _next/image and public images paths to exclusion", "percentage": 93}]'::jsonb, 'Middleware configuration, regex patterns', 'Images load without ImageError in dev', 'Incomplete middleware matcher regex', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/76286726/nextjs-imageerror-unable-to-optimize-image-and-unable-to-fallback-to-upstream-i', 'admin:1764222667'),

('Image Optimization timeout error in Next.js 15', 'nextjs', 'MEDIUM', '[{"solution": "Use unoptimized attribute on Image component for slow images", "percentage": 92}, {"solution": "Increase timeout using custom loader or disable optimization", "percentage": 88}]'::jsonb, 'Next.js 15, image configuration', 'Images load within timeout without errors', 'External images taking too long to fetch', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/79148751/next-js-15-image-optimization-timeout-error-resolved-after-restart-pc', 'admin:1764222667'),

('Next image not loading in production', 'nextjs', 'HIGH', '[{"solution": "Ensure file casing matches exactly: iphone.png not iphone.PNG", "percentage": 96}, {"solution": "Use next start not next export for production deployment", "percentage": 98}]'::jsonb, 'File naming, production deployment', 'Images display correctly in production', 'Incorrect file casing, using next export instead of next start', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/70797559/next-image-not-loading-in-production', 'admin:1764222667'),

('API routes not working getting 404 Not Found', 'nextjs', 'MEDIUM', '[{"solution": "Use app router: app/api/admin/route.ts with export function GET", "percentage": 99}, {"solution": "Or use pages router: pages/api/test.ts with default handler export", "percentage": 98}]'::jsonb, 'API routing conventions, file structure', 'API route accessible and returning response', 'Mixing old pages router with new app router conventions', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/76772934/problem-with-api-routes-not-working-in-next-js-keep-getting-404-not-found-i', 'admin:1764222667'),

('Default response on error or no HTTP method match', 'nextjs', 'MEDIUM', '[{"solution": "Use next-connect middleware for consistent error handling", "percentage": 92}, {"solution": "Or wrap API handler to return onError and onNoMatch", "percentage": 89}]'::jsonb, 'Error handling, middleware', 'Unified error handling for all API routes', 'Duplicate error handling code across routes', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/66529141/next-js-api-routes-default-response-on-error-or-no-http-method-match', 'admin:1764222667'),

('API route not found - page could not be found 404', 'nextjs', 'MEDIUM', '[{"solution": "Cannot use next export with API routes - remove from build", "percentage": 99}, {"solution": "API routes only work with next start server, not static exports", "percentage": 100}]'::jsonb, 'API routes, deployment, export', 'API routes accessible in production', 'Using next export with API routes', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/62664255/api-route-not-found-in-a-next-js-app-the-page-could-not-be-found', 'admin:1764222667'),

('External API call error in Next.js API route', 'nextjs', 'MEDIUM', '[{"solution": "Use try-catch for external API calls with proper error handling", "percentage": 94}, {"solution": "Check HTTP method matching and set correct headers for requests", "percentage": 92}]'::jsonb, 'HTTP requests, error handling', 'External API calls return expected responses', 'Missing error handling, incorrect headers, wrong HTTP method', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/61695659/encountered-error-when-making-external-api-call-in-next-js-api-route', 'admin:1764222667'),

('Could not find production build in .next directory', 'nextjs', 'HIGH', '[{"solution": "Run next build before next start in deployment", "percentage": 99}, {"solution": "Use npm run dev for development, npm start only after build", "percentage": 98}]'::jsonb, 'Build process, deployment', 'Application starts successfully with valid build', 'Skipping build step, missing .next directory after build', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/78919744/fail-to-run-build-project-next-js', 'admin:1764222667'),

('Cannot use import statement outside a module - build error', 'nextjs', 'MEDIUM', '[{"solution": "Add transpilePackages config for ESM packages in next.config.js", "percentage": 96}, {"solution": "Check babel configuration and next.config.js setup", "percentage": 93}]'::jsonb, 'Babel configuration, ESM modules', 'Build completes successfully with all imports', 'Missing ESM transpilation config, broken babel setup', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/63879688/next-js-npm-run-build-failed', 'admin:1764222667'),

('Cannot set headers after they are sent to client', 'nextjs', 'MEDIUM', '[{"solution": "Use async/await with axios instead of streams", "percentage": 94}, {"solution": "Ensure only one response send per request handler", "percentage": 98}]'::jsonb, 'Response handling, async/await', 'API route responds without header errors', 'Multiple response sends, not waiting for async operations', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/61695659/encountered-error-when-making-external-api-call-in-next-js-api-route', 'admin:1764222667'),

('Dynamic server usage error - Page could not be rendered statically', 'nextjs', 'MEDIUM', '[{"solution": "Mark route as dynamic to avoid static generation attempts", "percentage": 91}, {"solution": "Move cookies() and headers() calls out of catch blocks at root", "percentage": 88}]'::jsonb, 'Server components, dynamic rendering', 'Routes marked as dynamic where needed', 'Using cookies() in try-catch at route root level', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/78457541/getting-api-routes-in-nextjs-app-router-to-respond-with-json-okfalse-when-a', 'admin:1764222667')
;
