INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Error during connect: This error may indicate that the docker daemon is not running', 'docker', 'HIGH', '[{"solution": "Start Docker Desktop application on Windows/Mac or run systemctl start docker on Linux", "percentage": 95}, {"solution": "On Windows, run DockerCli.exe -SwitchDaemon from Docker installation directory", "percentage": 85}]'::jsonb, 'Docker installed', 'docker version command succeeds', 'Forgetting to start Docker application after restart', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/67788960/error-during-connect-this-error-may-indicate-that-the-docker-daemon-is-not-runn', 'admin:1764193747'),

('Error while fetching server API version: Connection aborted FileNotFoundError', 'docker', 'HIGH', '[{"solution": "Ensure docker daemon is running: systemctl status docker && systemctl start docker", "percentage": 92}, {"solution": "Check docker socket permissions: sudo chmod 666 /var/run/docker.sock", "percentage": 88}]'::jsonb, 'Docker daemon installed', 'docker version outputs correctly', 'Socket file may be corrupted or inaccessible', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/64952238/docker-errors-dockerexception-error-while-fetching-server-api-version', 'admin:1764193747'),

('ADD failed: stat /path/service: no such file or directory', 'docker', 'MEDIUM', '[{"solution": "Verify file/directory exists in build context (same directory as Dockerfile): ls service", "percentage": 91}, {"solution": "Check .dockerignore file - it may be excluding required files", "percentage": 87}, {"solution": "Ensure proper relative paths in ADD/COPY instructions", "percentage": 85}]'::jsonb, 'Dockerfile in correct location', 'docker build completes successfully', 'Files not in build context, .dockerignore misconfiguration', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/48977751/error-on-building-dockerfile-to-image', 'admin:1764193747'),

('Error response from daemon: Container is not running (cannot exec)', 'docker', 'HIGH', '[{"solution": "Start container first with: docker start <container-id>", "percentage": 94}, {"solution": "Keep container running with -i -t flags or --detach mode", "percentage": 90}, {"solution": "Run exec on a running container, not a stopped one", "percentage": 92}]'::jsonb, 'Container exists and has exited', 'docker ps shows container as Up', 'Container exits immediately after start due to no foreground process', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/29599632/container-is-not-running', 'admin:1764193747'),

('Permission denied on accessing host directory mounted as volume', 'docker', 'HIGH', '[{"solution": "Mount volume with SELinux label: -v /path:/container:z (relabel context)", "percentage": 93}, {"solution": "Use uppercase Z for unique label per container: -v /path:/container:Z", "percentage": 88}, {"solution": "Disable SELinux temporarily: su -c setenforce 0", "percentage": 75}]'::jsonb, 'SELinux/AppArmor enabled on host', 'ls -al shows no Permission denied', 'SELinux context mismatch between host and container', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker', 'admin:1764193747'),

('EACCES: permission denied on npm operations in mounted volume', 'docker', 'MEDIUM', '[{"solution": "Add :z flag to volume mount in docker-compose: volumes: ./:/app:z", "percentage": 90}, {"solution": "Update docker-compose to version 2+ for better SELinux handling", "percentage": 85}, {"solution": "Run container as correct user with -u flag: docker run -u $(id -u):$(id -g)", "percentage": 82}]'::jsonb, 'Docker Compose file configured', 'npm install runs without permission errors', 'File ownership mismatch between host (uid 1000) and container (root)', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/44139279/docker-mounting-volume-with-permission-denied', 'admin:1764193747'),

('Connection refused when accessing container port from host', 'docker', 'HIGH', '[{"solution": "Publish ports with -p flag: docker run -it -p 8080:8080 image", "percentage": 96}, {"solution": "Use -P (uppercase) for random port mapping to exposed ports", "percentage": 88}, {"solution": "Check docker-machine ip on Docker Toolkit: docker-machine ip default", "percentage": 85}]'::jsonb, 'Port exposed in Dockerfile', 'curl localhost:port succeeds inside container', 'Port not published to host (-p flag missing), Docker Toolbox IP confusion', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/36813690/connection-refused-on-docker-container', 'admin:1764193747'),

('Connection refused between containers in docker-compose', 'docker', 'HIGH', '[{"solution": "Use container service name instead of localhost: mongodb://service-name:27017", "percentage": 94}, {"solution": "Define explicit network in docker-compose with networks section", "percentage": 91}, {"solution": "Add depends_on in compose file to ensure correct startup order", "percentage": 88}]'::jsonb, 'Docker Compose file with multiple services', 'Service accessible by name from other containers', 'Using localhost instead of container name, no explicit network defined', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/55673786/connection-refused-between-containers', 'admin:1764193747'),

('Docker logs not visible when running container in daemon mode (-d flag)', 'docker', 'MEDIUM', '[{"solution": "View logs with: docker-compose logs or docker-compose logs -f for follow", "percentage": 95}, {"solution": "Filter specific errors with: docker-compose logs | grep error", "percentage": 92}, {"solution": "Run without -d flag during development to see output directly", "percentage": 88}]'::jsonb, 'Container running in detached mode', 'Error logs appear in docker-compose logs output', 'Expecting synchronous output with detached mode', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/56009180/how-to-see-error-logs-when-docker-compose-fails', 'admin:1764193747'),

('Cannot connect to other containers using localhost or 127.0.0.1', 'docker', 'HIGH', '[{"solution": "Use internal container ports, not exposed ports: service-name:8080 not 0.0.0.0:8080", "percentage": 94}, {"solution": "Create explicit bridge network: docker network create and use --net flag", "percentage": 92}, {"solution": "Verify containers on same network: docker network inspect network-name", "percentage": 90}]'::jsonb, 'Multiple containers need to communicate', 'container-to-container network traffic succeeds', 'Using exposed port mappings instead of internal ports, containers on different networks', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/50347169/docker-connection-from-inside-the-container-to-localhostport-refused', 'admin:1764193747');
