-- Playwright Troubleshooting - Official Docs Mining
-- Source: playwright.dev/docs/troubleshooting
-- Mined: 2025-11-25

INSERT INTO knowledge_entries (
    query, category, hit_frequency, solutions, prerequisites, success_indicators,
    common_pitfalls, success_rate, claude_version, last_verified, source_url
) VALUES (
    'Error: Failed to launch browser',
    'playwright',
    'HIGH',
    $$[{"solution": "Set DEBUG environment variable to pw:browser for detailed launch diagnostics", "percentage": 85, "note": "Helps identify missing dependencies or configuration issues", "command": "DEBUG=pw:browser npx playwright test"}]$$::jsonb,
    'Playwright installed, browser binaries available',
    'Browser launches successfully without error logs',
    'Not checking system dependencies, ignoring proxy/firewall issues',
    0.85,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/ci'
),
(
    'Browsers fail to run in CI environments - missing system dependencies',
    'playwright',
    'CRITICAL',
    $$[{"solution": "Install OS dependencies alongside browser binaries using --with-deps flag", "percentage": 95, "note": "This installs both browsers and required system libraries", "command": "npx playwright install --with-deps"}]$$::jsonb,
    'npx and Node.js installed, Playwright package in project',
    'All tests pass in CI environment, no browser launch errors',
    'Installing only browsers without OS dependencies, not running with --with-deps',
    0.95,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/ci'
),
(
    'Timeout waiting for element to appear - TimeoutError',
    'playwright',
    'HIGH',
    $$[{"solution": "Increase timeout value in click or wait operations", "percentage": 60, "note": "Default timeout may be too short for slow networks", "command": "await page.locator(''text=Foo'').click({ timeout: 5000 })"}, {"solution": "Use proper wait strategies like locator.waitFor() before interaction", "percentage": 75, "note": "Ensures element is ready before attempting action"}, {"solution": "Verify selector matches intended element", "percentage": 80, "note": "Incorrect locators cause infinite timeouts"}]$$::jsonb,
    'Page loaded, element exists in DOM',
    'Element interaction completes without TimeoutError exception',
    'Using hardcoded sleep times instead of waits, overly complex selectors, not validating locators',
    0.75,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/api/class-timeouterror'
),
(
    'Self-signed certificate in certificate chain - proxy/firewall blocks downloads',
    'playwright',
    'MEDIUM',
    $$[{"solution": "Configure custom CA certificate using NODE_EXTRA_CA_CERTS environment variable", "percentage": 90, "note": "Points to internal proxy''s root certificate", "command": "NODE_EXTRA_CA_CERTS=/path/to/cert.pem npx playwright install"}]$$::jsonb,
    'Company proxy with custom CA configured, certificate path known',
    'Browser installation succeeds through proxy',
    'Not setting environment variable before installation, using wrong certificate path',
    0.90,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/browsers'
),
(
    'HTTPS_PROXY blocked connection during browser installation',
    'playwright',
    'MEDIUM',
    $$[{"solution": "Set HTTPS_PROXY environment variable before running playwright install", "percentage": 88, "note": "Tells Playwright to route through corporate proxy", "command": "HTTPS_PROXY=http://proxy.company.com:8080 npx playwright install"}]$$::jsonb,
    'Proxy server details known and accessible',
    'Browser binaries download successfully',
    'Not setting proxy before installation, forgetting to include port number',
    0.88,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/browsers'
),
(
    'Slow network connection - browser installation timeout',
    'playwright',
    'MEDIUM',
    $$[{"solution": "Increase download timeout using PLAYWRIGHT_DOWNLOAD_CONNECTION_TIMEOUT in milliseconds", "percentage": 85, "note": "Default timeout may be too short for slow connections", "command": "PLAYWRIGHT_DOWNLOAD_CONNECTION_TIMEOUT=120000 npx playwright install"}]$$::jsonb,
    'Slow network connection identified, timeout threshold known',
    'Browser binaries complete download without timeout',
    'Using very high timeout values that mask actual network issues, not checking actual connection speed',
    0.85,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/browsers'
),
(
    'Tests are flaky and unstable - parallelism conflicts in CI',
    'playwright',
    'HIGH',
    $$[{"solution": "Disable parallelism by setting workers to 1 in playwright.config.ts for CI environments", "percentage": 90, "note": "Prevents resource conflicts and race conditions", "command": "webServer: { command: ''npm run start'', port: 3000, workers: 1 }"}]$$::jsonb,
    'Tests running in CI environment, playwright.config.ts accessible',
    'Tests pass consistently without intermittent failures',
    'Assuming parallelism is always optimal, not recognizing CI resource constraints',
    0.90,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/ci'
),
(
    'Headed mode fails on Linux CI agents - no display server',
    'playwright',
    'MEDIUM',
    $$[{"solution": "Wrap test commands with xvfb-run to provide virtual display", "percentage": 92, "note": "xvfb-run creates virtual X11 display for headless Linux systems", "command": "xvfb-run npx playwright test --headed"}]$$::jsonb,
    'xvfb-run installed on Linux system, heading mode required for tests',
    'Tests execute successfully in headed mode on Linux',
    'Assuming headed mode works on all systems, not installing xvfb',
    0.92,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/ci'
),
(
    'Brittle selectors break when DOM changes - element selection failures',
    'playwright',
    'HIGH',
    $$[{"solution": "Use role-based locators prioritizing user-visible behavior", "percentage": 85, "note": "getByRole() is more resilient to styling changes", "command": "page.getByRole(''button'', { name: ''Submit'' })"}, {"solution": "Use test IDs instead of CSS classes for stable selection", "percentage": 88, "note": "Test IDs are less likely to be removed by design changes"}, {"solution": "Chain and filter locators to target specific elements within regions", "percentage": 80, "note": "Narrows scope to avoid false matches"}]$$::jsonb,
    'Page structure known, elements have semantic roles or test IDs',
    'Locators remain valid after DOM refactoring',
    'Relying on CSS classes or complex XPath, not validating locators after changes',
    0.84,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/best-practices'
),
(
    'Manual assertions fail without waiting - expect().not.toBeTruthy() race condition',
    'playwright',
    'HIGH',
    $$[{"solution": "Use web-first assertions that automatically wait and retry", "percentage": 92, "note": "toBeVisible(), toBeEnabled() retry until timeout", "command": "await expect(page.locator(''button'')).toBeVisible()"}, {"solution": "Avoid checking async results immediately with await", "percentage": 85, "note": "Assertions without retry will fail on race conditions"}]$$::jsonb,
    'Elements exist in page, assertions library supports web-first matchers',
    'Assertions pass consistently without race condition failures',
    'Using await with boolean checks like expect(await element.isVisible()).toBe(true)',
    0.89,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/best-practices'
),
(
    'Firefox version incompatibility - Playwright not working with branded Firefox',
    'playwright',
    'MEDIUM',
    $$[{"solution": "Use official Firefox Stable channel - Playwright includes patches for specific build", "percentage": 95, "note": "Branded Firefox versions lack necessary Playwright patches", "command": "npx playwright install firefox"}]$$::jsonb,
    'Firefox browser available, testing against Firefox needed',
    'Tests execute successfully with official Firefox builds',
    'Installing branded Firefox, using user-installed Firefox instead of playwright version',
    0.95,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/browsers'
),
(
    'WebKit media codec errors - codecs unavailable on Linux',
    'playwright',
    'MEDIUM',
    $$[{"solution": "Run WebKit tests on macOS for optimal Safari-like testing", "percentage": 88, "note": "Media codec availability varies across operating systems", "command": "npx playwright test --project=webkit"}]$$::jsonb,
    'macOS system available, WebKit testing required',
    'WebKit tests execute without codec errors on macOS',
    'Running WebKit tests on Linux expecting full codec support, not accounting for OS differences',
    0.88,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/browsers'
),
(
    'Chromium headless mode behaves differently from Chrome/Edge new headless',
    'playwright',
    'MEDIUM',
    $$[{"solution": "Test against both headless modes - Playwright shell vs Chrome new headless differ in behavior", "percentage": 75, "note": "Google Chrome and Edge use newer headless implementation closer to headed mode", "command": "npx playwright test --project=chromium"}]$$::jsonb,
    'Understanding of headless mode differences, testing multiple browsers',
    'Tests pass consistently across headless implementations',
    'Assuming all headless modes behave identically, not testing cross-browser',
    0.75,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/browsers'
),
(
    'Non-isolated tests fail due to shared state between test runs',
    'playwright',
    'HIGH',
    $$[{"solution": "Use beforeEach/afterEach hooks to reset state between tests", "percentage": 88, "note": "Ensures each test starts fresh"}, {"solution": "Setup separate storage state per test using page.context()", "percentage": 90, "note": "Prevents cross-test contamination of cookies/localStorage"}, {"solution": "Use setup projects for test isolation", "percentage": 85, "note": "Creates isolated environments for each test"}]$$::jsonb,
    'Test framework configured, browser context management understood',
    'Tests pass independently without requiring specific execution order',
    'Assuming tests are isolated, sharing browser contexts between tests, not using beforeEach',
    0.88,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/best-practices'
),
(
    'Tests fail due to mocking third-party external API dependencies',
    'playwright',
    'HIGH',
    $$[{"solution": "Mock external API responses using Playwright Network API route interception", "percentage": 90, "note": "Replace external calls with deterministic responses", "command": "await page.route(''https://api.external.com/**'', route => route.abort())"}, {"solution": "Use route.fulfill() to return test data instead of hitting real APIs", "percentage": 92, "note": "Faster, more reliable tests"}]$$::jsonb,
    'External API endpoints identified, mock data available',
    'Tests pass without external API calls, execution time reduced',
    'Testing against live external APIs, relying on unpredictable third-party services',
    0.91,
    'sonnet-4',
    NOW(),
    'https://playwright.dev/docs/best-practices'
);
