INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERR_FR_TOO_MANY_REDIRECTS: Maximum number of redirects exceeded', 'http', 'HIGH', '[{"solution": "Set maxRedirects option to a higher value: axios.get(url, {maxRedirects: 30})", "percentage": 85}, {"solution": "Check for redirect loops in the target URL using a browser first", "percentage": 75}, {"solution": "Use a custom http/https agent with proper cookie jar support for complex scenarios", "percentage": 60}]'::jsonb, 'Axios instance, valid URL with redirects', 'Request succeeds and response is received', 'Not checking the actual redirect chain, too high redirect limit causing infinite loops', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/76587038/node-js-axios-get-request-error-code-err-fr-too-many-redirects', 'admin:1764225721'),

('ERR_BAD_OPTION_VALUE: Options must be an object', 'config', 'MEDIUM', '[{"solution": "Ensure config object is valid JSON-like object, not a string", "percentage": 90}, {"solution": "Check that paramsSerializer is configured correctly in axios.create()", "percentage": 85}]'::jsonb, 'Axios >= 1.0.0, valid config options', 'Request completes without validation errors', 'Passing strings instead of objects, incorrect config property types', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/75064305/axioserror-options-must-be-an-object-err-bad-option-value', 'admin:1764225721'),

('ERR_NETWORK: Network Error - request failed with no response', 'network', 'CRITICAL', '[{"solution": "Check if backend server is running and accessible: curl http://localhost:3000/", "percentage": 95}, {"solution": "Verify CORS is properly configured on backend server", "percentage": 90}, {"solution": "Ensure URL has proper http:// or https:// protocol prefix", "percentage": 88}, {"solution": "Check firewall/proxy settings blocking requests", "percentage": 70}]'::jsonb, 'Backend server running, network connectivity', 'Request reaches backend and returns response', 'Missing http:// prefix in URL, wrong port, firewall blocking, disabled CORS', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/74502482/axioserror-message-network-error-name-axioserror-code-err-network-c', 'admin:1764225721'),

('ECONNABORTED: Request timeout - socket hang up during request', 'network', 'HIGH', '[{"solution": "Increase timeout value: axios.defaults.timeout = 30000", "percentage": 92}, {"solution": "Check if error.code === ''ECONNABORTED'' to identify timeout specifically", "percentage": 95}, {"solution": "Implement retry logic with exponential backoff for timeout errors", "percentage": 80}]'::jsonb, 'Axios instance with timeout configured', 'Request completes within timeout window', 'Using timeout value too small for slow networks, not retrying on timeout', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/50619928/get-notified-after-axios-timeout', 'admin:1764225721'),

('ETIMEDOUT: Connection timeout - server took too long to respond', 'network', 'HIGH', '[{"solution": "Increase timeout configuration: {timeout: 60000} for 60 seconds", "percentage": 90}, {"solution": "Implement global timeout handler in interceptors", "percentage": 85}, {"solution": "Add timeout error message to user feedback", "percentage": 80}]'::jsonb, 'Network connectivity, axios instance', 'Request completes within expected timeframe', 'Timeout too aggressive, not logging timeout errors, no user feedback', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/61762978/best-way-of-globally-handling-requests-timeout-errors-with-axios-and-show-alert', 'admin:1764225721'),

('validateStatus: Handle non-2xx status codes as success', 'config', 'MEDIUM', '[{"solution": "Set validateStatus to custom function: validateStatus: () => true", "percentage": 95}, {"solution": "Create axios instance with validateStatus defaults: axios.create({validateStatus: () => true})", "percentage": 92}, {"solution": "Use validateStatus: (status) => status >= 200 && status < 500 for custom ranges", "percentage": 88}]'::jsonb, 'Axios >= 0.16.0, need to handle error status codes', 'Non-2xx responses treated as successful', 'Using false instead of function, forgetting to return boolean value', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/77700540/configure-axios-configure-the-validatestatus-function-once-per-project', 'admin:1764225721'),

('error.response: Access status code from error object', 'error-handling', 'HIGH', '[{"solution": "Check error.response.status for HTTP status code", "percentage": 95}, {"solution": "Access error.response.data for server error message", "percentage": 94}, {"solution": "Use error.response.headers to read response headers", "percentage": 88}]'::jsonb, 'Axios caught error with server response', 'Error details accessible in catch block', 'Assuming error.response exists without null check, not handling null response', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/39153080/how-can-i-get-the-status-code-from-an-http-error-in-axios', 'admin:1764225721'),

('error.request: Request made but no response from server', 'error-handling', 'MEDIUM', '[{"solution": "Check if error.request exists: if (error.request && !error.response)", "percentage": 95}, {"solution": "Handle network errors separately from response errors", "percentage": 90}, {"solution": "Log error.request for debugging connection issues", "percentage": 85}]'::jsonb, 'Axios caught error, request was sent', 'Distinguish between network errors and response errors', 'Not checking error.request existence, confusing with error.response', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/49967779/axios-handling-errors', 'admin:1764225721'),

('error.config: Access original request configuration in error', 'error-handling', 'MEDIUM', '[{"solution": "Get request method: error.config.method or error.response.config.method", "percentage": 92}, {"solution": "Retry request using error.config: axios(error.config)", "percentage": 90}, {"solution": "Access original URL with error.config.url", "percentage": 95}]'::jsonb, 'Axios caught error, need to retry or debug', 'Request method and URL accessible for retry logic', 'Not preserving config in error object, losing retry information', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/74050992/how-to-use-axios-response-error-config-to-retry-the-request', 'admin:1764225721'),

('ERR_BAD_RESPONSE: Invalid response format from server', 'http', 'MEDIUM', '[{"solution": "Use validateStatus to accept 500+ errors: validateStatus: (status) => status >= 200", "percentage": 88}, {"solution": "Check server logs for application errors causing bad responses", "percentage": 85}, {"solution": "Verify response Content-Type header matches data format", "percentage": 80}]'::jsonb, 'Axios request to server, server returning errors', 'Request completes with status code', 'Ignoring server status codes, not checking server logs', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/73934393/axioserror-on-post-request-is-giving-err-bad-response-on-my-reactjs-code', 'admin:1764225721'),

('ERR_BAD_REQUEST: Bad request configuration or payload', 'config', 'MEDIUM', '[{"solution": "Validate request payload matches API schema", "percentage": 90}, {"solution": "Check Content-Type header matches payload format", "percentage": 92}, {"solution": "Use proper FormData for multipart/form-data requests", "percentage": 85}]'::jsonb, 'Request configuration, valid payload format', 'Server accepts request and returns valid response', 'Incorrect payload format, wrong Content-Type, malformed JSON', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/72181195/axios-showing-error-err-bad-request-while-sending-formdata-using-react-native', 'admin:1764225721'),

('ERR_CANCELED: Request canceled - AbortController or CancelToken used', 'cancel', 'MEDIUM', '[{"solution": "Check if error is cancellation: axios.isCancel(error)", "percentage": 95}, {"solution": "Use AbortController in modern browsers: const controller = new AbortController()", "percentage": 90}, {"solution": "Implement request cancellation on component unmount in React", "percentage": 88}]'::jsonb, 'Axios with AbortController or CancelToken', 'Cancellation handled gracefully, no unhandled errors', 'Not checking axios.isCancel(), treating cancellation as error', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/73140563/axios-throwing-cancelederror-with-abort-controller-in-react', 'admin:1764225721'),

('ECONNREFUSED: Connection refused - server not listening on port', 'network', 'HIGH', '[{"solution": "Check if server is running on correct host and port", "percentage": 95}, {"solution": "Verify baseURL is correct: curl http://localhost:8000", "percentage": 93}, {"solution": "Check firewall is not blocking the port", "percentage": 85}]'::jsonb, 'Network connectivity, correct host/port', 'Server accepts connection and responds', 'Wrong port number, server not started, firewall blocking', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/73685590/axios-gives-axioserror-connect-econnrefused-0-0-0-0443-how-to-fix-this', 'admin:1764225721'),

('ENOTFOUND: DNS lookup failed - hostname cannot be resolved', 'network', 'HIGH', '[{"solution": "Check hostname spelling and DNS resolution: nslookup example.com", "percentage": 94}, {"solution": "Verify internet connectivity and DNS settings", "percentage": 90}, {"solution": "Check if domain exists and is accessible", "percentage": 92}]'::jsonb, 'Network connectivity, valid hostname', 'DNS resolves hostname to IP address', 'Typo in hostname, invalid domain, no internet connection', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/67914674/error-getaddrinfo-enotfound-3128-when-post-data-using-axios-in-node-js', 'admin:1764225721'),

('isAxiosError: Type guard to check if error is AxiosError', 'error-handling', 'MEDIUM', '[{"solution": "Use axios.isAxiosError(error) to type-guard error", "percentage": 95}, {"solution": "Import from axios: import { isAxiosError } from ''axios''", "percentage": 95}, {"solution": "Available on axios object: axios.isAxiosError(), not on instance", "percentage": 92}]'::jsonb, 'Axios error object, TypeScript or type safety needed', 'Error properly typed as AxiosError', 'Calling isAxiosError on instance instead of axios object, using as type without check', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/74078008/axiosinstance-and-isaxioserror', 'admin:1764225721'),

('AxiosError generic type: Type response.data in TypeScript', 'types', 'MEDIUM', '[{"solution": "Use generic: AxiosError<{status: string}> to type response data", "percentage": 95}, {"solution": "Type both request and response: AxiosError<ResponseType, RequestType>", "percentage": 92}, {"solution": "Use type annotation: (error: AxiosError<ErrorResponse>)", "percentage": 94}]'::jsonb, 'TypeScript, axios >= 0.18.0', 'IDE provides autocomplete for error.response.data properties', 'Using ''any'' type, not providing generic parameter, assuming object structure', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/73134233/what-type-of-axios-error-i-need-for-getting-error-response-data-status/73136164', 'admin:1764225721'),

('maxRedirects: Limit or increase number of followed redirects', 'config', 'LOW', '[{"solution": "Set maxRedirects to higher value: axios.get(url, {maxRedirects: 30})", "percentage": 92}, {"solution": "Set to 0 to not follow redirects: {maxRedirects: 0}", "percentage": 90}, {"solution": "Browser axios has maxRedirects: 5 as default", "percentage": 88}]'::jsonb, 'Axios making request to URL with redirects', 'Request follows correct number of redirects', 'Setting maxRedirects too low, not checking redirect chain', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/65473222/how-to-increase-the-limit-of-redirects-with-axios', 'admin:1764225721'),

('transformResponse: Transform response data with custom function', 'transform', 'MEDIUM', '[{"solution": "Concat with defaults: axios.defaults.transformResponse.concat(customFn)", "percentage": 95}, {"solution": "Return parsed JSON: transformResponse: [(data) => JSON.parse(data)]", "percentage": 92}, {"solution": "First function parses JSON, second transforms data", "percentage": 90}]'::jsonb, 'Axios >= 1.0.0, need data transformation', 'Response data transformed correctly', 'Overriding default transformResponse without JSON.parse, not returning data', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77656066/transformresponse-in-axios-breaks-the-response', 'admin:1764225721'),

('HTTP 403 Forbidden: Authorization header missing or invalid', 'http', 'HIGH', '[{"solution": "Add Bearer token to headers: Authorization: `Bearer ${token}`", "percentage": 95}, {"solution": "Check token is not expired or revoked", "percentage": 92}, {"solution": "Verify token format matches API requirements", "percentage": 90}]'::jsonb, 'Valid access token, correct authorization header format', 'Server accepts request and returns 200+ status', 'Typo in Bearer format (e.g., Bearer +), expired token, wrong token format', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/55215938/axios-get-request-response-with-403-error-forbidden', 'admin:1764225721'),

('HTTP 401 Unauthorized: Token expired or missing', 'http', 'CRITICAL', '[{"solution": "Refresh token and retry request in interceptor", "percentage": 93}, {"solution": "Check if error.response.status === 401 in interceptor", "percentage": 95}, {"solution": "Store refresh token and implement token refresh flow", "percentage": 88}]'::jsonb, 'Refresh token endpoint, token management', 'Request retries with fresh token on 401', 'Not implementing refresh token logic, ignoring 401 responses', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/47216452/how-to-handle-401-authentication-error-in-axios-and-react', 'admin:1764225721'),

('maxBodyLength: Request body exceeds size limit', 'config', 'MEDIUM', '[{"solution": "Increase maxBodyLength: axios({..., maxBodyLength: Infinity})", "percentage": 95}, {"solution": "Set maxContentLength: Infinity for responses", "percentage": 94}, {"solution": "Use both together for file uploads: maxBodyLength: Infinity, maxContentLength: Infinity", "percentage": 96}]'::jsonb, 'Large file upload, axios >= 0.16.0', 'Large files upload successfully', 'Using finite limits for large files, not setting on axios instance', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/58655532/increasing-maxcontentlength-and-maxbodylength-in-axios', 'admin:1764225721'),

('CORS Error: No Access-Control-Allow-Origin header', 'http', 'CRITICAL', '[{"solution": "Enable CORS on backend: app.use(cors())", "percentage": 97}, {"solution": "Add CORS headers on server, not on axios client", "percentage": 98}, {"solution": "Configure proxy in development: devServer: {proxy: url}", "percentage": 90}]'::jsonb, 'Backend server running, cross-origin request', 'Request succeeds without CORS error', 'Setting CORS headers on client (wrong), missing backend CORS config', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/50949594/axios-having-cors-issue', 'admin:1764225721'),

('Socket Hang Up: Connection closed unexpectedly by server', 'network', 'HIGH', '[{"solution": "Add res.send() or res.json() to Express routes to properly close connection", "percentage": 98}, {"solution": "Check server is returning response for all routes", "percentage": 96}, {"solution": "Set proper timeout if server processing takes long", "percentage": 85}]'::jsonb, 'Backend server with proper response handling', 'Request receives complete response', 'Missing response send in route handler, server timeout, unhandled promise', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/64888841/socket-hang-up-when-using-axios', 'admin:1764225721'),

('Request Aborted: Browser canceled request mid-flight', 'cancel', 'MEDIUM', '[{"solution": "Prevent default form submit: e.preventDefault()", "percentage": 96}, {"solution": "Use button type ''button'' not ''submit'' for API calls", "percentage": 94}, {"solution": "Implement AbortController to intentionally cancel requests", "percentage": 88}]'::jsonb, 'Form submission or request cancellation', 'Request completes without cancellation', 'Using type=''submit'' on button triggering form submit, not preventing default', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/61522494/react-axios-error-request-aborted-for-delete-request-in-firefox-but-not-in-chro', 'admin:1764225721'),

('Custom Adapter: Use custom request adapter instead of HTTP', 'config', 'LOW', '[{"solution": "Create adapter: const customAdapter = (config) => new Promise(...)", "percentage": 85}, {"solution": "Pass to axios.create(): {adapter: customAdapter}", "percentage": 90}, {"solution": "Use for modifying responses: settle(resolve, reject, response)", "percentage": 88}]'::jsonb, 'Custom response handling, axios >= 0.16.0', 'Custom adapter properly handles request/response', 'Using internal axios functions incorrectly, not handling promises in adapter', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/59401146/how-can-i-change-the-result-status-in-axios-with-an-adapter', 'admin:1764225721'),

('Deprecated: axios.all() and axios.spread() - use Promise.all()', 'deprecation', 'LOW', '[{"solution": "Replace axios.all() with Promise.all()", "percentage": 100}, {"solution": "Replace axios.spread(cb) with .then(([res1, res2]) => cb(res1, res2))", "percentage": 100}]'::jsonb, 'Axios >= 0.18.0, making concurrent requests', 'Using Promise.all for concurrent requests', 'Using deprecated axios.all(), not updating to Promise.all()', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/63002500/axios-deprecated-concurrent-requests', 'admin:1764225721'),

('Response Interceptor: Handle errors globally across all requests', 'interceptors', 'HIGH', '[{"solution": "Add error interceptor: axios.interceptors.response.use(resp, error => ...)", "percentage": 95}, {"solution": "Return Promise.reject to allow local catch blocks", "percentage": 92}, {"solution": "Check error.response?.status in global error handler", "percentage": 94}]'::jsonb, 'Axios instance, need global error handling', 'All errors caught and handled consistently', 'Not returning Promise.reject, swallowing errors in interceptor', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/58386395/how-to-properly-handle-axios-errors-and-how-to-get-detailed-error-descriptions', 'admin:1764225721'),

('HTTP 500 Internal Server Error: Server-side error response', 'http', 'MEDIUM', '[{"solution": "Use validateStatus to capture 500: validateStatus: (status) => status >= 200", "percentage": 90}, {"solution": "Check server logs for root cause of 500 error", "percentage": 95}, {"solution": "Implement retry logic for transient 500 errors", "percentage": 80}]'::jsonb, 'Server error logging, error handling strategy', 'Server error properly logged and handled', 'Ignoring error response, not checking server logs', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/50950011/axios-post-request-fails-with-error-status-code-500-internal-server-error', 'admin:1764225721'),

('TypeError TypeScript: Catch error as unknown not AxiosError', 'types', 'MEDIUM', '[{"solution": "Catch as unknown: catch (error: unknown) {}", "percentage": 96}, {"solution": "Type guard with isAxiosError: if (axios.isAxiosError(error))", "percentage": 95}, {"solution": "Cast with ''as'': (error as AxiosError).response?.status", "percentage": 92}]'::jsonb, 'TypeScript with strict null checks', 'Error properly typed without type errors', 'Directly typing as AxiosError without type guard, ignoring unknown type', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/69264472/axios-error-typescript-annotation-must-be-any-or-unknown-if', 'admin:1764225721'),

('Request Config Validation: Ensure valid config before sending', 'config', 'LOW', '[{"solution": "Validate URL format before creating request", "percentage": 90}, {"solution": "Check all required headers are present", "percentage": 88}, {"solution": "Validate data/params match API schema", "percentage": 85}]'::jsonb, 'Request configuration, API schema knowledge', 'API accepts request and validates data', 'Missing required fields, invalid URL format, type mismatches', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/39153080/how-can-i-get-the-status-code-from-an-http-error-in-axios', 'admin:1764225721');
