INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Cannot find name ''Bun'' - TypeScript error when using Bun singleton', 'bun', 'HIGH', '[{"solution": "Install bun-types as devDependency: bun add -d bun-types", "percentage": 85}, {"solution": "Add types to tsconfig.json compilerOptions: \"types\": [\"bun-types\"]", "percentage": 85}, {"solution": "Restart TypeScript server in VS Code with Ctrl+Shift+P", "percentage": 95}]'::jsonb, 'Bun installed, VS Code setup', 'Bun singleton recognized, no .ts(2304) errors', 'Not restarting TS server, using @types/bun instead of bun-types', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77339206/bun-in-vs-code-error-cannot-find-name-bun-when-using-the-bun-singleton', 'admin:1764197642'),

('error: Failed due to error: bunsh: No such file or directory - bun run scripts fail', 'bun', 'HIGH', '[{"solution": "Check if project folder contains non-ASCII characters (Chinese, special chars) and rename to English", "percentage": 80}, {"solution": "Try running the same script with npm to verify it works", "percentage": 75}, {"solution": "Verify bun binary is in PATH and executable", "percentage": 70}]'::jsonb, 'Bun installed, package.json with scripts', 'bun dev/scripts execute without bunsh errors', 'Folder path contains non-English characters, missing bun installation', 0.75, 'haiku', NOW(), 'https://stackoverflow.com/questions/78324016/error-failed-due-to-error-bunsh-no-such-file-or-directory-running-bun-dev', 'admin:1764197642'),

('Command ''bun'' not found after installation on WSL - bun not in PATH', 'bun', 'MEDIUM', '[{"solution": "After installing bun, edit ~/.bashrc to add: export BUN_INSTALL=\"$HOME/.bun\" and export PATH=\"$BUN_INSTALL/bin:$PATH\"", "percentage": 90}, {"solution": "Source the bashrc file: source ~/.bashrc or restart WSL completely", "percentage": 95}, {"solution": "Ensure you are using WSL2, not WSL1 (Bun doesn''t run on WSL1)", "percentage": 60}]'::jsonb, 'WSL2 environment, bun install script completed', 'bun --version returns version number', 'Using WSL1, not sourcing bashrc file, missing PATH export', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/72937512/bun-not-found-error-in-windows-with-wsl', 'admin:1764197642'),

('error: could not find bin metadata file - Bun failed to remap bin to proper location', 'bun', 'MEDIUM', '[{"solution": "Run bun install --force to properly extract and link binaries in node_modules", "percentage": 88}, {"solution": "Clear bun cache: delete C:\\Users\\<username>\\AppData\\Local\\bun on Windows", "percentage": 75}, {"solution": "Use bunx --bun shadcn@latest init instead of npx shadcn init when working with shadcn", "percentage": 80}]'::jsonb, 'Bun and npm/package managers installed', 'Dependencies install without EBUSY or bin metadata errors', 'Not clearing cache before retry, running scripts without --force flag', 0.79, 'haiku', NOW(), 'https://stackoverflow.com/questions/79290306/issues-setting-up-shadcn-with-next-js-bun-cache-errors-and-installation-failure', 'admin:1764197642'),

('Interpreter bun is NOT AVAILABLE in PATH - pm2 cannot find bun', 'bun', 'MEDIUM', '[{"solution": "Check pm2 version - if 5.3.1, downgrade to 5.3.0 which has known bun compatibility issues", "percentage": 85}, {"solution": "Verify bun executable is in system PATH: which bun", "percentage": 80}, {"solution": "Install bun globally and ensure it''s accessible from PATH before running pm2", "percentage": 75}]'::jsonb, 'pm2 and bun both installed, package.json configured', 'pm2 start succeeds with bun interpreter', 'pm2 version 5.3.1 has compatibility bug, bun not in system PATH', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/77887644/error-when-using-pm2-interpreter-bun-is-not-available-in-path', 'admin:1764197642'),

('Error: only absolute urls are supported - Next.js 15 build with bun run build', 'bun', 'MEDIUM', '[{"solution": "Update params and searchParams in Next.js 15 to be asynchronous: type TagPageProps = { params: Promise<{tag: string}> }", "percentage": 92}, {"solution": "Await params in generateMetadata: const { tag } = await params", "percentage": 92}, {"solution": "Make page component async: export default async function TagPage({ params }: TagPageProps)", "percentage": 92}]'::jsonb, 'Next.js 15 project, bun as package manager', 'bun run build completes without errors', 'Not updating params to Promise type, not awaiting params in functions', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/79373101/error-during-bun-run-build-after-upgrading-to-next-js-15', 'admin:1764197642'),

('Cannot find name ''Bun'' .ts(2304) - tsconfig not recognizing bun types', 'bun', 'HIGH', '[{"solution": "Install @types/bun package: bun add -D @types/bun", "percentage": 80}, {"solution": "Update tsconfig.json with: \"types\": [\"bun-types\"] in compilerOptions", "percentage": 90}, {"solution": "Reload VS Code editor after installing types and updating tsconfig", "percentage": 85}]'::jsonb, 'VS Code IDE, bun initialized project', 'IDE shows Bun type definitions and autocompletion', 'Using @types/bun instead of bun-types in tsconfig, not reloading editor', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/72902409/how-do-you-set-up-types-with-bun', 'admin:1764197642');
