-- Mining: NPM Errors
-- Source: Stack Overflow
-- Miner: Haiku 4.5
-- Timestamp: 2025-11-27

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('npm ERR code ELIFECYCLE npm run server failed', 'tooling-npm', 'HIGH', '[{"solution": "Run npm cache clean --force, delete node_modules and package-lock.json, then npm install", "percentage": 92}, {"solution": "Delete node_modules folder and reinstall dependencies", "percentage": 85}, {"solution": "Check if required dependencies are installed globally", "percentage": 78}]'::jsonb, 'npm, Node.js', 'npm start succeeds', 'Not clearing cache before reinstalling', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/22445371/npm-install-error-from-the-terminal', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ENOENT no such file or directory open package.json', 'tooling-npm', 'HIGH', '[{"solution": "Run npm init to create package.json file", "percentage": 95}, {"solution": "Check if you are in the project root directory", "percentage": 90}, {"solution": "Delete node_modules and run npm install again", "percentage": 82}]'::jsonb, 'npm, Node.js', 'package.json exists', 'Running from wrong directory', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/43260643/how-to-resolve-node-js-error-enoent-no-such-file-or-directory', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERESOLVE unable to resolve dependency tree npm ERR', 'tooling-npm', 'HIGH', '[{"solution": "Use npm install --legacy-peer-deps flag", "percentage": 96}, {"solution": "Run npm config set legacy-peer-deps true for global setting", "percentage": 93}, {"solution": "Fix upstream dependency conflicts by updating versions", "percentage": 85}, {"solution": "Use --force flag if needed but verify compatibility", "percentage": 70}]'::jsonb, 'npm, peer dependencies', 'npm install succeeds', 'Forcing installation without fixing conflicts', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/64573177/unable-to-resolve-dependency-tree-error-when-installing-npm-packages', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EACCES permission denied access usr local lib node_modules', 'tooling-npm', 'HIGH', '[{"solution": "Run sudo chown -R $(whoami) /usr/local/lib/node_modules", "percentage": 94}, {"solution": "Use npm install -g with sudo prefixed carefully", "percentage": 85}, {"solution": "Fix npm permissions using npm config set prefix", "percentage": 88}]'::jsonb, 'npm, permissions', 'npm install succeeds', 'Using sudo without fixing ownership', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/48910876/error-eacces-permission-denied-access-usr-local-lib-node-modules', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EPERM operation not permitted unlink node_modules', 'tooling-npm', 'MEDIUM', '[{"solution": "Close all editors and terminal windows using the folder", "percentage": 91}, {"solution": "Disable antivirus temporarily if blocking file operations", "percentage": 87}, {"solution": "Delete node_modules folder manually instead of npm", "percentage": 83}]'::jsonb, 'npm, file permissions', 'npm install completes', 'Files locked by running processes', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/39293636/npm-err-error-eperm-operation-not-permitted-rename', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ECONNREFUSED connection refused npm registry', 'tooling-npm', 'HIGH', '[{"solution": "Reset npm proxy: npm config set proxy null and npm config set https-proxy null", "percentage": 93}, {"solution": "Set npm registry to http://registry.npmjs.org/", "percentage": 91}, {"solution": "Check network connectivity and firewall settings", "percentage": 82}]'::jsonb, 'npm, network', 'npm install succeeds', 'Incorrect proxy settings', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/42371380/npm-err-error-connect-econnrefused-when-trying-to-update-the-npm', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('E404 not found 404 npm package', 'tooling-npm', 'MEDIUM', '[{"solution": "Verify the package name exists on npmjs.org", "percentage": 92}, {"solution": "Clear npm cache and retry: npm cache clean --force", "percentage": 85}, {"solution": "Check npm registry setting is correct", "percentage": 88}]'::jsonb, 'npm, packages', 'Package installs successfully', 'Typo in package name', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/47520181/installing-npm-package-fails-with-404', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERR_SOCKET_TIMEOUT Socket timeout npm install', 'tooling-npm', 'HIGH', '[{"solution": "Increase timeout: npm config set fetch-retry-mintimeout 20000 and fetch-retry-maxtimeout 120000", "percentage": 94}, {"solution": "Clear npm cache: npm cache clean --force", "percentage": 89}, {"solution": "Try downgrading npm version", "percentage": 75}]'::jsonb, 'npm, network', 'npm install completes', 'Registry server timeout', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/72442682/npm-err-code-err-socket-timeout-npm-err-network-socket-timeout', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ETARGET no matching version found for package', 'tooling-npm', 'MEDIUM', '[{"solution": "Check package versions on npmjs.org and update package.json", "percentage": 93}, {"solution": "Use a lower version number that exists", "percentage": 91}, {"solution": "Remove ^ or ~ from version specifier", "percentage": 85}]'::jsonb, 'npm, versions', 'Package installs successfully', 'Requesting non-existent version', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/52039375/stuck-while-installing-packages-npm-err-notarget-no-matching-version-found-for', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('npm ERR code EINTEGRITY package-lock.json', 'tooling-npm', 'MEDIUM', '[{"solution": "Delete package-lock.json and run npm install", "percentage": 94}, {"solution": "Run npm cache clean --force then npm install", "percentage": 91}, {"solution": "Delete node_modules and package-lock.json", "percentage": 88}]'::jsonb, 'npm, integrity', 'npm install succeeds', 'Corrupted package-lock.json', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/47545940/when-i-run-npm-install-it-returns-with-err-code-eintegrity-npm-5-3-0', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('npm ERR code 1 postinstall script failed', 'tooling-npm', 'HIGH', '[{"solution": "Check the specific postinstall script error in package.json", "percentage": 85}, {"solution": "Update the failing dependency to a newer version", "percentage": 82}, {"solution": "Run with --ignore-scripts flag if safe", "percentage": 70}]'::jsonb, 'npm, scripts', 'postinstall script succeeds', 'Missing native build tools', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/67399785/how-to-solve-npm-install-error-npm-err-code-1', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('npm dependencies conflict react version mismatch', 'tooling-npm', 'HIGH', '[{"solution": "Update package.json to compatible versions", "percentage": 92}, {"solution": "Use npm install with --legacy-peer-deps", "percentage": 88}, {"solution": "Check npm error report for exact conflicts", "percentage": 85}]'::jsonb, 'npm, dependencies', 'All dependencies install correctly', 'Incompatible peer dependencies', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/76039613/how-do-i-read-npm-dependency-conflict-errors', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('npm install fails exit status 1 script error', 'tooling-npm', 'MEDIUM', '[{"solution": "Check npm-debug.log for actual error details", "percentage": 88}, {"solution": "Verify all dependencies listed in package.json exist", "percentage": 86}, {"solution": "Delete node_modules and reinstall", "percentage": 82}]'::jsonb, 'npm, debugging', 'npm install succeeds', 'Hidden error in debug log', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/40103850/npm-install-fails-with-error', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('npm cannot find module after install', 'tooling-npm', 'MEDIUM', '[{"solution": "Run npm install again to complete installation", "percentage": 90}, {"solution": "Check if node_modules folder exists and has files", "percentage": 88}, {"solution": "Delete node_modules and reinstall", "percentage": 85}]'::jsonb, 'npm, modules', 'require() finds module', 'Incomplete installation', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/42445028/how-to-resolve-an-npm-install-error', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ENOENT chmod node_modules permission issue', 'tooling-npm', 'LOW', '[{"solution": "Delete node_modules folder completely and reinstall", "percentage": 92}, {"solution": "Use npm cache clean --force before reinstalling", "percentage": 88}, {"solution": "Check file system permissions on parent directory", "percentage": 80}]'::jsonb, 'npm, permissions', 'chmod succeeds', 'Corrupted node_modules installation', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/17990647/npm-install-errors-with-error-enoent-chmod', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ENOENT lstat node_modules folder missing', 'tooling-npm', 'MEDIUM', '[{"solution": "Reinstall dependencies: npm install", "percentage": 94}, {"solution": "Delete package-lock.json and run npm install", "percentage": 90}, {"solution": "Copy node_modules from another working installation", "percentage": 70}]'::jsonb, 'npm, installation', 'node_modules folder exists', 'Accidental deletion of node_modules', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/66597544/enoent-no-such-file-or-directory-lstat-users-desktop-node-modules', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('npm warn optional skipping optional dependency', 'tooling-npm', 'LOW', '[{"solution": "Install optional dependency explicitly if needed", "percentage": 85}, {"solution": "Use npm install --no-optional to skip optional deps", "percentage": 80}, {"solution": "Check if optional dependency is actually required", "percentage": 75}]'::jsonb, 'npm, optional', 'Application works without optional dep', 'Missing optional dependency', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/49651221/npm-enoent-no-such-file-or-directory-rename', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERESOLVE unable to resolve peer dependency angular', 'tooling-npm', 'MEDIUM', '[{"solution": "Use --legacy-peer-deps flag for installation", "percentage": 94}, {"solution": "Update angular and related packages to compatible versions", "percentage": 90}, {"solution": "Use --force flag if peer deps can be overridden", "percentage": 75}]'::jsonb, 'npm, angular', 'npm install succeeds', 'Incompatible angular versions', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/72686052/how-can-i-fix-eresolve-unable-to-resolve-dependency-tree-for-npm-install', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERESOLVE unable to resolve dependency react version', 'tooling-npm', 'HIGH', '[{"solution": "Run npm install --legacy-peer-deps", "percentage": 95}, {"solution": "Check package.json for react version constraints", "percentage": 92}, {"solution": "Update conflicting packages to match react version", "percentage": 88}]'::jsonb, 'npm, react', 'npm install succeeds', 'Peer dependency mismatch', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/71830754/npm-err-code-eresolve-npm-err-eresolve-unable-to-resolve-dependency-tree-in-re', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERESOLVE unable to resolve simple react app', 'tooling-npm', 'MEDIUM', '[{"solution": "Use npm install --legacy-peer-deps for the installation", "percentage": 96}, {"solution": "Downgrade npm to version 7 or earlier", "percentage": 80}, {"solution": "Use yarn instead of npm", "percentage": 75}]'::jsonb, 'npm, react', 'create-react-app succeeds', 'npm 8 strict peer deps', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/72478068/how-to-resolve-npm-err-eresolve-unable-to-resolve-dependency-tree-simple-reac', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERESOLVE facebook react dependency conflict', 'tooling-npm', 'MEDIUM', '[{"solution": "Use --legacy-peer-deps flag to override", "percentage": 93}, {"solution": "Install specific compatible versions of packages", "percentage": 88}, {"solution": "Check package documentation for version requirements", "percentage": 82}]'::jsonb, 'npm, react', 'facebook packages install', 'Version mismatch with react', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/65549858/eresolve-unable-to-resolve-dependency-tree-when-installing-npm-react-facebook', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERESOLVE unable to resolve cache dependencies', 'tooling-npm', 'MEDIUM', '[{"solution": "Clear npm cache: npm cache clean --force", "percentage": 92}, {"solution": "Delete node_modules and package-lock.json", "percentage": 90}, {"solution": "Try with --legacy-peer-deps if still failing", "percentage": 85}]'::jsonb, 'npm, cache', 'npm install succeeds', 'Stale cache with old dependencies', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/67710630/npm-install-eresolve-unable-to-resolve-dependency-tree', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERESOLVE unable to resolve dependency tree reactjs', 'tooling-npm', 'HIGH', '[{"solution": "Use npm install --legacy-peer-deps", "percentage": 96}, {"solution": "Fix upstream dependency conflicts in package.json", "percentage": 91}, {"solution": "Retry with --force flag if override is acceptable", "percentage": 70}]'::jsonb, 'npm, react', 'npm install succeeds', 'Strict peer dependency checking', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/64718633/unable-to-resolve-dependency-tree-reactjs', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERESOLVE unable to resolve newer packages', 'tooling-npm', 'MEDIUM', '[{"solution": "Update all packages to latest compatible versions", "percentage": 92}, {"solution": "Use npm install --legacy-peer-deps", "percentage": 89}, {"solution": "Check npm eresolve-report.txt for detailed conflicts", "percentage": 85}]'::jsonb, 'npm, versions', 'npm install succeeds', 'Outdated packages with new peer requirements', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/75985285/eresolve-unable-to-resolve-dependency-tree-when-running-npm-install', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EACCES permission denied rename node_modules path', 'tooling-npm', 'MEDIUM', '[{"solution": "Use sudo chown to fix ownership of npm folder", "percentage": 92}, {"solution": "Reinstall npm with correct permissions", "percentage": 88}, {"solution": "Use nvm to manage Node.js instead of system install", "percentage": 85}]'::jsonb, 'npm, permissions', 'npm operations succeed', 'Incorrect folder ownership', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/50639690/on-npm-install-unhandled-rejection-error-eacces-permission-denied', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EACCES permission denied usr lib node_modules', 'tooling-npm', 'MEDIUM', '[{"solution": "Run sudo chown -R $(whoami) /usr/lib/node_modules", "percentage": 91}, {"solution": "Use npm config set prefix to set custom directory", "percentage": 88}, {"solution": "Install npm locally instead of globally", "percentage": 82}]'::jsonb, 'npm, permissions', 'npm install succeeds', 'Missing write permissions in global folder', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/46058546/error-eacces-permission-denied-access-usr-lib-node-modules', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EACCES permission denied chown npm cache', 'tooling-npm', 'LOW', '[{"solution": "Run sudo chown -R $(whoami) ~/.npm and ~/.cache", "percentage": 93}, {"solution": "Clear npm cache and reset permissions", "percentage": 90}, {"solution": "Change npm cache directory with npm config set cache", "percentage": 85}]'::jsonb, 'npm, cache', 'npm cache commands work', 'Cache folder permission issues', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/38323880/error-eacces-permission-denied', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EACCES permission denied npm locking error', 'tooling-npm', 'MEDIUM', '[{"solution": "Fix npm lock permissions: sudo chown -R $(whoami) /tmp/.npm/_locks", "percentage": 92}, {"solution": "Use sudo npm cache clean --force", "percentage": 87}, {"solution": "Check if npm process is still running and kill it", "percentage": 85}]'::jsonb, 'npm, locking', 'npm install succeeds', 'Lock file permission denied', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/41350940/error-eacces-permission-denied-when-running-npm-install-on-elastic-beanstalk', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EACCES permission denied npm open cacache', 'tooling-npm', 'LOW', '[{"solution": "Clear npm cache directory permissions", "percentage": 90}, {"solution": "Delete ~/.npm and ~/.cache directories", "percentage": 88}, {"solution": "Run npm with proper user permissions", "percentage": 85}]'::jsonb, 'npm, cache', 'npm cache works', 'Corrupted cache permissions', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/56579529/npm-err-error-eacces-permission-denied-open', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EACCES permission denied mkdir npm install', 'tooling-npm', 'MEDIUM', '[{"solution": "Use sudo chown to fix directory ownership", "percentage": 91}, {"solution": "Create missing directory with proper permissions", "percentage": 88}, {"solution": "Use nvm instead of system Node.js installation", "percentage": 85}]'::jsonb, 'npm, permissions', 'npm install succeeds', 'No write permission to target directory', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/55938030/error-eacces-permission-denied-mkdir-when-installing-sth-with-npm', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EPERM operation not permitted windows npm', 'tooling-npm', 'MEDIUM', '[{"solution": "Close VS Code and all terminal windows", "percentage": 89}, {"solution": "Disable antivirus temporarily during npm operations", "percentage": 85}, {"solution": "Delete node_modules manually and reinstall", "percentage": 82}]'::jsonb, 'npm, windows', 'npm install succeeds', 'Files locked by other processes', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/34600932/eperm-operation-not-permitted-on-windows-with-npm', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EPERM operation not permitted unlink fsevents', 'tooling-npm', 'MEDIUM', '[{"solution": "Close all applications accessing node_modules", "percentage": 90}, {"solution": "Disable Windows Defender temporarily", "percentage": 86}, {"solution": "Install separately without fsevents", "percentage": 80}]'::jsonb, 'npm, mac', 'fsevents installs', 'Process locking files during unlink', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/46020018/error-eperm-operation-not-permitted-unlink-d-sources-node-modules-fseven', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EPERM operation not permitted expo application', 'tooling-npm', 'LOW', '[{"solution": "Close Metro bundler and restart installation", "percentage": 88}, {"solution": "Delete node_modules and lock files", "percentage": 86}, {"solution": "Use npm install --no-save to avoid lock issues", "percentage": 75}]'::jsonb, 'npm, expo', 'expo installation succeeds', 'Metro bundler holding file locks', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/56700018/npm-err-error-eperm-operation-not-permitted-unlink', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EPERM operation not permitted next js npm build', 'tooling-npm', 'LOW', '[{"solution": "Stop Next.js dev server before running npm operations", "percentage": 92}, {"solution": "Close all terminal windows and try again", "percentage": 88}, {"solution": "Delete .next folder and rebuild", "percentage": 85}]'::jsonb, 'npm, next.js', 'npm build succeeds', 'Next.js dev server holding locks', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/71851490/next-js-error-eperm-operation-not-permitted-open', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EPERM operation not permitted package unlink', 'tooling-npm', 'MEDIUM', '[{"solution": "Close all processes using the package", "percentage": 91}, {"solution": "Run npm cache clean --force before reinstalling", "percentage": 87}, {"solution": "Delete corrupted node_modules manually", "percentage": 85}]'::jsonb, 'npm, permissions', 'npm install succeeds', 'File in use by another process', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/47778492/npm-install-error-eperm-operation-not-permitted', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EPERM operation not permitted file open', 'tooling-npm', 'LOW', '[{"solution": "Check file permissions with ls -la", "percentage": 88}, {"solution": "Use chmod to add write permissions", "percentage": 85}, {"solution": "Delete and recreate the file", "percentage": 80}]'::jsonb, 'npm, file access', 'File access succeeds', 'File permissions incorrect', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/45686727/npm-err-error-eperm-operation-not-permitted', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ELIFECYCLE node app exits unexpectedly', 'tooling-npm', 'MEDIUM', '[{"solution": "Check if the port is already in use by another application", "percentage": 93}, {"solution": "Stop conflicting services (Apache, nginx, etc)", "percentage": 90}, {"solution": "Run the script directly to see actual error", "percentage": 88}]'::jsonb, 'npm, lifecycle', 'npm script runs without error', 'Port or resource conflict', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/30744964/what-does-the-elifecycle-node-js-error-mean', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ELIFECYCLE npm run dev exit status 1', 'tooling-npm', 'MEDIUM', '[{"solution": "Check npm-debug.log for actual error message", "percentage": 92}, {"solution": "Run the script directly to see detailed error", "percentage": 90}, {"solution": "Rebuild native modules if using vite", "percentage": 80}]'::jsonb, 'npm, vite', 'npm run dev succeeds', 'Script execution error not in npm log', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/75763176/npm-err-code-elifecycle-when-exiting-npm-run-dev', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ELIFECYCLE npm run errno 2 or 134', 'tooling-npm', 'MEDIUM', '[{"solution": "Check if required system tools are installed (Python, C++ build tools)", "percentage": 91}, {"solution": "Try running with a different Node.js version", "percentage": 85}, {"solution": "Clear cache and reinstall all dependencies", "percentage": 82}]'::jsonb, 'npm, system', 'npm script executes', 'Missing system dependencies', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/60069859/npm-err-code-elifecycle-npm-err-errno-2', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ELIFECYCLE react npm start error', 'tooling-npm', 'MEDIUM', '[{"solution": "Check if port 3000 is already in use", "percentage": 92}, {"solution": "Check for syntax errors in JavaScript/JSX files", "percentage": 90}, {"solution": "Clear React cache: rm -rf node_modules/.cache", "percentage": 85}]'::jsonb, 'npm, react', 'npm start succeeds', 'Port conflict or syntax error', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/62990304/how-to-solve-npm-err-code-elifecycle-in-react', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ELIFECYCLE npm run build exit status', 'tooling-npm', 'MEDIUM', '[{"solution": "Check build logs for actual compilation errors", "percentage": 93}, {"solution": "Fix TypeScript or syntax errors in source code", "percentage": 91}, {"solution": "Clear build cache directory", "percentage": 85}]'::jsonb, 'npm, build', 'npm run build succeeds', 'Compilation errors in source', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/44365238/how-can-i-resolve-npm-err-code-elifecycle-in-project-js-during-npm-start', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERR_SOCKET_TIMEOUT npm new angular project', 'tooling-npm', 'MEDIUM', '[{"solution": "Increase npm timeout: npm config set fetch-timeout 300000", "percentage": 93}, {"solution": "Clear npm cache and retry", "percentage": 90}, {"solution": "Use npm config set registry https://registry.npmmirror.com", "percentage": 85}]'::jsonb, 'npm, angular', 'npm new completes', 'Registry server timeout', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/67657599/npm-err-code-err-socket-timeout-on-creating-new-project-using-ng-new-appname', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERR_SOCKET_TIMEOUT npm install slow network', 'tooling-npm', 'HIGH', '[{"solution": "Increase fetch timeout limits", "percentage": 94}, {"solution": "Use alternative npm registry mirror", "percentage": 91}, {"solution": "Retry install with --verbose flag for debugging", "percentage": 85}]'::jsonb, 'npm, network', 'npm install completes', 'Network timeout', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/78784911/npm-install-fails-with-err-socket-timeout', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NOTARGET no matching version bootstrap', 'tooling-npm', 'MEDIUM', '[{"solution": "Update package.json to use correct bootstrap version", "percentage": 93}, {"solution": "Remove the caret (^) if requesting too wide a range", "percentage": 90}, {"solution": "Check npm registry for available versions", "percentage": 88}]'::jsonb, 'npm, bootstrap', 'Package installs', 'Version specifier too restrictive', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/51862044/npm-err-notarget-no-matching-version-found-for-bootstrap3', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ETARGET ELIFECYCLE combined error', 'tooling-npm', 'LOW', '[{"solution": "First fix ETARGET by updating version specifiers", "percentage": 89}, {"solution": "Then debug ELIFECYCLE by checking script output", "percentage": 87}, {"solution": "Clear cache and reinstall completely", "percentage": 82}]'::jsonb, 'npm, errors', 'Both errors resolved', 'Multiple error causes', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/58131932/npm-err-elifecycle-and-etarget', 'admin:1764219671');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NOTARGET no matching version angular', 'tooling-npm', 'MEDIUM', '[{"solution": "Use compatible Angular version in package.json", "percentage": 94}, {"solution": "Check Angular upgrade guide for compatibility", "percentage": 91}, {"solution": "Remove conflicting version constraints", "percentage": 88}]'::jsonb, 'npm, angular', 'Angular installs successfully', 'Incompatible Angular version', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/53122254/angular-7-new-project-err-code-etarget-no-matching-version-found-for-angul', 'admin:1764219671');

