-- AWS EC2 Error Codes - Official Docs Mining
-- Source: docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html
-- Mined: 2025-11-25

INSERT INTO knowledge_entries (
    query, category, hit_frequency, solutions, prerequisites, success_indicators,
    common_pitfalls, success_rate, claude_version, last_verified, source_url
) VALUES (
    'AWS EC2 error: AuthFailure - Credentials validation failed or insufficient permissions',
    'aws-ec2',
    'CRITICAL',
    $$[{"solution": "Verify your AWS credentials are correct and configured in your AWS CLI/SDK. Check that your account has active status and valid payment method on file. If using IAM user credentials, verify the user has appropriate EC2 permissions attached.", "percentage": 95, "note": "Most common cause is misconfigured credentials or missing IAM permissions"}, {"solution": "Run: aws ec2 describe-instances --region us-east-1 to verify credentials work", "percentage": 90, "note": "Test with a simple read operation first"}]$$::jsonb,
    'Valid AWS credentials configured, IAM user with EC2 permissions',
    'API call succeeds and returns instance data without AuthFailure error',
    'Using old credentials after rotation, wrong AWS region configured, expired temporary credentials',
    0.95,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html'
),
(
    'AWS EC2 error: UnauthorizedOperation - User lacks permission to perform requested action',
    'aws-ec2',
    'CRITICAL',
    $$[{"solution": "Check IAM policy attached to the user/role executing the API call. Ensure it includes ec2:* or specific EC2 action permissions (e.g., ec2:RunInstances). Use DecodeAuthorizationMessage action to see detailed policy rejection reason.", "percentage": 92, "note": "Decode the error message for specific policy issues"}, {"solution": "Attach AmazonEC2FullAccess policy or create custom policy with required permissions to the IAM user/role", "percentage": 88, "note": "Follow principle of least privilege for custom policies"}]$$::jsonb,
    'Access to AWS IAM console, ability to view and modify IAM policies',
    'EC2 API calls execute successfully without UnauthorizedOperation errors',
    'Assuming correct region has permissions when operating in different region, overly restrictive resource ARNs in policy',
    0.93,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html'
),
(
    'AWS EC2 error: InstanceLimitExceeded - Account has reached maximum concurrent instances',
    'aws-ec2',
    'HIGH',
    $$[{"solution": "Request an On-Demand Instance limit increase through AWS Service Quotas console. Navigate to EC2 Running On-Demand [InstanceType] instances quota and request increase.", "percentage": 90, "note": "Limit increases are typically processed within hours"}, {"solution": "Reduce instance count by terminating non-essential instances or breaking large launch requests into smaller batches across regions/availability zones", "percentage": 80, "note": "Temporary workaround while limit increase is pending"}]$$::jsonb,
    'AWS account access, understanding of current instance quota',
    'New instances launch successfully, Service Quotas shows increased limit',
    'Not checking current quota before requesting increase, requesting limit increase without terminating stopped instances',
    0.88,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html'
),
(
    'AWS EC2 error: InsufficientInstanceCapacity - AWS lacks capacity to fulfill request',
    'aws-ec2',
    'HIGH',
    $$[{"solution": "Wait a few minutes for AWS capacity to become available, then retry the request automatically using exponential backoff", "percentage": 75, "note": "This is a temporary capacity issue"}, {"solution": "Try launching instances in a different Availability Zone or AWS Region with available capacity", "percentage": 80, "note": "Different zones often have different capacity constraints"}, {"solution": "Try a different instance type if your workload allows, as less popular instance types usually have more available capacity", "percentage": 70, "note": "May need to update application deployment configurations"}]$$::jsonb,
    'Access to launch instances in different AZs/regions, flexibility in instance type selection',
    'Instances launch successfully in alternate AZ or with retry, check CloudFormation events show successful instance creation',
    'Not implementing retry logic, assuming single AZ always has capacity, not checking AWS status page for known capacity issues',
    0.80,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html'
),
(
    'AWS EC2 error: InvalidAMIID.NotFound - AMI does not exist or is unavailable in region',
    'aws-ec2',
    'HIGH',
    $$[{"solution": "Verify the AMI ID format is correct (ami-xxxxxxxxxxxxxxxx with 17 hex characters). Use AWS EC2 Console or CLI to search for valid AMIs in your region: aws ec2 describe-images --region us-east-1", "percentage": 94, "note": "Different regions have different AMIs available"}, {"solution": "Confirm you are operating in the correct AWS Region where the AMI exists. Copy the AMI ID to your target region by creating an image copy", "percentage": 90, "note": "AMIs are region-specific"}, {"solution": "Check if the AMI has been deregistered. Use aws ec2 describe-images --image-ids ami-xxxxx to verify its status", "percentage": 88, "note": "Deregistered AMIs cannot be launched"}]$$::jsonb,
    'AWS CLI configured, AMI ID string, correct AWS region specified',
    'aws ec2 describe-images returns the AMI with State=available, instance launches with specified AMI',
    'Copying AMI ID from AWS Console without verifying region, using abbreviated AMI ID format, attempting to launch from deregistered AMI',
    0.91,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html'
),
(
    'AWS EC2 error: InvalidKeyPair.NotFound - Specified key pair does not exist in region',
    'aws-ec2',
    'HIGH',
    $$[{"solution": "Verify the key pair name is spelled correctly and exists in the target region. List available key pairs: aws ec2 describe-key-pairs --region us-east-1", "percentage": 95, "note": "Key pair names are case-sensitive"}, {"solution": "If the key pair exists in a different region, create a new key pair in your target region or copy the key pair to the target region", "percentage": 92, "note": "Key pairs are region-specific resources"}, {"solution": "Create a new key pair if it does not exist: aws ec2 create-key-pair --key-name my-key-pair --region us-east-1", "percentage": 90, "note": "Save the private key immediately as it cannot be retrieved later"}]$$::jsonb,
    'AWS CLI configured, target region specified, private key backup if creating new pair',
    'aws ec2 describe-key-pairs shows the key pair in the target region, instance launches without InvalidKeyPair error',
    'Assuming key pair exists in all regions, not verifying exact key pair name spelling, losing private key file',
    0.94,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html'
),
(
    'AWS EC2 error: VPCResourceNotSpecified - Resource can only be used within VPC context',
    'aws-ec2',
    'HIGH',
    $$[{"solution": "Verify a VPC exists in your AWS account for the target region. Create a VPC if none exists: aws ec2 create-vpc --cidr-block 10.0.0.0/16", "percentage": 93, "note": "Default VPC is automatically created with new accounts"}, {"solution": "When launching instances, explicitly specify SubnetId (for VPC) or set --no-subnet to use EC2-Classic. For T2/T3 instances, you must specify a subnet ID", "percentage": 95, "note": "T2 and newer instance families require VPC"}, {"solution": "If using Infrastructure as Code, ensure NetworkInterface or SubnetId parameters are included in launch template or CloudFormation", "percentage": 90, "note": "Terraform/CloudFormation may default to EC2-Classic"}]$$::jsonb,
    'AWS account with VPC enabled, subnet ID (if using newer instance families like T2)',
    'Instance launches successfully in VPC, describe-instances shows PrivateIpAddress and VpcId',
    'Assuming EC2-Classic is still available (it is deprecated), not specifying subnet for T2 instances, using public IP without ENI',
    0.92,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html'
),
(
    'AWS EC2 error: InvalidInstanceID.NotFound - Specified instance does not exist',
    'aws-ec2',
    'MEDIUM',
    $$[{"solution": "Verify the instance ID format is correct (i-xxxxxxxx for older instances or i-xxxxxxxxxxxxxxxxx for newer). Double-check spelling and ensure you are querying the correct region", "percentage": 96, "note": "Instance IDs are case-sensitive"}, {"solution": "For recently created instances, wait 5-10 seconds for the instance ID to propagate through AWS systems before querying", "percentage": 88, "note": "Eventual consistency causes recent instances to not appear immediately"}, {"solution": "Confirm you are operating in the correct AWS Region where the instance was launched using: aws ec2 describe-instances --region us-east-1", "percentage": 94, "note": "Instances are region-specific"}]$$::jsonb,
    'AWS CLI configured, instance ID string, correct region specified',
    'aws ec2 describe-instances returns the instance data, instance visible in AWS Console',
    'Instance ID copied incorrectly from console, querying wrong region, attempting to reference instance before propagation delay',
    0.93,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html'
),
(
    'AWS EC2 error: VcpuLimitExceeded - Running instances have reached maximum vCPU allocation',
    'aws-ec2',
    'MEDIUM',
    $$[{"solution": "Request a vCPU limit increase through AWS Service Quotas: navigate to Running On-Demand [InstanceFamily]-instances vCPU quota and request increase for your needed instance family", "percentage": 91, "note": "Different instance families have separate limits"}, {"solution": "Terminate non-essential running instances to free up vCPU allocation, or move workloads to instances with fewer vCPUs", "percentage": 85, "note": "Stopped instances still count toward vCPU limit"}, {"solution": "Check current vCPU usage: aws ec2 describe-instances --filters Name=instance-state-name,Values=running | grep InstanceType", "percentage": 88, "note": "Calculate total vCPU from all running instances"}]$$::jsonb,
    'AWS account access, understanding of vCPU-to-instance-type mappings',
    'New instances launch with higher vCPU count, Service Quotas shows increased limit for instance family',
    'Not calculating current vCPU usage correctly, not understanding vCPU cost varies by instance family, stopping instead of terminating instances',
    0.88,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html'
),
(
    'AWS EC2 error: TagLimitExceeded - Reached maximum tags assignable to resource',
    'aws-ec2',
    'MEDIUM',
    $$[{"solution": "Review current tags on the resource: aws ec2 describe-tags --filters Name=resource-id,Values=i-xxxxx. Remove unnecessary tags to make room for new ones", "percentage": 94, "note": "AWS allows up to 50 tags per resource by default"}, {"solution": "Request a tag limit increase through Service Quotas (maximum is 50 tags per resource and this cannot be increased)", "percentage": 50, "note": "AWS has hard limit of 50 tags - focus on consolidation instead"}, {"solution": "Consolidate tag values - use fewer, more specific tags instead of many granular tags", "percentage": 96, "note": "Best practice approach to tag strategy"}]$$::jsonb,
    'AWS EC2 CLI configured, tagging permissions in IAM',
    'New tags apply to resource without TagLimitExceeded error, resource visible with correct tags in Console',
    'Assuming tag limit can be increased beyond 50, creating too many granular tags, not regularly auditing tag usage',
    0.93,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html'
),
(
    'AWS EC2 error: SecurityGroupLimitExceeded - Maximum security groups created or assigned',
    'aws-ec2',
    'MEDIUM',
    $$[{"solution": "Review current security groups: aws ec2 describe-security-groups. Delete unused security groups with: aws ec2 delete-security-group --group-id sg-xxxxx", "percentage": 92, "note": "Ensure no running instances are attached before deleting"}, {"solution": "Assign fewer security groups to instances (default limit is 5 per instance). Consolidate rules into fewer security groups", "percentage": 95, "note": "Better to have 2-3 focused security groups than many overlapping ones"}, {"solution": "Request security group limit increase through Service Quotas if account-level limit exceeded", "percentage": 88, "note": "Default account-level limit is 500 security groups per region"}]$$::jsonb,
    'AWS EC2 CLI configured, security group audit performed, no dependencies on specific SG IDs',
    'Security groups apply to instance without error, instance receives traffic matching security group rules',
    'Deleting security groups while instances still reference them, not understanding per-instance vs per-account limits, over-creating security groups',
    0.91,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html'
),
(
    'AWS EC2 error: InsufficientCapacity - AWS lacks resources to fulfill import or provision request',
    'aws-ec2',
    'HIGH',
    $$[{"solution": "Wait 5-15 minutes for AWS capacity to become available, then retry the API request with exponential backoff (1s, 2s, 4s, 8s...)", "percentage": 78, "note": "Temporary capacity issues resolve quickly"}, {"solution": "Check AWS Service Health Dashboard for any ongoing maintenance or incidents affecting your region/availability zone", "percentage": 82, "note": "Known issues are posted there"}, {"solution": "Modify request parameters: use a different instance type, smaller instance size, or different Availability Zone if launching", "percentage": 85, "note": "Some configurations may hit capacity before others"}]$$::jsonb,
    'AWS CLI or SDK configured, ability to wait and retry with backoff logic',
    'Retry succeeds and returns successful import/provision response, instance visible in Console',
    'Not implementing retry logic, giving up after single failure, assuming issue is permanent',
    0.82,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html'
),
(
    'AWS EC2 error: RequestLimitExceeded - API request rate exceeded for account',
    'aws-ec2',
    'MEDIUM',
    $$[{"solution": "Implement exponential backoff in your code: start with 1 second delay, double after each retry (1s, 2s, 4s, 8s, 16s max). Most requests succeed on first retry", "percentage": 93, "note": "Standard AWS rate limiting behavior"}, {"solution": "Use AWS SDK built-in retry logic (boto3, SDK.js, etc.) which handles backoff automatically with default 3-4 retries", "percentage": 95, "note": "SDKs have optimized retry logic already implemented"}, {"solution": "Batch API calls and reduce request frequency. Avoid looping rapid calls - use pagination cursors and batch operations", "percentage": 88, "note": "More efficient than individual requests"}]$$::jsonb,
    'AWS SDK or CLI installed, ability to modify application code for retry logic',
    'API calls succeed without rate limit errors, request responses return expected data',
    'Not implementing any retry logic, using sleep(1) instead of exponential backoff, not using SDK built-in retry features',
    0.94,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html'
);
