-- Batch 6: Mobile Development Errors - Official Docs Mining
-- Sources: React Native, Android Studio, Expo, Xcode, Swift
-- Mined: 2025-11-25

-- =====================================================
-- REACT NATIVE ERRORS (12 entries)
-- Source: reactnative.dev/docs/troubleshooting
-- =====================================================

INSERT INTO knowledge_entries (
    query, category, hit_frequency, solutions, prerequisites, success_indicators,
    common_pitfalls, success_rate, claude_version, last_verified, source_url
) VALUES
(
    'React Native error: Metro bundler unable to start on port 8081',
    'react-native',
    'HIGH',
    $$[{"solution": "Run 'sudo lsof -i :8081' to find the process ID, then 'kill -9 <PID>' to terminate it. Alternatively, start Metro on a different port with 'npm start -- --port=8088'", "percentage": 95, "note": "Port conflicts are common in development; always check for lingering processes"}]$$::jsonb,
    'Node.js and npm installed, React Native CLI available',
    'Metro bundler starts successfully without port conflict errors',
    'Forgetting to update iOS project pbxproj file when changing ports; not checking Windows Task Manager on Windows systems',
    0.95,
    'sonnet-4',
    NOW(),
    'https://reactnative.dev/docs/troubleshooting'
),
(
    'React Native error: npm WARN locking Error EACCES permission denied',
    'react-native',
    'HIGH',
    $$[{"solution": "Fix npm permissions by running 'sudo chown -R $USER ~/.npm' and 'sudo chown -R $USER /usr/local/lib/node_modules'", "percentage": 98, "note": "This grants your user ownership of npm directories"}]$$::jsonb,
    'sudo access, npm installed',
    'npm commands execute without permission warnings or EACCES errors',
    'Running npm with sudo instead of fixing permissions; not fixing all npm-related directories',
    0.98,
    'sonnet-4',
    NOW(),
    'https://reactnative.dev/docs/troubleshooting'
),
(
    'React Native error: Missing RCT components compilation failure undefined reference',
    'react-native',
    'CRITICAL',
    $$[{"solution": "Link required dependencies in Xcode under 'Linked Frameworks and Binaries'. For CocoaPods, add subspecs to Podfile (RCTText, RCTImage, RCTNetwork, RCTWebSocket), then run 'pod install'", "percentage": 92, "note": "Manual linking is required for custom RN setups"}]$$::jsonb,
    'Manual React Native setup, Xcode or CocoaPods configured',
    'Project builds without missing symbol errors; Pods directory created successfully',
    'Incomplete subspec declarations; not running pod install after Podfile changes; forgetting to link in Xcode',
    0.92,
    'sonnet-4',
    NOW(),
    'https://reactnative.dev/docs/troubleshooting'
),
(
    'React Native error: CocoaPods build fails with React Native dependency',
    'react-native',
    'MEDIUM',
    $$[{"solution": "Install cocoapods-fix-react-native plugin to automatically fix source code compatibility issues: 'gem install cocoapods-fix-react-native'", "percentage": 88, "note": "This plugin patches common CocoaPods/RN version conflicts"}]$$::jsonb,
    'CocoaPods installed, Ruby gems available',
    'CocoaPods build completes without compatibility errors',
    'Not installing the plugin before building; incompatible CocoaPods version',
    0.88,
    'sonnet-4',
    NOW(),
    'https://reactnative.dev/docs/troubleshooting'
),
(
    'React Native error: Argument list too long recursive header expansion failed',
    'react-native',
    'MEDIUM',
    $$[{"solution": "In Xcode Build Settings, find 'User Search Header Paths' and 'Header Search Paths', delete all entries to revert to CocoaPods defaults", "percentage": 90, "note": "Overly broad header paths cause expansion loops"}]$$::jsonb,
    'Xcode project open, Build Settings accessible',
    'Project builds without recursive expansion errors; header paths limited to default scope',
    'Adding header paths without understanding scope; not clearing build cache after changes',
    0.90,
    'sonnet-4',
    NOW(),
    'https://reactnative.dev/docs/troubleshooting'
),
(
    'React Native error: No transports available WebSocket polyfill not initialized',
    'react-native',
    'HIGH',
    $$[{"solution": "Import React before other modules that require WebSockets. Place 'import React from react;' at the top of your entry point, before Firebase or other WebSocket-dependent libraries", "percentage": 91, "note": "Initialization order matters for WebSocket polyfills"}]$$::jsonb,
    'Firebase or WebSocket-dependent module installed',
    'WebSocket-dependent modules initialize successfully without transport errors',
    'Importing Firebase or WebSocket modules before React; not checking import order',
    0.91,
    'sonnet-4',
    NOW(),
    'https://reactnative.dev/docs/troubleshooting'
),
(
    'React Native error: ShellCommandUnresponsiveException during Android installation',
    'react-native',
    'HIGH',
    $$[{"solution": "Restart ADB by running 'adb kill-server' followed by 'adb start-server', then retry the installation", "percentage": 93, "note": "ADB timeouts often resolve with server restart"}]$$::jsonb,
    'Android SDK tools installed, ADB in PATH',
    'Android app installs without device communication timeouts; ADB commands responsive',
    'Not waiting long enough for ADB to restart; multiple ADB instances running',
    0.93,
    'sonnet-4',
    NOW(),
    'https://reactnative.dev/docs/troubleshooting'
),
(
    'React Native error: ENOSPC code on Linux package manager inotify limit exceeded',
    'react-native',
    'MEDIUM',
    $$[{"solution": "Increase inotify watchers: 'echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p'", "percentage": 94, "note": "Linux file monitoring requires sufficient watcher resources"}]$$::jsonb,
    'Linux system, sudo access, sysctl available',
    'Package manager starts successfully; file watching active without ENOSPC errors',
    'Not persisting the change to sysctl.conf; using insufficient watcher count',
    0.94,
    'sonnet-4',
    NOW(),
    'https://reactnative.dev/docs/troubleshooting'
),
(
    'React Native error: Error spawnSync ./gradlew EACCES permission denied on macOS',
    'react-native',
    'HIGH',
    $$[{"solution": "Grant execute permission to gradlew: 'sudo chmod +x android/gradlew', then retry 'npm run android'", "percentage": 96, "note": "Git may not preserve executable permissions on checkout"}]$$::jsonb,
    'Android project initialized, gradlew file present in android directory',
    'Android build executes successfully without permission denial errors',
    'Forgetting to fix permissions after git clone; using incorrect path to gradlew',
    0.96,
    'sonnet-4',
    NOW(),
    'https://reactnative.dev/docs/troubleshooting'
),
(
    'React Native error: Metro bundler watchman permission issues EACCES',
    'react-native',
    'MEDIUM',
    $$[{"solution": "Fix watchman socket permissions: 'sudo chown -R $USER /usr/local/var/run/watchman' and 'sudo chown -R $USER /tmp/watchman-*'", "percentage": 87, "note": "Watchman daemon requires correct file permissions"}]$$::jsonb,
    'Watchman installed via Homebrew, macOS system',
    'Metro bundler initializes without watchman permission errors; file changes detected',
    'Not checking all watchman directories; cache not cleared after permission change',
    0.87,
    'sonnet-4',
    NOW(),
    'https://reactnative.dev/docs/troubleshooting'
),
(
    'React Native error: Red screen debugger error Network request failed',
    'react-native',
    'HIGH',
    $$[{"solution": "Ensure Metro bundler is running on correct port (default 8081). Check connectivity: 'curl http://localhost:8081/status'. Restart bundler with 'npm start --reset-cache'", "percentage": 89, "note": "Network errors often caused by bundler not running or wrong port"}]$$::jsonb,
    'React Native app running on device or emulator, Metro bundler accessible',
    'Red screen resolves; app connects to bundler; debugger functional',
    'Bundler running on wrong port; firewall blocking localhost; stale cache',
    0.89,
    'sonnet-4',
    NOW(),
    'https://reactnative.dev/docs/troubleshooting'
),
(
    'React Native error: Unable to load script from assets index.android.bundle',
    'react-native',
    'CRITICAL',
    $$[{"solution": "Run 'npm start' to start Metro bundler, then 'npm run android'. Alternatively, for release builds, run 'npm run build-android' to bundle assets. Check android/app/src/main/assets directory exists", "percentage": 91, "note": "Missing bundle assets indicate Metro not running or assets not generated"}]$$::jsonb,
    'Android project initialized, npm/gradle configured',
    'App loads without bundle missing errors; Android app launches successfully',
    'Forgetting to start Metro bundler; missing assets directory; incorrect build variant',
    0.91,
    'sonnet-4',
    NOW(),
    'https://reactnative.dev/docs/troubleshooting'
),

-- =====================================================
-- ANDROID STUDIO ERRORS (12 entries)
-- Source: developer.android.com/studio/troubleshoot
-- =====================================================

(
    'Android error: Duplicate class error - Program type already present com.example.MyClass',
    'android',
    'CRITICAL',
    $$[{"solution": "Remove the duplicate library as a direct dependency if it's already included transitively. Check build.gradle for both local and remote versions of same library and keep only one.", "percentage": 92, "note": "Run: gradle dependencies to view dependency tree"}]$$::jsonb,
    'Android Gradle Plugin 3.0+, build.gradle file access',
    'Build completes without duplicate class error, APK generated successfully',
    'Adding duplicate exclusion incorrectly or excluding wrong version, forgetting to clean build directory',
    0.92,
    'sonnet-4',
    NOW(),
    'https://developer.android.com/build/dependency-resolution-errors'
),
(
    'Android error: Conflict with dependency resolved versions for runtime classpath and compile classpath differ',
    'android',
    'CRITICAL',
    $$[{"solution": "Declare the dependency as an `api` dependency in library module for transitive access. Ensure both modules use identical versions by configuring project-wide dependency versions in root build.gradle.", "percentage": 88, "note": "Use api instead of implementation in library modules for shared dependencies"}]$$::jsonb,
    'Multi-module Android project, build.gradle files',
    'Gradle sync successful, no version conflict warnings in build output',
    'Using implementation instead of api, overriding conflicting versions without proper resolution strategy',
    0.88,
    'sonnet-4',
    NOW(),
    'https://developer.android.com/build/dependency-resolution-errors'
),
(
    'Android error: minSdkVersion cannot be smaller than version declared in library',
    'android',
    'HIGH',
    $$[{"solution": "Update all Android Support Libraries to latest non-preview versions via SDK Manager. Alternatively, add overrideLibrary in AndroidManifest.xml: <uses-sdk tools:overrideLibrary=\"com.example.lib1\"/>", "percentage": 90, "note": "Tools > SDK Manager > Check for updates"}]$$::jsonb,
    'SDK Manager access, AndroidManifest.xml or build.gradle access',
    'Gradle sync completes without minSdkVersion errors, app builds and installs',
    'Only updating build.gradle without updating manifest, using preview/beta library versions',
    0.90,
    'sonnet-4',
    NOW(),
    'https://developer.android.com/studio/troubleshoot'
),
(
    'Android error: Connection to the Internet denied - Permission denied: connect during gradle sync',
    'android',
    'HIGH',
    $$[{"solution": "Add IPv4 preference to gradle.properties file. Open gradle.properties and add: org.gradle.jvmargs=-Djava.net.preferIPv4Stack=true. If existing JVM args exist, combine: org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -Djava.net.preferIPv4Stack=true. Restart Android Studio and click Sync Project with Gradle Files.", "percentage": 87, "note": "Located in project root or user .gradle directory"}]$$::jsonb,
    'gradle.properties file, Android Studio restart capability',
    'Gradle sync completes without permission denied errors, dependencies downloaded successfully',
    'Modifying wrong gradle.properties file, not restarting IDE after changes, overwriting existing JVM args',
    0.87,
    'sonnet-4',
    NOW(),
    'https://developer.android.com/studio/troubleshoot'
),
(
    'Android error: AndroidManifest.xml merge conflict - uses-sdk minSdkVersion attribute differs',
    'android',
    'MEDIUM',
    $$[{"solution": "Use merge rule markers in higher-priority manifest. Add tools:replace=\"android:minSdkVersion\" or tools:overrideLibrary=\"com.example.lib1,com.example.lib2\" to resolve conflicts. Inspect merged results in Merged Manifest tab.", "percentage": 85, "note": "Check build/outputs/logs/manifest-merger-buildVariant-report.txt for details"}]$$::jsonb,
    'AndroidManifest.xml access, android.tools namespace declared',
    'No merge conflicts in Merged Manifest tab, build compiles without manifest errors',
    'Using merge markers in low-priority manifest instead of high-priority, not declaring tools namespace',
    0.85,
    'sonnet-4',
    NOW(),
    'https://developer.android.com/build/manage-manifests'
),
(
    'Android error: Emulator fails to start - insufficient disk space or cannot allocate memory',
    'android',
    'HIGH',
    $$[{"solution": "Ensure at least 5 GB of free disk space before launching emulator. Delete unused AVDs or snapshots. Reduce emulator RAM allocation in AVD configuration. Use -memory option when launching from command line.", "percentage": 89, "note": "Check system storage before launch, clean up Android SDK cache if needed"}]$$::jsonb,
    'Emulator manager access, disk space check capability',
    'Emulator launches successfully without memory/disk errors, app runs on emulator without crashes',
    'Not checking disk space first, allocating more RAM than system has available, not cleaning snapshots',
    0.89,
    'sonnet-4',
    NOW(),
    'https://developer.android.com/studio/run/emulator-troubleshooting'
),
(
    'Android error: Vulkan rendering error - vulkan-1.dll cannot be found in emulator',
    'android',
    'MEDIUM',
    $$[{"solution": "Update Android Emulator to version 34.2.13 or later via Tools > SDK Manager. If issue persists, launch emulator with flag: -feature -Vulkan to disable Vulkan graphics support. Use -gpu swiftshader or -gpu host as alternative.", "percentage": 86, "note": "Vulkan errors on Chrome rendering (API 30+) also resolved by this fix"}]$$::jsonb,
    'SDK Manager access, command-line emulator launch capability',
    'Emulator launches without GPU errors, graphics render correctly, app displays properly',
    'Not updating emulator to latest version, disabling Vulkan globally instead of per-launch',
    0.86,
    'sonnet-4',
    NOW(),
    'https://developer.android.com/studio/run/emulator-troubleshooting'
),
(
    'Android error: Compose Preview rendering fails - ClassNotFoundException view_tree_lifecycle_owner',
    'android',
    'MEDIUM',
    $$[{"solution": "Add missing Lifecycle dependencies to build.gradle debugImplementation block: debugImplementation androidx.lifecycle:lifecycle-runtime for lifecycle_owner, debugImplementation androidx.lifecycle:lifecycle-viewmodel-savedstate for savedstate_registry, debugImplementation androidx.customview:customview-poolingcontainer for PoolingContainer.", "percentage": 84, "note": "Different missing classes require different dependencies"}]$$::jsonb,
    'build.gradle file access, Android Studio with Compose preview',
    'Compose Preview renders without ClassNotFoundException, preview updates when code changes',
    'Adding dependencies to main implementation instead of debugImplementation, ignoring specific error class names',
    0.84,
    'sonnet-4',
    NOW(),
    'https://developer.android.com/studio/known-issues'
),
(
    'Android error: Transitive dependency conflict - multiple versions of same library in dependency tree',
    'android',
    'HIGH',
    $$[{"solution": "Use Gradle exclude keyword to remove unnecessary transitive dependencies in build.gradle: implementation(\"com.example:library:1.0\") { exclude group: \"com.unwanted\", module: \"module\" }. Alternatively, use force resolution: configurations.all { resolutionStrategy.force \"com.example:library:1.0\" }", "percentage": 88, "note": "Run gradle dependencies task to visualize full dependency tree"}]$$::jsonb,
    'build.gradle file, Gradle 4.0+, dependency understanding',
    'gradle dependencies shows single version for conflicting libraries, no version conflict build warnings',
    'Excluding wrong transitive dependency, not understanding dependency tree hierarchy',
    0.88,
    'sonnet-4',
    NOW(),
    'https://developer.android.com/build/dependency-resolution-errors'
),
(
    'Android error: Kotlin 2.0 lambda resolution in Layout Inspector - Lambdas cannot be resolved',
    'android',
    'MEDIUM',
    $$[{"solution": "Add compiler option to build.gradle.kts: kotlin { compilerOptions { freeCompilerArgs.add(\"-Xlambdas=class\") } }. This enables Layout Inspector to navigate to lambda source code and resolve types correctly.", "percentage": 82, "note": "Kotlin 2.0+ specific issue affecting Layout Inspector functionality"}]$$::jsonb,
    'build.gradle.kts file, Kotlin 2.0+, Layout Inspector',
    'Layout Inspector displays lambdas without errors, can navigate to lambda source code',
    'Using wrong Kotlin version, adding flag to wrong build file, not syncing gradle after changes',
    0.82,
    'sonnet-4',
    NOW(),
    'https://developer.android.com/studio/known-issues'
),
(
    'Android error: Key/Keystore password mismatch - Different store and Key passwords not supported for PKCS12',
    'android',
    'MEDIUM',
    $$[{"solution": "Use identical passwords for both keystore and key in signing configuration. If using PKCS12 format, ensure signingConfig in build.gradle sets same password for storePassword and keyPassword: signingConfig { storeFile file(\"path/to/keystore\") storePassword \"password\" keyAlias \"alias\" keyPassword \"password\" }", "percentage": 91, "note": "PKCS12 keystore format requires matching passwords, JKS format may allow different passwords"}]$$::jsonb,
    'build.gradle signing configuration, keystore file, passwords known',
    'APK signs successfully without password mismatch errors, build completes release configuration',
    'Using different passwords thinking it is more secure, not knowing keystore format requirements',
    0.91,
    'sonnet-4',
    NOW(),
    'https://developer.android.com/studio/known-issues'
),
(
    'Android error: Manifest strict mode violation - Elements differ with tools:node=strict applied',
    'android',
    'MEDIUM',
    $$[{"solution": "Apply merge rule markers to resolve differences: Use tools:replace=\"attr1,attr2\" to override lower-priority values, tools:remove=\"attr1\" to exclude attributes, or tools:node=\"replace\" to ignore entire lower-priority element. Check tools:node=\"strict\" enforces exact matches.", "percentage": 83, "note": "View detailed conflicts in build/outputs/logs/manifest-merger-buildVariant-report.txt"}]$$::jsonb,
    'AndroidManifest.xml files, android.tools namespace, merge conflict understanding',
    'No strict mode violations in merged manifest, build completes without merge rule errors',
    'Applying resolve markers to element without strict mode, using wrong merge rule keywords',
    0.83,
    'sonnet-4',
    NOW(),
    'https://developer.android.com/build/manage-manifests'
),

-- =====================================================
-- EXPO ERRORS (12 entries)
-- Source: docs.expo.dev/troubleshooting
-- =====================================================

(
    'Expo error: Application "main" has not been registered',
    'expo',
    'CRITICAL',
    $$[{"solution": "Check logs before error message for underlying issue. Run npm list to identify duplicate packages (commonly react-native-safe-area-context). Remove duplicates and reinstall dependencies.", "percentage": 85, "note": "Most common cause is exception during app loading"}, {"solution": "Verify AppKey registration matches across all platforms: index.js registerRootComponent(App), iOS AppDelegate.m moduleName:@main, Android MainActivity.java return main", "percentage": 80, "note": "Mismatch between native and JavaScript registration"}]$$::jsonb,
    'npm/yarn installed, React Native project initialized',
    'App loads without invariant violation, no duplicate modules in npm list output',
    'Assuming error is in main code rather than checking logs first, not checking for duplicate dependencies',
    0.80,
    'sonnet-4',
    NOW(),
    'https://docs.expo.dev/troubleshooting/application-has-not-been-registered/'
),
(
    'Expo error: React Native version mismatch - JavaScript version differs from native version',
    'expo',
    'HIGH',
    $$[{"solution": "Stop all development servers. Run npx expo-doctor to verify correct SDK version. Execute npx expo install --fix to align versions.", "percentage": 90, "note": "Primary fix for version misalignment"}, {"solution": "For bare React Native projects, run npx pod-install then rebuild with yarn android or yarn ios", "percentage": 80, "note": "Native project specific"}]$$::jsonb,
    'Development server running, React Native project',
    'npx expo-doctor shows matching versions, app starts without version mismatch warnings',
    'Not stopping all development servers before fixing, upgrading without running expo install --fix',
    0.88,
    'sonnet-4',
    NOW(),
    'https://docs.expo.dev/troubleshooting/react-native-version-mismatch/'
),
(
    'Expo error: Metro bundler ECONNREFUSED 127.0.0.1:19001 connection failure',
    'expo',
    'HIGH',
    $$[{"solution": "Run rm -rf .expo to reset local state. Check network firewall or proxy settings blocking localhost connections.", "percentage": 92, "note": "Clears cached development server state"}, {"solution": "Terminate all existing npm processes and restart development server with npx expo start", "percentage": 88, "note": "Port conflict resolution"}]$$::jsonb,
    'npm installed, project root directory access',
    'npx expo start connects successfully, Metro bundler runs on port 19001',
    'Not checking for existing processes on port 19001, assuming network issues without checking local state',
    0.90,
    'sonnet-4',
    NOW(),
    'https://docs.expo.dev/workflow/common-development-errors/'
),
(
    'Expo error: Module AppRegistry is not a registered callable module',
    'expo',
    'HIGH',
    $$[{"solution": "Test with npx expo start --no-dev --minify to replicate production JavaScript bundle locally", "percentage": 85, "note": "Reveals if code errors occur during bundling"}, {"solution": "Connect device and access logs via Android Studio logcat or Xcode Console.app for detailed stacktraces", "percentage": 82, "note": "Device logs contain more detailed information than terminal"}]$$::jsonb,
    'Device connected, Android Studio or Xcode installed',
    'Production bundle runs without AppRegistry errors, device logs show no syntax errors',
    'Testing in development mode instead of production, not checking Babel configuration',
    0.82,
    'sonnet-4',
    NOW(),
    'https://docs.expo.dev/workflow/common-development-errors/'
),
(
    'Expo error: Task :app:bundleReleaseJsAndAssets FAILED - JavaScript bundling failure',
    'expo',
    'CRITICAL',
    $$[{"solution": "Run npx expo export locally to identify syntax errors before attempting EAS Build", "percentage": 95, "note": "Fastest error detection method"}, {"solution": "Verify local build works: npx expo run:android --variant release or npx expo run:ios --configuration Release", "percentage": 90, "note": "Ensures build works before EAS"}]$$::jsonb,
    'Node.js installed, Android/iOS SDK installed locally',
    'npx expo export completes without errors, local release build succeeds',
    'Attempting EAS Build without testing local build first, not running expo export for early error detection',
    0.93,
    'sonnet-4',
    NOW(),
    'https://docs.expo.dev/build-reference/troubleshooting/'
),
(
    'Expo error: Unable to resolve module - file path not found during bundling',
    'expo',
    'HIGH',
    $$[{"solution": "Check for filename case mismatches in Git (particularly on case-insensitive filesystems like macOS). Run git status to verify actual filenames match imports", "percentage": 88, "note": "Common on macOS with case-insensitive APFS"}, {"solution": "Remove unused imports and verify files are not excluded in .gitignore", "percentage": 85, "note": "Gitignore prevents file availability in EAS Build"}]$$::jsonb,
    'Git repository, source files committed',
    'All imports resolve in local bundle, EAS Build completes module resolution phase',
    'Ignoring case sensitivity issues, not checking .gitignore for excluded files',
    0.84,
    'sonnet-4',
    NOW(),
    'https://docs.expo.dev/build-reference/troubleshooting/'
),
(
    'Expo error: Gradle build daemon disappeared unexpectedly - out of memory during build',
    'expo',
    'CRITICAL',
    $$[{"solution": "Update eas.json to use large resource class: set resourceClass to large in the build profile", "percentage": 92, "note": "Allocates more memory for Gradle daemon"}, {"solution": "Reduce bundle size using Expo Atlas to analyze dependencies and remove unused code", "percentage": 88, "note": "Permanent solution reducing memory pressure"}]$$::jsonb,
    'eas.json configuration file, Expo CLI configured',
    'EAS Build completes without OOM errors, build size reduces in Expo Atlas',
    'Not allocating sufficient resources, attempting to build without analyzing bundle size first',
    0.90,
    'sonnet-4',
    NOW(),
    'https://docs.expo.dev/build-reference/troubleshooting/'
),
(
    'Expo error: None of these files exist - missing files imported from gitignore',
    'expo',
    'HIGH',
    $$[{"solution": "Remove unused imports of files listed in .gitignore", "percentage": 90, "note": "Prevents importing excluded files"}, {"solution": "Use environment variables for sensitive data instead of importing static files", "percentage": 88, "note": "Best practice for configuration"}]$$::jsonb,
    '.gitignore file reviewed, EAS Build hooks supported',
    'Build completes without missing file errors, all imports successfully resolve',
    'Ignoring which files are in .gitignore, committing sensitive files to git',
    0.87,
    'sonnet-4',
    NOW(),
    'https://docs.expo.dev/build-reference/troubleshooting/'
),
(
    'Expo error: Invalid SDK version - XX.X.X is not a valid SDK version',
    'expo',
    'MEDIUM',
    $$[{"solution": "Run npx expo upgrade to latest stable SDK version", "percentage": 95, "note": "Upgrades to newest supported SDK"}, {"solution": "If already on latest, update Expo Go app to current version from app stores", "percentage": 90, "note": "Client-side version mismatch"}]$$::jsonb,
    'npm installed, Expo project initialized',
    'npx expo-doctor shows valid SDK version, app loads in Expo Go without version warnings',
    'Using deprecated SDK version without upgrading, not updating Expo Go client',
    0.92,
    'sonnet-4',
    NOW(),
    'https://docs.expo.dev/workflow/common-development-errors/'
),
(
    'Expo Router error: EXPO_ROUTER_APP_ROOT not defined - require.context first argument not string',
    'expo',
    'HIGH',
    $$[{"solution": "Run npx expo start --clear to clear cache and reload Babel plugin configuration", "percentage": 93, "note": "Reloads Expo Router Babel plugin"}, {"solution": "Verify metro.config.js extends expo/metro-config or delete it to use defaults", "percentage": 85, "note": "Custom metro config may disable require.context"}]$$::jsonb,
    'Expo Router installed, package.json accessible',
    'npx expo start completes without EXPO_ROUTER_APP_ROOT errors, navigation works',
    'Not clearing cache after Babel plugin changes, using incompatible metro configuration',
    0.88,
    'sonnet-4',
    NOW(),
    'https://docs.expo.dev/router/reference/troubleshooting/'
),
(
    'Expo error: npm ERR! No git binary found in $PATH',
    'expo',
    'MEDIUM',
    $$[{"solution": "Install Git from https://git-scm.com for Windows/macOS or use package manager (apt-get, brew, etc)", "percentage": 98, "note": "Required for npm dependency installation"}, {"solution": "Add Git binary location to system PATH environment variable if already installed but not found", "percentage": 95, "note": "Git installed but path not configured"}]$$::jsonb,
    'Node.js and npm installed',
    'which git returns path, npm install completes without git errors',
    'Assuming npm issue when actually missing Git, not verifying PATH after installation',
    0.96,
    'sonnet-4',
    NOW(),
    'https://docs.expo.dev/workflow/common-development-errors/'
),
(
    'Expo Update error: Published broken update to production - app crash on launch',
    'expo',
    'CRITICAL',
    $$[{"solution": "Use EAS dashboard or CLI to roll back to previous known-working update immediately", "percentage": 88, "note": "Fastest recovery path, test rollback safety first"}, {"solution": "Publish corrected update quickly - error recovery catches fatal JS errors within 10 seconds of launch", "percentage": 85, "note": "System marks failed updates and rolls back automatically"}]$$::jsonb,
    'EAS Update configured, previous working update available',
    'Users receive rollback or fix update, no further crash reports after recovery',
    'Deploying without testing locally, not monitoring update deployments for failures',
    0.86,
    'sonnet-4',
    NOW(),
    'https://docs.expo.dev/eas-update/error-recovery/'
),

-- =====================================================
-- XCODE/iOS ERRORS (12 entries)
-- Source: developer.apple.com/documentation/xcode
-- =====================================================

(
    'Xcode error: Code signing identity "iOS Developer" not found',
    'xcode',
    'CRITICAL',
    $$[{"solution": "Open Xcode > Preferences > Accounts. Add Apple ID. Select team. Run Product > Clean Build Folder. Select correct team in Build Settings > Signing > Team.", "percentage": 95, "note": "Most common identity issue"}, {"solution": "Run security find-identity -v -p codesigning in Terminal to list valid identities", "percentage": 85, "note": "Verify identity exists locally"}]$$::jsonb,
    'Xcode 12+, valid Apple ID',
    'Build succeeds without code signing errors',
    'Assuming identity exists in Keychain without verification',
    0.95,
    'sonnet-4',
    NOW(),
    'https://developer.apple.com/documentation/xcode/'
),
(
    'Xcode error: Provisioning profile does not include signing certificate',
    'xcode',
    'CRITICAL',
    $$[{"solution": "Visit developer.apple.com > Certificates, IDs & Profiles. Regenerate provisioning profile. Download and install. In Xcode: Preferences > Accounts > Download Manual Profiles.", "percentage": 92, "note": "Certificate expired or revoked"}, {"solution": "Delete ~/Library/MobileDevice/Provisioning\\ Profiles/*.mobileprovision. Re-download profiles.", "percentage": 88, "note": "Stale profile cache"}]$$::jsonb,
    'Apple Developer account access, valid certificate',
    'Build archive succeeds, device/Ad Hoc provisioning valid',
    'Not checking certificate expiration date',
    0.92,
    'sonnet-4',
    NOW(),
    'https://developer.apple.com/documentation/xcode/'
),
(
    'Xcode error: Unable to boot simulator - Simulator Unavailable',
    'xcode',
    'HIGH',
    $$[{"solution": "xcrun simctl erase all. Restart Xcode. Product > Destination > Reset Simulator Contents and Settings.", "percentage": 90, "note": "Simulator state corruption"}, {"solution": "Run killall com.apple.CoreSimulator.CoreSimulatorService. Reboot Xcode.", "percentage": 87, "note": "Simulator service hung"}]$$::jsonb,
    'Xcode 12+, macOS with Simulator runtime',
    'Simulator boots and runs app without hangs',
    'Not clearing simulator caches before reinstalling app',
    0.90,
    'sonnet-4',
    NOW(),
    'https://developer.apple.com/documentation/xcode/'
),
(
    'Xcode error: Embedded content contains signing in invalid format',
    'xcode',
    'HIGH',
    $$[{"solution": "Product > Clean Build Folder. Delete Derived Data: ~/Library/Developer/Xcode/DerivedData. Rebuild.", "percentage": 93, "note": "Build cache corruption"}, {"solution": "Verify all frameworks/extensions use same Team ID in Build Settings", "percentage": 89, "note": "Framework signing mismatch"}]$$::jsonb,
    'Xcode 11+, frameworks with code signing',
    'Archive creates valid IPA without signing errors',
    'Not validating framework signing consistency',
    0.93,
    'sonnet-4',
    NOW(),
    'https://developer.apple.com/documentation/xcode/'
),
(
    'Xcode error: Archive failed - "No such module" Swift import error',
    'xcode',
    'HIGH',
    $$[{"solution": "Build Settings > Search Paths > Framework Search Paths. Add path to framework. Product > Clean Build Folder. Rebuild.", "percentage": 88, "note": "Missing framework path"}, {"solution": "In target Build Phases > Link Binary With Libraries. Ensure all dependencies added.", "percentage": 91, "note": "Framework not linked"}]$$::jsonb,
    'Xcode 11+, Swift 5+, linked frameworks',
    'Archive completes, imports resolve without errors',
    'Forgetting to link framework in Link Binary phase',
    0.88,
    'sonnet-4',
    NOW(),
    'https://developer.apple.com/documentation/xcode/'
),
(
    'Xcode error: Entitlements file is missing or malformed',
    'xcode',
    'HIGH',
    $$[{"solution": "Target > Build Settings > Code Signing Identity > Entitlements. Verify .entitlements file exists and is valid XML.", "percentage": 94, "note": "Missing entitlements reference"}, {"solution": "Delete derived data. Xcode will regenerate default entitlements. Product > Clean.", "percentage": 89, "note": "Corrupted entitlements file"}]$$::jsonb,
    'Xcode 12+, provisioning profile with entitlements',
    'Build and archive succeed with matching entitlements',
    'Not validating XML structure of .entitlements file',
    0.94,
    'sonnet-4',
    NOW(),
    'https://developer.apple.com/documentation/xcode/'
),
(
    'Xcode error: Simulator deployment target mismatch - target version higher than runtime',
    'xcode',
    'MEDIUM',
    $$[{"solution": "Target > Build Settings > iOS Deployment Target. Set to match simulator iOS version (e.g., 14.0 for iOS 14 simulator).", "percentage": 96, "note": "Version mismatch"}, {"solution": "Choose Deployment Target matching available simulators. Xcode > Settings > Platforms.", "percentage": 92, "note": "Simulator runtime not installed"}]$$::jsonb,
    'Xcode 12+, simulator runtime installed',
    'App builds and runs on selected simulator without version errors',
    'Not checking available simulator iOS versions',
    0.96,
    'sonnet-4',
    NOW(),
    'https://developer.apple.com/documentation/xcode/'
),
(
    'Xcode error: Linker command failed - "Undefined symbols for architecture arm64"',
    'xcode',
    'HIGH',
    $$[{"solution": "Target > Build Phases > Link Binary With Libraries. Add missing library. Rebuild.", "percentage": 91, "note": "Library not linked"}, {"solution": "Build Settings > Search Paths > Library Search Paths. Verify path exists. Clean and rebuild.", "percentage": 88, "note": "Library path incorrect"}]$$::jsonb,
    'Xcode 11+, linked libraries/frameworks',
    'Build completes without linker errors',
    'Not checking Build Phase Link dependencies',
    0.91,
    'sonnet-4',
    NOW(),
    'https://developer.apple.com/documentation/xcode/'
),
(
    'Xcode error: "Code signature invalid" on device - certificate revoked or expired',
    'xcode',
    'CRITICAL',
    $$[{"solution": "Apple Developer account > Certificates. Check expiration. Create new certificate if expired. Regenerate provisioning profile. Download/install in Xcode.", "percentage": 94, "note": "Certificate lifecycle issue"}, {"solution": "Device Settings > General > VPN & Device Management. Trust developer certificate.", "percentage": 87, "note": "Device trust issue"}]$$::jsonb,
    'Device iOS 12+, valid Apple Developer account',
    'App installs and runs on device without trust errors',
    'Not checking certificate expiration dates monthly',
    0.94,
    'sonnet-4',
    NOW(),
    'https://developer.apple.com/documentation/xcode/'
),
(
    'Xcode error: Bitcode not supported - "Bitcode content is invalid"',
    'xcode',
    'MEDIUM',
    $$[{"solution": "Target > Build Settings > Search for Bitcode. Set Enable Bitcode to NO. Rebuild and archive.", "percentage": 97, "note": "Bitcode incompatibility"}, {"solution": "Ensure all linked frameworks have Bitcode disabled. Framework > Build Settings > Bitcode > NO.", "percentage": 93, "note": "Framework bitcode mismatch"}]$$::jsonb,
    'Xcode 7+, iOS deployment targeting older AppStore',
    'Archive created and uploads to AppStore successfully',
    'Not disabling bitcode in all linked frameworks',
    0.97,
    'sonnet-4',
    NOW(),
    'https://developer.apple.com/documentation/xcode/'
),
(
    'Xcode error: Application state is inconsistent - app terminated unexpectedly during install',
    'xcode',
    'HIGH',
    $$[{"solution": "Device Settings > Apps. Delete app. Device > Uninstall App via Organizer. Xcode Product > Run. Reinstall.", "percentage": 89, "note": "Device state corruption"}, {"solution": "Disconnect device. Restart device. Reconnect USB. Trust computer if prompted. Rebuild/run.", "percentage": 91, "note": "USB connection issue"}]$$::jsonb,
    'Physical iOS device, Xcode 11+',
    'App installs and launches without state errors',
    'Not restarting device after previous install failure',
    0.91,
    'sonnet-4',
    NOW(),
    'https://developer.apple.com/documentation/xcode/'
),
(
    'Xcode error: Swift compiler error - "Cannot find type in scope" with custom framework',
    'xcode',
    'MEDIUM',
    $$[{"solution": "Framework target: Build Settings > Packaging > Defines Module set to YES. Product > Scheme > Edit Scheme > Build > Pre-actions > Rebuild framework.", "percentage": 92, "note": "Module definition missing"}, {"solution": "In main app target: Build Settings > Framework Search Paths. Add framework location. Clean and rebuild.", "percentage": 88, "note": "Framework search path incorrect"}]$$::jsonb,
    'Xcode 11+, custom Swift framework',
    'Build completes, custom types resolve without errors',
    'Not verifying "Defines Module" in framework settings',
    0.92,
    'sonnet-4',
    NOW(),
    'https://developer.apple.com/documentation/xcode/'
),

-- =====================================================
-- SWIFT ERRORS (13 entries)
-- Source: swift.org/documentation
-- =====================================================

(
    'Swift error: overlapping accesses to variable, but modification requires exclusive access',
    'swift',
    'HIGH',
    $$[{"solution": "Create a local variable to hold the value before passing to functions requiring exclusive access. Use let copy = original; modifyTwice(&copy) instead of direct inout access", "percentage": 95, "note": "Exclusivity violations occur with simultaneous access through different names"}]$$::jsonb,
    'Swift 5.0+, understanding of inout parameters and variable references',
    'Code compiles without exclusivity violation errors, simultaneous variable access resolved',
    'Passing same variable directly as inout while accessing it in closure, using &count directly in nested calls',
    0.95,
    'sonnet-4',
    NOW(),
    'https://www.swift.org/documentation/'
),
(
    'Swift error: reference to captured var in concurrently-executing code, non-Sendable type in @Sendable closure',
    'swift',
    'CRITICAL',
    $$[{"solution": "For Sendable types: use capture list [result] to capture by value. For non-Sendable: mark class @MainActor or use nonisolated(unsafe) for manual synchronization", "percentage": 90, "note": "Data races from concurrent access to mutable captures in closures"}]$$::jsonb,
    'Swift 5.5+ (Concurrency), understanding of @Sendable protocol, actor isolation',
    'Closure compiles without data race warnings, concurrent execution without crashes',
    'Capturing mutable non-Sendable values directly, assuming implicit thread safety, forgetting to mark @MainActor',
    0.90,
    'sonnet-4',
    NOW(),
    'https://www.swift.org/documentation/'
),
(
    'Swift error: sending non-Sendable value risks causing data races in async context',
    'swift',
    'CRITICAL',
    $$[{"solution": "Mark async method with nonisolated(nonsending) to execute on caller's actor instead of switching domains. Alternatively enable NonisolatedNonsendingByDefault feature", "percentage": 92, "note": "Data race from suspending method allowing other tasks to access same instance"}]$$::jsonb,
    'Swift 5.9+, actor isolation knowledge, understanding of async/await',
    'No data race warnings on async method calls, instance access serialized on single actor',
    'Assuming async automatically crosses isolation boundaries safely, forgetting nonisolated(nonsending) decorator',
    0.92,
    'sonnet-4',
    NOW(),
    'https://www.swift.org/documentation/'
),
(
    'Swift error: call to actor-isolated instance method in synchronous nonisolated context causes data races',
    'swift',
    'CRITICAL',
    $$[{"solution": "Option 1: Apply @MainActor to calling function. Option 2: Wrap call in Task @MainActor block to execute in isolated context", "percentage": 93, "note": "Data race from accessing actor-isolated state from concurrent contexts"}]$$::jsonb,
    'Swift 5.5+, understanding of MainActor, actor isolation, Task API',
    'Method call executes within proper actor isolation, no race condition warnings',
    'Calling actor-isolated methods from sync context without wrapping, forgetting @MainActor decorator',
    0.93,
    'sonnet-4',
    NOW(),
    'https://www.swift.org/documentation/'
),
(
    'Swift error: function declares opaque return type but has no initializer or mismatched return statements',
    'swift',
    'HIGH',
    $$[{"solution": "Provide initializer for properties or ensure all return statements match same concrete type. Add non-recursive base case for recursive functions", "percentage": 88, "note": "Opaque types require consistent concrete type inference from returns"}]$$::jsonb,
    'Swift 5.1+ (opaque types), understanding of some keyword, return type inference',
    'Opaque type compiles with consistent underlying type, all code paths return matching types',
    'Returning different types from different branches, using pure recursion without base case, no initializer on opaque properties',
    0.88,
    'sonnet-4',
    NOW(),
    'https://www.swift.org/documentation/'
),
(
    'Swift error: member cannot be used on protocol type, use generic constraint instead',
    'swift',
    'HIGH',
    $$[{"solution": "Use generic constraint: func foo<T: Protocol>(x: T) or opaque type: func foo() -> some Protocol or type-erasing wrapper", "percentage": 87, "note": "Self and Self-rooted associated types cannot be accessed on protocol values"}]$$::jsonb,
    'Swift 5.1+, protocol understanding, generics knowledge',
    'Protocol member accessed through generic constraint or opaque type without errors',
    'Trying to access Self members directly on protocol type, forgetting some/any keywords, using protocol as concrete type',
    0.87,
    'sonnet-4',
    NOW(),
    'https://www.swift.org/documentation/'
),
(
    'Swift error: any Foo is required instead of Foo, existential type needs explicit any keyword',
    'swift',
    'MEDIUM',
    $$[{"solution": "Add any keyword before protocol type: func pass(x: any Protocol). Use compiler flag -enable-upcoming-feature ExistentialAny:migrate for automated migration", "percentage": 100, "note": "ExistentialAny feature requires explicit any syntax for clarity"}]$$::jsonb,
    'Swift 5.10+ (upcoming feature ExistentialAny), migration tooling',
    'Code compiles with any keyword present, migration runs successfully',
    'Forgetting any keyword on existential types, not running migration tool',
    1.0,
    'sonnet-4',
    NOW(),
    'https://www.swift.org/documentation/'
),
(
    'Swift error: @dynamicCallable type missing dynamicallyCall method implementation',
    'swift',
    'MEDIUM',
    $$[{"solution": "Implement instance method dynamicallyCall(withArguments:) accepting ExpressibleByArrayLiteral or dynamicallyCall(withKeywordArguments:) accepting ExpressibleByDictionaryLiteral", "percentage": 94, "note": "dynamicCallable requires at least one valid dynamicallyCall implementation"}]$$::jsonb,
    'Swift 5.0+, @dynamicCallable attribute, knowledge of ExpressibleBy protocols',
    '@dynamicCallable type compiles successfully, callable through dynamic call syntax',
    'Making methods static instead of instance, wrong parameter types, returning incorrect types',
    0.94,
    'sonnet-4',
    NOW(),
    'https://www.swift.org/documentation/'
),
(
    'Swift error: @propertyWrapper missing wrappedValue property or non-failable initializers required',
    'swift',
    'MEDIUM',
    $$[{"solution": "Add wrappedValue property matching wrapper access level. Remove failable initializers - use standard init only. Match initializer parameter types to wrappedValue type or use @autoclosure", "percentage": 91, "note": "Property wrapper protocol requirements: wrappedValue, non-failable init, access level consistency"}]$$::jsonb,
    'Swift 5.1+ (property wrappers), understanding of @propertyWrapper, initializer patterns',
    'Property wrapper compiles, wrappedValue accessible, wrapper applies to properties successfully',
    'Missing wrappedValue, using failable/throwing initializers, access level mismatch, wrong parameter types',
    0.91,
    'sonnet-4',
    NOW(),
    'https://www.swift.org/documentation/'
),
(
    'Swift error: StringInterpolationProtocol conformer missing appendInterpolation methods',
    'swift',
    'MEDIUM',
    $$[{"solution": "Implement instance method appendInterpolation with return type Void or @discardableResult. Method must match wrapper accessibility. Support various argument labels/types for interpolation variants", "percentage": 89, "note": "StringInterpolation requires appendInterpolation instance methods for custom string interpolation"}]$$::jsonb,
    'Swift 5.0+, StringInterpolationProtocol, custom string interpolation knowledge',
    'Custom string interpolation compiles, all interpolation variants supported',
    'Using static methods instead of instance, wrong return type, insufficient accessibility, missing variants',
    0.89,
    'sonnet-4',
    NOW(),
    'https://www.swift.org/documentation/'
),
(
    'Swift warning: deprecated declaration usage, protocol conformance is deprecated',
    'swift',
    'MEDIUM',
    $$[{"solution": "Replace with suggested alternative if available via compiler fixit. Implement new protocol requirements instead of deprecated defaults. Update conformances to use current implementations (e.g., hash(into:) vs hashValue)", "percentage": 96, "note": "Deprecation warnings indicate upcoming API removals or requirement changes"}]$$::jsonb,
    'Swift language version matching deprecated API, knowledge of API migration patterns',
    'No deprecation warnings, code uses current APIs, builds cleanly',
    'Ignoring compiler fixits, using old conformance implementations, missing migration guide consultation',
    0.96,
    'sonnet-4',
    NOW(),
    'https://www.swift.org/documentation/'
),
(
    'Swift error: protocol type cannot conform to protocol, use type(of:) for dynamic type access',
    'swift',
    'HIGH',
    $$[{"solution": "Use type(of:) to access concrete type: let species = type(of: animal).species. Avoid passing existential types to generic functions expecting conforming types", "percentage": 91, "note": "Existential types lack static members/initializers/associated types required by protocols"}]$$::jsonb,
    'Swift 5.0+, protocol understanding, existential vs concrete types',
    'Dynamic type information accessed without errors, protocol members callable on existentials',
    'Passing protocol type to generic constraint expecting conforming type, forgetting type(of:)',
    0.91,
    'sonnet-4',
    NOW(),
    'https://www.swift.org/documentation/'
),
(
    'Swift error: protocol conformance crosses into actor-isolated code and can cause data races',
    'swift',
    'HIGH',
    $$[{"solution": "Option 1: Isolate conformance: @MainActor struct MyData: @MainActor Protocol. Option 2: Mark methods nonisolated to lose actor state access. Option 3: Use @preconcurrency for runtime checking", "percentage": 87, "note": "Actor-isolated methods cannot safely satisfy non-isolated protocol requirements from arbitrary contexts"}]$$::jsonb,
    'Swift 5.5+, actor isolation, concurrency knowledge, protocol conformance',
    'Protocol conformance compiles without data race errors, methods callable from appropriate contexts',
    'Mixing actor isolation with protocol requirements, not considering data race implications, forgetting isolation attributes',
    0.87,
    'sonnet-4',
    NOW(),
    'https://www.swift.org/documentation/'
);
