-- Vue Authentication errors mining - 20251126
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Vue redirect not working after authentication set', 'vue', 'HIGH', '[{"solution": "Use useRouter hook from vue-router instead of importing router directly. Call const router = useRouter() in setup() then use router.push(''/''). Router instance must be called within component context.", "percentage": 95}, {"solution": "Ensure store state authenticated value updates before calling router.push(). Add redirect call after store commits new state.", "percentage": 85}]'::jsonb, 'Vue 3 with vue-router 4, component in setup() context', 'Successfully redirected to home page after login, no redirect loop to login', 'Importing router directly instead of using useRouter hook, calling router.push before state updates', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/76919771/vue-authentication', 'admin:1764192132');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Vue authentication state lost on page refresh route guard failing', 'vue', 'HIGH', '[{"solution": "Persist authentication state to localStorage. Store authenticated flag in localStorage on mutation and restore from localStorage on store initialization. Update store mutations to save to localStorage when setting authenticated state.", "percentage": 95}, {"solution": "Call router.push() after authentication mutations complete. Ensure state updates propagate before navigation redirect.", "percentage": 88}]'::jsonb, 'Vuex store setup, Vue 3 with vue-router 4, localStorage API available', 'Authentication state persists across page refresh, user stays logged in when revisiting protected routes', 'Storing auth state only in memory without localStorage persistence, redirecting before state updates complete', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/67272688/how-to-auth-the-user-in-vue-3', 'admin:1764192132');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('websanova vue-auth bearer token not sent to API requests', 'vue', 'HIGH', '[{"solution": "API must return authorization token in response header with key ''authorization'' (lowercase). Add ''Access-Control-Expose-Headers: Authorization'' CORS header to API response so browser exposes token to vue-auth. vue-auth reads from response header automatically.", "percentage": 97}, {"solution": "Verify auth configuration uses authType: ''bearer'' in fetchData and refreshData options. Ensure HTTP driver is driverHttpAxios.", "percentage": 90}]'::jsonb, 'websanova/vue-auth v3, API returns user response with token, CORS enabled on backend', 'API requests include Authorization: Bearer [token] header, fetchUser/refreshUser requests succeed with authentication', 'Token not returned in API response header, missing Access-Control-Expose-Headers CORS header, authType mismatch, token in response body instead of header', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/72759640/websanova-vue-auth-not-set-bearer-token-vue-3', 'admin:1764192132');
