INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ESLint and Prettier plugin conflicts causing formatting errors', 'formatter', 'HIGH', '[{"solution": "Install eslint-config-prettier package and add it to extends array: npm install --save-dev eslint-config-prettier", "percentage": 95}, {"solution": "Disable prettier/prettier rule in .eslintrc: rules: { ''prettier/prettier'': 0 }", "percentage": 90}, {"solution": "Disable Prettier VS Code extension if multiple formatter extensions are enabled", "percentage": 85}]'::jsonb, 'ESLint and Prettier both installed', 'Code formats without conflicts', 'Not installing eslint-config-prettier, enabling multiple formatter extensions', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/58424718/how-can-i-disable-the-error-prettier-prettier-on-eslint', 'admin:1764227008'),

('Prettier showing errors despite having formatted the file', 'formatter', 'HIGH', '[{"solution": "Check if multiple Prettier extensions are enabled - disable duplicates", "percentage": 95}, {"solution": "Set default formatter in VS Code: File > Preferences > Settings > search formatter > select Prettier", "percentage": 90}, {"solution": "Click ''fix all prettier issues'' and verify formatting is consistent", "percentage": 85}]'::jsonb, 'VS Code with Prettier extension installed', 'Format command applies changes without errors', 'Multiple Prettier extensions enabled, default formatter not set', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/73320894/prettier-showing-error-despite-having-formatted-the-file', 'admin:1764227008'),

('Insert space after function keyword prettier/prettier error', 'formatter', 'HIGH', '[{"solution": "Add space between function keyword and parentheses: function () {} instead of function() {}", "percentage": 96}, {"solution": "Enable format on save to auto-fix spacing issues", "percentage": 88}, {"solution": "Check Prettier configuration for spacing rules in .prettierrc", "percentage": 80}]'::jsonb, 'JavaScript/TypeScript project with Prettier', 'Code passes linting without spacing errors', 'Ignoring Prettier spacing rules, not running format on save', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/63694635/how-to-fix-or-ignore-the-following-prettier-error', 'admin:1764227008'),

('Code style issues found in above files - Forgot to run Prettier', 'formatter', 'HIGH', '[{"solution": "Run prettier --write . to format all files", "percentage": 97}, {"solution": "Add prettier --check to pre-commit hooks to catch formatting issues", "percentage": 92}, {"solution": "Use prettier-eslint to auto-fix formatting during development", "percentage": 85}]'::jsonb, 'Prettier installed in project', 'All files pass prettier --check without errors', 'Not running prettier before committing, skipping format on save', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/69797806/code-style-issues-found-in-the-above-files-forgot-to-run-prettier', 'admin:1764227008'),

('Prettier formatting differently on Windows vs Linux/Mac line endings', 'formatter', 'HIGH', '[{"solution": "Add * text=auto eol=lf to .gitattributes file to normalize line endings", "percentage": 98}, {"solution": "Set core.autocrlf to false in git config", "percentage": 92}, {"solution": "Ensure all developers use same Prettier version and config file", "percentage": 88}]'::jsonb, 'Git repository with cross-platform development', 'prettier --check passes on all operating systems', 'CRLF vs LF line endings, not normalizing via .gitattributes', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/61958231/github-actions-prettier-finds-errors-only-on-windows-latest', 'admin:1764227008'),

('Prettier formats code then ESLint shows error on formatted code', 'formatter', 'HIGH', '[{"solution": "Create .prettierrc file with matching ESLint rules: {\"trailingComma\": \"none\", \"tabWidth\": 2, \"semi\": true, \"singleQuote\": false}", "percentage": 96}, {"solution": "Ensure ESLint extends prettier config: extends: [\"prettier\"]", "percentage": 94}, {"solution": "Verify VS Code settings use project .prettierrc not workspace defaults", "percentage": 88}]'::jsonb, '.prettierrc and .eslintrc files exist', 'Format on save applies rules without ESLint conflicts', 'VS Code workspace settings overriding project config, missing extends in ESLint', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/66838133/in-vscode-why-is-prettier-formatting-my-code-and-then-highlighting-it-as-an-err', 'admin:1764227008'),

('Prettier --ignore-unknown option not recognized', 'formatter', 'MEDIUM', '[{"solution": "Update Prettier to latest version - some options require v2.6.0+", "percentage": 92}, {"solution": "If using yarn workspaces, add prettier to nohoist to use latest version", "percentage": 88}, {"solution": "Verify Prettier version: npx prettier -v", "percentage": 85}]'::jsonb, 'Prettier installed via npm or yarn', 'prettier --ignore-unknown runs without warnings', 'Old Prettier version in use, workspace version conflicts', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/69289584/prettier-ignored-unknown-option', 'admin:1764227008'),

('Prettier not formatting code in VS Code - no default formatter set', 'formatter', 'HIGH', '[{"solution": "Set default formatter: File > Preferences > Settings > search ''Editor: Default Formatter'' > select esbenp.prettier-vscode", "percentage": 97}, {"solution": "Enable format on save: Editor > Format On Save checkbox", "percentage": 94}, {"solution": "Use CTRL+SHIFT+P > Format Document With > select Prettier", "percentage": 92}]'::jsonb, 'VS Code with Prettier extension installed', 'Format Document command applies Prettier formatting', 'Default formatter set to null or wrong formatter selected', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/52586965/why-does-prettier-not-format-code-in-vs-code', 'admin:1764227008'),

('Prettier format on save not working after upgrading to v3', 'formatter', 'MEDIUM', '[{"solution": "Update VS Code settings for codeActionsOnSave with new syntax for v3", "percentage": 90}, {"solution": "Check if eslint.autoFixOnSave conflicts - use source.fixAll.eslint instead", "percentage": 88}, {"solution": "Reinstall Prettier extension after major version upgrade", "percentage": 82}]'::jsonb, 'Upgraded Prettier from v2 to v3', 'Format on save applies formatting without errors', 'Old config syntax after upgrade, deprecated eslint.autoFixOnSave setting', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/59433286/vs-code-prettier-format-on-save-doesnt-work', 'admin:1764227008'),

('Prettier format on save only working for some file types', 'formatter', 'MEDIUM', '[{"solution": "Set default formatter per language in settings: \"[javascript]\": { \"editor.defaultFormatter\": \"esbenp.prettier-vscode\" }", "percentage": 93}, {"solution": "Add file type association in workspace settings for CSS/HTML", "percentage": 89}, {"solution": "Verify Prettier supports the file type - check documentation", "percentage": 85}]'::jsonb, 'VS Code with Prettier v9.0.0+', 'All file types format on save consistently', 'Not configuring per-language formatter settings', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/69986240/prettier-format-on-save-not-working-in-css-or-html-files', 'admin:1764227008'),

('Cannot ignore block of code with prettier-ignore comments', 'formatter', 'MEDIUM', '[{"solution": "Use //prettier-ignore only on single statements - block ignore not supported", "percentage": 92}, {"solution": "Wrap multiple statements in a block and ignore the block: //prettier-ignore { statement1; statement2; }", "percentage": 88}, {"solution": "Move formatted-excluded code to separate file and add to .prettierignore", "percentage": 85}]'::jsonb, 'JavaScript/TypeScript with generated code', 'Specific lines formatted, others left untouched', 'Expecting prettier-ignore to work on multiple statements', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/66259151/how-to-make-prettier-to-ignore-a-block-of-code', 'admin:1764227008'),

('Prettier unknown option trailingComma with typo in config', 'formatter', 'LOW', '[{"solution": "Check for whitespace typos in JSON config - single space between key and value can break parsing", "percentage": 94}, {"solution": "Validate JSON syntax: use online JSON validator or editor linter", "percentage": 92}, {"solution": "Remove extra spaces: ''trailingComma'': ''none'' not ''trailingComma '' : ''none''", "percentage": 90}]'::jsonb, '.prettierrc.json or .prettierrc file exists', 'prettier --write runs without JSON parse errors', 'Typos in config file, invalid JSON syntax', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/63079614/prettier-unknown-options-trailingcomma', 'admin:1764227008'),

('Invalid Prettier configuration file UTF-16 encoding error', 'formatter', 'LOW', '[{"solution": "Change .prettierrc.json encoding from UTF-16 to UTF-8: delete and recreate via VS Code or text editor", "percentage": 96}, {"solution": "Avoid using echo command to create config - use file editor instead", "percentage": 94}, {"solution": "Verify file encoding: Right-click file > Change Encoding > UTF-8", "percentage": 92}]'::jsonb, '.prettierrc.json file exists', 'prettier --write runs without JSON parsing errors', 'Creating config file via command line with wrong encoding', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/70387394/prettier-invalid-configuration-file-even-though-the-file-is-straight-from-the-d', 'admin:1764227008'),

('VS Code Prettier extension hanging on files with large imports', 'formatter', 'MEDIUM', '[{"solution": "Check if WebStorm 2022.2+ issue - update to latest version", "percentage": 88}, {"solution": "Disable Prettier plugin temporarily and use CLI instead", "percentage": 85}, {"solution": "Simplify import statements or split into multiple files", "percentage": 78}]'::jsonb, 'VS Code or WebStorm with Prettier extension', 'Format Document completes without hanging', 'Large file size, too many imports, extension bug', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/74151161/format-with-prettier-on-save-doesnt-work-in-webstorm-2022-2-2', 'admin:1764227008'),

('Prettier VS Code keyboard shortcuts not working consistently', 'formatter', 'LOW', '[{"solution": "Verify VS Code Prettier settings and keyboard shortcuts are same in user + workspace settings", "percentage": 90}, {"solution": "Try CMD+SHIFT+P (Mac) or CTRL+SHIFT+P (Windows) > Format Document instead of shortcuts", "percentage": 88}, {"solution": "Restart VS Code and ensure extension is properly loaded", "percentage": 82}]'::jsonb, 'VS Code with Prettier extension', 'Format Document command works consistently', 'Keyboard shortcut conflicts with other extensions', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/75582427/prettier-not-working-on-save-from-within-visual-studio-code', 'admin:1764227008');
