INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Jest encountered an unexpected token - JSX/TypeScript not parsing', 'testing', 'CRITICAL', '[{"solution": "Add ts-jest transformer: \"^.+\\\\.tsx?$\": \"ts-jest\" in jest.config.js", "percentage": 92}, {"solution": "Ensure babel.config.js includes @babel/preset-typescript", "percentage": 88}]'::jsonb, 'Jest 24+, TypeScript or JSX files', 'Tests run without syntax errors', 'Missing babel config, wrong preset order', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/51994111', 'admin:1764226381'),

('Jest --no-cache required for tests to pass', 'testing', 'HIGH', '[{"solution": "Run jest --clearCache to clear stale cache", "percentage": 85}, {"solution": "Use jest.resetModules() in beforeEach to reset module cache", "percentage": 82}]'::jsonb, 'Jest 20+', 'Tests pass consistently without --no-cache flag', 'Not resetting module cache between tests', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/44866994', 'admin:1764226381'),

('jasmine.DEFAULT_TIMEOUT_INTERVAL - async test timeout', 'testing', 'HIGH', '[{"solution": "Set timeout in beforeEach: jasmine.DEFAULT_TIMEOUT_INTERVAL = 10000;", "percentage": 90}, {"solution": "Pass timeout as 3rd arg to test: it(''name'', fn, 5000)", "percentage": 85}]'::jsonb, 'Jasmine/Jest setup', 'Async tests complete within timeout', 'Setting timeout after test starts', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/9867601', 'admin:1764226381'),

('Cannot find module error - transformIgnorePatterns', 'testing', 'CRITICAL', '[{"solution": "Add transformIgnorePatterns: [\"node_modules/(?!axios)/\"] for ES modules", "percentage": 94}, {"solution": "Update babel-jest to latest version", "percentage": 87}]'::jsonb, 'Jest, Babel', 'All modules resolve correctly', 'Not excluding node_modules from transformation', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/74940474', 'admin:1764226381'),

('Unexpected token - ES6 import/export not transpiling', 'testing', 'CRITICAL', '[{"solution": "Ensure babel-jest is installed and configured", "percentage": 93}, {"solution": "Add \"transform\" key to jest.config.js with babel-jest", "percentage": 90}]'::jsonb, 'Jest, Babel', 'Import/export statements parse successfully', 'Babel config missing transform rules', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/57921019', 'admin:1764226381'),

('ReferenceError: jest is not defined', 'testing', 'MEDIUM', '[{"solution": "Ensure jest globals are enabled in jest.config.js", "percentage": 88}, {"solution": "Import jest at top of test file", "percentage": 91}]'::jsonb, 'Jest 24+', 'jest.fn() and other globals work', 'Globals disabled or Jest not properly installed', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/48157628', 'admin:1764226381'),

('Async callback was not invoked - fake timers not advancing', 'testing', 'HIGH', '[{"solution": "Call jest.runAllTimers() inside test before assertions", "percentage": 94}, {"solution": "Use jest.advanceTimersByTime(ms) for specific timing", "percentage": 91}]'::jsonb, 'Jest fake timers', 'Promise-based async code executes', 'Calling runAllTimers in afterAll hook instead of test', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/46710564', 'admin:1764226381'),

('Cannot read property ''then'' of undefined - mock not returning promise', 'testing', 'HIGH', '[{"solution": "Ensure mock returns Promise: jest.fn().mockResolvedValue(data)", "percentage": 96}, {"solution": "Use mockImplementation(() => Promise.resolve(...)) for complex returns", "percentage": 93}]'::jsonb, 'Jest, Promise-based testing', 'Mock functions return proper promises', 'Mock not returning promise, returning value directly', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/60681713', 'admin:1764226381'),

('Cannot spy on property because it is not a function', 'testing', 'MEDIUM', '[{"solution": "Use jest.fn() to create function before spying", "percentage": 89}, {"solution": "Verify property is function type before spyOn", "percentage": 85}]'::jsonb, 'Jest spyOn', 'spy() calls work without errors', 'Trying to spy on non-function property', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/60426804', 'admin:1764226381'),

('Cannot read property ''length'' of undefined', 'testing', 'MEDIUM', '[{"solution": "Check if array exists before accessing: if (arr && arr.length)", "percentage": 92}, {"solution": "Use optional chaining: arr?.length", "percentage": 95}]'::jsonb, 'JavaScript ES6+', 'No TypeError thrown for array access', 'Not handling null vs undefined, missing guards', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/46173527', 'admin:1764226381'),

('jest.fn() mock not returning value in .then()', 'testing', 'HIGH', '[{"solution": "Use mockResolvedValue for promise return: jest.fn().mockResolvedValue(val)", "percentage": 97}, {"solution": "Chain .then() on Promise, not on function call", "percentage": 94}]'::jsonb, 'Jest mocking', 'Promises resolve with expected values', 'Not returning Promise from mock function', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/48508225', 'admin:1764226381'),

('Test passes with async/await but not without', 'testing', 'HIGH', '[{"solution": "Return promise chain from test: return functionCall().then(...)", "percentage": 91}, {"solution": "Use async/await: const result = await function();", "percentage": 93}]'::jsonb, 'Jest async patterns', 'Tests pass consistently with or without async', 'Test returns before async code completes', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/70734846', 'admin:1764226381'),

('Cannot assign to read-only property error', 'testing', 'MEDIUM', '[{"solution": "Use Object.defineProperty to override: Object.defineProperty(window, ''prop'', {value: jest.fn()})", "percentage": 92}, {"solution": "Create local var before test, restore after: afterAll(() => { obj.prop = original })", "percentage": 88}]'::jsonb, 'Jest mocking', 'Read-only properties can be mocked', 'Trying to reassign directly, not using defineProperty', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/54018591', 'admin:1764226381'),

('Jest mock timers timeout - need to advance timers', 'testing', 'HIGH', '[{"solution": "Use jest.useFakeTimers() then jest.runAllTimers() in test", "percentage": 93}, {"solution": "Use jest.advanceTimersByTime(ms) for specific delays", "percentage": 91}]'::jsonb, 'Jest fake timers', 'Timed callbacks execute correctly', 'Not advancing fake timers in test, using real timers', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/46710564', 'admin:1764226381'),

('Module cache not invalidating between tests', 'testing', 'MEDIUM', '[{"solution": "Call jest.resetModules() in beforeEach hook", "percentage": 96}, {"solution": "Use jest.isolateModules(() => { require(...) }) for isolation", "percentage": 94}]'::jsonb, 'Jest module system', 'Modules reload with new environment variables', 'Module cache persists, environment changes ignored', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/48042200', 'admin:1764226381'),

('console.error mock not clearing between tests', 'testing', 'MEDIUM', '[{"solution": "Call console.error.mockClear() in afterEach hook", "percentage": 91}, {"solution": "Use jest.spyOn(console, ''error'').mockRestore() in afterEach", "percentage": 88}]'::jsonb, 'Jest mocking', 'console.error counts reset between tests', 'Not clearing mocks, state persists across tests', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/44596915', 'admin:1764226381'),

('Promise resolves but .resolves.toBe() fails with object', 'testing', 'MEDIUM', '[{"solution": "Use .resolves.toEqual() for objects instead of .toBe()", "percentage": 93}, {"solution": "Assert on specific property: expect(result.text).toBe(val)", "percentage": 91}]'::jsonb, 'Jest promise matchers', 'Promise resolution asserts correctly', 'Using === equality on objects, not deep equality', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/62712676', 'admin:1764226381'),

('Expected error not thrown - test with .rejects', 'testing', 'HIGH', '[{"solution": "Use: await expect(promise).rejects.toThrow(''Error'')", "percentage": 95}, {"solution": "Call function inside expect: expect(throwFunc()).rejects.toThrow()", "percentage": 93}]'::jsonb, 'Jest error testing', 'Errors throw and are caught correctly', 'Awaiting before expect, or passing result instead of call', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/70703051', 'admin:1764226381'),

('Sync test runs before async code - missing return or await', 'testing', 'HIGH', '[{"solution": "Return promise from test: return promiseFunction().then(...)", "percentage": 94}, {"solution": "Use async/await: async () => { await fn(); expect(...); }", "percentage": 96}]'::jsonb, 'Jest async patterns', 'Async operations complete before assertions', 'Not returning promise or using await', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/44741102', 'admin:1764226381'),

('Timeout waiting for async callback - flushPromises needed', 'testing', 'MEDIUM', '[{"solution": "Use flushPromises utility: const flushPromises = () => new Promise(setImmediate);", "percentage": 89}, {"solution": "Use jest.runAllTimersAsync() in Jest 29+", "percentage": 91}]'::jsonb, 'Jest async/Enzyme', 'Pending promises resolve before test completion', 'Not flushing promise queue, test times out', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/44741102', 'admin:1764226381'),

('TypeError: Cannot use import statement outside module', 'testing', 'CRITICAL', '[{"solution": "Enable ECMAScript modules in jest.config.js: \"extensionsToTreatAsEsm\": [\".ts\"]", "percentage": 88}, {"solution": "Add to package.json: \"type\": \"module\"", "percentage": 85}]'::jsonb, 'Jest ES modules', 'Import statements work without errors', 'Not configuring Jest for ES modules', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/71861628', 'admin:1764226381'),

('SyntaxError: Unexpected token < (JSX not transpiling)', 'testing', 'CRITICAL', '[{"solution": "Ensure jsx: \"react\" in tsconfig.json", "percentage": 93}, {"solution": "Add @babel/plugin-transform-react-jsx to babel.config.js", "percentage": 90}]'::jsonb, 'Jest, Babel, React', 'JSX components render in tests', 'JSX preset not configured, jsx compiler option wrong', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/56806193', 'admin:1764226381'),

('Missing ) after argument list - babel parsing error', 'testing', 'MEDIUM', '[{"solution": "Check babel.config.js has correct presets order", "percentage": 86}, {"solution": "Ensure tsconfig.json has \"lib\": [\"dom\", \"esnext\"]", "percentage": 84}]'::jsonb, 'Jest, Babel, TypeScript', 'Code parses without syntax errors', 'Babel preset order wrong, missing TypeScript lib', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/57921019', 'admin:1764226381'),

('expect.assertions not matching actual assertions', 'testing', 'MEDIUM', '[{"solution": "Set expect.assertions(1) before async test starts", "percentage": 92}, {"solution": "Count all assertions in promise chain and callbacks", "percentage": 90}]'::jsonb, 'Jest assertions', 'Assertion count matches expected value', 'Miscounting assertions in promise chains', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/43037566', 'admin:1764226381'),

('Jest config not found - run with explicit config path', 'testing', 'MEDIUM', '[{"solution": "Create jest.config.js or jest section in package.json", "percentage": 95}, {"solution": "Run with: jest --config ./jest.config.js", "percentage": 92}]'::jsonb, 'Jest configuration', 'Jest detects and loads configuration', 'Config file missing or in wrong location', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/69652505', 'admin:1764226381');
