-- Mining 10 Elysia Errors for clauderepo KB
-- Mined: 2025-11-26

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('VALIDATION error distinguishing response vs request validation in Elysia', 'elysia', 'HIGH', '[{"solution": "Use onError hook with error.type property to check if error.type === \"response\" for response validation errors, or use error.code === \"VALIDATION\" for both", "percentage": 92}, {"solution": "Access error.all array in local error handler to find specific validation errors by path property", "percentage": 88}]'::jsonb, 'Elysia onError hook knowledge', 'Validation errors properly categorized and handled', 'Not checking error.type property, treating all VALIDATION errors the same', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/77108947/how-to-distinguish-response-validation-error-from-other-validation-errors-in-ely', 'admin:1764210279'),

('Custom error messages with Elysia TypeBox schema validation', 'elysia', 'HIGH', '[{"solution": "Pass a function to error property: error({ errors, type, validator, value }) { switch(error.type) { case ValueErrorType.StringMinLength: return ''custom message'' } }", "percentage": 94}, {"solution": "Use ValueErrorType enum to match specific validation failure types", "percentage": 89}]'::jsonb, 'Elysia TypeBox, ValueErrorType enum', 'Custom error messages displayed correctly', 'Trying to pass array or object directly to error property instead of function', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/78304740/how-to-create-multiple-custom-error-messages-using-elysias-typebox', 'admin:1764210279'),

('Logging both successful responses and errors with single hook in Elysia', 'elysia', 'HIGH', '[{"solution": "Use onResponse hook for successful requests and onError hook for error handling separately - currently no single hook covers both cases", "percentage": 85}, {"solution": "Consider creating custom middleware pattern by combining onResponse and onError hooks", "percentage": 80}]'::jsonb, 'Elysia lifecycle hooks', 'Logging occurs for all request outcomes', 'Expecting a single onAllRepliesAtTheEnd hook that does not exist', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/77858417/in-elysiajs-is-there-a-way-to-print-a-log-to-the-console-after-either-an-error', 'admin:1764210279'),

('Recursive schema definition error in Elysia TypeBox - Cannot access before initialization', 'elysia', 'MEDIUM', '[{"solution": "Use t.Recursive(This => t.Object({ children: t.Optional(t.Array(This)) })) pattern where This parameter refers to the schema being defined", "percentage": 96}, {"solution": "Pass callback to t.Recursive that receives the schema reference instead of trying to reference variantSchema directly in definition", "percentage": 95}]'::jsonb, 'TypeBox t.Recursive pattern, callback functions', 'Recursive schemas properly defined without ReferenceError', 'Trying to use variable name inside its own t.Recursive definition before it''s assigned', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/79156719/issues-with-defining-a-recursive-schema-in-elysia', 'admin:1764210279'),

('Docker Prisma client generation failing with Elysia and Bun - Cannot find module .prisma/client', 'elysia', 'HIGH', '[{"solution": "Generate Prisma client on host machine before Docker build, then copy from node_modules/.prisma into container instead of running bunx prisma generate", "percentage": 93}, {"solution": "Change Prisma generator output path and copy generated directory into container, avoiding generation step in Docker", "percentage": 90}, {"solution": "Set binaryTargets in Prisma schema: binaryTargets = [\"native\", \"debian-openssl-1.1.x\"] based on base image", "percentage": 85}]'::jsonb, 'Docker, Bun, Prisma configuration', 'Docker build completes with Elysia app successfully', 'Running bunx prisma generate inside container, container platform mismatch for Prisma', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77097022/docker-build-failure-with-elysia-bun-and-prisma', 'admin:1764210279'),

('Request timeout with Elysia - infinite loop after 10 seconds with long-running handlers', 'elysia', 'MEDIUM', '[{"solution": "Pass idleTimeout option to .listen({idleTimeout: 30}) to extend default 10-second Bun.serve/uWS timeout", "percentage": 91}, {"solution": "Upgrade Bun version to support idleTimeout option properly - earlier versions may have limitations", "percentage": 87}]'::jsonb, 'Bun.serve configuration, uWS timeout settings', 'Long-running requests (>10s) complete without re-execution', 'Not aware of 10-second default timeout from underlying uWS library', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/79101771/bun-elysia-entrypoint-infinite-loop', 'admin:1764210279'),

('Middleware implementation error - argument assignment to handler signature in Elysia', 'elysia', 'HIGH', '[{"solution": "Use hooks with beforeHandle property instead of passing middleware as separate argument: app.post(path, handler, { beforeHandle: middleware })", "percentage": 94}, {"solution": "Refactor middleware from Express style (req, res, next) => {} to Elysia Context style with beforeHandle hook", "percentage": 92}, {"solution": "Use guard() for grouping routes with shared middleware instead of Express-style middleware", "percentage": 88}]'::jsonb, 'Elysia hooks, Context object, guard pattern', 'Middleware executes before route handlers without type errors', 'Passing Express-style middleware directly as route argument, not using hooks or beforeHandle', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/77107193/how-to-make-middleware-on-spesific-routes-in-elysiajs', 'admin:1764210279'),

('POST response body empty - ctx.body assignment not working in Elysia route', 'elysia', 'HIGH', '[{"solution": "Return the value directly from route handler instead of assigning to ctx.body: return { taskId } instead of ctx.body = { taskId }", "percentage": 96}, {"solution": "Elysia does not use ctx.body like Express - must explicitly return response object from handler", "percentage": 94}]'::jsonb, 'Elysia route handlers, response handling', 'POST route returns correct response body with status 200', 'Trying to use ctx.body assignment pattern from Express, forgetting to return value', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/77734474/how-do-i-set-the-post-response-body-in-bun-and-elysia', 'admin:1764210279'),

('Type safety lost when using JWT plugin in separate route files - jwt parameter shows as any', 'elysia', 'MEDIUM', '[{"solution": "Define JWTPayloadSchema with t.Object() and pass it to jwt config: jwt({ name: ''jwt'', secret: env.JWT_SECRET, schema: JWTPayloadSchema })", "percentage": 89}, {"solution": "Use schema property in jwt plugin configuration to maintain type safety across separate route files", "percentage": 87}]'::jsonb, 'Elysia JWT plugin, TypeBox schemas, type inference', 'JWT parameter properly typed in separate route files', 'Not providing schema property to jwt plugin configuration, expecting global type inference', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/79494287/is-it-possible-to-keep-type-safety-in-elysiajs-when-using-seperate-route-files', 'admin:1764210279'),

('Request object access in Elysia hooks - moving user data from middleware to route handler', 'elysia', 'MEDIUM', '[{"solution": "Use request.user pattern in beforeHandle hook to attach user data: request.user = decodedToken, then access in handler", "percentage": 90}, {"solution": "Attach custom properties to request object in hook instead of using res object like Express", "percentage": 88}]'::jsonb, 'Elysia hooks, Context, request object pattern', 'User data from JWT decoded in hook and accessible in route handlers', 'Expecting Express-style res.user pattern, not aware request object is mutable in Elysia', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77267860/express-jss-request-object-equivalent-in-elysia-js', 'admin:1764210279');
