BEGIN;

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Error acquiring the state lock ConditionalCheckFailedException', 'devops-terraform', 'HIGH', '[{"solution": "Run terraform force-unlock <lock-id> to release the stuck lock", "percentage": 95}, {"solution": "Check AWS DynamoDB for orphaned lock entries and delete manually", "percentage": 90}, {"solution": "Verify no other terraform processes are running", "percentage": 85}]'::jsonb, 'AWS backend configured with DynamoDB state lock', 'State lock released, terraform plan runs without lock error', 'Not checking for running terraform processes before forcing unlock', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/62189825/error-acquiring-the-state-lock-conditionalcheckfailedexception', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Error locking state blob is already locked', 'devops-terraform', 'HIGH', '[{"solution": "Use azure storage account to release the lock on blob lease", "percentage": 93}, {"solution": "Wait for current operation to complete before retrying", "percentage": 88}, {"solution": "Use terraform force-unlock in Azure backend", "percentage": 85}]'::jsonb, 'Azure backend with blob storage', 'Lease released, terraform can acquire lock', 'Attempting concurrent terraform operations', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/64690427/error-locking-state-error-acquiring-the-state-lock-state-blob-is-already-locke', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform statefile is locked how to unlock', 'devops-terraform', 'HIGH', '[{"solution": "Check state file timestamps and remove .terraform.lock.hcl", "percentage": 92}, {"solution": "For S3 backend: terraform force-unlock <lock-id>", "percentage": 90}, {"solution": "Verify IAM permissions for DynamoDB access", "percentage": 85}]'::jsonb, 'Access to terraform state backend', 'Lock file removed or DynamoDB entry deleted', 'Removing lock file without checking if operation is truly complete', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/65595852/terraform-statefile-is-locked-how-do-i-unlock-it', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform error acquiring state lock 2 errors occurred', 'devops-terraform', 'HIGH', '[{"solution": "Run terraform force-unlock with correct lock ID from error message", "percentage": 94}, {"solution": "Check backend connectivity and credentials", "percentage": 88}, {"solution": "Review CloudWatch logs for DynamoDB errors", "percentage": 82}]'::jsonb, 'AWS credentials configured with DynamoDB access', 'Lock successfully released', 'Incorrect lock ID format or insufficient permissions', 0.9, 'haiku', NOW(), 'https://stackoverflow.com/questions/64149876/terraform-error-error-locking-state-error-acquiring-the-state-lock-2-errors-o', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform state lock not able to release', 'devops-terraform', 'HIGH', '[{"solution": "Manually delete lock item in Azure Table Storage", "percentage": 91}, {"solution": "Check for stale processes holding the lock", "percentage": 89}, {"solution": "Re-authenticate with correct storage account credentials", "percentage": 85}]'::jsonb, 'Admin access to storage backend', 'Lock item deleted from storage, terraform can proceed', 'Deleting wrong table or not waiting for replication', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/60865899/terrform-state-lock-not-able-to-release', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform AWS error while acquiring state lock timeout', 'devops-terraform', 'HIGH', '[{"solution": "Increase DynamoDB provisioned throughput", "percentage": 87}, {"solution": "Check network connectivity to DynamoDB endpoint", "percentage": 90}, {"solution": "Verify correct region is configured for lock table", "percentage": 88}]'::jsonb, 'AWS access with proper VPC routing', 'Lock acquired within timeout period', 'Using provisioned throughput that is too low', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/78246112/terraform-aws-error-while-acquiring-state-lock', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Local state cannot be unlocked by another process terraform', 'devops-terraform', 'HIGH', '[{"solution": "Remove .terraform.lock.hcl file in local directory", "percentage": 94}, {"solution": "Kill any lingering terraform processes", "percentage": 92}, {"solution": "Use lsof to check which process has the lock", "percentage": 88}]'::jsonb, 'Local filesystem with file locking support', 'Lock file removed and no processes holding lock', 'Attempting to remove lock while process still running', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/71940888/local-state-cannot-be-unlocked-by-another-process-on-terraform', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Error acquiring the state lock resource temporarily unavailable', 'devops-terraform', 'HIGH', '[{"solution": "Retry terraform operation after waiting 30 seconds", "percentage": 91}, {"solution": "Check backend service status and availability", "percentage": 88}, {"solution": "Verify network connectivity to backend", "percentage": 86}]'::jsonb, 'Network connectivity to state backend', 'Terraform can acquire lock on retry', 'Not waiting long enough between retries', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/67643808/error-acquiring-the-state-lock-resource-temporarily-unavailable', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform reference to a resource type error', 'devops-terraform', 'HIGH', '[{"solution": "Check resource type spelling matches provider documentation", "percentage": 93}, {"solution": "Ensure provider version supports the resource type", "percentage": 91}, {"solution": "Verify resource is declared before being referenced", "percentage": 89}]'::jsonb, 'Correct provider installed', 'Resource type recognized by terraform plan', 'Typos in resource type or using old provider version', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/70764216/terraform-a-reference-to-a-resource-type-error', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Invalid reference from destroy provisioner terraform', 'devops-terraform', 'HIGH', '[{"solution": "Use self reference only in destroy provisioners", "percentage": 95}, {"solution": "Remove references to other resources in destroy block", "percentage": 92}, {"solution": "Move provisioner to local-exec which allows broader references", "percentage": 85}]'::jsonb, 'Understanding of provisioner lifecycle', 'Destroy provisioner runs without reference errors', 'Attempting to reference other resources in destroy phase', 0.9, 'haiku', NOW(), 'https://stackoverflow.com/questions/64436987/invalid-reference-from-destroy-provisioner', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Invalid reference in terraform using powershell', 'devops-terraform', 'HIGH', '[{"solution": "Escape dollar signs in interpolations: ${var.name}", "percentage": 94}, {"solution": "Use single quotes for strings containing dollar signs", "percentage": 91}, {"solution": "Check PowerShell variable scoping in scripts", "percentage": 87}]'::jsonb, 'PowerShell knowledge and terraform variable syntax', 'Variable interpolation works correctly', 'PowerShell interpreting dollar signs before terraform', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/71337217/invalid-reference-in-terraform-using-powershell', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform error reference to undeclared resource', 'devops-terraform', 'HIGH', '[{"solution": "Declare resource before referencing it", "percentage": 96}, {"solution": "Check resource name spelling matches declaration", "percentage": 94}, {"solution": "Use depends_on explicit dependency if needed", "percentage": 88}]'::jsonb, 'Terraform configuration files', 'Resource declaration found, reference resolves', 'Circular dependencies or typos in resource names', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/66433485/terraform-error-reference-to-undeclared-resource', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform invalid depends on reference syntax', 'devops-terraform', 'HIGH', '[{"solution": "Use resource.name format: depends_on = [aws_instance.web]", "percentage": 96}, {"solution": "Reference complete resource, not individual attributes", "percentage": 93}, {"solution": "Wrap multiple resources in list: depends_on = [res1, res2]", "percentage": 91}]'::jsonb, 'Understanding of terraform depends_on', 'Dependency graph resolves correctly', 'Using attribute references instead of resource references', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/64682567/terraform-invalid-depends-on-reference', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform error reference to undeclared resource when calling modules', 'devops-terraform', 'HIGH', '[{"solution": "Use module.name.output_name to reference module outputs", "percentage": 95}, {"solution": "Declare outputs in module before referencing", "percentage": 92}, {"solution": "Verify module source path is correct", "percentage": 89}]'::jsonb, 'Module structure with outputs defined', 'Module outputs accessible in parent config', 'Attempting to reference module internals directly', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/61421178/terraform-error-reference-to-undeclared-resource-when-calling-modules-from-te', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform invalid reference in launch template string', 'devops-terraform', 'HIGH', '[{"solution": "Use jsonencode for complex structures in user_data", "percentage": 92}, {"solution": "Escape quotes in interpolations: \\\"${var.name}\\\"", "percentage": 90}, {"solution": "Validate reference points to correct data type", "percentage": 88}]'::jsonb, 'EC2 launch template configuration', 'Launch template renders without reference errors', 'Quote escaping issues in template strings', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/70639016/terraform-invalid-reference-in-launch-template-string', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Reference to undeclared resource in terraform file', 'devops-terraform', 'HIGH', '[{"solution": "Search for resource declaration in all .tf files", "percentage": 94}, {"solution": "Check if resource is in different module", "percentage": 91}, {"solution": "Verify resource name case sensitivity", "percentage": 88}]'::jsonb, 'Multi-file terraform project', 'Resource found and imported', 'Assuming single file structure', 0.9, 'haiku', NOW(), 'https://stackoverflow.com/questions/71852802/reference-to-undeclared-resource', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform cycle error reading error message', 'devops-terraform', 'HIGH', '[{"solution": "Break cycle using depends_on instead of implicit dependencies", "percentage": 93}, {"solution": "Review resource graph: terraform graph | grep cycle", "percentage": 90}, {"solution": "Separate resources into different apply phases", "percentage": 85}]'::jsonb, 'Graphviz for graph visualization', 'Dependency graph is acyclic', 'Circular reference between resources', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/76474836/how-can-i-read-this-terraform-cycle-error-message-to-find-the-cyclic-references', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform fires cycle error when applying', 'devops-terraform', 'HIGH', '[{"solution": "Identify circular dependencies in resource references", "percentage": 94}, {"solution": "Use count or for_each to break cycle", "percentage": 89}, {"solution": "Restructure resources to remove mutual dependencies", "percentage": 87}]'::jsonb, 'Understanding of terraform dependency resolution', 'Resources can be applied in order without cycles', 'Multiple resources depending on same attribute', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/65250228/terraform-fires-cycle-error-when-applying', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform destroy produces cycle error when no cycles present', 'devops-terraform', 'HIGH', '[{"solution": "terraform graph shows false cycle in destroy phase", "percentage": 88}, {"solution": "Remove depends_on and let implicit dependencies resolve", "percentage": 85}, {"solution": "Use lifecycle ignore_changes to prevent changes", "percentage": 80}]'::jsonb, 'Understanding of destroy lifecycle', 'Destroy completes without cycle errors', 'Over-specifying dependencies in destroy phase', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/56514719/terraform-destroy-produces-cycle-error-when-no-cycles-present', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Solving terraform cycle for seemingly unrelated resources', 'devops-terraform', 'HIGH', '[{"solution": "Check shared variable or output dependencies", "percentage": 92}, {"solution": "Review all interpolations for hidden cycles", "percentage": 89}, {"solution": "Break cycle with separate apply phases using locals", "percentage": 85}]'::jsonb, 'Multi-resource configuration', 'Hidden dependency identified and removed', 'Assuming resources are independent', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/70846167/solving-terraform-cycle-for-seemingly-unrelated-resources', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Cycle error when creating AWS VPC security groups terraform', 'devops-terraform', 'HIGH', '[{"solution": "Avoid circular security group rule references", "percentage": 96}, {"solution": "Use aws_security_group_rule separate from aws_security_group", "percentage": 94}, {"solution": "Reference security group by ID instead of name", "percentage": 91}]'::jsonb, 'AWS provider and VPC knowledge', 'Security groups created without cycle errors', 'Multiple security groups referencing each other', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/38246326/cycle-error-when-trying-to-create-aws-vpc-security-groups-using-terraform', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Is there a way around this terraform cycle error', 'devops-terraform', 'HIGH', '[{"solution": "Use module dependencies with explicit ordering", "percentage": 90}, {"solution": "Split into separate root modules", "percentage": 87}, {"solution": "Use provisioners for ordering when cycle unavoidable", "percentage": 75}]'::jsonb, 'Advanced terraform structure', 'Resources applied in correct order', 'Trying to force all resources in single apply', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/76274910/is-there-a-way-around-this-terraform-cycle-error', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform cycle error circular dependency in assume role', 'devops-terraform', 'HIGH', '[{"solution": "Define IAM role policy separately from role assumption", "percentage": 94}, {"solution": "Use aws_iam_role_policy instead of inline policy", "percentage": 92}, {"solution": "Create service principal before referencing in policy", "percentage": 88}]'::jsonb, 'AWS IAM knowledge', 'Role and policy created without circular dependency', 'Inline policies with self-references', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/78930268/how-to-solve-cycle-error-circular-dependency-error-of-terraform-during-assum', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform throws error cycle with modules', 'devops-terraform', 'HIGH', '[{"solution": "Check module outputs for circular references", "percentage": 93}, {"solution": "Use depends_on to explicitly order module calls", "percentage": 90}, {"solution": "Separate modules into different apply operations", "percentage": 86}]'::jsonb, 'Modular terraform structure', 'Modules applied in topologically sorted order', 'Module outputs feeding back to module inputs', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/78809997/terraform-throws-error-cycle-with-modules', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform invalid provider configuration trying to use AWS with two regions', 'devops-terraform', 'HIGH', '[{"solution": "Define provider aliases: provider aws with alias = region2", "percentage": 95}, {"solution": "Pass provider explicitly to resources: provider = aws.region2", "percentage": 93}, {"solution": "Use different module invocations for each region", "percentage": 90}]'::jsonb, 'AWS multi-region configuration', 'Resources created in correct regions', 'Forgetting to pass provider alias to resources', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/78513771/terraform-invalid-provider-configuration-trying-to-use-aws-provider-with-two-reg', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Accessing provider configuration in custom terraform provider', 'devops-terraform', 'HIGH', '[{"solution": "Access via context.Meta in SDK v5+", "percentage": 91}, {"solution": "Use schema.ProviderMetaNestedBlock for custom config", "percentage": 88}, {"solution": "Check provider configuration before using", "percentage": 85}]'::jsonb, 'Terraform provider SDK knowledge', 'Custom provider accesses parent config', 'Misunderstanding meta context structure', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/75722726/accessing-provider-configuration-in-custom-terraform-provider', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform error refreshing state S3 does not have expected content', 'devops-terraform', 'HIGH', '[{"solution": "Restore valid state from backup: aws s3 cp", "percentage": 94}, {"solution": "Delete corrupted state and reinitialize", "percentage": 88}, {"solution": "Check S3 versioning to recover previous state", "percentage": 85}]'::jsonb, 'S3 backend configured with versioning', 'State file integrity restored', 'Not having state backups', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/57984714/error-refreshing-state-state-data-in-s3-does-not-have-the-expected-content', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform error refreshing state access denied', 'devops-terraform', 'HIGH', '[{"solution": "Verify IAM policy grants s3:GetObject on state bucket", "percentage": 96}, {"solution": "Check AWS credentials are current and valid", "percentage": 94}, {"solution": "Confirm bucket policy allows principal access", "percentage": 91}]'::jsonb, 'AWS S3 bucket with proper IAM', 'State file accessible, no access denied errors', 'Missing bucket or object-level permissions', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/49816309/terraform-error-refreshing-state-access-denied', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform error refreshing state BucketRegionError incorrect region', 'devops-terraform', 'HIGH', '[{"solution": "Specify correct bucket region: region = us-west-2", "percentage": 97}, {"solution": "Check S3 bucket is in expected region", "percentage": 95}, {"solution": "Update terraform backend configuration with correct region", "percentage": 93}]'::jsonb, 'S3 backend with regional configuration', 'Backend initialized with correct region', 'Assuming default region without checking', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/67860854/terraform-error-refreshing-state-bucketregionerror-incorrect-region', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform stuck on refreshing state when running against localstack', 'devops-terraform', 'HIGH', '[{"solution": "Set endpoint_url for s3 backend to localstack endpoint", "percentage": 92}, {"solution": "Configure skip_credentials_validation = true for local testing", "percentage": 89}, {"solution": "Check localstack container is running on correct port", "percentage": 87}]'::jsonb, 'LocalStack running with S3 service', 'State refresh completes within timeout', 'Using production endpoint for local testing', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/57106135/terraform-stuck-on-refreshing-state-when-running-against-localstack', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform could not refresh state known issue and workaround', 'devops-terraform', 'HIGH', '[{"solution": "Clear terraform cache: rm -rf .terraform", "percentage": 88}, {"solution": "Reinitialize backend: terraform init", "percentage": 91}, {"solution": "Check backend connectivity after infrastructure changes", "percentage": 85}]'::jsonb, 'Terraform initialized with backend', 'State refreshes successfully', 'Not clearing cache after backend changes', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/69162625/could-not-refresh-state-known-issue-and-known-workaround-is-not-working', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform error when manually moving state file and running plan', 'devops-terraform', 'HIGH', '[{"solution": "Use terraform state mv instead of manual file moves", "percentage": 97}, {"solution": "Update .terraform/terraform.tfstate after moving", "percentage": 92}, {"solution": "Rerun terraform init to resync state", "percentage": 89}]'::jsonb, 'Understanding of terraform state management', 'Plan shows no resource recreation', 'Manual state file manipulation without terraform commands', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/72171964/error-when-manually-moving-terraform-state-file-and-running-terraform-plan', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform error failed to load plugin schemas', 'devops-terraform', 'HIGH', '[{"solution": "Clear plugin cache: rm -rf .terraform/providers", "percentage": 93}, {"solution": "Run terraform init -upgrade to fetch latest providers", "percentage": 91}, {"solution": "Check provider version constraints are reasonable", "percentage": 88}]'::jsonb, 'Terraform with provider configuration', 'Provider plugins loaded successfully', 'Corrupted provider cache or network issues', 0.9, 'haiku', NOW(), 'https://stackoverflow.com/questions/70407525/terraform-gives-errors-failed-to-load-plugin-schemas', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform init command is failing in terraform file', 'devops-terraform', 'HIGH', '[{"solution": "Check terraform block syntax: terraform { required_version }", "percentage": 94}, {"solution": "Verify required_providers block is properly formatted", "percentage": 91}, {"solution": "Ensure backend block has correct configuration", "percentage": 89}]'::jsonb, 'Terraform configuration file', 'Terraform init completes without errors', 'Missing or malformed terraform block', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/63647764/the-terraform-init-command-is-failing-in-my-tf-file', 'admin:1764220197');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Having errors when initialize terraform', 'devops-terraform', 'HIGH', '[{"solution": "Check internet connectivity for provider downloads", "percentage": 90}, {"solution": "Verify terraform version compatibility", "percentage": 88}, {"solution": "Review error logs: export TF_LOG=DEBUG for details", "percentage": 91}]'::jsonb, 'Terraform installed and configured', 'Terraform init completes, .terraform directory created', 'Network issues or version mismatches', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/75904766/having-errors-when-initialize-terraform', 'admin:1764220197');

COMMIT;