INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('How to handle errors in Gin middleware', 'gin', 'HIGH', '[{"solution": "Use middleware with c.Next() to handle errors after route execution, check c.Errors for accumulated errors", "percentage": 95}, {"solution": "Use c.AbortWithError() or c.Error() to attach errors to context instead of returning directly", "percentage": 90}, {"solution": "Process errors in middleware after c.Next() completes", "percentage": 88}]'::jsonb, 'Gin framework, Go error handling', 'Centralized error handling without duplicating logic in each handler', 'Forgetting to call c.Next() before error handling, returning early instead of using middleware', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/69948784/how-to-handle-errors-in-gin-middleware', 'admin:1764210424'),

('Better error handling in Gin Gonic', 'gin', 'HIGH', '[{"solution": "Use middleware with JSONAppErrorReporter to handle all errors centrally", "percentage": 92}, {"solution": "Use c.Error(err) to attach errors to context, then process in middleware", "percentage": 90}, {"solution": "Avoid putting utils functions in error paths, use middleware instead", "percentage": 88}]'::jsonb, 'Go, error types, http status codes', 'All errors handled consistently with proper HTTP status codes', 'Treating middleware error handling like Express.js next(err) pattern', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/48224908/better-error-handling', 'admin:1764210424'),

('How to display custom error and abort in Golang Gin', 'gin', 'HIGH', '[{"solution": "Use c.AbortWithStatusJSON() instead of c.JSON() to properly abort request chain", "percentage": 94}, {"solution": "Return bool from error handler and check result before continuing execution", "percentage": 90}, {"solution": "Use wrapper function to convert error-returning handlers to valid Gin handlers", "percentage": 87}]'::jsonb, 'Gin Context, http StatusCodes', 'Request properly aborted with correct status code and JSON response', 'Using c.Abort() without status (only stops middleware chain), not returning from handler after abort', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/57837595/how-to-display-custom-error-and-abort-in-golang-gin', 'admin:1764210424'),

('How to return custom error if validation failed with Gin', 'gin', 'MEDIUM', '[{"solution": "Use reflection to extract json tags from struct fields and match with validation errors", "percentage": 85}, {"solution": "Convert field names to snake_case for JSON responses", "percentage": 78}, {"solution": "Iterate over validator.ValidationErrors and use reflect.TypeOf() to get field tags", "percentage": 82}]'::jsonb, 'Go reflection, validator.ValidationErrors, struct tags', 'Validation errors returned with correct field names matching JSON tags', 'Not handling missing json tags, not checking for FieldByName errors, assuming all fields have tags', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/50523102/how-to-return-custom-error-if-validation-failed-with-gin', 'admin:1764210424'),

('Validation error is being caught as decoding error in Go Gin', 'gin', 'MEDIUM', '[{"solution": "Check validator package version matches Gin''s validator dependency", "percentage": 96}, {"solution": "Use errors.As(err, &validationErrs) for safer type assertion", "percentage": 92}, {"solution": "Handle both validator.ValidationErrors and json.UnmarshalTypeError separately", "percentage": 88}]'::jsonb, 'Go error handling, type assertions, ShouldBindJSON', 'Validation errors properly distinguished from decoding errors', 'Version mismatch between validator package and Gin''s validator, unsafe type assertion with .()', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/79035793/validation-error-is-being-caught-as-a-decoding-error-in-go-gin-framework', 'admin:1764210424'),

('How to get field with error from Gin binding validation', 'gin', 'MEDIUM', '[{"solution": "Implement custom Validate() method on models instead of relying on playground validation", "percentage": 93}, {"solution": "Use custom validator that returns field-specific error messages", "percentage": 89}, {"solution": "Embed structs to reuse validation logic across models", "percentage": 85}]'::jsonb, 'Go struct validation, type parsing, error handling', 'Field-level error information available for all validation scenarios including parse errors', 'Expecting full error details from parse errors (int parsing), treating all errors uniformly', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/51920940/how-to-get-field-with-error-from-gin-binding-validation', 'admin:1764210424'),

('Gin Gonic confusing response status codes', 'gin', 'MEDIUM', '[{"solution": "Use c.AbortWithStatusJSON() directly in handler instead of calling separate function", "percentage": 95}, {"solution": "Ensure response functions call AbortWithStatusJSON, not just JSON with status", "percentage": 93}, {"solution": "Test status codes with curl -i or check response headers, not just handler logic", "percentage": 90}]'::jsonb, 'HTTP status codes, Gin context, response functions', 'Correct status code returned (422 for validation, 201 for created)', 'Calling c.JSON() after setting status in separate function, not using AbortWithStatusJSON', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/76512267/gin-gonic-framework-confusing-response-status-codes', 'admin:1764210424'),

('Gin Gonic custom error message fails when invalid data sent', 'gin', 'MEDIUM', '[{"solution": "Use type assertion safely with ok check: errs, ok := err.(validator.ValidationErrors)", "percentage": 94}, {"solution": "Handle json.UnmarshalTypeError separately from validator.ValidationErrors", "percentage": 91}, {"solution": "Check error type before casting to specific validation error type", "percentage": 89}]'::jsonb, 'Go type assertions, error handling, JSON unmarshaling', 'Custom error formatter handles both validation and type conversion errors', 'Unsafe type assertion with .(type), not checking for UnmarshalTypeError', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/69367914/gin-gonic-custom-error-message-fails-when-invalid-data-sent', 'admin:1764210424'),

('Panic error when trying to serve a Gin Gonic app', 'gin', 'HIGH', '[{"solution": "Use = assignment instead of := when assigning to global Router variable", "percentage": 97}, {"solution": "Avoid shadowing global variables with local := declarations", "percentage": 96}, {"solution": "Check that global Router is properly initialized before calling Run()", "percentage": 94}]'::jsonb, 'Go variable scoping, Gin engine initialization, global state', 'App starts and serves requests without nil pointer panic', 'Creating local Router variable with := instead of assigning to global, calling Run() on nil', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/40813776/panic-error-when-trying-to-serve-a-gin-gonic-app', 'admin:1764210424'),

('Gin error panic wildcard route conflicts with existing children', 'gin', 'MEDIUM', '[{"solution": "Use route groups to nest conflicting wildcard routes: resources := r.Group(''/resources/:rid'')", "percentage": 96}, {"solution": "Gin cannot distinguish /resources/otherroute from /resources/:id, use groups to separate them", "percentage": 94}, {"solution": "Order routes carefully or refactor to avoid mixing static and dynamic segments at same level", "percentage": 90}]'::jsonb, 'Gin routing, URL patterns, route conflicts', 'No panic on route registration, all routes accessible with correct handlers', 'Mixing static paths (otherroute) with dynamic segments (:id) at same level, expecting Gin to disambiguate', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/59147492/gin-error-panic-wildcard-route-conflicts-with-existing-children', 'admin:1764210424');
