INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERR_MODULE_NOT_FOUND: Cannot find module', 'nodejs', 'VERY_HIGH', '[{"solution": "Specify file extensions when using ES6 imports: import {urls} from ''./helpers.js''", "percentage": 95}, {"solution": "Use correct relative paths: require(''./src/utils/utils.js'') from root", "percentage": 92}, {"solution": "Use --es-module-specifier-resolution=node flag to auto-resolve .js files", "percentage": 75}]'::jsonb, 'Node.js ESM or CommonJS module system', 'Module imports successfully without errors', 'Missing file extensions in ES6 imports, incorrect relative paths', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/65384754/', 'admin:1764255713'),

('ERR_REQUIRE_ESM: require() of ES Module not supported', 'nodejs', 'VERY_HIGH', '[{"solution": "Use dynamic import instead: const chalk = await import(''chalk'')", "percentage": 92}, {"solution": "Add ''type'': ''module'' to package.json to use ES6 modules", "percentage": 88}, {"solution": "Downgrade package to earlier version supporting CommonJS", "percentage": 70}]'::jsonb, 'Node.js 12+, ES6 module support', 'Module imports without ERR_REQUIRE_ESM error', 'Mixing CommonJS require with ESM-only packages, incorrect tsconfig module settings', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/57169793/', 'admin:1764255713'),

('EADDRINUSE: Address already in use', 'nodejs', 'VERY_HIGH', '[{"solution": "Kill process on port: sudo lsof -i :3000 && kill -9 <PID>", "percentage": 98}, {"solution": "Use server.on(''listening'') to verify server is running before restarting", "percentage": 88}, {"solution": "Set SO_REUSEADDR socket option or use different port", "percentage": 75}]'::jsonb, 'Node.js running server, port access', 'Server starts without EADDRINUSE error', 'Not killing previous process, attempting to use same port immediately', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/9898372/', 'admin:1764255713'),

('ENOENT: no such file or directory', 'nodejs', 'VERY_HIGH', '[{"solution": "Verify file exists: check path with fs.existsSync() before reading", "percentage": 94}, {"solution": "Ensure config files are created in correct directory structure", "percentage": 90}, {"solution": "Run npm install to restore node_modules and dependencies", "percentage": 80}]'::jsonb, 'File system access, correct paths', 'File operations complete without ENOENT errors', 'Missing files, incorrect paths, incomplete npm install', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/43260643/', 'admin:1764255713'),

('FATAL ERROR: JavaScript heap out of memory', 'nodejs', 'HIGH', '[{"solution": "Increase max heap size: node --max-old-space-size=4096 app.js", "percentage": 96}, {"solution": "Set global NODE_OPTIONS: export NODE_OPTIONS=--max_old_space_size=4096", "percentage": 94}, {"solution": "Optimize data structures to reduce memory footprint", "percentage": 85}]'::jsonb, 'Node.js process, memory management', 'Application runs without heap memory exhaustion', 'Large data arrays in memory, memory leaks, infinite loops', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/38558989/', 'admin:1764255713'),

('UnhandledPromiseRejectionWarning: Unhandled promise rejection', 'nodejs', 'VERY_HIGH', '[{"solution": "Add .catch() handler to promise chains: promise.then().catch(err => console.log(err))", "percentage": 96}, {"solution": "Use try-catch with async-await: try { await func() } catch(err) { }", "percentage": 95}, {"solution": "Chain .catch() directly: promise.then(fn).catch(fn)", "percentage": 93}]'::jsonb, 'Promise/async handling, error management', 'No UnhandledPromiseRejectionWarning in logs', 'Promises without .catch(), async without error handling', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/40500490/', 'admin:1764255713'),

('ERR_UNKNOWN_FILE_EXTENSION: Unknown file extension .ts', 'nodejs', 'HIGH', '[{"solution": "Remove ''type'': ''module'' from package.json for ts-node", "percentage": 90}, {"solution": "Use tsx instead of ts-node: npm i -D tsx && npx tsx src/index.ts", "percentage": 92}, {"solution": "Configure ts-node-esm flag in tsconfig.json", "percentage": 75}]'::jsonb, 'TypeScript setup, Node.js ESM', 'TypeScript files run without file extension errors', 'Conflicting ESM module settings, incorrect ts-node configuration', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/62096269/', 'admin:1764255713'),

('ERR_HTTP_HEADERS_SENT: Cannot set headers after they are sent to the client', 'nodejs', 'HIGH', '[{"solution": "Return after sending response: if (!user) { res.json({error}); return; }", "percentage": 97}, {"solution": "Use res.status().json() instead of chaining res.send().json()", "percentage": 95}, {"solution": "Ensure only one res.json/res.send/res.end per request handler", "percentage": 94}]'::jsonb, 'Express/HTTP routing, response handling', 'HTTP responses complete without header conflicts', 'Multiple response sends, missing return statements, improper branching', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/52122272/', 'admin:1764255713'),

('ERR_SOCKET_TIMEOUT: Socket timeout', 'nodejs', 'HIGH', '[{"solution": "Increase npm timeout: npm config set fetch-retry-maxtimeout 120000", "percentage": 88}, {"solution": "Check npm version and downgrade if needed to 8.5.1 or earlier", "percentage": 82}, {"solution": "Verify network connectivity and DNS resolution", "percentage": 75}]'::jsonb, 'npm operations, network connections', 'npm install/operations complete without timeout', 'Network issues, npm misconfiguration, slow DNS', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/72442682/', 'admin:1764255713'),

('ERR_TLS_CERT_ALTNAME_INVALID: Hostname/IP does not match certificate''s altnames', 'nodejs', 'HIGH', '[{"solution": "Add www to URL if certificate includes it: https://www.domain.com", "percentage": 90}, {"solution": "Set Host header with domain registered in certificate", "percentage": 85}, {"solution": "Disable certificate verification for self-signed certs (dev only): NODE_TLS_REJECT_UNAUTHORIZED=0", "percentage": 60}]'::jsonb, 'TLS/HTTPS connections, certificate validation', 'HTTPS connections succeed without certificate errors', 'Using wrong domain in certificate, self-signed cert issues', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/74297626/', 'admin:1764255713'),

('TypeError: Cannot read property of undefined', 'nodejs', 'VERY_HIGH', '[{"solution": "Check if object exists before accessing properties: if (obj && obj.prop)", "percentage": 96}, {"solution": "Use optional chaining: obj?.prop?.nested", "percentage": 95}, {"solution": "Validate function returns before accessing properties", "percentage": 92}]'::jsonb, 'JavaScript object handling, null checks', 'No TypeError thrown when accessing properties', 'Missing null/undefined checks, incorrect initialization', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/40219733/', 'admin:1764255713'),

('ERR_INVALID_ARG_TYPE: The argument must be of type X. Received Y', 'nodejs', 'HIGH', '[{"solution": "Validate .env file exists with all required variables", "percentage": 91}, {"solution": "Ensure function arguments match expected types before calling", "percentage": 93}, {"solution": "Check environment variables are loaded: console.log(process.env.VAR)", "percentage": 88}]'::jsonb, 'Type validation, environment configuration', 'Functions execute with correct argument types', 'Missing .env file, undefined environment variables', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/63851344/', 'admin:1764255713'),

('ERR_STREAM_DESTROYED: Cannot call write after a stream was destroyed', 'nodejs', 'MEDIUM', '[{"solution": "Add error handler to stream: stream.on(''error'', (e) => {})", "percentage": 94}, {"solution": "Check if directory exists before writing logs", "percentage": 92}, {"solution": "Ensure file permissions allow write access (chmod 755)", "percentage": 88}]'::jsonb, 'Stream handling, file operations', 'Streams complete without destroyed errors', 'Insufficient permissions, missing directories, closed streams', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/63537576/', 'admin:1764255713'),

('Async callback error: Cannot await non-promise result', 'nodejs', 'MEDIUM', '[{"solution": "Wrap callback in Promise: new Promise((resolve) => dns.lookup(url, resolve))", "percentage": 93}, {"solution": "Use async-await syntax instead of callbacks", "percentage": 95}, {"solution": "Convert callback-based function to Promise-based", "percentage": 92}]'::jsonb, 'Async/await, Promise handling', 'Async operations complete successfully', 'Mixing callbacks with await, improper Promise wrapping', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/60314287/', 'admin:1764255713'),

('ReferenceError: X is not defined', 'nodejs', 'MEDIUM', '[{"solution": "Exit Node REPL with process.exit() before running commands", "percentage": 97}, {"solution": "Ensure variable is declared in scope before use", "percentage": 95}, {"solution": "Check imported modules exist: require(''module-name'')", "percentage": 92}]'::jsonb, 'Variable scope, REPL usage', 'Code executes without ReferenceError', 'Variable not in scope, REPL context confusion, missing imports', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/27170037/', 'admin:1764255713'),

('SyntaxError: Unexpected token import/export', 'nodejs', 'MEDIUM', '[{"solution": "Enable ES6 modules: add ''type'': ''module'' to package.json", "percentage": 93}, {"solution": "Use CommonJS require instead: const express = require(''express'')", "percentage": 92}, {"solution": "Run with --experimental-modules flag on Node 12-13", "percentage": 70}]'::jsonb, 'ES6 module support, syntax compatibility', 'Code parses without SyntaxError', 'ES6 import/export without proper module setup', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/39436322/', 'admin:1764255713'),

('ECONNREFUSED: Connection refused', 'nodejs', 'HIGH', '[{"solution": "Use 127.0.0.1 instead of localhost for Node.js DNS issues", "percentage": 94}, {"solution": "Ensure server is running before making requests", "percentage": 96}, {"solution": "Add uncaughtException handler to catch connection errors", "percentage": 85}]'::jsonb, 'Network connections, server setup', 'Network connections establish successfully', 'Server not running, DNS lookup issues, wrong host/port', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/14168433/', 'admin:1764255713'),

('EACCES: Permission denied when writing file', 'nodejs', 'HIGH', '[{"solution": "Use relative paths in current directory: ./book not /book", "percentage": 96}, {"solution": "Check file permissions: chmod 755 directory/", "percentage": 94}, {"solution": "Ensure Node.js process user owns write directory", "percentage": 92}]'::jsonb, 'File system permissions, directory structure', 'File write operations complete without EACCES', 'Using root paths, insufficient permissions, wrong directory owner', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/53846153/', 'admin:1764255713'),

('ETIMEDOUT: Connection timeout', 'nodejs', 'HIGH', '[{"solution": "Add error handler: stream.on(''error'', (err) => { if (err.code === ''ETIMEDOUT'') ... })", "percentage": 90}, {"solution": "Increase request timeout option in http/fetch call", "percentage": 88}, {"solution": "Implement retry logic with exponential backoff", "percentage": 85}]'::jsonb, 'HTTP requests, network operations', 'Network requests complete without timeout', 'Network issues, server slow, timeout too low', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/23632914/', 'admin:1764255713'),

('EPIPE: Write to closed pipe/stream', 'nodejs', 'MEDIUM', '[{"solution": "Add error handler to pipe: readStream.pipe(writeStream).on(''error'', handler)", "percentage": 93}, {"solution": "Check if receiving process is still running", "percentage": 88}, {"solution": "Handle broken pipe gracefully without crashing", "percentage": 90}]'::jsonb, 'Stream piping, child processes', 'Stream operations complete without EPIPE', 'Piping to closed stream, process termination during pipe', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/51839293/', 'admin:1764255713'),

('RangeError: Maximum call stack size exceeded', 'nodejs', 'MEDIUM', '[{"solution": "Wrap recursive calls in setImmediate/setTimeout to clear stack: setImmediate(() => recursiveFunc())", "percentage": 94}, {"solution": "Increase stack size: ulimit -s 65500 && node --stack-size=65500 app.js", "percentage": 75}, {"solution": "Refactor to iterative approach instead of recursive", "percentage": 88}]'::jsonb, 'Recursion, call stack management', 'Recursive operations complete without stack overflow', 'Deep recursion without yielding control, no async breaks', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/20936486/', 'admin:1764255713'),

('Module.exports vs exports confusion', 'nodejs', 'MEDIUM', '[{"solution": "Use module.exports = { func } instead of exports = { }", "percentage": 96}, {"solution": "Require correctly: const { func } = require(''./module'')", "percentage": 95}, {"solution": "Consistency: always use module.exports, never reassign exports", "percentage": 93}]'::jsonb, 'CommonJS modules, exports', 'Modules export and import correctly', 'Reassigning exports object, incorrect require patterns', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/40219733/', 'admin:1764255713'),

('Cannot find module with extension in CommonJS', 'nodejs', 'MEDIUM', '[{"solution": "Use correct path without extension: require(''./file'') not require(''./file.js'')", "percentage": 92}, {"solution": "Check relative paths are correct: ../ not /", "percentage": 94}, {"solution": "Ensure file exists in node_modules or project", "percentage": 90}]'::jsonb, 'CommonJS module resolution', 'Modules resolve without errors', 'Incorrect file paths, missing files, wrong directory structure', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/16163176/', 'admin:1764255713'),

('Promise rejection without catch in async code', 'nodejs', 'HIGH', '[{"solution": "Always chain .catch(): someAsyncCall().then(fn).catch(errorHandler)", "percentage": 95}, {"solution": "Use try-catch in async functions: try { await call() } catch(e) {}", "percentage": 94}, {"solution": "Add global unhandledRejection handler: process.on(''unhandledRejection'', handler)", "percentage": 80}]'::jsonb, 'Promise handling, error management', 'All promise rejections are handled', 'Missing catch handlers, async without error handling', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/67587274/', 'admin:1764255713'),

('ERR_REQUIRE_CALL_IN_CALLBACK not awaited', 'nodejs', 'LOW', '[{"solution": "Ensure all async operations resolve before exit", "percentage": 88}, {"solution": "Use process.exit() only after all callbacks complete", "percentage": 85}]'::jsonb, 'Async operation completion, event loop', 'All async operations complete before process exit', 'Exiting before callbacks finish, race conditions', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/57169793/', 'admin:1764255713'),

('CORS headers not set correctly in Express', 'nodejs', 'MEDIUM', '[{"solution": "Enable CORS: const cors = require(''cors''); app.use(cors())", "percentage": 93}, {"solution": "Set specific origins: app.use(cors({origin: ''http://localhost:3000''}))", "percentage": 91}, {"solution": "Add CORS headers manually in response", "percentage": 85}]'::jsonb, 'Express setup, HTTP headers', 'API calls from different origins work without CORS errors', 'Missing CORS middleware, incorrect origin whitelist', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/52122272/', 'admin:1764255713'),

('fs.readFile encoding issues with non-UTF8', 'nodejs', 'MEDIUM', '[{"solution": "Specify encoding explicitly: fs.readFile(path, ''utf8'', callback)", "percentage": 94}, {"solution": "Handle Buffer when no encoding specified", "percentage": 90}, {"solution": "Use correct encoding for file type (latin1, base64, etc)", "percentage": 88}]'::jsonb, 'File operations, character encoding', 'Files read correctly with proper encoding', 'Missing encoding parameter, wrong encoding for file type', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/43260643/', 'admin:1764255713'),

('Mixing callback and promise patterns', 'nodejs', 'MEDIUM', '[{"solution": "Use promisify: const {promisify} = require(''util''); const fn = promisify(callbackFn)", "percentage": 92}, {"solution": "Standardize on async-await throughout codebase", "percentage": 94}, {"solution": "Wrap callbacks in Promise constructor for compatibility", "percentage": 88}]'::jsonb, 'Promise/callback patterns, code consistency', 'Code uses consistent async patterns throughout', 'Mixing old callback style with new promises/async-await', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/60314287/', 'admin:1764255713'),

('next() called multiple times in Express middleware', 'nodejs', 'MEDIUM', '[{"solution": "Return after next(): if (error) { next(err); return; }", "percentage": 96}, {"solution": "Use proper middleware chaining without duplicate calls", "percentage": 94}, {"solution": "Check middleware ordering to prevent double execution", "percentage": 90}]'::jsonb, 'Express middleware, request handling', 'Express middleware executes exactly once per request', 'Calling next() in multiple code paths, missing returns', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/52122272/', 'admin:1764255713');
