-- Vue Other Errors Migration
-- Mined on 2025-11-26

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EPERM: operation not permitted, unlink Vue CLI npm install', 'vue', 'HIGH', '[{"solution": "Delete existing @vue and vue-cli folders from C:\\Users\\AppData\\Roaming\\npm\\node_modules, then run npm install command as Administrator", "percentage": 92}, {"solution": "Clear npm cache with npm cache clean --force before reinstalling", "percentage": 85}]'::jsonb, 'Administrator access, node/npm installed', 'npm install completes without EPERM errors', 'Running from non-administrator terminal, not clearing node_modules before reinstall', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/46137890/npm-err-code-eperm-while-installing-vue-cli', 'admin:1764191796'),

('Uncaught TypeError: Cannot read properties of undefined (reading ''install'') Vue runtime', 'vue', 'HIGH', '[{"solution": "Check Vuetify plugin import and use syntax - ensure Vue.use(Vuetify) is called with correct plugin instance", "percentage": 93}, {"solution": "Verify that vuetify/lib exports properly and no circular dependencies exist in import chain", "percentage": 88}]'::jsonb, 'Vuetify installed, Vue 3 or Vue 2 composition', 'App loads without console errors, Vuetify theme applies correctly', 'Missing Vue.use() call, incorrect import path for Vuetify', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/72252237/vue-runtime-error-uncaught-typeerror-cannot-read-properties-of-undefined-rea', 'admin:1764191796'),

('Uncaught TypeError: Cannot read property ''name'' of null Vue template', 'vue', 'HIGH', '[{"solution": "Use v-if directive to guard template access: <p v-if=\"selectedTopic\">{{ selectedTopic.name }}</p>", "percentage": 95}, {"solution": "Initialize data property with empty object instead of null: data() { return { selectedTopic: {} } }", "percentage": 89}, {"solution": "Use ternary operator in template: {{ selectedTopic ? selectedTopic.name : ''No topic'' }}", "percentage": 87}]'::jsonb, 'Vue component with data binding, asynchronous data loading', 'Template renders without TypeError, null data handled gracefully', 'Accessing nested properties on null/undefined without null-checking, not initializing data properly', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/43104848/vue-syntax-error', 'admin:1764191796'),

('Uncaught SyntaxError: Must be called at the top of a setup function Vue i18n', 'vue', 'MEDIUM', '[{"solution": "Call useI18n() directly at the top of setup function before any conditionals or nested function calls", "percentage": 91}, {"solution": "Use app.use(i18n) instead of app.use(VueAxios, axios, i18n) - separate plugin registration calls", "percentage": 90}]'::jsonb, 'Vue 3 Composition API, vue-i18n installed', 'useI18n() returns translation function without errors, templates render translated text', 'Calling composable inside nested functions, registering multiple plugins in single app.use() call', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/72651884/vue-3-usei18n-uncaught-syntaxerror-must-be-called-at-the-top-of-a-setup-f', 'admin:1764191796'),

('Uncaught ReferenceError: currentPage is not defined Vue method', 'vue', 'HIGH', '[{"solution": "Access data properties via ''this'' keyword in methods: this.currentPage instead of currentPage", "percentage": 96}, {"solution": "Ensure arrow functions are not used in methods definition as they bind different ''this'' context", "percentage": 92}]'::jsonb, 'Vue component with methods and data properties', 'Methods access data properties without ReferenceError, console logs show correct values', 'Forgetting ''this'' prefix, using arrow functions in method definitions', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/66707818/uncaught-referenceerror-xxx-is-not-defined-vue', 'admin:1764191796'),

('ENOSPC: System limit for number of file watchers reached Vue Vite development', 'vue', 'MEDIUM', '[{"solution": "Increase Linux inotify limit: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p", "percentage": 89}, {"solution": "Configure Vite to ignore non-relevant folders in vite.config.js server.watch.ignored array (vendor, storage, etc)", "percentage": 94}]'::jsonb, 'Linux system, Vue + Vite dev server, large project with many dependencies', 'npm run dev starts without ENOSPC errors, file watchers available for project files', 'Not excluding vendor folders from watch, system inotify limit too low, running on high-file-count projects', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/73365921/laravel-9-switched-to-vite-now-enospc-limit-of-file-watchers-reached', 'admin:1764191796'),

('Hydration mismatch warning Vue SSR server-side rendering', 'vue', 'MEDIUM', '[{"solution": "In Vue 3.5+, use data-allow-mismatch attribute on elements with expected mismatches", "percentage": 88}, {"solution": "Suppress warning globally via Vue.config.warning = false (use sparingly in dev only)", "percentage": 75}, {"solution": "Ensure server-rendered HTML and client DOM match exactly - check for Date.now(), Math.random() calls", "percentage": 92}]'::jsonb, 'Vue 3 SSR setup, server-side and client-side rendering', 'SSR page loads without hydration mismatch warnings, client correctly hydrates server DOM', 'Ignoring hydration mismatches instead of fixing root cause, using non-deterministic data in server rendering', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/68438016/vuessr-suppress-hydration-mismatch-warning', 'admin:1764191796'),

('ESLint exhaustive-deps warning Vue Composition API dependency array', 'vue', 'MEDIUM', '[{"solution": "Include all variables used within the effect/hook in the dependency array to ensure proper reactivity", "percentage": 90}, {"solution": "If variable should not trigger re-run, extract it outside the effect or use useCallback to memoize it", "percentage": 87}, {"solution": "As last resort, disable rule with // eslint-disable-next-line react-hooks/exhaustive-deps (document why) only if intentional", "percentage": 60}]'::jsonb, 'Vue 3 Composition API with watchers, reactive state management', 'Effect/watcher runs only when intended dependencies change, no stale closures, ESLint rule satisfied', 'Missing dependencies in array causing stale closures, not understanding reactive vs static dependencies, disabling rule without understanding impact', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/71268880/eslint-exhaustive-deps-warning-in-useeffect', 'admin:1764191796');
