INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Vite React Svelte errors on npm run dev', 'vite', 'HIGH', '[{"solution": "Update vite to latest version: npm i -D vite@latest", "percentage": 85}, {"solution": "Clear node_modules and package-lock.json, then npm install", "percentage": 80}, {"solution": "Downgrade to vite@^5 if using vite 6.x: npm install vite@^5", "percentage": 75}]'::jsonb, 'Node.js, npm, vite project', 'Dev server starts without errors', 'Mixing vite versions, stale dependencies', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/79296528/errors-while-starting-vite-react', 'admin:1764210840'),

('Vite ignoring compiler errors until file used at runtime', 'vite', 'HIGH', '[{"solution": "Run tsc --noEmit --watch in parallel for type checking", "percentage": 95}, {"solution": "Use vite-plugin-checker to integrate type checking: npm i vite-plugin-checker", "percentage": 92}, {"solution": "Chain type check with build: tsc --noEmit && npm run build", "percentage": 88}]'::jsonb, 'TypeScript, Vite configuration', 'All errors caught before runtime', 'Assuming Vite does type checking (it doesn''t)', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/76480836/vite-is-ignoring-compiler-errors-until-the-file-is-used-at-runtime', 'admin:1764210840'),

('Vite errors and warnings not appearing in terminal', 'vite', 'MEDIUM', '[{"solution": "Use vite-plugin-terminal: npm i vite-plugin-terminal", "percentage": 70}, {"solution": "Install Console Ninja VSCode extension for terminal logging", "percentage": 75}, {"solution": "Configure vite.config.ts to forward browser errors to terminal", "percentage": 65}]'::jsonb, 'React, TypeScript, Vite setup', 'Errors display in terminal during dev', 'Only checking browser console, missing vite config', 0.70, 'haiku', NOW(), 'https://stackoverflow.com/questions/77781537/to-display-errors-and-warnings-in-the-terminal-for-a-react-app-with-vite', 'admin:1764210840'),

('TypeScript errors during Vite build with HeadlessUI', 'vite', 'MEDIUM', '[{"solution": "Remove tsc from build script: change tsc && vite build to just vite build", "percentage": 90}, {"solution": "Use vite build without type checking if types are correct in IDE", "percentage": 85}]'::jsonb, 'TypeScript, Vite, HeadlessUI components', 'Build succeeds without type checking', 'Type checking conflicting with framework types', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/76684190/typescript-errors-with-build-command-in-vite', 'admin:1764210840'),

('Uncaught TypeError production build with Day.js import', 'vite', 'HIGH', '[{"solution": "Use default import instead of namespace: import dayjs from dayjs instead of import * as dayjs", "percentage": 94}, {"solution": "Verify library export format matches your import style", "percentage": 90}]'::jsonb, 'Vite, React, TypeScript, Day.js', 'Production build runs without errors', 'Mixing namespace and default imports with bundlers', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/76754734/error-in-production-build-with-vite-react-error-in-uncaught-typeerror-is-n', 'admin:1764210840'),

('Customize Vite error overlay modal on dev server', 'vite', 'LOW', '[{"solution": "Vite does not provide API for custom error overlay, built into dev server", "percentage": 5}, {"solution": "Use error boundary components in React/Vue for application-level errors", "percentage": 80}, {"solution": "Create custom error handler middleware instead of replacing overlay", "percentage": 75}]'::jsonb, 'Vite dev server, React/Vue project', 'Error handling implemented at app level', 'Expecting Vite dev server overlay to be customizable', 0.75, 'haiku', NOW(), 'https://stackoverflow.com/questions/77799426/handling-errors-with-vite-dev-server', 'admin:1764210840'),

('ESLint errors preventing Vite dev server startup', 'vite', 'MEDIUM', '[{"solution": "Set failOnError: false in vite-plugin-eslint config", "percentage": 92}, {"solution": "Use lintOnStart: false if you want to skip startup linting", "percentage": 88}]'::jsonb, 'Vite, React, ESLint, vite-plugin-eslint', 'Dev server starts despite ESLint errors', 'ESLint failing on startup by default in plugin', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/75161132/run-vite-server-despite-errors', 'admin:1764210840'),

('Vue3 production build loses error location information', 'vite', 'MEDIUM', '[{"solution": "Enable source maps in production: add sourcemap: true to vite.config.js build options", "percentage": 93}, {"solution": "Use error tracking service with source map support (Sentry, etc)", "percentage": 85}]'::jsonb, 'Vue3, Vite, production deployment', 'Error stack traces show original file names and line numbers', 'Disabling source maps in production', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/73864115/vue3-vite-error-handling-in-production', 'admin:1764210840'),

('Vite includes removed module from cache', 'vite', 'MEDIUM', '[{"solution": "Run vite --force to clear and regenerate cache", "percentage": 95}, {"solution": "Manually delete node_modules/.vite/ directory and restart vite", "percentage": 90}]'::jsonb, 'Vite dev server, module management', 'Vite reflects current dependencies after cache clear', 'Forgetting vite caches prebundled dependencies', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/76926120/vite-includes-module-that-does-not-exist-how-to-clear-cache', 'admin:1764210840'),

('Yarn workspace dependency not updating in Vite cache', 'vite', 'MEDIUM', '[{"solution": "Run vite --force to rebundle workspace deps every time", "percentage": 92}, {"solution": "Exclude workspace from prebundling: optimizeDeps: { exclude: [''@namespace''] }", "percentage": 88}]'::jsonb, 'Vite, yarn workspaces, monorepo setup', 'Updated workspace exports available in vite cache', 'Vite caching workspace deps without hot reload', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/75907894/yarn-workspace-dependency-isnt-updated-in-vite-cache', 'admin:1764210840');
