-- Mining batch: General CORS errors (Haiku 4.5)
-- Date: 2025-11-26
-- Miner: admin:1764191441

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

-- Entry 1: Chrome localhost CORS issue
('Chrome does not support localhost for CORS requests - XMLHttpRequest cannot load. Origin localhost is not allowed by Access-Control-Allow-Origin', 'general', 'HIGH', '[{"solution": "Use a domain like localho.st (points to 127.0.0.1) instead of localhost, or start Chrome with --disable-web-security flag for testing only", "percentage": 95}, {"solution": "Use the Allow-Control-Allow-Origin Chrome extension as workaround for development", "percentage": 85}]'::jsonb, 'Chrome browser, CORS-enabled API, localhost testing setup', 'Requests from localhost domain work without Access-Control-Allow-Origin errors', 'Relying on Chrome extensions in production, forgetting that localhost is special case', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/10883211/why-does-my-http-localhost-cors-origin-not-work', 'admin:1764191441'),

-- Entry 2: CORS vs CORP differentiation
('Difference between CORS (Cross-Origin Resource Sharing) and CORP (Cross-Origin Resource Policy) - confused when to use each header', 'general', 'MEDIUM', '[{"solution": "CORS (Access-Control-Allow-Origin) allows foreign origins to REQUEST resources from your server. CORP (Cross-Origin-Resource-Policy) prevents foreign origins from EMBEDDING your resources (img, video, iframe). Use CORS for API endpoints, CORP for static assets", "percentage": 93}]'::jsonb, 'Understanding of same-origin policy, knowledge of HTTP headers', 'CORS requests succeed, embedded resources are properly restricted', 'Mixing up which header applies to which security concern, setting CORS when CORP is needed', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/72983230/how-is-corp-different-from-cors', 'admin:1764191441'),

-- Entry 3: Missing Access-Control-Allow-Origin header on API
('Access to XMLHttpRequest at external API blocked by CORS policy: Response to preflight request doesn''t pass access control check: No ''Access-Control-Allow-Origin'' header is present on the requested resource', 'general', 'CRITICAL', '[{"solution": "Create a backend proxy/middleware that forwards the request to the external API and adds CORS headers to the response. Frontend calls your backend instead of external API directly", "percentage": 96}, {"solution": "Request the external API provider to add CORS headers to their responses", "percentage": 70}]'::jsonb, 'Backend server (Node.js, Express, etc), ability to create proxy endpoint', 'Frontend can fetch from external API via your proxy, no CORS errors in browser console', 'Trying to add Access-Control-Allow-Origin headers on client-side (headers are response-only), calling external API directly from browser', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/72084470/how-to-solve-cors-error-while-fetching-an-external-api', 'admin:1764191441'),

-- Entry 4: Cloudflare CORS configuration for API Gateway
('Configure CORS for Access-Control-Allow-Origin header using Cloudflare when backend doesn''t support CORS headers', 'general', 'HIGH', '[{"solution": "Use Cloudflare Rules > Transform Rules > Modify Response Header to add Access-Control-Allow-Origin header. Set condition to Hostname, operator to Equals, value to your domain. Set header name to access-control-allow-origin and value to * or specific domain", "percentage": 94}, {"solution": "Use PageRules with Disable Security setting (deprecated), migrate to new Transform Rules", "percentage": 65}]'::jsonb, 'Cloudflare account access, domain managed by Cloudflare', 'CORS preflight requests from browser succeed, Access-Control-Allow-Origin header present in responses', 'Using old PageRules feature which is deprecated, setting wildcard * when specific domains needed for production', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/76983353/how-to-configure-cors-of-access-control-allow-origin-using-cloudflare', 'admin:1764191441'),

-- Entry 5: Go CORS implementation with rs/cors package
('Go backend with rs/cors package not enforcing CORS rules - GET request still works when only POST and OPTIONS allowed', 'general', 'HIGH', '[{"solution": "CORS filtering only applies to browser JavaScript (XHR/fetch). Direct HTTP clients (curl, Postman, Go clients) bypass CORS. Add middleware to handle OPTIONS preflight requests and return appropriate headers: Access-Control-Allow-Origin, Access-Control-Allow-Methods, Access-Control-Allow-Headers", "percentage": 92}, {"solution": "Implement custom CORS middleware that wraps your handler and properly validates OPTIONS requests before executing route handlers", "percentage": 88}]'::jsonb, 'Go http package, rs/cors package installed, understanding of CORS preflight mechanism', 'Browser XHR/fetch requests work correctly, non-browser clients bypass CORS as expected, OPTIONS requests return proper headers', 'Assuming CORS applies to all clients equally, not realizing CORS is browser-enforced only', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/64062803/how-to-enable-cors-in-go', 'admin:1764191441'),

-- Entry 6: DynamoDB Local CORS support
('DynamoDB Local returns no Access-Control-Allow-Origin header when called from browser JavaScript', 'general', 'HIGH', '[{"solution": "Start DynamoDB Local with --cors flag: java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar --cors \"*\" (or specify comma-separated domains)", "percentage": 97}, {"solution": "Use opaque responses or proxy through Node.js backend instead of direct browser-to-DynamoDB", "percentage": 80}]'::jsonb, 'DynamoDB Local installed and running, Java environment configured', 'Browser JavaScript can call DynamoDB Local without CORS errors, listTables and other operations succeed', 'Forgetting to add --cors flag, not escaping special characters in domain list', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/28702136/dynamodb-local-access-control-allow-origin', 'admin:1764191441'),

-- Entry 7: AWS Lambda DynamoDB CORS with API Gateway
('Access to fetch at Lambda API Gateway endpoint blocked by CORS policy: No ''Access-Control-Allow-Origin'' header even after adding headers to Lambda response', 'general', 'CRITICAL', '[{"solution": "Enable CORS on the API Gateway resource/method directly using AWS Console API Gateway > [resource] > Actions > Enable CORS and Replace CORS headers. This automatically adds mock integration for OPTIONS", "percentage": 96}, {"solution": "Manually add OPTIONS method to all endpoints returning proper CORS headers in Integration Response", "percentage": 94}]'::jsonb, 'AWS Lambda function, API Gateway endpoint, IAM permissions to modify API Gateway', 'Browser fetch() calls to API Gateway succeed, preflight OPTIONS returns CORS headers, data reaches Lambda', 'Adding CORS headers only in Lambda response without configuring API Gateway CORS, not handling OPTIONS preflight', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/61378284/cors-issue-confusion-with-aws-lambda-dynamodb-api-gateway-and-react', 'admin:1764191441'),

-- Entry 8: Sequelize database query returns CORS error
('Sequelize model query returns 500 Internal Server Error or CORS error when missing response headers', 'general', 'MEDIUM', '[{"solution": "Ensure Express middleware handles OPTIONS preflight requests before route handlers. Add cors middleware or manual OPTIONS handler: app.options(''*'', cors()). Set proper HTTP status and headers on all responses", "percentage": 91}, {"solution": "Switch from GET to POST request, ensure response body is properly formatted JSON, not raw object", "percentage": 75}]'::jsonb, 'Express.js server, Sequelize ORM, CORS middleware (or manual header handling)', 'Requests from browser succeed without CORS errors, both preflight and actual requests return 200', 'Returning error without proper headers, not implementing OPTIONS handler, sending undefined or non-JSON responses', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/55445898/cors-policy-no-access-control-allow-origin-500-internal-server-error-prob', 'admin:1764191441'),

-- Entry 9: SAML authentication triggers CORS error on redirect
('XMLHttpRequest cannot load [SAML IDP URL]. No ''Access-Control-Allow-Origin'' header when AJAX request triggers SAML login redirect', 'general', 'HIGH', '[{"solution": "Never make AJAX requests to trigger SAML login. Instead, ensure HTML page loads from server every time using cache-busting headers (Cache-Control: no-cache, no-store). HTML page load triggers SAML flow server-side before JavaScript runs", "percentage": 94}, {"solution": "Use a non-cached landing page that redirects to application after SAML login completes", "percentage": 89}]'::jsonb, 'SAML 2.0 IDP configured, Express.js or similar backend, understanding of SAML flow', 'Users can access protected resources without CORS errors, SAML login completes before AJAX calls made', 'Trying to make AJAX calls that trigger SAML flow, expecting IDP to set CORS headers', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/36316574/getting-cors-error-with-saml-2-0', 'admin:1764191441'),

-- Entry 10: DynamoDB Local CORS configuration with specific domains
('DynamoDB Local --cors parameter not accepting specific domain names, only wildcard * works', 'general', 'MEDIUM', '[{"solution": "Use the format: java -jar DynamoDBLocal.jar --cors \"domain1.com,domain2.com\" (comma-separated, no spaces). Ensure domains are exact matches with protocol if needed", "percentage": 88}, {"solution": "Use wildcard * for development, configure reverse proxy (nginx/Apache) for production CORS handling", "percentage": 82}]'::jsonb, 'DynamoDB Local running, knowledge of allowed CORS domains', 'DynamoDB Local accepts requests only from specified domains, wildcard requests blocked', 'Including spaces in comma-separated list, incorrect domain format, using patterns instead of exact domains', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/30957473/dynamodb-local-cors-example', 'admin:1764191441');
