-- Vue Migration Errors Mining
-- Mined from Stack Overflow real user questions
-- Date: 2025-11-26

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Vue 2 to Vue 3 migration strategy for updating codebase with many libraries', 'vue', 'HIGH', '[{"solution": "Migrate Vue core first, then update external libraries (vue-chart-js, primevue, vuex) to their Vue 3 versions separately. Use Vue 3 migration build (@vue/compat) as intermediate compatibility layer during transition.", "percentage": 95}, {"solution": "Create large PR handling all dependencies at once if using migration build for all libraries simultaneously", "percentage": 70}]'::jsonb, 'Vue 2.7.8 codebase with external Vue 2 libraries installed', 'All external libraries upgraded to Vue 3 versions, application runs without @vue/compat warnings', 'Attempting to migrate libraries without using compatibility layer, circular dependency issues between library versions', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/76306554/vue-2-to-vue-3-migration-strategy-for-updating-codebase-with-many-libraries', 'admin:1764191855'),

('Class-based components not compatible with Vue 3 composition API', 'vue', 'HIGH', '[{"solution": "Migrate from class-based components (vue-class-component) to function-based components using composition API. Replace @Component decorators with <script setup> syntax.", "percentage": 93}, {"solution": "Use @vue/compat mode to maintain class components temporarily, plan migration to composition API over time", "percentage": 75}]'::jsonb, 'Vue 2 codebase using vue-class-component or class-based syntax', 'All components using composition API, TypeScript intellisense working, no Vue 3 migration warnings', 'Assuming class components will work in Vue 3 as-is, mixing class and composition API in same component, not updating TypeScript decorators', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/58367558/best-practices-for-easy-migration-from-vuejs2-to-vuejs3', 'admin:1764191855'),

('Vuetify 2 to Vuetify 3 migration with Webpack 4 configuration', 'vue', 'HIGH', '[{"solution": "Upgrade Vuetify to v3.3.2 in package.json, update webpack-plugin-vuetify to v2.0.1, replace vue-cli-plugin-vuetify (~2.0.6) with webpack-plugin-vuetify. Consider migrating to Vite for better performance.", "percentage": 91}, {"solution": "Keep Webpack 4 with @vue/compat mode while gradual migration to Vue 3, upgrade Vuetify components incrementally", "percentage": 72}]'::jsonb, 'Vue 2.7.14 with Vuetify 2, Webpack 4.46.0, vue-cli-service', 'Vuetify 3 components render without style errors, all Material Design icons display correctly, theme configuration works', 'Missing plugin configuration updates, incompatible sass-loader version, mixing Vuetify 2 and 3 components', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/76390970/vue-2-to-vue-3-migration-vuetify-2-to-vuetify-3', 'admin:1764191855'),

('ENOSPC system limit for file watchers exceeded during Vue 3 Vite migration', 'vue', 'MEDIUM', '[{"solution": "On Linux, increase inotify file watcher limit: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p", "percentage": 88}, {"solution": "Configure Vite to ignore non-essential directories in vite.config.js server.watch.ignored: [''vendor/**'', ''bootstrap/**'', ''config/**'', ''storage/**'', ''database/**'']", "percentage": 85}]'::jsonb, 'Vite 3.0.7+, Node.js v18+, Linux file system', 'npm run dev starts without ENOSPC errors, hot module reload works, file watchers stable under 50k', 'Only increasing watchers without ignoring vendor directories, not rebooting after increasing limits, watching build output directories', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/76902287/vue-upgrade-migration-from-vue2-to-vue3', 'admin:1764191855'),

('Vue 2 to Vue 3 app.js migration with Inertia, vue-i18n, and Ziggy routes', 'vue', 'HIGH', '[{"solution": "Replace Vue instance with createApp, use @inertiajs/vue3 instead of inertia-vue, import resolvePageComponent from @inertiajs/vue3, setup i18n with i18next.init promise chain, wrap route helper in global property instead of mixin.", "percentage": 92}, {"solution": "Keep Inertia v1 with compat mode temporarily, incrementally refactor to Inertia v2 + Vue 3 setup syntax", "percentage": 68}]'::jsonb, 'Laravel Inertia Vue 2 app with @inertiajs/inertia-vue, vue-i18n, portal-vue, ziggy-js', 'Routes resolve correctly via $route global property, i18n translations load per-component, no console errors on page transitions', 'Forgetting to await resolvePageComponent in async context, mixing Inertia v1 and v2 imports, vue-meta deprecated in v3', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/78169400/how-to-migrate-the-app-js-configuration-of-this-vue-2-app-for-vue-3', 'admin:1764191855'),

('CompatConfig mode 2 vs 3 conflict when using BootstrapVue with Vue 3 libraries', 'vue', 'MEDIUM', '[{"solution": "Use yarn patch to override library''s defineComponent call, wrap external library components with custom defineComponent that injects compatConfig: { mode: 3 } at definition level. Patch node_modules library first lines to redefine Vue imports.", "percentage": 79}, {"solution": "Migrate away from BootstrapVue (legacy) to bootstrap-vue-next or use CSS-only Bootstrap 5, eliminates need for compatConfig mode 2", "percentage": 84}]'::jsonb, 'BootstrapVue requiring compatConfig mode 2, Vue 3 libraries needing mode 3, Vite build setup', 'All components render with correct styling, no mode conflict warnings, internal library components inherit proper compat mode', 'Applying compatConfig only to wrapper not internal components, mixing modes in nested component trees, not using yarn patch correctly', 0.76, 'haiku', NOW(), 'https://stackoverflow.com/questions/75931200/how-to-configure-separate-compatconfig-options-per-external-vue-library-with-the', 'admin:1764191855');
