INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('exception.getStatus() : HttpStatus.INTERNAL_SERVER_ERROR const message = excepti', 'nestjs', 'HIGH', '[{"solution": "Use exception filters to catch errors and map to proper HTTP status codes. Check if exception is HttpException instance to get status via getStatus()", "percentage": 88}, {"solution": "Create custom exception filters that extend BaseExceptionFilter to handle specific error types properly", "percentage": 85}]'::jsonb, 'HttpException knowledge', 'Proper HTTP status returned', 'Forgetting to check exception type before calling getStatus()', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/51112952/what-is-the-nestjs-error-handling-approach-business-logic-error-vs-http-error', 'admin:1764210549'),

('NestJS CRLF line-break errors in VS Code', 'nestjs', 'MEDIUM', '[{"solution": "Change line ending from CRLF to LF at bottom-right corner of VS Code status bar", "percentage": 100}, {"solution": "Configure editor.crlf setting in VS Code settings.json to auto-convert on file open", "percentage": 92}]'::jsonb, 'VS Code editor', 'No line-break errors in linter output', 'Not checking file line ending setting', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/76985126/why-im-getting-errors-in-nestjs', 'admin:1764210549'),

('NestJS Response object does not pass through errors with .catch()', 'nestjs', 'MEDIUM', '[{"solution": "Use exception filters instead of manually setting response status - throw BadRequestException or HttpException from services", "percentage": 90}, {"solution": "Use @HttpCode() decorator to explicitly set status code when not throwing exceptions", "percentage": 82}]'::jsonb, 'NestJS exception filters', 'Error responses properly passed through', 'Trying to catch and transform errors at response level instead of exception level', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/56883056/how-to-send-error-codes-in-nestjs-app-from-controller', 'admin:1764210549'),

('NestJS error handling approach: service vs controller responsibility', 'nestjs', 'HIGH', '[{"solution": "Use interceptors to transform business logic errors into HttpExceptions. Services throw domain errors, controllers/interceptors handle HTTP mapping", "percentage": 91}, {"solution": "Throw specific NestJS exceptions like NotFoundException, ForbiddenException, BadRequestException instead of InternalServerErrorException", "percentage": 88}, {"solution": "Let NestJS default filter handle uncaught errors as 500 responses instead of explicitly throwing InternalServerError", "percentage": 85}]'::jsonb, 'NestJS architecture patterns', 'Clean separation of concerns between layers', 'Mixing HTTP concerns into business logic layer', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/72478119/nestjs-how-to-structure-code-to-elegantly-handle-errors', 'admin:1764210549'),

('NestJS globally handle database errors like duplicate key entries', 'nestjs', 'HIGH', '[{"solution": "Create a global exception filter using @Catch() decorator to handle database errors (ER_DUP_ENTRY, etc) and map to proper HTTP status", "percentage": 92}, {"solution": "Implement custom exception filter that checks error code property and returns appropriate HttpException", "percentage": 89}]'::jsonb, 'Exception filters, database errors', 'Duplicate entry errors mapped to 409 Conflict', 'Not implementing exception filter for database-specific errors', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/72995370/how-do-i-globally-handle-all-type-of-exception-in-nestjs', 'admin:1764210549'),

('NestJS microservices exception handling with RpcException', 'nestjs', 'HIGH', '[{"solution": "Throw RpcException from microservice controllers, implement RpcExceptionFilter in microservice to catch and handle properly", "percentage": 89}, {"solution": "Return error objects from services instead of throwing, let controller decide on error mapping", "percentage": 84}, {"solution": "Check exception type with instanceof before accessing error details - handle RpcException and Error types separately", "percentage": 87}]'::jsonb, 'Microservices pattern', 'Proper error propagation in microservice chain', 'Not implementing RpcExceptionFilter, throwing generic Error instead of RpcException', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/76594775/how-to-handle-exceptions-in-nestjs-microservices', 'admin:1764210549'),

('NestJS try-catch blocks in multiple service layers redundancy', 'nestjs', 'MEDIUM', '[{"solution": "Only use try-catch in top-level service or once in controller/interceptor for consistency", "percentage": 86}, {"solution": "Create custom exception class extending HttpException and use exception filter to handle consistently across app", "percentage": 84}, {"solution": "Use logger in catch blocks for debugging but let exception filter handle HTTP response", "percentage": 90}]'::jsonb, 'Service layer design', 'Single point of error handling, consistent logging', 'Wrapping exceptions multiple times through service layers', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/78527560/nestjs-try-catch-error-handling-best-practice', 'admin:1764210549'),

('NestJS services should not throw HttpException', 'nestjs', 'HIGH', '[{"solution": "Services should return Result<T> or Error objects, let controllers throw HttpException based on result type", "percentage": 88}, {"solution": "Use custom domain error classes in services, map to HttpException only in controller layer", "percentage": 86}]'::jsonb, 'Layered architecture', 'HttpException only in controllers', 'Putting HTTP-specific code in service layer', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/71467793/what-is-the-correct-type-of-exception-to-throw-in-a-nestjs-service', 'admin:1764210549'),

('NestJS cannot rethrow exception from ExceptionFilter, use BaseExceptionFilter', 'nestjs', 'HIGH', '[{"solution": "Extend BaseExceptionFilter instead of implementing ExceptionFilter directly - call super.catch() to delegate response building", "percentage": 93}, {"solution": "Use Interceptor with catchError() instead of ExceptionFilter if you need to transform and rethrow exceptions", "percentage": 89}, {"solution": "Build response manually in ExceptionFilter.catch() using host.switchToHttp().getResponse() instead of rethrow", "percentage": 91}]'::jsonb, 'Exception filter architecture', 'No UnhandledPromiseRejectionWarning thrown', 'Trying to throw from exception filter catch method', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/54945917/nestjs-throw-from-exceptionfilter', 'admin:1764210549'),

('NestJS business errors vs exception filters design pattern', 'nestjs', 'HIGH', '[{"solution": "Create custom Error class with status property, use exception filter to catch and transform to HttpException", "percentage": 87}, {"solution": "Throw business error in service, catch in controller/filter and check instanceof before throwing HttpException", "percentage": 85}, {"solution": "Use exception filters instead of try-catch in every controller method to centralize error handling", "percentage": 89}]'::jsonb, 'Error handling design patterns', 'Centralized error handling, DRY code', 'Stringifying errors, try-catch in every controller', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/70681202/is-it-good-way-to-throw-error-from-service-in-nestjs-like-it', 'admin:1764210549');
