-- Database Connection Errors - Mined 2025-11-26
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('database is locked - Diesel SQLite with r2d2 connection pool', 'database', 'HIGH', '[{"solution": "Enable WAL mode with PRAGMA journal_mode = WAL and PRAGMA synchronous = NORMAL for concurrent access", "percentage": 95}, {"solution": "Add PRAGMA busy_timeout with CustomizeConnection in r2d2 pool builder", "percentage": 90}, {"solution": "Set max_size(1) for single connection pools", "percentage": 85}]'::jsonb, 'Diesel ORM, r2d2 pool, SQLite connection pool configured', 'Multiple threads can query database concurrently without SQLITE_BUSY errors; crossbeam scope operations complete successfully', 'Forgetting to enable WAL mode; not setting busy_timeout; max_size(1) limiting concurrency unnecessarily', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/57123453/how-to-use-diesel-with-sqlite-connections-and-avoid-database-is-locked-type-of', 'admin:1764191737'),

('undefined: sqlite3.ErrNoExtended and undefined: sqlite3.Error - GORM SQLite driver', 'database', 'MEDIUM', '[{"solution": "Downgrade gorm.io/driver/sqlite to version 1.4.4 from 1.5.0", "percentage": 95}, {"solution": "Wait for gorm.io/driver/sqlite v1.5.1+ release fixing error translator issue", "percentage": 80}]'::jsonb, 'Go GORM library, SQLite driver installed, go-sqlite3 driver in PATH', 'GORM migrations execute without compilation errors; database opens successfully', 'Using incompatible GORM sqlite driver versions; not checking github.com/go-gorm/sqlite issues for known bugs', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/76091188/golang-with-gorm-sqlite-error-when-trying-to-migrate', 'admin:1764191737'),

('sqlalchemy.exc.OperationalError: could not connect to server: Connection refused - PostgreSQL Docker', 'database', 'HIGH', '[{"solution": "Change Docker container database HOST from 127.0.0.1 to service name (db) in docker-compose network", "percentage": 95}, {"solution": "Define explicit backend network in docker-compose and attach both web and db services to it", "percentage": 92}]'::jsonb, 'SQLAlchemy ORM, Docker, docker-compose, PostgreSQL container', 'Database connection succeeds from web container; ActiveRecord queries execute without connection errors', 'Using 127.0.0.1 instead of service hostname; containers on different networks; missing network definition in docker-compose', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/65829960/sql-alchemy-connection-refused-when-trying-to-connect-db-and-web-containers', 'admin:1764191737'),

('Unable to connect to the database - TypeORM NestJS SQLite', 'database', 'MEDIUM', '[{"solution": "Use entities pattern ''dist/**/*.entity{.ts,.js}'' instead of __dirname pattern for TypeORM entity resolution", "percentage": 96}, {"solution": "Change entities path to ''__dirname + ''/**/*.entity{.ts,.js}'' to resolve runtime entity loading", "percentage": 88}]'::jsonb, 'TypeORM, NestJS, SQLite database, TypeScript compilation', 'AutoMigrate executes without syntax errors; database tables created on synchronize', 'Using __dirname + ''/../...'' pattern in development causing TypeScript import syntax errors; not using compiled dist/ directory', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/56468911/typeorm-creates-database-but-unable-to-connect-it', 'admin:1764191737'),

('SQLITE_CANTOPEN: unable to open database file - Sequelize Node.js', 'database', 'MEDIUM', '[{"solution": "Replace hardcoded path ''path/to/database.sqlite'' with config-based path using sequelize new Sequelize(db[process.env.NODE_ENV])", "percentage": 94}, {"solution": "Ensure db/ directory exists before Sequelize initialization; create directory with mkdir -p db/", "percentage": 85}]'::jsonb, 'Sequelize ORM, Express.js, SQLite dialect configured, config file with storage paths', 'Sequelize.authenticate() resolves successfully; ''Database Connected'' message appears', 'Hardcoded placeholder paths in code (path/to/database.sqlite); config file not loaded by Sequelize constructor', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/55835942/starting-a-new-sequelize-backend-and-cannot-connect-to-sqlite-db', 'admin:1764191737'),

('Connection refused: connect - DynamoDB Local Java SDK', 'database', 'MEDIUM', '[{"solution": "Start DynamoDB Local with java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb before SDK operations", "percentage": 97}, {"solution": "Use IP alias alias 172.16.123.1 for SAM Local or Lambda connections instead of localhost", "percentage": 88}]'::jsonb, 'DynamoDB Local installed, AWS Java SDK, Java environment configured', 'DynamoDB shell accessible at http://localhost:8000/shell/; DynamoDBMapper save/load operations succeed', 'Starting DynamoDB after SDK initialization attempts; not verifying shell accessibility; incorrect endpoint URLs', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/33801460/dynamo-db-local-connection-refused', 'admin:1764191737'),

('sqlite file inside iOS/Android Simulator not accessible - Drizzle React Native Expo', 'database', 'MEDIUM', '[{"solution": "Use expo-drizzle-studio-plugin with useDrizzleStudio hook to visualize database inside simulator", "percentage": 96}, {"solution": "Access SQLite database through expo-sqlite driver; file location is simulator-internal, not project filesystem", "percentage": 90}]'::jsonb, 'React Native Expo, Drizzle ORM, expo-sqlite dependency installed, drizzle-kit configured', 'Drizzle studio portal displays database tables and schema; development mode database introspection works', 'Attempting to find .sqlite file in project directory; expecting file system location for simulator databases; using drizzle studio in production builds', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/78821137/drizzle-orm-in-react-native-expo-does-not-show-database-file', 'admin:1764191737'),

('EventEmitter memory leak warning - Node.js Database Listeners', 'database', 'LOW', '[{"solution": "Move event listener registration outside of loops; add listener once instead of multiple times", "percentage": 98}, {"solution": "Only increase setMaxListeners() after identifying and fixing root cause of excessive listeners", "percentage": 70}]'::jsonb, 'Node.js, EventEmitter pattern, database connection listeners', 'Event listeners added once at startup; no memory leak warnings during operation', 'Adding listeners in loops; increasing maxListeners without debugging root cause; listener registration on every request', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/50959776/sequelize-sqlite3-connects-to-database-but-throw-error-when-fetching-data', 'admin:1764191737'),

('connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused - ActiveRecord PostgreSQL', 'database', 'HIGH', '[{"solution": "Start PostgreSQL server or verify running status with systemctl start postgresql", "percentage": 94}, {"solution": "Check database.yml host/port configuration matches PostgreSQL server listening address", "percentage": 88}]'::jsonb, 'Rails ActiveRecord, PostgreSQL database, database.yml configured', 'ActiveRecord migrations run without connection errors; Rails server boots successfully', 'PostgreSQL server not started; incorrect host/port in database.yml; firewall blocking connections', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/73921263/activerecordconnectionnotestablished-error-after-i-switched-from-sqlite-to-p', 'admin:1764191737'),

('dial tcp 172.31.0.2:5430: connect: connection refused - GORM PostgreSQL Docker', 'database', 'HIGH', '[{"solution": "Map correct port in docker-compose ports: ''5430:5432'' to forward host 5430 to container 5432", "percentage": 96}, {"solution": "Use host.docker.internal as hostname instead of localhost/127.0.0.1 for inter-container communication", "percentage": 91}]'::jsonb, 'GORM, PostgreSQL Docker container, docker-compose networking', 'GORM database.Ping() succeeds; application connects and queries execute successfully', 'Using port 5430 in PostgreSQL container instead of standard 5432; using localhost from inside container; missing network bridge configuration', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/76219050/gorm-dial-tcp-127-0-0-15432-connect-connection-refused', 'admin:1764191737');
