INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Vite is ignoring compiler errors until the file is used at runtime', 'vite', 'HIGH', '[{"solution": "Run type checking in parallel: tsc --noEmit --watch", "percentage": 85}, {"solution": "Use vite-plugin-checker to integrate type checking into build", "percentage": 90}]'::jsonb, 'TypeScript, Vite 4.x', 'Type errors shown in terminal during dev', 'Assuming Vite does type checking by default', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/76480836', 'admin:1764222715'),

('Display errors and warnings in terminal for React app with Vite', 'vite', 'HIGH', '[{"solution": "Use vite-plugin-terminal for terminal error display", "percentage": 80}, {"solution": "Install Console Ninja VSCode extension", "percentage": 75}]'::jsonb, 'React, Vite, VSCode', 'Errors visible in terminal output', 'Not configuring error output properly', 0.78, 'haiku', NOW(), 'https://stackoverflow.com/questions/77781537', 'admin:1764222715'),

('TypeScript errors when running npm run build in Vite', 'vite', 'MEDIUM', '[{"solution": "Change build command from tsc && vite build to just vite build", "percentage": 95}, {"solution": "Set skipLibCheck: true in tsconfig.json", "percentage": 70}]'::jsonb, 'Vite 4.x, TypeScript, React', 'Build completes without type errors', 'Running tsc before vite build', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/76684190', 'admin:1764222715'),

('Production build TypeError with Vite React Day.js import', 'vite', 'MEDIUM', '[{"solution": "Change import from import * as dayjs to import dayjs default", "percentage": 98}, {"solution": "Update Day.js plugin imports similarly", "percentage": 95}]'::jsonb, 'React, Vite 4.x, Day.js', 'Production build runs without TypeError', 'Using namespace import instead of default import', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/76754734', 'admin:1764222715'),

('Cannot find module vite-react-react-router-dom error', 'vite', 'HIGH', '[{"solution": "Run npm install or yarn install to install dependencies", "percentage": 92}, {"solution": "Delete node_modules and reinstall", "percentage": 88}, {"solution": "Use correct yarn syntax: yarn config set nodeLinker node-modules", "percentage": 85}]'::jsonb, 'Vite 2.x, node_modules', 'Modules resolve correctly in IDE', 'Incomplete package installation', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/71108772', 'admin:1764222715'),

('Cannot find module @vitejs/plugin-react type declarations', 'vite', 'HIGH', '[{"solution": "Restart VSCode editor", "percentage": 60}, {"solution": "Use @vitejs/plugin-react-swc for SWC projects", "percentage": 85}, {"solution": "Delete node_modules/.vite and reinstall", "percentage": 80}]'::jsonb, 'Vite, React, TypeScript', 'No module not found errors in IDE', 'Using wrong plugin for build tool', 0.75, 'haiku', NOW(), 'https://stackoverflow.com/questions/71286740', 'admin:1764222715'),

('Vite with Jest cannot find module with alias import', 'vite', 'MEDIUM', '[{"solution": "Add moduleNameMapper to jest.config.js with @/* pattern", "percentage": 95}, {"solution": "Add paths to tsconfig.json compilerOptions", "percentage": 90}]'::jsonb, 'Jest, Vite, TypeScript aliases', 'Jest tests resolve aliased imports', 'Not configuring Jest to understand Vite aliases', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/68486297', 'admin:1764222715'),

('Cannot find module with special characters in folder path', 'vite', 'LOW', '[{"solution": "Remove special characters like & from parent directory names", "percentage": 100}, {"solution": "Use URL encoding for folder names if necessary", "percentage": 50}]'::jsonb, 'Vite, Node.js', 'Module resolution succeeds', 'Folder names contain special characters &, %, $, ?', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/72774636', 'admin:1764222715'),

('Vite failed to load configuration due to missing local vite package', 'vite', 'MEDIUM', '[{"solution": "Run npm install --force to reinstall all dependencies", "percentage": 85}, {"solution": "Create fresh Vite project with npx create vite@latest", "percentage": 80}]'::jsonb, 'Vite, Node.js, npm', 'Vite config loads without errors', 'Corrupted vite.config.js or missing vite package', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/79642118', 'admin:1764222715'),

('Path alias resolution in TypeScript and Vite deployment', 'vite', 'HIGH', '[{"solution": "Move alias config from tsconfig.json to tsconfig.app.json", "percentage": 92}, {"solution": "Ensure @ path matches in both vite.config.ts and tsconfig", "percentage": 88}]'::jsonb, 'Vite, TypeScript, Vercel', 'Aliases resolve in dev and build', 'Config split between multiple tsconfig files', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/77521077', 'admin:1764222715'),

('Vue3 Vite cannot find module App.vue or type declarations', 'vite', 'MEDIUM', '[{"solution": "Enable Volar takeover mode in VSCode", "percentage": 95}, {"solution": "Disable TypeScript Language Features extension in workspace", "percentage": 90}]'::jsonb, 'Vue3, Vite 4.x, VSCode', 'App.vue found in editor', 'TypeScript extension conflict with Volar', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/73322883', 'admin:1764222715'),

('Vue3 Vite HMR hot reload not working in browser', 'vite', 'HIGH', '[{"solution": "Add server.watch.usePolling: true to vite.config.ts", "percentage": 85}, {"solution": "Disable vite-plugin-checker if using it", "percentage": 80}]'::jsonb, 'Vue3, Vite 3.x+, Docker/WSL', 'Hot reload changes visible in browser', 'File system watching not working in containers', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/74625283', 'admin:1764222715'),

('Vite WebSocket HMR connection failed with wss error', 'vite', 'MEDIUM', '[{"solution": "Set hmr: false in vite config to disable HMR", "percentage": 95}, {"solution": "Configure hmr with host, port, and protocol settings", "percentage": 85}]'::jsonb, 'Vite, Docker, Kubernetes', 'HMR connection established or disabled', 'Docker blocking HMR port', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/71956576', 'admin:1764222715'),

('Vite HMR remote server blank screen Laravel issue', 'vite', 'MEDIUM', '[{"solution": "Configure vite.config with hmr.host matching domain", "percentage": 88}, {"solution": "Ensure CSS/JS links point to accessible host not localhost", "percentage": 92}]'::jsonb, 'Laravel, Vite, Remote Server', 'Remote site renders without blank screen', 'HMR pointing to localhost instead of remote domain', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/76539636', 'admin:1764222715'),

('Vite HMR not working with Nuxt3 Docker setup', 'vite', 'MEDIUM', '[{"solution": "Expose ports 3000:3000 and 24678:24678 in docker-compose", "percentage": 95}, {"solution": "Set hmr protocol to ws with host 0.0.0.0 in nuxt.config", "percentage": 90}]'::jsonb, 'Nuxt3, Vite, Docker', 'HMR connection stable without reloads', 'Docker ports not exposed for HMR', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/72016669', 'admin:1764222715'),

('Nuxt3 Vite HMR infinite reload with Docker Traefik', 'vite', 'MEDIUM', '[{"solution": "Expose ports 3000 and 24678 in docker-compose", "percentage": 95}, {"solution": "Set nuxt.config vite.server.hmr with default empty config", "percentage": 88}]'::jsonb, 'Nuxt3, Vite, Docker, Traefik', 'Page stops infinite reloading', 'HMR port blocked by Docker', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/70290931', 'admin:1764222715'),

('React Vite HMR causing blank page and root.render errors', 'vite', 'MEDIUM', '[{"solution": "Split context and app into separate files for fast refresh", "percentage": 95}, {"solution": "Set hmr.clientPort explicitly in vite config", "percentage": 80}]'::jsonb, 'React, Vite, React Router', 'Page reloads without blank screen or render errors', 'Root component not Fast Refreshable', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/76297888', 'admin:1764222715'),

('Vite HMR not working with Spring Boot backend', 'vite', 'MEDIUM', '[{"solution": "Follow Vite backend integration guide for HMR setup", "percentage": 85}, {"solution": "Use Spring Boot proxy to route HMR requests", "percentage": 80}]'::jsonb, 'Spring Boot, Vite', 'HMR working with Spring Boot MPA', 'HMR configuration not compatible with MPA setup', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/75753422', 'admin:1764222715'),

('Vite HMR proxy through Nginx Docker configuration', 'vite', 'MEDIUM', '[{"solution": "Set hmr.clientPort to browser accessible port", "percentage": 90}, {"solution": "Configure Nginx to proxy WebSocket with Upgrade headers", "percentage": 88}]'::jsonb, 'Vite, Nginx, Docker', 'WebSocket connection established through proxy', 'Nginx not configured for WebSocket upgrade', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/71050909', 'admin:1764222715'),

('Vite optimize dependency error with big decimal js', 'vite', 'MEDIUM', '[{"solution": "Add js-big-decimal to optimizeDeps.exclude in config", "percentage": 92}, {"solution": "Delete node_modules and pnpm-lock.yaml then reinstall", "percentage": 85}]'::jsonb, 'React, Vite, js-big-decimal', 'Application loads without optimize errors', 'Dependency pre-bundling conflicts', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/75883720', 'admin:1764222715'),

('Vite optimizeDeps include option not working correctly', 'vite', 'MEDIUM', '[{"solution": "Use optimizeDeps.exclude instead of include for CommonJS modules", "percentage": 90}, {"solution": "Configure both build and dev toolchains separately", "percentage": 80}]'::jsonb, 'Vite 4.x, CommonJS modules', 'Dependencies optimized correctly', 'Dev and build use different toolchains', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/79250054', 'admin:1764222715'),

('Vite build hangs forever after bundling completes', 'vite', 'LOW', '[{"solution": "Create plugin with closeBundle hook to call process.exit(0)", "percentage": 98}, {"solution": "Check if build.watch is configured and disable if not needed", "percentage": 95}]'::jsonb, 'Vite, Node.js', 'Build process exits cleanly', 'Build process watching for changes indefinitely', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/75839993', 'admin:1764222715'),

('Vite build target es2022 not respecting top-level await', 'vite', 'MEDIUM', '[{"solution": "Set build.target to esnext and esbuild.target to es2022", "percentage": 95}, {"solution": "Add optimizeDeps.esbuildOptions with target es2022", "percentage": 90}]'::jsonb, 'Vite, TypeScript, WebGPU', 'Top-level await supported in build', 'Build target mismatch between Vite and esbuild', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/76616620', 'admin:1764222715'),

('Failed to resolve import in Vitest with alias paths', 'vite', 'MEDIUM', '[{"solution": "Add resolve.alias to vitest.config.ts with correct paths", "percentage": 95}, {"solution": "Move path config to tsconfig.app.json instead of tsconfig.json", "percentage": 88}]'::jsonb, 'Vitest, Vite, Vue3', 'Vitest resolves aliased imports correctly', 'Vitest not configured with same aliases as Vite', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/75798479', 'admin:1764222715'),

('Vite Vue import missing file extension .vue error', 'vite', 'HIGH', '[{"solution": "Add .vue extension to dynamic imports: import(''../../views/main/index.vue'')", "percentage": 100}, {"solution": "Configure moduleResolution: bundler in TypeScript", "percentage": 85}]'::jsonb, 'Vue3, Vite, dynamic imports', 'Component imports resolve correctly', 'Missing file extensions on Vue imports', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/72642058', 'admin:1764222715'),

('Vite aliased imports not resolving in monorepo', 'vite', 'MEDIUM', '[{"solution": "Prefix paths with / in tsconfig.json to use absolute paths", "percentage": 92}, {"solution": "Configure alias in vite.config.ts with correct path.resolve", "percentage": 88}]'::jsonb, 'Vite, React, monorepo', 'Aliased imports resolve in all files', 'Relative path alias configuration causing issues', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/72503638', 'admin:1764222715'),

('Rollup failed to resolve CSS import in Vite build', 'vite', 'MEDIUM', '[{"solution": "Use absolute paths with / prefix for CSS imports in HTML", "percentage": 95}, {"solution": "Add CSS to build.rollupOptions.external if needed", "percentage": 70}]'::jsonb, 'Vite, Tailwind CSS, build', 'Build completes without resolve errors', 'Using relative paths for CSS files', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/67696920', 'admin:1764222715'),

('Failed to resolve import axios in Vue Vite project', 'vite', 'HIGH', '[{"solution": "Run npm install axios --save to install dependency", "percentage": 98}, {"solution": "Check package.json has axios listed in dependencies", "percentage": 95}]'::jsonb, 'Vue3, Vite, axios', 'Axios imported and used without errors', 'Missing axios installation', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/76903739', 'admin:1764222715');
