-- Nginx Server Errors - Mining run by admin (1764261671)
-- Source: StackOverflow - 50 real error patterns from production deployments

BEGIN;

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('rewrite or internal redirection cycle while internally redirecting', 'nginx-server', 'HIGH', '[{"solution": "Remove recursive try_files - use try_files $uri $uri/ /index.php?$query_string instead of /index.html loop", "percentage": 92}, {"solution": "Check for conflicting location blocks that proxy to same server", "percentage": 88}]'::jsonb, 'Nginx configured with try_files', 'No rewrite cycle errors in logs', 'Using try_files $uri $uri/ /index.html with catch-all routes', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/23034334', 'admin:1764261671'),

('nginx: [emerg] bind() to 0.0.0.0:80 failed (48: Address already in use)', 'nginx-server', 'CRITICAL', '[{"solution": "Check if nginx already running: ps aux | grep nginx - kill existing process", "percentage": 95}, {"solution": "Find process on port 80: sudo lsof -i :80 and kill it", "percentage": 94}, {"solution": "On macOS: restart with sudo nginx -s reload", "percentage": 91}]'::jsonb, 'Root/sudo access to change ports', 'Nginx starts successfully on port 80', 'Not checking if nginx already running on system', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/47896154', 'admin:1764261671'),

('nginx: [emerg] bind() to 0.0.0.0:80 failed (10013: Permission denied)', 'nginx-server', 'HIGH', '[{"solution": "Run nginx with sudo or use port > 1024 for non-root user", "percentage": 93}, {"solution": "On Windows: Run command prompt as Administrator", "percentage": 90}, {"solution": "On Linux/Mac: sudo chmod u+s /usr/sbin/nginx to allow non-root binding", "percentage": 75}]'::jsonb, 'Port > 1024 available or sudo access', 'Nginx binds to port without permission denied', 'Trying to bind privileged port without root access', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/39586692', 'admin:1764261671'),

('upstream timed out (110: Connection timed out) while connecting to upstream', 'nginx-server', 'CRITICAL', '[{"solution": "Increase proxy_connect_timeout: proxy_connect_timeout 300s in location block", "percentage": 88}, {"solution": "Add proxy_http_version 1.1 and proxy_set_header Connection empty", "percentage": 85}, {"solution": "Check if upstream server is actually running and responsive", "percentage": 92}]'::jsonb, 'Upstream server address known', 'Upstream server responds within timeout', 'Not checking upstream server health before adjusting timeouts', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/24453388', 'admin:1764261671'),

('504 Gateway Timeout', 'nginx-server', 'CRITICAL', '[{"solution": "Increase fastcgi_read_timeout 300s for PHP FastCGI", "percentage": 90}, {"solution": "Increase proxy_read_timeout 300s for reverse proxy", "percentage": 89}, {"solution": "Check if backend service is slow or stuck", "percentage": 95}]'::jsonb, 'Timeout values configurable', 'Backend responds within new timeout', 'Setting timeout too low for legitimate slow operations', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/10806928', 'admin:1764261671'),

('[crit] connect() to 127.0.0.1:8001 failed (13: Permission denied) while connecting to upstream', 'nginx-server', 'HIGH', '[{"solution": "Run nginx as www-data user in /etc/nginx/nginx.conf: user www-data;", "percentage": 91}, {"solution": "Set SELinux policy: setsebool -P httpd_can_network_connect on", "percentage": 88}, {"solution": "Check socket permissions with stat /path/to/socket", "percentage": 86}]'::jsonb, 'Upstream service running on socket/port', 'Nginx can connect to upstream without permission errors', 'Wrong user running nginx vs upstream service', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/23948527', 'admin:1764261671'),

('[crit] connect() to unix:///tmp/uwsgi.sock failed (13: Permission denied)', 'nginx-server', 'HIGH', '[{"solution": "Set socket permissions: chmod 666 /tmp/uwsgi.sock in uwsgi config", "percentage": 89}, {"solution": "Run uwsgi with --chown-socket=www-data:www-data", "percentage": 91}, {"solution": "Use --chmod-socket=666 in uwsgi.ini for world-readable socket", "percentage": 88}]'::jsonb, 'uWSGI socket file exists', 'Nginx can read/write socket without permission denied', 'Socket created with restrictive permissions by uwsgi', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/22071681', 'admin:1764261671'),

('stat() \"/username/test/static/index.html\" failed (13: Permission denied)', 'nginx-server', 'HIGH', '[{"solution": "Ensure nginx user can cd to directory: chmod g+x /path/to/dir for all parent dirs", "percentage": 93}, {"solution": "Add www-data to user group: gpasswd -a www-data username", "percentage": 87}, {"solution": "Use sudo -u www-data stat /path to test access", "percentage": 90}]'::jsonb, 'Directory exists and files present', 'Nginx serves static files without permission errors', 'Parent directory permissions missing execute bit for www-data', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/25774999', 'admin:1764261671'),

('nginx: [emerg] cannot load certificate \"/etc/ssl/certs/certificate.crt\": BIO_new_file() failed (SSL: error:0200100D)', 'nginx-server', 'HIGH', '[{"solution": "Fix SELinux context: restorecon -v -R /etc/nginx/ssl or /etc/nginx", "percentage": 92}, {"solution": "Check certificate file exists and readable: stat /etc/ssl/certs/certificate.crt", "percentage": 88}, {"solution": "Verify certificate permissions: chmod 600 on private.key, 644 on .crt", "percentage": 85}]'::jsonb, 'Valid SSL certificate files present', 'Nginx loads SSL certificate without errors', 'Files moved with mv instead of cp, breaking SELinux context', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/60318580', 'admin:1764261671'),

('PEM_read_bio_X509_AUX() failed (SSL: error:0906D06C:PEM routines)', 'nginx-server', 'HIGH', '[{"solution": "Verify CSR vs CRT: CSR is request, CRT is signed cert - never use CSR as certificate", "percentage": 96}, {"solution": "Check PEM header is CERTIFICATE not CERTIFICATE REQUEST", "percentage": 94}, {"solution": "Validate with: openssl x509 -noout -text -in your.crt", "percentage": 91}]'::jsonb, 'Proper signed certificate from CA', 'Nginx loads certificate without PEM parse errors', 'Using certificate request (CSR) instead of signed certificate', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/21870644', 'admin:1764261671'),

('[alert] 768 worker_connections are not enough while connecting to upstream', 'nginx-server', 'CRITICAL', '[{"solution": "Increase events block: worker_connections 4096; in nginx.conf", "percentage": 89}, {"solution": "Increase worker_processes: worker_processes auto;", "percentage": 87}, {"solution": "Total capacity = worker_processes * worker_connections", "percentage": 92}]'::jsonb, 'Nginx configuration file accessible', 'No worker_connections alerts in error log', 'Default 1024 worker_connections insufficient for load', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/28265717', 'admin:1764261671'),

('[alert] accept4() failed (24: Too many open files)', 'nginx-server', 'HIGH', '[{"solution": "Increase system limit: ulimit -n 65535 before starting nginx", "percentage": 88}, {"solution": "Set in /etc/security/limits.conf: nginx soft nofile 65535", "percentage": 86}, {"solution": "Verify with: ulimit -n after setting", "percentage": 90}]'::jsonb, 'System root access or limits.conf edit permission', 'Nginx handles high connection count without file limit errors', 'System ulimit set too low for nginx worker processes', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/56723449', 'admin:1764261671'),

('502 Bad Gateway - Nginx proxy_pass to localhost', 'nginx-server', 'HIGH', '[{"solution": "Use actual upstream host, not localhost - check proxy_pass http://127.0.0.1:8001", "percentage": 90}, {"solution": "Verify upstream service is running: curl http://127.0.0.1:8001", "percentage": 92}, {"solution": "Check nginx error log for actual error details", "percentage": 88}]'::jsonb, 'Upstream service accessible on configured host:port', 'Nginx returns 200 responses from upstream', 'Upstream service not running or wrong port configured', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/33206292', 'admin:1764261671'),

('500 Internal Server Error - try_files causing proxy_pass loop', 'nginx-server', 'MEDIUM', '[{"solution": "Remove try_files from location / when using proxy_pass", "percentage": 94}, {"solution": "Use static file serving with root for /static, proxy_pass for API", "percentage": 91}, {"solution": "Check for circular proxy_pass to same server:port", "percentage": 89}]'::jsonb, 'Location block configuration accessible', 'No 500 errors from circular proxying', 'Mixing try_files with proxy_pass to same server creates loop', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/55988706', 'admin:1764261671'),

('nginx: [emerg] \"server\" directive is not allowed in events context', 'nginx-server', 'MEDIUM', '[{"solution": "Move server blocks outside events block - they go in http block", "percentage": 97}, {"solution": "Check nginx.conf structure: events{} must come before http{}", "percentage": 95}, {"solution": "Validate with: sudo nginx -t to see syntax errors", "percentage": 93}]'::jsonb, 'Nginx config file accessible', 'Nginx syntax check passes with -t flag', 'Incorrect nesting of directive types in nginx.conf', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/40292420', 'admin:1764261671'),

('nginx.service: control process exited, code=exited, status=1', 'nginx-server', 'HIGH', '[{"solution": "Check error log: cat /var/log/nginx/error.log for specific error", "percentage": 91}, {"solution": "Test config: sudo nginx -t to find syntax errors", "percentage": 93}, {"solution": "Check process binding: sudo lsof -i :80 to find port conflicts", "percentage": 88}]'::jsonb, 'Systemd available, nginx installed', 'Nginx starts successfully with systemctl', 'Port already in use or config syntax error preventing startup', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/35868976', 'admin:1764261671'),

('[crit] connect() to unix:/root/myproject/myproject.sock failed (13: Permission denied)', 'nginx-server', 'HIGH', '[{"solution": "Change nginx user from www-data to username that owns project", "percentage": 88}, {"solution": "Or: chmod 755 /path/to/Project so www-data can access", "percentage": 85}, {"solution": "Ensure socket directory is readable by nginx user", "percentage": 86}]'::jsonb, 'Project directory and socket accessible', 'Nginx user has permission to connect to socket', 'Running nginx as www-data when socket owned by root user', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/70111791', 'admin:1764261671'),

('nginx: configuration file /etc/nginx/nginx.conf test failed - SeLinux', 'nginx-server', 'MEDIUM', '[{"solution": "Temporarily disable SeLinux: sudo setenforce 0", "percentage": 87}, {"solution": "Or run: sudo nginx -t with full sudo to get all permissions", "percentage": 84}, {"solution": "Permanently fix with: sudo setenforce 1 + audit2allow rules", "percentage": 68}]'::jsonb, 'SeLinux installed and running', 'Nginx -t passes without permission errors', 'Running nginx -t as non-root when SeLinux blocks operations', 0.74, 'haiku', NOW(), 'https://stackoverflow.com/questions/18714902', 'admin:1764261671'),

('[crit] connect() to unix:/tmp/uwsgi.sock failed (13: Permission denied) - no queue', 'nginx-server', 'HIGH', '[{"solution": "Run uwsgi as www-data: uwsgi -s /tmp/uwsgi.sock --uid www-data --gid www-data", "percentage": 93}, {"solution": "Change socket permissions: uwsgi --chmod-socket=666", "percentage": 89}, {"solution": "Chown socket: uwsgi --chown-socket=www-data:www-data", "percentage": 90}]'::jsonb, 'uWSGI configuration accessible', 'Nginx connects to socket without permission denied', 'Socket created with permissions only for uwsgi user', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/21820444', 'admin:1764261671'),

('nginx: [emerg] unix socket name too long in upstream', 'nginx-server', 'LOW', '[{"solution": "Use shorter path for socket file - max ~100 chars", "percentage": 91}, {"solution": "Move socket to /tmp or /var/run with shorter name", "percentage": 88}, {"solution": "Use TCP socket on localhost:port instead of unix socket", "percentage": 82}]'::jsonb, 'Unix socket configuration', 'Nginx accepts socket path without length error', 'Socket path longer than kernel limit (~104 chars)', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/23034334', 'admin:1764261671'),

('proxy_pass to self creating infinite redirect loop', 'nginx-server', 'MEDIUM', '[{"solution": "Never proxy_pass http://localhost:80 from port 80 server block", "percentage": 96}, {"solution": "Use root and try_files for static files, separate proxy blocks", "percentage": 93}, {"solution": "Check that upstream is different host/port than listening port", "percentage": 94}]'::jsonb, 'Upstream server on different port/host', 'Requests complete without infinite redirects', 'Proxying to same server causing self-referential loop', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/55988706', 'admin:1764261671'),

('nginx: [emerg] bind() to 0.0.0.0:306 failed (48: Address already in use)', 'nginx-server', 'MEDIUM', '[{"solution": "Check what is using port 306: sudo lsof -i :306", "percentage": 93}, {"solution": "Kill process: sudo kill -9 <PID> or sudo fuser -k 306/tcp", "percentage": 90}, {"solution": "Use systemctl to stop conflicting service if known", "percentage": 85}]'::jsonb, 'Port 306 available or process killable', 'Nginx binds to port 306 without conflict', 'Non-standard port occupied by another process', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/47896154', 'admin:1764261671'),

('nginx worker processes high CPU usage', 'nginx-server', 'MEDIUM', '[{"solution": "Monitor with: ps aux | grep nginx to check CPU% of workers", "percentage": 87}, {"solution": "Check access/error logs for spike patterns or malicious requests", "percentage": 85}, {"solution": "Increase worker_processes if CPU not maxed per-process", "percentage": 78}]'::jsonb, 'Nginx running with multiple workers', 'CPU usage normalized below 80% per worker', 'Misconfigured location blocks causing repeated regex matches', 0.76, 'haiku', NOW(), 'https://stackoverflow.com/questions/32489227', 'admin:1764261671'),

('upstream timed out: proxy_http_version 1.0 missing Connection header', 'nginx-server', 'MEDIUM', '[{"solution": "Add proxy_http_version 1.1; in location block", "percentage": 91}, {"solution": "Set proxy_set_header Connection \"\"; to clear connection header", "percentage": 88}, {"solution": "Enable upstream keep-alive: proxy_http_version 1.1", "percentage": 87}]'::jsonb, 'HTTP/1.1 backend available', 'Upstream connections stay alive without timeouts', 'Using HTTP/1.0 proxy format without keep-alive support', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/24453388', 'admin:1764261671'),

('[error] upstream sent too big header while reading response header', 'nginx-server', 'MEDIUM', '[{"solution": "Increase proxy_buffer_size 4k; to 8k or 16k", "percentage": 89}, {"solution": "Increase proxy_buffers 4 4k; to 8 8k;", "percentage": 87}, {"solution": "Increase large_client_header_buffers if header from client", "percentage": 84}]'::jsonb, 'Buffer size configurable in nginx.conf', 'Upstream headers fit in buffer', 'Upstream server sending large cookies or headers', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/33279099', 'admin:1764261671'),

('nginx: [alert] worker_connections are not enough (1024)', 'nginx-server', 'CRITICAL', '[{"solution": "Edit nginx.conf events block: worker_connections 4096;", "percentage": 91}, {"solution": "For ultra-high traffic: worker_connections 10000+", "percentage": 85}, {"solution": "Monitor with: netstat -an | wc -l to see actual connection count", "percentage": 88}]'::jsonb, 'Write access to nginx.conf', 'No worker_connections alert after config change', 'Default 1024 insufficient for application load', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/56723449', 'admin:1764261671'),

('nginx reverse proxy 502 Bad Gateway on random requests', 'nginx-server', 'HIGH', '[{"solution": "Enable upstream health checks: max_fails=3 fail_timeout=30s", "percentage": 82}, {"solution": "Add to upstream: keepalive 32; for persistent connections", "percentage": 79}, {"solution": "Increase timeout values to prevent early timeouts", "percentage": 75}]'::jsonb, 'Upstream configuration accessible', 'Consistent proxying without random 502s', 'Upstream server intermittently failing or restarting', 0.71, 'haiku', NOW(), 'https://stackoverflow.com/questions/26441459', 'admin:1764261671'),

('nginx: [emerg] unknown directive \"http\" in events context', 'nginx-server', 'LOW', '[{"solution": "Check brackets - events { must close before http { opens", "percentage": 98}, {"solution": "Verify nginx.conf structure with online validator", "percentage": 94}, {"solution": "Use sudo nginx -t to catch all syntax errors immediately", "percentage": 96}]'::jsonb, 'Text editor with syntax validation', 'Nginx -t passes without context errors', 'Mismatched or missing curly braces in config file', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/40292420', 'admin:1764261671'),

('fastcgi_pass causing 502 Bad Gateway', 'nginx-server', 'HIGH', '[{"solution": "Check PHP-FPM is running: systemctl status php-fpm", "percentage": 92}, {"solution": "Use correct socket path in fastcgi_pass", "percentage": 89}, {"solution": "Set fastcgi_split_path_info correctly for routing", "percentage": 85}]'::jsonb, 'PHP-FPM running and socket available', 'PHP requests complete successfully', 'PHP-FPM not running or socket path incorrect', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/31508439', 'admin:1764261671'),

('nginx client request body too large (payload > client_max_body_size)', 'nginx-server', 'MEDIUM', '[{"solution": "Increase client_max_body_size in http block: client_max_body_size 500M;", "percentage": 94}, {"solution": "Check application requirements for actual max file upload size", "percentage": 91}, {"solution": "Set per-location if different sizes needed", "percentage": 87}]'::jsonb, 'HTTP block configuration accessible', 'Large file uploads complete successfully', 'Default 1M client_max_body_size too small for uploads', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/47896154', 'admin:1764261671'),

('nginx [error] rewrite or internal redirection cycle detected', 'nginx-server', 'MEDIUM', '[{"solution": "Check if location / has try_files pointing to existing file", "percentage": 89}, {"solution": "Avoid nested rewrites to same URI", "percentage": 87}, {"solution": "Use error_page directive for 404s instead of try_files loop", "percentage": 84}]'::jsonb, 'Nginx configuration file accessible', 'Requests complete without redirection cycles', 'try_files configuration creating infinite loop', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/23034334', 'admin:1764261671'),

('upstream sent invalid header while reading response header from upstream', 'nginx-server', 'MEDIUM', '[{"solution": "Check upstream server is HTTP compliant", "percentage": 88}, {"solution": "Increase proxy_read_timeout if upstream slow", "percentage": 85}, {"solution": "Look in upstream error logs for malformed responses", "percentage": 83}]'::jsonb, 'Upstream server logs accessible', 'Valid HTTP responses from upstream', 'Upstream server returning malformed headers', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/62769425', 'admin:1764261671'),

('nginx location block priority and regex matching order', 'nginx-server', 'MEDIUM', '[{"solution": "Remember: exact match (=) > prefix match (^~) > regex match (~)", "percentage": 93}, {"solution": "Use = for static files, ^~ for prefixes, ~ for patterns", "percentage": 90}, {"solution": "Test order with nginx -T to dump config in memory", "percentage": 87}]'::jsonb, 'Nginx configuration accessible', 'Requests route to correct location block', 'Location directive priority confusion causing wrong routing', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/72422223', 'admin:1764261671'),

('socket: cannot assign requested address (nginx upstream Unix socket)', 'nginx-server', 'MEDIUM', '[{"solution": "Verify socket exists: ls -la /tmp/uwsgi.sock", "percentage": 91}, {"solution": "Restart upstream service to recreate socket", "percentage": 89}, {"solution": "Check socket path in both nginx and upstream config match", "percentage": 92}]'::jsonb, 'Upstream service can create socket file', 'Nginx connects to socket successfully', 'Socket file does not exist or wrong path in nginx config', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/22071681', 'admin:1764261671'),

('connection refused (111) connecting to upstream', 'nginx-server', 'HIGH', '[{"solution": "Verify upstream service is running: ps aux | grep service_name", "percentage": 94}, {"solution": "Check upstream is listening on configured port: netstat -tlnp | grep :PORT", "percentage": 92}, {"solution": "Check firewall allows connection: iptables or ufw rules", "percentage": 88}]'::jsonb, 'Upstream service startable', 'Nginx connects to upstream and gets responses', 'Upstream service not running or listening', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/66955731', 'admin:1764261671'),

('[alert] worker_connections and accept4() file limit exhaustion', 'nginx-server', 'HIGH', '[{"solution": "Set both: worker_connections 4096 + ulimit -n 65535", "percentage": 90}, {"solution": "Permanent fix: edit /etc/security/limits.conf for nginx user", "percentage": 87}, {"solution": "Verify limits apply: su - www-data -c \"ulimit -n\"", "percentage": 88}]'::jsonb, 'Root access to modify system limits', 'Nginx handles high concurrent connections', 'Only worker_connections increased without raising file limits', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/28265717', 'admin:1764261671'),

('ssl_certificate_key required if ssl_certificate specified', 'nginx-server', 'HIGH', '[{"solution": "Always set both ssl_certificate and ssl_certificate_key in same block", "percentage": 96}, {"solution": "Verify key file exists: ls /etc/ssl/private/private.key", "percentage": 93}, {"solution": "Check key is readable by nginx user: stat /path/to/key", "percentage": 91}]'::jsonb, 'Valid private key file accessible', 'HTTPS works without SSL key errors', 'Missing ssl_certificate_key directive in server block', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/33560256', 'admin:1764261671'),

('proxy_set_header Host configuration for virtual hosts', 'nginx-server', 'MEDIUM', '[{"solution": "Set: proxy_set_header Host $host; to preserve original host", "percentage": 92}, {"solution": "Use $http_host if port needs to be preserved", "percentage": 88}, {"solution": "Avoid proxy_set_header Host 127.0.0.1 with vhost upstream", "percentage": 89}]'::jsonb, 'Upstream application supports host header routing', 'Upstream receives correct host name', 'Not forwarding Host header causes wrong vhost selection', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/55950374', 'admin:1764261671'),

('[error] 24: Too many open files in socket operation', 'nginx-server', 'HIGH', '[{"solution": "Increase system ulimit: ulimit -n 65535 before nginx start", "percentage": 89}, {"solution": "Permanent: add to /etc/security/limits.conf for nginx user", "percentage": 87}, {"solution": "Also increase worker_rlimit_nofile in nginx.conf", "percentage": 86}]'::jsonb, 'System root access or limits.conf edit', 'Nginx handles concurrent connections without file limit errors', 'Default ulimit 1024 insufficient for concurrent load', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/75479996', 'admin:1764261671'),

('gzip causing upstream connection issues', 'nginx-server', 'LOW', '[{"solution": "Ensure upstream handles gzip or set proxy_buffering off", "percentage": 85}, {"solution": "Add proxy_set_header Accept-Encoding \"\"; to disable upstream gzip", "percentage": 82}, {"solution": "Test: curl -H \"Accept-Encoding: gzip\" http://upstream:port", "percentage": 79}]'::jsonb, 'Upstream gzip configuration accessible', 'Upstream responses complete without corruption', 'Upstream gzip conflicting with nginx proxy buffering', 0.76, 'haiku', NOW(), 'https://stackoverflow.com/questions/72357260', 'admin:1764261671'),

('nginx caching stale content (proxy_cache_valid expiration)', 'nginx-server', 'MEDIUM', '[{"solution": "Set proper cache validity: proxy_cache_valid 200 1h; for HTTP 200s", "percentage": 88}, {"solution": "Use Cache-Control headers from upstream if available", "percentage": 85}, {"solution": "Clear cache: rm -rf /var/cache/nginx/* and reload nginx", "percentage": 80}]'::jsonb, 'Cache directory writable by nginx user', 'Requests return fresh content after cache expiry', 'proxy_cache_valid set too high causing stale responses', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/76652569', 'admin:1764261671'),

('max_fails and fail_timeout for upstream health checks', 'nginx-server', 'MEDIUM', '[{"solution": "Use: server upstream:8000 max_fails=3 fail_timeout=30s;", "percentage": 86}, {"solution": "Set lower fail_timeout during development: 5s", "percentage": 82}, {"solution": "Monitor with: tail -f /var/log/nginx/error.log", "percentage": 81}]'::jsonb, 'Multiple upstream servers configured', 'Failover works without long outages', 'No health check configuration causes long timeout on failure', 0.79, 'haiku', NOW(), 'https://stackoverflow.com/questions/55614698', 'admin:1764261671'),

('nginx ssl_protocols directive deprecated values', 'nginx-server', 'MEDIUM', '[{"solution": "Use only: ssl_protocols TLSv1.2 TLSv1.3;", "percentage": 95}, {"solution": "Avoid: SSLv2, SSLv3, TLSv1.0, TLSv1.1 for security", "percentage": 97}, {"solution": "Test with: openssl s_client -connect domain:443", "percentage": 88}]'::jsonb, 'SSL/TLS certificate available', 'Client browsers support configured TLS versions', 'Using outdated SSL protocols causing security warnings', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/65234900', 'admin:1764261671'),

('upstream keepalive connection handling', 'nginx-server', 'LOW', '[{"solution": "Add to upstream block: keepalive 32;", "percentage": 84}, {"solution": "Set proxy_http_version 1.1 for keep-alive support", "percentage": 86}, {"solution": "Clear Connection header: proxy_set_header Connection \"\";", "percentage": 83}]'::jsonb, 'Upstream supports HTTP keep-alive', 'Reduced connection churn and latency', 'Creating new connection for each request causes overhead', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/26441459', 'admin:1764261671'),

('nginx access control with allow/deny directives', 'nginx-server', 'MEDIUM', '[{"solution": "Use allow/deny in location: allow 192.168.1.0/24; deny all;", "percentage": 89}, {"solution": "Order matters - first match wins", "percentage": 91}, {"solution": "Use ngx_http_geo_module for GeoIP blocking", "percentage": 76}]'::jsonb, 'IP ranges or GeoIP data available', 'Access control enforced correctly', 'Wrong order of allow/deny causing access exceptions', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/43119705', 'admin:1764261671'),

('nginx CORS headers for cross-origin requests', 'nginx-server', 'MEDIUM', '[{"solution": "Add: add_header Access-Control-Allow-Origin *; in location", "percentage": 87}, {"solution": "For credentials: Access-Control-Allow-Origin $http_origin;", "percentage": 85}, {"solution": "Include: Access-Control-Allow-Methods and Allow-Headers", "percentage": 82}]'::jsonb, 'CORS policy requirements defined', 'CORS headers present in response', 'Missing or overly permissive CORS headers', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/33279099', 'admin:1764261671'),

('nginx stream module for TCP/UDP proxying', 'nginx-server', 'LOW', '[{"solution": "Use stream context for non-HTTP: stream { upstream app { server app:5000; } }", "percentage": 82}, {"solution": "Compile with --with-stream module if not available", "percentage": 71}, {"solution": "Useful for database proxy, DNS, custom protocols", "percentage": 78}]'::jsonb, 'Nginx compiled with stream module', 'TCP/UDP traffic proxied successfully', 'Attempting HTTP directives in stream context', 0.74, 'haiku', NOW(), 'https://stackoverflow.com/questions/66123149', 'admin:1764261671'),

('nginx root vs alias directive differences', 'nginx-server', 'MEDIUM', '[{"solution": "root: URI appended to path - location /app { root /var/www; } serves /var/www/app/index.html", "percentage": 91}, {"solution": "alias: URI replaces path - location /app/ { alias /var/www/app/; } serves /var/www/app/index.html", "percentage": 92}, {"solution": "Always use trailing / with alias to avoid 404s", "percentage": 88}]'::jsonb, 'Static file directory structure defined', 'Requests serve correct static files', 'Confusing root vs alias causing wrong file paths', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/72357260', 'admin:1764261671'),

('rate limiting with limit_req in nginx', 'nginx-server', 'MEDIUM', '[{"solution": "Define limit_req_zone: limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;", "percentage": 89}, {"solution": "Apply: limit_req zone=api burst=20 nodelay;", "percentage": 87}, {"solution": "Monitor with: tail -f /var/log/nginx/error.log for limit messages", "percentage": 84}]'::jsonb, 'Rate limit policy requirements defined', 'Excessive requests rejected cleanly at 429', 'No rate limiting causing API abuse', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/62769425', 'admin:1764261671'),

('nginx load balancing strategy selection', 'nginx-server', 'MEDIUM', '[{"solution": "Default round-robin: upstream backend { server app1; server app2; }", "percentage": 87}, {"solution": "Use least_conn: upstream backend { least_conn; server app1; }", "percentage": 83}, {"solution": "Use ip_hash: upstream backend { ip_hash; server app1; }", "percentage": 79}]'::jsonb, 'Multiple upstream servers available', 'Load distributed according to strategy', 'Round-robin causing uneven load with different server capacity', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/55614698', 'admin:1764261671');

COMMIT;
