-- Database CORS Errors Mining (10 entries)
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('Firebase Realtime Database CORS: Request from another blocked source', 'database', 'HIGH', '[{"solution": "Go to Firebase console -> Authentication -> Sign-in method -> Authorized domains and add your IP Address or domain", "percentage": 95}, {"solution": "For REST API calls, append .json to your URL endpoint (e.g., https://example.europe-west1.firebasedatabase.app/data.json)", "percentage": 85}]'::jsonb, 'Firebase project with Realtime Database configured', 'API requests succeed from your domain, console shows domain in Authorized domains list', 'Forgetting to add the IP or domain to authorized list, using wrong Firebase endpoint', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/46963855/firebase-realtime-database-cors-issue', 'admin:1764191559'),

('Spring Boot Dynamically retrieve CORS configuration from database: changes not reflected until restart', 'database', 'HIGH', '[{"solution": "Implement custom CORS filter with @Component annotation that queries database at request time, wrap in cache layer that updates at runtime", "percentage": 90}, {"solution": "Create CorsService with updateCorsConfig() method that updates both DB and in-memory cache, avoiding need to restart", "percentage": 88}]'::jsonb, 'Spring Boot project with database connection, Spring Data JPA configured', 'CORS config changes applied immediately without restart, requests from new origins succeed', 'Setting CORS only at startup via CorsFilter bean, not updating cache when DB changes', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/60274482/dynamicallly-retrieve-spring-boot-cors-configuration-from-database-for-specific', 'admin:1764191559'),

('Azure Cosmos DB CORS error: Access to fetch blocked by CORS policy', 'database', 'HIGH', '[{"solution": "Go to CosmosDB account in Azure portal -> Settings -> CORS -> add your app origin URL to Allowed Origins field", "percentage": 96}, {"solution": "For development, temporarily use * as allowed origin, then restart your application", "percentage": 90}]'::jsonb, 'Azure Cosmos DB account, JavaScript SDK (@azure/cosmos)', 'Requests from your domain/origin succeed, CORS errors no longer appear in browser console', 'Forgetting to restart app after CORS changes, using wrong origin format', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/60288353/dealing-with-an-access-to-fetch-blocked-by-cors-policy-exception-in-react-app', 'admin:1764191559'),

('Firebase Realtime Database CORS header Access-Control-Allow-Origin missing', 'database', 'HIGH', '[{"solution": "Import Firebase SDK from correct CDN URL: https://www.gstatic.com/firebasejs/VERSION/firebase-database.js instead of trying to import from database URL", "percentage": 97}, {"solution": "Verify Firebase config contains correct databaseURL and all domains are in authorized domains list", "percentage": 92}]'::jsonb, 'Firebase SDK loaded from CDN', 'CORS errors disappear, database reads succeed from browser', 'Attempting to import Firebase SDK directly from database endpoint URL', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/72039831/firebase-real-time-database-cors-header-access-control-allow-origin-missing', 'admin:1764191559'),

('CORS error calling MongoDB database from backend via proxy: No Access-Control-Allow-Origin header', 'database', 'HIGH', '[{"solution": "Set CORS headers at top of Express app BEFORE all routes using middleware: res.set(''Access-Control-Allow-Origin'', ''*''), order matters", "percentage": 94}, {"solution": "Use cors npm package at app root: app.use(cors()); or specify allowed origins: app.use(cors({ origin: [''http://localhost'', ''https://youromain.com''] }))", "percentage": 92}]'::jsonb, 'Express.js server with cors npm package or manual header configuration', 'Cross-origin requests succeed, CORS errors no longer appear in browser', 'Setting CORS headers on individual routes instead of globally, setting headers after routes are defined', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/73098673/cors-error-in-client-when-calling-mongodb-database-from-backend', 'admin:1764191559'),

('MongoDB Golang backend CORS: Response to preflight request doesn''t pass access control check', 'database', 'HIGH', '[{"solution": "Handle OPTIONS preflight requests in route handler: if req.Method == http.MethodOptions { w.WriteHeader(http.StatusOK); return }", "percentage": 93}, {"solution": "Set CORS headers for all HTTP methods: res.Header().Set(''Access-Control-Allow-Methods'', ''GET,HEAD,OPTIONS,POST,PUT,DELETE'')", "percentage": 91}]'::jsonb, 'Golang backend with mux router, MongoDB connection', 'DELETE and PUT requests succeed without preflight errors', 'Forgetting to handle OPTIONS requests, not including DELETE/PUT in allowed methods', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/58450951/blocked-by-cors-policy-error-when-calling-to-mongo-golang-db-with-angular-web-ap', 'admin:1764191559'),

('Node.js Express Mongoose MongoDB CORS: preflight OPTIONS check before real request fails', 'database', 'HIGH', '[{"solution": "Add OPTIONS request handler before route handlers: res.header(''Access-Control-Allow-Methods'', ''PATCH, POST, GET, PUT, DELETE, OPTIONS''); if (req.method === ''OPTIONS'') return res.send(200);", "percentage": 94}, {"solution": "Install and use cors middleware at app level: const cors = require(''cors''); app.use(cors());", "percentage": 92}]'::jsonb, 'Node.js with Express and Mongoose', 'Cross-origin requests complete successfully, preflight OPTIONS requests return 200', 'Not handling OPTIONS requests, setting headers on wrong route', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/31548654/node-express-mongoose-mongodb-cors-failure', 'admin:1764191559'),

('CouchDB CORS: HTTP OPTIONS method not allowed for _users database in preflight request', 'database', 'HIGH', '[{"solution": "Run: npm install --global add-cors-to-couchdb && add-cors-to-couchdb http://example.com:5984 -u username -p password", "percentage": 88}, {"solution": "Use Apache/Nginx reverse proxy instead of direct CORS: proxy_pass http://localhost:5984 with proper header forwarding", "percentage": 85}]'::jsonb, 'CouchDB instance running, Node.js with npm', 'PUT/DELETE requests to CouchDB succeed, OPTIONS preflight returns 204, no 405 errors', 'Trying to configure CORS directly on all endpoints, not handling _bulk_docs restrictions', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/32304973/http-options-method-not-allowed-for-users-database-in-couchdb', 'admin:1764191559'),

('Netlify Node.js Express backend CORS error from React frontend: No Access-Control-Allow-Origin header present', 'database', 'HIGH', '[{"solution": "Set CORS headers at app root BEFORE route definition using middleware function that sets headers on every response", "percentage": 95}, {"solution": "Use npm cors package: app.use(cors()); ensure it''s before all route definitions", "percentage": 93}]'::jsonb, 'Express.js backend deployed on Netlify, React frontend', 'Cross-origin requests from frontend succeed, no CORS errors in browser console', 'Setting CORS headers after routes, setting headers in response object without middleware', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/73098673/cors-error-in-client-when-calling-mongodb-database-from-backend', 'admin:1764191559'),

('Socket.io database CORS: Access to XMLHttpRequest blocked from different IP address on same network', 'database', 'MEDIUM', '[{"solution": "Initialize Socket.io with CORS options: io(server, { cors: { origin: ''*'', methods: [''GET'', ''POST''] } })", "percentage": 89}, {"solution": "Use absolute URL with same IP/domain for both server and client, not localhost mixed with IP address", "percentage": 87}]'::jsonb, 'Node.js with Express, Socket.io library, MySQL database', 'Socket.io connection succeeds from remote IP on network, no CORS errors', 'Mixing localhost and IP addresses in URLs, not configuring Socket.io CORS separately', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/78217354/access-control-allow-origin-error-even-though-cors-is-enabled', 'admin:1764191559');
