INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('You should explicitly define the GraphQL schema for your source data', 'gatsby', 'HIGH', '[{"solution": "Use schema customization to define GraphQL types: https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions", "percentage": 95}, {"solution": "Check for null/falsy values in query results before using createPage", "percentage": 90}]'::jsonb, 'GraphQL knowledge', 'Pages created without errors', 'Assuming all fields exist without defining schema', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/61340384/gatsby-build-createpages-error-handling', 'admin:1764210403'),

('Error: page resources for /innovation/ not found. Not rendering React', 'gatsby', 'HIGH', '[{"solution": "Clear .cache folder: rm -rf .cache", "percentage": 85}, {"solution": "Clear browser history/cache", "percentage": 60}, {"solution": "Downgrade to stable Gatsby version like 2.20.36", "percentage": 75}]'::jsonb, 'Gatsby project setup', 'Page loads correctly', 'Not clearing cache after changes', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/64732966/gatsby-error-page-resources-not-found-not-rendering-react-after-gatsby-build', 'admin:1764210403'),

('ERROR #11903 COMPILATION There was an unhandled error during compilation', 'gatsby', 'HIGH', '[{"solution": "Move project folder outside OneDrive or cloud sync directories", "percentage": 92}, {"solution": "Use only ASCII characters in file paths", "percentage": 88}, {"solution": "Verify project is not in a synchronized cloud folder", "percentage": 90}]'::jsonb, 'Windows/project setup', 'gatsby develop completes successfully', 'Storing project in OneDrive or cloud folders', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/71552122/error-11903-when-developing-first-gatsby-project', 'admin:1764210403'),

('The field "Mdx.excerpt." was explicitly defined as non-nullable via schema customization API', 'gatsby', 'MEDIUM', '[{"solution": "Add excerpt field to MDX front matter: excerpt: ''This is my excerpt''", "percentage": 98}, {"solution": "Make excerpt nullable in schema: excerpt: String (not String!)", "percentage": 92}]'::jsonb, 'MDX/Gatsby Plugin MDX', 'gatsby build completes', 'Missing required front matter fields', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/71445802/when-i-was-a-gatsby-build-i-get-2-errors', 'admin:1764210403'),

('Cannot read property ''imgSrc'' of undefined during gatsby build', 'gatsby', 'HIGH', '[{"solution": "Add undefined check in component: if(product === undefined) return null", "percentage": 96}, {"solution": "Verify context data is passed correctly to createPage", "percentage": 92}, {"solution": "Use console.log in gatsby-node.js to debug variable structure", "percentage": 88}]'::jsonb, 'Dynamic page creation, React patterns', 'gatsby build HTML completes', 'Assuming context variables always exist', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/54402112/gatsby-develop-command-runs-but-gatsby-build-gives-error', 'admin:1764210403'),

('Cannot register existing type ''VipsObject'' - sharp module errors', 'gatsby', 'MEDIUM', '[{"solution": "Uninstall gatsby-plugin-favicon and use alternative icon plugin", "percentage": 88}, {"solution": "Clear yarn/npm cache: yarn cache clean or npm cache clean --force", "percentage": 85}, {"solution": "Delete node_modules and reinstall dependencies", "percentage": 82}]'::jsonb, 'Node modules, native bindings', 'gatsby develop runs without sharp errors', 'Using outdated plugins with sharp incompatibilities', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/57603001/gatsby-project-giving-strange-errors-and-is-unable-to-build', 'admin:1764210403'),

('Hydration error in production: Minified React error #418 or #423', 'gatsby', 'MEDIUM', '[{"solution": "Run gatsby build && gatsby serve to reproduce locally", "percentage": 90}, {"solution": "Wrap window/document references in if guard: if (typeof window !== ''undefined'')", "percentage": 98}, {"solution": "Enable DEV_SSR flag in gatsby-config.js to test SSR issues", "percentage": 94}]'::jsonb, 'Server-side rendering, React hooks', 'No hydration errors in gatsby serve output', 'Using browser objects outside useEffect or without guards', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/78110409/gatsby-hydration-error-on-production-but-everything-works-fine-locally', 'admin:1764210403'),

('Dynamic pages not generating - gatsby-node.js file not executing correctly', 'gatsby', 'HIGH', '[{"solution": "Check for duplicate exports.onCreateWebpackConfig - second one overrides first", "percentage": 96}, {"solution": "Run gatsby clean before gatsby develop/build", "percentage": 88}, {"solution": "Verify GraphQL query returns expected data with result.errors check", "percentage": 94}]'::jsonb, 'Gatsby Node APIs, dynamic page creation', 'All expected pages generated', 'Duplicate API exports or missing error handling', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/69388322/gatsby-js-is-not-generating-the-dynamic-pages-that-the-gatsby-node-js-files-gra', 'admin:1764210403'),

('ERROR Something went wrong installing the ''sharp'' module - Cannot find module', 'gatsby', 'HIGH', '[{"solution": "Complete Windows system reset and reinstall Node/Gatsby from scratch", "percentage": 70}, {"solution": "Delete node_modules and package-lock.json, reinstall: npm install", "percentage": 85}, {"solution": "Ensure Node.js and Python are properly installed for native module compilation", "percentage": 82}]'::jsonb, 'Windows environment, native modules', 'sharp module loads without errors', 'Environment conflicts or incomplete Node.js installation', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/63997253/error-installing-gatsby-starter-something-went-wrong-installing-the-sharp-mod', 'admin:1764210403'),

('npm ERR! Maximum call stack size exceeded when running gatsby new', 'gatsby', 'HIGH', '[{"solution": "Install Node.js via nvm instead of installer: nvm install 14.13.1", "percentage": 92}, {"solution": "Upgrade gatsby-cli: npm update -g gatsby-cli", "percentage": 88}, {"solution": "Hard cache clean: npm cache clean --force", "percentage": 85}]'::jsonb, 'Node version management, npm', 'gatsby new completes successfully', 'Using Node installed via system package manager with permission issues', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/62454262/gatsby-command-failed-with-exit-code-1-npm-install', 'admin:1764210403');
