-- React Errors Mining - 10 entries
-- Mined from Stack Overflow 2025-11-26

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Error Boundary not catching render errors', 'react', 'HIGH', '[{"solution": "Use Error Boundary component with componentDidCatch lifecycle method to catch render errors", "percentage": 95}, {"solution": "Wrap child components inside Error Boundary to catch errors in their tree", "percentage": 92}, {"solution": "Use react-error-boundary package for simpler implementation", "percentage": 88}]'::jsonb, 'React 16+, Error Boundary pattern', 'No white screen on error', 'Not wrapping component tree properly, only catching sync errors', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/36897434/error-handling-in-react-best-practices', 'admin:1764210695'),
('TypeError: Cannot read property of undefined in render', 'react', 'HIGH', '[{"solution": "Add default values to props: const { data = [] } = props", "percentage": 97}, {"solution": "Use optional chaining: data?.length", "percentage": 93}, {"solution": "Add null checks before accessing properties", "percentage": 90}]'::jsonb, 'JavaScript, understanding null vs undefined', 'Component renders without errors', 'Not checking array/object existence before access', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/31111771/can-you-catch-all-errors-of-a-react-js-app-with-a-try-catch-block', 'admin:1764210695'),
('Handling HTTP errors in React async operations', 'react', 'HIGH', '[{"solution": "Use window.onerror and window.onunhandledrejection for global error capture", "percentage": 94}, {"solution": "Implement try/catch blocks in async methods", "percentage": 89}, {"solution": "Use error interceptors in Axios for HTTP error handling", "percentage": 91}]'::jsonb, 'Async/await, Promise handling, Axios setup', 'Errors logged to server, no unhandled rejections', 'Forgetting to handle async errors, missing error interceptors', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/31111771/can-you-catch-all-errors-of-a-react-js-app-with-a-try-catch-block', 'admin:1764210695'),
('Rendering error when array.length is undefined', 'react', 'HIGH', '[{"solution": "Check array existence: if (array && array.length > 0)", "percentage": 96}, {"solution": "Use Array.isArray() to validate array type", "percentage": 94}, {"solution": "Set default empty array in destructuring", "percentage": 92}]'::jsonb, 'JavaScript fundamentals, array methods', 'Conditional rendering without white screen', 'Not validating data types, skipping null checks', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/73216579/how-to-display-error-message-if-something-not-found-in-reactjs', 'admin:1764210695'),
('npx create-react-app fails with template error', 'react', 'MEDIUM', '[{"solution": "Run npx clear-npx-cache before creating app", "percentage": 98}, {"solution": "Uninstall global create-react-app: npm uninstall -g create-react-app", "percentage": 96}, {"solution": "Use Vite or other modern alternatives for project setup", "percentage": 85}]'::jsonb, 'Node.js 14+, npm/yarn, command line', 'Project created successfully', 'Outdated global create-react-app, corrupted npm cache', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/72258091/when-im-trying-to-create-react-file-it-is-showing-me-error', 'admin:1764210695'),
('Capturing global uncaught React errors', 'react', 'HIGH', '[{"solution": "Use Error Boundary component wrapping entire app", "percentage": 93}, {"solution": "Implement window.onerror listener for JavaScript errors", "percentage": 88}, {"solution": "Use window.onunhandledrejection for promise rejections", "percentage": 87}]'::jsonb, 'React lifecycle, event listeners, error handling', 'All errors logged externally, graceful fallback UI', 'Only catching sync errors, missing async error handling', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/40234855/capturing-react-errors-globally', 'admin:1764210695'),
('Handling different HTTP error status codes in React', 'react', 'MEDIUM', '[{"solution": "Use instanceof to check error types in catch block", "percentage": 92}, {"solution": "Check error.response?.status for HTTP status codes", "percentage": 94}, {"solution": "Use axios.isAxiosError() helper for identifying axios errors", "percentage": 91}]'::jsonb, 'Axios library, HTTP status codes, error instances', 'Proper error message displayed per status code', 'Not checking response structure, using optional chaining incorrectly', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/75718461/handling-errors-for-different-response-status-in-react', 'admin:1764210695'),
('React Hooks called conditionally - Rendered more hooks than previous render', 'react', 'HIGH', '[{"solution": "Call hooks only at top level, never in conditions or loops", "percentage": 98}, {"solution": "Call hooks only from React function components or custom hooks", "percentage": 97}, {"solution": "Ensure same number of hooks are called on every render", "percentage": 95}]'::jsonb, 'React Hooks (useState, useEffect), functional components', 'No hook-related errors, consistent renders', 'Calling hooks conditionally, calling in loops, calling in nested functions', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/60905050/minified-react-error-310-use-the-non-minified-dev-environment-for-full-errors', 'admin:1764210695'),
('Minified React error message decoding', 'react', 'MEDIUM', '[{"solution": "Visit https://reactjs.org/docs/error-decoder.html?invariant=XXX with error number", "percentage": 100}, {"solution": "Use non-minified development build for debugging", "percentage": 93}, {"solution": "Check webpack build mode: use --mode development", "percentage": 89}]'::jsonb, 'React production vs development builds, webpack', 'Error messages decoded, original error identified', 'Using production build without error decoder', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/50497026/minified-react-error-152-how-to-resolve-this', 'admin:1764210695'),
('Calling setState in render method causing infinite loop', 'react', 'MEDIUM', '[{"solution": "Move setState logic to componentDidMount or componentDidUpdate", "percentage": 95}, {"solution": "Initialize state in constructor instead of render", "percentage": 97}, {"solution": "Use proper lifecycle methods to avoid render-time state mutations", "percentage": 94}]'::jsonb, 'React lifecycle methods, class components, state management', 'Component renders once without loops', 'Calling handleSelect directly in render, calling setState synchronously', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/51849734/how-to-find-out-where-the-error-is-coming-from-in-reactjs', 'admin:1764210695');
