INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('This project is configured to use yarn', 'package-manager', 'HIGH', '[{"solution": "Change packageManager in package.json from yarn to pnpm", "percentage": 95}, {"solution": "Remove yarn.lock and yarn config from home directory", "percentage": 85}]'::jsonb, 'package.json with packageManager field', 'pnpm install succeeds without error', 'Leaving yarn.lock in place or having yarn config in home directory', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/72201239/pnpm-install-usage-error-this-project-is-configured-to-use-yarn', 'admin:1764227402'),

('ERR_PNPM_OUTDATED_LOCKFILE Cannot install with frozen-lockfile', 'package-manager', 'HIGH', '[{"solution": "Run pnpm install to update pnpm-lock.yaml", "percentage": 98}, {"solution": "Delete pnpm-lock.yaml and push updated file to repository", "percentage": 85}]'::jsonb, 'Lockfile out of sync with package.json', 'pnpm-lock.yaml matches package.json', 'Mixing npm and pnpm in same project', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/76869615/next-js-how-to-fix-err-pnpm-outdated-lockfile', 'admin:1764227402'),

('ERR_PNPM_PEER_DEP_ISSUES Unmet peer dependencies found', 'package-manager', 'HIGH', '[{"solution": "Enable strict-peer-dependencies=true in .npmrc", "percentage": 92}, {"solution": "Use pnpm install --resolution-only --config.strict-peer-dependencies=true", "percentage": 88}]'::jsonb, 'pnpm installation with peer dependency conflicts', 'No ERR_PNPM_PEER_DEP_ISSUES errors thrown', 'Not setting strict-peer-dependencies when peer conflicts exist', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/78644964/can-pnpm-installation-errors-due-to-missing-peer-dependencies-be-detected-in-scr', 'admin:1764227402'),

('ERR_PNPM_LINKING_FAILED Error EPERM operation not permitted rename', 'package-manager', 'HIGH', '[{"solution": "Upgrade pnpm to version 8.8.0 or later", "percentage": 89}, {"solution": "Retry pnpm install multiple times until all packages succeed", "percentage": 70}, {"solution": "Close VS Code and other processes accessing node_modules", "percentage": 85}]'::jsonb, 'Windows environment with pnpm 8.7.6 or earlier', 'pnpm install completes without EPERM errors', 'Using older pnpm versions or having open file access conflicts', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/77180619/pnpm-install-err-pnpm-linking-failed-operation-not-permitted-rename', 'admin:1764227402'),

('ERR_PNPM_SYMLINK_FAILED UNKNOWN unknown error symlink', 'package-manager', 'MEDIUM', '[{"solution": "Format drive as NTFS instead of EXFAT", "percentage": 88}, {"solution": "Use an NTFS-formatted drive instead of D: drive (EXFAT)", "percentage": 85}, {"solution": "Run pnpm install in WSL or elevated command prompt", "percentage": 72}]'::jsonb, 'Windows environment with EXFAT-formatted drive', 'pnpm install completes without SYMLINK_FAILED errors', 'Using EXFAT drive format or insufficient permissions', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/77459703/pnpm-err-pnpm-symlink-failed-error-on-windows-machine', 'admin:1764227402'),

('ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE The lockfile is broken', 'package-manager', 'MEDIUM', '[{"solution": "Upgrade pnpm to latest version", "percentage": 91}, {"solution": "Remove pnpm store: rm -rf $(pnpm store path)", "percentage": 94}, {"solution": "Run pnpm install to rebuild store", "percentage": 95}]'::jsonb, 'pnpm version < 6.30 with corrupted store', 'pnpm install completes successfully', 'Not upgrading pnpm or removing corrupted store before retry', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/72196681/err-pnpm-err-pnpm-unexpected-pkg-content-in-store-the-lockfile-is-broken-a-full', 'admin:1764227402'),

('@myorg/package-2 is not in the npm registry workspace does not recognize packages', 'package-manager', 'MEDIUM', '[{"solution": "Rename pnpm-workspaces.yml to pnpm-workspace.yaml", "percentage": 97}, {"solution": "Use --workspace flag when adding workspace dependencies", "percentage": 93}]'::jsonb, 'pnpm monorepo with workspace configuration', 'pnpm add @scope/package succeeds for workspace packages', 'Incorrect filename (pnpm-workspaces.yml vs pnpm-workspace.yaml)', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/67376863/pnpm-add-within-a-workspace-does-not-add-projects-from-workspace', 'admin:1764227402'),

('Rollup failed to resolve import vue shamefully-hoist breaks build', 'package-manager', 'MEDIUM', '[{"solution": "Set PNPM_FLAGS=--shamefully-hoist in Environment Variables", "percentage": 88}, {"solution": "Update build command to pnpm build instead of npm run build", "percentage": 87}]'::jsonb, 'Netlify deployment with pnpm and Nuxt 3', 'Nuxt build succeeds without Rollup resolution errors', 'Not setting PNPM_FLAGS or using incorrect build command', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/75771755/pnpm-install-shamefully-hoist-causes-build-fail-on-netlify', 'admin:1764227402'),

('pnpm patch does not take effect after applying', 'package-manager', 'LOW', '[{"solution": "Verify patch is applied to correct file entry point", "percentage": 85}, {"solution": "Check that you patched the actual entry file not a subfile", "percentage": 92}]'::jsonb, 'pnpm patch applied but changes not visible', 'Patched code reflects changes in node_modules', 'Patching wrong file or checking wrong location for changes', 0.78, 'haiku', NOW(), 'https://stackoverflow.com/questions/78565448/pnpm-patch-successfully-patches-the-project-but-the-patch-does-not-take-effect', 'admin:1764227402'),

('Error ENOENT no such file or directory Windows username with space', 'package-manager', 'MEDIUM', '[{"solution": "Run pnpm install from directory without spaces in path", "percentage": 89}, {"solution": "Install from Google Drive folder or user directory with spaces", "percentage": 86}, {"solution": "Use corepack enable instead of standalone installer", "percentage": 91}]'::jsonb, 'Windows with directory paths containing spaces', 'pnpm install succeeds without ENOENT errors', 'Running from paths with spaces or using buggy installer', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77297035/pnpm-install-error-enoent-no-such-file-or-directory', 'admin:1764227402'),

('Stop pnpm from hoisting common deps isolate subdirectories', 'package-manager', 'MEDIUM', '[{"solution": "Set node-linker=hoisted in .npmrc", "percentage": 77}, {"solution": "Use --shamefully-hoist flag to match npm behavior", "percentage": 70}]'::jsonb, 'pnpm monorepo with hoisting to root node_modules', 'Dependencies isolated in project subdirectories', 'Default pnpm hoisting behavior not matching project requirements', 0.73, 'haiku', NOW(), 'https://stackoverflow.com/questions/78977132/stop-pnpm-from-hoisting-common-deps-isolate-subdirectories', 'admin:1764227402'),

('Multiple react versions hoisting conflict in monorepo', 'package-manager', 'MEDIUM', '[{"solution": "Create alias for older react version in package.json", "percentage": 82}, {"solution": "Use npm alias: npm:react@16 to avoid hoisting conflict", "percentage": 88}]'::jsonb, 'pnpm monorepo with different react versions per workspace', 'Each workspace uses correct react version without conflicts', 'Hoisting resolves to higher version automatically', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/77921885/turbo-monorepo-with-pnpm-and-two-react-versions-hoisting', 'admin:1764227402'),

('Set auto-install-peers=true for peer dependencies', 'package-manager', 'HIGH', '[{"solution": "Create .npmrc file in project root with auto-install-peers=true", "percentage": 96}, {"solution": "Run pnpm config set auto-install-peers true --location project", "percentage": 94}]'::jsonb, 'pnpm project with unmet peer dependencies', 'Peer dependencies auto-install without manual steps', 'Not setting .npmrc in project root or using global config', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/72468635/pnpm-peer-dependencies-auto-install', 'admin:1764227402'),

('Peer dependencies conflict react version mismatch', 'package-manager', 'HIGH', '[{"solution": "Use pnpm.peerDependencyRules.allowedVersions in package.json", "percentage": 89}, {"solution": "Downgrade package to compatible react version", "percentage": 82}]'::jsonb, 'pnpm with conflicting peer dependency versions', 'Installation succeeds without peer dependency warnings', 'Not allowing compatible versions or forcing exact matches', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/74171399/what-is-the-best-practice-to-resolving-this-peer-dependencies-issue', 'admin:1764227402'),

('EACCES permission denied pnpm install rename node_modules', 'package-manager', 'MEDIUM', '[{"solution": "Ensure correct file permissions: sudo chown -R user:user directory", "percentage": 85}, {"solution": "Run pnpm install with elevated privileges or fix store permissions", "percentage": 80}]'::jsonb, 'Linux/Unix with permission issues on node_modules', 'pnpm install completes without EACCES errors', 'Incorrect ownership or insufficient permissions on node_modules', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/76453681/pnpm-install-eacces-permission-denied', 'admin:1764227402'),

('ERR_PNPM_NO_MATCHING_VERSION no matching version found', 'package-manager', 'MEDIUM', '[{"solution": "Use overrides to specify compatible version", "percentage": 88}, {"solution": "Use resolutions field to force exact version", "percentage": 86}]'::jsonb, 'pnpm with transitive dependency version mismatch', 'All dependencies resolve to compatible versions', 'Transitive dependency version conflicts not resolved', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/78890225/getting-error-when-deploying-to-vercel-err-pnpm-no-matching-version', 'admin:1764227402'),

('ERR_PNPM_BAD_PM_VERSION project configured to use pnpm v8.9.0', 'package-manager', 'MEDIUM', '[{"solution": "Install specified pnpm version globally: npm install -g pnpm@8.9.0", "percentage": 91}, {"solution": "Update packageManager field in package.json to desired version", "percentage": 89}]'::jsonb, 'pnpm version mismatch between project and global install', 'pnpm version matches project requirement', 'Using different pnpm version than specified in packageManager field', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/78480073/err-pnpm-bad-pm-version-this-project-is-configured-to-use-v8-9-0-of-pnpm-your-c', 'admin:1764227402'),

('Unsupported URL Type workspace protocol in npm', 'package-manager', 'MEDIUM', '[{"solution": "Use workspace:* instead of workspace: in pnpm", "percentage": 94}, {"solution": "Switch from npm to yarn or pnpm for workspace support", "percentage": 88}]'::jsonb, 'npm with workspace dependencies not yet supported', 'workspace:* dependencies resolve correctly', 'Using workspace: protocol with npm instead of pnpm/yarn', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/70546696/getting-error-npm-err-code-eunsupportedprotocol-while-running-npm-install', 'admin:1764227402'),

('ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL workspace build order dependency', 'package-manager', 'MEDIUM', '[{"solution": "Use workspace:* dependencies instead of link:", "percentage": 93}, {"solution": "Specify build order with --filter and --workspace-concurrency=1", "percentage": 87}]'::jsonb, 'pnpm monorepo with inter-workspace dependencies', 'All workspace builds complete in correct dependency order', 'Not declaring workspace dependencies or incorrect dependency syntax', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77667725/pnpm-recursive-install-order', 'admin:1764227402'),

('pnpm store corrupted modified files integrity check failed', 'package-manager', 'LOW', '[{"solution": "Run pnpm install --force to reverify and relink packages", "percentage": 92}, {"solution": "Delete node_modules and run pnpm install", "percentage": 89}, {"solution": "Run pnpm store status to identify mutated packages", "percentage": 85}]'::jsonb, 'pnpm with manually modified node_modules files', 'Packages reverified and restored from store', 'Not using --force flag or deleting corrupted files manually', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/52594626/how-to-remove-a-package-from-pnpm-store-or-force-re-download-it', 'admin:1764227402');
