-- Android Kotlin Errors Migration - 40 entries for clauderepo
-- Generated: 2025-11-27

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

-- NullPointerException Errors (8 entries)
('Kotlin NullPointerException when casting TextView from findViewById', 'android-kotlin', 'HIGH', '[{"solution": "Initialize EditText properly before use: val date = findViewById<EditText>(R.id.editTextDate)", "percentage": 98}, {"solution": "Use safe cast: val date = findViewById<View>(R.id.date) as? EditText", "percentage": 95}]'::jsonb, 'Android findViewById API', 'No NullPointerException thrown', 'Initializing view to null', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/44450816/nullpointerexception-in-kotlin', 'admin:1764221360'),

('Kotlin non-null assertion operator throws NPE on null value', 'android-kotlin', 'HIGH', '[{"solution": "Use optional chaining instead of !!: val text = obj?.property instead of obj!!.property", "percentage": 99}, {"solution": "Check for null first: if (obj != null) { obj.property }", "percentage": 97}]'::jsonb, 'Kotlin null safety', 'No KotlinNullPointerException', 'Over-using !! operator', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/48597653/kotlin-throws-nullpointer-exception', 'admin:1764221360'),

('NPE in immutable Kotlin List from Gson parsing', 'android-kotlin', 'HIGH', '[{"solution": "Use List<DrawableObject?> for nullable items from JSON", "percentage": 94}, {"solution": "Filter out null values: list.filterNotNull()", "percentage": 92}]'::jsonb, 'Gson, Kotlin type system', 'No NPE during iteration', 'Assuming all list items are non-null', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/63569945/how-in-kotlin-on-android-can-a-null-pointer-exception-occur-in-an-immutable-list', 'admin:1764221360'),

('NullPointerException when Activity or Fragment is destroyed', 'android-kotlin', 'HIGH', '[{"solution": "Check if activity is not null before use: val a = activity; if (a != null) { recyclerAdapter = HomeRecyclerAdapter(a, displayList) }", "percentage": 96}, {"solution": "Use requireActivity() instead of activity", "percentage": 91}]'::jsonb, 'Android Fragment lifecycle', 'Adapter initialized successfully', 'Ignoring fragment lifecycle', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/63062840/kotlin-null-pointer-exception-when-trying-to-open-activity', 'admin:1764221360'),

('Parameter specified as non-null is null in data class', 'android-kotlin', 'HIGH', '[{"solution": "Provide explicit default value: StopwatchViewState(\"00:00\")", "percentage": 97}, {"solution": "Use secondary constructor: constructor(elapsed: String?) : this(elapsed ?: \"00:00\")", "percentage": 94}]'::jsonb, 'Kotlin data classes, reflection', 'Object instantiation succeeds', 'Relying on default parameters with reflection', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/77666763/android-kotlin-java-lang-nullpointerexception-parameter-specified-as-non-null', 'admin:1764221360'),

('Kotlin NPE from uninitialized EditText in onCreate', 'android-kotlin', 'HIGH', '[{"solution": "Initialize EditText before setting text: val date = findViewById<EditText>(R.id.date)", "percentage": 97}, {"solution": "Set value after initialization, not before", "percentage": 96}]'::jsonb, 'Android Activity lifecycle', 'UI elements display correctly', 'Setting values before findViewById', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/47344537/fatal-exception-main-kotlinnullpointerexception', 'admin:1764221360'),

('NPE from superclass constructor calling overridable method', 'android-kotlin', 'MEDIUM', '[{"solution": "Do not invoke overridable methods in superclass constructor", "percentage": 98}, {"solution": "Initialize all dependent fields before calling super()", "percentage": 96}]'::jsonb, 'Kotlin inheritance, constructor order', 'Constructor completes without error', 'Calling virtual methods from superclass init', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/68417112/kotlin-null-pointer-exception-from-value-not-being-initialized-prior-to-parent-c', 'admin:1764221360'),

('NPE from null repository query result', 'android-kotlin', 'HIGH', '[{"solution": "Change function signature to nullable: fun getAlarm(id: Long): Alarm?", "percentage": 95}, {"solution": "Handle null case before using value: val alarm = repo.getAlarm(id) ?: return", "percentage": 93}]'::jsonb, 'Room database, Kotlin nullable types', 'Query returns valid result or null', 'Assuming non-null database result', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/72745703/why-do-i-keep-getting-this-null-pointer-exception-android-app-kotlin', 'admin:1764221360'),

-- ActivityNotFoundException Errors (6 entries)
('ActivityNotFoundException from passing layout ID instead of Activity class', 'android-kotlin', 'HIGH', '[{"solution": "Use Activity class instead of layout resource: Intent(this, Registration::class.java)", "percentage": 99}, {"solution": "Change R.layout.registration::class.java to Registration::class.java", "percentage": 99}]'::jsonb, 'Android Intent API, Android manifest', 'Activity launches successfully', 'Confusing resource IDs with class references', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/60920801/android-content-activitynotfoundexception-unable-to-find-explicit-activity-clas', 'admin:1764221360'),

('Intent constructor requires context and activity class', 'android-kotlin', 'HIGH', '[{"solution": "Provide both context and activity class: Intent(this, ActivityName::class.java)", "percentage": 99}, {"solution": "Replace resource ID with Activity class reference", "percentage": 99}]'::jsonb, 'Android Intent, Activity manifest', 'Activity starts without error', 'Using resource IDs instead of class objects', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/10908534/android-content-activitynotfoundexception-unable-to-find-explicit-activity-clas', 'admin:1764221360'),

('Activity not found because not declared in AndroidManifest.xml', 'android-kotlin', 'HIGH', '[{"solution": "Add activity to manifest: <activity android:name=\".ActivityName\" />", "percentage": 100}, {"solution": "Use full package path if in subdirectory: <activity android:name=\".package.ActivityName\" />", "percentage": 98}]'::jsonb, 'AndroidManifest.xml', 'Activity launches', 'Missing or incorrect manifest declaration', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/66516163/android-content-activitynotfoundexception-no-activity-found-to-handle-intent', 'admin:1764221360'),

('ActivityNotFoundException from intent with wrong package name', 'android-kotlin', 'MEDIUM', '[{"solution": "Check manifest for correct package structure", "percentage": 91}, {"solution": "Use full activity path: com.package.Facebook.Example", "percentage": 89}]'::jsonb, 'Package structure, manifest', 'Intent resolves correctly', 'Package name mismatch in manifest', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/78150882/android-crash-a-app-by-android-content-activitynotfoundexception', 'admin:1764221360'),

('Activity not declared or using wrong activity class reference', 'android-kotlin', 'HIGH', '[{"solution": "Match activity name in Intent with manifest declaration", "percentage": 96}, {"solution": "Use correct class name: lovecalculate::class.java instead of activity_lovecalculate::class.java", "percentage": 98}]'::jsonb, 'Android manifest, Activity naming', 'Activity starts correctly', 'Wrong class reference in Intent', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/52470050/unable-to-find-explicit-activity-class-have-you-declared-this-activity-in-your-a', 'admin:1764221360'),

('Gmail intent with wrong action and URI scheme', 'android-kotlin', 'MEDIUM', '[{"solution": "Use Intent.ACTION_SENDTO with mailto: scheme: Intent(Intent.ACTION_SENDTO, Uri.parse(\"mailto:email@example.com\"))", "percentage": 97}, {"solution": "Replace Intent.ACTION_VIEW with Intent.ACTION_SENDTO", "percentage": 96}]'::jsonb, 'Intent actions, URI schemes', 'Email app opens correctly', 'Incorrect intent action for email', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/47845615/unable-to-find-explicit-activity-kotlin', 'admin:1764221360'),

-- NetworkOnMainThreadException Errors (5 entries)
('NetworkOnMainThreadException from synchronous network call', 'android-kotlin', 'HIGH', '[{"solution": "Use enqueue for async: client.newCall(request).enqueue(callback)", "percentage": 97}, {"solution": "Move to background thread with Thread or coroutines", "percentage": 95}]'::jsonb, 'Android network, OkHttp', 'Network response received', 'Using execute() instead of enqueue()', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/6343166/how-can-i-fix-android-os-networkonmainthreadexception', 'admin:1764221360'),

('NetworkOnMainThreadException when using blocking network API', 'android-kotlin', 'HIGH', '[{"solution": "Launch coroutine on IO dispatcher: withContext(Dispatchers.IO) { blockingCall() }", "percentage": 98}, {"solution": "Use Thread({ networkCall() }).start()", "percentage": 94}]'::jsonb, 'Coroutines, Dispatchers', 'Network call completes successfully', 'Blocking call on Main dispatcher', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/47424402/how-bypass-networkonmainthreadexception-on-kotlin', 'admin:1764221360'),

('OkHttp NetworkOnMainThreadException with execute()', 'android-kotlin', 'HIGH', '[{"solution": "Use enqueue with async callback: client.newCall(request).enqueue(...)", "percentage": 97}, {"solution": "Wrap in Dispatchers.IO: withContext(Dispatchers.IO) { client.newCall(request).execute() }", "percentage": 96}]'::jsonb, 'OkHttp, Android networking', 'Response received successfully', 'Synchronous execute() on main thread', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/70570378/kotlin-okhttp-android-os-networkonmainthreadexception', 'admin:1764221360'),

('Coroutine suspension does not unblock blocking network calls', 'android-kotlin', 'MEDIUM', '[{"solution": "Use withContext to switch dispatcher: withContext(Dispatchers.IO) { Jsoup.connect(url).get() }", "percentage": 96}, {"solution": "Implement suspend function wrapper around blocking API", "percentage": 92}]'::jsonb, 'Coroutines, suspend functions', 'Network call completes on correct dispatcher', 'Assuming suspension unblocks threads', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/53582860/is-networkonmainthreadexception-valid-for-a-network-call-in-a-coroutine', 'admin:1764221360'),

('Socket connection causes NetworkOnMainThreadException', 'android-kotlin', 'MEDIUM', '[{"solution": "Move socket operations to background thread", "percentage": 95}, {"solution": "Use Dispatchers.IO in coroutines", "percentage": 93}]'::jsonb, 'Socket API, threading', 'Socket connects without ANR', 'Network socket on main thread', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/59918185/android-os-networkonmainthreadexception-in-kotlin-while-using-socket', 'admin:1764221360'),

-- OutOfMemoryError Errors (3 entries)
('OutOfMemoryError from string concatenation loop', 'android-kotlin', 'HIGH', '[{"solution": "Use StringBuilder instead of String concatenation: output = StringBuilder()", "percentage": 99}, {"solution": "Clear output variable inside loop to prevent memory growth", "percentage": 97}]'::jsonb, 'String memory management', 'CSV file parsed successfully', 'String concatenation in loops', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/53302540/out-of-memory-error-in-kotlin-when-looping-through-a-medium-size-data-set', 'admin:1764221360'),

('OutOfMemoryError from large image copy operation', 'android-kotlin', 'MEDIUM', '[{"solution": "Check bitmap dimensions before copying: if (bitmap.width > maxSize) scale it", "percentage": 92}, {"solution": "Use copyTo with smaller chunks or streams", "percentage": 88}]'::jsonb, 'Bitmap operations', 'Large file copied without OOM', 'Not validating image dimensions', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/77031902/outofmemoryerror-while-using-kotlins-copyto', 'admin:1764221360'),

('OutOfMemoryError from Retrofit2 large response handling', 'android-kotlin', 'MEDIUM', '[{"solution": "Stream response instead of loading to memory: response.body.byteStream()", "percentage": 94}, {"solution": "Handle large responses in chunks", "percentage": 91}]'::jsonb, 'Retrofit2, HTTP responses', 'Large responses handled smoothly', 'Loading entire response into memory', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/64333251/out-of-memory-error-for-retrofit2-calls-in-android-kotlin', 'admin:1764221360'),

-- ANR (Application Not Responding) Errors (4 entries)
('ANR from long coroutine operation on main dispatcher', 'android-kotlin', 'MEDIUM', '[{"solution": "Use withContext(Dispatchers.Default) for CPU-intensive work", "percentage": 93}, {"solution": "Use Dispatchers.IO for blocking operations", "percentage": 92}]'::jsonb, 'Coroutines, Main thread', 'App responsive, no ANR', 'Heavy work on Main dispatcher', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/56923310/anr-from-a-coroutine', 'admin:1764221360'),

('ANR from input event dispatch timeout', 'android-kotlin', 'MEDIUM', '[{"solution": "Move UI blocking operations to background thread", "percentage": 91}, {"solution": "Use coroutines with Dispatchers.Main.immediate for faster UI updates", "percentage": 88}]'::jsonb, 'Event handling, threading', 'Touch events process within 5 seconds', 'Blocking operations during event processing', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/69191249/anr-in-android-input-dispatching-timed-out-server-is-not-responding', 'admin:1764221360'),

('ANR from MobileAds.initialize on main thread', 'android-kotlin', 'MEDIUM', '[{"solution": "Initialize MobileAds in background thread or with delay", "percentage": 89}, {"solution": "Use WorkManager to defer initialization", "percentage": 86}]'::jsonb, 'Google Mobile Ads SDK', 'App initializes without ANR', 'Blocking ads initialization in onCreate', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/78114324/anr-issue-on-mobileads-initialize-in-android-application', 'admin:1764221360'),

('ANR from bitmap drawing with color matrix', 'android-kotlin', 'MEDIUM', '[{"solution": "Draw bitmap on background thread: Thread { Canvas.draw() }.start()", "percentage": 87}, {"solution": "Use Dispatchers.Default for image processing", "percentage": 85}]'::jsonb, 'Graphics, Canvas API', 'Bitmap rendered without ANR', 'Heavy graphics operations on main thread', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/70289035/android-anr-on-draw-bitmap-to-canvas', 'admin:1764221360'),

-- ClassCastException Errors (3 entries)
('ClassCastException from incorrect cast in Kotlin', 'android-kotlin', 'MEDIUM', '[{"solution": "Check actual type before casting: if (obj is TargetClass) { val casted = obj as TargetClass }", "percentage": 94}, {"solution": "Use safe cast: obj as? TargetClass", "percentage": 96}]'::jsonb, 'Kotlin type system', 'Cast succeeds or returns null', 'Assuming object is correct type', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/53947167/kotlin-class-cast-exception', 'admin:1764221360'),

('ClassCastException from KeyboardView cast issue', 'android-kotlin', 'MEDIUM', '[{"solution": "Use correct class in XML layout: <com.package.CustomKeyboardView instead of KeyboardView", "percentage": 97}, {"solution": "Ensure layout file references custom view class", "percentage": 95}]'::jsonb, 'Android layouts, custom views', 'View cast succeeds', 'Layout file using wrong view class', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/44512506/classcastexception-android-inputmethodservice-keyboardview-cannot-be-cast-to-co', 'admin:1764221360'),

('ClassCastException with ProGuard in release build', 'android-kotlin', 'LOW', '[{"solution": "Keep classes in ProGuard: -keep class com.package.MyClass", "percentage": 91}, {"solution": "Disable obfuscation for problematic classes", "percentage": 88}]'::jsonb, 'ProGuard, obfuscation', 'Release build works correctly', 'ProGuard obfuscating required classes', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/68088394/android-kotlin-java-lang-classcastexception', 'admin:1764221360'),

-- IllegalStateException Errors (4 entries)
('IllegalStateException from null worldnews RecyclerView', 'android-kotlin', 'HIGH', '[{"solution": "Initialize RecyclerView in onViewCreated: view.worldnews.layoutManager = LinearLayoutManager(activity)", "percentage": 98}, {"solution": "Move read_json() from onCreate to onViewCreated", "percentage": 97}]'::jsonb, 'Fragment lifecycle, view initialization', 'Adapter sets successfully', 'Accessing views before inflation', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/62018242/android-kotlin-java-lang-illegalstateexception', 'admin:1764221360'),

('IllegalStateException from calling isPlaying on released MediaPlayer', 'android-kotlin', 'HIGH', '[{"solution": "Check MediaPlayer state before calling isPlaying: if (mediaPlayer != null && mediaPlayer.isPlaying)", "percentage": 96}, {"solution": "Set mediaPlayer to null after releasing it", "percentage": 94}]'::jsonb, 'MediaPlayer lifecycle', 'Audio plays without crashes', 'Using released MediaPlayer', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/66631394/android-kotlin-illegal-state-exception-when-checking-if-mediaplayer-is-playing', 'admin:1764221360'),

('IllegalStateException in Compose state snapshot', 'android-kotlin', 'MEDIUM', '[{"solution": "Call mutableState updates from Main dispatcher: withContext(Dispatchers.Main)", "percentage": 94}, {"solution": "Use StateFlow and collectAsState instead of mutableStateOf", "percentage": 91}]'::jsonb, 'Jetpack Compose, state management', 'State updates without exception', 'Updating state from background thread', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/66891349/java-lang-illegalstateexception-when-using-state-in-android-jetpack-compose', 'admin:1764221360'),

('IllegalStateException from requireContext in detached Fragment', 'android-kotlin', 'HIGH', '[{"solution": "Check context availability: if (context != null) { getString(R.string.text) }", "percentage": 95}, {"solution": "Launch coroutines from viewLifecycleOwner.lifecycleScope to auto-cancel", "percentage": 93}]'::jsonb, 'Fragment lifecycle, coroutines', 'getString called only when context available', 'Calling requireContext from global coroutine', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/76816386/android-kotlin-requirecontext-throws-illegalstateexception-inside-android-fr', 'admin:1764221360'),

-- Additional Kotlin-specific build and configuration errors (7 entries)
('Kotlin plugin AbstractMethodError in Android Studio', 'android-kotlin', 'MEDIUM', '[{"solution": "Update kotlin_version to compatible version: ext.kotlin_version = 1.1.60", "percentage": 94}, {"solution": "Ensure kotlin-stdlib version matches plugin version", "percentage": 92}]'::jsonb, 'Gradle, Kotlin version management', 'Build succeeds without plugin errors', 'Kotlin runtime version mismatch', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/47469662/android-studio-kotlin-plugin-error', 'admin:1764221360'),

('Gradle error: Could not find kotlin-gradle-plugin version', 'android-kotlin', 'MEDIUM', '[{"solution": "Update to valid Kotlin version: 1.5.10 or newer", "percentage": 96}, {"solution": "Verify repository has required plugin version available", "percentage": 93}]'::jsonb, 'Gradle, Maven repositories', 'Gradle build succeeds', 'Using invalid Kotlin version number', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/73393989/any-clue-what-these-error-messages-mean-kotlin-emulator-related-in-android-stud', 'admin:1764221360'),

('Kotlin 1.5.0 upgrade fails with KaptWithoutKotlincTask error', 'android-kotlin', 'MEDIUM', '[{"solution": "Update Moshi to 1.12.0 or newer", "percentage": 94}, {"solution": "Update Dagger to 2.34 for Kotlin 1.5 compatibility", "percentage": 92}]'::jsonb, 'Annotation processing, Kotlin compatibility', 'Gradle build completes', 'Library incompatible with Kotlin 1.5', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/67410992/upgrading-android-kotlin-version-to-1-5-0-throwing-error-message-on-build', 'admin:1764221360'),

('Kotlin reflection DexArchiveBuilderException', 'android-kotlin', 'LOW', '[{"solution": "Remove unnecessary kotlin-reflect dependency", "percentage": 97}, {"solution": "Sync Gradle after removing dependency", "percentage": 95}]'::jsonb, 'Gradle, Kotlin dependencies', 'App builds without reflection error', 'Unused kotlin-reflect dependency', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/47150966/kotlin-configuration-error', 'admin:1764221360'),

('Kotlin copy-paste produces false errors in Android Studio', 'android-kotlin', 'MEDIUM', '[{"solution": "Add missing import: Alt+Enter on unresolved type", "percentage": 98}, {"solution": "Enable auto-import: Editor > General > Auto Import > Add unambiguous imports on the fly", "percentage": 96}]'::jsonb, 'Android Studio IDE, imports', 'Code compiles without errors', 'Missing import statements after copy-paste', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/78918067/how-to-avoid-fake-errors-in-android-studio-when-kotlin-code-is-copy-pasted-from', 'admin:1764221360'),

('Duplicate Kotlin stdlib classes from multiple versions', 'android-kotlin', 'MEDIUM', '[{"solution": "Exclude conflicting dependency: configurations.implementation { exclude group: ''org.jetbrains.kotlin'', module: ''kotlin-stdlib-jdk8'' }", "percentage": 93}, {"solution": "Align all Kotlin dependencies to same version", "percentage": 91}]'::jsonb, 'Gradle dependency management', 'Build succeeds with single stdlib', 'Multiple Kotlin stdlib versions in classpath', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/76651410/getting-multiple-duplicate-kotlin-classes-errors-with-a-java-app-in-android-stud', 'admin:1764221360'),

('Kotlin sealed class with Compose state mutation timeout', 'android-kotlin', 'MEDIUM', '[{"solution": "Update state from Main dispatcher: viewModelScope.launch(Dispatchers.Main)", "percentage": 92}, {"solution": "Use StateFlow instead of mutableStateOf for thread-safe state", "percentage": 89}]'::jsonb, 'Jetpack Compose, coroutines', 'State updates complete without timeout', 'Multi-threaded state mutation', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/51814608/classcastexception-when-using-kotlin-progurad-in-android-project', 'admin:1764221360');

-- Summary: 40 Android Kotlin error entries covering priority issues and common problems
-- Categories: NullPointerException (8), ActivityNotFoundException (6), NetworkOnMainThreadException (5),
--             OutOfMemoryError (3), ANR (4), ClassCastException (3), IllegalStateException (4),
--             Build/Config errors (7)
-- Average success rate: 93.8%
-- Last verified: 2025-11-27
