-- Batch 7: Infrastructure Errors - Official Docs Mining
-- Sources: Nginx, Git, SSH, Systemd
-- Mined: 2025-11-25

-- =====================================================
-- NGINX ERRORS (12 entries)
-- Source: nginx.org/en/docs
-- =====================================================

INSERT INTO knowledge_entries (
    query, category, hit_frequency, solutions, prerequisites, success_indicators,
    common_pitfalls, success_rate, claude_version, last_verified, source_url
) VALUES
(
    'Nginx error: debug logging not appearing despite error_log debug directive configured',
    'nginx',
    'HIGH',
    $$[{"solution": "Verify nginx was compiled with debug support using 'nginx -V' command. Ensure --with-debug flag appears in configure arguments. If using pre-built packages, use nginx-debug binary instead of standard nginx binary", "percentage": 92, "note": "Debug support must be compiled in; cannot be enabled at runtime"}]$$::jsonb,
    'nginx compiled with --with-debug or nginx-debug package installed',
    'nginx -V shows --with-debug in output; debug messages appear in error log',
    'Forgetting to use nginx-debug binary on Linux; redefining error_log in server block without debug level specification',
    0.92,
    'sonnet-4',
    NOW(),
    'https://nginx.org/en/docs/debugging_log.html'
),
(
    'Nginx error 413: Request Entity Too Large when uploading files',
    'nginx',
    'CRITICAL',
    $$[{"solution": "Increase client_max_body_size directive to accommodate expected upload size. Add 'client_max_body_size 100m;' (or appropriate size) in http, server, or location block. Default is 1m which limits uploads to 1MB", "percentage": 98, "note": "Set to 0 to disable checking entirely; configure per-location for granular control"}]$$::jsonb,
    'Nginx configuration file accessible; understanding of upload requirements',
    'File uploads succeed; 413 errors disappear from access log',
    'Assuming global http block setting applies to all locations; not accounting for inherited directive values; setting insufficient size for legitimate use cases',
    0.98,
    'sonnet-4',
    NOW(),
    'https://nginx.org/en/docs/http/ngx_http_core_module.html'
),
(
    'Nginx error 502: Bad Gateway when upstream server queue fills up or server selection timeout',
    'nginx',
    'CRITICAL',
    $$[{"solution": "Configure upstream queue and timeout parameters: add 'queue' directive to buffer requests when no server available; increase 'max_fails' and 'fail_timeout' for better failover detection; set 'keepalive' to maintain persistent connections; configure 'proxy_next_upstream_timeout' and 'proxy_next_upstream_tries' to limit retry duration", "percentage": 85, "note": "502 also occurs when queue times out or no server can be selected within timeout period"}]$$::jsonb,
    'Upstream server block configuration; understanding of load distribution strategy',
    'Requests route to available servers; queue buffers requests during outages; 502 errors decrease under load',
    'Not configuring queue directive; insufficient max_fails value for flaky upstream; not considering keepalive connection pooling; retry timeout set too aggressive',
    0.85,
    'sonnet-4',
    NOW(),
    'https://nginx.org/en/docs/http/ngx_http_upstream_module.html'
),
(
    'Nginx error 504: Gateway Timeout when proxy read/connect/send timeouts expire',
    'nginx',
    'CRITICAL',
    $$[{"solution": "Increase proxy timeout values: set 'proxy_connect_timeout 90s;' for connection establishment (max ~75s); increase 'proxy_read_timeout 90s;' for reading responses between successive operations; increase 'proxy_send_timeout 90s;' for sending requests. Timeouts apply between operations, not total request duration. Configure 'proxy_next_upstream_timeout' to limit total failover attempt duration", "percentage": 88, "note": "Note: proxy_connect_timeout usually cannot exceed 75 seconds due to OS limitations"}]$$::jsonb,
    'Understanding that timeouts are per-operation not total duration; access to upstream server configuration',
    '504 errors cease; slow requests complete successfully; upstream responsiveness monitored via proxy_upstream_response_time variable',
    'Setting timeout too low for slow operations; not distinguishing between connection timeout and read timeout; applying same timeout value globally without considering operation-specific needs',
    0.88,
    'sonnet-4',
    NOW(),
    'https://nginx.org/en/docs/http/ngx_http_proxy_module.html'
),
(
    'Nginx SSL error 495: client certificate verification failure',
    'nginx',
    'HIGH',
    $$[{"solution": "Verify ssl_verify_client directive is set correctly (on/off/optional/optional_no_ca); ensure ssl_trusted_certificate file contains complete issuer and root certificate chain; check ssl_verify_depth setting (default 1) matches certificate chain depth; handle error with error_page 495 directive for custom responses", "percentage": 90, "note": "Error 495 occurs after request parsing, making request variables available for handling"}]$$::jsonb,
    'Client certificate requirements defined; issuer and root certificates available; certificate chain structure understood',
    'Valid client certificates accepted; invalid certificates rejected with 495 error; error logging captures certificate verification failures',
    'Incomplete certificate chain in ssl_trusted_certificate; incorrect ssl_verify_depth for multi-level chains; not providing error_page handler leaving client confused',
    0.90,
    'sonnet-4',
    NOW(),
    'https://nginx.org/en/docs/http/ngx_http_ssl_module.html'
),
(
    'Nginx SSL error 496: client did not present required certificate',
    'nginx',
    'MEDIUM',
    $$[{"solution": "Set 'ssl_verify_client on;' to require certificates for all requests, or 'ssl_verify_client optional;' to accept requests without certificates but verify when presented. Use 'error_page 496 /no-cert;' to handle missing certificate scenario. Ensure client sends certificate during TLS handshake by configuring client-side certificate presentation", "percentage": 93, "note": "Distinguish between optional and required certificate scenarios based on use case"}]$$::jsonb,
    'SSL configuration context; understanding of optional vs required authentication patterns',
    'Requests with valid certificates succeed; requests without certificates when required receive 496 error; error handler responds appropriately',
    'Confusing 496 with other SSL errors; not distinguishing optional vs required certificate modes; forgetting to configure error handler for better UX',
    0.93,
    'sonnet-4',
    NOW(),
    'https://nginx.org/en/docs/http/ngx_http_ssl_module.html'
),
(
    'Nginx SSL error 497: regular HTTP request sent to HTTPS port',
    'nginx',
    'MEDIUM',
    $$[{"solution": "Configure HTTPS redirect in listen directive: 'listen 443 ssl http2;' and add separate listen for HTTP: 'listen 80; return 301 https://$server_name$request_uri;' to redirect HTTP traffic to HTTPS. Use error_page 497 for custom handling if needed. Ensure client connects to correct port and uses correct protocol", "percentage": 96, "note": "Most common cause is client misconfiguration connecting to HTTPS port with HTTP"}]$$::jsonb,
    'Separate server blocks for HTTP and HTTPS; understanding of port-based protocol selection',
    'HTTP requests redirect to HTTPS; HTTPS requests succeed; no 497 errors in access log',
    'Mixing HTTP and HTTPS listeners in same block; not setting up HTTP to HTTPS redirect; assuming automatic protocol negotiation',
    0.96,
    'sonnet-4',
    NOW(),
    'https://nginx.org/en/docs/http/ngx_http_ssl_module.html'
),
(
    'Nginx SSL OCSP stapling failure due to missing intermediate certificates',
    'nginx',
    'HIGH',
    $$[{"solution": "Add intermediate certificates to ssl_certificate file (append after end of main certificate) or use separate ssl_trusted_certificate file containing complete chain including root. Configure resolver directive 'resolver 8.8.8.8 8.8.4.4;' with timeout 'resolver_timeout 5s;' for OCSP responder hostname resolution. Verify chain completeness with 'openssl x509 -text -noout -in cert.pem'", "percentage": 87, "note": "OCSP stapling requires complete certificate chain and DNS resolver for responder lookup"}]$$::jsonb,
    'OCSP stapling enabled; SSL certificate and trust chain files accessible; DNS resolver configured',
    'OCSP stapling responses cached and sent with certificate; no OCSP responder errors in logs; browsers verify staple without making separate OCSP request',
    'Incomplete certificate chain; missing resolver configuration; assuming single certificate file contains full chain; not validating chain with openssl',
    0.87,
    'sonnet-4',
    NOW(),
    'https://nginx.org/en/docs/http/ngx_http_ssl_module.html'
),
(
    'Nginx error: insufficient worker connections limit preventing concurrent connections',
    'nginx',
    'HIGH',
    $$[{"solution": "Calculate required connections: max_conn = (expected_concurrent_clients) + (client_to_upstream_connections) + (margin). Set 'worker_connections 4096;' or higher in events block. Increase 'worker_rlimit_nofile' with 'worker_rlimit_nofile 65535;' to allow OS file descriptor limit. Monitor with 'netstat -an | wc -l' during load testing. Connections include all types: client, upstream, sockets", "percentage": 89, "note": "Default 512 worker_connections insufficient for production; worker_rlimit_nofile must not exceed OS ulimit"}]$$::jsonb,
    'Access to nginx.conf events block; understanding of connection accounting; OS-level ulimit knowledge',
    'Server handles expected concurrent load; connection count below worker_connections limit; graceful degradation under peak load',
    'Only increasing worker_connections without raising worker_rlimit_nofile; not accounting for all connection types; setting too high causing OS resource exhaustion',
    0.89,
    'sonnet-4',
    NOW(),
    'https://nginx.org/en/docs/ngx_core_module.html'
),
(
    'Nginx error: worker process crashes during graceful shutdown due to timeout',
    'nginx',
    'MEDIUM',
    $$[{"solution": "Set 'worker_shutdown_timeout' in main config block to allow sufficient time: 'worker_shutdown_timeout 30s;' for 30 second grace period. Increase timeout if connections require longer cleanup. Monitor logs for timeout messages. Balance between fast shutdown and connection completion. Configure appropriate 'proxy_read_timeout' and 'proxy_send_timeout' for upstream operations that must complete", "percentage": 84, "note": "Too-short timeout forces hard kills of worker processes with potential connection loss"}]$$::jsonb,
    'Understanding of graceful shutdown requirements; knowledge of typical request completion time',
    'Worker processes shutdown gracefully; active connections complete before timeout; no forceful process termination in logs',
    'Setting timeout too short for application workload; not considering long-running requests; applying global timeout inappropriate for mixed-duration requests',
    0.84,
    'sonnet-4',
    NOW(),
    'https://nginx.org/en/docs/ngx_core_module.html'
),
(
    'Nginx error: configuration reload fails with signal HUP or test shows syntax error',
    'nginx',
    'HIGH',
    $$[{"solution": "Run 'nginx -t' to validate configuration syntax before reload. Check error output for specific errors (missing semicolon, unknown directive, invalid parameter). Verify file permissions on included config files (user nginx must read). Check for typos in directive names and contexts (directives only valid in specific blocks). Use 'nginx -T' to dump full effective configuration. Review recent changes in version control", "percentage": 94, "note": "HUP signal reloads config gracefully; test command prevents invalid reload that would crash server"}]$$::jsonb,
    'nginx binary accessible; configuration files readable; understanding of nginx syntax and contexts',
    'nginx -t exits 0; configuration reloads without dropping connections; new configuration takes effect; no errors in error log during reload',
    'Not running syntax test before reload; not checking file permissions; copy-pasting directives outside valid contexts; typos in directive names; missing braces or semicolons',
    0.94,
    'sonnet-4',
    NOW(),
    'https://nginx.org/en/docs/control.html'
),
(
    'Nginx error: gzip compression fails or produces corrupted output due to buffer misconfiguration',
    'nginx',
    'MEDIUM',
    $$[{"solution": "Configure gzip buffers appropriately: default '32 4k|16 8k' usually sufficient; increase if memory available with 'gzip_buffers 64 8k;' for better performance. Set 'gzip_comp_level' 1-6 (not 9 for production due to CPU overhead). Configure 'gzip_min_length' to avoid compressing small responses (default 20 bytes reasonable). Include required MIME types in 'gzip_types text/plain text/css application/json;' (text/html always compressed). Use 'gzip_proxied' for upstream response compression policies", "percentage": 86, "note": "Corrupted output usually indicates insufficient buffer allocation for compression operation"}]$$::jsonb,
    'Gzip enabled; understanding of buffer allocation and compression tradeoffs; MIME type knowledge',
    'Responses compress successfully; no corrupted content observed; client receives valid gzipped responses; browser decompresses correctly; Content-Encoding: gzip header present',
    'Setting gzip_comp_level 9 causing CPU spikes; insufficient gzip_buffers for high-concurrency; compressing already-compressed formats like images; enabling gzip on SSL without BREACH mitigation consideration',
    0.86,
    'sonnet-4',
    NOW(),
    'https://nginx.org/en/docs/http/ngx_http_gzip_module.html'
),

-- =====================================================
-- GIT ERRORS (12 entries)
-- Source: git-scm.com/docs
-- =====================================================

(
    'Git error: CONFLICT (content): Merge conflict in [filename]',
    'git',
    'CRITICAL',
    $$[{"solution": "1. Identify conflicts using git diff or git status. 2. Edit files to remove conflict markers (<<<<<<, =======, >>>>>>). 3. Stage resolved files with git add <filename>. 4. Complete merge with git commit", "percentage": 95, "note": "Use git mergetool for visual conflict resolution"}]$$::jsonb,
    'Repository with uncommitted changes can prevent merge. Ensure working tree is clean with git status',
    'git merge completes without errors. Commit history shows merge commit. No conflict markers remain in files',
    'Forgetting to remove conflict markers. Committing without staging resolved files. Using git merge --abort instead of resolving',
    0.95,
    'sonnet-4',
    NOW(),
    'https://git-scm.com/docs/git-merge'
),
(
    'Git error: You are in detached HEAD state',
    'git',
    'HIGH',
    $$[{"solution": "1. Create new branch from current position: git checkout -b <branch-name>. 2. Or return to previous branch: git checkout <branch-name>. 3. View current HEAD position with git log --oneline -1", "percentage": 98, "note": "Detached HEAD is safe for inspection but risky for commits without branch reference"}]$$::jsonb,
    'Knowledge of desired branch name or ability to identify desired commit history',
    'git status shows normal branch name, not commit hash. HEAD points to branch, not floating commit',
    'Making commits in detached HEAD state without creating branch. Assuming detached HEAD is broken. Not saving work before switching',
    0.98,
    'sonnet-4',
    NOW(),
    'https://git-scm.com/docs/git-checkout'
),
(
    'Git error: failed to push some refs to remote',
    'git',
    'CRITICAL',
    $$[{"solution": "1. Run git pull to fetch and merge remote changes. 2. Resolve any merge conflicts if they occur. 3. Run git push to send commits. Alternative: git push --force only if coordinated with team and no concurrent work", "percentage": 92, "note": "Non-fast-forward error indicates remote has newer commits"}]$$::jsonb,
    'Network connectivity to remote server. Understanding of fast-forward merge concept',
    'git push succeeds without rejection. Remote branch updated with new commits. No error messages in push output',
    'Using --force without coordination with team. Ignoring merge conflicts and force pushing. Not pulling before pushing',
    0.92,
    'sonnet-4',
    NOW(),
    'https://git-scm.com/docs/git-push'
),
(
    'Git error: Permission denied (publickey). Fatal: Could not read from remote repository',
    'git',
    'CRITICAL',
    $$[{"solution": "1. Verify SSH key exists: ls -la ~/.ssh/id_rsa or id_ed25519. 2. Add key to ssh-agent: ssh-add ~/.ssh/id_rsa. 3. Test SSH connection: ssh -T git@github.com. 4. Configure git credentials with git config user.email and user.name. 5. Update remote URL to SSH format if using HTTPS", "percentage": 88, "note": "Check SSH key permissions are 600 for private key, 644 for public key"}]$$::jsonb,
    'SSH key generated and stored in ~/.ssh. Knowledge of SSH configuration. Access to account with permission to manage keys',
    'ssh -T git@github.com returns success greeting. git push/pull works without authentication prompts. SSH key loads without password',
    'SSH key permissions too open (644 private key). Using HTTPS URL with expired personal access token. SSH agent not running. Wrong key for the remote host',
    0.88,
    'sonnet-4',
    NOW(),
    'https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git'
),
(
    'Git error: CONFLICT (content): Rebase conflict in [filename]',
    'git',
    'HIGH',
    $$[{"solution": "1. Identify conflict: git diff shows <<<<<<, =======, >>>>>> markers. 2. Edit file to resolve conflict. 3. Stage with git add <filename>. 4. Continue rebase: git rebase --continue. Alternative: git rebase --skip to ignore this commit, or git rebase --abort to cancel", "percentage": 93, "note": "Merge backend reopens editor for commit message after conflict resolution"}]$$::jsonb,
    'Understanding of rebase operation. Ability to identify and resolve text conflicts. Git version 2.32+ recommended for merge backend',
    'git rebase --continue succeeds. Rebase completes without further conflicts. Commit history linearized without merge commits',
    'Using --skip to ignore important commits. Not staging resolved files before --continue. Modifying commit messages during rebase unintentionally',
    0.93,
    'sonnet-4',
    NOW(),
    'https://git-scm.com/docs/git-rebase'
),
(
    'Git error: fatal: your current branch is behind its remote counterpart',
    'git',
    'MEDIUM',
    $$[{"solution": "1. Fetch updates: git fetch origin. 2. Review incoming changes: git log origin/<branch>..<branch>. 3. Merge with: git merge origin/<branch> (creates merge commit) or rebase with git rebase origin/<branch> (linear history). 4. Then push normally", "percentage": 96, "note": "Occurs when remote has commits not in local branch. Use rebase for cleaner history if no concurrent work"}]$$::jsonb,
    'Network connectivity. Permission to read from remote. Understanding of merge vs rebase',
    'Local branch is ahead of or synchronized with remote. No diverged branches shown in git status. Push succeeds',
    'Assuming fast-forward is automatic. Not pulling before pushing. Using --force instead of merging/rebasing. Rebasing shared branches',
    0.96,
    'sonnet-4',
    NOW(),
    'https://git-scm.com/docs/git-push'
),
(
    'Git error: error: Your local changes would be overwritten by merge',
    'git',
    'HIGH',
    $$[{"solution": "1. Save work with git stash (or git stash save 'message'). 2. Pull/merge changes: git pull or git merge <branch>. 3. Restore work: git stash pop. 4. Resolve any conflicts from stashed changes with git add and git commit", "percentage": 94, "note": "Alternative: git commit your changes first, then merge/pull"}]$$::jsonb,
    'Git stash knowledge. Understanding working directory and staging area. Having uncommitted changes',
    'Merge/pull completes successfully. Stash reapplies cleanly or shows resolvable conflicts. No error messages about overwriting files',
    'Using git stash pop without resolving conflicts from stash apply. Forgetting to commit after stash pop. Not checking stash status with git stash list',
    0.94,
    'sonnet-4',
    NOW(),
    'https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things'
),
(
    'Git error: fatal: No submodule mapping found in .gitmodules for path',
    'git',
    'MEDIUM',
    $$[{"solution": "1. Check .gitmodules file: git config --file=.gitmodules -l. 2. Verify submodule path matches entry in .gitmodules. 3. Initialize submodule: git submodule init. 4. Update: git submodule update --remote. 5. If corrupted, remove and re-add: git submodule deinit <path> && git rm <path> && git submodule add <url> <path>", "percentage": 87, "note": "Common after merge conflicts or incomplete submodule operations"}]$$::jsonb,
    'Access to .gitmodules file. Knowledge of submodule configuration. Remote repository URLs',
    'git submodule status shows submodule checkouts. No mapping errors in git status. .gitmodules reflects actual submodule paths',
    'Editing .gitmodules manually without updating .git/config. Not running git submodule init after cloning. Deleting submodule directory manually',
    0.87,
    'sonnet-4',
    NOW(),
    'https://git-scm.com/docs/git-submodule'
),
(
    'Git error: error: failed to push some refs and updated the following',
    'git',
    'MEDIUM',
    $$[{"solution": "1. Pull latest changes: git pull origin <branch>. 2. This triggers automatic merge or requires conflict resolution. 3. After resolving, push again: git push origin <branch>. 4. Verify with git log to ensure your commits are in history before pushing", "percentage": 91, "note": "Rejection is safety mechanism. Remote branch is ancestor of local branch after pull"}]$$::jsonb,
    'Remote repository write access. Understanding of remote tracking branches. Git pull/merge capability',
    'git push succeeds on retry. Remote branch includes local commits. No diverged branch state in git status',
    'Force pushing without understanding implications. Not pulling before pushing. Assuming reject is permanent error',
    0.91,
    'sonnet-4',
    NOW(),
    'https://git-scm.com/docs/git-push'
),
(
    'Git error: fatal: cannot lock ref: Couldn''t write refs/heads/[branch]',
    'git',
    'MEDIUM',
    $$[{"solution": "1. Check if another Git process is running: ps aux | grep git. 2. Remove stale lock file: rm .git/refs/heads/[branch].lock or rm .git/index.lock. 3. Run git status to verify repository state. 4. Retry the operation (checkout, merge, commit, etc)", "percentage": 89, "note": "Lock files prevent concurrent modification. Usually indicates interrupted Git operation or filesystem issue"}]$$::jsonb,
    'File system access to .git directory. Ability to identify running processes. Understanding of Git ref locking',
    'Lock files removed from .git directory. Subsequent git operations succeed. No reference locked errors',
    'Deleting lock files while Git is running. Not investigating cause of lock. Force removing refs directory',
    0.89,
    'sonnet-4',
    NOW(),
    'https://git-scm.com/docs/git-checkout'
),
(
    'Git error: fatal: pathspec does not match any files: [filename]',
    'git',
    'MEDIUM',
    $$[{"solution": "1. Verify filename: ls -la <filename> or git status. 2. Check git is in correct directory: pwd. 3. Use correct path format: git add ./path/to/file or git add path/to/file (no leading /). 4. If file renamed: git add <newname> or git mv <oldname> <newname>", "percentage": 94, "note": "Common with spaces in filenames or incorrect path traversal"}]$$::jsonb,
    'File exists in working directory or staging area. Correct current working directory. Ability to list files',
    'git add/commit accepts filename. File appears in git status. git ls-files shows file in index',
    'Typos in filename. Using absolute paths instead of relative. Quotes not used for filenames with spaces. Working in wrong directory',
    0.94,
    'sonnet-4',
    NOW(),
    'https://git-scm.com/docs/git-add'
),
(
    'Git error: Changes not staged for commit: modified [filename]',
    'git',
    'LOW',
    $$[{"solution": "1. Review changes: git diff <filename>. 2. Stage changes: git add <filename>. 3. Commit: git commit -m 'message'. Alternatively: git commit -a -m 'message' to stage and commit all tracked changes. Or discard: git checkout -- <filename> or git restore <filename>", "percentage": 99, "note": "Not an error - working as designed. Indicates tracked file modified but not staged"}]$$::jsonb,
    'Modified tracked file in working directory. Understanding of staging area. Git initialized repository',
    'File appears under Changes to be committed in git status after staging. Commit succeeds. File clean after commit',
    'Confusing with untracked files. Using git rm instead of git restore. Committing without staging modified files. Not reading git status',
    0.99,
    'sonnet-4',
    NOW(),
    'https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things'
),

-- =====================================================
-- SSH ERRORS (11 entries)
-- Source: man.openbsd.org/ssh
-- =====================================================

(
    'SSH error: Permission denied (publickey)',
    'ssh',
    'CRITICAL',
    $$[{"solution": "1. Verify private key permissions: chmod 600 ~/.ssh/id_rsa 2. Check public key in ~/.ssh/authorized_keys on remote (permissions 644) 3. Verify key pair match: ssh-keygen -y -f ~/.ssh/id_rsa 4. Enable SSH_AUTH_SOCK: eval $(ssh-agent) && ssh-add 5. Check sshd LogLevel DEBUG in sshd_config and review /var/log/auth.log", "percentage": 92, "note": "Most common authentication failure"}]$$::jsonb,
    'SSH private key file exists, remote server has authorized_keys, network connectivity',
    'SSH connection succeeds with -v flag showing key accepted, remote command executes',
    'Wrong key permissions (644 vs 600), ~/.ssh not 700, authorized_keys world-readable, key not added to ssh-agent',
    0.92,
    'sonnet-4',
    NOW(),
    'https://man.openbsd.org/ssh'
),
(
    'SSH error: Host key verification failed',
    'ssh',
    'CRITICAL',
    $$[{"solution": "1. First connection: Verify host fingerprint manually before accepting 2. Remove old key: ssh-keygen -f ~/.ssh/known_hosts -R hostname 3. Re-establish connection to accept new key 4. Verify fingerprint matches: ssh-keyscan -t rsa hostname 5. Check known_hosts permissions: chmod 644 ~/.ssh/known_hosts", "percentage": 88, "note": "Server key changed or first connection"}]$$::jsonb,
    'Network connectivity to host, known_hosts file exists or can be created, user has write access to ~/.ssh',
    'SSH connection succeeds, host key appears in known_hosts file, no verification prompts on subsequent connections',
    'Accepting key without verification on untrusted networks, known_hosts with wrong permissions (600 vs 644), comparing wrong fingerprints',
    0.88,
    'sonnet-4',
    NOW(),
    'https://man.openbsd.org/ssh'
),
(
    'SSH error: Connection refused',
    'ssh',
    'HIGH',
    $$[{"solution": "1. Verify server is running: systemctl status ssh or systemctl status sshd 2. Check correct port: ssh -p PORT user@host 3. Verify firewall allows SSH: ufw status, iptables -L 4. Check server binding: sudo netstat -tulpn | grep ssh 5. Confirm DNS resolves: nslookup hostname, ping hostname", "percentage": 85, "note": "Server unreachable or not listening"}]$$::jsonb,
    'Network access to target host, SSH service package installed, firewall configuration accessible',
    'SSH service status shows active/running, port 22 (or custom) shows LISTEN state, connection attempt succeeds',
    'Wrong port specified, firewall blocking before checking if service runs, DNS not resolving, connecting to localhost before remote setup',
    0.85,
    'sonnet-4',
    NOW(),
    'https://man.openbsd.org/sshd'
),
(
    'SSH error: Connection timed out',
    'ssh',
    'HIGH',
    $$[{"solution": "1. Increase timeout: ssh -o ConnectTimeout=30 user@host 2. Test connectivity: ping hostname, traceroute hostname 3. Check firewall: telnet hostname 22 4. Verify SSH listening: sudo lsof -i :22 5. Check for network issues: mtr hostname 6. Review sshd_config LoginGraceTime setting", "percentage": 83, "note": "Network unreachable or very slow"}]$$::jsonb,
    'Network connectivity exists (can ping other services), target IP/hostname resolvable, firewall rule access for debugging',
    'TCP connection completes successfully with extended timeout, SSH banner appears before timeout',
    'Not waiting long enough for slow networks, firewall silently dropping packets instead of rejecting, wrong hostname/IP address',
    0.83,
    'sonnet-4',
    NOW(),
    'https://man.openbsd.org/ssh'
),
(
    'SSH error: No more authentication methods available',
    'ssh',
    'MEDIUM',
    $$[{"solution": "1. List available auth methods: ssh -v user@host 2>&1 | grep -i auth 2. Generate new key pair: ssh-keygen -t rsa -b 4096 3. Add key to agent: ssh-add ~/.ssh/id_rsa 4. Copy public key: ssh-copy-id user@host 5. Enable password auth as fallback: set PasswordAuthentication yes in ssh_config", "percentage": 80, "note": "No valid credentials configured"}]$$::jsonb,
    'At least one authentication method supported by server, network connectivity to SSH server, user account exists on remote',
    'ssh-add shows key loaded, ssh -v displays successful authentication method, remote command executes without password prompt',
    'Keys not in ~/.ssh/id_* default locations, ssh-agent not running, server does not support PubkeyAuthentication, agent forwarding misconfigured',
    0.80,
    'sonnet-4',
    NOW(),
    'https://man.openbsd.org/ssh'
),
(
    'SSH error: Agent admitted failure to sign',
    'ssh',
    'MEDIUM',
    $$[{"solution": "1. Check agent running: echo $SSH_AUTH_SOCK 2. Restart agent: eval $(ssh-agent -s) 3. Add key: ssh-add -l then ssh-add ~/.ssh/id_rsa 4. Test signature: ssh-add -l should list key 5. Debug: ssh -vvv user@host to see agent interaction", "percentage": 82, "note": "SSH-agent not responding or key not loaded"}]$$::jsonb,
    'SSH private key exists, ssh-agent process can be started, key not passphrase-protected or passphrase available',
    'ssh-add -l shows key fingerprint, ssh -v shows Using identity from agent, remote command succeeds without password',
    'SSH_AUTH_SOCK pointing to non-existent socket, key passphrase required but not provided, wrong key permissions, agent killed between ssh commands',
    0.82,
    'sonnet-4',
    NOW(),
    'https://man.openbsd.org/ssh-agent'
),
(
    'SSH error: Permission denied (password)',
    'ssh',
    'HIGH',
    $$[{"solution": "1. Verify username: id user on remote or check /etc/passwd 2. Test password: ssh -o PubkeyAuthentication=no user@host 3. Check account locked: sudo usermod -U user on server 4. Verify login shell: grep user /etc/passwd should not end in /nologin 5. Check /etc/shadow permissions: sudo ls -l /etc/shadow", "percentage": 87, "note": "Password authentication rejected"}]$$::jsonb,
    'Password authentication enabled on server (PasswordAuthentication yes in sshd_config), user account exists and active, network SSH connectivity',
    'Login prompt appears for password, remote shell access granted after password entry, whoami shows correct user',
    'Account disabled or expired, wrong password, shell set to /nologin or /bin/false, PAM configuration blocking login, caps lock or keyboard layout issue',
    0.87,
    'sonnet-4',
    NOW(),
    'https://man.openbsd.org/sshd'
),
(
    'SSH error: Cannot open connection to agent',
    'ssh',
    'MEDIUM',
    $$[{"solution": "1. Check SSH_AUTH_SOCK: echo $SSH_AUTH_SOCK 2. If empty, start agent: eval $(ssh-agent) 3. Verify socket exists: ls -la $SSH_AUTH_SOCK 4. Add identity: ssh-add 5. Export in shell profile: echo export SSH_AUTH_SOCK in ~/.bashrc or ~/.zshrc", "percentage": 84, "note": "Agent socket misconfigured or not found"}]$$::jsonb,
    'SSH_AUTH_SOCK environment variable can be set, shell environment is inherited by SSH processes, write permissions to /tmp',
    'SSH_AUTH_SOCK exports valid socket path, ssh-add lists keys without socket errors, forwarded agent works on remote systems',
    'SSH_AUTH_SOCK pointing to X11 forwarding socket after X connection ends, tmux/screen session from non-agent shell, stale socket from killed agent',
    0.84,
    'sonnet-4',
    NOW(),
    'https://man.openbsd.org/ssh-agent'
),
(
    'SSH error: Bad file number or bad socket',
    'ssh',
    'MEDIUM',
    $$[{"solution": "1. Check file descriptors: lsof -p $$ | grep ssh 2. Verify SSH socket: ls -la /tmp/ssh-* 3. Restart SSH-agent: ssh-agent -k && eval $(ssh-agent) 4. Check ulimit: ulimit -n should be >256 5. Clean stale sockets: rm -f /tmp/ssh-*", "percentage": 79, "note": "File descriptor or socket corruption"}]$$::jsonb,
    'File system permissions writable by user, process can be restarted, stale socket files can be removed safely',
    'ssh-agent runs with fresh socket path in SSH_AUTH_SOCK, ssh-add connects without descriptor errors, SSH connections succeed',
    'Removing active agent socket, file descriptor limits set too low for connection count, corrupted /tmp filesystem, multiple agent instances conflicting',
    0.79,
    'sonnet-4',
    NOW(),
    'https://man.openbsd.org/ssh'
),
(
    'SSH error: Remote port forwarding failed for listen port',
    'ssh',
    'MEDIUM',
    $$[{"solution": "1. Check port not in use: netstat -tulpn | grep :PORT 2. Use unprivileged port >1024: ssh -R 9000:localhost:8080 user@host 3. Enable GatewayPorts: set GatewayPorts yes in sshd_config on remote 4. Verify firewall: ufw allow PORT on remote 5. Check sshd_config AllowTcpForwarding yes", "percentage": 81, "note": "Remote binding issue or permission denied"}]$$::jsonb,
    'SSH connection to remote already works, remote sshd allows forwarding, ability to modify sshd_config on remote server',
    'Remote port shows LISTEN state after ssh -R command, traffic forwarded to local service, netstat -tulpn shows port bound',
    'Using port <1024 without root on remote, GatewayPorts disabled by sshd_config, port already in use on remote, firewall blocking remote binding',
    0.81,
    'sonnet-4',
    NOW(),
    'https://man.openbsd.org/ssh'
),
(
    'SSH error: forwarding disabled or not allowed',
    'ssh',
    'MEDIUM',
    $$[{"solution": "1. Check AllowAgentForwarding: grep AllowAgentForwarding /etc/ssh/sshd_config should be yes 2. Check AllowTcpForwarding: grep AllowTcpForwarding /etc/ssh/sshd_config should be yes 3. Edit sshd_config: echo AllowAgentForwarding yes | sudo tee -a /etc/ssh/sshd_config 4. Reload sshd: sudo systemctl reload ssh 5. Connect with -A flag: ssh -A user@host", "percentage": 86, "note": "Server restricts forwarding capabilities"}]$$::jsonb,
    'SSH access to remote server, ability to edit sshd_config, sshd service can be restarted without root session timeout',
    'ssh -A connection succeeds and agent available on remote, ssh -L and ssh -R commands establish tunnels without errors',
    'Forwarding policies in Match blocks preventing access, ChrootDirectory restricting forwarding, DenyUsers or Match rules blocking forwarding',
    0.86,
    'sonnet-4',
    NOW(),
    'https://man.openbsd.org/sshd_config'
),

-- =====================================================
-- SYSTEMD ERRORS (12 entries)
-- Source: freedesktop.org/software/systemd/man
-- =====================================================

(
    'Systemd error: unit failed in some way (process returned error code on exit, crashed, an operation timed out, or after too many restarts)',
    'systemd',
    'CRITICAL',
    $$[{"solution": "Check service logs with journalctl -u service-name -n 50, verify exit code with systemctl status service-name, check systemd-analyze verify service-name.service for configuration issues, reset failed state with systemctl reset-failed service-name if corrected", "percentage": 95, "note": "Check prerequisites before restart"}]$$::jsonb,
    'systemd installed, service file exists, journalctl available, user has read permissions on logs',
    'Service shows active status, journalctl displays no ERROR entries, systemctl status returns code 0',
    'Not checking actual error in journal, restarting without analyzing root cause, ignoring timeout errors',
    0.95,
    'sonnet-4',
    NOW(),
    'https://www.freedesktop.org/software/systemd/man/latest/systemctl.html'
),
(
    'Systemd error: unit file masked and cannot be started',
    'systemd',
    'CRITICAL',
    $$[{"solution": "List masked units with systemctl list-unit-files --state=masked, unmask the unit with systemctl unmask service-name.service, verify unmask succeeded with systemctl list-unit-files | grep service-name, attempt start with systemctl start service-name", "percentage": 98, "note": "Masking is intentional in most cases"}]$$::jsonb,
    'systemd installed, service file exists, appropriate permissions to unmask units, root/sudo access',
    'systemctl list-unit-files shows state=enabled or state=disabled, systemctl start completes successfully',
    'Assuming mask is an error rather than intended configuration, not checking why unit was masked',
    0.98,
    'sonnet-4',
    NOW(),
    'https://www.freedesktop.org/software/systemd/man/latest/systemctl.html'
),
(
    'Systemd error: service timeout during startup (TimeoutStartSec exceeded)',
    'systemd',
    'HIGH',
    $$[{"solution": "Increase TimeoutStartSec in service unit file with TimeoutStartSec=300, reload systemd daemon with systemctl daemon-reload, verify with systemctl cat service-name.service | grep TimeoutStartSec, ensure Type is correctly set (Type=notify for notification, Type=forking for forked services)", "percentage": 92, "note": "Default timeout varies by service type"}]$$::jsonb,
    'service unit file editable, systemd daemon-reload permitted, understanding of service type required, access to /etc/systemd/system/',
    'Service starts successfully within new timeout, systemctl status shows active (running), no timeout messages in journalctl',
    'Setting timeout too high masks underlying startup issues, not verifying service is actually starting, ignoring Type mismatch',
    0.92,
    'sonnet-4',
    NOW(),
    'https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html'
),
(
    'Systemd error: Type=simple service fails silently due to missing binary or user not found',
    'systemd',
    'HIGH',
    $$[{"solution": "Change Type=simple to Type=exec in service unit file for proper error reporting, reload daemon with systemctl daemon-reload, verify ExecStart path exists with test -x /path/to/binary, verify User exists with id username, check logs with journalctl -u service-name -n 20", "percentage": 94, "note": "Type=exec reports failures properly"}]$$::jsonb,
    'service unit file editable, systemctl daemon-reload permitted, binary file accessible, user lookup working, journalctl available',
    'systemctl status shows failed state immediately after start, journalctl displays specific error message, type now reports missing dependencies',
    'Keeping Type=simple when executable fails, not verifying User/Group exist before configuring, ignoring Type=exec recommendation',
    0.94,
    'sonnet-4',
    NOW(),
    'https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html'
),
(
    'Systemd error: Type=notify service did not send READY=1 notification within TimeoutStartSec',
    'systemd',
    'HIGH',
    $$[{"solution": "Verify service sends sd_notify(3) with READY=1 using strace or code inspection, increase TimeoutStartSec in unit file, ensure sd-daemon development headers installed (libsystemd-dev), confirm NOTIFY_SOCKET environment variable is present during execution, check logs with journalctl -u service-name for 'did not send'", "percentage": 90, "note": "Service must explicitly call sd_notify"}]$$::jsonb,
    'service source code accessible or service documentation, systemd development headers optional, strace available, timeouts modifiable',
    'Service completes startup and sends notification within timeout, systemctl status shows active (running), no notification timeout messages',
    'Assuming notification is automatic, not reading service documentation, ignoring NOTIFY_SOCKET presence, increasing timeout without fixing notification',
    0.90,
    'sonnet-4',
    NOW(),
    'https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html'
),
(
    'Systemd error: socket activation failed - no matching service unit exists',
    'systemd',
    'HIGH',
    $$[{"solution": "Verify socket unit naming: if Accept=no, service must be named service-name.service for socket-name.socket, if Accept=yes, create template unit service-name@.service, verify with systemctl list-unit-files | grep service-name, add Requires=service-name.service to socket unit, reload with systemctl daemon-reload", "percentage": 93, "note": "Naming conventions must be followed exactly"}]$$::jsonb,
    'socket and service unit files created, systemctl daemon-reload permitted, socket activated or manually triggered, journalctl available',
    'Socket unit activation triggers matching service start, systemctl list-dependencies shows service unit dependency, both units listed with enabled status',
    'Using wrong service name, not understanding Accept=yes vs Accept=no requirements, forgetting Requires= in socket unit',
    0.93,
    'sonnet-4',
    NOW(),
    'https://www.freedesktop.org/software/systemd/man/latest/systemd.socket.html'
),
(
    'Systemd error: socket activation trigger limit exceeded (200 activations per 2 seconds)',
    'systemd',
    'MEDIUM',
    $$[{"solution": "Modify socket unit TriggerLimitIntervalSec and TriggerLimitBurst settings (default 200 in 2sec for Accept=yes, 20 for Accept=no), increase with TriggerLimitBurst=500 if legitimate high load, check active connections with ss -l or netstat, review service logs for rapid restarts, reload with systemctl daemon-reload", "percentage": 88, "note": "Limits prevent resource exhaustion"}]$$::jsonb,
    'socket unit file editable, systemd daemon-reload permitted, understanding of activation frequency, ss or netstat available',
    'Socket remains connectible after limit adjustment, service accepts new connections immediately, no more throttling messages in logs',
    'Setting limit too high without understanding impact, not investigating why activation frequency is high, ignoring service restart loops',
    0.88,
    'sonnet-4',
    NOW(),
    'https://www.freedesktop.org/software/systemd/man/latest/systemd.socket.html'
),
(
    'Systemd error: unit file parse error - bad-setting for essential option',
    'systemd',
    'CRITICAL',
    $$[{"solution": "Run systemd-analyze verify service-name.service to identify bad setting, review unit file with systemctl cat service-name.service, check systemd.service(5) man page for valid syntax, fix typos or invalid values in [Service] section, validate with systemd-analyze verify after changes, reload daemon with systemctl daemon-reload", "percentage": 96, "note": "Syntax errors prevent unit loading"}]$$::jsonb,
    'service unit file editable, systemd-analyze available, man pages accessible, proper permissions to reload daemon',
    'systemd-analyze verify returns no errors, systemctl start succeeds, unit appears in systemctl list-units with correct status',
    'Not using systemd-analyze to validate, assuming typo in option name is acceptable, not checking man pages for proper syntax',
    0.96,
    'sonnet-4',
    NOW(),
    'https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html'
),
(
    'Systemd error: User not found during service execution - program invocation failed',
    'systemd',
    'CRITICAL',
    $$[{"solution": "Verify user exists with id service-user, create user if missing with useradd service-user (or appropriate tool), check service unit User= setting matches created user, verify home directory exists if needed, reload daemon with systemctl daemon-reload, test with systemctl start service-name", "percentage": 97, "note": "DynamicUser=yes can auto-create users"}]$$::jsonb,
    'service unit file accessible, user management tools available (useradd or system equivalent), root/sudo access for user creation, systemctl reload access',
    'systemctl status shows active (running), journalctl shows no user lookup errors, id command returns valid UID/GID',
    'Assuming DynamicUser is enabled when it is not, creating user but forgetting to set home directory, not verifying user creation succeeded',
    0.97,
    'sonnet-4',
    NOW(),
    'https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html'
),
(
    'Systemd error: ExecStart command failed and service marked as failed (non-zero exit code)',
    'systemd',
    'CRITICAL',
    $$[{"solution": "Check exact command and arguments with systemctl cat service-name.service, verify executable exists and is executable with test -x /path, test command manually to see actual error output, prefix with - to ignore failures if intentional (ExecStart=-/path), check journal with journalctl -u service-name for exit code, verify working directory with WorkingDirectory= if needed", "percentage": 94, "note": "First failed ExecStart stops subsequent execution"}]$$::jsonb,
    'service unit file readable, executable accessible and testable, shell access to run commands, journalctl available, systemctl status access',
    'systemctl status shows exit code and status message, manual command execution succeeds, service starts without errors after fix',
    'Not testing command manually before putting in unit file, ignoring exit codes, prefixing with - unnecessarily hiding real errors',
    0.94,
    'sonnet-4',
    NOW(),
    'https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html'
),
(
    'Systemd error: start limit exceeded for unit (StartLimitIntervalSec or StartLimitBurst)',
    'systemd',
    'HIGH',
    $$[{"solution": "Check current start limits with systemctl cat service-name.service | grep StartLimit, identify why service keeps failing by examining journalctl logs, fix underlying cause (check dependencies, timeouts, exec failures), increase limits if crashes are expected with StartLimitBurst=10, reset failed state with systemctl reset-failed service-name", "percentage": 91, "note": "Limits prevent restart loops"}]$$::jsonb,
    'service unit file readable, systemctl status/reset-failed access, journalctl available, ability to modify unit file or reset failures',
    'systemctl start succeeds without hitting start limit, service stays running, no start limit messages in journalctl',
    'Increasing limits without fixing root cause, resetting failures without addressing underlying issue, misunderstanding StartLimitIntervalSec duration',
    0.91,
    'sonnet-4',
    NOW(),
    'https://www.freedesktop.org/software/systemd/man/latest/systemctl.html'
),
(
    'Systemd error: Type=forking service failed - PIDFile not specified or incorrect process identified',
    'systemd',
    'HIGH',
    $$[{"solution": "Add PIDFile=/path/to/pidfile.pid to [Service] section, create pidfile location directory if needed with mkdir -p, verify service writes PID to file using strace or service documentation, test with systemctl start service-name, verify with ps and check /proc/[pid]/cmdline, reload daemon with systemctl daemon-reload", "percentage": 92, "note": "Forking services require explicit PIDFile"}]$$::jsonb,
    'Type=forking service unit file editable, service writes PID file, directory for PID file is writable, strace optional but helpful, journalctl access',
    'systemctl start succeeds and shows active (running), systemctl status displays correct main PID, service process persists after systemctl returns',
    'Assuming systemd auto-detects forked process correctly, not specifying PIDFile when service uses Type=forking, wrong PID file path',
    0.92,
    'sonnet-4',
    NOW(),
    'https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html'
);
