-- Next.js Error Mining - 10 High-Impact Errors from Stack Overflow
-- Mined on 2025-11-26

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Application error: a client-side exception has occurred', 'nextjs', 'HIGH', '[{"solution": "Check browser console for detailed error stack trace", "percentage": 90}, {"solution": "Disable package incompatibilities like Headless UI with React 18", "percentage": 85}, {"solution": "Disable reactStrictMode if incompatible packages detected", "percentage": 80}]'::jsonb, 'Next.js 12+, React 18', 'Application renders without error popup', 'Ignoring browser console logs, assuming frontend issue is server-side', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/72607999/next-js-application-error-a-client-side-exception-has-occurred-see-the-browser', 'admin:1764210570'),

('Error objects are not supported when passing from Server Components to Client Components', 'nextjs', 'HIGH', '[{"solution": "Serialize error to plain object: return { error: { message: error.message } }", "percentage": 95}, {"solution": "Catch error on server-side and pass stringified message only", "percentage": 92}, {"solution": "Use error state with useEffect to trigger error boundary", "percentage": 88}]'::jsonb, 'Next.js 13+, App Router, Server Actions', 'Custom error handling in client component without serialization warning', 'Passing Error object directly instead of serialized plain object', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/77336592/how-to-throw-and-handle-custom-errors-from-server-to-client-side-in-next-js', 'admin:1764210570'),

('Error Boundaries do not catch errors from event handlers', 'nextjs', 'HIGH', '[{"solution": "Use error state + useEffect to trigger boundary: if (error) throw error", "percentage": 91}, {"solution": "Import notFound from next/navigation for 404s", "percentage": 88}, {"solution": "Catch in try-catch and set state, useEffect throws for boundary", "percentage": 85}]'::jsonb, 'React 16+, Error Boundaries, Event Handlers', 'Error caught by boundary when error state changes', 'Expecting Error Boundary to catch event handler errors directly', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/76964636/next-js-13-error-and-not-found-pages-not-displaying-properly', 'admin:1764210570'),

('Custom error page (_error.js) completely ignored in dev mode', 'nextjs', 'MEDIUM', '[{"solution": "Use npm run prod (build + NODE_ENV=production next start) to test custom error page", "percentage": 92}, {"solution": "Accept that Next.js shows internal error-debug page in dev intentionally", "percentage": 88}, {"solution": "Add debug script to package.json combining build and start", "percentage": 85}]'::jsonb, 'Next.js 9-10, _error.js file, dev mode', 'Custom error page displays in production build', 'Expecting custom error page to work in dev mode (by design, it doesn''t)', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/49758680/nextjs-use-error-js-in-dev-mode', 'admin:1764210570'),

('How to cleanly handle errors in getStaticProps without JSON serialization errors', 'nextjs', 'HIGH', '[{"solution": "Return notFound: true to trigger 404 page on error", "percentage": 93}, {"solution": "Wrap fetch in try-catch and return notFound on exception", "percentage": 90}, {"solution": "Check for data existence before returning props", "percentage": 88}]'::jsonb, 'Next.js, getStaticProps, Static Generation', 'Page renders custom error state or 404 without serialization errors', 'Passing complex error objects in props instead of simple status codes', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/67168743/how-to-cleanly-handle-errors-in-nextjs-getstaticprops', 'admin:1764210570'),

('Custom error page only works locally but not on Netlify/Vercel deployment', 'nextjs', 'MEDIUM', '[{"solution": "Use getServerSideProps with try-catch returning errorCode prop", "percentage": 89}, {"solution": "Explicitly render error component when errorCode prop is set", "percentage": 86}, {"solution": "Ensure custom _error page receives props properly in export", "percentage": 83}]'::jsonb, 'Next.js 10+, _error.js, Netlify/Vercel deployment', 'Custom error page renders on deployed production build', 'Not passing errorCode through props to error page component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/68000425/next-js-custom-error-page-only-works-locally', 'admin:1764210570'),

('Rendering custom error page when API fetch fails in getInitialProps', 'nextjs', 'MEDIUM', '[{"solution": "Wrap fetch in try-catch in getInitialProps", "percentage": 88}, {"solution": "Return items: null on error for conditional rendering", "percentage": 85}, {"solution": "Render error component when items is null in page component", "percentage": 82}]'::jsonb, 'Next.js 8-11, getInitialProps, SSR', 'Error page or fallback UI renders when API request fails', 'Not handling fetch errors in getInitialProps gracefully', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/60624532/next-js-how-to-handle-error-in-getinitialprops', 'admin:1764210570'),

('Cannot read properties of undefined (reading ''map'') in Next.js component', 'nextjs', 'HIGH', '[{"solution": "Check if array exists before mapping: if (items && items.length)", "percentage": 94}, {"solution": "Use optional chaining: items?.map()", "percentage": 92}, {"solution": "Provide default empty array in destructuring or props", "percentage": 89}]'::jsonb, 'JavaScript, React, Array methods', 'No undefined reference error when rendering lists', 'Attempting to map over undefined or null data without null checks', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/72607999/next-js-application-error-a-client-side-exception-has-occurred-see-the-browser', 'admin:1764210570'),

('Best practices for handling server errors and avoiding cascading failures', 'nextjs', 'MEDIUM', '[{"solution": "Use Early Return pattern to exit on errors immediately", "percentage": 87}, {"solution": "Validate data at component boundaries before rendering", "percentage": 85}, {"solution": "Log errors server-side while showing generic message to client", "percentage": 82}]'::jsonb, 'Error handling patterns, Server-side validation', 'No cascading errors or undefined prop warnings', 'Not validating data structure before passing to child components', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/64583856/nextjs-best-practice-for-handling-server-error-and-client-side-error', 'admin:1764210570'),

('Duplicate entry error or database constraint violations in Next.js API routes', 'nextjs', 'MEDIUM', '[{"solution": "Check database uniqueness constraints before insert/update", "percentage": 88}, {"solution": "Return 409 Conflict status with user-friendly error message", "percentage": 85}, {"solution": "Implement idempotency keys for API operations to prevent duplicates", "percentage": 80}]'::jsonb, 'Database design, API routes, SQL constraints', 'Unique constraint violations handled gracefully with HTTP 409', 'Ignoring SQL constraint errors and exposing database error messages to client', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/77336592/how-to-throw-and-handle-custom-errors-from-server-to-client-side-in-next-js', 'admin:1764210570');
