INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: encountered during context initialization - cancel', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/25356781/spring-boot-remove-whitelabel-error-page', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: encountered during context initialization - cancel', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/49034254/spring-boot-whitelabel-error-page-type-not-found-status-404', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('BeanCreationException: Error creating bean with name ''notificationService', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for BeanCreationException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for BeanCreationException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/39628930/why-do-i-always-get-whitelabel-error-page-with-status-404-while-running-a-simp', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('InvocationTargetException: at sun.reflect.NativeMethodAccessorImpl.invoke0(Na', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for InvocationTargetException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for InvocationTargetException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/69601526/spring-boot-getmapping-returns-a-404-whitelabel-error-page-in-a-very-simple-pro', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('BeanCreationException: Error creating bean with name ''notificationService', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for BeanCreationException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for BeanCreationException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/66322184/i-keep-getting-a-whitelabel-error-page-when-running-spring-boot-application', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('BeanCreationException: Error creating bean with name ''notificationService', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for BeanCreationException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for BeanCreationException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/49948699/spring-boot-whitelabel-error-page-while-adding-or-updating-a-row', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('InvocationTargetException: at sun.reflect.NativeMethodAccessorImpl.invoke0(Na', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for InvocationTargetException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for InvocationTargetException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/37769173/spring-boot-remove-whitelabel-error-page-for-web-application', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Spring Boot Error', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Spring Boot Error", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Spring Boot Error", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/37447168/springboot-whitelabel-error-page', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('InvocationTargetException: at sun.reflect.NativeMethodAccessorImpl.invoke0(Na', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for InvocationTargetException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for InvocationTargetException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/33169681/spring-boot-bean-creation-exception', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Spring Boot Error', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Spring Boot Error", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Spring Boot Error", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/65181495/bean-creation-error-when-starting-spring-boot-application', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('InvocationTargetException: at sun.reflect.NativeMethodAccessorImpl.invoke0(Na', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for InvocationTargetException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for InvocationTargetException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/78221032/bean-creation-exception-after-upgrading-to-spring-boot-3-2-2-from-2-x', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: encountered during context initialization - cancel', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/42363779/spring-boot-bean-creation-exception', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('InvocationTargetException: at sun.reflect.NativeMethodAccessorImpl.invoke0(Na', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for InvocationTargetException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for InvocationTargetException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/77989588/updating-springboot-to-2-7-18-caused-beancreationexception', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NoSuchBeanDefinitionException: ` and the related `UnsatisfiedDependencyException`', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for NoSuchBeanDefinitionException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for NoSuchBeanDefinitionException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/42385998/spring-boot-rest-service-bean-creation-exception', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NoSuchBeanDefinitionException: ` and the related `UnsatisfiedDependencyException`', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for NoSuchBeanDefinitionException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for NoSuchBeanDefinitionException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/64395920/spring-beancreationexception-unexpected-exception-during-bean-creation', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NoSuchBeanDefinitionException: ` and the related `UnsatisfiedDependencyException`', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for NoSuchBeanDefinitionException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for NoSuchBeanDefinitionException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/39173982/what-is-a-nosuchbeandefinitionexception-and-how-do-i-fix-it', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NoSuchBeanDefinitionException: ` and the related `UnsatisfiedDependencyException`', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for NoSuchBeanDefinitionException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for NoSuchBeanDefinitionException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/54978279/get-nosuchbeandefinitionexception-when-trying-to-autowire-repository-on-control', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NoSuchBeanDefinitionException: ` and the related `UnsatisfiedDependencyException`', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for NoSuchBeanDefinitionException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for NoSuchBeanDefinitionException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/47948014/spring-boot-application-org-springframework-beans-factory-nosuchbeandefinitione', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NoSuchBeanDefinitionException: ` and the related `UnsatisfiedDependencyException`', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for NoSuchBeanDefinitionException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for NoSuchBeanDefinitionException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/27428265/running-integration-tests-with-spring-boot-nosuchbeandefinitionexception', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NoSuchBeanDefinitionException: ` and the related `UnsatisfiedDependencyException`', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for NoSuchBeanDefinitionException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for NoSuchBeanDefinitionException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/51560688/nosuchbeandefinitionexception-while-running-unit-test-when-using-configuration', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NoSuchBeanDefinitionException: ` and the related `UnsatisfiedDependencyException`', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for NoSuchBeanDefinitionException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for NoSuchBeanDefinitionException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/51384800/nosuchbeandefinitionexception-no-qualifying-bean-of-type-available-expected-at', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NoSuchBeanDefinitionException: ` and the related `UnsatisfiedDependencyException`', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for NoSuchBeanDefinitionException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for NoSuchBeanDefinitionException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/70730327/nosuchbeandefinitionexception-unsatisfieddependencyexception-when-testing-spri', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: encountered during context initialization - cancel', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/57740335/i-am-getting-nosuchbeandefinitionexception-while-creating-a-simple-spring-boot-p', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NoSuchBeanDefinitionException: ` and the related `UnsatisfiedDependencyException`', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for NoSuchBeanDefinitionException", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for NoSuchBeanDefinitionException", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/4410087/how-can-we-solve-the-dataintegrityviolationexception-in-spring-hibernate', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: Handler annotation. I want always return instance ', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/2109476/how-to-handle-dataintegrityviolationexception-in-spring', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: Handler annotation. I want always return instance ', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/36498327/catch-dataintegrityviolationexception-in-transactional-service-method', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: Handler annotation. I want always return instance ', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/13239040/org-springframework-dao-dataintegrityviolationexception-misreporting-cause', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: Handler annotation. I want always return instance ', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/52456783/cannot-catch-dataintegrityviolationexception', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: Handler annotation. I want always return instance ', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/37248719/couldnt-catch-dataintegrityviolationexception-with-spring-data-rest', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: Handler annotation. I want always return instance ', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/37335107/spring-boot-throwing-dataintegrityviolationexception-when-inserting-into-my-sql', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: Handler annotation. I want always return instance ', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/70203663/how-to-skip-the-rollback-for-dataintegrityviolationexception', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: Handler annotation. I want always return instance ', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/79131067/spring-boot-validation-problem-understanding-the-methodargumentnotvalidexceptio', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: Handler annotation. I want always return instance ', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/66371164/spring-boot-exceptionhandler-for-methodargumentnotvalidexception-in-restcontroll', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: encountered during context initialization - cancel', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/33663801/how-do-i-customize-default-error-message-from-spring-valid-validation', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: Handler annotation. I want always return instance ', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/51991992/getting-ambiguous-exceptionhandler-method-mapped-for-methodargumentnotvalidexce', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: { UserDto existingUserDto; try { existingUserDto =', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/48136070/spring-boot-requestbody-with-valid-exceptionhandler-for-methodargumentnotvali', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: { UserDto existingUserDto; try { existingUserDto =', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/49339406/how-to-properly-throw-methodargumentnotvalidexception', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: { UserDto existingUserDto; try { existingUserDto =', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/56467965/why-spring-boot-throws-different-exceptions-for-controller-method-argument-valid', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: { UserDto existingUserDto; try { existingUserDto =', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/59952013/how-to-override-handlemethodargumentnotvalid-properly-in-spring-boot', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: { UserDto existingUserDto; try { existingUserDto =', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/62666481/how-to-handle-org-springframework-http-converter-httpmessagenotreadableexceptio', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: { UserDto existingUserDto; try { existingUserDto =', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/15561159/httpmessagenotreadableexception-could-not-read-json-unrecognized-field-using-s', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: { UserDto existingUserDto; try { existingUserDto =', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/75145749/exception-handlind-httpmessagenotreadableexception-on-springboot', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: encountered during context initialization - cancel', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/19541878/spring-httpmessagenotreadableexception', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: encountered during context initialization - cancel', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/63219682/get-missing-fields-when-httpmessagenotreadableexception-occurs', 'admin:1764222342');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Exception: encountered during context initialization - cancel', 'spring-boot', 'HIGH', '[{"solution": "Check if you have the correct @ComponentScan configuration for Exception", "percentage": 85}, {"solution": "Verify bean definitions and component scanning for Exception", "percentage": 80}, {"solution": "Review Spring Boot configuration and dependency injection setup", "percentage": 75}]'::jsonb, 'Spring Boot', 'Application starts without errors', 'Incorrect package structure, missing @Component', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/55112349/unable-to-use-custom-httpmessagenotreadableexception-error-message-in-spring-boo', 'admin:1764222342');