INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('CSS specificity conflicts - child rule not overriding parent rule', 'css', 'HIGH', '[{"solution": "Increase specificity of child selector by including parent elements: table.rule1 tr td.rule2 instead of just td.rule2", "percentage": 95}, {"solution": "Use !important as last resort but avoid if possible for maintainability", "percentage": 60}]'::jsonb, 'CSS selector understanding, CSS cascade rules', 'Child style rule overrides parent/ancestor rule correctly', 'Using !important everywhere, not understanding id vs class vs tag specificity calculations', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/11263488/css-override-rules-and-specificity', 'admin:1764223136'),

('CSS selector specificity with multiple stylesheets', 'css', 'HIGH', '[{"solution": "Calculate specificity as (ids, classes, tags): each ID adds 100, class adds 10, tag adds 1. Compare final numbers", "percentage": 93}, {"solution": "Use BEM (Block Element Modifier) methodology for consistent naming and lower conflicts", "percentage": 85}]'::jsonb, 'CSS specificity calculation, multiple stylesheet knowledge', 'Correct style applied without needing !important', 'Misunderstanding specificity with comma-separated selectors', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/7535149/css-selector-specificity-conflicts-due-to-multiple-stylesheets', 'admin:1764223136'),

('z-index stacking context not working as expected', 'css', 'HIGH', '[{"solution": "Ensure positioned elements have z-index values: use position: absolute, relative, fixed, or sticky with z-index", "percentage": 94}, {"solution": "Remember z-index only works on positioned elements unless using flexbox or grid items", "percentage": 92}]'::jsonb, 'CSS positioning knowledge, understanding stacking contexts', 'Elements appear in correct z-order regardless of nesting', 'Forgetting to add position property, mixing positioned and non-positioned elements', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/32513540/understanding-z-index-stacking-order', 'admin:1764223136'),

('Cannot override z-index stacking context for nested elements', 'css', 'MEDIUM', '[{"solution": "Child elements cannot break out of parent stacking context. Use 3D transform: transform-style: preserve-3d and translateZ(1px) as workaround", "percentage": 75}, {"solution": "Restructure DOM so competing elements are siblings, not nested in different stacking contexts", "percentage": 80}]'::jsonb, 'Understanding stacking contexts, CSS transforms', 'Element appears above higher z-index sibling from different stacking context', 'Trying to use z-index alone to break stacking context hierarchy', 0.78, 'haiku', NOW(), 'https://stackoverflow.com/questions/19850037/override-css-z-index-stacking-context', 'admin:1764223136'),

('Flexbox align-content not working on single-line flex containers', 'css', 'HIGH', '[{"solution": "Use align-items instead of align-content for single-line flex containers", "percentage": 96}, {"solution": "align-content only applies to multi-line flex containers with flex-wrap: wrap", "percentage": 95}]'::jsonb, 'Flexbox properties knowledge', 'Flex items align correctly using align-items', 'Using align-content instead of align-items, not enabling flex-wrap for multi-line', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/37226787/align-content-not-working-on-flex-items', 'admin:1764223136'),

('Flexbox align-items center not centering items', 'css', 'HIGH', '[{"solution": "Set explicit height on flex container: height: 100vh or specific pixel value", "percentage": 96}, {"solution": "Ensure align-items is on container not individual items, use align-self for overrides", "percentage": 94}]'::jsonb, 'Flexbox layout, container height requirement', 'Items centered vertically in flex container', 'Missing container height, confusing align-items with align-self', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/48516538/flex-align-items-center-not-centering-items', 'admin:1764223136'),

('CSS media queries not working on mobile devices', 'css', 'HIGH', '[{"solution": "Add viewport meta tag: <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">", "percentage": 98}, {"solution": "Use max-width and min-width instead of max-device-width and min-device-width for responsive design", "percentage": 92}]'::jsonb, 'Mobile responsive design, viewport configuration', 'Media queries apply on mobile and resized browser windows', 'Missing viewport meta tag, using device-width instead of width', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/7859336/why-are-my-css3-media-queries-not-working-on-mobile-devices', 'admin:1764223136'),

('CSS media query not working in stylesheet', 'css', 'MEDIUM', '[{"solution": "Ensure viewport meta tag is present in HTML head", "percentage": 97}, {"solution": "Place media queries at end of CSS file to ensure proper cascade", "percentage": 85}]'::jsonb, 'CSS media queries, HTML viewport setup', 'Media query styles apply when viewport conditions are met', 'Missing viewport meta tag, media query appearing before base styles', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/18207076/css-media-query-wont-work', 'admin:1764223136'),

('CSS Grid syntax error - grid not registering', 'css', 'HIGH', '[{"solution": "Fix grid-template-columns syntax: repeat(2, 1fr) not repeat (2 1fr) - no space after repeat", "percentage": 97}, {"solution": "Remove spaces in repeat function: repeat(8, 1fr) with comma, not repeat (8 1fr)", "percentage": 96}]'::jsonb, 'CSS Grid syntax, repeat() function', 'Grid displays correctly with proper column/row layout', 'Adding spaces in repeat() function, forgetting commas', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/56914861/css-grid-layout-problems', 'admin:1764223136'),

('CSS Grid layout with ng-repeat creating stacked items', 'css', 'MEDIUM', '[{"solution": "Apply grid container at outer level, not repeated per item. Move grid to parent wrapping the ng-repeat", "percentage": 91}, {"solution": "Grid applies only to direct children, so structure DOM with grid container outside loop", "percentage": 90}]'::jsonb, 'CSS Grid, Angular ng-repeat behavior', 'Items properly distributed in grid, not stacked on top of each other', 'Applying grid-container class to repeated elements instead of parent', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/50228696/why-is-css-grid-not-working', 'admin:1764223136'),

('CSS Grid template areas invalid - non-rectangular regions', 'css', 'MEDIUM', '[{"solution": "Grid areas must form rectangles. L-shaped or disconnected regions are invalid. Use grid-column and grid-row instead", "percentage": 92}, {"solution": "Verify all area names have same column count and form solid rectangles", "percentage": 90}]'::jsonb, 'CSS Grid template areas, rectangle shapes', 'Grid template areas form valid rectangular regions', 'Using L-shaped or disconnected grid regions', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/43461457/css-grid-template-areas-property-not-aligning-grid-items', 'admin:1764223136'),

('CSS specificity - type selector losing to class selector with attribute', 'css', 'MEDIUM', '[{"solution": "Attribute selector specificity: input[type=\"text\"] (type + attribute = 0-1-1) beats class alone (0-1-0)", "percentage": 94}, {"solution": "Qualify class selector with element: input.classname (0-1-1) equals attribute selector specificity", "percentage": 93}]'::jsonb, 'CSS specificity calculation, attribute selectors', 'Correct selector wins based on specificity calculation', 'Not counting type selector in attribute selector specificity', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/14666581/precedence-in-css-selector-specifity-conflicts-type-vs-class-selector', 'admin:1764223136'),

('CSS properties that create stacking contexts', 'css', 'MEDIUM', '[{"solution": "Stacking contexts created by: z-index on positioned elements, opacity < 1, transform other than none, will-change with relevant property", "percentage": 93}, {"solution": "Also: perspective, filter, mix-blend-mode not normal, isolation: isolate, transform-style: preserve-3d", "percentage": 89}]'::jsonb, 'CSS stacking context properties', 'Child elements can be positioned relative to parent stacking context', 'Forgetting all the ways stacking contexts are created', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/16148007/which-css-properties-create-a-stacking-context', 'admin:1764223136'),

('CSS media queries with specific pixel ratios for different devices', 'css', 'MEDIUM', '[{"solution": "For high-DPI devices: use -webkit-device-pixel-ratio media query. Example: @media (-webkit-device-pixel-ratio: 3)", "percentage": 85}, {"solution": "Use comma-separated media queries for multiple conditions: @media screen and (min-width:640px), screen and (-webkit-device-pixel-ratio: 3)", "percentage": 82}]'::jsonb, 'Device pixel ratio knowledge, media query syntax', 'Correct styles apply to devices with different pixel densities', 'Not considering device pixel ratio for responsive design', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/23869883/css-media-query-not-working-correctly', 'admin:1764223136'),

('CSS Grid rounding errors in Chrome causing width mismatches', 'css', 'LOW', '[{"solution": "Ensure container width divides evenly by number of columns. Use 984px instead of 980px for 12 columns", "percentage": 88}, {"solution": "Adjust grid-column-gap so final calculation divides evenly without sub-pixel fractions", "percentage": 75}]'::jsonb, 'CSS Grid calculations, container sizing', 'Grid items fill container without sub-pixel rendering artifacts', 'Using widths that create recurring decimal fractions in column calculations', 0.78, 'haiku', NOW(), 'https://stackoverflow.com/questions/66116397/my-css-grid-layout-doesnt-fill-its-container-on-chrome-whats-causing-the-loss', 'admin:1764223136'),

('CSS specificity with multiple IDs in selector', 'css', 'MEDIUM', '[{"solution": "Each ID selector in a selector string adds to specificity. #parent #child has specificity 0-2-0 (two IDs)", "percentage": 95}, {"solution": "Specificity = (num-ids, num-classes, num-tags). More specific selector always wins regardless of order", "percentage": 94}]'::jsonb, 'CSS specificity with ID selectors', 'Correct selector applied based on ID count in specificity', 'Not understanding that multiple IDs in one selector increase specificity', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/6405918/question-about-a-confusing-css-specificity-rule-from-the-book-sams-teach-yours', 'admin:1764223136'),

('CSS syntax error - margin and padding missing colon', 'css', 'HIGH', '[{"solution": "CSS property-value syntax is property: value; not property value. Use margin: 0; not margin 0;", "percentage": 98}, {"solution": "Add colon after property name and semicolon at end of declaration", "percentage": 99}]'::jsonb, 'CSS syntax knowledge', 'CSS parses without syntax errors, styles apply', 'Forgetting colon between property and value', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/72234434/how-do-i-solve-a-problem-with-a-css-file', 'admin:1764223136'),

('CSS z-index auto vs z-index 0 and stacking context differences', 'css', 'MEDIUM', '[{"solution": "z-index: auto does not create stacking context (element in parent context). z-index: 0 creates new stacking context", "percentage": 96}, {"solution": "Child of z-index: auto can appear above siblings of parent. Child of z-index: 0 trapped in that context", "percentage": 94}]'::jsonb, 'Stacking context creation, z-index behavior', 'z-index values work as expected with proper stacking context understanding', 'Confusing z-index: auto with z-index: 0', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/16285968/children-of-z-index-auto-vs-z-index-0-and-what-is-stacking-context-in-css', 'admin:1764223136'),

('CSS Grid layout with non-rectangular spanning items', 'css', 'MEDIUM', '[{"solution": "Structure grid so items only span rectangular regions. Use nested grids if needing complex layouts", "percentage": 88}, {"solution": "Define grid with auto-placement and use grid-row/grid-column for positioning", "percentage": 85}]'::jsonb, 'CSS Grid layout, DOM structure', 'Grid items arrange properly without overlapping incorrectly', 'Trying to make grid items span non-rectangular areas', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/53950923/css-grid-not-working-as-expected-with-rows', 'admin:1764223136'),

('CSS z-index interwoven elements with different parent contexts', 'css', 'LOW', '[{"solution": "Remove z-index from parent elements so children use same stacking context. Keep only z-index on actual children", "percentage": 92}, {"solution": "If parents have z-index: auto (default), children can mix across sibling parents", "percentage": 89}]'::jsonb, 'Stacking context control, CSS positioning', 'Child elements from different parents interweave correctly', 'Adding z-index to parent elements creating separate stacking contexts', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/27450486/understanding-css-z-index-when-stacked-within-other-z-index', 'admin:1764223136'),

('Flexbox align-items space-around property does not exist', 'css', 'HIGH', '[{"solution": "Use align-content: space-around for multi-line flex containers (requires flex-wrap: wrap)", "percentage": 96}, {"solution": "Use justify-content: space-around for horizontal spacing instead", "percentage": 93}]'::jsonb, 'Flexbox properties, multi-line containers', 'Items space correctly using valid flexbox properties', 'Using non-existent align-items: space-around', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/39711210/flexbox-align-items-not-working', 'admin:1764223136'),

('CSS media queries not working without explicit screen keyword', 'css', 'MEDIUM', '[{"solution": "Use @media screen and (min-width: 401px) instead of @media (min-width: 401px)", "percentage": 88}, {"solution": "Always include screen keyword and use proper syntax: @media screen and (condition)", "percentage": 86}]'::jsonb, 'Media query syntax, CSS media types', 'Media queries apply correctly with screen keyword', 'Omitting screen keyword from media query', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/18470350/css-media-queries-not-working-anywhere', 'admin:1764223136'),

('Media query CSS not applying to mobile - device-width vs width', 'css', 'HIGH', '[{"solution": "Use @media screen and (min-width: 320px) for responsive. Device-width is deprecated for most modern use", "percentage": 94}, {"solution": "Add viewport meta tag and ensure width-based queries instead of device-width", "percentage": 93}]'::jsonb, 'Media query best practices, viewport configuration', 'Mobile and desktop show correct responsive styles', 'Using device-width instead of width in media queries', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/17208218/css-media-query-dont-working-in-css-file', 'admin:1764223136'),

('Flexbox align-content space-around not working without height', 'css', 'HIGH', '[{"solution": "Set explicit height on flex container (height: 300px or height: 100vh)", "percentage": 96}, {"solution": "align-content needs extra space to distribute. Without height or flex-grow, no extra cross-axis space exists", "percentage": 94}]'::jsonb, 'Flexbox cross-axis alignment, container sizing', 'Flex lines distribute properly with align-content when height available', 'Not providing container height for align-content to work', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/53151053/align-content-space-around-not-working-in-css-flexbox', 'admin:1764223136'),

('CSS selector specificity with class not overriding type selector with attribute', 'css', 'MEDIUM', '[{"solution": "Attribute selector + element (input[type=\"text\"] = 0-1-1) beats single class (.class = 0-1-0). Add element to class: input.class", "percentage": 95}, {"solution": "Understand specificity calculation: (ID count, class/attribute count, element count)", "percentage": 93}]'::jsonb, 'CSS specificity rules, selector combinations', 'Correct selector with higher specificity overrides', 'Not accounting for element type in attribute selector specificity', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/549828/how-can-i-set-one-style-to-override-another-conflicting-style-in-css', 'admin:1764223136');
