INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('WRONGTYPE Operation against a key holding the wrong kind of value', 'database-redis', 'HIGH', '[{"solution": "Check if the key contains the expected data type before operating on it", "percentage": 85}, {"solution": "Use Redis TYPE command to verify key type: TYPE key_name", "percentage": 80}, {"solution": "Delete and recreate the key with correct type", "percentage": 75}]'::jsonb, 'Redis 2.0+', 'Operation succeeds on correct data type', 'Mixing different set methods (SET then HSET)', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/47879894/redis-error-wrongtype-operation-against-a-key-holding-the-wrong-kind-of-value', 'admin:1764220207'),

('MOVED slot redirection error in cluster', 'database-redis', 'HIGH', '[{"solution": "Use Redis.Cluster client instead of plain Redis for cluster mode", "percentage": 90}, {"solution": "Enable cluster-mode support in client library", "percentage": 88}, {"solution": "Redirect to specified node: GET x -MOVED 3999 127.0.0.1:6381", "percentage": 85}]'::jsonb, 'Redis Cluster 3.0+', 'Request successfully routed to correct node', 'Using non-cluster-aware client with cluster endpoint', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/64374113/replyerror-moved-error-after-connecting-to-redis-cluster-aws', 'admin:1764220207'),

('CLUSTERDOWN The cluster is down', 'database-redis', 'HIGH', '[{"solution": "Check that all hash slots are covered: cluster info", "percentage": 85}, {"solution": "Set cluster-require-full-coverage to no if partial cluster is acceptable", "percentage": 80}, {"solution": "Ensure each master has at least one replica at all times", "percentage": 82}]'::jsonb, 'Redis Cluster 3.0+', 'Cluster commands execute successfully', 'Missing replicas for failed masters causing uncovered slots', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/53594257/clusterdown-the-cluster-is-down-in-redis', 'admin:1764220207'),

('LOADING Redis is loading the dataset in memory', 'database-redis', 'MEDIUM', '[{"solution": "Wait for Redis startup to complete before issuing commands", "percentage": 90}, {"solution": "Check Redis logs for startup progress or errors", "percentage": 85}, {"solution": "Increase timeout in client: redis-cli -h host --raw", "percentage": 80}]'::jsonb, 'Redis 2.6+', 'Commands execute after loading completes', 'Attempting operations during startup or full resynchronization', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/74896763/analysis-of-redis-error-logs-loading-redis-is-loading-the-dataset-in-memory-an', 'admin:1764220207'),

('OOM command not allowed when used memory exceeds maxmemory', 'database-redis', 'HIGH', '[{"solution": "Increase maxmemory setting: CONFIG SET maxmemory 1gb", "percentage": 88}, {"solution": "Change eviction policy: CONFIG SET maxmemory-policy allkeys-lru", "percentage": 85}, {"solution": "Delete non-volatile keys to free memory", "percentage": 80}]'::jsonb, 'Redis 2.2+', 'SET commands succeed after memory freed', 'Setting volatile-lru policy when non-volatile keys exist', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/18430324/how-to-debug-the-error-oom-command-not-allowed-when-used-memory-maxmemory', 'admin:1764220207'),

('BUSYKEY target key name already exists', 'database-redis', 'MEDIUM', '[{"solution": "Use MIGRATE with REPLACE flag to overwrite existing key", "percentage": 92}, {"solution": "Delete existing key before RESTORE: DEL key_name", "percentage": 88}, {"solution": "Check for key name collisions before migration", "percentage": 85}]'::jsonb, 'Redis 2.6+', 'MIGRATE or RESTORE commands complete', 'Running MIGRATE COPY without REPLACE on existing keys', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/57704700/redis-busykey-target-key-name-already-exists', 'admin:1764220207'),

('Connection refused unable to connect to Redis', 'database-redis', 'HIGH', '[{"solution": "Start Redis server: redis-server", "percentage": 92}, {"solution": "Verify Redis is listening on configured port: redis-cli ping", "percentage": 90}, {"solution": "Check firewall rules and network connectivity", "percentage": 85}]'::jsonb, 'Redis 1.0+', 'PING returns PONG', 'Redis server not running on expected port', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/42857551/could-not-connect-to-redis-at-127-0-0-16379-connection-refused-with-homebrew', 'admin:1764220207'),

('READONLY You can''t write against a read only replica', 'database-redis', 'HIGH', '[{"solution": "Connect to master node instead of replica for writes", "percentage": 90}, {"solution": "Use read-only replica only for read operations", "percentage": 88}, {"solution": "Set replica as master if original master failed: REPLICAOF NO ONE", "percentage": 82}]'::jsonb, 'Redis 2.4+', 'Write commands succeed on master', 'Accidentally connecting to replica endpoint for writes', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/72521353/redis-issue-with-readonly-you-cant-write-against-a-read-only-replica-but-only-r', 'admin:1764220207'),

('Protocol error got H as reply type byte', 'database-redis', 'MEDIUM', '[{"solution": "Verify Redis server is running (not HTTP server)", "percentage": 85}, {"solution": "Check port number - ensure using Redis port not HTTP", "percentage": 88}, {"solution": "Disable proxy/firewall interference: use direct connection", "percentage": 80}]'::jsonb, 'Redis 2.0+', 'Commands return valid RESP protocol responses', 'HTTP server responding on Redis port or proxy interference', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/50950494/protocol-error-got-h-as-reply-type-byte', 'admin:1764220207'),

('Sentinel cannot get master from available sentinels', 'database-redis', 'MEDIUM', '[{"solution": "Use correct Sentinel IP binding: bind 127.0.1.1 (not 127.0.0.1)", "percentage": 85}, {"solution": "Switch to Lettuce client for better Sentinel support", "percentage": 82}, {"solution": "Configure sentinel bind to non-loopback IP", "percentage": 80}]'::jsonb, 'Redis Sentinel 2.8+', 'Sentinel successfully locates master', 'Loopback IP binding issues in Sentinel configuration', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/53437726/java-client-cant-connect-to-redis-sentinel-which-is-running-on-localhost', 'admin:1764220207'),

('EXECABORT Transaction discarded because of previous errors', 'database-redis', 'MEDIUM', '[{"solution": "Ensure at least one command is in the transaction", "percentage": 88}, {"solution": "Check for out-of-memory condition: INFO memory", "percentage": 85}, {"solution": "Verify all commands are valid before EXEC", "percentage": 82}]'::jsonb, 'Redis 2.0+', 'MULTI/EXEC completes successfully', 'Empty MULTI/EXEC transaction or OOM condition', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/32724410/redis-execabort-transaction-discarded-because-of-previous-errors-rediscomman', 'admin:1764220207'),

('MASTER aborted replication with error ERR Unable to perform background save', 'database-redis', 'MEDIUM', '[{"solution": "Enable memory overcommit: sysctl vm.overcommit_memory=1", "percentage": 88}, {"solution": "Restart Redis master server", "percentage": 85}, {"solution": "Increase available memory on master", "percentage": 80}]'::jsonb, 'Redis 2.4+', 'Slave syncs with master successfully', 'Master running out of memory during BGSAVE for replication', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/18859763/redis-slave-wont-sync-with-master', 'admin:1764220207'),

('ERR value is not an integer or out of range', 'database-redis', 'MEDIUM', '[{"solution": "Ensure key contains valid integer before INCR", "percentage": 90}, {"solution": "Use StringRedisTemplate for reliable increment operations", "percentage": 85}, {"solution": "Initialize key with SET before INCR: SET key 0", "percentage": 88}]'::jsonb, 'Redis 2.0+', 'INCR returns integer value', 'INCR on non-integer key or exceeded int64 bounds', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/52978717/redis-incrementing-a-numeric-value-err-value-is-not-an-integer-or-out-of-range', 'admin:1764220207'),

('Redis pub/sub subscription hangs on subscribe method', 'database-redis', 'MEDIUM', '[{"solution": "Use dedicated thread for subscription: new Thread() with subscribe", "percentage": 88}, {"solution": "Use separate Redis connection for pub/sub operations", "percentage": 90}, {"solution": "Implement proper callback handlers in JedisPubSub", "percentage": 85}]'::jsonb, 'Redis 2.0+', 'Subscription receives messages in separate thread', 'Blocking subscribe on main thread without thread separation', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/41499605/pubsub-is-not-working-in-redis', 'admin:1764220207'),

('MISCONF Redis is configured to save RDB snapshots but currently not able to persist', 'database-redis', 'HIGH', '[{"solution": "Restart Redis server to reset configuration: systemctl restart redis", "percentage": 92}, {"solution": "Disable save-on-error: CONFIG SET stop-writes-on-bgsave-error no", "percentage": 85}, {"solution": "Check disk space and permissions for dump.rdb location", "percentage": 88}]'::jsonb, 'Redis 2.4+', 'SET commands execute successfully', 'BGSAVE failure due to disk/memory issues after upgrade', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/19581059/misconf-redis-is-configured-to-save-rdb-snapshots', 'admin:1764220207'),

('MISCONF Errors writing to the AOF file No space left on device', 'database-redis', 'HIGH', '[{"solution": "Free up disk space immediately", "percentage": 92}, {"solution": "Enable AOF rewrite to compact file: BGREWRITEAOF", "percentage": 88}, {"solution": "Increase disk space available to Redis", "percentage": 85}]'::jsonb, 'Redis 2.4+', 'AOF write succeeds after space freed', 'Disk full while writing to appendonly.aof', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/66480305/redis-unable-to-write-to-aof-due-to-disk-space-aof-rewrite-enabled', 'admin:1764220207'),

('NOAUTH Authentication required no password set', 'database-redis', 'MEDIUM', '[{"solution": "Issue AUTH command with correct password: AUTH password", "percentage": 88}, {"solution": "Restart Redis to reset config if compromised", "percentage": 85}, {"solution": "Use requirepass in redis.conf to set password", "percentage": 82}]'::jsonb, 'Redis 2.6+', 'AUTH succeeds and commands execute', 'Unsecured Redis exposed and set requirepass by attacker', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/34115213/redis-raises-noauth-authentication-required-error-but-there-is-no-password-set', 'admin:1764220207'),

('ACL SAVE Permission denied opening temp ACL file', 'database-redis', 'MEDIUM', '[{"solution": "Ensure ACL directory is writable by redis user: chown redis:redis /path", "percentage": 92}, {"solution": "Set permissions on ACL file directory: chmod 750", "percentage": 88}, {"solution": "Ensure /tmp directory is writable for temporary files", "percentage": 85}]'::jsonb, 'Redis 6.0+', 'ACL SAVE completes successfully', 'Redis process lacks write permissions on ACL config directory', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/65178234/unable-to-save-redis-acls-getting-permission-denied-in-logs', 'admin:1764220207'),

('CROSSSLOT Keys in request don''t hash to the same slot', 'database-redis', 'HIGH', '[{"solution": "Use hash tags to force keys to same slot: {tag}key1 {tag}key2", "percentage": 92}, {"solution": "Split multi-key operations into separate calls", "percentage": 88}, {"solution": "Ensure all keys in transaction belong to same hash slot", "percentage": 90}]'::jsonb, 'Redis Cluster 3.0+', 'Multi-key operations succeed with keys in same slot', 'Attempting multi-key operation with keys in different slots', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/38042629/err-crossslot-keys-in-request-dont-hash-to-the-same-slot', 'admin:1764220207'),

('Read timeout error on connection or socket timeout', 'database-redis', 'MEDIUM', '[{"solution": "Increase read timeout: OPT_READ_TIMEOUT or config parameter", "percentage": 88}, {"solution": "Set read timeout to -1 for no timeout on blocking operations", "percentage": 85}, {"solution": "Disable persistent connections in phpredis", "percentage": 82}]'::jsonb, 'Redis 2.0+', 'Operations complete within configured timeout', 'Timeout too short for blocking operations like BLPOP', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/18072407/php-redis-timeout-read-error-on-connection', 'admin:1764220207'),

('ERR max number of clients reached', 'database-redis', 'HIGH', '[{"solution": "Increase maxclients config: CONFIG SET maxclients 20000", "percentage": 90}, {"solution": "Use connection pooling to reuse connections", "percentage": 92}, {"solution": "Close unused client connections: CLIENT KILL", "percentage": 85}]'::jsonb, 'Redis 2.0+', 'New client connections accepted', 'Creating new client per request without connection pooling', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/50910697/redis-max-number-of-clients-reached', 'admin:1764220207'),

('ERR Error running script call to f_... This Redis command is not allowed from scripts', 'database-redis', 'MEDIUM', '[{"solution": "Use redis.replicate_commands() at start of Lua script", "percentage": 88}, {"solution": "Avoid no-script commands (CLIENT, CONFIG GET, INFO) in Lua", "percentage": 90}, {"solution": "Use alternative commands that are script-safe", "percentage": 85}]'::jsonb, 'Redis 3.0+', 'Lua script executes without command restriction errors', 'Calling no-script commands inside Lua scripts', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/58947190/cannot-run-passed-lua-script-to-redis-this-redis-command-is-not-allowed-from-sc', 'admin:1764220207'),

('Unicode decode error UTF-8 encoding mismatch', 'database-redis', 'MEDIUM', '[{"solution": "Enable decode_responses=True in Redis client", "percentage": 92}, {"solution": "Specify encoding parameter in Redis constructor: encoding=''utf-8''", "percentage": 88}, {"solution": "Manually decode responses: value.decode(''utf-8'')", "percentage": 85}]'::jsonb, 'Redis 2.0+', 'Unicode values stored and retrieved correctly', 'Not setting decode_responses or proper encoding in client', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/41830055/does-redis-py-support-unicode-and-utf-8-and-how-does-it-work', 'admin:1764220207'),

('SLAVEOF/REPLICAOF data is not replicated from master to slaves', 'database-redis', 'MEDIUM', '[{"solution": "Ensure slave has same requirepass as master", "percentage": 88}, {"solution": "Verify network connectivity between master and slave", "percentage": 90}, {"solution": "Check master is not in CLUSTERDOWN state", "percentage": 85}]'::jsonb, 'Redis 2.4+', 'Slave data synchronized with master', 'Password mismatch or network issues preventing sync', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/65751542/data-is-not-replicated-from-redis-master-to-slaves', 'admin:1764220207'),

('Socket error trying to sync with MASTER connection lost', 'database-redis', 'MEDIUM', '[{"solution": "Check network connectivity between master and slave", "percentage": 88}, {"solution": "Verify slave can reach master hostname/IP and port", "percentage": 90}, {"solution": "Increase replica-read-timeout configuration", "percentage": 82}]'::jsonb, 'Redis 2.4+', 'Slave successfully syncs with master', 'Network partition or master unreachable during SYNC', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/56983731/redis-first-time-replication-issue', 'admin:1764220207'),

('Redis dump.rdb file reading failed RDB corruption', 'database-redis', 'MEDIUM', '[{"solution": "Backup corrupted dump.rdb and delete it", "percentage": 85}, {"solution": "Restore from latest good backup if available", "percentage": 88}, {"solution": "Start Redis fresh: remove dump.rdb and appendonly.aof", "percentage": 82}]'::jsonb, 'Redis 2.4+', 'Redis starts successfully and loads data', 'Incomplete write or data corruption in RDB file', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/31420366/loading-dump-rdb-fails', 'admin:1764220207'),

('Redis server started but killed immediately OOM killer', 'database-redis', 'MEDIUM', '[{"solution": "Increase available system memory", "percentage": 85}, {"solution": "Set maxmemory limit to prevent unlimited growth", "percentage": 90}, {"solution": "Use 32-bit Redis if actual usage is under 4GB", "percentage": 80}]'::jsonb, 'Redis 2.0+', 'Redis process stays running without OOM kill', 'Not setting maxmemory or system running out of RAM', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/21406705/redis-server-started-but-killed-in-a-second', 'admin:1764220207');
