INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Pod CrashLoopBackOff with no logs', 'kubernetes', 'HIGH', '[{"solution": "Check if Dockerfile has a command to run or ReplicationController specifies a command - pod crashing because it starts then immediately exits", "percentage": 90}, {"solution": "Run kubectl describe pod <pod-name> to see event details", "percentage": 85}, {"solution": "Use kubectl logs <pod-name> to view application logs", "percentage": 85}]'::jsonb, 'kubectl configured, pod created', 'Pod enters Running state, logs show output', 'Assuming pod is working without checking logs, not specifying command in Dockerfile', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/41604499/my-kubernetes-pods-keep-crashing-with-crashloopbackoff-but-i-cant-find-any-lo', 'admin:1764193768'),

('ImagePullBackOff Docker registry authentication', 'kubernetes', 'HIGH', '[{"solution": "Create imagePullSecret for private registry: kubectl create secret docker-registry", "percentage": 92}, {"solution": "Verify imagePullSecrets is specified in pod spec", "percentage": 88}, {"solution": "Check registry credentials are correct", "percentage": 85}]'::jsonb, 'Docker registry credentials, private registry access', 'Pod successfully pulls image, no ErrImagePull events', 'Forgetting imagePullSecrets, incorrect credentials, typos in secret name', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/37302776/what-is-the-meaning-of-imagepullbackoff-status-on-a-kubernetes-pod', 'admin:1764193768'),

('CrashLoopBackOff and ImagePullBackOff definitions', 'kubernetes', 'HIGH', '[{"solution": "CrashLoopBackOff: container exits with error after successful pull - check kubectl logs", "percentage": 95}, {"solution": "ImagePullBackOff: Kubernetes cannot pull image - check kubectl describe pod events", "percentage": 95}, {"solution": "Use kubectl describe pod <podname> to see detailed error messages", "percentage": 92}]'::jsonb, 'Pod deployed, kubectl access', 'Pod description shows clear error message, resolution path identified', 'Confusing the two states, not running kubectl describe', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/77193878/what-does-it-mean-a-pod-status-crashloopbackoff-and-imagepullbackoff', 'admin:1764193768'),

('kubectl connection refused to server localhost:8080', 'kubernetes', 'CRITICAL', '[{"solution": "Start minikube if using minikube: minikube start", "percentage": 96}, {"solution": "Create/copy kubeconfig to ~/.kube/config: mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config", "percentage": 93}, {"solution": "Export KUBECONFIG: export KUBECONFIG=/etc/kubernetes/admin.conf", "percentage": 90}]'::jsonb, 'Kubernetes cluster, kubeadm or minikube installed', 'kubectl version returns version info, commands execute successfully', 'Not starting minikube, missing kubeconfig file, wrong kubeconfig permissions', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/37921222/kubectl-connection-to-server-was-refused', 'admin:1764193768'),

('PersistentVolumeClaim indefinitely pending state', 'kubernetes', 'HIGH', '[{"solution": "Add storageClassName to both PersistentVolume and PersistentVolumeClaim so they match", "percentage": 94}, {"solution": "Check PersistentVolume reclaimPolicy is Recycle or Delete, not Retain if reusing volumes", "percentage": 88}, {"solution": "Manually reclaim released PersistentVolume by deleting and recreating it", "percentage": 85}]'::jsonb, 'Storage provisioned, kubectl access', 'PersistentVolumeClaim shows Bound status, pod can mount volume', 'Mismatched storageClassName, Retain policy with reused volume, not checking PV status', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/44891319/kubernetes-persistent-volume-claim-indefinitely-in-pending-state', 'admin:1764193768'),

('Kubernetes Service IPs not reachable from pods', 'kubernetes', 'HIGH', '[{"solution": "Enable IP forwarding on all nodes: sudo sysctl net.ipv4.ip_forward=1", "percentage": 96}, {"solution": "Verify kube-proxy is running on each node: systemctl status kube-proxy or check daemonset", "percentage": 92}, {"solution": "Check iptables rules on nodes: iptables -L and iptables -t nat -L", "percentage": 85}]'::jsonb, 'Kubernetes cluster with services, node SSH access', 'Service responds from pod, DNS resolution works, curl to service IP succeeds', 'IP forwarding not enabled, kube-proxy not running, overlay network misconfigured', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/42705432/kubernetes-service-ips-not-reachable', 'admin:1764193768'),

('ImagePullBackOff with private Docker Hub image', 'kubernetes', 'MEDIUM', '[{"solution": "Ensure image exists in your Docker Hub repository with correct tag", "percentage": 93}, {"solution": "Use full image path: docker.io/username/imagename:tag", "percentage": 88}, {"solution": "Verify Docker Hub rate limits not exceeded, use authentication if needed", "percentage": 85}]'::jsonb, 'Docker image pushed to registry, kubeconfig set', 'Pod enters Running state, imagePullPolicy: Always succeeds', 'Typos in image name, non-existent tags, exceeding rate limits, missing authentication', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/54697970/kubernetes-error-message-imagepullbackoff-when-deploy-a-pod', 'admin:1764193768'),

('Delete pod stuck in CrashLoopBackOff state', 'kubernetes', 'MEDIUM', '[{"solution": "Delete single pod: kubectl delete pod <pod-name>", "percentage": 95}, {"solution": "Delete all CrashLoopBackOff pods: kubectl delete pod $(kubectl get pods | awk ''$3 == \"CrashLoopBackOff\" {print $1}'')", "percentage": 90}, {"solution": "Force delete stuck pod: kubectl delete pod <pod-name> --grace-period=0 --force", "percentage": 88}]'::jsonb, 'Pod in CrashLoopBackOff, kubectl access, pod manifest fixed', 'Pod successfully deleted, replacement pod created with fixed image', 'Not fixing underlying issue, attempting delete before fixing root cause', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/35453704/how-to-clear-crashloopbackoff', 'admin:1764193768'),

('kubectl config wrong context or missing kubeconfig', 'kubernetes', 'CRITICAL', '[{"solution": "Check current context: kubectl config get-contexts and kubectl config current-context", "percentage": 94}, {"solution": "Verify kubectl location: which kubectl to ensure system binary", "percentage": 91}, {"solution": "Override config: KUBECONFIG=.kube/config kubectl get nodes or --kubeconfig flag", "percentage": 89}]'::jsonb, 'kubeconfig file exists, kubectl installed', 'kubectl commands execute, nodes/pods visible, no connection refused errors', 'Wrong kubeconfig path, multiple kubectl installations, context not set', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/77968315/trouble-with-kubectl-connection-refused-error', 'admin:1764193768'),

('Pod evicted due to insufficient resources', 'kubernetes', 'MEDIUM', '[{"solution": "Check node resources: kubectl top nodes and kubectl describe node <nodename>", "percentage": 92}, {"solution": "Reduce pod resource requests or add more nodes to cluster", "percentage": 89}, {"solution": "Check eviction thresholds: kubelet configuration ephemeral-storage.evictionHard", "percentage": 85}]'::jsonb, 'Kubernetes cluster, metrics-server installed, kubectl access', 'Pod rescheduled successfully, node memory/disk available, pod running', 'Not monitoring resource usage, setting resource limits too low, insufficient cluster capacity', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/42169285/kubernetes-services-sometimes-unreachable', 'admin:1764193768');
