-- Socket IO Errors Mining - 20 entries
-- Mined from Stack Overflow for clauderepo knowledge base
-- Focus: WebSocket connection, CORS, version mismatch, polling, disconnect, timeout, reconnect, namespace, emit, auth, memory issues

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('Socket.IO error event not triggering on server - XHR request failed', 'websocket', 'HIGH', '[{"solution": "Listen for connect_error, connect_failed, disconnect events instead of error", "percentage": 95}, {"solution": "Understand that XHR errors come from browser, not socket.io itself", "percentage": 90}]'::jsonb, 'Socket.IO server and client', 'Error events properly caught and logged', 'Trying to catch browser XHR errors directly, expecting custom error handling', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/14649590/how-to-catch-socket-io-errors-and-prevent-them-from-showing-up-in-the-console', 'admin:1764225146'),

('Socket.IO socket won''t reconnect after error - reconnection not working', 'connection', 'HIGH', '[{"solution": "Add force new connection option: { ''force new connection'': true }", "percentage": 93}, {"solution": "Don''t set socket = null, recreate connection with socket.socket.connect()", "percentage": 85}]'::jsonb, 'Socket.IO client library', 'Socket successfully reconnects after disconnect', 'Expecting automatic reconnection without force new connection flag, nullifying socket object', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/13585712/socket-io-error-handling', 'admin:1764225146'),

('Socket.IO connect_failed event not triggered - namespace vs socket events', 'connection', 'MEDIUM', '[{"solution": "Get underlying socket from namespace: var socket = ns_news.socket", "percentage": 92}, {"solution": "Bind connect_failed to socket level, not namespace level", "percentage": 88}]'::jsonb, 'Socket.IO 0.9.x client', 'connect_failed event fires when connection fails', 'Binding socket-level events to namespace object instead of underlying socket', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/8588689/node-js-socket-io-client-connect-failed-connect-error-event', 'admin:1764225146'),

('Socket.IO polling transport timeout - net::ERR_TIMED_OUT on production', 'polling', 'HIGH', '[{"solution": "Set transports explicitly and remove http protocol: io.connect(hostname+port, {transports: [''websocket'', ''xhr-polling'']})", "percentage": 94}, {"solution": "Verify server is accessible on specified port from client location", "percentage": 89}]'::jsonb, 'Socket.IO server accessible on port', 'Polling fallback works when WebSocket unavailable', 'Using full http:// URL, not specifying transports, firewall blocking port', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/50757568/socket-io-error-on-server', 'admin:1764225146'),

('Socket.IO module not found error - Cannot find module socket.io', 'installation', 'MEDIUM', '[{"solution": "Run npm install from correct project root, not nested folder", "percentage": 96}, {"solution": "Delete node_modules and npm cache, reinstall: rm -rf node_modules && npm cache clean && npm install", "percentage": 94}]'::jsonb, 'Node.js and npm installed', 'socket.io module loads without error', 'Running from wrong directory, stale cache, wrong package name (socketio vs socket.io)', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/11266608/socket-io-error', 'admin:1764225146'),

('WebSocket handshake error 400 - unexpected response code with HTTPS/SSL', 'websocket', 'HIGH', '[{"solution": "Add SSLProxyEngine On and WebSocket rewrite rules to Apache: RewriteCond %{HTTP:UPGRADE} ^WebSocket$, RewriteRule .* ws://backend%{REQUEST_URI} [P]", "percentage": 96}, {"solution": "Enable mod_proxy and mod_rewrite Apache modules", "percentage": 93}]'::jsonb, 'Apache reverse proxy with SSL', 'WebSocket connections successful over wss://', 'Missing SSL proxy settings, no upgrade header rewrite, firewall blocking ws ports', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/53788936/socket-io-error-on-connection-error-during-websocket-handshake-unexpected-resp', 'admin:1764225146'),

('Socket.IO emit callback not supported - error on broadcast operator', 'emit', 'MEDIUM', '[{"solution": "Remove callback function from broadcast: io.to(room).emit(event, data) instead of io.to(room).emit(event, data, callback)", "percentage": 100}, {"solution": "Use callback only with single socket emit: socket.emit(event, data, callback)", "percentage": 97}]'::jsonb, 'Socket.IO with broadcast operations', 'Broadcast emits work without callbacks, room messages deliver', 'Trying to pass callback to broadcast or io.emit instead of socket.emit', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/67044502/how-to-handle-error-when-socket-io-emits-a-message', 'admin:1764225146'),

('Socket.IO CORS blocked - Cross-Origin Request Blocked in browser', 'cors', 'HIGH', '[{"solution": "Socket.IO v3+: const io = require(''socket.io'')(server, { cors: { origin: ''*'', methods: [''GET'', ''POST''] } })", "percentage": 98}, {"solution": "Socket.IO <v3: io.set(''origins'', ''*:*'') or io.origins(''*:*'')", "percentage": 95}]'::jsonb, 'Socket.IO server (v2.0+)', 'Clients connect without CORS errors from different origins', 'Using socketio package instead of socket.io, missing cors option, origin set to single string without credentials handling', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/24058157/socket-io-node-js-cross-origin-request-blocked', 'admin:1764225146'),

('Socket.IO CORS credentials error - Access-Control-Allow-Credentials must be true', 'cors', 'HIGH', '[{"solution": "Match credentials on both sides: server credentials: true, client withCredentials: true", "percentage": 97}, {"solution": "Handle CORS preflight with io.engine events for v4+: io.engine.on(''initial_headers'', (headers) => {})", "percentage": 91}]'::jsonb, 'Socket.IO v4+ with credentials', 'CORS requests succeed with proper credential handling', 'Mismatched credentials settings, using old CORS config format, not handling preflight headers', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/65566462/how-to-fix-this-cors-issue-in-socket-io', 'admin:1764225146'),

('Socket.IO unsupported protocol version - code 5 EIO3 vs EIO4 mismatch', 'version', 'HIGH', '[{"solution": "Set allowEIO3: true on server if client is older: const io = require(''socket.io'')({allowEIO3: true})", "percentage": 96}, {"solution": "Update socket.io-client to match server version: npm install socket.io-client@latest", "percentage": 94}]'::jsonb, 'Socket.IO server and client both present', 'Protocol handshake succeeds, connections establish', 'Client v1/v2 connecting to server v3, old cached libraries, mismatched package versions', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/66047026/socket-io-v3-unsupported-protocol-version-error', 'admin:1764225146'),

('Socket.IO unsupported version protocol from Python Flask - Engine.IO v3 mismatch', 'version', 'MEDIUM', '[{"solution": "Use compatible Flask-SocketIO versions: Flask-SocketIO==4.3.1, python-socketio==4.6.0, python-engineio==3.13.2", "percentage": 95}, {"solution": "Match JavaScript Socket.IO version to Python library version on server", "percentage": 92}]'::jsonb, 'Flask-SocketIO and Python socket.io', 'JavaScript client connects to Python Flask server without protocol errors', 'Version mismatch between Node/JavaScript and Python stacks, installing latest versions without compatibility check', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/66069215/the-client-is-using-an-unsupported-version-of-the-socket-io-or-engine-io-protoco', 'admin:1764225146'),

('Socket.IO disconnect event not working - event fired but can''t emit from server', 'disconnect', 'MEDIUM', '[{"solution": "Handle logic in server-side disconnect listener, not by emitting to client from server disconnect event", "percentage": 98}, {"solution": "Client can''t receive disconnect event from server - socket already lost connection", "percentage": 96}]'::jsonb, 'Socket.IO server-side disconnect handler', 'Clean disconnection, cleanup executed, no memory leaks', 'Emitting disconnect event from server, expecting client to receive it, race condition on client disconnect', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/17287330/socket-io-handling-disconnect-event', 'admin:1764225146'),

('Socket.IO disconnect - detecting disconnect reason not available', 'disconnect', 'MEDIUM', '[{"solution": "Access reason parameter in disconnect handler: socket.on(''disconnect'', (reason) => { console.log(reason) })", "percentage": 100}, {"solution": "Common disconnect reasons: server namespace disconnect, ping timeout, transport error, transport close", "percentage": 98}]'::jsonb, 'Socket.IO server v4+', 'Disconnect reasons logged and handled appropriately', 'Not checking disconnect reason parameter, assuming reason is always present', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/21173618/socket-io-detect-disconnect-reason', 'admin:1764225146'),

('Socket.IO client auto-disconnect - socket disconnects immediately after connect', 'disconnect', 'MEDIUM', '[{"solution": "Update socket.io-client version to match server version", "percentage": 96}, {"solution": "Check Socket.IO client is latest compatible version with server", "percentage": 93}]'::jsonb, 'Socket.IO client-server version match', 'Client stays connected, no automatic disconnects', 'Version mismatch between socket.io and socket.io-client, outdated client library', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/40991599/socket-io-automatically-disconnects-socket', 'admin:1764225146'),

('Socket.IO ping timeout - client disconnects due to missed PONG packet', 'timeout', 'HIGH', '[{"solution": "Configure pingInterval and pingTimeout: io.eio.pingInterval = 25000; io.eio.pingTimeout = 60000", "percentage": 97}, {"solution": "Or use older syntax: io.set(''heartbeat interval'', 5000); io.set(''heartbeat timeout'', 60000)", "percentage": 94}]'::jsonb, 'Socket.IO v2+', 'Ping/pong heartbeat works, connections remain stable', 'Default timeout too low for slow networks, no custom timeout configuration', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/30991326/socket-io-server-side-timeout-for-inactive-client-connection', 'admin:1764225146'),

('Socket.IO connection timeout slow - 2 minute delay detecting server down', 'timeout', 'MEDIUM', '[{"solution": "timeout only affects slow connections, connect_error fires immediately on refused/closed connections", "percentage": 94}, {"solution": "Reduce reconnectionDelay and reconnectionDelayMax to detect failures faster", "percentage": 91}]'::jsonb, 'Socket.IO client with custom timeout', 'Fast connection failure detection, appropriate reconnection timing', 'Expecting timeout to apply to all connection failures, misunderstanding timeout vs connect_error', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/32390268/socket-io-how-to-change-timeout-value-option-on-client-side', 'admin:1764225146'),

('Socket.IO reconnection not happening - disconnect called prevents reconnect', 'reconnect', 'HIGH', '[{"solution": "Use socket.socket.connect() for reconnection after explicit disconnect, not io.connect() again", "percentage": 97}, {"solution": "Or avoid explicit disconnect() and rely on Socket.IO auto-reconnect", "percentage": 93}]'::jsonb, 'Socket.IO client v1+', 'Reconnection succeeds after manual disconnect', 'Creating new io.connect() after disconnect, not using socket.socket.connect()', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/10437584/socket-io-reconnect', 'admin:1764225146'),

('Socket.IO reconnect event doesn''t exist - No reconnect event fired', 'reconnect', 'MEDIUM', '[{"solution": "Use connect event instead: socket.on(''connect'', () => { /* fires on initial and reconnect */ })", "percentage": 100}, {"solution": "Or detect reconnect attempt with reconnecting, reconnect_error, connect_error events", "percentage": 97}]'::jsonb, 'Socket.IO client library', 'Reconnection detected via connect or reconnecting events', 'Listening for non-existent reconnect event, not understanding connect fires on every connection including reconnects', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/36827974/how-to-detect-reconnect-event-in-socket-io', 'admin:1764225146'),

('Socket.IO namespace path confusion - can''t connect with custom path and namespace', 'namespace', 'MEDIUM', '[{"solution": "Separate namespace from path: var socket = io(''http://example.com/namespace-name'', {path: ''/custom/path''})", "percentage": 98}, {"solution": "Server must also set path: const io = require(''socket.io'')(server, {path: ''/custom/path''})", "percentage": 96}]'::jsonb, 'Socket.IO with custom path and namespaces', 'Custom path and namespace both work correctly', 'Mixing namespace and path in URL, not setting path on server side, not using separate options', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/29511404/connect-to-socket-io-server-with-specific-path-and-namespace', 'admin:1764225146'),

('Socket.IO error event reserved name - custom error event won''t work', 'emit', 'MEDIUM', '[{"solution": "Use custom event name instead of ''error'': socket.emit(''my-error'', data) on server", "percentage": 100}, {"solution": "Listen to custom event on client: socket.on(''my-error'', (data) => {})", "percentage": 99}]'::jsonb, 'Socket.IO client and server', 'Custom error events emit and receive properly', 'Using ''error'' as event name which is reserved in Socket.IO', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/33872052/how-to-emit-error-to-be-possible-catch-it-on-error-handler-on-client-side', 'admin:1764225146'),

('Socket.IO emit with callback fails silently - no error when server doesn''t respond', 'emit', 'HIGH', '[{"solution": "Implement timeout for callbacks: set timeout promise to detect no-response", "percentage": 91}, {"solution": "Ensure socket.emit callback is actually reached on server side with proper event listener", "percentage": 94}]'::jsonb, 'Socket.IO with emit callbacks', 'Callbacks execute or timeout, no silent failures', 'Server event handler not implemented, callback never invoked, no timeout logic for callback detection', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/42291247/socket-emit-error-handling-with-socket-io', 'admin:1764225146'),

('Socket.IO JWT authentication - verify token during connection handshake', 'auth', 'HIGH', '[{"solution": "Pass JWT via query: var socket = io(url, {query: {token: jwt_token}})", "percentage": 94}, {"solution": "Or modern approach with auth option: var socket = io(url, {auth: {token: jwt_token}})", "percentage": 97}]'::jsonb, 'Socket.IO v3+ with JWT tokens', 'Authenticated connections allowed, unauthorized rejected', 'Not verifying token, passing token as plaintext, wrong secret key for JWT verification', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/36788831/authenticating-socket-io-connections-using-jwt', 'admin:1764225146'),

('Socket.IO memory leak on rapid reconnect - event listeners not cleaned up', 'memory', 'MEDIUM', '[{"solution": "Explicitly remove listeners on disconnect: socket.removeAllListeners() in disconnect handler", "percentage": 88}, {"solution": "Force garbage collection if needed: node --expose-gc and call global.gc() on intervals", "percentage": 80}]'::jsonb, 'Socket.IO with many connected clients', 'Memory stable with many connections, no listener leak warnings', 'Not removing listeners on disconnect, not setting socket to null, relying only on V8 garbage collection', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/30766753/nodejs-socket-io-simple-code-memory-leak', 'admin:1764225146'),

('Socket.IO EventEmitter max listeners warning - too many listeners added on fast refresh', 'memory', 'MEDIUM', '[{"solution": "Set max listeners globally: require(''events'').EventEmitter.prototype._maxListeners = 100", "percentage": 93}, {"solution": "Or for socket.io instance: io.setMaxListeners(0)", "percentage": 95}]'::jsonb, 'Socket.IO with rapid client reconnections', 'No EventEmitter max listeners warning, handles many listeners', 'Not increasing max listeners limit, rapid page refreshes causing listener accumulation', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/16056379/node-js-socket-io-memory-leak-and-max-listener', 'admin:1764225146');
