-- Mining run: Flask Errors - 10 entries
-- Date: 2025-11-26
-- Source: Stack Overflow

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Custom exception with @app.errorhandler decorator', 'flask', 'HIGH', '[{"solution": "Create custom exception class and register with @app.errorhandler(CustomException) decorator. Return jsonified error response with status code", "percentage": 98}, {"solution": "Use error.to_dict() method to convert exception to dictionary for JSON serialization", "percentage": 95}]'::jsonb, 'Flask app instance, custom exception class definition', 'Custom exception caught and JSON response returned with correct status code', 'Not setting status_code attribute on custom exception, forgetting to register errorhandler decorator', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/60324360/what-is-best-practice-for-flask-error-handling', 'admin:1764210382');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Global error handler for all exceptions and HTTP errors', 'flask', 'HIGH', '[{"solution": "@app.errorhandler(Exception) handles all uncaught exceptions, check isinstance(e, HTTPException) to preserve status codes", "percentage": 96}, {"solution": "Use werkzeug.exceptions default_exceptions loop to register handler for all HTTP error codes", "percentage": 90}, {"solution": "Set app.config[''TRAP_HTTP_EXCEPTIONS'']=True to handle HTTPException with exception class handlers", "percentage": 88}]'::jsonb, 'Flask app instance, werkzeug.exceptions imported', 'All exceptions caught, JSON responses returned for both HTTP and custom exceptions', 'Not handling HTTPException separately, using wrong exception class hierarchy', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/29332056/global-error-handler-for-any-exception', 'admin:1764210382');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Raise custom exceptions instead of returning error tuples', 'flask', 'HIGH', '[{"solution": "Use @app.errorhandler() with custom exception class instead of returning (error, code) tuples from business logic", "percentage": 97}, {"solution": "Allows clean separation: business logic raises exceptions, error handler converts to HTTP responses", "percentage": 95}]'::jsonb, 'Flask app, business logic functions, exception handlers registered', 'Custom exceptions caught at endpoint level, clean error propagation through function calls', 'Returning tuples from every function level, mixing error handling with business logic', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/12630224/returning-api-error-messages-with-python-and-flask', 'admin:1764210382');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Return 400/500 responses with abort() vs tuple vs Response object', 'flask', 'MEDIUM', '[{"solution": "Simple tuple return: return (''message'', 400) - cleanest for basic cases", "percentage": 92}, {"solution": "abort(400, ''message'') - raises HTTPException, must have errorhandler to catch", "percentage": 88}, {"solution": "Response object: return Response(''message'', status=400) - explicit, good for custom headers", "percentage": 85}]'::jsonb, 'Flask route handler, desired status code', 'Appropriate HTTP status code returned to client with error message', 'Using abort() without errorhandler, mixing response methods inconsistently', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/57664997/how-to-return-400-bad-request-on-flask', 'admin:1764210382');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Handle all HTTP errors with single errorhandler instead of per-code decorators', 'flask', 'MEDIUM', '[{"solution": "@app.errorhandler(HTTPException) catches all HTTP errors from werkzeug.exceptions", "percentage": 94}, {"solution": "Use app.error_handler_spec[None][code] = handler_function to programmatically register for multiple codes", "percentage": 82}]'::jsonb, 'Flask app, werkzeug.exceptions.HTTPException', 'All HTTP error codes handled by single function without repetitive decorators', 'Registering handler with numeric codes instead of exception classes', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/27760113/how-can-i-implement-a-custom-error-handler-for-all-http-errors-in-flask', 'admin:1764210382');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Debug mode not showing errors in browser with WSGI', 'flask', 'MEDIUM', '[{"solution": "app.debug = True only works when running Flask directly, not with WSGI servers (Gunicorn, mod_wsgi)", "percentage": 97}, {"solution": "For WSGI production, remove debug mode and use proper logging/error handlers instead", "percentage": 95}]'::jsonb, 'Flask app config, WSGI server environment', 'Errors visible in development with debug=True, proper logging in production', 'Expecting debug mode to work with WSGI servers, leaving debug=True in production', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/20396253/how-to-show-all-errors-in-the-browser-on-flask-framework', 'admin:1764210382');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Custom error templates not loaded from separate errors module', 'flask', 'LOW', '[{"solution": "Place error templates (404.html, 500.html) in main templates/ folder, not nested in app submodules", "percentage": 93}, {"solution": "Register errorhandlers in main app init, not in separate blueprint modules", "percentage": 89}]'::jsonb, 'Flask app structure, template loader configuration', 'Custom error templates rendered instead of default Flask error pages', 'Templates in nested app modules, errorhandlers registered in wrong module scope', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/15831364/flask-error-handler', 'admin:1764210382');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Flask-RESTful custom exception handler not triggered', 'flask', 'MEDIUM', '[{"solution": "Flask-RESTful overrides handle_error(). Create custom Api class extending _Api and override error_router() method", "percentage": 87}, {"solution": "Let Flask-RESTful handle HTTPException, pass other exceptions to default Flask handler via original_handler()", "percentage": 85}]'::jsonb, 'Flask-RESTful Api, custom exception class', 'Custom error handler executed for non-HTTP exceptions with correct status code', 'Using vanilla Flask errorhandler with Flask-RESTful routes, not overriding error_router', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/56049481/why-is-my-flask-error-handler-not-being-called', 'admin:1764210382');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('500 error handler not triggered for uncaught exceptions in debug mode', 'flask', 'MEDIUM', '[{"solution": "Debug mode=True re-raises exceptions immediately, disabling errorhandler. Set debug=False to enable 500 handler", "percentage": 96}, {"solution": "Explicitly call abort(500) or raise exception in try block to test handler", "percentage": 92}]'::jsonb, 'Flask app in debug mode, uncaught exception', 'Debug mode disabled, 500 errorhandler catches uncaught exceptions', 'Running with debug=True when expecting errorhandler to trigger', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/14993318/catching-a-500-server-error-in-flask', 'admin:1764210382');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Errors not logged in production with Gunicorn and journalctl', 'flask', 'HIGH', '[{"solution": "@app.errorhandler(Exception) with logging.exception(e) logs full traceback to stderr/journalctl", "percentage": 98}, {"solution": "Configure Flask logger with app.logger.exception(e) for application-level logging", "percentage": 95}]'::jsonb, 'Flask app, logging module, production environment', 'Full exception tracebacks visible in journalctl or server logs', 'Relying on debug mode in production, not configuring error handlers with logging', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/64667539/flask-access-500-internal-server-errors-in-production', 'admin:1764210382');
