INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('QueryFailedError: column reference is ambiguous', 'orm', 'HIGH', '[{"solution": "Use explicit table aliases in JOIN queries: SELECT u.id FROM user u JOIN post p ON u.id = p.userId", "percentage": 92}, {"solution": "Specify which table column to select when multiple tables have the same column: SELECT users.id instead of just id", "percentage": 88}]'::jsonb, 'PostgreSQL, TypeORM 0.2+', 'Query executes without ambiguity error', 'Joining tables without explicit column qualification, using ambiguous column names', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/49124626/typeorm-queryfailederror-postgresql', 'admin:1764226243'),

('QueryFailedError: relation does not exist', 'orm', 'HIGH', '[{"solution": "Ensure synchronize: true is set in TypeORM config to auto-create schema", "percentage": 95}, {"solution": "Run migrations before querying: typeorm migration:run", "percentage": 90}, {"solution": "Check entity is registered in connection entities array", "percentage": 85}]'::jsonb, 'TypeORM connection configured, entities defined', 'Database tables created and queries execute', 'Forgetting to sync schema, not running migrations, missing entity registration', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/66909895/typeorm-queryfailederror-relation-does-not-exist', 'admin:1764226243'),

('QueryFailedError: Table already exists on MySQL synchronize', 'orm', 'MEDIUM', '[{"solution": "Use lowercase entity names: @Entity({ name: ''users'' }) instead of @Entity({ name: ''Users'' })", "percentage": 88}, {"solution": "Change database name to lowercase in config to match created schema", "percentage": 85}]'::jsonb, 'MySQL database, TypeORM NestJS module', 'Application starts without table exists error', 'Using uppercase entity names, mismatched database name case', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/62434734/typeorm-throws-queryfailederror-table-already-exists-on-mysql-when-synchronize-i', 'admin:1764226243'),

('QueryFailedError: ER_NO_DEFAULT_FOR_FIELD: Field doesn''t have default value', 'orm', 'MEDIUM', '[{"solution": "Add nullable: true to optional columns: @Column({ nullable: true })", "percentage": 91}, {"solution": "Provide default values for required fields: @Column({ default: null })", "percentage": 87}, {"solution": "Run migration after updating entity schema", "percentage": 90}]'::jsonb, 'MySQL database, TypeORM entities', 'INSERT queries execute without field default error', 'Not marking optional fields as nullable, not running migrations after schema changes', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/68722371/typeorm-evokes-error-in-findone-query-queryfailederror-er-no-default-for-fiel', 'admin:1764226243'),

('QueryFailedError: duplicate key value violates unique constraint', 'orm', 'HIGH', '[{"solution": "Check for duplicate @Index decorators on same column", "percentage": 89}, {"solution": "Delete dist/ folder and rebuild to clear cached metadata", "percentage": 85}, {"solution": "Remove duplicate index definition @Index and @Column unique: true", "percentage": 90}]'::jsonb, 'PostgreSQL, TypeORM with indexes', 'Inserts execute without constraint violation', 'Defining same index twice, stale compiled artifacts', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/67756722/receiving-queryfailederror-duplicate-key-value-violates-unique-constraint-pg', 'admin:1764226243'),

('QueryFailedError: invalid input syntax for type uuid', 'orm', 'MEDIUM', '[{"solution": "Await async operations before query execution", "percentage": 93}, {"solution": "Validate UUID format before database operations", "percentage": 88}, {"solution": "Use proper UUID column type: @PrimaryGeneratedColumn(''uuid'')", "percentage": 91}]'::jsonb, 'PostgreSQL, TypeORM entities with UUID', 'Queries execute with valid UUID parameters', 'Not awaiting async promises, passing invalid UUID strings, missing UUID type declaration', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/67052678/custom-typeorm-errors-in-nestjs-service', 'admin:1764226243'),

('QueryFailedError: ERROR: duplicate entry for key', 'orm', 'HIGH', '[{"solution": "Handle errno: 1062 specifically in error filter", "percentage": 91}, {"solution": "Add unique: true constraint to column @Column({ unique: true })", "percentage": 89}, {"solution": "Check for duplicate values before insert with pre-check query", "percentage": 75}]'::jsonb, 'MySQL database, TypeORM repository', 'Duplicate inserts properly rejected and logged', 'Not parsing error codes, missing unique constraints', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/78562446/error-handling-with-typeorm-sql-in-nestjs', 'admin:1764226243'),

('MissingDriverError: Wrong driver undefined given', 'orm', 'HIGH', '[{"solution": "Install database driver: npm install mysql2 / pg / oracle", "percentage": 94}, {"solution": "Explicitly set type in TypeORM config: type: ''postgres''", "percentage": 92}, {"solution": "Load environment variables before TypeORM initialization", "percentage": 88}]'::jsonb, 'TypeORM connection config, Node.js environment', 'Database connection establishes successfully', 'Missing driver installation, undefined config type, env vars not loaded', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/45950473/missingdrivererror-when-type-is-oracle-using-typeorm', 'admin:1764226243'),

('TypeORM version conflict: @nestjs/typeorm peer dependency', 'orm', 'MEDIUM', '[{"solution": "Downgrade typeorm to 0.2.45: npm install typeorm@0.2.45", "percentage": 91}, {"solution": "Upgrade @nestjs/typeorm to version matching typeorm 0.3+", "percentage": 88}, {"solution": "Use --legacy-peer-deps flag: npm install --legacy-peer-deps", "percentage": 85}]'::jsonb, 'NestJS project, npm 8.11.0+', 'npm install completes without ERESOLVE error', 'Mixing incompatible typeorm versions, ignoring peer dependency warnings', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/73058252/why-i-receive-error-message-while-install-typeorm', 'admin:1764226243'),

('ColumnTypeUndefinedError: Column type is not defined', 'orm', 'MEDIUM', '[{"solution": "Enable emitDecoratorMetadata in tsconfig.json: ''emitDecoratorMetadata'': true", "percentage": 93}, {"solution": "Ensure reflect-metadata is imported before entities: import ''reflect-metadata''", "percentage": 92}, {"solution": "Specify explicit column type: @Column({ type: ''varchar'', length: 255 })", "percentage": 89}]'::jsonb, 'TypeScript, TypeORM decorators', 'Columns properly typed without metadata errors', 'Missing reflect-metadata import, emitDecoratorMetadata disabled, implicit types', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/66428004/columntypeundefinederror-in-typeorm', 'admin:1764226243'),

('EntityMetadataNotFound: Entity metadata not found for relationship', 'orm', 'MEDIUM', '[{"solution": "Register all entities in connection options: entities: [User, Post, etc]", "percentage": 94}, {"solution": "Add @Entity() decorator to related entities", "percentage": 92}, {"solution": "Ensure entities are imported before connection creation", "percentage": 90}]'::jsonb, 'TypeORM NestJS, multiple entities', 'Relationships resolve without metadata errors', 'Missing entity registration, missing @Entity decorator, import order issues', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/67210764/typeorm-entity-metadata-not-found', 'admin:1764226243'),

('AlreadyHasActiveConnectionError: Cannot create new connection named default', 'orm', 'HIGH', '[{"solution": "Set keepConnectionAlive: true in TypeORM config for serverless", "percentage": 89}, {"solution": "Name connection explicitly: name: ''custom_name'' instead of default", "percentage": 92}, {"solution": "Use getConnection with named connection: getConnection(''custom_name'')", "percentage": 88}]'::jsonb, 'NestJS/TypeORM on AWS Lambda, concurrent execution', 'Application handles multiple concurrent requests', 'Default connection reuse issues, concurrent lambda instantiation', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/72731740/nest-js-typeorm-throws-alreadyhasactiveconnectionerror-error', 'admin:1764226243'),

('Migration error: Unable to open file Cannot use import statement', 'orm', 'MEDIUM', '[{"solution": "Use DataSource file path with -d flag: typeorm migration:run -d src/data-source.ts", "percentage": 90}, {"solution": "Build TypeScript to dist folder before migrations: npx tsc", "percentage": 91}, {"solution": "Use ts-node-commonjs: npx typeorm-ts-node-commonjs migration:run", "percentage": 87}]'::jsonb, 'TypeORM 0.3.6+, TypeScript migrations', 'Migrations execute without import statement errors', 'Using .ts files without transpilation, wrong -d path syntax, missing build step', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/72580969/nestjs-typeorm-error-during-migration-run-unable-to-open-file', 'admin:1764226243'),

('Connection "default" was not found', 'orm', 'MEDIUM', '[{"solution": "Call getRepository inside async function after connection established", "percentage": 93}, {"solution": "Use getConnectionManager().get(''default'') for named connections", "percentage": 89}, {"solution": "Ensure TypeOrmModule is imported before using repositories", "percentage": 91}]'::jsonb, 'NestJS TypeORM, repository initialization', 'Repositories available after connection opens', 'Calling getRepository at module load time, connection not ready', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/49794140/connection-default-was-not-found-with-typeorm', 'admin:1764226243'),

('No connection options were found in any orm configuration files', 'orm', 'MEDIUM', '[{"solution": "Create ormconfig.json or ormconfig.ts in project root", "percentage": 94}, {"solution": "Use lowercase filename: ormconfig (not OrmConfig)", "percentage": 92}, {"solution": "Configure via environment variables with TYPEORM_ prefix", "percentage": 88}]'::jsonb, 'TypeORM standalone, configuration files', 'Connection options loaded from config file', 'Missing ormconfig file, incorrect filename casing, config path issues', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/65513965/typeorm-error-no-connection-options-were-found-in-any-orm-configuration-files', 'admin:1764226243'),

('EntityColumnNotFound: No entity column found in embedded entity', 'orm', 'LOW', '[{"solution": "Use save() instead of update() for embedded OneToMany relations", "percentage": 93}, {"solution": "Remove OneToMany from embedded entity, keep on main entity", "percentage": 87}, {"solution": "Use inverse side of relation only: project => project.context.physicalPresets", "percentage": 85}]'::jsonb, 'TypeORM embedded entities, relationships', 'Embedded entities update without column not found errors', 'OneToMany in embedded entities, using update() instead of save()', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/54904349/typeorm-one-to-many-entitycolumnnotfound-no-entity-column-context-physicalp', 'admin:1764226243'),

('RepositoryNotFoundError: Repository not registered', 'orm', 'MEDIUM', '[{"solution": "Import TypeOrmModule.forFeature([Entity]) in feature module", "percentage": 94}, {"solution": "Add @InjectRepository(Entity) in service constructor", "percentage": 93}, {"solution": "Register entity in entities array of TypeOrmModule.forRoot", "percentage": 91}]'::jsonb, 'NestJS modules, TypeORM repositories', 'Repositories injectable without not found errors', 'Missing forFeature registration, wrong module import, entity not registered', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/58993405/how-can-i-handle-typeorm-error-in-nestjs', 'admin:1764226243'),

('QueryFailedError when raw SQL with PostgreSQL syntax', 'orm', 'MEDIUM', '[{"solution": "Enable logging: true in connection options to debug queries", "percentage": 90}, {"solution": "Test raw SQL directly in psql before using in TypeORM", "percentage": 92}, {"solution": "Use query parameters instead of string interpolation: query.setParameters({ id: 1 })", "percentage": 89}]'::jsonb, 'PostgreSQL, TypeORM raw queries', 'Raw SQL queries execute correctly', 'Unescaped string interpolation, invalid PostgreSQL syntax, missing query parameters', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/54392659/typeorm-queryfailederror-when-using-raw-sql-with-postgresql', 'admin:1764226243'),

('UnhandledPromiseRejectionWarning: QueryFailedError from async operation', 'orm', 'HIGH', '[{"solution": "Add process.on(''unhandledRejection'', ...) to catch unhandled promises", "percentage": 88}, {"solution": "Wrap database operations in try/catch blocks", "percentage": 94}, {"solution": "Use @Catch(QueryFailedError) exception filter in NestJS", "percentage": 91}]'::jsonb, 'Node.js, TypeORM async/await', 'Promise rejections handled gracefully', 'Missing async/await, no error handlers, unhandled promise chains', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/62327213/typeorm-stack-trace-not-showing-origin-of-error-in-my-code', 'admin:1764226243');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('TypeORM No changes in database schema were found cannot generate migration', 'orm', 'MEDIUM', '[{"solution": "Ensure entities have @Entity() decorator and are registered", "percentage": 91}, {"solution": "Check synchronize: true is set to auto-detect changes", "percentage": 89}, {"solution": "Verify entity changes are different from database schema", "percentage": 87}]'::jsonb, 'TypeORM migration system, database schema', 'Migrations generated from entity changes', 'Entity not properly decorated, no actual schema changes, entities not registered', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/60834678/typeorm-migrations-no-changes-were-found', 'admin:1764226243');
