INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('Cannot find name ''Bun'' when using Bun singleton in VS Code', 'typescript', 'HIGH', '[{"solution": "Install bun-types as devDependency: bun add -d bun-types", "percentage": 95}, {"solution": "Add bun-types to tsconfig.json compilerOptions.types array", "percentage": 92}]'::jsonb, 'Bun runtime, TypeScript project, VS Code', 'No TS2304 error, Bun singleton has autocompletion', 'Forgetting to add types to tsconfig.json, using wrong package name', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/77339206/bun-in-vs-code-error-cannot-find-name-bun-when-using-the-bun-singleton', 'admin:1764227374'),

('Failed due to error: bunsh: No such file or directory', 'runtime', 'HIGH', '[{"solution": "Check for non-ASCII characters in project folder name, rename to English characters only", "percentage": 88}, {"solution": "Ensure Bun can find the shell executable in PATH", "percentage": 85}]'::jsonb, 'Bun installed, package.json with scripts', 'Scripts execute without bunsh errors', 'Using non-English folder names, missing PATH setup', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/78324016/error-failed-due-to-error-bunsh-no-such-file-or-directory-running-bun-dev', 'admin:1764227374'),

('Could not find bin metadata file - Bun failed to remap bin', 'installation', 'MEDIUM', '[{"solution": "Run bun install --force to rebuild cache and bin metadata", "percentage": 90}, {"solution": "Clear Bun cache directory and reinstall", "percentage": 85}]'::jsonb, 'Bun installed, corrupted node_modules or cache', 'bun install completes without EBUSY or EPERM errors', 'Not running with sufficient permissions, cross-disk installation issues', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/79290306/issues-setting-up-shadcn-with-next-js-bun-cache-errors-and-installation-failure', 'admin:1764227374'),

('Command bun not found in PATH on WSL/Windows', 'installation', 'MEDIUM', '[{"solution": "Add BUN_INSTALL to .bashrc: export BUN_INSTALL=$HOME/.bun && export PATH=$BUN_INSTALL/bin:$PATH", "percentage": 92}, {"solution": "Run source ~/.bashrc or restart shell after adding exports", "percentage": 90}]'::jsonb, 'Bun installed via curl, WSL2 (not WSL1)', 'bun --version returns version number', 'Running WSL1 instead of WSL2, not sourcing bashrc', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/72937512/bun-not-found-error-in-windows-with-wsl', 'admin:1764227374'),

('Interpreter bun is NOT AVAILABLE in PATH with PM2', 'runtime', 'LOW', '[{"solution": "Downgrade PM2 to version 5.3.0 if using 5.3.1+", "percentage": 88}, {"solution": "Use node interpreter in PM2 config instead of ts-node-dev with bun", "percentage": 85}]'::jsonb, 'PM2 v5.3.1+, TypeScript project, Bun runtime', 'PM2 starts process without interpreter errors', 'Using incompatible PM2 versions, missing environment setup', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/77887644/error-when-using-pm2-interpreter-bun-is-not-available-in-path', 'admin:1764227374'),

('Failed to initialize network thread: SystemOutdated', 'network', 'MEDIUM', '[{"solution": "Update WSL to latest version: wsl --update", "percentage": 93}, {"solution": "Restart WSL VM: wsl --shutdown", "percentage": 91}, {"solution": "Use --backend=copyfile flag for installations: bun install --backend=copyfile", "percentage": 80}]'::jsonb, 'WSL2, Bun runtime, network operations', 'Network requests work without SystemOutdated errors', 'Running WSL1, outdated WSL version, filesystem issues', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/72902550/multiple-errors-when-running-bun-via-wsl', 'admin:1764227374'),

('Module not found: Can''t resolve ''fs'' in Next.js with Bun compiler', 'module-resolution', 'MEDIUM', '[{"solution": "Use microservice for filesystem operations, expose via API instead of direct fs import", "percentage": 85}, {"solution": "Configure webpack/Bun bundler to externalize fs module", "percentage": 78}]'::jsonb, 'Next.js 14+, Bun compiler, server-side module imports', 'PDF parsing works without fs resolution errors', 'Mixing browser and server-side imports, wrong bundler config', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/79415932/module-not-found-cant-resolve-fs-in-next-js-application-bun-compiler', 'admin:1764227374'),

('Error when importing local package made with Bun - Cannot resolve', 'module-resolution', 'MEDIUM', '[{"solution": "Ensure build step runs before linking: bun run build && bun link", "percentage": 87}, {"solution": "Check that dist files exist with correct exports in package.json main/module fields", "percentage": 85}]'::jsonb, 'Bun project, local packages, monorepo setup', 'bun link succeeds and imports resolve correctly', 'Skipping build step, wrong main/module export paths', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/77857061/error-when-importing-a-local-package-made-with-bun', 'admin:1764227374'),

('Twilio client hangs Promise never resolves with Bun', 'runtime', 'LOW', '[{"solution": "Use alternative HTTP client like fetch instead of axios in Bun", "percentage": 80}, {"solution": "Keep monitoring Bun GitHub for HTTP/Promise handling fixes", "percentage": 75}]'::jsonb, 'Bun runtime, Twilio SDK, Elysia.js', 'Twilio verification completes and returns result', 'Using node-only HTTP clients, Promise issues with Bun internals', 0.78, 'haiku', NOW(), 'https://stackoverflow.com/questions/78362644/twilio-client-does-not-resolve-when-using-with-bun', 'admin:1764227374'),

('WebSocket packet loss - Bun drops packets above 1MB', 'websocket', 'MEDIUM', '[{"solution": "Increase backpressureLimit in websocket config: backpressureLimit: 2 * 1024 * 1024 (or higher)", "percentage": 92}, {"solution": "Check Bun WebSocket backpressure documentation for limits", "percentage": 88}]'::jsonb, 'Bun.serve() WebSocket, high-volume packet transmission', 'All packets delivered without packet loss', 'Using default 1MB backpressure limit for large messages', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/79261451/bun-js-packet-losses-in-websocket', 'admin:1764227374'),

('FFI complex return types not supported - cannot read struct pointers', 'ffi', 'LOW', '[{"solution": "Create getter/setter functions in C/Rust that return primitive types", "percentage": 90}, {"solution": "Use DataView.read() with manual offset calculations for struct field access", "percentage": 75}]'::jsonb, 'Bun FFI, Rust/C structs, complex return types', 'C functions return primitive types that FFI can handle', 'Trying to return struct pointers directly from FFI', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/77254006/read-from-complex-return-types-using-bunffi', 'admin:1764227374'),

('Symbol napi_register_module_v1 not found in native module', 'native-module', 'MEDIUM', '[{"solution": "Use pure JavaScript implementation instead of bcrypt native module when possible", "percentage": 80}, {"solution": "Use node:crypto or alternative crypto library compatible with Bun", "percentage": 85}]'::jsonb, 'Bun runtime, bcrypt or other NAPI modules, Node.js code', 'Crypto operations work without NAPI symbol errors', 'Using Node-only NAPI modules that require node-gyp', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/78805002/bun-symbol-napi-register-module-v1-not-found-in-native-module-is-this-a-node', 'admin:1764227374'),

('Could not find native build for platform - Couchbase with Bun', 'native-module', 'LOW', '[{"solution": "Use Docker builder from official Bun image (oven/bun)", "percentage": 88}, {"solution": "Pre-compile native modules for your target architecture before build", "percentage": 82}]'::jsonb, 'Bun Docker build, native modules like Couchbase, ARM64 target', 'Docker build completes and binary runs on target platform', 'Cross-platform native module mismatches, missing prebuilds', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/79610677/could-not-find-native-build-for-couchbase-with-bun', 'admin:1764227374'),

('EINVAL: Failed to replace old lockfile with new lockfile on disk', 'installation', 'MEDIUM', '[{"solution": "Manually delete bun.lockb file: rm bun.lockb", "percentage": 85}, {"solution": "Run bun install again to regenerate lockfile", "percentage": 90}, {"solution": "Ensure project is on same disk as Bun installation (avoid cross-disk)", "percentage": 80}]'::jsonb, 'Bun project, file permissions, disk access', 'bun install completes without EINVAL errors', 'Working on different disk than Bun install, permission issues, file locked by editor', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/78413400/bun-lockfile-issue', 'admin:1764227374'),

('Invalid NPM Lockfile error when upgrading Bun', 'installation', 'LOW', '[{"solution": "Clear npm cache: npm cache clean -f", "percentage": 80}, {"solution": "Delete package-lock.json and bun.lockb, run bun install fresh", "percentage": 85}]'::jsonb, 'Bun upgrade, npm compatibility, package-lock.json', 'bun install completes without lockfile validation errors', 'Mixing npm and Bun lockfiles, corrupted cache', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/78705386/global-installation-of-packages-not-working-in-bun', 'admin:1764227374'),

('Bun not supported natively on Windows (pre-1.0)', 'platform', 'LOW', '[{"solution": "Use WSL2 (Windows Subsystem for Linux 2) to run Bun", "percentage": 95}, {"solution": "Update to latest Bun version (now has Windows support)", "percentage": 92}]'::jsonb, 'Windows OS, Bun < 1.0 (older versions)', 'Bun runs natively on Windows or via WSL2', 'Using old Bun version, running WSL1', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/77102635/bun-latest-version-is-not-getting-installed-in-my-windows', 'admin:1764227374'),

('Error spawning process with Bun.spawn - ReadableStream issues', 'runtime', 'MEDIUM', '[{"solution": "Use for await loop to read from proc.stdout instead of .on() events", "percentage": 90}, {"solution": "Decode chunks with TextDecoder: new TextDecoder().decode(chunk)", "percentage": 88}]'::jsonb, 'Bun runtime, subprocess spawning, stream reading', 'Process output reads in real-time without hanging', 'Using Node.js-style .on() callbacks instead of async iteration', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/74341249/bun-how-to-get-output-from-spawn', 'admin:1764227374'),

('bun start command repeats infinitely - echoes command repeatedly', 'runtime', 'LOW', '[{"solution": "Change package.json start script from bun start to bun run: bun run dist/index.js", "percentage": 95}]'::jsonb, 'Bun project, package.json scripts, build output', 'bun start executes once without infinite loops', 'Using bun start instead of bun run for file execution', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/79486100/having-a-challenge-starting-my-bun-project-after-running-build-command', 'admin:1764227374'),

('bun run does nothing - just echoes command to stdout', 'runtime', 'LOW', '[{"solution": "Ensure script exists in package.json scripts section with proper definition", "percentage": 85}, {"solution": "Use bun run path/to/file.ts for direct file execution instead of script names", "percentage": 90}]'::jsonb, 'Bun runtime, package.json, tauri or other build tools', 'bun run executes script without echoing to stdout', 'Missing script definition in package.json, incorrect syntax', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/77806748/bun-run-does-nothing-but-echo-the-command', 'admin:1764227374');
