-- Auth errors mining batch: General Auth issues from multiple ORMs and services

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('User is not authorized to perform: dynamodb:PutItem on resource', 'general', 'HIGH', '[{"solution": "Check IAM policy matches the exact table name and ARN in your code. Verify Resource field contains the correct table ARN: arn:aws:dynamodb:region:account:table/TableName", "percentage": 95}, {"solution": "Add missing table ARN to the Resource list in IAM policy if accessing multiple tables", "percentage": 85}]'::jsonb, 'AWS IAM console access, DynamoDB table name, Lambda function role', 'Lambda function successfully writes to DynamoDB table without AccessDeniedException', 'Typos in table names between code and policy, confusing table name with ARN', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/34784804', 'admin:1764191658'),

('User is not authorized to perform: dynamodb:Query on resource', 'general', 'HIGH', '[{"solution": "Add index ARN to IAM policy Resource list: arn:aws:dynamodb:region:account:table/TableName/index/* to cover all global secondary indexes", "percentage": 96}, {"solution": "Verify the role assumption is correct and the AssumedRole has proper permissions attached", "percentage": 88}]'::jsonb, 'AWS IAM policy editor, DynamoDB table with GSI, Serverless framework config', 'Query against GSI returns results without AccessDeniedException', 'Forgetting to include index/* wildcard, GSI permissions assumed to be covered by table permissions', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/51537795', 'admin:1764191658'),

('User: arn:aws:sts::xxx:assumed-role/Cognito_SampleUnauth_Role/CognitoIdentity is not authorized to perform: dynamodb:DescribeTable', 'general', 'HIGH', '[{"solution": "Attach appropriate DynamoDB policy to the Cognito UnAuth role via IAM console. Include actions: DescribeTable, GetItem, Query, Scan", "percentage": 94}, {"solution": "Use AWS Mobile Hub to auto-generate policies for Cognito Identity Pool roles with correct permissions", "percentage": 82}]'::jsonb, 'Cognito Identity Pool setup, IAM console access, DynamoDB table ARN', 'Mobile app successfully describes and queries DynamoDB table', 'Assuming Cognito setup auto-grants DynamoDB permissions, not attaching policy to UnAuth role', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/44691817', 'admin:1764191658'),

('ClientError: An error occurred (AccessDeniedException) when calling the GetItem operation: User is not authorized', 'general', 'HIGH', '[{"solution": "Verify Lambda role policy table name matches exactly: policy has table/lambda-dynamodb-url-shortener but code uses table/url-shortener-table. Fix either the policy or the code", "percentage": 97}, {"solution": "If using multiple DynamoDB tables, ensure all table ARNs are listed in the Resource array of the policy", "percentage": 90}]'::jsonb, 'Lambda function code, IAM role policy JSON, DynamoDB table names', 'Lambda invocation returns item data without AccessDeniedException', 'Name mismatch between policy and actual table accessed, partial policy ARN strings', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/72160726', 'admin:1764191658'),

('Access denied for user ''xxxxx''@''%'' to database ''xxxxxxx'' using Sequelize', 'general', 'HIGH', '[{"solution": "Verify database user has GRANT permissions on the specific database: GRANT ALL PRIVILEGES ON *.* TO ''username''@''%'' WITH GRANT OPTION", "percentage": 93}, {"solution": "Check database config uses correct username/password and that user exists on the target host", "percentage": 89}]'::jsonb, 'MySQL user account credentials, Sequelize connection config, database name', 'Sequelize connects to database and executes queries without access denied error', 'Wrong credentials in environment variables, user created for localhost only not remote hosts', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/70615562', 'admin:1764191658'),

('Error: P1010: User was denied access on the database schema', 'general', 'HIGH', '[{"solution": "Grant schema access with: GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO username; and GRANT CONNECT ON DATABASE dbname TO username", "percentage": 94}, {"solution": "Check for conflicting PostgreSQL instances on same port (port 5432) causing connection to wrong database", "percentage": 87}]'::jsonb, 'PostgreSQL database connection, Prisma schema file, user permissions SQL', 'Prisma migration runs successfully and creates tables in public schema', 'Forgetting to grant schema-level permissions, multiple PostgreSQL instances running', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/76211701', 'admin:1764191658'),

('Error: EACCES: permission denied, copyfile Prisma libquery-engine', 'general', 'MEDIUM', '[{"solution": "Fix file ownership: chown -R node:node node_modules/.prisma to give correct user permission to Prisma cache files", "percentage": 96}, {"solution": "Delete .cache/prisma directory and reinstall: rm -rf ~/.cache/prisma && npm install", "percentage": 88}]'::jsonb, 'Node.js project with Prisma, Docker container access, user permissions', 'npx prisma generate completes without EACCES errors', 'Running prisma as root then switching users, stale cache files after node_modules reinstall', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/72550271', 'admin:1764191658'),

('Permission denied: Cassandra doesn''t have write permission for data directory', 'general', 'MEDIUM', '[{"solution": "Verify Cassandra user owns data directories: chown -R cassandra:cassandra /var/lib/cassandra /var/log/cassandra", "percentage": 95}, {"solution": "Check directory permissions are 755+ and process runs as cassandra user not root", "percentage": 91}]'::jsonb, 'Cassandra server installation, Linux user account, directory paths', 'Cassandra node starts without FSWriteError, compaction completes successfully', 'Running Cassandra as wrong user, insufficient directory permissions (644 instead of 755)', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/17735590', 'admin:1764191658'),

('Error 1003 Access Denied: Cloudflare Workers cannot fetch IP addresses directly', 'general', 'MEDIUM', '[{"solution": "Use DNS domain name instead of raw IP: fetch(''http://ec2-54-xxx.compute.amazonaws.com'') instead of fetch(''http://54.xxx.xxx.xxx'')", "percentage": 97}, {"solution": "Create DNS CNAME record for your IP and use the domain name in fetch requests", "percentage": 92}]'::jsonb, 'Cloudflare Worker code, AWS EC2 instance public DNS name, fetch API', 'Worker fetch request returns 200 status code when using domain name', 'Using public IPv4 address instead of public IPv4 DNS from AWS console, assuming IP and DNS resolve identically from Workers', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/69671668', 'admin:1764191658'),

('HTTP 403 Forbidden when fetching from Cloudflare with Spring Boot RestTemplate', 'general', 'LOW', '[{"solution": "Add User-Agent header to RestTemplate: headers.set(''User-Agent'', ''Mozilla/5.0'') to prevent Cloudflare bot detection blocking the request", "percentage": 94}, {"solution": "Configure RestTemplate with custom HttpClient that sends standard browser headers mimicking real requests", "percentage": 85}]'::jsonb, 'Spring Boot RestTemplate, Cloudflare protected resource, S3 bucket with Cloudflare CDN', 'RestTemplate fetch returns 200 status and retrieves image data successfully', 'Not setting User-Agent header, sending empty or non-standard user agents that trigger Cloudflare protection', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/77606398', 'admin:1764191658');
