-- Astro Framework Errors - Mining Run 20251127
-- 70 comprehensive error patterns for clauderepo knowledge base

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('could not find commit hash for latest', 'astro', 'MEDIUM', '[{"solution": "Check if git is installed and accessible: git --version", "percentage": 85}, {"solution": "Update npm and try again: npm install -g npm@latest", "percentage": 70}, {"solution": "Use degit alternative: npx create-astro@latest --template minimal", "percentage": 90}]'::jsonb, 'Node.js, npm, git installed', 'Project initializes without degit errors', 'Git SSH key issues, corrupted npm cache', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/70547766', 'admin:1764259619'),

('error-astro-preview-adapter-does-not-have-previewentrypoint', 'astro', 'MEDIUM', '[{"solution": "Only Node adapter supports astro preview: use @astrojs/node", "percentage": 95}, {"solution": "For Vercel/Netlify use production builds instead of preview", "percentage": 85}, {"solution": "Check adapter documentation for preview support", "percentage": 80}]'::jsonb, 'SSR adapter configured', 'astro preview command runs successfully', 'Using incompatible adapters like Vercel with preview', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/74119829', 'admin:1764259619'),

('failed-to-resolve-extends-astro-tsconfigs-strict', 'astro', 'HIGH', '[{"solution": "Replace with official tsconfig from Astro GitHub", "percentage": 95}, {"solution": "Ensure astro package is properly installed in node_modules", "percentage": 88}, {"solution": "Run npm install to reinstall dependencies", "percentage": 85}]'::jsonb, 'TypeScript configured, astro installed', 'TypeScript compilation succeeds', 'Corrupted tsconfig, missing node_modules', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/73978567', 'admin:1764259619'),

('astro-seeing-x-error-the-build-was-canceled', 'astro', 'HIGH', '[{"solution": "Check for conflicting integrations like Svelte+React without include config", "percentage": 92}, {"solution": "Update all integrations to compatible versions", "percentage": 88}, {"solution": "Split JSX components into framework-specific folders", "percentage": 95}]'::jsonb, 'Multiple framework integrations', 'Build completes without X error', 'Mixed JSX frameworks without proper config', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77623123', 'admin:1764259619'),

('hydration-completed-but-contains-mismatches', 'astro', 'HIGH', '[{"solution": "Defer dynamic content to mounted() lifecycle hook", "percentage": 90}, {"solution": "Ensure server and client render identical HTML", "percentage": 95}, {"solution": "Use client:only directive for client-only components", "percentage": 92}]'::jsonb, 'Vue/React component in Astro', 'Hydration completes without mismatches', 'Rendering dynamic content at creation', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/76618212', 'admin:1764259619'),

('no-renderer-installed-for-react', 'astro', 'CRITICAL', '[{"solution": "Install @astrojs/react: npm install @astrojs/react", "percentage": 98}, {"solution": "Add to astro.config.mjs integrations array", "percentage": 98}, {"solution": "In Astro v3, use include option to specify react folder pattern", "percentage": 95}]'::jsonb, 'Astro project with React components', 'React components render in browser', 'Missing integration, incorrect config', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/77280297', 'admin:1764259619'),

('no-renderer-installed-for-solid-js', 'astro', 'CRITICAL', '[{"solution": "Install @astrojs/solid-js: npm install @astrojs/solid-js", "percentage": 98}, {"solution": "Add to integrations in astro.config.mjs", "percentage": 98}, {"solution": "Separate Solid components into /solid/ folder for Astro v3+", "percentage": 95}]'::jsonb, 'Astro project with Solid.js components', 'Solid.js components render without errors', 'Missing integration, config path mismatch', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/74578397', 'admin:1764259619'),

('astro-components-cannot-use-framework-components', 'astro', 'MEDIUM', '[{"solution": "Framework components can only be used in Astro pages/layouts via client directive", "percentage": 95}, {"solution": "Cannot nest framework inside framework - use Astro as wrapper", "percentage": 90}, {"solution": "Pass data via Astro props to framework components", "percentage": 92}]'::jsonb, 'Astro component with framework component', 'Components render correctly', 'Trying to nest React in Vue', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/76169944', 'admin:1764259619'),

('error-when-evaluating-ssr-module', 'astro', 'HIGH', '[{"solution": "Check for CommonJS modules that need ESM: use getViteConfig", "percentage": 85}, {"solution": "Verify all dependencies are ESM compatible", "percentage": 88}, {"solution": "Add problematic packages to ssr.noExternal in vite config", "percentage": 90}]'::jsonb, 'SSR adapter configured', 'Build succeeds without SSR evaluation errors', 'ESM/CommonJS module conflicts', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/77621581', 'admin:1764259619'),

('build-error-using-astro-framework-react-image-gallery', 'astro', 'MEDIUM', '[{"solution": "Verify image library is ESM compatible", "percentage": 82}, {"solution": "Check for inline styles that conflict with Astro image component", "percentage": 88}, {"solution": "Use img tag instead of framework-specific image components", "percentage": 85}]'::jsonb, 'Astro with React and image library', 'Images load without build errors', 'ESM compatibility, CSS-in-JS conflicts', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/76029503', 'admin:1764259619'),

('astro-site-css-not-working-after-building', 'astro', 'MEDIUM', '[{"solution": "Serve via localhost not file://, use astro preview", "percentage": 95}, {"solution": "Check CSS scoping in Astro components", "percentage": 88}, {"solution": "Verify CSS is imported, not just in <style> tag", "percentage": 90}]'::jsonb, 'Astro static site built', 'CSS loads correctly in browser dev tools', 'Opening HTML file directly (file://)', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/77403679', 'admin:1764259619'),

('astro-layout-for-mdx-with-predefined-allowed-components', 'astro', 'MEDIUM', '[{"solution": "Define allowed components in MDX export config", "percentage": 92}, {"solution": "Wrap content in layout component with component prop", "percentage": 90}, {"solution": "Use rehype plugins to extend component support", "percentage": 85}]'::jsonb, 'MDX content collection with layouts', 'MDX renders with custom components', 'Missing component definitions', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/78368288', 'admin:1764259619'),

('cannot-find-css-file-double-click-open', 'astro', 'LOW', '[{"solution": "Use local server: npm run preview or npm run dev", "percentage": 98}, {"solution": "Deploy to actual web server", "percentage": 95}, {"solution": "Use VSCode Live Server extension", "percentage": 90}]'::jsonb, 'Astro built project', 'CSS loads when served over HTTP', 'Opening dist/index.html directly', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/74857285', 'admin:1764259619'),

('astro-project-has-updated-cannot-run-local-host', 'astro', 'MEDIUM', '[{"solution": "Reinstall dependencies: rm -rf node_modules && npm install", "percentage": 92}, {"solution": "Update Astro: npm install astro@latest", "percentage": 88}, {"solution": "Check Node version compatibility", "percentage": 85}]'::jsonb, 'Astro project after update', 'Dev server starts without errors', 'Outdated node_modules, version mismatch', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77505288', 'admin:1764259619'),

('typescript-cannot-find-module-astrocontent', 'astro', 'MEDIUM', '[{"solution": "Enable allowJs and strictNullChecks in tsconfig.json", "percentage": 90}, {"solution": "Ensure astro version matches content collection API", "percentage": 92}, {"solution": "Run astro sync to generate types", "percentage": 95}]'::jsonb, 'Astro with content collections', 'TypeScript resolves astro:content imports', 'Outdated Astro, missing tsconfig settings', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/79125943', 'admin:1764259619'),

('dynamically-import-all-images-from-folder', 'astro', 'MEDIUM', '[{"solution": "Use import.meta.glob for dynamic imports: const images = import.meta.glob()", "percentage": 95}, {"solution": "Ensure glob pattern is literal string, not template", "percentage": 92}, {"solution": "Check import.meta is available in module context", "percentage": 88}]'::jsonb, 'Astro module with image assets', 'Dynamic imports resolve all assets', 'Template literal in glob, missing import.meta', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/75126196', 'admin:1764259619'),

('error-import-markdown-files-in-astro-using-astro-glob', 'astro', 'MEDIUM', '[{"solution": "Use Astro.glob() in server context: const posts = await Astro.glob()", "percentage": 95}, {"solution": "Use import.meta.glob() in module context", "percentage": 92}, {"solution": "Ensure glob pattern uses forward slashes", "percentage": 90}]'::jsonb, 'Astro with markdown files', 'Markdown files imported successfully', 'Context mismatch, backslash paths', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/79001460', 'admin:1764259619'),

('astro-dynamic-import-unexpected-error', 'astro', 'MEDIUM', '[{"solution": "Use dynamic import in server component: const Component = (await import()).default", "percentage": 92}, {"solution": "Wrap in try-catch for error handling", "percentage": 88}, {"solution": "Verify import path is string literal", "percentage": 90}]'::jsonb, 'Astro server component with dynamic import', 'Dynamic imports resolve without errors', 'Template expressions in import path', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/77966918', 'admin:1764259619'),

('import-meta-glob-does-not-list-freshly-generated-file', 'astro', 'MEDIUM', '[{"solution": "Restart dev server after generating new files", "percentage": 95}, {"solution": "import.meta.glob is computed at build time", "percentage": 92}, {"solution": "Use dynamic import for runtime file discovery", "percentage": 85}]'::jsonb, 'Astro with import.meta.glob', 'Glob includes all files', 'Expectation of runtime globbing', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/79301222', 'admin:1764259619'),

('how-can-i-do-dynamic-imports-in-astrojs', 'astro', 'MEDIUM', '[{"solution": "For icons: const icon = (await import(PATH)).default", "percentage": 92}, {"solution": "Use URL constructor for public assets", "percentage": 88}, {"solution": "Preload all icons if performance critical", "percentage": 85}]'::jsonb, 'Astro project needing dynamic imports', 'Dynamic imports resolve and render', 'Async/await in template context', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/78133036', 'admin:1764259619'),

('astro-js-not-correctly-importing-functions', 'astro', 'MEDIUM', '[{"solution": "Verify export syntax: export const func = ...", "percentage": 93}, {"solution": "Use named imports: import { func } from ''./path''", "percentage": 95}, {"solution": "Check file extensions in import paths", "percentage": 90}]'::jsonb, 'Astro component with imports', 'Functions import and execute', 'Missing export, path with/without extension', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/73789345', 'admin:1764259619'),

('how-do-i-import-astro-files-in-astro-config', 'astro', 'LOW', '[{"solution": "Import .astro files in config: import type { AstroConfig } from ''astro''", "percentage": 85}, {"solution": "Use relative paths from config directory", "percentage": 88}, {"solution": "Astro files are not supported in config, use .ts/.js instead", "percentage": 92}]'::jsonb, 'Astro config file', 'Config imports resolve', 'Expecting .astro to work in config', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/75878983', 'admin:1764259619'),

('astro-seeing-x-error-build-was-canceled', 'astro', 'CRITICAL', '[{"solution": "Check Svelte/React integration conflict in logs", "percentage": 95}, {"solution": "Separate framework components with include/exclude options", "percentage": 95}, {"solution": "Update integrations to v3+ compatible versions", "percentage": 90}]'::jsonb, 'Multiple framework integrations', 'Build completes to completion', 'Undeclared framework conflicts', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/77623123', 'admin:1764259619'),

('astro-build-freezes-after-upgrading-to-v5', 'astro', 'HIGH', '[{"solution": "Check for circular dependencies or infinite loops", "percentage": 85}, {"solution": "Update to latest Astro patch: npm install astro@latest", "percentage": 88}, {"solution": "Try with npm instead of bun if using Bun", "percentage": 82}]'::jsonb, 'Astro v5 project', 'Build completes in reasonable time', 'Circular deps, bun build issues', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/79304137', 'admin:1764259619'),

('astro-static-build-fails-when-using-certain-node-packages', 'astro', 'HIGH', '[{"solution": "Add problematic packages to ssr.noExternal in vite config", "percentage": 90}, {"solution": "Verify package is ES6 module compatible", "percentage": 88}, {"solution": "Use dynamic import instead of top-level require", "percentage": 85}]'::jsonb, 'Node packages in Astro build', 'Build succeeds with all packages', 'CommonJS packages, module resolution', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/77621581', 'admin:1764259619'),

('nodemailer-in-astro-project-not-sending-mail', 'astro', 'MEDIUM', '[{"solution": "Connection timeout - check SMTP credentials in production env", "percentage": 85}, {"solution": "Use API endpoint with server-side imports", "percentage": 90}, {"solution": "Add timeout and error handling to SMTP connection", "percentage": 92}]'::jsonb, 'Astro API route with nodemailer', 'Email sends successfully', 'Env vars, SMTP config, timeout', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/78457237', 'admin:1764259619'),

('astro-build-version-routes-not-working', 'astro', 'MEDIUM', '[{"solution": "Use file format instead of directory for build", "percentage": 88}, {"solution": "Check output format matches router expectations", "percentage": 85}, {"solution": "Verify route exists in build output", "percentage": 92}]'::jsonb, 'Astro with build output format config', 'Routes resolve in built site', 'Incorrect build format for router', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/75603461', 'admin:1764259619'),

('location-href-not-defined-in-astro-pages', 'astro', 'MEDIUM', '[{"solution": "Check if window is defined: if (typeof window !== ''undefined'')", "percentage": 95}, {"solution": "Use client directive on component: client:load", "percentage": 92}, {"solution": "Move code to useEffect hook (React) or mounted (Vue)", "percentage": 93}]'::jsonb, 'Astro page accessing browser APIs', 'Code executes only on client', 'Server-side execution of browser code', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/74184132', 'admin:1764259619'),

('unexpected-error-creating-custom-react-astro-component', 'astro', 'MEDIUM', '[{"solution": "Check MUI imports are not causing conflicts", "percentage": 88}, {"solution": "Verify component props are serializable", "percentage": 90}, {"solution": "Use client:load directive if component needs hydration", "percentage": 92}]'::jsonb, 'Custom React component in Astro', 'Component renders without errors', 'Non-serializable props, CSS conflicts', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/74588321', 'admin:1764259619'),

('collectionentry-is-any-type-error', 'astro', 'MEDIUM', '[{"solution": "Ensure collection folder has content files: src/content/articles/", "percentage": 95}, {"solution": "Run astro sync to generate type definitions", "percentage": 98}, {"solution": "Check config.ts properly exports defineCollection", "percentage": 92}]'::jsonb, 'Content collection TypeScript', 'CollectionEntry types resolve correctly', 'Empty collection folder, missing sync', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/75942713', 'admin:1764259619'),

('schema-not-working-with-subdirectories-in-content', 'astro', 'MEDIUM', '[{"solution": "Set strictNullChecks: true and allowJs: true in tsconfig.json", "percentage": 95}, {"solution": "Organize subdirectories before defineCollection", "percentage": 92}, {"solution": "Ensure schema matches all file structures", "percentage": 90}]'::jsonb, 'Content collections with subdirs', 'Schema validates all content files', 'TypeScript config, schema mismatch', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/76931395', 'admin:1764259619'),

('script-tag-in-astro-component-not-working-in-collection', 'astro', 'MEDIUM', '[{"solution": "Use is:inline for inline scripts in content", "percentage": 90}, {"solution": "Import dependencies instead of embedding scripts", "percentage": 88}, {"solution": "Move scripts to separate layout component", "percentage": 92}]'::jsonb, 'Script in content collection component', 'Scripts execute without conflicts', 'Mixing inline and imported scripts', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/75351313', 'admin:1764259619'),

('customizing-definecollection-in-astro', 'astro', 'MEDIUM', '[{"solution": "Use z.object() from zod for schema customization", "percentage": 93}, {"solution": "Reference other collections with reference() function", "percentage": 92}, {"solution": "Check collection name matches defineCollection key", "percentage": 95}]'::jsonb, 'Content collection customization', 'Custom collection schema works', 'Schema definition syntax', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/79243125', 'admin:1764259619'),

('how-to-create-sub-types-in-astro-content-collections', 'astro', 'MEDIUM', '[{"solution": "Use z.union() or z.discriminatedUnion() in schema", "percentage": 92}, {"solution": "Create references between collections", "percentage": 88}, {"solution": "Use polymorphic type with type field", "percentage": 90}]'::jsonb, 'Advanced content collection schema', 'Subtypes resolve with correct discrimination', 'Zod schema composition', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/77671025', 'admin:1764259619'),

('astro-build-failing-in-netlify-decapcms', 'astro', 'MEDIUM', '[{"solution": "Check decap CMS file format matches collection schema", "percentage": 90}, {"solution": "Verify frontmatter syntax in generated files", "percentage": 92}, {"solution": "Run astro sync before build in CI", "percentage": 95}]'::jsonb, 'Astro with decap CMS on Netlify', 'Build succeeds with decap content', 'Decap file format, schema mismatch', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/77936468', 'admin:1764259619'),

('build-error-astro-5-image-collections-image-component', 'astro', 'MEDIUM', '[{"solution": "Ensure Image component receives correct src prop", "percentage": 92}, {"solution": "Build image with explicit src path: src={post.data.image.src}", "percentage": 95}, {"solution": "Check image file exists in public or src directory", "percentage": 90}]'::jsonb, 'Astro 5 with image collections', 'Images display in built site', 'Image prop format, missing files', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/79762165', 'admin:1764259619'),

('astro-sanity-integration-error-evaluating-ssr', 'astro', 'HIGH', '[{"solution": "Update @astrojs/sanity to compatible version", "percentage": 92}, {"solution": "Check Sanity client configuration in astro.config.mjs", "percentage": 90}, {"solution": "Verify Sanity dataset and project ID in env", "percentage": 95}]'::jsonb, 'Astro with Sanity CMS integration', 'SSR evaluation succeeds', 'Integration version mismatch, config', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/77530353', 'admin:1764259619'),

('npm-dependency-conflicts-astro-compress', 'astro', 'MEDIUM', '[{"solution": "Use compatible version of astro-compress", "percentage": 85}, {"solution": "Downgrade Astro or astro-compress to matching versions", "percentage": 88}, {"solution": "Use alternative compression integration", "percentage": 80}]'::jsonb, 'npm install with dependency conflicts', 'All dependencies resolve', 'Version incompatibility', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/76875559', 'admin:1764259619'),

('astro-image-sharp-error-sanity-integration', 'astro', 'HIGH', '[{"solution": "Update sharp dependency: npm install sharp@latest", "percentage": 90}, {"solution": "Verify node version is compatible with sharp (Node 16+)", "percentage": 92}, {"solution": "Reinstall node_modules: rm -rf node_modules && npm install", "percentage": 88}]'::jsonb, 'Astro with Sanity and Image component', 'Images process without sharp errors', 'Sharp version, Node compatibility', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/77777542', 'admin:1764259619'),

('error-astro-icon-package-ssr-module', 'astro', 'MEDIUM', '[{"solution": "Update astro-icon to latest: npm install astro-icon@latest", "percentage": 92}, {"solution": "Check astro-icon integration is added to config", "percentage": 90}, {"solution": "Verify icon files exist in specified directory", "percentage": 88}]'::jsonb, 'Astro with astro-icon package', 'Icons render without SSR errors', 'Outdated package, missing config', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/78855241', 'admin:1764259619'),

('invalid-attempt-to-resolve-component', 'astro', 'MEDIUM', '[{"solution": "Check component export is default or named export", "percentage": 92}, {"solution": "Verify component path is correct", "percentage": 93}, {"solution": "Ensure component file uses correct framework syntax", "percentage": 90}]'::jsonb, 'Astro component resolution', 'Components resolve and render', 'Missing export, incorrect path', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/70547766', 'admin:1764259619'),

('error-fetch-failed-starting-new-astro-project', 'astro', 'MEDIUM', '[{"solution": "Check internet connection and DNS", "percentage": 88}, {"solution": "Use npm registry: npm config set registry https://registry.npmjs.org/", "percentage": 90}, {"solution": "Try again with --verbose flag for debugging", "percentage": 85}]'::jsonb, 'npm create astro@latest', 'Project initializes successfully', 'Network issues, registry problems', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/75938260', 'admin:1764259619'),

('unable-to-access-port-astro-docker-container', 'astro', 'MEDIUM', '[{"solution": "Expose port in Docker: EXPOSE 4321 and -p 4321:4321", "percentage": 95}, {"solution": "Bind to 0.0.0.0 not localhost: astro dev --host", "percentage": 95}, {"solution": "Check Docker network configuration", "percentage": 88}]'::jsonb, 'Astro running in Docker', 'Astro dev server accessible from host', 'Port binding, Docker network', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/77709052', 'admin:1764259619'),

('astro-how-to-proxy-service-calls', 'astro', 'MEDIUM', '[{"solution": "Use vite.server.proxy in astro.config.mjs", "percentage": 92}, {"solution": "Configure proxy to rewrite requests: /api -> http://localhost:3010", "percentage": 95}, {"solution": "Use dev server middleware for custom logic", "percentage": 88}]'::jsonb, 'Astro with external service on different port', 'Service calls proxy correctly', 'Proxy config, CORS issues', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/73212935', 'admin:1764259619'),

('astro-network-only-with-run-dev-not-with-preview', 'astro', 'MEDIUM', '[{"solution": "Use astro preview --host 0.0.0.0 for network access", "percentage": 92}, {"solution": "Check preview adapter supports network binding", "percentage": 90}, {"solution": "Verify firewall allows traffic to preview port", "percentage": 88}]'::jsonb, 'Astro dev server networking', 'Preview accessible on network', 'Preview binding, adapter support', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/77942648', 'admin:1764259619'),

('cant-connect-to-astro-dev-server-on-other-device', 'astro', 'MEDIUM', '[{"solution": "Bind dev server to 0.0.0.0: astro dev --host 0.0.0.0", "percentage": 95}, {"solution": "Use local machine IP instead of localhost", "percentage": 92}, {"solution": "Check both devices on same network", "percentage": 95}]'::jsonb, 'Astro dev server on local network', 'Dev server accessible from other devices', 'Localhost binding, network issues', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/77680934', 'admin:1764259619'),

('websocket-port-problem-already-in-use', 'astro', 'MEDIUM', '[{"solution": "Kill process on port: lsof -ti:4321 | xargs kill -9", "percentage": 95}, {"solution": "Use different port: astro dev --port 3000", "percentage": 95}, {"solution": "One process per port is OS requirement", "percentage": 90}]'::jsonb, 'Port 4321 already in use', 'Dev server starts on available port', 'Process still running on port', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/6619361', 'admin:1764259619'),

('esbuild-npm-install-failure-docker', 'astro', 'MEDIUM', '[{"solution": "Install esbuild in Docker: npm install esbuild", "percentage": 92}, {"solution": "Use correct platform tag for esbuild", "percentage": 90}, {"solution": "Ensure Node.js version is compatible", "percentage": 88}]'::jsonb, 'Astro in Docker without esbuild', 'esbuild installs successfully', 'Missing esbuild, platform mismatch', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/73567964', 'admin:1764259619'),

('node-js-port-3000-already-in-use-not-actually', 'astro', 'MEDIUM', '[{"solution": "Use lsof to find real process: lsof -i :3000", "percentage": 95}, {"solution": "Check if zombie process exists, restart system", "percentage": 85}, {"solution": "Clear npm cache: npm cache clean --force", "percentage": 82}]'::jsonb, 'Port appears in use but isnt', 'Port becomes available', 'Zombie process, system state', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/39322089', 'admin:1764259619'),

('error-deploy-astro-node-adapter-cookie-module-not-found', 'astro', 'HIGH', '[{"solution": "Install cookie package: npm install cookie", "percentage": 98}, {"solution": "Verify cookie is in dependencies not devDependencies", "percentage": 95}, {"solution": "Ensure package.json includes cookie in deploy", "percentage": 95}]'::jsonb, 'Astro Node adapter deployment', 'Deployment succeeds without cookie errors', 'Missing cookie package in prod', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/79384055', 'admin:1764259619'),

('how-to-deploy-ssr-astro-node-adapter-netlify', 'astro', 'MEDIUM', '[{"solution": "Add sharp to dependencies for image optimization", "percentage": 92}, {"solution": "Configure Netlify build settings for Node SSR", "percentage": 90}, {"solution": "Ensure astro.config includes @astrojs/node", "percentage": 95}]'::jsonb, 'Astro SSR with Node adapter on Netlify', 'Site deploys and runs on Netlify', 'Missing dependencies, config', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/75352316', 'admin:1764259619'),

('astro-site-not-generating-static-pages-vercel-adapter', 'astro', 'MEDIUM', '[{"solution": "Use static pre-rendering in Vercel adapter config", "percentage": 92}, {"solution": "Verify getStaticPaths returns all routes", "percentage": 95}, {"solution": "Check vercel.json build command uses astro build", "percentage": 90}]'::jsonb, 'Astro SSR to Vercel', 'All pages generate as static', 'Adapter config, route generation', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/78034697', 'admin:1764259619'),

('how-to-deploy-astro-ssr-nodejs-adapter-azure', 'astro', 'MEDIUM', '[{"solution": "Use @astrojs/node adapter configured for Azure", "percentage": 90}, {"solution": "Deploy as Node.js app on Azure App Service", "percentage": 90}, {"solution": "Configure startup script in package.json", "percentage": 92}]'::jsonb, 'Astro SSR to Azure App Service', 'Site runs on Azure', 'Adapter setup, deployment config', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/77412026', 'admin:1764259619'),

('astro-cloudflare-adapter-ignores-wrangler-config', 'astro', 'MEDIUM', '[{"solution": "Define SESSION KV binding in wrangler.json", "percentage": 95}, {"solution": "Use @astrojs/cloudflare configured for wrangler", "percentage": 93}, {"solution": "Restart dev server after wrangler.json changes", "percentage": 90}]'::jsonb, 'Astro Cloudflare adapter', 'KV bindings work in dev and deploy', 'wrangler.json config, binding setup', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/79632700', 'admin:1764259619'),

('how-to-deploy-astro-ssr-firebase-hosting', 'astro', 'MEDIUM', '[{"solution": "Use @astrojs/node with Cloud Functions for SSR", "percentage": 88}, {"solution": "Deploy static assets to Firebase Hosting", "percentage": 85}, {"solution": "Configure routing between Functions and Hosting", "percentage": 90}]'::jsonb, 'Astro deployment to Firebase', 'Site runs on Firebase', 'Cloud Functions config, routing', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/76699640', 'admin:1764259619'),

('javascript-not-working-on-page-change-astro', 'astro', 'HIGH', '[{"solution": "Use astro:after-swap event to reinitialize scripts", "percentage": 95}, {"solution": "Use client directive on interactive components", "percentage": 92}, {"solution": "Move scripts to layout component instead of page", "percentage": 90}]'::jsonb, 'ViewTransition with JavaScript initialization', 'Scripts run on every page change', 'Script scope, lifecycle timing', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/77278507', 'admin:1764259619'),

('astro-view-transition-morph-framework-to-astro', 'astro', 'MEDIUM', '[{"solution": "Use transition:persist for shared elements between pages", "percentage": 92}, {"solution": "Ensure both pages have same element transition:name", "percentage": 95}, {"solution": "Check CSS animation definitions for morph effect", "percentage": 88}]'::jsonb, 'View transitions between framework and Astro', 'Smooth transitions between page types', 'Element naming, CSS animation', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/77555482', 'admin:1764259619'),

('astro-viewtransition-not-working-windows-10', 'astro', 'MEDIUM', '[{"solution": "Use Astro view transition polyfill for browser support", "percentage": 95}, {"solution": "Check browser supports document.startViewTransition", "percentage": 92}, {"solution": "Fallback to non-transition experience for unsupported browsers", "percentage": 90}]'::jsonb, 'ViewTransition on Windows 10', 'Transitions work or gracefully degrade', 'Browser compatibility, polyfill', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/78464257', 'admin:1764259619'),

('animations-view-transitions-weird-chrome-firefox', 'astro', 'MEDIUM', '[{"solution": "Adjust CSS animation timing for cross-browser consistency", "percentage": 90}, {"solution": "Test in both Chrome and Firefox DevTools", "percentage": 92}, {"solution": "Use CSS @supports to detect ViewTransition support", "percentage": 88}]'::jsonb, 'ViewTransition cross-browser animation', 'Smooth animations in all browsers', 'Browser rendering differences', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/79702273', 'admin:1764259619'),

('using-viewtransition-for-dark-mode-astro', 'astro', 'MEDIUM', '[{"solution": "Update theme in beforeswap event handler", "percentage": 92}, {"solution": "Ensure transition:persist applies to theme root element", "percentage": 90}, {"solution": "Test CSS animations for theme switch", "percentage": 88}]'::jsonb, 'ViewTransition with theme switching', 'Dark mode transitions smoothly', 'Event timing, element persistence', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/77092920', 'admin:1764259619'),

('view-transitions-not-working-transition-name-property', 'astro', 'MEDIUM', '[{"solution": "Only one element per view-transition-name across all pages", "percentage": 98}, {"solution": "Use unique names for different transitioned elements", "percentage": 96}, {"solution": "Check CSS view-transition-name applied to correct element", "percentage": 95}]'::jsonb, 'ViewTransition in Astro pages', 'Transitions work without conflicts', 'Duplicate transition-name values', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/76552831', 'admin:1764259619'),

('rerun-ionic-scripts-astro-view-transition', 'astro', 'MEDIUM', '[{"solution": "Reinitialize Ionic components in astro:after-swap event", "percentage": 92}, {"solution": "Define custom event listener for component reinit", "percentage": 90}, {"solution": "Use ion-router with view transitions", "percentage": 88}]'::jsonb, 'Ionic components with ViewTransition', 'Ionic components persist across transitions', 'Component lifecycle, re-initialization', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/78513699', 'admin:1764259619'),

('aos-not-triggering-animation-in-view-astro', 'astro', 'MEDIUM', '[{"solution": "Reinitialize AOS on page change: AOS.refresh()", "percentage": 95}, {"solution": "Use astro:after-swap event to trigger AOS init", "percentage": 93}, {"solution": "Verify AOS loaded as client component", "percentage": 90}]'::jsonb, 'Astro with AOS (Animate On Scroll)', 'Animations trigger on all pages', 'Lifecycle timing, AOS initialization', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/76575482', 'admin:1764259619'),

('react-18-hydration-failed-initial-ui-mismatch', 'astro', 'HIGH', '[{"solution": "Ensure server and client render identical DOM", "percentage": 95}, {"solution": "Check for conditional rendering using window object", "percentage": 95}, {"solution": "Use useEffect for client-only content", "percentage": 94}]'::jsonb, 'React 18 in Astro with hydration', 'Hydration succeeds without errors', 'Server/client render mismatch', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/71706064', 'admin:1764259619'),

('partial-hydration-vue-js', 'astro', 'MEDIUM', '[{"solution": "Use client:load directive for interactive components", "percentage": 92}, {"solution": "Astro handles automatic partial hydration", "percentage": 95}, {"solution": "Only hydrate components with client: directives", "percentage": 95}]'::jsonb, 'Vue component partial hydration in Astro', 'Components hydrate correctly', 'Expecting manual hydration setup', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/73473992', 'admin:1764259619'),

('quasar-ssr-hydration-mismatches-v-for', 'astro', 'MEDIUM', '[{"solution": "Ensure v-for keys are stable between server/client", "percentage": 95}, {"solution": "Check list data matches on both renders", "percentage": 93}, {"solution": "Use transition:persist for list elements", "percentage": 88}]'::jsonb, 'Quasar v-for hydration in Astro', 'v-for renders match between server/client', 'Unstable keys, list data', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/79044557', 'admin:1764259619'),

('vue-ssr-suppress-hydration-mismatch-warning', 'astro', 'MEDIUM', '[{"solution": "Use suppressHydrationWarning attribute on element", "percentage": 90}, {"solution": "Better: fix underlying render mismatch", "percentage": 95}, {"solution": "Use client:only for truly client-only content", "percentage": 95}]'::jsonb, 'Vue SSR hydration warning suppression', 'Hydration warnings gone or fixed', 'Mismatch root cause identification', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/68438016', 'admin:1764259619'),

('astro-is-not-rendering-hcaptcha-component', 'astro', 'MEDIUM', '[{"solution": "Use client:load on hCaptcha component: <HCaptcha client:load />", "percentage": 95}, {"solution": "Verify hCaptcha sitekey is set correctly", "percentage": 92}, {"solution": "Check hCaptcha library is ESM compatible", "percentage": 90}]'::jsonb, 'hCaptcha widget in Astro', 'hCaptcha renders and validates', 'Missing client directive, config', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/78233797', 'admin:1764259619'),

('astro-hydration-clientonly-react-not-working', 'astro', 'MEDIUM', '[{"solution": "Use client:only=react directive for React components", "percentage": 95}, {"solution": "Verify @astrojs/react integration is installed", "percentage": 98}, {"solution": "React component should render after client hydration", "percentage": 94}]'::jsonb, 'React client:only hydration', 'React component renders after client load', 'Integration setup, directive syntax', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/76055053', 'admin:1764259619'),

('astro-error-unable-to-render-component', 'astro', 'MEDIUM', '[{"solution": "Check component export is named or default", "percentage": 92}, {"solution": "Verify component props are passed correctly", "percentage": 93}, {"solution": "Check component file syntax is correct for framework", "percentage": 90}]'::jsonb, 'Astro component rendering error', 'Component renders in page', 'Export syntax, prop passing', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/76055053', 'admin:1764259619');
