INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Undefined variable in Sass', 'sass-css-preprocessor', 'HIGH', '[{"solution": "Ensure variable is defined before use with @use or @import statements", "percentage": 95}, {"solution": "Use namespace notation: namespace.variablename when using @use", "percentage": 92}]'::jsonb, 'Sass file structure, variable scope understanding', 'Variable compiles without error, styles apply correctly', 'Forgetting @use statements in each file, not using namespace notation', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/73054062/sasserror-undefined-variable-failing-dependencies', 'admin:1764261662'),

('SassError undefined variable with @use', 'sass-css-preprocessor', 'HIGH', '[{"solution": "Add ''as *'' to @use statement: @use ''path/to/module'' as *", "percentage": 97}, {"solution": "Import in the file that uses variables, not global files", "percentage": 90}]'::jsonb, 'Dart Sass, @use syntax knowledge', 'No undefined variable error, CSS variables accessible', 'Using @import instead of @use, not adding ''as *''', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/62127255/sass-use-makes-error-undefined-variable', 'admin:1764261662'),

('Undefined variable in SCSS with @use rule', 'sass-css-preprocessor', 'HIGH', '[{"solution": "Each file needs its own @use declaration for the variables it uses", "percentage": 98}, {"solution": "Use @use statement before accessing variables: @use ''path'' as ns;", "percentage": 95}]'::jsonb, 'File-scoped variable understanding', 'Variables accessible with namespace, no compilation errors', 'Variables only defined once in shared file, not repeated in each file', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/64980432/how-to-fix-an-undefined-variable-error-in-scss', 'admin:1764261662'),

('Illegal nesting: Only properties may be nested', 'sass-css-preprocessor', 'HIGH', '[{"solution": "Add missing semicolon at end of property values", "percentage": 99}, {"solution": "Check nesting structure is valid: selectors > properties > nested selectors", "percentage": 97}]'::jsonb, 'SCSS syntax knowledge', 'Valid nested structure, compiles without error', 'Missing semicolons, invalid selector nesting, mixing tabs and spaces', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/22977744/what-does-this-error-in-sass-mean-illegal-nesting-only-properties-may-be-nest', 'admin:1764261662'),

('Undefined mixin when using @use instead of @import', 'sass-css-preprocessor', 'HIGH', '[{"solution": "Add @use statement in the file that calls the mixin, not just the file that defines it", "percentage": 96}, {"solution": "Use @use ''path/to/mixins'' as *; to access mixins without namespace", "percentage": 94}]'::jsonb, '@use syntax understanding', 'Mixin compiles and outputs correctly', 'Only defining @use in one file, forgetting to import in child partials', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/66708858/scss-switching-from-import-to-use-undefined-mixin', 'admin:1764261662'),

('Can''t find stylesheet to import', 'sass-css-preprocessor', 'HIGH', '[{"solution": "Remove leading dots and use absolute path: @import ''node_modules/package/file''", "percentage": 94}, {"solution": "Verify relative paths point to correct directory structure", "percentage": 92}]'::jsonb, 'File path understanding, npm package knowledge', 'Stylesheet imports successfully, no path errors', 'Using ../ instead of correct relative paths, incorrect node_modules references', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/51127038/sass-error-cant-find-stylesheet-to-import', 'admin:1764261662'),

('Incompatible units in Sass operations', 'sass-css-preprocessor', 'HIGH', '[{"solution": "Use calc() for cross-unit operations: width: calc(50vw - 10px)", "percentage": 96}, {"solution": "Use unquote() for CSS functions: width: unquote(''max(50px, 5rem)'')", "percentage": 88}]'::jsonb, 'CSS unit knowledge, calc() syntax', 'Property compiles with correct units, browser renders properly', 'Mixing vw with px in functions, attempting direct unit conversion', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/54090345/sass-incompatible-units-vw-and-px', 'admin:1764261662'),

('Failed to extend selector in Sass', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use @extend .selector !optional to handle missing selectors gracefully", "percentage": 95}, {"solution": "Ensure extended selector is defined before @extend statement", "percentage": 97}]'::jsonb, '@extend syntax, selector definition order', 'Styles apply without @extend errors, cascade works correctly', '@extend used without !optional flag, extending non-existent selectors', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/26523647/shows-error-failed-to-extend-when-a-class-is-extended-in-sass', 'admin:1764261662'),

('Darken/lighten color function errors', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use sass:color module with color.adjust() instead of deprecated darken()", "percentage": 98}, {"solution": "Use tint/shade functions with mix(): mix(#fff, $color, 50%)", "percentage": 92}]'::jsonb, 'Sass color module knowledge', 'Color adjustments apply without errors, expected output achieved', 'Using deprecated darken/lighten, not importing sass:color', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/59281689/sass-color-lighten-darken-function', 'admin:1764261662'),

('SassError expected identifier or at-rule', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Check for mismatched or missing braces, semicolons, and valid selectors", "percentage": 96}, {"solution": "Ensure only SCSS syntax in .scss files (not mixed SASS/SCSS)", "percentage": 94}]'::jsonb, 'SCSS vs SASS syntax knowledge', 'File compiles without syntax errors', 'Mixing SCSS and SASS syntax, forgotten opening/closing braces', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/65911728/why-do-i-get-a-syntax-error-sasserror-expected', 'admin:1764261662'),

('Sass syntax error with calc() expressions', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use string interpolation for complex calc: background: linear-gradient(..., #{calc(50% - 1px)}, ...)", "percentage": 91}, {"solution": "Wrap calc() in quotes or use unquote()", "percentage": 89}]'::jsonb, 'Calc syntax, interpolation knowledge', 'Gradient or calc compiles correctly, displays as expected', 'Unquoted calc expressions, missing interpolation syntax', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/62675830/sass-syntax-error-expected-a-number-got-calc', 'admin:1764261662'),

('Cannot find module node-sass or sass', 'sass-css-preprocessor', 'HIGH', '[{"solution": "Install sass: npm install sass (or yarn add sass)", "percentage": 98}, {"solution": "Remove node-sass and use npm install sass-loader --save-dev", "percentage": 96}]'::jsonb, 'npm/yarn package management', 'Sass module available, no import errors', 'Not installing sass package, using deprecated node-sass', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/47447199/module-not-found-error-cant-resolve-sass-loader', 'admin:1764261662'),

('Replacement: migrate from node-sass to dart-sass', 'sass-css-preprocessor', 'HIGH', '[{"solution": "Remove node-sass and install sass: yarn remove node-sass && yarn add sass", "percentage": 99}, {"solution": "Ensure react-scripts >= 4.0.0 for automatic Dart Sass support", "percentage": 95}]'::jsonb, 'Package.json management, Dart Sass compatibility', 'Build completes without node-sass warnings, styles compile correctly', 'Keeping node-sass installed, incompatible react-scripts version', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/63943756/replace-node-sass-with-dart-sass-in-create-react-app-v3-x', 'admin:1764261662'),

('Invalid CSS after value: expected expression in Sass', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Check for missing closing brackets, braces, or semicolons", "percentage": 97}, {"solution": "Ensure property values are properly quoted if containing special characters", "percentage": 94}]'::jsonb, 'CSS syntax validation', 'CSS compiles and renders without errors', 'Unclosed selectors, invalid value syntax, missing quotes', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/7745855/sass-invalid-css-error-expected-expression', 'admin:1764261662'),

('Color name in interpolation warning', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Quote color names in map keys: \"white\" instead of white", "percentage": 97}, {"solution": "Use interpolation: .text-#{$colorName} instead of direct usage", "percentage": 94}]'::jsonb, 'Map key syntax, interpolation knowledge', 'No deprecation warnings, color names convert to strings correctly', 'Using unquoted color names in maps, not using interpolation', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/57455245/how-to-i-solve-this-sass-interpolation-issue', 'admin:1764261662'),

('Alpha channel must be between 0 and 1 for rgba', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Change rgba values to have alpha between 0-1: rgba(0, 0, 0, 0.8) not rgba(0, 0, 0, 8)", "percentage": 99}, {"solution": "Verify all rgba functions have 4 arguments with correct alpha", "percentage": 98}]'::jsonb, 'RGBA color format knowledge', 'Colors apply correctly, no compilation errors', 'Incorrect alpha values (>1 or too large), typos in values', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/38342332/sasssyntaxerror-alpha-channel-8-must-be-between-0-and-1-for-rgba', 'admin:1764261662'),

('Division operator not compiling in SCSS', 'sass-css-preprocessor', 'HIGH', '[{"solution": "Use parentheses: (30px / 2) for division operations", "percentage": 98}, {"solution": "Divide by unitless number: width: 30px / 2 when no unit needed", "percentage": 96}]'::jsonb, 'SCSS division syntax, parenthesis usage', 'Math operations compile and calculate correctly', 'Not wrapping division in parentheses, dividing px by px', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/22486709/scss-divide-operator-not-compiling', 'admin:1764261662'),

('Deprecation warning: Using / for division is deprecated', 'sass-css-preprocessor', 'HIGH', '[{"solution": "Use math.div() function: @use ''sass:math''; math.div(50, 16)", "percentage": 99}, {"solution": "Use calc() for CSS divisions: calc(50 / 16)", "percentage": 96}]'::jsonb, 'sass:math module, calc() syntax', 'No deprecation warnings, division operations work correctly', 'Using / outside calc(), not importing sass:math', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/71262427/deprecation-warning-using-for-division-outside-of-calc-is-deprecated-and-wi', 'admin:1764261662'),

('CSS variable not interpolating in Sass', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use interpolation syntax: --variable: #{$value}", "percentage": 99}, {"solution": "Note: CSS custom properties require #{ } even for variable values", "percentage": 98}]'::jsonb, 'CSS custom properties, interpolation syntax', 'CSS variables render with correct values, no literal $var names', 'Omitting #{} for CSS variable assignments, direct variable reference', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/73079963/sass-scss-variable-not-working-with-css-variable-assignment', 'admin:1764261662'),

('Font shorthand property invalid value', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use full font syntax: p { font: $size $family; } with size and family", "percentage": 96}, {"solution": "Or use separate properties: font-family and font-size", "percentage": 98}]'::jsonb, 'CSS font property shorthand', 'Font applies correctly, text renders with proper styling', 'Using font with only font-family, missing required size', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/56865201/sass-invalid-property-value', 'admin:1764261662'),

('Wrong number of arguments for mixin/function', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Check mixin definition for expected argument count and provide all required args", "percentage": 97}, {"solution": "Use default values in mixin definition: @mixin name($arg: default)", "percentage": 95}]'::jsonb, 'Mixin and function parameter syntax', 'Mixin includes compile without argument errors', 'Incorrect argument count, missing required parameters', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/25980054/sasssyntaxerror-wrong-number-of-arguments-5-for-4-for-rgba', 'admin:1764261662'),

('Properties only allowed within rules error', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Include mixins within selectors: .class { @include mixin; }", "percentage": 99}, {"solution": "Cannot call mixins at root level outside of selectors", "percentage": 98}]'::jsonb, 'Mixin scope understanding, SCSS structure', 'Mixins included correctly, no scope errors', 'Calling @include at root level, properties outside selectors', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/28088550/conditional-in-sass-mixin-throws-error', 'admin:1764261662'),

('Bootstrap 5.2 Sass utilities undefined variable', 'sass-css-preprocessor', 'HIGH', '[{"solution": "Import Bootstrap _maps.scss file: @import ''~bootstrap/scss/maps''", "percentage": 99}, {"solution": "Import in correct order: functions > variables > maps > mixins", "percentage": 98}]'::jsonb, 'Bootstrap 5.2+ import order', 'Bootstrap utilities compile, no undefined variable errors', 'Missing _maps.scss import, incorrect import order', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/73054062/sasserror-undefined-variable-failing-dependencies', 'admin:1764261662'),

('Sass @for loop syntax error', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use correct @for syntax: @for $i from 1 through 10", "percentage": 98}, {"solution": "Use ''to'' (exclusive) or ''through'' (inclusive) for range", "percentage": 97}]'::jsonb, '@for loop syntax knowledge', 'Loop iterates correctly, generates expected CSS', 'Incorrect loop syntax, wrong keywords (to vs through)', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/15146706/each-loop-with-index', 'admin:1764261662'),

('Sass map-get returns undefined for key', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Check key exists: @if map-has-key($map, $key)", "percentage": 96}, {"solution": "Use conditional with fallback: if(map-has-key($map, key), map-get($map, key), default)", "percentage": 94}]'::jsonb, 'Map operations, key checking', 'Map values retrieve correctly, no undefined returns', 'Accessing non-existent keys, not checking key existence', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/31945400/why-doesnt-sass-map-get-return-an-error-for-a-non-existent-key', 'admin:1764261662'),

('Target selector was not found for @extend', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Add !optional flag: @extend .selector !optional", "percentage": 97}, {"solution": "Ensure selector exists before @extend, use placeholder %selector for safety", "percentage": 96}]'::jsonb, '@extend !optional flag knowledge', 'Styles apply with graceful fallback, no extend errors', 'Using @extend without !optional, extending placeholders in media queries', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/70810300/sasserror-the-target-selector-was-not-found', 'admin:1764261662'),

('Error: no module with namespace in Sass', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Correct namespace in @use: @use ''path/module'' as shortname", "percentage": 98}, {"solution": "Check module path exists and import statement is correct", "percentage": 96}]'::jsonb, '@use namespace syntax, file paths', 'Module imports correctly, namespace accessible', 'Typos in namespace names, incorrect module paths', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/61330432/sasserror-there-is-no-module-with-the-namespace-math', 'admin:1764261662'),

('Sass Expected newline syntax error', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Ensure each property is on new line in SASS (not SCSS)", "percentage": 97}, {"solution": "Check for missing colons or invalid indentation in SASS files", "percentage": 96}]'::jsonb, 'SASS indentation rules, SASS vs SCSS', 'SASS compiles with correct formatting, valid indentation', 'Using SCSS syntax in .sass files, inconsistent indentation', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/61028750/vuetify-sasserror-expected-newline', 'admin:1764261662'),

('Module already loaded @forward configuration error', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Place @forward statements before @use statements in the same file", "percentage": 99}, {"solution": "Order: @forward first, then @use for configuration to apply", "percentage": 98}]'::jsonb, '@forward/@use directive ordering', 'Module loads without configuration errors', 'Mixing @forward and @use order, configuring already-loaded modules', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/67321885/sass-error-when-configuring-a-forwarded-module-that-has-been-used-before', 'admin:1764261662'),

('Invalid parent selector & in loop', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use selector syntax correctly in loops: &-#{$value} instead of &#{$value}", "percentage": 96}, {"solution": "Cannot use & to extend parent at root level or outside valid selectors", "percentage": 95}]'::jsonb, 'Parent selector & knowledge', 'Selectors compile correctly with parent reference', 'Invalid & usage in @each, trying to use & at root level', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/60227719/how-to-solve-sasserror-invalid-parent-selector', 'admin:1764261662'),

('Cannot extend selectors within media queries', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use @mixin inside media query instead of @extend outside", "percentage": 98}, {"solution": "Define mixin outside, include it inside media query for reuse", "percentage": 97}]'::jsonb, '@extend vs @mixin knowledge', 'Styles apply correctly without extend restrictions', 'Attempting @extend across @media boundaries', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/14840918/extending-selectors-from-within-media-queries-with-sass', 'admin:1764261662'),

('Invalid UTF-8 in compiled Sass file', 'sass-css-preprocessor', 'LOW', '[{"solution": "Set file encoding to UTF-8 in IDE before saving", "percentage": 98}, {"solution": "Remove non-ASCII characters from folder paths and file names", "percentage": 96}]'::jsonb, 'File encoding settings, character set knowledge', 'Compilation succeeds with no UTF-8 errors', 'Non-UTF-8 character encoding, special characters in paths', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/32496807/error-invalid-utf-8-when-compiling-sass-with-import', 'admin:1764261662'),

('Webpack sass-loader source map error', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Add ?sourceMap query to sass-loader: loader: ''style!css!sass?sourceMap''", "percentage": 94}, {"solution": "Ensure webpack and loaders are compatible versions", "percentage": 92}]'::jsonb, 'Webpack loader configuration', 'Sass compiles through webpack without source map errors', 'Incompatible loader versions, missing sourceMap option', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/30932592/sass-loader-not-working-in-webpack', 'admin:1764261662'),

('Nested @while loop variable not reset', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Reset loop variable before outer loop increment", "percentage": 98}, {"solution": "Use @for instead of @while for predictable iteration", "percentage": 99}]'::jsonb, 'Sass loop syntax and variable scope', 'Nested loops iterate correctly, all combinations generate', 'Not resetting inner loop variable, infinite loop possibility', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/23117012/sass-nested-while-loops', 'admin:1764261662'),

('Compass CSS3 mixin not imported', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Add @import ''compass/css3'' to enable CSS3 mixins like border-radius", "percentage": 99}, {"solution": "Ensure Compass gem is installed and config.rb is valid", "percentage": 97}]'::jsonb, 'Compass library, mixin import knowledge', 'Compass mixins available and compile correctly', 'Missing @import for Compass, Compass gem not installed', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/10993556/sass-compass-css3-mixins-not-working/10994163', 'admin:1764261662'),

('Multiple conditions in @if statement syntax', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use ''and'' and ''or'' keywords: @if $var1 == val and $var2 == val", "percentage": 99}, {"solution": "Use parentheses for complex logic: @if ($var1 and not ($var2))", "percentage": 98}]'::jsonb, 'Sass boolean operators, @if syntax', 'Conditional compiles with multiple conditions correctly', 'Using && instead of ''and'', || instead of ''or''', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/17225229/using-multiple-conditions-and-in-sass-if-statement', 'admin:1764261662'),

('Sass $variable value persists across loop iterations', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Variables in loops maintain scope: use unique variable names or reset after use", "percentage": 97}, {"solution": "Declare fresh variables in each iteration if needed", "percentage": 95}]'::jsonb, 'Sass variable scope in loops', 'Loop variables maintain correct iteration values', 'Reusing variable names across iterations without resetting', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/15371332/sass-ignores-variables-defined-in-if-statement', 'admin:1764261662'),

('Sass @use with configuration ''with'' clause', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use @use ''path'' with ($var: value) syntax for module configuration", "percentage": 98}, {"solution": "Variables must be !default in module for ''with'' to override", "percentage": 97}]'::jsonb, 'Sass @use with() syntax, module defaults', 'Module loads with configured values applied', 'Using @use without with clause, variables not marked !default', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/64766014/how-to-propagate-configuration-everywhere-with-dart-sass-modules-use-forward', 'admin:1764261662'),

('Sass string concatenation with + operator', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use #{} interpolation: .text-#{$color} instead of string concatenation", "percentage": 99}, {"solution": "For property values, interpolation ensures proper syntax", "percentage": 98}]'::jsonb, 'String interpolation, selector building', 'Selectors and values generate correctly without syntax errors', 'Attempting string + concatenation, not using interpolation', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/51244750/concatenate-strings-using-sass/51245499', 'admin:1764261662'),

('CSS variables require interpolation in Sass @mixin', 'sass-css-preprocessor', 'HIGH', '[{"solution": "Always use interpolation for CSS custom properties: --var: #{$value}", "percentage": 99}, {"solution": "Note: this is required even for simple variable assignments", "percentage": 99}]'::jsonb, 'CSS custom properties, interpolation syntax', 'CSS variables render with correct values, no uninterpolated $var names', 'Omitting #{} for CSS variable values, direct variable reference', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/73079963/sass-scss-variable-not-working-with-css-variable-assignment', 'admin:1764261662'),

('Unknown output style in Dart Sass', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use only ''expanded'' or ''compressed'' with dart-sass: outputStyle: ''compressed''", "percentage": 99}, {"solution": "''nested'' and ''compact'' only work with node-sass, not dart-sass", "percentage": 98}]'::jsonb, 'Dart Sass vs node-sass differences', 'Sass compiles with valid output style', 'Using ''compact'' or ''nested'' with dart-sass, wrong output style', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/76987391/sass-error-unknown-output-style-compact', 'admin:1764261662'),

('Source map generation error with Sass', 'sass-css-preprocessor', 'LOW', '[{"solution": "Update grunt-contrib-sass and Sass gem to latest versions", "percentage": 97}, {"solution": "Disable source maps if not needed: sourcemap: none", "percentage": 95}]'::jsonb, 'Grunt/build tool configuration', 'Sass compiles with valid source maps, no generation errors', 'Outdated package versions, incompatible Sass-Grunt combination', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/26501454/error-generating-source-map-grunt-and-sass-configuration', 'admin:1764261662'),

('Ruby version incompatibility with Sass gem', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Install Ruby 2.0+ using rvm: rvm install 2.x", "percentage": 99}, {"solution": "Or upgrade system Ruby version to meet Sass requirements", "percentage": 97}]'::jsonb, 'Ruby version management, RVM knowledge', 'Sass gem installs successfully, compilation works', 'Ruby version < 2.0.0, outdated Ruby installation', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/45391974/travis-build-error-sass-requires-ruby-version-2-0-0', 'admin:1764261662'),

('Sass custom function type checking error', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use type-of() to check variable types: @if type-of($val) == ''number''", "percentage": 98}, {"solution": "Validate input types before operations to prevent errors", "percentage": 96}]'::jsonb, 'Type checking functions, value validation', 'Custom functions handle various types without errors', 'Not checking types, assuming variable types', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/23277103/sass-check-which-kind-of-value-a-variable-has', 'admin:1764261662'),

('Sass list/array iteration with @each incorrect order', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Map iteration: @each $key, $value in $map (key, value order)", "percentage": 99}, {"solution": "For lists use: @each $item in $list", "percentage": 98}]'::jsonb, '@each loop syntax for maps and lists', 'Maps and lists iterate in correct order', 'Reversed key-value order in @each, wrong iteration syntax', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/53129741/each-loop-using-map-get', 'admin:1764261662'),

('Sass string manipulation with str functions', 'sass-css-preprocessor', 'LOW', '[{"solution": "Use str-index() to find substring position, str-slice() to extract", "percentage": 95}, {"solution": "Remember string functions return strings, use carefully", "percentage": 93}]'::jsonb, 'Sass string function knowledge', 'String operations produce correct substrings', 'Wrong function choice, not handling string return types', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/32376461/how-to-split-a-string-into-two-lists-of-numbers-in-sass', 'admin:1764261662'),

('Sass @mixin parameter default value syntax', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use @mixin name($param: defaultValue) syntax for optional parameters", "percentage": 99}, {"solution": "Parameters without defaults are required when including mixin", "percentage": 98}]'::jsonb, 'Mixin parameter syntax', 'Mixins accept optional parameters, defaults apply correctly', 'Missing default syntax, incorrect parameter declaration', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/5456467/syntax-for-if-else-condition-in-scss-mixin', 'admin:1764261662'),

('Sass variable scope in nested selectors', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Variables declared in nested blocks have limited scope", "percentage": 97}, {"solution": "Declare variables at file/root level for global access", "percentage": 98}]'::jsonb, 'Variable scope rules in nesting', 'Variables accessible in correct scope, no undefined errors', 'Using nested variable declarations outside scope', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/12365703/scss-variable-scope', 'admin:1764261662'),

('Sass placeholder selector scope limitation', 'sass-css-preprocessor', 'LOW', '[{"solution": "Use %placeholder selectors for @extend-only classes", "percentage": 98}, {"solution": "Placeholders can be scoped within media queries but extend cannot cross", "percentage": 96}]'::jsonb, 'Placeholder selector (@extend) knowledge', 'Placeholders generate correct output when extended', 'Trying to extend placeholders across media query boundaries', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/23742080/scope-of-the-extend-only-selectors-placeholders-in-sass', 'admin:1764261662'),

('Sass function with nested conditionals', 'sass-css-preprocessor', 'MEDIUM', '[{"solution": "Use @if/@else blocks to handle multiple conditions in functions", "percentage": 97}, {"solution": "Ensure all code paths return a value in Sass functions", "percentage": 96}]'::jsonb, 'Conditional function logic, return values', 'Functions execute all branches and return correct values', 'Missing @return statements, incomplete condition coverage', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/39985409/error-handling-in-sass', 'admin:1764261662');
