INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('TimeoutException: Timed out waiting for broker response', 'apache-kafka', 'HIGH', '[{"solution": "Increase broker.socket.request.max.bytes", "percentage": 93}, {"solution": "Check broker connectivity", "percentage": 93}, {"solution": "Adjust request.timeout.ms", "percentage": 93}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without TimeoutException occurring', 'Not implementing retry logic for TimeoutException', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-1', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('LEADER_NOT_AVAILABLE: No leader elected for partition', 'apache-kafka', 'CRITICAL', '[{"solution": "Ensure all brokers are running", "percentage": 94}, {"solution": "Check ZooKeeper connectivity", "percentage": 94}, {"solution": "Verify broker configuration", "percentage": 94}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without LEADER_NOT_AVAILABLE occurring', 'Not implementing retry logic for LEADER_NOT_AVAILABLE', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-2', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NOT_ENOUGH_REPLICAS: Insufficient in-sync replicas', 'apache-kafka', 'HIGH', '[{"solution": "Reduce min.insync.replicas setting", "percentage": 95}, {"solution": "Ensure replication factor is sufficient", "percentage": 95}, {"solution": "Check broker health", "percentage": 95}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without NOT_ENOUGH_REPLICAS occurring', 'Not implementing retry logic for NOT_ENOUGH_REPLICAS', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-3', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('OFFSET_OUT_OF_RANGE: Consumer offset beyond available data', 'apache-kafka', 'HIGH', '[{"solution": "Use auto.offset.reset=earliest", "percentage": 96}, {"solution": "Reset consumer group offset", "percentage": 96}, {"solution": "Check log retention", "percentage": 96}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without OFFSET_OUT_OF_RANGE occurring', 'Not implementing retry logic for OFFSET_OUT_OF_RANGE', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-4', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('GROUP_COORDINATOR_NOT_AVAILABLE: Coordinator unreachable', 'apache-kafka', 'MEDIUM', '[{"solution": "Ensure __consumer_offsets topic exists", "percentage": 92}, {"solution": "Check broker availability", "percentage": 92}, {"solution": "Verify group configuration", "percentage": 92}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without GROUP_COORDINATOR_NOT_AVAILABLE occurring', 'Not implementing retry logic for GROUP_COORDINATOR_NOT_AVAILABLE', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-5', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('REBALANCE_IN_PROGRESS: Consumer group rebalancing', 'apache-kafka', 'MEDIUM', '[{"solution": "Implement exponential backoff", "percentage": 93}, {"solution": "Increase session timeout", "percentage": 93}, {"solution": "Reduce poll() timeout", "percentage": 93}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without REBALANCE_IN_PROGRESS occurring', 'Not implementing retry logic for REBALANCE_IN_PROGRESS', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-6', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NotLeaderOrFollowerException: Broker not leader', 'apache-kafka', 'HIGH', '[{"solution": "Refresh metadata from broker", "percentage": 94}, {"solution": "Verify broker leadership", "percentage": 94}, {"solution": "Check network connectivity", "percentage": 94}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without NotLeaderOrFollowerException occurring', 'Not implementing retry logic for NotLeaderOrFollowerException', 0.9, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-7', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ConnectionResetException: Broker reset connection', 'apache-kafka', 'MEDIUM', '[{"solution": "Check broker socket settings", "percentage": 95}, {"solution": "Verify producer timeout", "percentage": 95}, {"solution": "Monitor broker resources", "percentage": 95}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without ConnectionResetException occurring', 'Not implementing retry logic for ConnectionResetException', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-8', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('OffsetCommitFailedException: Offset commit failed', 'apache-kafka', 'MEDIUM', '[{"solution": "Increase offsets.commit.timeout.ms", "percentage": 96}, {"solution": "Verify __consumer_offsets exists", "percentage": 96}, {"solution": "Check coordinator availability", "percentage": 96}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without OffsetCommitFailedException occurring', 'Not implementing retry logic for OffsetCommitFailedException', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-9', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('FetchSessionClosedException: Fetch session closed', 'apache-kafka', 'LOW', '[{"solution": "Update Kafka client to 2.3+", "percentage": 92}, {"solution": "Tune connections.max.idle.ms", "percentage": 92}, {"solution": "Check fetch configuration", "percentage": 92}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without FetchSessionClosedException occurring', 'Not implementing retry logic for FetchSessionClosedException', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-10', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('BrokerNotAvailableException: No available broker', 'apache-kafka', 'CRITICAL', '[{"solution": "Start missing brokers", "percentage": 93}, {"solution": "Check broker startup logs", "percentage": 93}, {"solution": "Verify ZooKeeper connectivity", "percentage": 93}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without BrokerNotAvailableException occurring', 'Not implementing retry logic for BrokerNotAvailableException', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-11', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('InvalidTopicException: Topic does not exist', 'apache-kafka', 'MEDIUM', '[{"solution": "Create topic with kafka-topics.sh", "percentage": 94}, {"solution": "Verify topic name", "percentage": 94}, {"solution": "Check auto.create.topics.enable", "percentage": 94}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without InvalidTopicException occurring', 'Not implementing retry logic for InvalidTopicException', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-12', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('SerializationException: Failed to serialize', 'apache-kafka', 'MEDIUM', '[{"solution": "Verify serializer implementation", "percentage": 95}, {"solution": "Use schema registry", "percentage": 95}, {"solution": "Check message value type", "percentage": 95}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without SerializationException occurring', 'Not implementing retry logic for SerializationException', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-13', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('DeserializationException: Failed to deserialize', 'apache-kafka', 'MEDIUM', '[{"solution": "Use default.deserialization.exception.handler", "percentage": 96}, {"solution": "Enable error handling", "percentage": 96}, {"solution": "Implement custom deserializer", "percentage": 96}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without DeserializationException occurring', 'Not implementing retry logic for DeserializationException', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-14', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('KafkaTimeoutException: Operation exceeded timeout', 'apache-kafka', 'HIGH', '[{"solution": "Increase connections.max.idle.ms", "percentage": 92}, {"solution": "Increase request.timeout.ms", "percentage": 92}, {"solution": "Optimize broker processing", "percentage": 92}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without KafkaTimeoutException occurring', 'Not implementing retry logic for KafkaTimeoutException', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-15', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('IllegalStateException: Invalid consumer/producer state', 'apache-kafka', 'LOW', '[{"solution": "Close properly before reuse", "percentage": 93}, {"solution": "Avoid concurrent access", "percentage": 93}, {"solution": "Use try-with-resources", "percentage": 93}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without IllegalStateException occurring', 'Not implementing retry logic for IllegalStateException', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-16', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ProducerFenced: Another producer with same ID', 'apache-kafka', 'LOW', '[{"solution": "Ensure single producer per ID", "percentage": 94}, {"solution": "Increase replication factor", "percentage": 94}, {"solution": "Use unique transactional IDs", "percentage": 94}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without ProducerFenced occurring', 'Not implementing retry logic for ProducerFenced', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-17', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('OutOfOrderSequenceException: Sequence out of order', 'apache-kafka', 'LOW', '[{"solution": "Enable idempotent producer", "percentage": 95}, {"solution": "Set max.in.flight.requests=1", "percentage": 95}, {"solution": "Check sequence validation", "percentage": 95}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without OutOfOrderSequenceException occurring', 'Not implementing retry logic for OutOfOrderSequenceException', 0.9, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-18', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('DuplicateSequenceException: Duplicate detected', 'apache-kafka', 'LOW', '[{"solution": "Verify idempotent producer", "percentage": 96}, {"solution": "Check log compaction", "percentage": 96}, {"solution": "Implement deduplication", "percentage": 96}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without DuplicateSequenceException occurring', 'Not implementing retry logic for DuplicateSequenceException', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-19', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ControlBatchTooLarge: Message batch too large', 'apache-kafka', 'LOW', '[{"solution": "Increase message.max.bytes", "percentage": 92}, {"solution": "Reduce partition updates", "percentage": 92}, {"solution": "Upgrade broker", "percentage": 92}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without ControlBatchTooLarge occurring', 'Not implementing retry logic for ControlBatchTooLarge', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-20', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('UnsupportedCompressionType: Compression not supported', 'apache-kafka', 'LOW', '[{"solution": "Use supported compression type", "percentage": 93}, {"solution": "Verify broker setting", "percentage": 93}, {"solution": "Check version compatibility", "percentage": 93}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without UnsupportedCompressionType occurring', 'Not implementing retry logic for UnsupportedCompressionType', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-21', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('InvalidProducerIdMapping: Producer ID invalid', 'apache-kafka', 'LOW', '[{"solution": "Recreate producer instance", "percentage": 94}, {"solution": "Check broker metadata", "percentage": 94}, {"solution": "Restart brokers", "percentage": 94}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without InvalidProducerIdMapping occurring', 'Not implementing retry logic for InvalidProducerIdMapping', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-22', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('AbortedTransactionException: Transaction aborted', 'apache-kafka', 'LOW', '[{"solution": "Set isolation.level=read_uncommitted", "percentage": 95}, {"solution": "Increase session timeout", "percentage": 95}, {"solution": "Check transaction timeout", "percentage": 95}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without AbortedTransactionException occurring', 'Not implementing retry logic for AbortedTransactionException', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-23', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('RequestTimedOutException: Request timeout', 'apache-kafka', 'MEDIUM', '[{"solution": "Increase request timeout", "percentage": 96}, {"solution": "Check broker load", "percentage": 96}, {"solution": "Optimize processing", "percentage": 96}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without RequestTimedOutException occurring', 'Not implementing retry logic for RequestTimedOutException', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-24', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('MessageSizeTooLargeException: Message too large', 'apache-kafka', 'MEDIUM', '[{"solution": "Increase max.message.bytes", "percentage": 92}, {"solution": "Check broker configuration", "percentage": 92}, {"solution": "Reduce message size", "percentage": 92}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without MessageSizeTooLargeException occurring', 'Not implementing retry logic for MessageSizeTooLargeException', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-25', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('StaleEpochException: Broker epoch stale', 'apache-kafka', 'LOW', '[{"solution": "Update broker metadata", "percentage": 93}, {"solution": "Restart broker if needed", "percentage": 93}, {"solution": "Check configuration", "percentage": 93}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without StaleEpochException occurring', 'Not implementing retry logic for StaleEpochException', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-26', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('OffsetsLoadInProgressException: Offsets loading', 'apache-kafka', 'MEDIUM', '[{"solution": "Wait for offsets to load", "percentage": 94}, {"solution": "Check broker state", "percentage": 94}, {"solution": "Verify connectivity", "percentage": 94}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without OffsetsLoadInProgressException occurring', 'Not implementing retry logic for OffsetsLoadInProgressException', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-27', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('AlreadyAssignedException: Topic already assigned', 'apache-kafka', 'LOW', '[{"solution": "Unsubscribe from topic first", "percentage": 95}, {"solution": "Use proper consumer API", "percentage": 95}, {"solution": "Check subscription logic", "percentage": 95}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without AlreadyAssignedException occurring', 'Not implementing retry logic for AlreadyAssignedException', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-28', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NotMemberForGroupException: Not group member', 'apache-kafka', 'MEDIUM', '[{"solution": "Rejoin consumer group", "percentage": 96}, {"solution": "Check group membership", "percentage": 96}, {"solution": "Verify group ID", "percentage": 96}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without NotMemberForGroupException occurring', 'Not implementing retry logic for NotMemberForGroupException', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-29', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('RebalanceInProgressException: Rebalance in progress', 'apache-kafka', 'MEDIUM', '[{"solution": "Wait for rebalance completion", "percentage": 92}, {"solution": "Implement retry logic", "percentage": 92}, {"solution": "Check consumer state", "percentage": 92}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without RebalanceInProgressException occurring', 'Not implementing retry logic for RebalanceInProgressException', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-30', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('IllegalGenerationException: Generation mismatch', 'apache-kafka', 'LOW', '[{"solution": "Rejoin consumer group", "percentage": 93}, {"solution": "Update generation ID", "percentage": 93}, {"solution": "Check group state", "percentage": 93}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without IllegalGenerationException occurring', 'Not implementing retry logic for IllegalGenerationException', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-31', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('CoordinatorNotAvailableException: Coordinator unavailable', 'apache-kafka', 'MEDIUM', '[{"solution": "Wait for coordinator", "percentage": 94}, {"solution": "Check broker state", "percentage": 94}, {"solution": "Verify metadata", "percentage": 94}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without CoordinatorNotAvailableException occurring', 'Not implementing retry logic for CoordinatorNotAvailableException', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-32', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('UnknownTopicOrPartitionException: Topic not found', 'apache-kafka', 'HIGH', '[{"solution": "Create topic first", "percentage": 95}, {"solution": "Verify topic name", "percentage": 95}, {"solution": "Check cluster state", "percentage": 95}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without UnknownTopicOrPartitionException occurring', 'Not implementing retry logic for UnknownTopicOrPartitionException', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-33', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('FencedInstanceIdException: Instance ID fenced', 'apache-kafka', 'LOW', '[{"solution": "Use unique instance IDs", "percentage": 96}, {"solution": "Check concurrent access", "percentage": 96}, {"solution": "Restart consumer", "percentage": 96}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without FencedInstanceIdException occurring', 'Not implementing retry logic for FencedInstanceIdException', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-34', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('InconsistentGroupProtocolException: Protocol mismatch', 'apache-kafka', 'LOW', '[{"solution": "Use consistent protocol", "percentage": 92}, {"solution": "Check group config", "percentage": 92}, {"solution": "Update consumers", "percentage": 92}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without InconsistentGroupProtocolException occurring', 'Not implementing retry logic for InconsistentGroupProtocolException', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-35', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('InvalidSessionTimeoutException: Timeout invalid', 'apache-kafka', 'LOW', '[{"solution": "Set session.timeout.ms within range", "percentage": 93}, {"solution": "Check configuration", "percentage": 93}, {"solution": "Verify settings", "percentage": 93}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without InvalidSessionTimeoutException occurring', 'Not implementing retry logic for InvalidSessionTimeoutException', 0.9, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-36', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('GroupMaxSizeReachedException: Group at max size', 'apache-kafka', 'LOW', '[{"solution": "Reduce consumer group size", "percentage": 94}, {"solution": "Increase max.group.size", "percentage": 94}, {"solution": "Check configuration", "percentage": 94}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without GroupMaxSizeReachedException occurring', 'Not implementing retry logic for GroupMaxSizeReachedException', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-37', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NetworkException: Network communication failed', 'apache-kafka', 'MEDIUM', '[{"solution": "Check network connectivity", "percentage": 95}, {"solution": "Verify firewall", "percentage": 95}, {"solution": "Check broker availability", "percentage": 95}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without NetworkException occurring', 'Not implementing retry logic for NetworkException', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-38', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('RetriableException: Operation failed retryable', 'apache-kafka', 'HIGH', '[{"solution": "Implement retry logic", "percentage": 96}, {"solution": "Check broker state", "percentage": 96}, {"solution": "Verify configuration", "percentage": 96}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without RetriableException occurring', 'Not implementing retry logic for RetriableException', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-39', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('UnknownServerException: Unknown broker error', 'apache-kafka', 'MEDIUM', '[{"solution": "Check broker logs", "percentage": 92}, {"solution": "Verify configuration", "percentage": 92}, {"solution": "Update broker", "percentage": 92}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without UnknownServerException occurring', 'Not implementing retry logic for UnknownServerException', 0.8, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-40', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('InvalidConfigException: Invalid configuration', 'apache-kafka', 'MEDIUM', '[{"solution": "Verify config values", "percentage": 93}, {"solution": "Check documentation", "percentage": 93}, {"solution": "Fix invalid settings", "percentage": 93}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without InvalidConfigException occurring', 'Not implementing retry logic for InvalidConfigException', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-41', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('UnsupportedVersionException: Version not supported', 'apache-kafka', 'MEDIUM', '[{"solution": "Update Kafka client", "percentage": 94}, {"solution": "Check broker version", "percentage": 94}, {"solution": "Verify compatibility", "percentage": 94}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without UnsupportedVersionException occurring', 'Not implementing retry logic for UnsupportedVersionException', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-42', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('UnauthorizedException: Not authorized', 'apache-kafka', 'MEDIUM', '[{"solution": "Add permissions", "percentage": 95}, {"solution": "Check ACL settings", "percentage": 95}, {"solution": "Verify credentials", "percentage": 95}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without UnauthorizedException occurring', 'Not implementing retry logic for UnauthorizedException', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-43', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('LogDirFailureException: Log directory failed', 'apache-kafka', 'CRITICAL', '[{"solution": "Check disk space", "percentage": 96}, {"solution": "Verify permissions", "percentage": 96}, {"solution": "Repair file system", "percentage": 96}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without LogDirFailureException occurring', 'Not implementing retry logic for LogDirFailureException', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-44', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('SaslAuthenticationException: SASL auth failed', 'apache-kafka', 'MEDIUM', '[{"solution": "Verify credentials", "percentage": 92}, {"solution": "Check SASL config", "percentage": 92}, {"solution": "Update credentials", "percentage": 92}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without SaslAuthenticationException occurring', 'Not implementing retry logic for SaslAuthenticationException', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-45', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('InvalidTopicIdException: Topic ID invalid', 'apache-kafka', 'LOW', '[{"solution": "Verify topic ID", "percentage": 93}, {"solution": "Check cluster state", "percentage": 93}, {"solution": "Recreate topic", "percentage": 93}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without InvalidTopicIdException occurring', 'Not implementing retry logic for InvalidTopicIdException', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-46', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('PrincipalDeserializationException: Deserialize failed', 'apache-kafka', 'LOW', '[{"solution": "Check principal format", "percentage": 94}, {"solution": "Verify configuration", "percentage": 94}, {"solution": "Fix serialization", "percentage": 94}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without PrincipalDeserializationException occurring', 'Not implementing retry logic for PrincipalDeserializationException', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-47', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('DelegationTokenAuthorizationException: Token denied', 'apache-kafka', 'LOW', '[{"solution": "Check token permissions", "percentage": 95}, {"solution": "Verify token", "percentage": 95}, {"solution": "Update token", "percentage": 95}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without DelegationTokenAuthorizationException occurring', 'Not implementing retry logic for DelegationTokenAuthorizationException', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-48', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('DelegationTokenExpiredException: Token expired', 'apache-kafka', 'LOW', '[{"solution": "Refresh delegation token", "percentage": 96}, {"solution": "Check expiration", "percentage": 96}, {"solution": "Renew token", "percentage": 96}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without DelegationTokenExpiredException occurring', 'Not implementing retry logic for DelegationTokenExpiredException', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-49', 'admin:1764221365');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('InvalidPrincipalTypeException: Invalid type', 'apache-kafka', 'LOW', '[{"solution": "Use valid principal type", "percentage": 92}, {"solution": "Check configuration", "percentage": 92}, {"solution": "Verify setup", "percentage": 92}]'::jsonb, 'Kafka broker, proper client configuration', 'Error resolved without InvalidPrincipalTypeException occurring', 'Not implementing retry logic for InvalidPrincipalTypeException', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/kafka-50', 'admin:1764221365');