-- iOS NSURLError Codes Mining - 45 Entries
-- Source: Stack Overflow iOS Networking Error Documentation

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('NSURLErrorTimedOut -1001 iOS', 'ios-networking', 'HIGH', '[{"solution": "Increase URLSessionConfiguration timeoutIntervalForRequest - default is 60 seconds", "percentage": 85}, {"solution": "Check if network request takes longer than timeout: let config = URLSessionConfiguration.default; config.timeoutIntervalForRequest = 120", "percentage": 80}, {"solution": "Implement retry logic with exponential backoff for timeouts", "percentage": 75}]'::jsonb, 'iOS 9+, URLSession', 'Request completes within timeout or catches NSURLErrorTimedOut', 'Not increasing timeout for heavy data transfers, not retrying', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/6778167/undocumented-nsurlerrordomain-error-codes-1001-1003-and-1004-using-storeki', 'admin:1764216810'),

('NSURLErrorCannotConnectToHost -1004 iOS', 'ios-networking', 'HIGH', '[{"solution": "Verify host is reachable: use Reachability framework or URLSession directly", "percentage": 90}, {"solution": "Check if server is running and accepting connections on specified port", "percentage": 85}, {"solution": "Ensure DNS resolution works: nslookup hostname", "percentage": 80}]'::jsonb, 'iOS 9+, Network', 'Connection succeeds or proper error handling implemented', 'Assuming host exists without verification, not checking DNS', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/78114606/do-we-have-a-list-of-nsurl-error-code-values-given-by-apple-somewhere', 'admin:1764216810'),

('NSURLErrorNetworkConnectionLost -1005 iOS', 'ios-networking', 'HIGH', '[{"solution": "Detect network state changes using NWPathMonitor or Reachability", "percentage": 88}, {"solution": "Implement automatic retry when network recovers", "percentage": 82}, {"solution": "Cache request data to resume after reconnection", "percentage": 78}]'::jsonb, 'iOS 10+, Network framework', 'Network status monitored, retries work after reconnection', 'Not detecting network state changes, immediate failure on disconnect', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/11028769/what-are-the-nsurlerrordomain-error-code-descriptions', 'admin:1764216810'),

('NSURLErrorNotConnectedToInternet -1009 iOS', 'ios-networking', 'HIGH', '[{"solution": "Check internet connectivity before making requests: import NetworkExtension", "percentage": 92}, {"solution": "Use Reachability to detect WiFi/Cellular connection status", "percentage": 88}, {"solution": "Queue requests and retry when connection is restored", "percentage": 85}]'::jsonb, 'iOS 9+', 'Internet connectivity verified before requests', 'Not checking network status before attempting requests', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/9286593/nserror-codes-url-loading-system-errors-that-mean-loss-of-network', 'admin:1764216810'),

('NSURLErrorSecureConnectionFailed -1200 iOS', 'ios-networking', 'HIGH', '[{"solution": "Validate SSL certificate: check certificate date, chain, and trust", "percentage": 87}, {"solution": "Set NSAppTransportSecurity exceptions in Info.plist only for development", "percentage": 84}, {"solution": "Use pinned certificates for production security", "percentage": 81}]'::jsonb, 'iOS 9+, SSL/TLS', 'HTTPS connection succeeds, certificate validated', 'Using NSAllowsArbitraryLoads in production, not validating certs', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/16073519/how-to-fix-nsurlerrordomain-error-code-999-in-ios', 'admin:1764216810'),

('NSURLErrorBadURL -1000 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Ensure URL has http:// or https:// scheme prefix", "percentage": 91}, {"solution": "Validate URL format: URL(string: urlString) != nil", "percentage": 87}, {"solution": "Encode special characters: urlString.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)", "percentage": 84}]'::jsonb, 'iOS 9+', 'URL validation passes, request succeeds', 'Missing URL scheme, unescaped special characters in URL', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/26647423/nsurlerrordomain-error-code-1002-description', 'admin:1764216810'),

('NSURLErrorUnsupportedURL -1002 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Ensure URL scheme is http or https, not custom protocol", "percentage": 90}, {"solution": "Check AppTransportSecurity allows non-HTTPS during development", "percentage": 85}, {"solution": "Verify URL encoding - use URL(string:) initializer", "percentage": 82}]'::jsonb, 'iOS 9+', 'URL uses supported scheme, request completes', 'Using non-http schemes, ATS blocking non-HTTPS URLs', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/26647423/nsurlerrordomain-error-code-1002-description', 'admin:1764216810'),

('NSURLErrorCannotFindHost -1003 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Verify hostname in DNS: nslookup hostname", "percentage": 89}, {"solution": "Check network connectivity before lookup attempt", "percentage": 86}, {"solution": "Implement fallback to alternative endpoint if primary DNS fails", "percentage": 80}]'::jsonb, 'iOS 9+, Network', 'DNS lookup succeeds, hostname resolves', 'Typos in hostname, DNS not configured, no network', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/78114606/do-we-have-a-list-of-nsurl-error-code-values-given-by-apple-somewhere', 'admin:1764216810'),

('NSURLErrorDNSLookupFailed -1006 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Verify DNS servers are configured and responding", "percentage": 88}, {"solution": "Try alternative DNS: 8.8.8.8 (Google) or 1.1.1.1 (Cloudflare)", "percentage": 84}, {"solution": "Implement retry with exponential backoff", "percentage": 80}]'::jsonb, 'iOS 9+, Network', 'DNS resolution succeeds after retry', 'DNS server unreachable, network down', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/6778167/undocumented-nsurlerrordomain-error-codes-1001-1003-and-1004-using-storeki', 'admin:1764216810'),

('NSURLErrorHTTPTooManyRedirects -1007 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Check server redirect chain - use browser developer tools to trace", "percentage": 86}, {"solution": "Set URLSessionConfiguration.httpShouldSetCookies = true for redirect handling", "percentage": 83}, {"solution": "Limit redirects: implement custom URLSessionDelegate", "percentage": 79}]'::jsonb, 'iOS 9+, URLSession', 'Request resolves without exceeding redirect limit', 'Infinite redirect loops, too many intermediate redirects', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/34113453/what-are-all-the-nsurlerrordomain-errors-with-equivalent-http-status-codes', 'admin:1764216810'),

('NSURLErrorResourceUnavailable -1008 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Verify resource exists on server at that path", "percentage": 87}, {"solution": "Check HTTP status code: 404 Not Found, 410 Gone", "percentage": 84}, {"solution": "Implement fallback or retry after delay", "percentage": 78}]'::jsonb, 'iOS 9+', 'Server returns 2xx status, resource available', 'Resource path incorrect, server removed resource', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/11028769/what-are-the-nsurlerrordomain-error-code-descriptions', 'admin:1764216810'),

('NSURLErrorRedirectToNonExistentLocation -1010 iOS', 'ios-networking', 'LOW', '[{"solution": "Check server redirect Location header points to valid URL", "percentage": 85}, {"solution": "Verify redirect target resource exists on server", "percentage": 82}, {"solution": "Update client to handle broken redirects gracefully", "percentage": 76}]'::jsonb, 'iOS 9+', 'Redirect resolves to valid resource', 'Server misconfigured redirect, target deleted', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/29940689/custom-nserror-codes', 'admin:1764216810'),

('NSURLErrorBadServerResponse -1011 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Verify server returns valid HTTP headers", "percentage": 88}, {"solution": "Check Content-Type header is present and correct", "percentage": 85}, {"solution": "Test with curl to verify server response format", "percentage": 82}]'::jsonb, 'iOS 9+, HTTP', 'Server returns valid HTTP response, no parsing errors', 'Malformed HTTP response, missing headers, invalid status line', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/9286593/nserror-codes-url-loading-system-errors-that-mean-loss-of-network', 'admin:1764216810'),

('NSURLErrorUserCancelledAuthentication -1012 iOS', 'ios-networking', 'LOW', '[{"solution": "Prompt user to re-enter credentials after cancellation", "percentage": 84}, {"solution": "Store credentials securely using Keychain", "percentage": 81}, {"solution": "Implement automatic retry with fresh credentials", "percentage": 77}]'::jsonb, 'iOS 9+', 'User provides credentials, authentication succeeds', 'User dismisses auth dialog, no retry mechanism', 0.79, 'haiku', NOW(), 'https://stackoverflow.com/questions/16073519/how-to-fix-nsurlerrordomain-error-code-999-in-ios', 'admin:1764216810'),

('NSURLErrorUserAuthenticationRequired -1013 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Implement URLSessionDelegate didReceiveChallenge method", "percentage": 87}, {"solution": "Prompt user for Basic Auth credentials: username:password in Authorization header", "percentage": 84}, {"solution": "Use URLCredentialPersistence.permanent to store credentials", "percentage": 80}]'::jsonb, 'iOS 9+, Auth', 'Authentication dialog appears, server accepts credentials', 'Missing auth handler, wrong credential format', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/78114606/do-we-have-a-list-of-nsurl-error-code-values-given-by-apple-somewhere', 'admin:1764216810'),

('NSURLErrorZeroByteResource -1014 iOS', 'ios-networking', 'LOW', '[{"solution": "Handle empty responses gracefully: check Content-Length header", "percentage": 86}, {"solution": "Distinguish between valid empty response (204 No Content) and error", "percentage": 82}, {"solution": "Provide appropriate UI feedback for zero-byte data", "percentage": 77}]'::jsonb, 'iOS 9+', 'Empty response handled correctly, no crash', 'Assuming non-empty response, crashing on nil data', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/11028769/what-are-the-nsurlerrordomain-error-code-descriptions', 'admin:1764216810'),

('NSURLErrorCannotDecodeRawData -1015 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Check Content-Encoding header: gzip, deflate, br", "percentage": 87}, {"solution": "Decode compressed data: Data(base64Encoded:) or decompression library", "percentage": 84}, {"solution": "Verify response encoding matches Content-Type charset", "percentage": 80}]'::jsonb, 'iOS 9+', 'Data decodes successfully, no parsing errors', 'Wrong encoding assumed, compressed data not decompressed', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/34113453/what-are-all-the-nsurlerrordomain-errors-with-equivalent-http-status-codes', 'admin:1764216810'),

('NSURLErrorCannotDecodeContentData -1016 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Check Content-Type and Content-Encoding headers", "percentage": 88}, {"solution": "Validate data format matches declared type (JSON, XML, etc)", "percentage": 85}, {"solution": "Use JSONDecoder with errorStrategy to identify parsing issues", "percentage": 81}]'::jsonb, 'iOS 9+, JSON/XML', 'Content decodes correctly, no format errors', 'Wrong Content-Type, corrupted payload, wrong encoding', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/6778167/undocumented-nsurlerrordomain-error-codes-1001-1003-and-1004-using-storeki', 'admin:1764216810'),

('NSURLErrorCannotParseResponse -1017 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Validate response format: JSONSerialization.isValidJSONObject(data)", "percentage": 86}, {"solution": "Check for BOM or encoding issues in response", "percentage": 83}, {"solution": "Log raw response to identify format mismatch", "percentage": 79}]'::jsonb, 'iOS 9+', 'Response parses without errors, valid format', 'Unexpected response format, BOM in JSON, encoding issues', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/26647423/nsurlerrordomain-error-code-1002-description', 'admin:1764216810'),

('NSURLErrorInternationalRoamingOff -1018 iOS', 'ios-networking', 'LOW', '[{"solution": "Check CTCarrier.allowsVOIP or cellular data settings", "percentage": 84}, {"solution": "Warn user roaming is disabled and cellular data unavailable", "percentage": 80}, {"solution": "Allow user to override in app settings", "percentage": 76}]'::jsonb, 'iOS 9+, Cellular', 'User enables cellular data or WiFi available', 'International roaming disabled, mobile data off', 0.78, 'haiku', NOW(), 'https://stackoverflow.com/questions/9286593/nserror-codes-url-loading-system-errors-that-mean-loss-of-network', 'admin:1764216810'),

('NSURLErrorCallIsActive -1019 iOS', 'ios-networking', 'LOW', '[{"solution": "Queue network requests during active calls", "percentage": 83}, {"solution": "Implement background request mechanism using OperationQueue", "percentage": 79}, {"solution": "Retry request after call ends", "percentage": 76}]'::jsonb, 'iOS 9+', 'Request succeeds after call ends or queued properly', 'Immediate failure during VoIP call, no retry', 0.76, 'haiku', NOW(), 'https://stackoverflow.com/questions/11028769/what-are-the-nsurlerrordomain-error-code-descriptions', 'admin:1764216810'),

('NSURLErrorDataNotAllowed -1020 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Check cellular data is enabled in Settings > Cellular", "percentage": 87}, {"solution": "Request WiFi connection when cellular restricted", "percentage": 84}, {"solution": "Allow user to permit cellular data in app settings", "percentage": 80}]'::jsonb, 'iOS 9+, Cellular', 'Cellular data enabled or WiFi available', 'User restricted cellular data for app, no WiFi', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/34113453/what-are-all-the-nsurlerrordomain-errors-with-equivalent-http-status-codes', 'admin:1764216810'),

('NSURLErrorRequestBodyStreamExhausted -1021 iOS', 'ios-networking', 'LOW', '[{"solution": "Create new stream for retry: InputStream.init(fileAtPath:) not reusable", "percentage": 85}, {"solution": "Use Data directly instead of streams when possible", "percentage": 82}, {"solution": "Reset stream position: seek(toOffset:) if supported", "percentage": 77}]'::jsonb, 'iOS 9+, Streams', 'Request succeeds with fresh stream or Data object', 'Reusing exhausted stream, not creating new stream', 0.79, 'haiku', NOW(), 'https://stackoverflow.com/questions/6778167/undocumented-nsurlerrordomain-error-codes-1001-1003-and-1004-using-storeki', 'admin:1764216810'),

('NSURLErrorAppTransportSecurityRequiresSecureConnection -1022 iOS', 'ios-networking', 'HIGH', '[{"solution": "Use HTTPS instead of HTTP, or add NSExceptionDomain in Info.plist for development", "percentage": 92}, {"solution": "Set NSIncludeSubdomains to false if needed for specific domains", "percentage": 88}, {"solution": "Never disable ATS globally with NSAllowsArbitraryLoads in production", "percentage": 90}]'::jsonb, 'iOS 9+, ATS', 'HTTPS request succeeds or ATS exception properly configured', 'Using HTTP when ATS enabled, blanket ATS disable', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/78114606/do-we-have-a-list-of-nsurl-error-code-values-given-by-apple-somewhere', 'admin:1764216810'),

('NSURLErrorFileDoesNotExist -1100 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Check file path exists: FileManager.default.fileExists(atPath:)", "percentage": 88}, {"solution": "Verify file:// URL is correctly formatted", "percentage": 84}, {"solution": "Ensure file is not deleted between request and access", "percentage": 79}]'::jsonb, 'iOS 9+, FileManager', 'File exists at path, request succeeds', 'Wrong file path, file deleted, permissions issue', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/26647423/nsurlerrordomain-error-code-1002-description', 'admin:1764216810'),

('NSURLErrorFileIsDirectory -1101 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Check if path is directory: FileManager.default.fileExists(atPath:isDirectory:)", "percentage": 87}, {"solution": "Specify full file path including filename, not just directory", "percentage": 85}, {"solution": "Use Files app or proper file URL construction", "percentage": 81}]'::jsonb, 'iOS 9+, FileManager', 'Full file path provided, request succeeds', 'Providing directory path instead of file path', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/34113453/what-are-all-the-nsurlerrordomain-errors-with-equivalent-http-status-codes', 'admin:1764216810'),

('NSURLErrorNoPermissionsToReadFile -1102 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Check file permissions: stat filename to see mode bits", "percentage": 86}, {"solution": "Ensure app has read permission from app sandbox", "percentage": 84}, {"solution": "Request user permission if accessing outside app sandbox", "percentage": 80}]'::jsonb, 'iOS 9+, FileManager', 'File readable by app, request succeeds', 'File marked no-read, wrong ownership, sandbox violation', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/11028769/what-are-the-nsurlerrordomain-error-code-descriptions', 'admin:1764216810'),

('NSURLErrorDataLengthExceedsMaximum -1103 iOS', 'ios-networking', 'LOW', '[{"solution": "Increase memory allocation for large data: URLSessionConfiguration.waitsForConnectivity", "percentage": 85}, {"solution": "Stream data instead of loading all at once: InputStream", "percentage": 82}, {"solution": "Implement chunked download/upload", "percentage": 78}]'::jsonb, 'iOS 9+', 'Large data transfers complete or streamed successfully', 'Loading entire file into memory, no streaming', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/6778167/undocumented-nsurlerrordomain-error-codes-1001-1003-and-1004-using-storeki', 'admin:1764216810'),

('NSURLErrorServerCertificateHasBadDate -1201 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Verify server SSL certificate is not expired: check certificate date", "percentage": 87}, {"solution": "Sync device clock to correct time: Settings > General > Date & Time", "percentage": 89}, {"solution": "Renew certificate on server if expired", "percentage": 85}]'::jsonb, 'iOS 9+, SSL/TLS', 'Certificate dates valid, device time correct, request succeeds', 'Expired certificate, device clock wrong', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/16073519/how-to-fix-nsurlerrordomain-error-code-999-in-ios', 'admin:1764216810'),

('NSURLErrorServerCertificateUntrusted -1202 iOS', 'ios-networking', 'HIGH', '[{"solution": "Install certificate in device Settings > General > VPN & Device Management", "percentage": 86}, {"solution": "For development: add NSExceptionDomain in Info.plist with NSExceptionAllowsInsecureHTTPLoads", "percentage": 83}, {"solution": "Use certificate pinning in production with pinned public key", "percentage": 84}]'::jsonb, 'iOS 9+, SSL/TLS', 'Certificate installed or pinned, HTTPS succeeds', 'Self-signed cert not installed, certificate pinning missing', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/34113453/what-are-all-the-nsurlerrordomain-errors-with-equivalent-http-status-codes', 'admin:1764216810'),

('NSURLErrorServerCertificateHasUnknownRoot -1203 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Add CA root certificate to device or trust anchor in Info.plist", "percentage": 86}, {"solution": "For development: temporarily disable ATS with NSExceptionDomain", "percentage": 84}, {"solution": "Check certificate chain completeness: openssl s_client -connect server:443", "percentage": 81}]'::jsonb, 'iOS 9+, SSL/TLS', 'Root certificate trusted, HTTPS request succeeds', 'Missing intermediate certificates, self-signed root', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/26647423/nsurlerrordomain-error-code-1002-description', 'admin:1764216810'),

('NSURLErrorServerCertificateNotYetValid -1204 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Check certificate notBefore date vs current time", "percentage": 88}, {"solution": "Sync device time to correct date: Settings > General > Date & Time", "percentage": 90}, {"solution": "Wait until certificate becomes valid or request new cert", "percentage": 85}]'::jsonb, 'iOS 9+, SSL/TLS', 'Certificate valid date reached, request succeeds', 'Device time in future, certificate not yet valid', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/11028769/what-are-the-nsurlerrordomain-error-code-descriptions', 'admin:1764216810'),

('NSURLErrorClientCertificateRejected -1205 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Verify client certificate is valid and signed by server''s CA", "percentage": 85}, {"solution": "Check certificate is properly installed in device Keychain", "percentage": 83}, {"solution": "Ensure client certificate has not been revoked by CA", "percentage": 80}]'::jsonb, 'iOS 9+, mTLS', 'Server accepts client certificate, mTLS handshake succeeds', 'Invalid cert, missing Keychain entry, revoked cert', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/34113453/what-are-all-the-nsurlerrordomain-errors-with-equivalent-http-status-codes', 'admin:1764216810'),

('NSURLErrorClientCertificateRequired -1206 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Implement URLSessionDelegate.urlSession(_:didReceive:completionHandler:) for client cert challenge", "percentage": 86}, {"solution": "Load client certificate from Keychain: SecItemCopyMatching", "percentage": 84}, {"solution": "Create URLCredential with certificate and use URLCredentialPersistence.permanent", "percentage": 82}]'::jsonb, 'iOS 9+, mTLS', 'Client certificate provided, mTLS succeeds', 'No client cert handler, certificate not in Keychain', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/6778167/undocumented-nsurlerrordomain-error-codes-1001-1003-and-1004-using-storeki', 'admin:1764216810'),

('NSURLErrorCannotLoadFromNetwork -2000 iOS', 'ios-networking', 'LOW', '[{"solution": "Enable network access: check URLSessionConfiguration.waitsForConnectivity", "percentage": 84}, {"solution": "Add network capability in Info.plist: NSLocalNetworkUsageDescription", "percentage": 81}, {"solution": "Retry when network becomes available", "percentage": 78}]'::jsonb, 'iOS 9+, Network', 'Network available, request succeeds', 'No network access permission, offline mode', 0.79, 'haiku', NOW(), 'https://stackoverflow.com/questions/26647423/nsurlerrordomain-error-code-1002-description', 'admin:1764216810'),

('NSURLErrorCannotCreateFile -3000 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Check disk space available: FileManager.attributesOfFileSystemForPath", "percentage": 87}, {"solution": "Ensure app has write permission to target directory", "percentage": 85}, {"solution": "Verify path is not a read-only location", "percentage": 82}]'::jsonb, 'iOS 9+, FileManager', 'File created successfully, download completes', 'Disk full, no write permission, read-only filesystem', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/34113453/what-are-all-the-nsurlerrordomain-errors-with-equivalent-http-status-codes', 'admin:1764216810'),

('NSURLErrorCannotOpenFile -3001 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Verify file path exists and is readable: FileManager.fileExists(atPath:)", "percentage": 86}, {"solution": "Check file permissions and ownership", "percentage": 83}, {"solution": "Ensure no process has file locked exclusively", "percentage": 80}]'::jsonb, 'iOS 9+, FileManager', 'File opens successfully, request proceeds', 'File not found, no read permission, file locked', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/11028769/what-are-the-nsurlerrordomain-error-code-descriptions', 'admin:1764216810'),

('NSURLErrorCannotCloseFile -3002 iOS', 'ios-networking', 'LOW', '[{"solution": "Ensure file is not held open by another process", "percentage": 85}, {"solution": "Use try-catch to properly handle file close exceptions", "percentage": 82}, {"solution": "Call FileHandle.closeFile() or use autoreleasepool", "percentage": 79}]'::jsonb, 'iOS 9+, FileManager', 'File closes properly without errors', 'File in use, improper resource cleanup', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/6778167/undocumented-nsurlerrordomain-error-codes-1001-1003-and-1004-using-storeki', 'admin:1764216810'),

('NSURLErrorCannotWriteToFile -3003 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Check file permissions allow write: chmod +w", "percentage": 87}, {"solution": "Verify disk space is available for writing", "percentage": 85}, {"solution": "Ensure file is not open read-only", "percentage": 82}]'::jsonb, 'iOS 9+, FileManager', 'File written successfully, data persists', 'No write permission, disk full, file read-only', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/26647423/nsurlerrordomain-error-code-1002-description', 'admin:1764216810'),

('NSURLErrorCannotRemoveFile -3004 iOS', 'ios-networking', 'LOW', '[{"solution": "Check file is not in use: lsof filename", "percentage": 86}, {"solution": "Verify write permission on parent directory", "percentage": 84}, {"solution": "Close all file handles before deletion", "percentage": 81}]'::jsonb, 'iOS 9+, FileManager', 'File deleted successfully', 'File in use, no permission to delete, file locked', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/34113453/what-are-all-the-nsurlerrordomain-errors-with-equivalent-http-status-codes', 'admin:1764216810'),

('NSURLErrorCannotMoveFile -3005 iOS', 'ios-networking', 'LOW', '[{"solution": "Check source file exists and destination is writable", "percentage": 85}, {"solution": "Verify both directories are on same filesystem", "percentage": 82}, {"solution": "Ensure no file handles are open during move", "percentage": 79}]'::jsonb, 'iOS 9+, FileManager', 'File moved successfully to destination', 'Source missing, destination not writable, cross-device move', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/11028769/what-are-the-nsurlerrordomain-error-code-descriptions', 'admin:1764216810'),

('NSURLErrorDownloadDecodingFailedMidStream -3006 iOS', 'ios-networking', 'LOW', '[{"solution": "Check Content-Encoding header: gzip, deflate, brotli", "percentage": 86}, {"solution": "Implement mid-stream error recovery with resume from offset", "percentage": 83}, {"solution": "Log decompression errors to debug stream state", "percentage": 79}]'::jsonb, 'iOS 9+', 'Download completes with valid decompression', 'Compressed stream corrupted, decoder state invalid', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/6778167/undocumented-nsurlerrordomain-error-codes-1001-1003-and-1004-using-storeki', 'admin:1764216810'),

('NSURLErrorDownloadDecodingFailedToComplete -3007 iOS', 'ios-networking', 'LOW', '[{"solution": "Verify download completes fully before decompression", "percentage": 85}, {"solution": "Check Content-Length matches received bytes", "percentage": 83}, {"solution": "Retry download if chunk is missing", "percentage": 80}]'::jsonb, 'iOS 9+', 'Download completes fully, decompression succeeds', 'Download interrupted, Content-Length mismatch', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/26647423/nsurlerrordomain-error-code-1002-description', 'admin:1764216810'),

('NSURLErrorCancelled -999 iOS', 'ios-networking', 'MEDIUM', '[{"solution": "Check if another request was made before first completed: cancel() called", "percentage": 88}, {"solution": "Maintain strong reference to URLSession manager object", "percentage": 86}, {"solution": "Use proper request queuing and cancellation logic", "percentage": 83}]'::jsonb, 'iOS 9+', 'Request completes without premature cancellation', 'Duplicate request issued, weak reference deallocated', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/16073519/how-to-fix-nsurlerrordomain-error-code-999-in-ios', 'admin:1764216810'),

('NSURLErrorUnknown -1 iOS', 'ios-networking', 'LOW', '[{"solution": "Check NSError.localizedDescription and NSError.localizedFailureReason for details", "percentage": 82}, {"solution": "Log full NSError object: domain, code, userInfo dictionary", "percentage": 80}, {"solution": "Investigate CFNetwork.log or system logs for underlying cause", "percentage": 76}]'::jsonb, 'iOS 9+', 'Error details retrieved, root cause identified', 'Generic error code, insufficient logging', 0.78, 'haiku', NOW(), 'https://stackoverflow.com/questions/34113453/what-are-all-the-nsurlerrordomain-errors-with-equivalent-http-status-codes', 'admin:1764216810'),

('NSURLErrorBackgroundSessionRequiresSharedContainer -995 iOS', 'ios-networking', 'LOW', '[{"solution": "Configure App Groups in Signing & Capabilities: com.apple.security.application-groups", "percentage": 87}, {"solution": "Use same group identifier in URLSessionConfiguration.sharedContainerIdentifier", "percentage": 85}, {"solution": "Ensure parent app and extensions have same code signing", "percentage": 82}]'::jsonb, 'iOS 13+, App Extensions', 'Background session configured with shared container', 'App Groups not enabled, mismatched identifiers', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/11028769/what-are-the-nsurlerrordomain-error-code-descriptions', 'admin:1764216810'),

('NSURLErrorBackgroundSessionInUseByAnotherProcess -996 iOS', 'ios-networking', 'LOW', '[{"solution": "Ensure unique identifier for URLSessionConfiguration.identifier", "percentage": 86}, {"solution": "Don''t create multiple sessions with same identifier across processes", "percentage": 84}, {"solution": "Use URLSession.shared for non-background sessions", "percentage": 81}]'::jsonb, 'iOS 9+', 'Session created with unique identifier, no conflicts', 'Duplicate session identifier, multiple processes', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/6778167/undocumented-nsurlerrordomain-error-codes-1001-1003-and-1004-using-storeki', 'admin:1764216810'),

('NSURLErrorBackgroundSessionWasDisconnected -997 iOS', 'ios-networking', 'LOW', '[{"solution": "Implement URLSessionDelegate.urlSessionDidFinishEventsForBackgroundURLSession", "percentage": 85}, {"solution": "Re-create background session with same identifier to reconnect", "percentage": 82}, {"solution": "Ensure delegate is retained while session processes requests", "percentage": 79}]'::jsonb, 'iOS 9+', 'Background session reconnects, events resume processing', 'Delegate released prematurely, no reconnection logic', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/26647423/nsurlerrordomain-error-code-1002-description', 'admin:1764216810');
