INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('pnpm-workspace.yaml file named incorrectly', 'pnpm', 'HIGH', '[{"solution": "Rename pnpm-workspaces.yml to pnpm-workspace.yaml", "percentage": 100}, {"solution": "Check for typos in workspace configuration file name", "percentage": 95}]'::jsonb, 'pnpm monorepo setup', 'Workspaces recognized correctly', 'Using wrong file extension or plural form', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/67376863/pnpm-add-within-a-workspace-does-not-add-projects-from-workspace', 'admin:1764255663'),

('Cannot read properties of undefined (reading ''manifest'')', 'pnpm', 'HIGH', '[{"solution": "Add ''version'' field to all workspace package.json files", "percentage": 92}, {"solution": "Use pnpm with compatible lerna version", "percentage": 85}]'::jsonb, 'pnpm monorepo with lerna', 'Package installs without errors', 'Missing required fields in package.json', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/72325220/pnpm-workspaces-does-not-allow-installing-of-dependencies-on-brand-new-projects', 'admin:1764255663'),

('ERR_PNPM_WORKSPACE_PKG_NOT_FOUND @namespace/PackageA not found in workspace', 'pnpm', 'HIGH', '[{"solution": "Ensure package.json ''name'' field matches namespace convention: @namespace/PackageName", "percentage": 98}, {"solution": "Verify workspace glob pattern includes the package in pnpm-workspace.yaml", "percentage": 90}]'::jsonb, 'pnpm workspace with namespaced packages', 'Workspace packages resolve correctly', 'Incorrect namespace in package.json name field', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/77865368/packagea-is-in-the-dependencies-but-no-package-named-packagea-is-present-in', 'admin:1764255663'),

('ERROR packages field is not an array when using pnpm-workspace.yaml', 'pnpm', 'MEDIUM', '[{"solution": "Verify packages field is formatted as array with quotes: packages: [''packages/**'']", "percentage": 95}, {"solution": "Check YAML syntax for proper indentation", "percentage": 88}]'::jsonb, 'pnpm workspace YAML configuration', 'pnpm install succeeds without error', 'Improper YAML array formatting', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/79471557/error-packages-field-is-not-an-array-when-using-pnpm-workspace-yaml-in-a-monor', 'admin:1764255663'),

('PNPM workspace protocol not supported in Firebase deployment', 'pnpm', 'MEDIUM', '[{"solution": "Use pre-deploy script to convert workspace: protocol to file: protocol", "percentage": 85}, {"solution": "Bundle dependencies instead of using workspace references", "percentage": 78}]'::jsonb, 'Firebase functions with pnpm workspace', 'Functions deploy successfully', 'Attempting to deploy workspace: references directly', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/75785161/how-to-use-pnpm-workspace-protocol-and-deploy-firebase-functions', 'admin:1764255663'),

('ERR_PNPM_PEER_DEP_ISSUES unmet peer dependencies', 'pnpm', 'HIGH', '[{"solution": "Set auto-install-peers = true in .npmrc at project root", "percentage": 94}, {"solution": "Run pnpm install --resolution-only to detect peer dependency issues in CI", "percentage": 85}]'::jsonb, 'pnpm strict peer dependency checking', 'pnpm install completes with all peers satisfied', 'Ignoring peer dependency warnings', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/72468635/pnpm-peer-dependencies-auto-install', 'admin:1764255663'),

('ERR_PNPM_PEER_DEP_ISSUES missing peer eslint', 'pnpm', 'HIGH', '[{"solution": "Add missing peer dependency to package.json or set strict-peer-dependencies = false", "percentage": 90}, {"solution": "Use peerDependencyRules in .npmrc to allow version mismatches", "percentage": 85}]'::jsonb, 'ESLint plugin peer dependency resolution', 'Peer dependencies satisfied', 'Not installing peer dependencies in monorepo', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/74376477/how-to-check-pnpm-strict-peer-dependencies-err-pnpm-peer-dep-issues-when-lock', 'admin:1764255663'),

('ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY broken lockfile in pnpm-lock.yaml', 'pnpm', 'HIGH', '[{"solution": "Delete pnpm-lock.yaml and run pnpm install to regenerate", "percentage": 92}, {"solution": "Downgrade to stable pnpm version if issue persists", "percentage": 78}, {"solution": "Delete build folder and rebuild application", "percentage": 82}]'::jsonb, 'pnpm lock file corruption', 'pnpm install completes without lockfile errors', 'Ignoring merge conflicts in lockfile', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/76361624/error-err-pnpm-lockfile-missing-dependency-broken-lockfile-in-pnpm-installati', 'admin:1764255663'),

('ERR_PNPM_OUTDATED_LOCKFILE cannot install with frozen-lockfile', 'pnpm', 'HIGH', '[{"solution": "Run pnpm install locally to update pnpm-lock.yaml then commit", "percentage": 98}, {"solution": "Ensure pnpm versions match between local machine and CI/deployment", "percentage": 90}]'::jsonb, 'pnpm lockfile sync issue', 'Deployment succeeds with updated lockfile', 'Lockfile out of sync with package.json', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/76869615/next-js-how-to-fix-err-pnpm-outdated-lockfile', 'admin:1764255663'),

('ERR_PNPM_NO_MATCHING_VERSION no matching version found for package', 'pnpm', 'MEDIUM', '[{"solution": "Add override in package.json to resolve exact version: overrides: {package: ''version''}", "percentage": 88}, {"solution": "Use resolutions field to force dependency version", "percentage": 85}]'::jsonb, 'pnpm version resolution in dependencies', 'Dependencies install with correct versions', 'Conflicting transitive dependency versions', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/78890225/getting-error-when-deploying-to-vercel-err-pnpm-no-matching-version', 'admin:1764255663'),

('ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE workspace package resolution', 'pnpm', 'MEDIUM', '[{"solution": "Ensure pnpm-workspace.yaml exists at root with correct packages glob pattern", "percentage": 95}, {"solution": "Create dedicated lockfile using @pnpm/make-dedicated-lockfile for partial installs", "percentage": 80}]'::jsonb, 'pnpm monorepo partial installation', 'Docker build completes successfully', 'Missing pnpm-workspace.yaml in root directory', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/71378111/pnpm-workspace-dependencies', 'admin:1764255663'),

('shamefully-hoist causes build failures in deployment', 'pnpm', 'MEDIUM', '[{"solution": "Set PNPM_FLAGS=--shamefully-hoist in environment variables on deployment platform", "percentage": 90}, {"solution": "Add shamefully-hoist=true to .npmrc file", "percentage": 85}]'::jsonb, 'pnpm hoisting on Netlify/Vercel', 'Build completes without module resolution errors', 'Module not found with pnpm strict structure', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/75771755/pnpm-install-shamefully-hoist-causes-build-fail-on-netlify', 'admin:1764255663'),

('TypeError Cannot read property ''uid'' of undefined', 'pnpm', 'LOW', '[{"solution": "Set shamefully-hoist=true in .npmrc or use --shamefully-hoist flag", "percentage": 92}, {"solution": "Ensure all transitive dependencies are properly installed", "percentage": 88}]'::jsonb, 'pnpm module resolution', 'Application runs without undefined errors', 'Missing implicit dependencies without hoisting', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/70597494/pnpm-does-not-resolve-dependencies', 'admin:1764255663'),

('ERR_PNPM_FETCH_404 no authorization header set for private packages', 'pnpm', 'MEDIUM', '[{"solution": "Configure .npmrc with proper registry and auth token: //registry.npmjs.org/:_authToken", "percentage": 92}, {"solution": "Use workspace: protocol for local packages instead of registry lookup", "percentage": 90}]'::jsonb, 'pnpm private package registry authentication', 'Private packages install successfully', 'Missing auth token in .npmrc for private registry', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/79330407/no-authorization-header-was-set-for-the-request-err-pnpm-fetch-404-get-https', 'admin:1764255663'),

('ERR_PNPM_FETCH_401 unauthorized when fetching private npm packages in Docker', 'pnpm', 'MEDIUM', '[{"solution": "Pass NPM_TOKEN build arg to Docker and configure .npmrc with token in Dockerfile", "percentage": 85}, {"solution": "Use multiple .npmrc files for different registries with proper auth setup", "percentage": 80}]'::jsonb, 'Docker private package authentication', 'Docker build completes with private packages', 'Auth token not passed or configured in Docker', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/77598929/pnpm-no-authorization-header-was-set-for-the-request-private-packages-in-dock', 'admin:1764255663'),

('Failed to parse registry URL invalid URL format', 'pnpm', 'LOW', '[{"solution": "Regenerate auth tokens in private registry", "percentage": 88}, {"solution": "Verify registry URL format is correct in .npmrc or pnpm-lock.yaml", "percentage": 85}]'::jsonb, 'pnpm private registry configuration', 'Registry URLs parse correctly', 'Expired or malformed auth tokens in registry', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/78295837/pnpm-install-failed-to-parse-registry-url', 'admin:1764255663'),

('ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE lockfile is broken', 'pnpm', 'MEDIUM', '[{"solution": "Delete store directory: rm -rf $(pnpm store path) and reinstall", "percentage": 95}, {"solution": "Upgrade pnpm to latest version to fix edge cases", "percentage": 88}]'::jsonb, 'pnpm store corruption', 'pnpm install completes without store errors', 'Corrupted package store from pnpm version issues', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/72196681/err-pnpm-err-pnpm-unexpected-pkg-content-in-store-the-lockfile-is-broken-a-full', 'admin:1764255663'),

('PNPM_HOME environment variable causing store in wrong location', 'pnpm', 'LOW', '[{"solution": "Set PNPM_HOME environment variable to correct location: export PNPM_HOME=/path/to/pnpm", "percentage": 90}, {"solution": "Use pnpm store path to verify store location and reconfigure if needed", "percentage": 85}]'::jsonb, 'pnpm store location configuration', 'pnpm uses correct store directory', 'PNPM_HOME pointing to wrong filesystem', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77099690/how-do-i-make-pnpm-work-as-intended-in-a-vscode-dev-container', 'admin:1764255663'),

('pnpm provides different hashes for same dependency version', 'pnpm', 'MEDIUM', '[{"solution": "Set dedupe-peer-dependents=true in .npmrc to force single instance of peer-dependent packages", "percentage": 92}, {"solution": "Use resolutions field to pin exact versions across monorepo", "percentage": 85}]'::jsonb, 'pnpm peer dependency deduplication', 'Dependencies have consistent hashes', 'Stateful packages like NestJS with multiple copies', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/73308570/pnpm-provides-different-hashes-for-the-exact-same-version-of-the-same-dependency', 'admin:1764255663'),

('Component not resolving nested dependencies in monorepo', 'pnpm', 'MEDIUM', '[{"solution": "Add transitive dependency directly to consumer package.json or use public-hoist-pattern", "percentage": 88}, {"solution": "Ensure workspace dependency is properly linked with workspace: protocol", "percentage": 85}]'::jsonb, 'pnpm workspace nested dependency resolution', 'Nested components resolve correctly', 'Not exposing required transitive dependencies', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/72259151/pnpm-monorepo-resolve-nested-dependencies', 'admin:1764255663'),

('pnpm link overrides breaking symlinks in deployment', 'pnpm', 'LOW', '[{"solution": "Use conditional overrides only in development .npmrc or remove before deployment", "percentage": 85}, {"solution": "Add external to build.rollupOptions instead of using link: override", "percentage": 78}]'::jsonb, 'pnpm local package linking', 'Build succeeds without broken symlinks', 'Link overrides conflicting with deployment build', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/79594121/how-to-properly-manage-pnpm-link-overrides', 'admin:1764255663'),

('pnpm overrides not being applied to transitive dependencies', 'pnpm', 'MEDIUM', '[{"solution": "Delete pnpm-lock.yaml and node_modules, then run pnpm install to force re-resolution", "percentage": 92}, {"solution": "Ensure overrides use exact package name and version syntax", "percentage": 88}]'::jsonb, 'pnpm dependency override configuration', 'Overrides applied to all instances', 'Stale lockfile with old resolution', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/75463984/pnpm-not-overriding-package', 'admin:1764255663'),

('pnpm node-linker pnp not generating node_modules correctly', 'pnpm', 'LOW', '[{"solution": "Change node-linker setting: node-linker=hoisted for compatibility or remove pnp setting", "percentage": 88}, {"solution": "Ensure node-linker is set only in root .npmrc for consistency", "percentage": 85}]'::jsonb, 'pnpm node-linker configuration', 'node_modules structure matches expectations', 'Conflicting node-linker settings across workspace', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/78551367/why-is-pnpm-with-node-linker-to-pnp-and-symlink-false-still-generating-a-node-mo', 'admin:1764255663'),

('ERR_PNPM_SYMLINK_FAILED unknown error creating symlinks on Windows', 'pnpm', 'LOW', '[{"solution": "Use NTFS-formatted drive instead of EXFAT or ReFS for pnpm operations", "percentage": 90}, {"solution": "Run pnpm install with elevated privileges (admin PowerShell)", "percentage": 82}]'::jsonb, 'pnpm Windows symlink creation', 'pnpm install completes without symlink errors', 'File system not supporting hard links (EXFAT)', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/77459703/pnpm-err-pnpm-symlink-failed-error-on-windows-machine', 'admin:1764255663'),

('ERR_PNPM_LINKING_FAILED EPERM operation not permitted rename', 'pnpm', 'MEDIUM', '[{"solution": "Close all applications accessing the directory (VSCode, file explorer) and retry", "percentage": 92}, {"solution": "Upgrade pnpm to v8.8.0 or later if running v8.7.6", "percentage": 85}]'::jsonb, 'pnpm file permission issues', 'pnpm install completes successfully', 'Other processes holding file handles during install', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77180619/pnpm-install-err-pnpm-linking-failed-operation-not-permitted-rename', 'admin:1764255663');
