-- Jest Advanced Error Patterns Mining - 45 Entries
-- Date: 2025-11-27
-- Category: jest-advanced
-- Source: Stack Overflow Research

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('Jest advanceTimersByTime not working in retry util function', 'jest-advanced', 'MEDIUM', '[{"solution": "Await the retry function after calling advanceTimersByTime. Timer advancement needs async functions to settle", "percentage": 90}, {"solution": "Use jest.runAllTimers() instead of advanceTimersByTime if testing all accumulated timers", "percentage": 80}]'::jsonb, 'Jest fake timers enabled, async function', 'Function retries at correct intervals', 'Forgetting to await after timer advancement', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/66391541', 'admin:1764261683'),

('Jest timer and promise don''t work well with setTimeout and async function', 'jest-advanced', 'MEDIUM', '[{"solution": "Use jest.useFakeTimers() at start and jest.useRealTimers() at end. Combine with runAllTimers() for promises", "percentage": 92}, {"solution": "Ensure setTimeout is called before advanceTimersByTime or runAllTimers", "percentage": 85}]'::jsonb, 'Jest setup, Promise pattern, async/await', 'Promise resolves at expected time', 'Mixing real and fake timers, order of operations', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/52177631', 'admin:1764261683'),

('Jest fake timers how to advance both real and fake time', 'jest-advanced', 'MEDIUM', '[{"solution": "Use advanceTimersByTime() for fake timers and Promise microtasks separately", "percentage": 88}, {"solution": "Call jest.advanceTimersByTime(ms) then await new Promise(resolve => setTimeout(resolve, 0)) for real scheduling", "percentage": 82}]'::jsonb, 'Jest fake timers mode, Promise understanding', 'Both timer systems advance correctly', 'Not sequencing timer and microtask advancement', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/77133115', 'admin:1764261683'),

('Explain Jest advanceTimersToNextTimer', 'jest-advanced', 'MEDIUM', '[{"solution": "advanceTimersToNextTimer() advances only until the next timer without arguments", "percentage": 93}, {"solution": "Use in loop with advanceTimersToNextTimer() to iterate through all scheduled timers", "percentage": 88}]'::jsonb, 'Jest fake timers enabled, timers queued', 'Timers fire in correct order', 'Calling without timers queued returns immediately', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/71667406', 'admin:1764261683'),

('Testing a promise using setTimeout with Jest', 'jest-advanced', 'HIGH', '[{"solution": "Mock setTimeout with jest.useFakeTimers() then jest.advanceTimersByTime(timeout) to trigger promises", "percentage": 94}, {"solution": "Return promise from test and use jest.runAllTimersAsync() in Jest 29+", "percentage": 89}]'::jsonb, 'Jest setup, Promise/setTimeout pattern', 'Promise resolves in test', 'Not advancing timers after scheduling', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/46710564', 'admin:1764261683'),

('Jest can''t advance timers related to date', 'jest-advanced', 'MEDIUM', '[{"solution": "Use jest.setSystemTime() to mock Date, not just advanceTimersByTime", "percentage": 91}, {"solution": "Call jest.useFakeTimers({ now: new Date() }) to set initial date value", "percentage": 87}]'::jsonb, 'Jest fake timers, Date object usage', 'Mocked dates advance correctly', 'Using advanceTimersByTime without setSystemTime', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/71772373', 'admin:1764261683'),

('Mock setInterval method in React using Jest test cases', 'jest-advanced', 'HIGH', '[{"solution": "Use jest.useFakeTimers() then jest.advanceTimersByTime() to advance interval callbacks", "percentage": 93}, {"solution": "Clear intervals with jest.clearAllTimers() or jest.clearAllMocks() after tests", "percentage": 90}]'::jsonb, 'Jest fake timers, React component, setInterval', 'Interval fires correct number of times', 'Not clearing timers between tests', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/55998217', 'admin:1764261683'),

('Testing an express middleware with Jest', 'jest-advanced', 'MEDIUM', '[{"solution": "Mock request/response objects using jest.fn() for res.send(), res.json(), res.status()", "percentage": 89}, {"solution": "Use supertest library instead of mocking raw Express objects for cleaner tests", "percentage": 92}]'::jsonb, 'Express middleware, mock objects, Jest', 'Middleware calls next() or sends response', 'Not mocking all response methods', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/60722281', 'admin:1764261683'),

('How to test the type of a thrown exception in Jest', 'jest-advanced', 'HIGH', '[{"solution": "Use expect(() => { throw new TypeError() }).toThrow(TypeError)", "percentage": 95}, {"solution": "Use expect(fn).rejects.toThrow(TypeError) for async functions that throw", "percentage": 92}]'::jsonb, 'Error handling, Jest matchers', 'Correct error type caught', 'Passing non-function to toThrow', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/46042613', 'admin:1764261683'),

('In Jest how can I make a test fail intentionally', 'jest-advanced', 'HIGH', '[{"solution": "Use fail() function: expect.fail(''Reason for failure'')", "percentage": 96}, {"solution": "Use throw new Error(''message'') to fail immediately", "percentage": 93}]'::jsonb, 'Jest matchers, test control', 'Test fails with correct message', 'Forgetting to return fail()', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/42176642', 'admin:1764261683'),

('How to add custom message to Jest expect', 'jest-advanced', 'MEDIUM', '[{"solution": "Pass message as second argument: expect(value).toBe(expected, ''Custom message'')", "percentage": 88}, {"solution": "Use .rejects.toThrow().then() with custom error text for better clarity", "percentage": 82}]'::jsonb, 'Jest matchers, error messages', 'Custom message appears in test output', 'Jest version doesn''t support message param', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/45348083', 'admin:1764261683'),

('How to fix test suite failed to run when running test with Jest', 'jest-advanced', 'HIGH', '[{"solution": "Check jest.config.js for syntax errors and correct babel/typescript configuration", "percentage": 91}, {"solution": "Ensure all imports are resolvable and dependencies are installed", "percentage": 89}]'::jsonb, 'Jest configuration, build setup', 'Test suite runs without errors', 'Missing jest dependencies or bad config', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/57998950', 'admin:1764261683'),

('Why Jest passed all tests but still throw an error', 'jest-advanced', 'MEDIUM', '[{"solution": "Check for promises that aren''t awaited. Return Promise or use async/await in test", "percentage": 90}, {"solution": "Look for setTimeout/setInterval not handled by jest.useFakeTimers()", "percentage": 87}]'::jsonb, 'Async handling, Promise management', 'All tests pass without lingering errors', 'Unawaited async operations after tests', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/74513668', 'admin:1764261683'),

('ReferenceError: jest is not defined when running unit test', 'jest-advanced', 'HIGH', '[{"solution": "Add jest-environment-node or jest-environment-jsdom to jest.config.js testEnvironment field", "percentage": 94}, {"solution": "Ensure setupFilesAfterEnv includes proper Jest global setup", "percentage": 89}]'::jsonb, 'Jest configuration, test environment', 'jest globals available in tests', 'Missing or incorrect testEnvironment config', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/65190123', 'admin:1764261683'),

('Testing an error thrown by a React component using testing-library and Jest', 'jest-advanced', 'MEDIUM', '[{"solution": "Use expect(() => render(Component)).toThrow() to catch component render errors", "percentage": 91}, {"solution": "Wrap in ErrorBoundary and test error state instead of throws", "percentage": 88}]'::jsonb, 'React testing-library, Jest matchers', 'Component error caught in test', 'Not using proper error boundary patterns', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/66328549', 'admin:1764261683'),

('Jest to continue checking expect even after error', 'jest-advanced', 'MEDIUM', '[{"solution": "Use expect.extend() to create custom matchers that aggregate assertions", "percentage": 85}, {"solution": "Break test into multiple expects and continue manually after handling errors", "percentage": 78}]'::jsonb, 'Jest matchers, error recovery', 'Multiple expects validate despite earlier failures', 'Jest stops at first failed expect by default', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/57065326', 'admin:1764261683'),

('Spy on Jest mock', 'jest-advanced', 'HIGH', '[{"solution": "Use jest.spyOn(object, ''method'') to spy on existing methods while keeping original behavior", "percentage": 93}, {"solution": "Chain with .mockImplementation() to spy AND change behavior", "percentage": 90}]'::jsonb, 'Jest spies, mocking patterns', 'Spy tracks calls without affecting functionality', 'Using jest.mock() instead of jest.spyOn()', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/40101513', 'admin:1764261683'),

('How to reset or clear a spy in Jest', 'jest-advanced', 'MEDIUM', '[{"solution": "Use spy.mockClear() to reset call count, or mockReset() to also clear mock data", "percentage": 92}, {"solution": "Use jest.clearAllMocks() in afterEach() to clear all spies between tests", "percentage": 89}]'::jsonb, 'Jest spies, cleanup, test isolation', 'Spy tracks calls correctly in new test', 'Not clearing spies between tests', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/53350382', 'admin:1764261683'),

('How to use Jest to mock spy named imports in the ES module way', 'jest-advanced', 'MEDIUM', '[{"solution": "Use jest.mock(''./module'', () => ({ namedExport: jest.fn() }))", "percentage": 88}, {"solution": "Import module first then jest.spyOn(module, ''namedExport'')", "percentage": 85}]'::jsonb, 'Jest ES modules, named imports, mocking', 'Named export mocked correctly', 'Incorrect module path or export name', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/79336026', 'admin:1764261683'),

('How to spy on an object function returned from a mock in Jest', 'jest-advanced', 'MEDIUM', '[{"solution": "Mock the parent object first, then spyOn the returned method using jest.spyOn()", "percentage": 89}, {"solution": "Use mockReturnValue to return an object with mocked methods", "percentage": 86}]'::jsonb, 'Jest spies, nested mocks, return values', 'Returned function tracked correctly', 'Trying to spy on non-existent methods', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/70646844', 'admin:1764261683'),

('How to reset a spy or mock in Jest', 'jest-advanced', 'HIGH', '[{"solution": "Use jest.clearAllMocks() for global reset or spy.mockClear() for specific spy", "percentage": 94}, {"solution": "Use jest.resetAllMocks() to clear mocks including implementation", "percentage": 91}]'::jsonb, 'Jest spies, mocks, cleanup', 'All mocks/spies reset between tests', 'Forgetting to reset in afterEach', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/62530414', 'admin:1764261683'),

('Jest spy on a mocked function from the mock file', 'jest-advanced', 'MEDIUM', '[{"solution": "Export mock as named export, then import and spy on it in test", "percentage": 87}, {"solution": "Use jest.spyOn() on the actual module before jest.mock() loads it", "percentage": 84}]'::jsonb, 'Jest mocks, spies, file structure', 'Spy tracks calls on mocked function', 'Module loading order issues', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/69363921', 'admin:1764261683'),

('How to mock spy useState hook in Jest', 'jest-advanced', 'MEDIUM', '[{"solution": "Mock React module: jest.mock(''react'', () => ({ useState: jest.fn() }))", "percentage": 86}, {"solution": "Use jest-mock-extended or ts-mockito for easier hook mocking", "percentage": 88}]'::jsonb, 'Jest React hooks, mocking, spies', 'useState hook tracked in test', 'Not mocking React module first', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/64165138', 'admin:1764261683'),

('How to change mock implementation on a per single test basis', 'jest-advanced', 'HIGH', '[{"solution": "Use jest.fn().mockImplementation() or .mockImplementationOnce() in each test", "percentage": 93}, {"solution": "Create mock before describe block, reset in beforeEach, implement in test", "percentage": 90}]'::jsonb, 'Jest mocks, per-test configuration', 'Mock behaves differently per test', 'Not resetting mocks between tests', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/48790927', 'admin:1764261683'),

('Jest ReferenceError is not defined', 'jest-advanced', 'MEDIUM', '[{"solution": "Check testEnvironment in jest.config.js - should be ''jsdom'' for browser globals", "percentage": 91}, {"solution": "Use setupFilesAfterEnv to polyfill missing globals", "percentage": 87}]'::jsonb, 'Jest config, test environment, globals', 'Global references available in tests', 'Wrong testEnvironment setting', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/45684811', 'admin:1764261683'),

('ReferenceError describe is not defined in Jest TypeScript', 'jest-advanced', 'MEDIUM', '[{"solution": "Install @types/jest and add to tsconfig.json types array", "percentage": 92}, {"solution": "Add jest globals to jest.config.js via testEnvironment", "percentage": 89}]'::jsonb, 'Jest TypeScript, type definitions', 'Jest globals recognized by TypeScript', 'Missing @types/jest dependency', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/59927799', 'admin:1764261683'),

('ReferenceError test is not defined with Jest', 'jest-advanced', 'MEDIUM', '[{"solution": "Ensure jest.config.js exists with correct testEnvironment configuration", "percentage": 90}, {"solution": "Add jest globals via setupFilesAfterEnv if testEnvironment not working", "percentage": 86}]'::jsonb, 'Jest globals, test function, configuration', 'test() function available in test file', 'Missing Jest configuration', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/62031536', 'admin:1764261683'),

('Define is not defined in Jest when testing ES6 module with requirejs dependency', 'jest-advanced', 'MEDIUM', '[{"solution": "Mock requirejs in jest.config.js setupFiles or mock individual modules", "percentage": 83}, {"solution": "Use babel to transform requirejs calls to ES6 imports", "percentage": 80}]'::jsonb, 'Jest ES6, module systems, babel', 'ES6 modules load without requirejs errors', 'Incompatible module systems', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/40919028', 'admin:1764261683'),

('Jest ReferenceError define is not defined for a simple test file', 'jest-advanced', 'MEDIUM', '[{"solution": "Remove requirejs dependency or mock it in jest setup", "percentage": 85}, {"solution": "Use ES6 imports instead of define() calls", "percentage": 88}]'::jsonb, 'Jest modules, AMD to ES6', 'Test file loads without define errors', 'Old AMD/requirejs patterns', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/53055695', 'admin:1764261683'),

('Jest ReferenceError imported function is not defined', 'jest-advanced', 'MEDIUM', '[{"solution": "Check import path is correct and file exists", "percentage": 92}, {"solution": "Use jest.mock() at top level before importing mocked module", "percentage": 89}]'::jsonb, 'Jest imports, file resolution, mocking', 'Imported function resolves correctly', 'Incorrect import path or module not found', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/60217165', 'admin:1764261683'),

('React Jest testing error ReferenceError expect is not defined', 'jest-advanced', 'MEDIUM', '[{"solution": "Ensure @testing-library/react is installed and jest.config.js has testEnvironment set", "percentage": 91}, {"solution": "Add @types/jest to devDependencies for TypeScript projects", "percentage": 88}]'::jsonb, 'Jest React testing, expect global, types', 'expect() function available in tests', 'Missing jest types or config', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/69932488', 'admin:1764261683'),

('Jest mock cannot find module', 'jest-advanced', 'HIGH', '[{"solution": "Use correct relative path in jest.mock(): jest.mock(''../module/path'')", "percentage": 94}, {"solution": "Ensure mocked file actually exists", "percentage": 91}]'::jsonb, 'Jest mocking, path resolution', 'Module mocked successfully', 'Wrong relative path to module', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/68481988', 'admin:1764261683'),

('Jest cannot read property instances of undefined when mocking ES6 classes', 'jest-advanced', 'MEDIUM', '[{"solution": "Mock the class constructor: jest.mock(''./Class'', () => ({ default: jest.fn() }))", "percentage": 88}, {"solution": "Return jest.fn() that returns an object with the expected properties", "percentage": 85}]'::jsonb, 'Jest ES6 classes, mocking, constructors', 'Class mocked with proper interface', 'Not returning correct object from mock', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/49564103', 'admin:1764261683'),

('Jest mock TypeError cannot assign to read only property', 'jest-advanced', 'MEDIUM', '[{"solution": "Use Object.defineProperty() to override readonly: Object.defineProperty(obj, ''prop'', { value: mock })", "percentage": 87}, {"solution": "Mock at module level before assignment attempts", "percentage": 84}]'::jsonb, 'Jest mocking, readonly properties, ES6', 'Read-only property overridden in test', 'Trying to reassign frozen object directly', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/78428523', 'admin:1764261683'),

('How do I resolve Jest mock error cannot find module', 'jest-advanced', 'HIGH', '[{"solution": "Double-check jest.mock() path matches actual file location relative to test file", "percentage": 93}, {"solution": "Use moduleNameMapper in jest.config.js if mocking node_modules", "percentage": 90}]'::jsonb, 'Jest mocking, module resolution, paths', 'Jest finds and mocks module correctly', 'Path mismatch or module doesn''t exist', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/67715883', 'admin:1764261683'),

('Jest test cannot find module error when trying to mock react-native-device-info', 'jest-advanced', 'MEDIUM', '[{"solution": "Mock using correct path: jest.mock(''react-native-device-info'') or use manual mock file", "percentage": 89}, {"solution": "Add moduleNameMapper to map react-native to mock in jest.config.js", "percentage": 86}]'::jsonb, 'Jest React Native, mocking third party', 'react-native module mocked correctly', 'Incorrect mock path or format', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/69531300', 'admin:1764261683'),

('Cannot find module request error using mock in Jest', 'jest-advanced', 'MEDIUM', '[{"solution": "Provide relative path from test file: jest.mock(''../../node_modules/request'')", "percentage": 85}, {"solution": "Or use moduleNameMapper in jest.config.js to map request mock", "percentage": 88}]'::jsonb, 'Jest mocking, npm modules, paths', 'Module mocks resolve correctly', 'Incorrect relative path', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/42480461', 'admin:1764261683'),

('Cannot find module error while mocking elements in Jest unit testing with TypeScript', 'jest-advanced', 'MEDIUM', '[{"solution": "Check tsconfig.json moduleResolution matches jest.config.js settings", "percentage": 88}, {"solution": "Use ts-jest preset in jest.config.js for TypeScript support", "percentage": 91}]'::jsonb, 'Jest TypeScript, module resolution, ts-jest', 'TypeScript modules mocked in Jest', 'TypeScript/Jest config mismatch', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/78312050', 'admin:1764261683'),

('Jest error cannot read property get of undefined', 'jest-advanced', 'MEDIUM', '[{"solution": "Ensure mocked object exists before accessing nested properties", "percentage": 90}, {"solution": "Return proper mock object structure: jest.mock(...) returns { get: jest.fn() }", "percentage": 87}]'::jsonb, 'Jest mocking, property access, null safety', 'Mocked object has expected properties', 'Incomplete mock object definition', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/67756507', 'admin:1764261683'),

('Async callback was not invoked within timeout specified by Jest', 'jest-advanced', 'HIGH', '[{"solution": "Use async/await syntax: test(''name'', async () => { ... }) instead of callbacks", "percentage": 94}, {"solution": "Return Promise or use done callback: test(''name'', (done) => { ... done() })", "percentage": 91}]'::jsonb, 'Jest async testing, callbacks, promises', 'Async callback completes within timeout', 'Not returning promise or using done', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/49603939', 'admin:1764261683'),

('Jest with async function calls before and after setTimeout', 'jest-advanced', 'MEDIUM', '[{"solution": "Use jest.useFakeTimers() then advanceTimersByTime() for controlled async tests", "percentage": 90}, {"solution": "Await all promises before advancing timers with jest.runAllTimersAsync()", "percentage": 88}]'::jsonb, 'Jest async, fake timers, promise ordering', 'Async functions execute in correct order', 'Timer/promise execution order issues', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/62993577', 'admin:1764261683'),

('Jest async await fails callback regardless TypeScript', 'jest-advanced', 'MEDIUM', '[{"solution": "Add return statement before Promise: return asyncFunction().then(...)", "percentage": 91}, {"solution": "Use async/await: test(''name'', async () => { await asyncFunc() })", "percentage": 93}]'::jsonb, 'Jest async, TypeScript, callbacks', 'Async callback resolves successfully', 'Not returning promise or awaiting', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/62350370', 'admin:1764261683'),

('Jest not awaiting timeout before test completes', 'jest-advanced', 'HIGH', '[{"solution": "Manually advance time with jest.advanceTimersByTime(ms) after scheduling", "percentage": 92}, {"solution": "Use jest.runAllTimersAsync() in Jest 29+ to handle all timers", "percentage": 89}]'::jsonb, 'Jest fake timers, test completion, async', 'Timeout waits complete before test ends', 'Not advancing timers in fake timer mode', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/57083470', 'admin:1764261683'),

('setTimeout with promise wrapper not working as expected with Jest async await', 'jest-advanced', 'MEDIUM', '[{"solution": "Wrap setTimeout in Promise and use jest.useFakeTimers() with advanceTimersByTime()", "percentage": 89}, {"solution": "Return Promise from test: return new Promise(resolve => setTimeout(resolve, ms))", "percentage": 86}]'::jsonb, 'Jest async, promises, setTimeout, fake timers', 'Promise resolves after timeout correctly', 'Mixing real/fake timers improperly', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/55668630', 'admin:1764261683'),

('Async await test with Jest not working in Node.js', 'jest-advanced', 'MEDIUM', '[{"solution": "Ensure jest-environment-node is set in jest.config.js for Node tests", "percentage": 91}, {"solution": "Return Promise or use async function syntax in test()", "percentage": 89}]'::jsonb, 'Jest Node environment, async/await setup', 'Async tests run in Node.js environment', 'Wrong testEnvironment configuration', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/62712676', 'admin:1764261683'),

('How to make Jest wait for all asynchronous code to finish execution before expect', 'jest-advanced', 'HIGH', '[{"solution": "Use jest.runAllTimersAsync() in Jest 29+ to resolve all timers and promises", "percentage": 94}, {"solution": "Or use jest.advanceTimersByTime(largeNumber) followed by awaiting promises", "percentage": 89}]'::jsonb, 'Jest async handling, timer completion', 'All async operations complete before assertion', 'Not advancing all timers or promises', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/44741102', 'admin:1764261683'),

('Error running a Jest snapshot test using a custom snapshot serializer jest styled components', 'jest-advanced', 'MEDIUM', '[{"solution": "Import jest-styled-components and configure in jest.config.js snapshotSerializers", "percentage": 88}, {"solution": "Ensure snapshot serializer matches component library version", "percentage": 85}]'::jsonb, 'Jest snapshots, custom serializers, styled-components', 'Styled component snapshots render correctly', 'Serializer version mismatch', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/59793848', 'admin:1764261683'),

('What''s React Scripts Jest default serializer for snapshot testing', 'jest-advanced', 'MEDIUM', '[{"solution": "Jest uses pretty-format library for default serialization", "percentage": 90}, {"solution": "Custom serializers override default pretty-format behavior", "percentage": 87}]'::jsonb, 'Jest snapshots, serialization, React', 'Snapshots serialize with correct formatting', 'Overriding serializer incorrectly', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/50913760', 'admin:1764261683'),

('Jest snapshot different when testing through CI vs locally', 'jest-advanced', 'HIGH', '[{"solution": "Remove dynamic values (timestamps, IDs, UUIDs) from snapshots", "percentage": 93}, {"solution": "Use snapshot serializers to strip platform-specific paths", "percentage": 90}]'::jsonb, 'Jest snapshots, CI testing, deterministic tests', 'Snapshots match in CI and local environments', 'Dynamic or platform-specific values in snapshots', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/39786514', 'admin:1764261683');
