INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERROR gcloud services enable PERMISSION_DENIED: The caller does not have permission', 'gcp', 'CRITICAL', '[{"solution": "Verify you have the Service Admin role or higher permissions in IAM", "percentage": 90}, {"solution": "Enable the service through gcloud: gcloud services enable <service-name>", "percentage": 85}]'::jsonb, 'gcloud CLI installed and authenticated', 'gcloud command succeeds and service is enabled', 'Using insufficient permissions like Editor instead of Admin', 0.919, 'haiku', NOW(), 'https://stackoverflow.com/questions/59804258/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('GCP billing error when billing is enabled', 'gcp', 'CRITICAL', '[{"solution": "Check if billing account is attached to project", "percentage": 88}, {"solution": "Verify billing account has available budget", "percentage": 82}]'::jsonb, 'GCP project with billing setup', 'Billing dashboard shows active account', 'Assuming free tier covers all services', 0.918, 'haiku', NOW(), 'https://stackoverflow.com/questions/75632596/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('GCP Cloud Function logging errors to stderr instead of info level', 'gcp', 'CRITICAL', '[{"solution": "Use console.log() for info and console.error() for errors explicitly", "percentage": 92}, {"solution": "Configure logging level in function runtime environment", "percentage": 78}]'::jsonb, 'Cloud Functions runtime with logging support', 'Logs appear at correct level in Cloud Logging', 'Relying on stderr capture without explicit log level', 0.917, 'haiku', NOW(), 'https://stackoverflow.com/questions/65776399/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('GCP Error Reporting not grouping exceptions without stack traces', 'gcp', 'CRITICAL', '[{"solution": "Always include stack trace in error objects", "percentage": 94}, {"solution": "Use structured logging with error type and stack", "percentage": 89}]'::jsonb, 'GCP Error Reporting enabled on project', 'Errors grouped by error type in dashboard', 'Sending error messages without context', 0.916, 'haiku', NOW(), 'https://stackoverflow.com/questions/71344271/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('googleapiclient.errors GoogleAPIClientError when labeling compute instances', 'gcp', 'CRITICAL', '[{"solution": "Add compute.instances.setLabels permission to service account", "percentage": 91}, {"solution": "Use gcloud compute instances add-labels with proper auth", "percentage": 87}]'::jsonb, 'Service account with compute API access', 'Labels set on instance without error', 'Using wrong service account or insufficient permissions', 0.915, 'haiku', NOW(), 'https://stackoverflow.com/questions/73265895/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Permission denied publickey SSH to Google Cloud instance', 'gcp', 'CRITICAL', '[{"solution": "Add SSH public key to GCP metadata or OS Login", "percentage": 96}, {"solution": "Use gcloud compute ssh which handles auth automatically", "percentage": 93}]'::jsonb, 'GCP Compute instance with SSH enabled', 'SSH connection succeeds to instance', 'Wrong key path or missing metadata updates', 0.914, 'haiku', NOW(), 'https://stackoverflow.com/questions/51614552/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('UNAUTHENTICATED requests do not have permission artifact registry repositories upload', 'gcp', 'CRITICAL', '[{"solution": "Authenticate with gcloud auth application-default login before pushing", "percentage": 89}, {"solution": "Configure Docker credentials: gcloud auth configure-docker", "percentage": 91}]'::jsonb, 'gcloud CLI and Docker installed', 'Docker push succeeds to artifact registry', 'Assuming gcloud login is sufficient for Docker auth', 0.913, 'haiku', NOW(), 'https://stackoverflow.com/questions/78106286/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('gcloud init command returns PERMISSION_DENIED error', 'gcp', 'CRITICAL', '[{"solution": "Ensure your GCP account has at least Viewer role on the project", "percentage": 87}, {"solution": "Re-authenticate: gcloud auth login", "percentage": 85}]'::jsonb, 'GCP account with project access', 'gcloud init completes successfully', 'Using account without any project permissions', 0.912, 'haiku', NOW(), 'https://stackoverflow.com/questions/59804258/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('gcloud functions deploy PERMISSION_DENIED error', 'gcp', 'CRITICAL', '[{"solution": "Verify you have Cloud Functions Developer role", "percentage": 93}, {"solution": "Check service account has cloudfunctions.functions.create permission", "percentage": 89}]'::jsonb, 'Cloud Functions API enabled', 'Function deployment succeeds', 'Missing Cloud Functions Developer role', 0.911, 'haiku', NOW(), 'https://stackoverflow.com/questions/73653385/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('permission artifactregistry repositories uploadartifacts denied on resource', 'gcp', 'CRITICAL', '[{"solution": "Grant Artifact Registry Writer role to service account", "percentage": 92}, {"solution": "Use gcloud auth configure-docker gcr.io to setup credentials", "percentage": 88}]'::jsonb, 'Artifact Registry repository exists', 'Docker push succeeds to registry', 'Using read-only permissions on registry', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/75840164/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('gcloud auth print-access-token gives permission denied error', 'gcp', 'HIGH', '[{"solution": "Re-authenticate with gcloud auth login", "percentage": 91}, {"solution": "Check if authentication token has expired", "percentage": 84}]'::jsonb, 'gcloud CLI installed', 'Valid token returned from command', 'Stale cached credentials', 0.909, 'haiku', NOW(), 'https://stackoverflow.com/questions/72993558/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Permission denied publickey SSH authentication via gssapi', 'gcp', 'HIGH', '[{"solution": "Add public SSH key to instance metadata", "percentage": 95}, {"solution": "Use gcloud compute ssh instead of raw SSH", "percentage": 92}]'::jsonb, 'GCP Compute instance', 'SSH login succeeds', 'SSH key not properly configured in metadata', 0.908, 'haiku', NOW(), 'https://stackoverflow.com/questions/16729694/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Permission denied on resource project calling deployed ML model', 'gcp', 'HIGH', '[{"solution": "Verify caller has AI Platform User or Editor role", "percentage": 88}, {"solution": "Ensure service account has ml.models.predict permission", "percentage": 90}]'::jsonb, 'AI Platform model deployed', 'Model prediction request succeeds', 'Using wrong service account for predictions', 0.907, 'haiku', NOW(), 'https://stackoverflow.com/questions/65766588/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('RESOURCE_EXHAUSTED frequent errors in GCP', 'gcp', 'HIGH', '[{"solution": "Increase quota limits through GCP console", "percentage": 85}, {"solution": "Implement request rate limiting and backoff strategy", "percentage": 88}]'::jsonb, 'Understanding of GCP quotas and limits', 'Requests succeeds after quota increase', 'Not waiting for quota increase propagation', 0.906, 'haiku', NOW(), 'https://stackoverflow.com/questions/44707091/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Zone resource pool exhausted when creating GCP instance', 'gcp', 'HIGH', '[{"solution": "Try different zone with available capacity", "percentage": 89}, {"solution": "Request quota increase for the zone", "percentage": 84}]'::jsonb, 'GCP Compute Engine access', 'Instance created in alternative zone', 'Not checking zone capacity before requesting', 0.905, 'haiku', NOW(), 'https://stackoverflow.com/questions/52586941/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Terraform GCP timeout and resources already exist error', 'gcp', 'HIGH', '[{"solution": "Import existing resources: terraform import", "percentage": 91}, {"solution": "Increase timeout values in Terraform config", "percentage": 87}]'::jsonb, 'Terraform and GCP provider configured', 'Terraform apply succeeds', 'Idempotency issues with existing resources', 0.904, 'haiku', NOW(), 'https://stackoverflow.com/questions/70466873/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('GCE error the resource name already exists but it does not', 'gcp', 'HIGH', '[{"solution": "Delete the resource using gcloud CLI directly", "percentage": 90}, {"solution": "Wait for deletion to fully propagate before recreating", "percentage": 86}]'::jsonb, 'gcloud compute CLI access', 'Resource creation succeeds', 'Timing issues with async deletion', 0.903, 'haiku', NOW(), 'https://stackoverflow.com/questions/27447654/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Google Cloud RESOURCE_EXHAUSTED insufficient accelerators quota', 'gcp', 'HIGH', '[{"solution": "Request GPU quota increase from Quotas page", "percentage": 87}, {"solution": "Use different GPU type with available quota", "percentage": 85}]'::jsonb, 'ML Engine access and quota system knowledge', 'Training job uses requested accelerators', 'Assuming quota increase is immediate', 0.902, 'haiku', NOW(), 'https://stackoverflow.com/questions/52908410/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('GCP GAE resource exhausted quota error deployment', 'gcp', 'HIGH', '[{"solution": "Check App Engine quotas in GCP console", "percentage": 88}, {"solution": "Reduce deployment size or enable auto-scaling", "percentage": 83}]'::jsonb, 'App Engine application deployed', 'Application deploys successfully', 'Exceeding free tier limits', 0.901, 'haiku', NOW(), 'https://stackoverflow.com/questions/65466222/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('GCP zone resource pool exhausted Asia South region', 'gcp', 'HIGH', '[{"solution": "Switch to different zone like asia-south1-a instead of asia-south1-b", "percentage": 91}, {"solution": "Request capacity increase for zone", "percentage": 79}]'::jsonb, 'GCP Compute Engine', 'Instance created successfully', 'Zone-specific capacity constraints', 0.9, 'haiku', NOW(), 'https://stackoverflow.com/questions/63515444/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('FAILED_PRECONDITION when trying to create new Google API project', 'gcp', 'MEDIUM', '[{"solution": "Ensure billing account is properly attached to project", "percentage": 92}, {"solution": "Wait for project setup to complete before API operations", "percentage": 88}]'::jsonb, 'Google Cloud project', 'API project creation succeeds', 'Operating on project before fully initialized', 0.899, 'haiku', NOW(), 'https://stackoverflow.com/questions/43214920/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('googleapi Error 400 Precondition check failed failedPrecondition', 'gcp', 'MEDIUM', '[{"solution": "Verify preconditions met before operation for example etag match", "percentage": 93}, {"solution": "Retry operation with updated resource state", "percentage": 89}]'::jsonb, 'Understanding of API preconditions', 'API call succeeds with correct preconditions', 'Stale resource state or etag mismatch', 0.898, 'haiku', NOW(), 'https://stackoverflow.com/questions/67015382/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Cloud Function Go client error 400 precondition when deploying', 'gcp', 'MEDIUM', '[{"solution": "Ensure Cloud Functions API is enabled", "percentage": 91}, {"solution": "Verify service account has function.developer role", "percentage": 88}]'::jsonb, 'Go client library for Cloud Functions', 'Function deploys via Go client', 'Missing API enablement or permissions', 0.897, 'haiku', NOW(), 'https://stackoverflow.com/questions/60710493/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('com.google.api.client.googleapis.json GoogleJsonResponseException 401', 'gcp', 'MEDIUM', '[{"solution": "Add proper OAuth credentials to client code", "percentage": 89}, {"solution": "Ensure IAM policy allows the service account", "percentage": 90}]'::jsonb, 'Google API client library', 'Authenticated API request succeeds', 'Missing authentication setup', 0.896, 'haiku', NOW(), 'https://stackoverflow.com/questions/56784577/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Precondition not met while deleting GCS object at generation 0', 'gcp', 'MEDIUM', '[{"solution": "Avoid using if-generation-match:0 for existing objects", "percentage": 94}, {"solution": "Use delete_generation or omit the header for unversioned buckets", "percentage": 91}]'::jsonb, 'Google Cloud Storage knowledge', 'Object deletion succeeds', 'Misunderstanding generation versioning', 0.895, 'haiku', NOW(), 'https://stackoverflow.com/questions/72092861/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Firestore API is not available for Cloud Datastore projects', 'gcp', 'MEDIUM', '[{"solution": "Enable Cloud Firestore API in project", "percentage": 92}, {"solution": "Cannot convert existing Datastore projects to Firestore - create new project", "percentage": 87}]'::jsonb, 'GCP project with Firestore/Datastore', 'Firestore API enabled and operations succeed', 'Attempting to convert Datastore to Firestore', 0.894, 'haiku', NOW(), 'https://stackoverflow.com/questions/58001922/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Cannot read property firestore of null in Firebase', 'gcp', 'MEDIUM', '[{"solution": "Initialize Firebase app before accessing firestore: initializeApp(config)", "percentage": 95}, {"solution": "Check Firebase config and credentials are loaded", "percentage": 92}]'::jsonb, 'Firebase SDK integrated', 'Firestore instance initializes successfully', 'Accessing Firestore before app initialization', 0.893, 'haiku', NOW(), 'https://stackoverflow.com/questions/63007860/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Cannot switch Firestore from Datastore to native mode on GCP', 'gcp', 'MEDIUM', '[{"solution": "Create new project with native Firestore if needed", "percentage": 88}, {"solution": "Understand Datastore mode is incompatible with native Firestore", "percentage": 86}]'::jsonb, 'Understanding of Firestore modes', 'Project operates in intended Firestore mode', 'Assuming modes are interchangeable', 0.892, 'haiku', NOW(), 'https://stackoverflow.com/questions/70689925/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Cannot view data from GCP Datastore Firestore in browser with emulator', 'gcp', 'MEDIUM', '[{"solution": "Set DATASTORE_EMULATOR_HOST environment variable correctly", "percentage": 90}, {"solution": "Use correct app ID in client library configuration", "percentage": 87}]'::jsonb, 'Datastore emulator running', 'Emulator data visible in browser UI', 'Environment variable misconfiguration', 0.891, 'haiku', NOW(), 'https://stackoverflow.com/questions/61006211/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Python time out of stream method on GCP Firestore', 'gcp', 'MEDIUM', '[{"solution": "Increase timeout in Firestore client configuration", "percentage": 86}, {"solution": "Implement retry logic with exponential backoff", "percentage": 88}]'::jsonb, 'Python Firestore client', 'Queries complete within timeout', 'Default timeout too low for large operations', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/62734229/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('com.google.cloud.bigquery BigQueryException read timed out', 'gcp', 'LOW', '[{"solution": "Increase query timeout: job_config.priority = QueryPriority.INTERACTIVE", "percentage": 87}, {"solution": "Optimize query to run faster", "percentage": 89}]'::jsonb, 'Google BigQuery client library', 'Query completes successfully', 'Long-running queries without adequate timeout', 0.889, 'haiku', NOW(), 'https://stackoverflow.com/questions/41847663/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Java GCP BigQuery Simba JDBC connection timeout', 'gcp', 'LOW', '[{"solution": "Increase JDBC timeout: connectionTimeout=30000", "percentage": 85}, {"solution": "Use BigQuery REST API instead of JDBC for large queries", "percentage": 83}]'::jsonb, 'BigQuery JDBC driver', 'JDBC connection established', 'Default timeout too low', 0.888, 'haiku', NOW(), 'https://stackoverflow.com/questions/76440904/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Timeout error writing large amounts of data to BigQuery', 'gcp', 'LOW', '[{"solution": "Use BigQuery streaming insert with batching", "percentage": 90}, {"solution": "Increase default_query_job_config timeout parameter", "percentage": 87}]'::jsonb, 'BigQuery Python client', 'Large writes complete successfully', 'Attempting single insert for large datasets', 0.887, 'haiku', NOW(), 'https://stackoverflow.com/questions/75475875/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('BigQuery client Python timeout and polling issues', 'gcp', 'LOW', '[{"solution": "Update google-api-core to version 1.33.2 or later", "percentage": 89}, {"solution": "Set polling_interval for async operations", "percentage": 85}]'::jsonb, 'Python 3 with BigQuery client', 'BigQuery operations complete without timeout', 'Using outdated google-api-core version', 0.886, 'haiku', NOW(), 'https://stackoverflow.com/questions/74673148/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Google GCP Cloud Functions to BigQuery error', 'gcp', 'LOW', '[{"solution": "Ensure Cloud Function has BigQuery Editor role", "percentage": 91}, {"solution": "Enable BigQuery API and set GOOGLE_CLOUD_PROJECT env var", "percentage": 88}]'::jsonb, 'Cloud Functions integrated with BigQuery', 'Function successfully writes to BigQuery', 'Missing service account permissions', 0.885, 'haiku', NOW(), 'https://stackoverflow.com/questions/63045661/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Cloud Function is not triggered by Pub/Sub topic', 'gcp', 'LOW', '[{"solution": "Ensure Cloud Function has Pub/Sub Subscriber role", "percentage": 91}, {"solution": "Verify topic is correctly bound in function trigger config", "percentage": 89}]'::jsonb, 'Cloud Functions and Pub/Sub setup', 'Function executes on Pub/Sub message', 'Missing service account permissions for subscription', 0.884, 'haiku', NOW(), 'https://stackoverflow.com/questions/77915407/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('GCP Eventarc response code 500 using Pub/Sub trigger with Cloud Run', 'gcp', 'LOW', '[{"solution": "Check Cloud Run service returns proper HTTP status codes", "percentage": 88}, {"solution": "Ensure Cloud Run service has Pub/Sub Subscriber role", "percentage": 86}]'::jsonb, 'Eventarc with Cloud Run and Pub/Sub', 'Eventarc successfully triggers Cloud Run', 'Cloud Run service returning 5xx errors', 0.883, 'haiku', NOW(), 'https://stackoverflow.com/questions/70518146/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('HTTP 400 on Pub/Sub push to Cloud Run', 'gcp', 'LOW', '[{"solution": "Cloud Run service must accept POST requests with Pub/Sub message format", "percentage": 92}, {"solution": "Verify endpoint URL is public and accessible", "percentage": 89}]'::jsonb, 'Public Cloud Run service', 'Cloud Run receives Pub/Sub messages', 'Handler expecting different request format', 0.882, 'haiku', NOW(), 'https://stackoverflow.com/questions/69209115/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Cloud Run 429 the request was aborted because there was no available instance', 'gcp', 'LOW', '[{"solution": "Increase Cloud Run max instances: --max-instances=N", "percentage": 87}, {"solution": "Enable CPU always allocated: --cpu-throttling=False", "percentage": 84}]'::jsonb, 'Cloud Run service deployed', 'Requests no longer rejected due to capacity', 'Default max instances too low for load', 0.881, 'haiku', NOW(), 'https://stackoverflow.com/questions/62511117/', 'admin:1764221374');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Google Pub/Sub Cloud Run spawning multiple containers concurrency issue', 'gcp', 'LOW', '[{"solution": "Set --concurrency=N to control max concurrent requests per instance", "percentage": 89}, {"solution": "Use Pub/Sub acknowledgment deadlines to control retry behavior", "percentage": 86}]'::jsonb, 'Cloud Run with Pub/Sub integration', 'Controlled concurrency and no dropped messages', 'Uncontrolled concurrent request spawning', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/63365549/', 'admin:1764221374');
