INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

-- Priority Error 1: CANCELLED
('gRPC CANCELLED error context cancelled without error', 'rpc', 'HIGH', '[{"solution": "Use Context.fork() to create independent context that won''t be cancelled with inbound RPC", "percentage": 90}, {"solution": "Wrap async work in separate context using ctx.run() to prevent cancellation propagation", "percentage": 85}]'::jsonb, 'grpc-java with context support', 'No CANCELLED errors on independent async work', 'Not forking context for async operations', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/57110811/grpc-random-cancelled-exception-on-rpc-calls', 'admin:1764225811'),

-- Priority Error 2: UNKNOWN
('gRPC UNKNOWN service error unimplemented service', 'rpc', 'HIGH', '[{"solution": "Register service before calling grpc.Serve() - call RegisterXXXServer before Serve", "percentage": 95}, {"solution": "Ensure client and server use matching contract versions", "percentage": 85}]'::jsonb, 'gRPC Go with proto service definition', 'Service is reachable and responds to method calls', 'Registering service after server starts or version mismatch', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/50289261/getting-unimplemented-desc-unknown-service-error-grpc', 'admin:1764225811'),

-- Priority Error 3: INVALID_ARGUMENT
('gRPC INVALID_ARGUMENT resource exhausted bandwidth enhanced your calm', 'rpc', 'MEDIUM', '[{"solution": "Use Context objects instead of Metadata for multithreaded environments - Metadata is single-threaded", "percentage": 92}, {"solution": "Increase MaxCallSendMsgSize and MaxCallRecvMsgSize on client", "percentage": 88}]'::jsonb, 'gRPC with multithreading and load testing', 'Calls complete without INVALID_ARGUMENT errors under load', 'Using Metadata for multithreaded requests or wrong message size config', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/75606357/invalid-argument-resource-exhausted-connection-closed-after-goaway', 'admin:1764225811'),

-- Priority Error 4: DEADLINE_EXCEEDED
('gRPC DEADLINE_EXCEEDED timeout error client waiting', 'rpc', 'HIGH', '[{"solution": "Optimize server implementation to handle requests faster", "percentage": 90}, {"solution": "Increase client deadline with context.WithTimeout() to allow more time", "percentage": 85}, {"solution": "Implement exponential backoff retry strategy for transient failures", "percentage": 80}]'::jsonb, 'gRPC with deadline context support', 'Requests complete before deadline expires', 'Setting too aggressive deadline or slow server implementation', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/42973191/how-to-solve-grpc-deadline-exceeded-error', 'admin:1764225811'),

-- Priority Error 5: NOT_FOUND
('gRPC NOT_FOUND resource does not exist lookup failed', 'rpc', 'MEDIUM', '[{"solution": "Return NOT_FOUND status code when resource query returns empty", "percentage": 93}, {"solution": "Check database query before returning error to ensure resource existence", "percentage": 88}]'::jsonb, 'gRPC with database backend', 'Client receives proper 404-like error when resource missing', 'Returning UNKNOWN or INTERNAL instead of NOT_FOUND', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/52969205/how-to-assert-grpc-error-codes-client-side-in-go', 'admin:1764225811'),

-- Priority Error 6: ALREADY_EXISTS
('gRPC ALREADY_EXISTS resource duplicate creation conflict', 'rpc', 'MEDIUM', '[{"solution": "Check unique constraint violation in database and return ALREADY_EXISTS", "percentage": 92}, {"solution": "Include conflict details in error message to help client understand existing resource", "percentage": 87}]'::jsonb, 'gRPC with unique database constraints', 'Duplicate creation attempts return ALREADY_EXISTS with details', 'Returning INTERNAL on database constraint violation', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/76949763/good-designing-of-grpc-status-and-response', 'admin:1764225811'),

-- Priority Error 7: PERMISSION_DENIED
('gRPC PERMISSION_DENIED user not authorized HTTP2 TLS', 'rpc', 'HIGH', '[{"solution": "Ensure gRPC server uses HTTPS/TLS on port 50051", "percentage": 94}, {"solution": "Use HttpProtocols.Http2 in Kestrel server configuration", "percentage": 92}, {"solution": "Enable AppContext.SetSwitch for HTTP2 unencrypted support on client if needed", "percentage": 88}]'::jsonb, 'ASP.NET Core gRPC with AWS deployment', 'gRPC calls succeed with proper TLS configuration', 'Missing TLS setup on cloud deployment or wrong HTTP protocol', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/76818612/grpc-permission-denied', 'admin:1764225811'),

-- Priority Error 8: RESOURCE_EXHAUSTED
('gRPC RESOURCE_EXHAUSTED received message larger than max size', 'rpc', 'MEDIUM', '[{"solution": "Increase MaxCallRecvMsgSize on client side: grpc.MaxCallRecvMsgSize(32*10e6)", "percentage": 95}, {"solution": "Set MaxCallSendMsgSize on server to match or exceed client settings", "percentage": 93}]'::jsonb, 'gRPC Go with large message transfers', 'Large messages transferred without size limit errors', 'Using default 4MB limit without configuration or mismatched sizes', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/55362342/grpc-received-message-larger-than-max-8653851-vs-4194304', 'admin:1764225811'),

-- Priority Error 9: FAILED_PRECONDITION
('gRPC FAILED_PRECONDITION system state does not allow operation version mismatch', 'rpc', 'MEDIUM', '[{"solution": "Use FAILED_PRECONDITION for state-dependent operation failures not INVALID_ARGUMENT", "percentage": 91}, {"solution": "Include expected vs actual state in error message to guide client recovery", "percentage": 86}]'::jsonb, 'gRPC with versioned resource updates', 'Clients receive clear precondition failure messages and retry appropriately', 'Confusing FAILED_PRECONDITION with INVALID_ARGUMENT', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77983292/grpc-invalidargument-or-failedprecondition-if-system-cannot-be-updated', 'admin:1764225811'),

-- Priority Error 10: ABORTED
('gRPC ABORTED CORS error missing grpc-status header exposure', 'rpc', 'LOW', '[{"solution": "Expose grpc-status and grpc-message headers in CORS configuration", "percentage": 94}, {"solution": "Configure Envoy to pass through gRPC status headers in proxy setup", "percentage": 90}]'::jsonb, 'gRPC web with CORS and proxy', 'Frontend receives proper gRPC status codes via headers', 'CORS blocking gRPC status headers or proxy stripping headers', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/79473549/aborted-grpc-requests-erroring-in-the-frontend-with-rpcerror-missing-status', 'admin:1764225811'),

-- Priority Error 11: OUT_OF_RANGE
('gRPC OUT_OF_RANGE value exceeds acceptable bounds pagination index', 'rpc', 'LOW', '[{"solution": "Validate request parameters are within acceptable range before processing", "percentage": 93}, {"solution": "Return OUT_OF_RANGE status with clear bounds in error message", "percentage": 89}]'::jsonb, 'gRPC with numeric bounds validation', 'Requests with out-of-range values rejected with proper status code', 'Not validating bounds or returning INVALID_ARGUMENT instead', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/38901721/grpc-code-9-failed-precondition-on-time-time-filter-query-using-the-go-client', 'admin:1764225811'),

-- Priority Error 12: UNIMPLEMENTED
('gRPC UNIMPLEMENTED method not found service incomplete', 'rpc', 'MEDIUM', '[{"solution": "Ensure all service methods defined in proto are implemented", "percentage": 92}, {"solution": "Regenerate proto stubs if proto file was updated but stubs not rebuilt", "percentage": 90}]'::jsonb, 'gRPC service implementation with proto definitions', 'All defined RPC methods are callable and implemented', 'Missing method implementations or stale generated code', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/56794993/grpc-server-shows-unimplemented-service-error', 'admin:1764225811'),

-- Priority Error 13: INTERNAL
('gRPC INTERNAL failed to serialize response proto codec error', 'rpc', 'MEDIUM', '[{"solution": "Enable Python logging with logging.basicConfig(level=logging.INFO) to see actual error", "percentage": 92}, {"solution": "Ensure client and server proto files are consistent and regenerated together", "percentage": 94}, {"solution": "Check for type mismatches like returning wrong message type", "percentage": 89}]'::jsonb, 'gRPC Python with Django REST framework', 'Responses serialize correctly without codec errors', 'Proto version mismatch or type mismatches in serialization', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/69349406/python-grpc-error-error-13-internal-failed-to-serialize-response-when-tr', 'admin:1764225811'),

-- Priority Error 14: UNAVAILABLE
('gRPC UNAVAILABLE transport is closing connection abrupt', 'rpc', 'HIGH', '[{"solution": "Set MaxConnectionIdle on server: grpc.KeepaliveParams(MaxConnectionIdle: 5*time.Minute)", "percentage": 95}, {"solution": "Configure connection reuse and health checks on client side", "percentage": 88}]'::jsonb, 'gRPC with load balancer and cloud environment', 'Connections stay alive and gracefully close before timeout', 'Not configuring keepalive or connection idle timeout', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/52993259/problem-with-grpc-setup-getting-an-intermittent-rpc-unavailable-error', 'admin:1764225811'),

-- Priority Error 15: DATA_LOSS
('gRPC DATA_LOSS enum deserialization protobuf mismatch corruption', 'rpc', 'LOW', '[{"solution": "Ensure proto field numbers and types match exactly between client and server", "percentage": 93}, {"solution": "Validate all enum values are valid before returning to client", "percentage": 88}]'::jsonb, 'gRPC with enum serialization and proto evolution', 'Enum values deserialize correctly without data loss', 'Proto field number changes or enum value corruption', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/75454767/grpc-data-loss-error-code-usage-clarification', 'admin:1764225811'),

-- Priority Error 16: UNAUTHENTICATED
('gRPC UNAUTHENTICATED credentials required missing auth token', 'rpc', 'HIGH', '[{"solution": "Implement authentication interceptor to validate credentials before method execution", "percentage": 92}, {"solution": "Return UNAUTHENTICATED status code specifically for missing or invalid credentials", "percentage": 90}]'::jsonb, 'gRPC with security interceptors and auth headers', 'Unauthenticated requests properly rejected with UNAUTHENTICATED status', 'Not implementing auth interceptor or confusing with PERMISSION_DENIED', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/70146578/grpc-unauthenticated-exception-caused-by-method-not-foudn', 'admin:1764225811'),

-- Additional practical errors: 17
('gRPC custom error handling metadata error details passing', 'rpc', 'MEDIUM', '[{"solution": "Use google.rpc.Status proto with Details field for structured error information", "percentage": 92}, {"solution": "Pass error details via Metadata with custom key-value pairs for rich error info", "percentage": 88}]'::jsonb, 'gRPC with error detail propagation', 'Clients receive detailed error information with field-level messages', 'Using generic error strings without detailed error metadata', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/48748745/pattern-for-rich-error-handling-in-grpc', 'admin:1764225811'),

-- Additional practical errors: 18
('gRPC client timeout deadline context withTimeout milliseconds', 'rpc', 'MEDIUM', '[{"solution": "Create deadline context with ctx, cancel := context.WithTimeout(context.Background(), timeout)", "percentage": 94}, {"solution": "Use reasonable timeout values - 300ms might be too aggressive for remote calls", "percentage": 87}]'::jsonb, 'gRPC Go client with context management', 'Requests complete within timeout or cleanly timeout', 'Setting too aggressive timeout or forgetting to defer cancel()', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/60214864/grpc-client-timeout', 'admin:1764225811'),

-- Additional practical errors: 19
('gRPC connection refused dial kubernetes service discovery DNS', 'rpc', 'MEDIUM', '[{"solution": "Verify service name resolves correctly in Kubernetes DNS: service-name:port", "percentage": 91}, {"solution": "Ensure gRPC server pod is running and livenessProbe is not too strict", "percentage": 89}]'::jsonb, 'gRPC deployment on Kubernetes with service mesh', 'Kubernetes service DNS resolves and gRPC connects successfully', 'Using wrong service name or not waiting for pods to be ready', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/70131524/grpc-server-connection-refused', 'admin:1764225811'),

-- Additional practical errors: 20
('gRPC TLS negotiation failed ALPN protocol HTTP/2 SSL handshake', 'rpc', 'MEDIUM', '[{"solution": "Ensure server supports HTTP/2 with proper TLS configuration", "percentage": 94}, {"solution": "Install Play Services Dynamic Security Provider on Android for modern TLS", "percentage": 88}]'::jsonb, 'gRPC Java/Android with TLS transport security', 'TLS handshake succeeds and HTTP/2 is negotiated', 'Server not supporting HTTP/2 or outdated TLS library on client', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/52210169/dealing-with-tls-on-grpc', 'admin:1764225811'),

-- Additional practical errors: 21
('gRPC certificate verification InsecureSkipVerify self-signed CA', 'rpc', 'MEDIUM', '[{"solution": "For internal services, use InsecureTrustManagerFactory: GrpcSslContexts.forClient().trustManager(InsecureTrustManagerFactory.INSTANCE)", "percentage": 91}, {"solution": "For production, provide proper CA certificate chain to trustManager", "percentage": 95}]'::jsonb, 'gRPC with custom or self-signed certificates', 'gRPC calls succeed with appropriate certificate handling', 'Trying to verify invalid self-signed certs or missing CA chain', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/52540899/disabling-certificate-check-in-grpc-tls', 'admin:1764225811'),

-- Additional practical errors: 22
('gRPC oneof error response handling success or failure union type', 'rpc', 'LOW', '[{"solution": "Use oneof response { SuccessResponse success_response = 1; ErrorResponse error_response = 2; } pattern", "percentage": 89}, {"solution": "Check response.getResponseCase() to distinguish success from error on client", "percentage": 87}]'::jsonb, 'gRPC with proto union types (oneof)', 'Client properly handles both success and error response branches', 'Using status codes instead of oneof or not checking response case', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/52969205/how-to-assert-grpc-error-codes-client-side-in-go', 'admin:1764225811'),

-- Additional practical errors: 23
('gRPC server error HTTP proxy 400 status code mapping', 'rpc', 'LOW', '[{"solution": "Return proper gRPC status code with grpc-web for HTTP proxy to map to HTTP status", "percentage": 88}, {"solution": "Use status.Errorf(codes.CodeName, description) for proper status propagation", "percentage": 90}]'::jsonb, 'gRPC with HTTP proxy bridge and grpc-web', 'HTTP proxy correctly maps gRPC errors to HTTP status codes', 'Using wrong HTTP status or not returning gRPC status code', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/45455144/grpc-server-error-handler-golang', 'admin:1764225811'),

-- Additional practical errors: 24
('gRPC Python assertion error code client side test', 'rpc', 'LOW', '[{"solution": "Use status.FromError(err) to parse error and check status.Code()", "percentage": 92}, {"solution": "In tests, assert specific error codes with assertEqual(status.Code(err), codes.CodeType)", "percentage": 88}]'::jsonb, 'gRPC Python with unit tests', 'Tests properly assert expected error codes are returned', 'Not using status.FromError() or checking wrong exception type', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/52969205/how-to-assert-grpc-error-codes-client-side-in-go', 'admin:1764225811'),

-- Additional practical errors: 25
('gRPC channel configuration connection pool keep-alive parameters', 'rpc', 'MEDIUM', '[{"solution": "Set channel options with WithDefaultCallOptions for all calls", "percentage": 90}, {"solution": "Configure NettyChannelBuilder with keepAliveTime and keepAliveTimeout params", "percentage": 88}]'::jsonb, 'gRPC channel pooling and network optimization', 'Connections are efficiently pooled and kept alive without timeouts', 'Not configuring keep-alive or using default aggressive timeouts', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/60214864/grpc-client-timeout', 'admin:1764225811');
