-- Mine 30 Yarn Errors for clauderepo KB
-- Data collected from Stack Overflow

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('YN0000 info Resolution step fetch link completed logs', 'package-manager', 'HIGH', '[{"solution": "YN0000 codes are info-level logs and not actual errors - they are normal output from Yarn operations", "percentage": 100}, {"solution": "These logs indicate the progress of resolution, fetch, and link steps during yarn install", "percentage": 95}]'::jsonb, 'Yarn 3.x or later', 'yarn install completes successfully', 'Treating YN0000 as error when it is just informational', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/74420056/why-does-yarn-install-command-completes-with-errors-on-my-project', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('YN0001 exception error persisting cache unreachable', 'package-manager', 'HIGH', '[{"solution": "Node version issues can cause path and fs handling problems - try different Node version", "percentage": 85}, {"solution": "Check Github Actions environment and verify Node.js version compatibility", "percentage": 80}]'::jsonb, 'Node.js 18+, Yarn 4.x', 'yarn install succeeds with correct node version', 'Not verifying Node.js version compatibility with Yarn', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/79592514/yn0001-error-while-persisting-users-runner-yarn-berry-cache-expo-vector-ico', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('YN0002 missing peer dependency doesnt provide requested', 'package-manager', 'CRITICAL', '[{"solution": "Run yarn install again after encountering YN0002 warnings - Yarn will resolve peer dependencies", "percentage": 92}, {"solution": "Use yarn explain peer-requirements <hash> to debug specific peer dependency conflicts", "percentage": 88}, {"solution": "Ensure all peer dependency requirements are met in package.json", "percentage": 85}]'::jsonb, 'Yarn 1.x or later', 'All peer dependencies resolved without warnings', 'Ignoring YN0002 warnings instead of running yarn install again', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/73778417/yarn-berry-error-must-be-built-because-it-never-has-been-before-or-the-last-one', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('YN0007 must be built because never has been or last one failed', 'package-manager', 'HIGH', '[{"solution": "Cache clean and reinstall: yarn cache clean && yarn install", "percentage": 90}, {"solution": "Set yarn version to stable: yarn set version stable", "percentage": 85}, {"solution": "Update checksum behavior: YARN_CHECKSUM_BEHAVIOR=update yarn install", "percentage": 82}]'::jsonb, 'Yarn 3.x or later', 'All packages built successfully', 'Not clearing cache before reinstalling native packages', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/74420056/why-does-yarn-install-command-completes-with-errors-on-my-project', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('YN0013 unplugged cache package cannot be found fetch from registry', 'package-manager', 'MEDIUM', '[{"solution": "This is an informational message not an error - package will be downloaded from registry", "percentage": 100}, {"solution": "Ensure stable network connection for fetching from registry", "percentage": 95}]'::jsonb, 'Yarn 3.x or later', 'Package successfully fetched from registry', 'Treating YN0013 as a critical error', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/74420056/why-does-yarn-install-command-completes-with-errors-on-my-project', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('YN0019 outdated lockfile appears to be unused removing', 'package-manager', 'MEDIUM', '[{"solution": "YN0019 is a cleanup message indicating unused cache entries are being removed", "percentage": 100}, {"solution": "This is normal behavior during Yarn install and not a problem", "percentage": 98}]'::jsonb, 'Yarn 2.x or later', 'yarn install completes without errors', 'Treating YN0019 cleanup messages as errors', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/59982445/yn0000-resolution-step-error-on-react-js', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('YN0028 lockfile would have been modified frozen install forbidden', 'package-manager', 'CRITICAL', '[{"solution": "Fresh clone from git: git clone, then run yarn install to generate fresh lockfile", "percentage": 92}, {"solution": "Disable immutable installs: YARN_ENABLE_IMMUTABLE_INSTALLS=false", "percentage": 88}, {"solution": "Check git submodules not properly committed - remove and re-add workspace folders", "percentage": 85}]'::jsonb, 'Yarn 2.x or later, CI environment', 'Lockfile matches all dependencies without modification', 'Not committing updated lockfile to git before CI', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/67062308/getting-yn0028-the-lockfile-would-have-been-modified-by-this-install-which-is-e', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('YN0082 No candidates found version resolution failure', 'package-manager', 'CRITICAL', '[{"solution": "Clear Yarn Berry metadata cache: rm -r ~/.yarn/berry/metadata/npm/", "percentage": 90}, {"solution": "Use compatible Yarn version: yarn set version 3.6.4 instead of 4.0.2", "percentage": 88}]'::jsonb, 'Yarn 3.x or later', 'Package resolves to available version', 'Not clearing metadata cache when versions are available but not found', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/77593499/why-does-yarn-fail-with-no-candidates-found-errors/77695841', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('yarn-error.log file created at root directory on error', 'package-manager', 'HIGH', '[{"solution": "Check yarn-error.log at project root for detailed error information", "percentage": 100}, {"solution": "Include yarn-error.log in CI artifacts for debugging: artifacts: paths: [yarn-error.log]", "percentage": 95}]'::jsonb, 'Yarn 1.x or later', 'Error logs available for analysis', 'Not checking yarn-error.log for actual error details', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/55834349/what-is-the-path-to-yarn-error-log-files', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn incorrect peer dependency warning package not matched', 'package-manager', 'MEDIUM', '[{"solution": "Update peer dependency in package.json to match required version", "percentage": 92}, {"solution": "Manually install peer dependency: yarn add -D package@version", "percentage": 88}]'::jsonb, 'Yarn 1.x or later', 'No peer dependency warnings on yarn install', 'Not understanding peer dependencies are not auto-installed', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/42361942/when-installing-packages-with-yarn-what-does-incorrect-peer-dependency-mean', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn unmet peer dependency vue-loader vue-template-compiler', 'package-manager', 'MEDIUM', '[{"solution": "Run yarn install --check-files to ensure all peer dependencies are installed", "percentage": 90}, {"solution": "Manually add missing peer dependency to package.json", "percentage": 85}]'::jsonb, 'Yarn 1.x or later', 'All peer dependencies satisfied', 'Peer dependencies not auto-installed in npm3+ compatible managers', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/46928390/what-does-has-unmet-peer-dependency-mean-when-installing-a-package-with-yarn', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('yarn.lock merge conflict git automatic merge failed', 'package-manager', 'HIGH', '[{"solution": "Run yarn install after resolving package.json conflicts - Yarn will auto-merge yarn.lock", "percentage": 95}, {"solution": "Use git checkout origin/master -- yarn.lock then yarn install to regenerate", "percentage": 90}]'::jsonb, 'Yarn 1.x or later', 'yarn.lock merged successfully and yarn install completes', 'Manually editing or deleting yarn.lock during merge conflicts', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/42939113/how-do-you-resolve-git-conflicts-in-yarn-lock', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EACCES permission denied unlink yarn-integrity node_modules', 'package-manager', 'HIGH', '[{"solution": "Remove node_modules with sudo rm -rf node_modules/ then run yarn without sudo", "percentage": 92}, {"solution": "Fix permissions: sudo chown -R $USER:$GROUP node_modules/", "percentage": 88}]'::jsonb, 'Yarn 1.x or later', 'yarn install succeeds without permission errors', 'Running yarn with sudo causing permission issues', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/55157150/yarn-install-eacces-permission-denied-unlink-yarn-integrity', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EACCES permission denied mkdir cacache workspace node_modules', 'package-manager', 'HIGH', '[{"solution": "Set correct ownership: sudo chown -R $USER node_modules/", "percentage": 90}, {"solution": "Change permissions: sudo chmod -R u+w /your/project/directory", "percentage": 85}]'::jsonb, 'Yarn 1.x or later with workspaces', 'yarn install succeeds without permission errors', 'Not addressing persistent permission issues with workspace setup', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/62355079/yarn-eacces-permission-denied', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn workspaces node_modules not created NodeLinker PnP', 'package-manager', 'CRITICAL', '[{"solution": "Add nodeLinker: node-modules to .yarnrc.yml to use legacy linker", "percentage": 95}, {"solution": "Add nmHoistingLimits: workspaces to prevent hoisting across workspace boundaries", "percentage": 88}]'::jsonb, 'Yarn 2.x or later', 'node_modules folder created and dependencies installed', 'Not configuring nodeLinker when upgrading to Yarn 2+', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/66819276/yarn-2-workspaces-not-installing-dependencies', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn PnP multiple pnpapi instances test error', 'package-manager', 'CRITICAL', '[{"solution": "Use workspace-relative PnP setup instead of per-workspace .pnp.cjs files", "percentage": 85}, {"solution": "Disable global cache: enableGlobalCache: false in .yarnrc.yml", "percentage": 80}]'::jsonb, 'Yarn 2.x or later with PnP', 'Tests run with single pnpapi instance', 'Creating separate .pnp.cjs in each workspace instead of using root', 0.76, 'haiku', NOW(), 'https://stackoverflow.com/questions/71366461/yarn-2-workspaces-pnp-and-unit-tests-in-child-workspaces', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ENOTFOUND registry.yarnpkg.com DNS resolution error', 'package-manager', 'HIGH', '[{"solution": "Upgrade yarn and clear cache: yarn cache clean", "percentage": 90}, {"solution": "Delete yarn.lock and reinstall: rm yarn.lock && yarn install", "percentage": 88}]'::jsonb, 'Yarn 1.x or later', 'yarn install succeeds with network connectivity', 'Network connectivity issues or DNS problems', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/68037425/enotfound-registry-yarnpkg-com-error-while-running-yarn-install', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ECONNREFUSED connection refused localhost proxy DNS hosts file', 'package-manager', 'MEDIUM', '[{"solution": "Check DNS settings and verify hosts file does not have invalid entries", "percentage": 92}, {"solution": "Switch to Google DNS: 8.8.8.8 and 8.8.4.4", "percentage": 88}]'::jsonb, 'Yarn 1.x or later', 'Connection to registry succeeds', 'ISP blocking or local proxy interference', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/58587383/yarn-error-connect-econnrefused-127-0-0-1443', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn integrity check failed computed hash mismatch package', 'package-manager', 'CRITICAL', '[{"solution": "Update checksums: yarn --update-checksums", "percentage": 95}, {"solution": "For Yarn 3+: yarn cache clean --all && yarn up --mode update-lockfile", "percentage": 92}, {"solution": "Remove problematic entry from yarn.lock and reinstall", "percentage": 88}]'::jsonb, 'Yarn 1.x or later', 'All packages pass integrity check', 'Registry tampering or cache corruption', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/75634734/why-running-yarn-commands-is-giving-an-error-integrity-check-failed-for-yargs', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn integrity check failed checksums multiple registries', 'package-manager', 'HIGH', '[{"solution": "Set networkConcurrency 1 in .yarnrc file for sequential downloads", "percentage": 92}, {"solution": "Delete yarn.lock and reinstall fresh: rm yarn.lock && yarn install", "percentage": 88}]'::jsonb, 'Yarn 1.x or later with private registries', 'All packages install without integrity errors', 'Parallel downloads causing race conditions with multiple registries', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/78914776/yarn-install-failing-with-integrity-check-failed-but-checksums-and-hashes', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn offline mode pack install lockfile missing entry', 'package-manager', 'MEDIUM', '[{"solution": "First install online to create yarn.lock entries: yarn install", "percentage": 95}, {"solution": "Pack package: yarn pack --filename @scope/[email protected]", "percentage": 90}, {"solution": "Never delete yarn.lock when using offline mode", "percentage": 100}]'::jsonb, 'Yarn 1.x or later', 'Offline install succeeds from local mirror', 'Attempting offline install without first creating lockfile', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/55023058/pack-and-install-node-package-in-offline-mode-with-yarn', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn install hangs Building fresh packages offline mode', 'package-manager', 'MEDIUM', '[{"solution": "This is often a normal operation during offline install with large dependency trees", "percentage": 85}, {"solution": "Check disk space and system resources", "percentage": 80}]'::jsonb, 'Yarn 1.x or later', 'Build completes within reasonable time', 'Timeout expectations too strict for large dependency graphs', 0.79, 'haiku', NOW(), 'https://stackoverflow.com/questions/52325562/yarn-install-hangs-in-offline-mode', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn workspaces binary compilation post-install hook failed', 'package-manager', 'HIGH', '[{"solution": "Ensure binaries are compiled before workspace dependencies reference them", "percentage": 88}, {"solution": "Use postinstall scripts in workspace root to build native modules", "percentage": 85}]'::jsonb, 'Yarn 1.x with workspaces', 'Native binaries build successfully before workspace linking', 'Building binaries after workspace installation', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/51429190/with-yarn-workspaces-how-can-compiled-binaries-be-linked-to-the-workspace-post', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn build fail Module parse Babel loader unexpected token', 'package-manager', 'HIGH', '[{"solution": "Downgrade Babel: @babel/core 7.19.6, @babel/generator 7.19.6", "percentage": 92}, {"solution": "Add Babel versions to resolutions section instead of dependencies", "percentage": 90}]'::jsonb, 'Yarn 1.x or later with Babel', 'Build completes without module parsing errors', 'Using outdated Babel versions incompatible with dependencies', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/74330344/getting-an-error-during-yarn-build-in-react-js', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn unable to verify the first certificate SSL TLS error', 'package-manager', 'HIGH', '[{"solution": "Disable strict SSL: yarn config set \"strict-ssl\" false -g", "percentage": 92}, {"solution": "Provide certificate path: yarn config set cafile /path/to/certificate.pem", "percentage": 88}]'::jsonb, 'Yarn 1.x or later', 'SSL connections succeed with proper certificate configuration', 'Corporate proxy or self-signed certificates not recognized', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/40033794/yarn-unable-to-verify-the-first-certificate', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn private packages unable to get local issuer certificate', 'package-manager', 'HIGH', '[{"solution": "Add npmScopes config with certificate for private registry", "percentage": 90}, {"solution": "Use enableScripts: false for registries with certificate issues", "percentage": 85}]'::jsonb, 'Yarn 2.x or later', 'Private package authentication succeeds', 'Not configuring per-registry SSL settings in .yarnrc.yml', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/60225897/yarn-2-0-unable-to-get-local-issuer-certificate', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Circular dependency resolution visx library exports', 'package-manager', 'MEDIUM', '[{"solution": "Add explicit dependency: add missing package to package.json even if transitive", "percentage": 95}, {"solution": "Review export chains for circular dependencies between packages", "percentage": 88}]'::jsonb, 'Yarn 1.x with workspaces', 'No circular dependency warnings during build', 'Not explicitly declaring all required dependencies', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/66772064/how-to-resolve-circular-dependency-in-compilation-of-node-modules', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn workspaces hoisting modules only exist one workspace', 'package-manager', 'HIGH', '[{"solution": "Add nohoist to workspace: \"nohoist\": \"**\" in workspace package.json", "percentage": 92}, {"solution": "For React Native: prevent hoisting of native modules with specific nohoist patterns", "percentage": 88}]'::jsonb, 'Yarn 1.x with workspaces', 'Dependencies installed only in their workspace node_modules', 'Not using nohoist for workspace-specific dependencies', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/65984258/yarn-workspaces-is-hoisting-modules-that-exist-in-only-one-workspace', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn PnP Cannot find module Berry js missing release file', 'package-manager', 'CRITICAL', '[{"solution": "Remove .yarnrc.yml and reconfigure: yarn set version berry", "percentage": 92}, {"solution": "Add yarn-berry.js to .gitignore: .yarn/releases/ in .gitignore", "percentage": 90}]'::jsonb, 'Yarn 2.x or later', 'yarn commands execute without MODULE_NOT_FOUND errors', 'Not committing .yarn/releases files after yarn set version', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/62456078/yarn-install-leads-to-cannot-find-module-yarn-berry-js', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Yarn 3 Cannot find module lodash PnP require without yarn node', 'package-manager', 'HIGH', '[{"solution": "Use yarn node to run scripts: yarn node index.js instead of node index.js", "percentage": 96}, {"solution": "Set NODE_OPTIONS environment variable: NODE_OPTIONS=\"--require ./.pnp.cjs\" node index.js", "percentage": 92}]'::jsonb, 'Yarn 3.x with PnP', 'Scripts execute successfully with proper module resolution', 'Running node directly without yarn node wrapper for PnP', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/70446257/cannot-find-module-using-yarn-v-3', 'admin:1764228467');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('yarn spawn ENOENT process executable not found child', 'package-manager', 'MEDIUM', '[{"solution": "Check PATH environment variable includes yarn binary location", "percentage": 92}, {"solution": "Verify yarn is installed globally: which yarn", "percentage": 95}]'::jsonb, 'Yarn 1.x or later', 'yarn spawn commands execute without ENOENT', 'Yarn executable not in system PATH', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/65843263/how-to-resolve-this-error-spawn-yarn-enoent', 'admin:1764228467');
