-- AWS Lambda Troubleshooting - Official Docs Mining
-- Source: docs.aws.amazon.com/lambda/latest/dg/lambda-troubleshooting.html
-- Mined: 2025-11-25

INSERT INTO knowledge_entries (
    query, category, hit_frequency, solutions, prerequisites, success_indicators,
    common_pitfalls, success_rate, claude_version, last_verified, source_url
) VALUES (
    'Task timed out after 3 seconds - Lambda init phase timeout',
    'aws-lambda',
    'HIGH',
    $$[{"solution": "Extend function timeout duration to allow init phase to complete. Timeout range is 1-900 seconds.", "percentage": 85, "note": "Init phase exceeds configured timeout", "command": "aws lambda update-function-configuration --function-name <name> --timeout <seconds>"}, {"solution": "Increase memory allocation to 1769+ MB to get proportional CPU boost (1.8GB = 1vCPU)", "percentage": 90, "note": "More CPU reduces initialization time"}]$$::jsonb,
    'Function must be in Active state; memory allocation minimum 128 MB',
    'Function enters Active state; invocations complete before timeout; verify via CloudWatch START log',
    'Assuming timeout is only handler timeout, not init timeout; not optimizing initialization code before increasing resources',
    0.88,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-invocation.html'
),
(
    'EACCES: permission denied, open /var/task - Lambda deployment file permissions error',
    'aws-lambda',
    'HIGH',
    $$[{"solution": "Adjust file permissions using chmod 644 for non-executable files and 755 for directories/executables before packaging ZIP", "percentage": 95, "note": "Linux/MacOS environments", "command": "chmod 644 <filepath> && chmod 755 <directory>"}, {"solution": "Repackage deployment ZIP with correct permissions and redeploy", "percentage": 95}]$$::jsonb,
    'Linux or MacOS development environment; original source files accessible',
    'Deployment succeeds; function code loads without permission errors; CloudWatch logs appear within 5-10 minutes',
    'Forgetting to fix permissions before zipping; assuming Windows file permissions apply; not verifying permissions after extraction',
    0.92,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-deployment.html'
),
(
    'RequestEntityTooLargeException - Lambda deployment package exceeds 50 MB limit',
    'aws-lambda',
    'HIGH',
    $$[{"solution": "Store deployment package in Amazon S3 bucket in same region as Lambda function. Use S3Bucket and S3Key parameters in UpdateFunctionCode API", "percentage": 95, "note": "Direct ZIP upload limit is ~50MB; S3 supports much larger packages", "command": "aws lambda update-function-code --function-name <name> --s3-bucket <bucket> --s3-key <key>"}, {"solution": "Note that Base64 encoding increases file size ~30%; account for this in size calculations", "percentage": 100, "note": "Critical for large uploads"}]$$::jsonb,
    'S3 bucket exists in same region as Lambda; S3 bucket contains deployment package; appropriate IAM permissions for S3 access',
    'UpdateFunctionCode succeeds; CodeSha256 changes; new function version available in console',
    'Using direct upload for packages over 50MB; not accounting for Base64 encoding overhead; S3 bucket in different region',
    0.93,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-deployment.html'
),
(
    'Cannot find module / Unable to import module - Lambda handler resolution failure',
    'aws-lambda',
    'HIGH',
    $$[{"solution": "Verify handler configuration matches actual code implementation. Handler format: filename.methodname (e.g., index.handler for index.js with handler function)", "percentage": 90, "note": "Common across Node.js, Python, Ruby, Java, Go, C#, PowerShell", "command": "aws lambda get-function-configuration --function-name <name> | grep Handler"}, {"solution": "Reference language-specific runtime documentation for correct handler naming conventions", "percentage": 95, "note": "Each runtime has specific requirements"}]$$::jsonb,
    'Function code deployed; handler file and method exist; correct file permissions',
    'Function successfully loads handler; no import/module errors in CloudWatch logs; function ready for invocation',
    'Typos in handler name; incorrect path separators; case sensitivity issues; handler in subdirectory not reflected in config',
    0.91,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-deployment.html'
),
(
    'User is not authorized to perform: lambda:InvokeFunction - IAM authorization failure',
    'aws-lambda',
    'HIGH',
    $$[{"solution": "Add AWSLambdaRole policy to user role or custom policy granting lambda:InvokeFunction action", "percentage": 95, "note": "Missing permissions on invoker identity", "command": "aws iam attach-role-policy --role-name <role> --policy-arn arn:aws:iam::aws:policy/AWSLambdaRole"}, {"solution": "For cross-account invocation, add resource-based policy on Lambda function granting invoke permissions to remote account", "percentage": 90, "note": "Cross-account requires both identity and resource-based policies"}]$$::jsonb,
    'User/role exists; target Lambda function exists; IAM access to manage policies',
    'InvokeFunction API calls succeed; function executes without authorization errors; CloudWatch logs show invocations',
    'Only updating identity policy without resource-based policy for cross-account; not checking principal in policy document; assuming $LATEST has permissions',
    0.94,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-invocation.html'
),
(
    'Memory configuration insufficient - Lambda function slower than expected',
    'aws-lambda',
    'HIGH',
    $$[{"solution": "Increase memory allocation (128 MB minimum, up to 10,240 MB). CPU scales proportionally: 1.8GB = 1vCPU, 10,240MB = 6vCPUs", "percentage": 95, "note": "Higher memory = higher CPU throughput", "command": "aws lambda update-function-configuration --function-name <name> --memory-size <mb>"}, {"solution": "Test with realistic upper-bound datasets to identify memory-bound performance bottlenecks", "percentage": 90, "note": "Load test with production-size payloads"}]$$::jsonb,
    'Function must be in Active state; baseline memory allocation known',
    'Function duration decreases; CloudWatch metrics show improved performance; no OutOfMemory errors; function completes within timeout',
    'Setting memory too low for library-heavy functions; not measuring performance before/after; assuming CPU scales independently',
    0.92,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-configuration.html'
),
(
    'Code storage limit exceeded - Lambda account quota at 75 GB per region',
    'aws-lambda',
    'MEDIUM',
    $$[{"solution": "Delete unused function versions and aliases to free storage. AWS accounts receive 75GB per Region limit.", "percentage": 90, "note": "Only published versions consume storage; $LATEST does not"}, {"solution": "Implement Lambda layers to share code across functions instead of duplicating in each", "percentage": 85, "note": "Reduces per-function storage footprint"}, {"solution": "Request additional AWS accounts for distinct workloads to distribute storage quota", "percentage": 70, "note": "Multi-account strategy for large deployments"}]$$::jsonb,
    'Access to Lambda console or AWS CLI; function versions must exist to delete',
    'Storage usage decreases in Lambda console Dashboard; new versions publishable; no 413 errors on deployment',
    'Deleting $LATEST (not possible); not verifying storage before deploying new versions; not using layers for shared dependencies',
    0.88,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-deployment.html'
),
(
    'Lambda memory leak - global variables retain state across warm invocations',
    'aws-lambda',
    'MEDIUM',
    $$[{"solution": "Use INIT phase for global setup; place initialization code outside handler function. Lambda automatically manages INIT lifecycle.", "percentage": 88, "note": "INIT code runs once per execution environment"}, {"solution": "Check third-party library documentation for serverless compatibility and memory leak patterns", "percentage": 82, "note": "Libraries may accumulate state across invocations"}, {"solution": "Compare awsRequestId from context object with callback ID to detect cross-invocation data leakage", "percentage": 75, "note": "Diagnostic tool for identifying state retention issues"}]$$::jsonb,
    'Function code accessible; knowledge of runtime initialization phases; ability to modify handler code',
    'Duration remains consistent across warm invocations; memory usage stable in CloudWatch metrics; no timeout errors from paging',
    'Initializing state inside handler; not properly managing global variable lifecycle; callbacks executing outside handler scope',
    0.81,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-configuration.html'
),
(
    'Asynchronous callback results appear in later invocation - data leakage across executions',
    'aws-lambda',
    'MEDIUM',
    $$[{"solution": "Use async/await keywords to force completion before handler exit. Async operations must await before handler returns.", "percentage": 92, "note": "Ensures callbacks complete in same invocation"}, {"solution": "Return promises directly to runtime instead of executing callbacks asynchronously without awaiting", "percentage": 90, "note": "Runtime waits for promise resolution"}]$$::jsonb,
    'Function uses async/await or promise-based patterns; handler can be modified',
    'Private data from previous invocation not visible in subsequent invocation; CloudWatch logs show single invocation per callback; awsRequestId consistent within invocation',
    'Fire-and-forget callback patterns; not awaiting async operations; callbacks scheduled without await; multiple invocations handling single callback',
    0.89,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-configuration.html'
),
(
    'Invalid alias configuration for provisioned concurrency - initialization failures prevent pre-initialization',
    'aws-lambda',
    'MEDIUM',
    $$[{"solution": "Rollback alias to known-good version: aws lambda update-alias --function-name <name> --name <alias-name> --function-version <version>", "percentage": 95, "note": "Restores function to stable state"}, {"solution": "Fix initialization code to eliminate uncaught exceptions and properly initialize clients/connections", "percentage": 93, "note": "Prevents resource constraint errors"}, {"solution": "Redeploy corrected code, publish new version, then update alias to new version", "percentage": 92, "note": "Complete deployment cycle after fixing issues"}]$$::jsonb,
    'Function with provisioned concurrency; alias configuration in place; ability to modify and redeploy code',
    'Alias successfully points to new version; provisioned concurrency instances fully initialized; ProvisionedConcurrencyInvocations metric non-zero',
    'Not checking code for uncaught exceptions before deployment; assuming resource constraints not fixable; not verifying client initialization',
    0.90,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-deployment.html'
),
(
    'Environment variables exceed 4KB limit - InvalidParameterValueException',
    'aws-lambda',
    'MEDIUM',
    $$[{"solution": "Remove non-essential environment variables or reduce value sizes. Limit is 4096 bytes including keys, values, quotes, commas, and brackets.", "percentage": 93, "note": "Standard ASCII = 1 byte; extended ASCII/Unicode = 2-4 bytes per character"}, {"solution": "Store large configuration in S3, DynamoDB, or Secrets Manager and reference via single environment variable", "percentage": 88, "note": "Externalizes configuration beyond 4KB limit"}]$$::jsonb,
    'Access to function configuration; understanding of character encoding overhead',
    'UpdateFunctionConfiguration succeeds; environment variables populate in CloudWatch Lambda context; no 400 errors on invocation',
    'Not accounting for quotes and commas in size calculation; using Unicode characters without considering byte overhead; not externalizing large configs',
    0.91,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-deployment.html'
),
(
    'CloudWatch Logs missing - insufficient execution role permissions',
    'aws-lambda',
    'HIGH',
    $$[{"solution": "Add AWSLambdaBasicExecutionRole managed policy to function execution role", "percentage": 96, "note": "Grants logs:CreateLogGroup, logs:CreateLogStream, logs:PutLogEvents", "command": "aws iam attach-role-policy --role-name <role> --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"}, {"solution": "After updating permissions, deploy code or config change to replace running instances with updated credentials", "percentage": 95, "note": "Credentials cached until container recycles"}]$$::jsonb,
    'Function execution role exists; IAM permissions to attach policies; function must execute at least once after policy attachment',
    'Logs appear in CloudWatch Logs within 5-10 minutes of first invocation; START, END, REPORT lines visible; no permission denied errors',
    'Only attaching policy without updating function; checking logs immediately without waiting for container recycle; policy attached to wrong role',
    0.95,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-execution.html'
),
(
    'VPC: Function loses internet access - missing NAT gateway or packet fragmentation',
    'aws-lambda',
    'HIGH',
    $$[{"solution": "Configure NAT gateway in public subnet to route outbound traffic. Lambda cannot handle IP fragmentation for TCP/ICMP.", "percentage": 92, "note": "Solves both ETIMEDOUT and fragmentation issues", "command": "aws ec2 create-nat-gateway --subnet-id <subnet-id> --allocation-id <eip-allocation-id>"}, {"solution": "Verify route table has 0.0.0.0/0 route pointing to NAT gateway (not internet gateway for Lambda in private subnet)", "percentage": 91, "note": "Direct internet gateway routing bypasses NAT"}]$$::jsonb,
    'VPC configured for Lambda function; public subnet with internet gateway available; Elastic IP address available',
    'Outbound HTTPS requests complete without timeout; external API calls succeed; network trace shows traffic through NAT gateway',
    'Using internet gateway directly instead of NAT gateway; not creating NAT gateway in correct subnet; assuming IPv6 works the same as IPv4',
    0.90,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-networking.html'
),
(
    'ENILimitReachedException - Lambda elastic network interface quota exceeded',
    'aws-lambda',
    'MEDIUM',
    $$[{"solution": "Request quota increase via Service Quotas console for quota ID L-9FEE3D26 (ENI limit per VPC, default 250)", "percentage": 94, "note": "Hyperplane ENI architecture requires ENI per concurrent execution", "command": "aws service-quotas request-service-quota-increase --service-code vpc --quota-code L-9FEE3D26 --desired-value <new-limit>"}, {"solution": "Alternatively, reduce concurrent Lambda invocations by lowering reserved concurrency or distributing across regions", "percentage": 70, "note": "Temporary mitigation if quota increase delayed"}]$$::jsonb,
    'VPC configured for Lambda; ability to request quota increase from AWS Support; current quota limit known',
    'ENI quota increase approved in Service Quotas; Lambda functions successfully attach to VPC without 417 error; concurrent invocations proceed',
    'Assuming 250 ENI limit is hard ceiling; not accounting for account-wide VPC usage; not considering Lambda cold start ENI lifecycle',
    0.88,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-networking.html'
),
(
    'Lambda function stuck in Pending state - cannot invoke or modify',
    'aws-lambda',
    'MEDIUM',
    $$[{"solution": "If Pending >6 minutes, call UpdateFunctionCode, UpdateFunctionConfiguration, or PublishVersion API to unblock", "percentage": 96, "note": "VPC attachment during creation locks function state"}, {"solution": "Wait for state transition if <6 minutes; do not attempt invocations or modifications during Pending state", "percentage": 90, "note": "Concurrent operations will fail with ResourceConflictException"}]$$::jsonb,
    'Function must be created or recently updated; network connectivity available; API access with appropriate IAM permissions',
    'Function transitions from Pending to Active state; invocations accepted; modifications succeed; Lambda console shows Active status',
    'Attempting invocations during Pending state; not waiting for VPC attachment to complete; deleting and recreating function unnecessarily',
    0.94,
    'sonnet-4',
    NOW(),
    'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-invocation.html'
);
