INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Chromatic GitHub Action publish-to-chromatic timeout error after 10 minutes', 'general', 'HIGH', '[{"solution": "Check for filename case mismatches between local and remote - rename files using git mv -f to match case exactly", "percentage": 95}, {"solution": "Verify all component imports use correct case - case sensitivity on some systems causes Chromatic build timeouts", "percentage": 90}]'::jsonb, 'GitHub Actions workflow setup with Chromatic, Storybook configured', 'Chromatic build succeeds within normal time limit (under 5 minutes), GitHub Action completes without timeout', 'Changing file case directly without git mv can cause git to not recognize the change, leading to case mismatch between local and remote', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/78537014/publish-to-chromatic-github-action-timeout-error', 'admin:1764191461'),

('Node.js Error: connect ECONNREFUSED - server connection refused on localhost', 'general', 'HIGH', '[{"solution": "Verify the target server is running on the specified host and port before making requests", "percentage": 97}, {"solution": "Replace localhost with 127.0.0.1 if DNS resolution issues occur - Node.js may have issues resolving localhost on some systems", "percentage": 88}, {"solution": "Add uncaughtException handler to keep server running and enable debugging: process.on(''uncaughtException'', function(err) { console.log(err); })", "percentage": 85}]'::jsonb, 'Node.js server, target service running on specific port', 'HTTP request completes successfully without ECONNREFUSED error, server responds to requests', 'Not starting the target server before connecting, using localhost instead of 127.0.0.1 when DNS issues exist, failing to handle uncaught exceptions', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/14168433/node-js-error-connect-econnrefused', 'admin:1764191461'),

('Passport.js connection timeout with MongoDB - intermittent database connection timeout', 'general', 'HIGH', '[{"solution": "Index the MongoDB collections used in authentication - run ensureIndex on username and password fields: db.citizens.ensureIndex({ username: 1, password: 1 })", "percentage": 96}, {"solution": "Optimize database query performance when database grows beyond 2GB - add indexes to frequently queried fields before authentication triggers", "percentage": 93}]'::jsonb, 'MongoDB connection established, Passport.js middleware configured, MEAN Stack application', 'Passport authentication completes consistently under 5 seconds, no timeout errors in 100+ consecutive login attempts', 'Skipping database indexing, not optimizing queries for large collections, assuming timeout is application code issue when it''s database performance', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/41385181/passportjs-events-js160-unhandled-error-connection-timeout', 'admin:1764191461'),

('MobX timeout - predicate not fulfilled and timeout not triggered', 'general', 'MEDIUM', '[{"solution": "Use whenWithTimeout from mobx-utils package for versions before 4.0.0", "percentage": 94}, {"solution": "For MobX 4.0.0+, pass timeout as third parameter option: when(() => condition, () => effect, { timeout: 1000 })", "percentage": 96}]'::jsonb, 'MobX 4.0.0 or higher installed, observable state configured', 'when() predicate fires within specified timeout regardless of condition, code executes as expected', 'Passing timeout directly to when without options object, using incorrect syntax for timeout parameter, not checking MobX version before implementation', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/54889836/having-a-timeout-for-mobxs-when', 'admin:1764191461'),

('Recoil "Did not retain recoil value on render, or committed after timeout elapsed" warning', 'general', 'MEDIUM', '[{"solution": "Ignore this warning - it''s a known Recoil issue that occurs unnecessarily and will be fixed in next release, does not indicate code problem", "percentage": 100}, {"solution": "If warning persists across releases, verify atom definitions are correct and async selectors handle errors properly", "percentage": 75}]'::jsonb, 'Recoil 0.3.0+, react-testing-library configured, new atom just added', 'Warning no longer appears in console or test output after Recoil version update, tests pass successfully', 'Attempting to fix warning when none is needed, changing atom structure unnecessarily, assuming tests are failing when warning is just informational', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/68118088/what-does-did-not-retain-recoil-value-on-render-or-committed-after-timeout-ela', 'admin:1764191461'),

('Clerk middleware taking too long to load - Next.js Vercel 504 FUNCTION_INVOCATION_TIMEOUT', 'general', 'HIGH', '[{"solution": "Remove duplicate routes from publicRoutes and ignoredRoutes - having same route in both causes middleware to run slowly", "percentage": 97}, {"solution": "Configure middleware correctly: publicRoutes for auth access, ignoredRoutes to skip middleware entirely, never duplicate", "percentage": 95}]'::jsonb, 'Clerk authentication configured, Next.js middleware.ts file, Vercel deployment', 'Middleware loads in under 3 seconds, deployment completes without 504 timeout error, page loads successfully', 'Duplicating routes in both publicRoutes and ignoredRoutes, misconfiguring route matchers, not separating concerns between public and ignored routes', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/78131983/clerk-middleware-is-taking-too-long-to-load-resulting-in-nextjs-vercel-504-e', 'admin:1764191461'),

('npm Error: connect ECONNREFUSED xxx.xxx.xx.xxx:xxx - npm registry connection refused', 'general', 'HIGH', '[{"solution": "Reset npm proxy configuration: npm config set proxy null && npm config set https-proxy null && npm config set registry http://registry.npmjs.org/", "percentage": 96}, {"solution": "If behind corporate proxy, configure npm proxy settings properly with correct protocol and port, see npm help config", "percentage": 92}]'::jsonb, 'npm and Node.js installed, network connectivity established', 'npm install completes successfully, packages download from official registry without connection errors', 'Not clearing existing proxy settings before setting new ones, configuring wrong registry URL, assuming firewall issue when proxy is misconfigured', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/42371380/npm-err-error-connect-econnrefused-when-trying-to-update-the-npm', 'admin:1764191461'),

('Passport.js server timeout when rendering response after Facebook authentication', 'general', 'MEDIUM', '[{"solution": "Explicitly send rendered HTML in callback: res.render(''template'', data, function(err, html) { res.end(html); })", "percentage": 94}, {"solution": "Ensure session middleware is configured: app.use(connect.session({ secret: ''key'', cookie: { maxAge: 60000 } }))", "percentage": 89}]'::jsonb, 'Express.js server, Passport.js with Facebook strategy, EJS or view engine configured', 'Response sent to client immediately after authentication, loading message displays before processing completes', 'Forgetting res.end(html) in callback, misconfigured session middleware, rendering without explicit response', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/23546049/handle-server-timeout-in-passportjs', 'admin:1764191461'),

('Remix Ethereum IDE external HTTP provider connection error - HTTPS only requirement', 'general', 'MEDIUM', '[{"solution": "Set up HTTPS proxy using Nginx to forward traffic to localhost HTTP endpoint, Remix requires HTTPS URIs", "percentage": 95}, {"solution": "Obtain SSL certificate and configure reverse proxy on cloud server with HTTPS listener forwarding to HTTP backend", "percentage": 93}]'::jsonb, 'Ethereum node running on cloud server, Remix IDE open in browser, domain name registered (optional)', 'Remix IDE connects successfully to external node, Web3 calls execute without connection errors', 'Using HTTP URI when Remix requires HTTPS, forgetting to configure reverse proxy, not enabling CORS headers on blockchain node', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/77544342/unable-to-connect-to-the-test-node-by-using-external-http-provider-in-remix', 'admin:1764191461'),

('Svelte dev server ECONNREFUSED - cannot connect to local development server', 'general', 'MEDIUM', '[{"solution": "Ensure Svelte dev server is running on correct port before client tries to connect", "percentage": 97}, {"solution": "Verify firewall allows local connections, check netstat to confirm server listening on expected address:port", "percentage": 91}]'::jsonb, 'Svelte project initialized, dev server build tools configured, Node.js/npm installed', 'Svelte dev server starts without connection errors, hot module replacement works correctly, page loads in browser', 'Starting client before server starts listening, firewall blocking localhost connections, using wrong port number', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/tagged/svelte', 'admin:1764191461');
