-- GitHub Actions Troubleshooting - Official Docs Mining
-- Source: docs.github.com/en/actions/how-tos/troubleshoot-workflows
-- Mined: 2025-11-25

INSERT INTO knowledge_entries (
    query, category, hit_frequency, solutions, prerequisites, success_indicators,
    common_pitfalls, success_rate, claude_version, last_verified, source_url
) VALUES (
    'Workflow not executing when expected - trigger conditions not met',
    'github-actions',
    'HIGH',
    $$[{"solution": "1. Review the on: field configuration to verify trigger conditions\n2. Check if triggering event only runs from default branch\n3. Verify scheduled jobs are not scheduled during peak hours (top of hour)\n4. Check commit messages for skip annotations (e.g., [skip ci])\n5. Verify branch/tag/path filters match actual changes", "percentage": 85, "note": "Most common cause is misconfigured on: field"}]$$::jsonb,
    'Access to workflow file in .github/workflows/ directory',
    'Workflow runs appear in Actions tab with expected trigger event',
    'Forgetting that some events only trigger from default branch; scheduling at :00 when system is under high load',
    0.85,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/how-tos/troubleshoot-workflows'
),
(
    'Workflow will not run on pull_request activity due to merge conflict',
    'github-actions',
    'MEDIUM',
    $$[{"solution": "1. Identify the merge conflict in the pull request\n2. Resolve the merge conflict locally\n3. Push the resolved changes to the branch\n4. Workflow will automatically trigger once merge conflicts are resolved", "percentage": 95, "note": "Automatic trigger after conflict resolution"}]$$::jsonb,
    'Pull request with merge conflicts',
    'Workflow appears in PR checks after conflict resolution',
    'Attempting to run workflow without resolving conflicts first',
    0.95,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/how-tos/troubleshoot-workflows'
),
(
    'Cannot cancel running workflow - conditional statement blocks cancellation',
    'github-actions',
    'MEDIUM',
    $$[{"solution": "1. Identify jobs using always() status check function\n2. Replace always() with !cancelled() conditional expression\n3. Test cancellation via GitHub UI or API\n4. If still fails, use force-cancel API endpoint as last resort", "percentage": 90, "note": "Replace always() which returns true even during cancellation"}]$$::jsonb,
    'Running workflow with jobs using conditional statements',
    'Workflow can be cancelled successfully via UI or API',
    'Using always() instead of !cancelled() in job conditionals',
    0.90,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/how-tos/troubleshoot-workflows'
),
(
    'Workflow YAML syntax error - cannot use both branches and branches-ignore',
    'github-actions',
    'HIGH',
    $$[{"solution": "1. Review on: push: or on: pull_request: configuration\n2. Remove conflicting filter - choose either branches OR branches-ignore\n3. Apply same rule to tags and paths filters\n4. Validate YAML syntax before committing", "percentage": 100, "note": "Mutually exclusive filters - exactly one must be used"}]$$::jsonb,
    'Workflow file in .github/workflows/ directory',
    'Workflow syntax validation passes; workflow appears in Actions tab',
    'Mixing branches and branches-ignore, tags and tags-ignore, or paths and paths-ignore',
    1.0,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions'
),
(
    'Workflow_call input missing type parameter - required field validation error',
    'github-actions',
    'MEDIUM',
    $$[{"solution": "1. Locate on: workflow_call: inputs: section\n2. Add type: parameter to each input (required)\n3. Valid types: string, number, boolean\n4. Example: inputs:\\n  environment:\\n    type: string\\n    required: true", "percentage": 100, "note": "Type parameter is mandatory for all workflow_call inputs"}]$$::jsonb,
    'Reusable workflow file with workflow_call trigger',
    'Workflow can be called from other workflows without validation errors',
    'Omitting type parameter in workflow_call inputs',
    1.0,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions'
),
(
    'Path filter evaluation limited to first 300 files - workflow skips if limit exceeded',
    'github-actions',
    'LOW',
    $$[{"solution": "1. Check how many files changed in commit (Developer Console or git diff)\n2. If >300 files changed, workflow execution is skipped for path filtering\n3. Split large changes into smaller commits with fewer files\n4. Alternatively, remove path filtering if not essential", "percentage": 75, "note": "Only applies when using paths or paths-ignore filters"}]$$::jsonb,
    'Workflow using paths or paths-ignore filters',
    'Workflow executes for commits with <300 files changed',
    'Large commits with >300 files that should match path filters',
    0.75,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions'
),
(
    'Runner label configuration matches preset GitHub labels instead of custom labels',
    'github-actions',
    'MEDIUM',
    $$[{"solution": "1. For self-hosted runners, use unique label names\n2. Avoid label names matching preset GitHub-hosted runner labels (ubuntu-latest, windows-latest, macos-latest)\n3. Example good labels: custom-ubuntu, internal-runner, team-ci\n4. Verify runner labels in settings vs runs-on: configuration", "percentage": 88, "note": "Prevents ambiguous runner matching"}]$$::jsonb,
    'Self-hosted runners configured with labels',
    'Jobs consistently assign to intended runners without ambiguity',
    'Using generic labels (test, build) that may match GitHub-hosted runners',
    0.88,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/how-tos/troubleshoot-workflows'
),
(
    'Secrets not accessible in workflow - triggered from forked repository',
    'github-actions',
    'HIGH',
    $$[{"solution": "1. Understand that secrets are not passed to workflows triggered from forks (except GITHUB_TOKEN)\n2. For pull requests from forks, require maintainer approval via Approve workflows to run\n3. GITHUB_TOKEN has read-only permissions in fork contexts\n4. Use GitHub Environments to control secret access by branch", "percentage": 90, "note": "GITHUB_TOKEN is always available but with limited permissions"}]$$::jsonb,
    'Repository secrets configured; workflow triggered from fork',
    'Workflow completes with GITHUB_TOKEN access; secrets absent as expected',
    'Assuming secrets available in fork pull requests without approval',
    0.90,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions'
),
(
    'Secrets exceed 48 KB limit - GPG encryption workaround with masking caveat',
    'github-actions',
    'LOW',
    $$[{"solution": "1. For secrets >48 KB, use GPG encryption as workaround\n2. CRITICAL: GitHub does not redact encrypted secrets from logs\n3. If using GPG encryption, ensure encrypted value is NOT printed to logs\n4. Test workflow output to confirm sensitive data not exposed\n5. Consider splitting large secrets into smaller pieces instead", "percentage": 70, "note": "High risk - manual masking required"}]$$::jsonb,
    'Secret value exceeds 48 KB; GPG installed',
    'Encrypted secret decrypts correctly; sensitive output properly masked',
    'Printing large encrypted secrets to logs; assuming automatic redaction',
    0.70,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions'
),
(
    'Self-hosted runner offline - cannot connect to GitHub',
    'github-actions',
    'HIGH',
    $$[{"solution": "1. Verify runner machine is powered on and accessible\n2. Check if runner application is running (status: systemctl status / svc.sh status)\n3. Run ./config.sh --check --url REPO-URL --pat TOKEN to diagnose connectivity\n4. Review _diag/Runner_* logs for detailed error messages\n5. For TLS issues, verify GitHub certificate installation (not production-safe: GITHUB_ACTIONS_RUNNER_TLS_NO_VERIFY=1)", "percentage": 85, "note": "Check machine, process, and network connectivity in order"}]$$::jsonb,
    'Self-hosted runner configured and registered',
    'Runner shows Idle or Active status in GitHub; --check returns PASS',
    'Assuming GitHub connectivity without running diagnostic check',
    0.85,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/monitoring-and-troubleshooting-self-hosted-runners'
),
(
    'Docker error: File not found or permission denied on self-hosted runner',
    'github-actions',
    'MEDIUM',
    $$[{"solution": "1. Verify Docker is installed: docker --version\n2. If error File not found: docker: Install Docker CLI\n3. If error connect: permission denied: Add runner service account to docker group (sudo usermod -aG docker runner-user)\n4. If runner installed via snap: Use native Docker instead (snap wrapper causes issues)\n5. Verify Docker daemon is running: sudo systemctl status docker", "percentage": 88, "note": "Snap-installed Docker often causes shell wrapper issues"}]$$::jsonb,
    'Self-hosted runner with Docker job step',
    'Docker commands execute successfully without permission or file errors',
    'Using snap-installed Docker; not granting docker group permissions to runner account',
    0.88,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/monitoring-and-troubleshooting-self-hosted-runners'
),
(
    'Input required and not supplied error - Docker shell wrapper instead of binary',
    'github-actions',
    'LOW',
    $$[{"solution": "1. Error: Error: Input required and not supplied: [parameter]\n2. Root cause: Docker installed via snap creates shell wrapper, not binary executable\n3. Solution: Uninstall snap Docker and install native Docker package\n4. Verify: which docker returns /usr/bin/docker, not snap path\n5. Test: docker run hello-world confirms proper binary execution", "percentage": 92, "note": "Snap wrapper interferes with input parameter passing"}]$$::jsonb,
    'Self-hosted runner with snap-installed Docker',
    'Docker steps execute without input parameter errors',
    'Failing to detect snap wrapper issue; reinstalling Docker without removing snap',
    0.92,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/monitoring-and-troubleshooting-self-hosted-runners'
),
(
    'Insufficient permissions - cannot create secrets or variables on repository',
    'github-actions',
    'MEDIUM',
    $$[{"solution": "1. For repository secrets: User must have write access to repository\n2. For personal repos: Repository owner must create secrets\n3. For organization repos: Must have write access; collaborators can only use REST API\n4. For organization-level secrets: Requires admin:org scope\n5. Check GitHub settings > Secrets and variables > Actions for current access level", "percentage": 95, "note": "Different rules for personal repos vs organization repos"}]$$::jsonb,
    'GitHub user account with repository collaboration',
    'Can create/edit secrets in repository settings without permission denied errors',
    'Assuming collaborator can create secrets; attempting to create org-level secrets without admin scope',
    0.95,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions'
),
(
    'Organization-level secrets not accessible by private repositories on GitHub Free plan',
    'github-actions',
    'MEDIUM',
    $$[{"solution": "1. Verify repository plan: GitHub Free does not support org-level secrets for private repos\n2. Upgrade to GitHub Team or Enterprise plan\n3. OR use repository-level secrets instead of organization-level\n4. OR use personal repositories on Free plan (org secrets work)\n5. Check organization billing settings to confirm current plan", "percentage": 85, "note": "Plan-dependent feature; workaround available with repo-level secrets"}]$$::jsonb,
    'Organization with private repository on GitHub Free plan',
    'Secrets accessible to workflow (either via upgraded plan or repo-level secrets)',
    'Assuming org secrets work on Free plan; not reading plan limitations',
    0.85,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions'
),
(
    'Workflow approval expires after 30 days - pending approval workflow auto-deleted',
    'github-actions',
    'LOW',
    $$[{"solution": "1. Check pull request creation date vs current date (30 day threshold)\n2. If >30 days old: Pull request workflow is automatically deleted from queue\n3. No action needed - workflow will need to be re-triggered on updated PR\n4. To avoid expiry: Approve/reject workflows promptly after PR creation\n5. Maintainers can expedite by reviewing and approving pending workflows", "percentage": 100, "note": "Automatic cleanup; no manual intervention available"}]$$::jsonb,
    'Pull request from external contributor with pending approval',
    'Workflow executes after maintainer approval within 30 days',
    'Delaying approval >30 days; assuming workflow persists indefinitely',
    1.0,
    'sonnet-4',
    NOW(),
    'https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks'
);
