-- Python Null/None Error Mining
-- Mined from Stack Overflow on 2025-11-26

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

-- 1. FastAPI NoneType attribute error
('AttributeError: ''NoneType'' object has no attribute ''send'' FastAPI AsyncClient test', 'python', 'HIGH', '[{"solution": "Create conftest.py with event_loop fixture scoped to ''session'' and asyncio default fixture loop scope set to ''function''. This ensures AsyncClient is properly initialized for each test without NoneType errors.", "percentage": 95}, {"solution": "Override the async event_loop fixture explicitly in conftest.py with asyncio.new_event_loop() and add pytest.ini with asyncio_default_fixture_loop_scope = function", "percentage": 85}]'::jsonb, 'pytest, pytest-asyncio, httpx with AsyncClient, SQLModel or SQLAlchemy', 'Second and subsequent test runs pass without AttributeError, AsyncClient.send() returns valid response object', 'Reusing event_loop across tests without proper cleanup, not setting fixture scope to ''function'', mixing TestClient with AsyncClient', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/79191599/fastapi-unit-testing-attributeerror-nonetype-object-has-no-attribute-send', 'admin:1764192014'),

-- 2. FastAPI NoneType append error
('AttributeError: ''NoneType'' object has no attribute ''append'' FastAPI SQLAlchemy relationship', 'python', 'HIGH', '[{"solution": "database.fetch_one() returns a Row object, not an ORM model instance with relationship methods. Use proper ORM session.query() or async session to load model with relationships enabled, then use model.relationship_name.append()", "percentage": 95}, {"solution": "When using raw database queries, manually construct relationships instead of relying on ORM relationship attributes. Fetch related objects separately and create the association in the join table directly.", "percentage": 80}]'::jsonb, 'FastAPI, SQLAlchemy, SQLModel, async database queries, understanding of ORM vs raw database queries', 'Successfully append objects to relationship without NoneType error, correct association created in database join table', 'Confusing database.fetch_one() Row objects with ORM model instances, expecting ORM relationship methods on raw query results, not loading relationships explicitly in async context', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/74313495/nonetype-object-has-no-attribute-append-fastapi-sqlalchemy-many-to-man', 'admin:1764192014'),

-- 3. Flask variable undefined error
('UnboundLocalError: local variable ''account'' referenced before assignment Flask template', 'python', 'HIGH', '[{"solution": "Pass variable to render_template() explicitly: return render_template(''profile.html'', account=account). Also ensure POST handler returns render_template() instead of only GET handler.", "percentage": 96}, {"solution": "Initialize account variable before conditional blocks: account = None at function start, then update in conditionals. This ensures variable always exists when template renders.", "percentage": 88}]'::jsonb, 'Flask, Jinja2 templates, understanding template variable passing, MySQL cursor operations', 'Template renders without UnboundLocalError, displays account data correctly, both GET and POST requests handled', 'Forgetting to pass variables to render_template(), only handling one HTTP method, variable scope misunderstanding, using uninitialized variables in templates', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/62220241/variable-is-undefined-flask-mysql', 'admin:1764192014'),

-- 4. Flask request undefined values
('undefined values or empty result b''undefined='' Flask AJAX array POST request', 'python', 'MEDIUM', '[{"solution": "Send JavaScript data as JSON with JSON.stringify() and contentType: ''application/json''. Access in Flask with request.json instead of request.form. JavaScript: data: JSON.stringify(test), contentType: ''application/json''. Python: result = request.json", "percentage": 96}, {"solution": "If form data needed, send as URLEncoded or multipart/form-data with proper field names. Do not send raw arrays without field names or content-type headers.", "percentage": 78}]'::jsonb, 'Flask, jQuery/AJAX, JSON serialization, understanding request.form vs request.json, content-type headers', 'AJAX request receives proper Flask response, data is correctly parsed, console shows clean response object not ''undefined'' string', 'Not using JSON.stringify() for complex data types, missing contentType header, sending arrays without field names, trying to access JSON data with request.form, not using request.json', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/54751985/python-flask-request-returns-undefined-values', 'admin:1764192014');
