-- Flutter Common Errors - Official Docs Mining
-- Source: docs.flutter.dev/testing/common-errors
-- Mined: 2025-11-25

INSERT INTO knowledge_entries (
    query, category, hit_frequency, solutions, prerequisites, success_indicators,
    common_pitfalls, success_rate, claude_version, last_verified, source_url
) VALUES (
    'Flutter error: A RenderFlex overflowed by X pixels',
    'flutter',
    'CRITICAL',
    $$[{"solution": "Wrap the overflowing child widget in an Expanded or Flexible widget to constrain its size within the Column or Row", "percentage": 95, "note": "Use Expanded for equal distribution or Flexible with flex property for custom ratios"}]$$::jsonb,
    'Flutter project with Column or Row layout',
    'Yellow and black striped overflow indicator disappears, widget displays correctly within bounds',
    'Forgetting to use Expanded for children in Row/Column, using fixed widths without considering parent constraints',
    0.95,
    'sonnet-4',
    NOW(),
    'https://docs.flutter.dev/testing/common-errors'
),
(
    'Flutter error: Vertical Viewport given unbounded height',
    'flutter',
    'CRITICAL',
    $$[{"solution": "Wrap ListView with Expanded widget to specify available height, or use SizedBox with explicit height", "percentage": 92, "note": "Expanded is preferred as it adapts to parent constraints"}]$$::jsonb,
    'Flutter ListView inside Column layout',
    'ListView renders without error, content scrolls properly, no height constraint violations',
    'Using ListView directly inside Column without constraints, assuming ListView handles its own height',
    0.92,
    'sonnet-4',
    NOW(),
    'https://docs.flutter.dev/testing/common-errors'
),
(
    'Flutter error: InputDecorator cannot have unbounded width',
    'flutter',
    'HIGH',
    $$[{"solution": "Wrap TextField with Expanded widget for flexible width, or SizedBox for fixed width constraints", "percentage": 90, "note": "Use Expanded inside Row to share available space proportionally"}]$$::jsonb,
    'Flutter TextField inside Row or unbounded horizontal layout',
    'TextField renders with proper width constraints, no error in console',
    'Placing TextField directly in Row without width wrapper, using fixed widths on parent Row',
    0.90,
    'sonnet-4',
    NOW(),
    'https://docs.flutter.dev/testing/common-errors'
),
(
    'Flutter error: setState called during build',
    'flutter',
    'CRITICAL',
    $$[{"solution": "Move setState() or showDialog() calls out of build() method. Trigger them from user interactions like button presses instead", "percentage": 93, "note": "Use callbacks in initState() or event handlers to manage state changes"}]$$::jsonb,
    'Stateful Flutter widget with setState in build method',
    'No setState during build error, dialog or navigation triggers correctly on user action',
    'Calling showDialog() in build(), triggering state changes synchronously during render',
    0.93,
    'sonnet-4',
    NOW(),
    'https://docs.flutter.dev/testing/common-errors'
),
(
    'Flutter error: RenderBox was not laid out',
    'flutter',
    'HIGH',
    $$[{"solution": "Check and fix primary constraint-related errors first. Use Flutter Inspector to trace layout violations and identify root cause", "percentage": 85, "note": "This is often a secondary error from RenderFlex or viewport constraints"}]$$::jsonb,
    'Flutter project with layout errors, Flutter Inspector available',
    'Primary constraint errors resolved, RenderBox error disappears',
    'Treating as primary error without addressing constraint violations, ignoring Inspector diagnostics',
    0.85,
    'sonnet-4',
    NOW(),
    'https://docs.flutter.dev/testing/common-errors'
),
(
    'Flutter error: Incorrect use of ParentData widget',
    'flutter',
    'MEDIUM',
    $$[{"solution": "Ensure Positioned is in Stack, Flexible in Row/Column, TableCell in TableRow. Move widget to correct parent container", "percentage": 88, "note": "Check widget documentation for required parent types"}]$$::jsonb,
    'Flutter layout using Positioned, Flexible, or TableCell widgets',
    'Widget renders in correct parent container without ParentData errors',
    'Using ParentData widgets outside required parents, mismatching widget hierarchies',
    0.88,
    'sonnet-4',
    NOW(),
    'https://docs.flutter.dev/testing/common-errors'
),
(
    'Flutter error: Null check operator on null value',
    'flutter',
    'CRITICAL',
    $$[{"solution": "Add null checks before accessing properties. Use null-coalescing operator (??) or conditional access (?.) to handle nullable values", "percentage": 91, "note": "Enable null safety in pubspec.yaml and use type-safe patterns"}]$$::jsonb,
    'Flutter project with null safety enabled, nullable variables',
    'No null check errors at runtime, null values handled gracefully',
    'Assuming variables are non-null without checks, ignoring null safety warnings',
    0.91,
    'sonnet-4',
    NOW(),
    'https://docs.flutter.dev/testing/common-errors'
),
(
    'Flutter error: The method was called on null',
    'flutter',
    'CRITICAL',
    $$[{"solution": "Check for null before calling methods. Initialize objects before use, use null-safe navigation operators (?.), or provide default values", "percentage": 89, "note": "Use late keyword carefully and ensure initialization before access"}]$$::jsonb,
    'Flutter code with method calls on potentially null objects',
    'Methods execute without null errors, proper initialization verified',
    'Calling methods without null initialization, ignoring late keyword constraints',
    0.89,
    'sonnet-4',
    NOW(),
    'https://docs.flutter.dev/testing/common-errors'
),
(
    'Flutter error: Widget test failures and assertion errors',
    'flutter',
    'HIGH',
    $$[{"solution": "Use find.byType(), find.byIcon(), find.text() to locate widgets. Use pumpWidget() or pump(Duration) to rebuild. Verify async operations complete with pumpAndSettle()", "percentage": 87, "note": "Check widget tree with WidgetTester.allWidgets for debugging"}]$$::jsonb,
    'Flutter project with widget tests, testWidgets() setup',
    'All widget tests pass, assertions succeed, async operations complete',
    'Not pumping widget after state changes, missing await on async operations, wrong finder patterns',
    0.87,
    'sonnet-4',
    NOW(),
    'https://docs.flutter.dev/testing/common-errors'
),
(
    'Flutter error: Hot reload issues and state persistence',
    'flutter',
    'MEDIUM',
    $$[{"solution": "Clear hot reload cache, restart app with hot restart, verify hot reload restrictions (avoid static variables, const constructors). Check for missing Provider refresh", "percentage": 84, "note": "Some code changes require full restart instead of reload"}]$$::jsonb,
    'Flutter app with hot reload enabled, development environment',
    'Hot reload updates UI correctly, state changes reflect properly',
    'Expecting all changes to hot reload, using static variables with hot reload, ignoring Provider rebuild',
    0.84,
    'sonnet-4',
    NOW(),
    'https://docs.flutter.dev/testing/common-errors'
),
(
    'Flutter error: MissingPluginException for platform channels',
    'flutter',
    'HIGH',
    $$[{"solution": "Run flutter pub get, flutter pub upgrade, then flutter clean and flutter run. Ensure native platform code is compiled with correct channel names", "percentage": 86, "note": "Verify method channel names match exactly between Dart and native code"}]$$::jsonb,
    'Flutter project with platform channels, native plugins',
    'Platform channel calls execute without MissingPluginException',
    'Not running pub get after adding dependencies, mismatched channel names, incomplete native implementation',
    0.86,
    'sonnet-4',
    NOW(),
    'https://docs.flutter.dev/testing/common-errors'
),
(
    'Flutter error: Unhandled Exception type X is not a subtype',
    'flutter',
    'MEDIUM',
    $$[{"solution": "Add explicit type casting, verify generic types match expected types. Use as casting or type guards before operations", "percentage": 82, "note": "Enable strong mode in analysis_options.yaml for better type checking"}]$$::jsonb,
    'Flutter Dart code with type mismatches, generic types',
    'Type casting operations succeed, no subtype exceptions',
    'Assuming generic type compatibility, missing explicit casts, ignoring analyzer warnings',
    0.82,
    'sonnet-4',
    NOW(),
    'https://docs.flutter.dev/testing/common-errors'
),
(
    'Flutter error: NoSuchMethodError in dynamic calls',
    'flutter',
    'HIGH',
    $$[{"solution": "Check method names for typos, verify objects have the method before calling. Use type annotations instead of dynamic when possible", "percentage": 85, "note": "Enable lint rules to catch missing methods during development"}]$$::jsonb,
    'Flutter Dart code with dynamic variables or reflection',
    'Method calls execute successfully, no NoSuchMethodError',
    'Using dynamic types without validation, typos in method names, missing method implementations',
    0.85,
    'sonnet-4',
    NOW(),
    'https://docs.flutter.dev/testing/common-errors'
),
(
    'Flutter error: Platform channel exception handler timeout',
    'flutter',
    'MEDIUM',
    $$[{"solution": "Increase timeout duration in platform channel calls, add error handlers, verify native code completes operations. Check for deadlocks in native code", "percentage": 80, "note": "Use Future.timeout() to prevent indefinite hangs"}]$$::jsonb,
    'Flutter platform channels with native operations, async handlers',
    'Platform channel operations complete within timeout, native methods respond',
    'Not handling timeouts, missing error callbacks, blocking operations in native code',
    0.80,
    'sonnet-4',
    NOW(),
    'https://docs.flutter.dev/testing/common-errors'
);
