-- Angular Other errors - Mining batch 20251126
-- 10 entries for clauderepo knowledge base

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ReferenceError: $ is not defined in Angular 6 with jQuery', 'angular', 'HIGH', '[{"solution": "Create typings.d.ts file with: declare var $: any; declare var jQuery: any;", "percentage": 95}, {"solution": "Use npm import: import * as $ from \"jquery\"; in app.module.ts", "percentage": 85}]'::jsonb, 'jQuery installed via npm, angular.json scripts configured', 'jQuery functions work without console errors', 'Importing jQuery in component instead of globally, not declaring types', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/50793325/angular-6-referenceerror-is-not-defined-error-with-jquery', 'admin:1764191422'),

('ERROR ReferenceError: document is not defined in Angular Universal SSR', 'angular', 'HIGH', '[{"solution": "Import DOCUMENT from @angular/common and use @Inject(DOCUMENT) in service constructor", "percentage": 97}, {"solution": "Use domino library to create global window object before accessing document", "percentage": 88}]'::jsonb, 'Angular Universal setup, SSR enabled, service using document', 'SSR build succeeds without document reference errors', 'Accessing document directly without injection, not importing DOCUMENT token', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/60636286/angular-9-ssr-build-serve-eror-error-referenceerror-document-is-not-defined', 'admin:1764191422'),

('ReferenceError: bootstrap is not defined in Angular 10', 'angular', 'MEDIUM', '[{"solution": "Declare bootstrap variable globally: declare var bootstrap: any;", "percentage": 93}, {"solution": "Import Bootstrap CSS and JS properly in angular.json scripts array", "percentage": 82}]'::jsonb, 'Bootstrap installed, TypeScript strict mode enabled', 'Bootstrap components initialize without reference errors', 'Not declaring bootstrap as global, importing CSS without JS bundle', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/78572435/in-angular-error-referenceerror-bootstrap-is-not-defined', 'admin:1764191422'),

('error TS1206: Decorators are not valid here in Angular 2', 'angular', 'HIGH', '[{"solution": "Place @Component decorator directly before export class keyword", "percentage": 98}, {"solution": "Define routes before @NgModule decorator, not after", "percentage": 89}]'::jsonb, 'Component, Module, or Directive using decorators, TypeScript 2.2+', 'No TS1206 compilation errors, decorators recognized', 'Placing code between decorator and class definition, decorator order issues', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/38357384/ts1206-decorators-are-not-valid-here-angular-2', 'admin:1764191422'),

('Decorators are not valid here ts(1206) with @Inject in Angular 17', 'angular', 'MEDIUM', '[{"solution": "Use inject() function instead of @Inject decorator in constructor: document: Document = inject(DOCUMENT);", "percentage": 96}, {"solution": "Ensure @Injectable() decorator is present on service class", "percentage": 85}]'::jsonb, 'Angular 15+, @angular/core package, service with constructor injection', 'No TypeScript decorator warnings, code compiles successfully', 'Mixing @Inject with constructor parameters, missing @Injectable decorator', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/77940160/angular-decorators-are-not-valid-here-ts1206', 'admin:1764191422'),

('ERROR NG2007: Class is using Angular features but is not decorated', 'angular', 'HIGH', '[{"solution": "Add @Component({ template: '''' }) to base class and mark as abstract", "percentage": 97}, {"solution": "Use @Injectable() decorator on abstract base class for Angular 10+", "percentage": 90}]'::jsonb, 'Base component with @Input properties, Angular 9+, inheritance pattern', '@Input() properties recognized, child components compile without errors', 'Forgetting decorator on base class, not marking base as abstract', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/63126067/class-is-using-angular-features-but-is-not-decorated-please-add-an-explicit-ang', 'admin:1764191422'),

('Class is using Angular features but is not decorated in Angular 15', 'angular', 'MEDIUM', '[{"solution": "Disable Angular Language Service extension in VS Code if only showing warning", "percentage": 87}, {"solution": "Ensure class properly uses @Component or @Injectable decorator", "percentage": 92}]'::jsonb, 'Angular 15 component, VS Code with extensions', 'Component renders correctly, no runtime errors despite warning', 'Not checking if warning is from extension, missing actual decorator', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/76286385/angular-how-to-resolve-class-is-using-angular-features-but-is-not-decorated-p', 'admin:1764191422'),

('error TS7053: Element implicitly has any type in property decorator', 'angular', 'MEDIUM', '[{"solution": "Type target as Record<string, any>: (target: Record<string, any>) => target[key]", "percentage": 94}, {"solution": "Use type assertion: let val = (<any>target)[key];", "percentage": 88}]'::jsonb, 'Custom property decorator, TypeScript strict mode', 'Decorator applies property getter/setter without type errors', 'Using bare Object type for target, not casting index type', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/71022432/i-am-tryin-to-create-a-method-decorator-in-angular-but-this-error-shows-up', 'admin:1764191422'),

('Method decorator unable to catch errors in Observable subscribe', 'angular', 'MEDIUM', '[{"solution": "Pipe Observable through catchError operator instead of relying on try-catch", "percentage": 93}, {"solution": "Handle subscription errors using error callback and custom error handler", "percentage": 84}]'::jsonb, 'Method decorator on component methods, Observable usage, error handling', 'All errors from methods and subscriptions logged consistently', 'Not subscribing to Observable pipeline in decorator, missing pipe operators', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/69176991/angular-method-decorator-error-handling-with-subscriptions', 'admin:1764191422'),

('error TS1206 in @NgModule RouterModule decorator Angular 6', 'angular', 'MEDIUM', '[{"solution": "Place closing brace and export class statement immediately after @NgModule decorator", "percentage": 97}, {"solution": "Verify no code between decorator closing brace and class declaration", "percentage": 94}]'::jsonb, 'Angular 6+ @NgModule decorator, RouterModule import', 'Module compiles without TS1206 errors, routing works', 'Extra code between decorator and export statement, line break issues', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/50671474/ts1206-decorators-are-not-valid-here-angular-6-tutorial-example/53713182', 'admin:1764191422');
