-- Angular Memory Errors Mining (2025-11-26)
-- 10 Common Angular Memory Leak Issues

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Angular 12 memory leak when compiling application - memory usage steadily increasing with each recompile until CLI crashes over 4000MB', 'angular', 'HIGH', '[{"solution": "Upgrade Angular CLI to latest version with bug fixes for memory leak during compilation", "percentage": 90}, {"solution": "Remove unused NPM modules that may be causing the leak during build process", "percentage": 75}, {"solution": "Increase available memory allocation for ng serve command", "percentage": 60}]'::jsonb, 'Angular 12 or higher installed, npm modules present', 'Memory usage stabilizes during recompilation, no CLI crashes after ~5 recompiles', 'Assuming memory issue is always in user code rather than Angular CLI itself', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/67737668/memory-leak-when-compiling-angular-12-application', 'admin:1764191717');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Angular 17 SSR memory leak - HTMLBaseElement and R3Injector still referenced after component destruction causing increased heap', 'angular', 'HIGH', '[{"solution": "Ensure all observables are properly unsubscribed in ngOnDestroy using takeUntil pattern", "percentage": 85}, {"solution": "Check for setTimeout/setInterval that are not cleared on component destruction", "percentage": 80}, {"solution": "Verify no circular imports between components and services", "percentage": 70}, {"solution": "Use divide and conquer approach to isolate leaking component one by one", "percentage": 75}]'::jsonb, 'Angular 17 with SSR setup, zone.js configured', 'Memory profiler shows CSS and DOM elements properly garbage collected, R3Injector no longer retained', 'Not checking for timer functions like setTimeout/setInterval in ngOnChanges or ngDoCheck lifecycle hooks', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/78957733/how-to-find-where-my-memory-leak-is-in-angular-17-ssr', 'admin:1764191717');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Observable subscription not unsubscribed in component - memory leak from continued observable emissions after component navigation away', 'angular', 'CRITICAL', '[{"solution": "Implement OnDestroy lifecycle hook and call unsubscribe() on subscription in ngOnDestroy", "percentage": 95}, {"solution": "Use async pipe in template instead of manual subscription", "percentage": 90}, {"solution": "Use takeUntil operator with Subject to auto-unsubscribe when component destroys", "percentage": 92}]'::jsonb, 'RxJS subscription present in component, Angular 2+', 'Console no longer shows emissions from subscribed observables after component navigation', 'Forgetting to implement OnDestroy interface or calling unsubscribe incorrectly', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/39011677/memory-leaks-in-angular2', 'admin:1764191717');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Angular component not garbage collected by browser - shallow size small but retained size large with DOM nodes kept in memory', 'angular', 'HIGH', '[{"solution": "Use Chrome DevTools Memory Inspector to check retained vs shallow size and identify references", "percentage": 88}, {"solution": "Verify display: flex CSS property is not causing retention issues in specific browser versions", "percentage": 65}, {"solution": "Test in production mode build as memory leak may not reproduce in dev mode", "percentage": 80}]'::jsonb, 'Chrome DevTools with memory inspector access, Angular 11-13', 'DOM nodes properly released after component destruction, retained size matches expected component size', 'Testing only in development mode where Angular retains additional debug information', 0.78, 'haiku', NOW(), 'https://stackoverflow.com/questions/71026959/memory-leak-garbage-collection-in-browser-not-collecting-components', 'admin:1764191717');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Angular subscription flashing old values - multiple subscription updates causing incorrect data display when switching currencies', 'angular', 'HIGH', '[{"solution": "Use first() operator to retrieve value once instead of continuous updates from observable", "percentage": 85}, {"solution": "Add unsubscribe in ngOnDestroy to prevent subscription continuation after component destroyed", "percentage": 90}, {"solution": "Use debounceTime or throttleTime to limit update frequency", "percentage": 80}]'::jsonb, 'Angular component with observable subscription, RxJS library', 'Latest exchange rate displayed without flashing previous values, no crashes on rapid currency switches', 'Subscribing to observables in getter methods which causes multiple subscriptions', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/50220562/angular-memory-leaking-and-subscription-not-working-properly', 'admin:1764191717');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Angular Renderer2 event listeners retained in memory after removal - removeListener leaves DebugElement references in dev mode', 'angular', 'MEDIUM', '[{"solution": "Verify listeners are properly removed using Renderer2.listen() return function in removeListeners method", "percentage": 90}, {"solution": "Test in production mode build where DebugElement references are not retained", "percentage": 75}, {"solution": "Ensure all listener unlistening calls are executed in correct order", "percentage": 85}]'::jsonb, 'Angular 6+, Renderer2 event listeners', 'No additional event listeners retained in memory after toggle add/remove cycles', 'Not realizing dev mode retains DebugElement references which disappear in production mode', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/53081668/angular-renderer2-remove-listener-leaves-eventlisteners-in-memory-memory-leak', 'admin:1764191717');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Node.js EventEmitter memory leak detected - 11 listeners added warning indicating uncontrolled listener accumulation', 'angular', 'MEDIUM', '[{"solution": "Find and fix code adding listeners in loops instead of outside loops", "percentage": 95}, {"solution": "Verify listener is only added once during initialization not in recurring function", "percentage": 92}, {"solution": "Only increase maxListeners after confirming design intentionally uses many listeners", "percentage": 60}]'::jsonb, 'Node.js EventEmitter usage in Angular server environment', 'No EventEmitter memory leak warning in console output', 'Increasing maxListeners limit without fixing underlying code bug causing multiple listener additions', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/9768444/possible-eventemitter-memory-leak-detected', 'admin:1764191717');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Angular Material DOM nodes not released - Performance monitor shows DOM nodes and event listeners constantly increasing on route switch', 'angular', 'HIGH', '[{"solution": "Check for cached DOM references in Material component libraries", "percentage": 82}, {"solution": "Verify Material components properly clean up overlay containers on destroy", "percentage": 80}, {"solution": "Upgrade Angular Material to latest version with memory leak fixes", "percentage": 85}, {"solution": "Disable browser extensions and use Chrome incognito for accurate memory testing", "percentage": 70}]'::jsonb, 'Angular Material 11+, Chrome DevTools Performance monitor', 'DOM nodes and event listeners count stable after garbage collection across route switches', 'Running tests with Chrome extensions enabled which can retain DOM references', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/66498365/angular-material-not-releasing-dom-nodes-js-event-listeners', 'admin:1764191717');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Angular HTTP request subscription memory leak with polling - poll observable not unsubscribed causing continuous memory growth', 'angular', 'HIGH', '[{"solution": "Implement OnDestroy and unsubscribe from poll subscription in ngOnDestroy method", "percentage": 95}, {"solution": "Use takeUntil operator with Subject in the Observable pipe chain", "percentage": 93}, {"solution": "Use async pipe in template instead of manual subscribe in component", "percentage": 90}]'::jsonb, 'Angular HTTP polling setup, RxJS repeat and mergeMap operators', 'Memory usage stable during long polling operations, no continuous growth over time', 'Forgetting to type subscription variable as Subscription type or missing OnDestroy implementation', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/76604533/angular-memory-leak-need-to-know-how-to-solve-leak', 'admin:1764191717');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Angular preventing memory leaks best practices - unsubscription from services not implemented in component lifecycle', 'angular', 'CRITICAL', '[{"solution": "Use async pipe in template with observables instead of manual subscription", "percentage": 90}, {"solution": "Implement takeUntil pattern with destroy Subject in ngOnDestroy", "percentage": 92}, {"solution": "Use lazy loading modules to prevent accumulation of component instances in memory", "percentage": 85}, {"solution": "Use state management Redux/NgRx to avoid repeating same service calls in multiple components", "percentage": 80}]'::jsonb, 'Angular application with observable subscriptions, NgRx optional', 'No console warnings about unsubscribed observables, memory usage stable across navigation', 'Not using any pattern for subscription management across application', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/70527515/how-to-prevent-memory-leaks-in-angular', 'admin:1764191717');
