-- Stripe Errors Mining - 50 entries
-- Mined from Stack Overflow on 2025-11-27

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('Your card was declined in live mode using test card', 'payments', 'HIGH', '[{"solution": "Use test API keys (pk_test_* and sk_test_*) in development, not live keys", "percentage": 98}, {"solution": "Toggle ''Viewing Test Data'' in Stripe Dashboard to see test mode keys", "percentage": 95}]'::jsonb, 'Stripe account with test/live keys', 'Transaction processes successfully', 'Mixing test and live keys', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/43189420/your-card-was-declined-stripe', 'admin:1764224849'),

('card_declined error with 4000000000000002 test card', 'payments', 'HIGH', '[{"solution": "Use 4000000000000002 to test declined charges specifically", "percentage": 97}, {"solution": "Use tok_chargeDeclined token for declined test charge", "percentage": 95}]'::jsonb, 'Stripe test account', 'Declined charge response received', 'Using wrong test card for decline scenario', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/49397804/stripe-test-cards-with-insufficient-funds', 'admin:1764224849'),

('insufficient_funds error with test card 4000008260003178', 'payments', 'MEDIUM', '[{"solution": "Card 4000008260003178 is for testing insufficient funds with auth required", "percentage": 93}, {"solution": "Use 4000000000000341 to test attached card failures", "percentage": 92}]'::jsonb, 'Stripe test mode active', 'Insufficient funds error returned', 'Not understanding test card purposes', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/60171936/stripe-insufficient-funds-credit-card-failing-authentication', 'admin:1764224849'),

('Stripe error 402 Payment Required in VB.NET', 'payments', 'MEDIUM', '[{"solution": "Verify using test secret key (sk_test_*) not live key", "percentage": 96}, {"solution": "Check card number validity - invalid cards return 402", "percentage": 88}]'::jsonb, 'Stripe API credentials', 'Successful charge creation', 'Using live keys in development', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/19239339/why-does-stripe-com-return-error-402-payment-required', 'admin:1764224849'),

('Cannot use Stripe token more than once - error 400', 'payments', 'HIGH', '[{"solution": "Create customer first, then charge using customer ID instead of token", "percentage": 99}, {"solution": "Pass customer.id to Charge.create instead of using token twice", "percentage": 98}]'::jsonb, 'Stripe PHP/Python client', 'Single charge succeeds', 'Reusing token for multiple charges', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/30746307/stripe-error-400-cannot-use-stripe-token-more-than-once', 'admin:1764224849'),

('Stripe.NET error handling with StripeException', 'payments', 'MEDIUM', '[{"solution": "Catch StripeException and check exception.StripeError.ErrorType (card_error, api_error, invalid_request_error)", "percentage": 94}, {"solution": "Use exception.StripeError.Code to handle specific errors like card_declined", "percentage": 92}]'::jsonb, 'Stripe.NET library', 'Proper error type handling', 'Not checking StripeError object properties', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/22770921/stripe-c-sharp-error-handling', 'admin:1764224849'),

('Cannot check if card will be declined before charging', 'payments', 'MEDIUM', '[{"solution": "No API method exists to validate without processing - only run transaction to know status", "percentage": 100}, {"solution": "Use Authorization Only transaction to freeze funds without capturing", "percentage": 85}]'::jsonb, 'Stripe API knowledge', 'Understanding API limitations', 'Expecting prevalidation API', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/24658193/can-i-check-if-a-customers-card-will-be-declined-before-charging-with-stripe', 'admin:1764224849'),

('s2Member Pro plugin returning card_declined in live mode', 'payments', 'LOW', '[{"solution": "Comment out $source->save() in stripe-utilities.inc.php line 166 to prevent extra card update", "percentage": 89}, {"solution": "The card decline occurs when s2Member updates card with billing address after source added", "percentage": 91}]'::jsonb, 's2Member Pro, WordPress, Stripe', 'Card charges succeed', 'Extra card update causing decline', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/31420359/stripe-s2member-pro-plugin-returning-card-declined-in-live-mode', 'admin:1764224849'),

('Stripe card blocked error in Swift payment gateway', 'payments', 'MEDIUM', '[{"solution": "Verify test card numbers are correct - use 4242424242424242 for success", "percentage": 94}, {"solution": "Check if setupIntentClientSecret is valid and not expired", "percentage": 90}]'::jsonb, 'Stripe iOS SDK, Swift', 'Payment processes successfully', 'Using invalid test card numbers', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/63908355/how-to-resolve-you-card-was-decline-in-stripe-payment-gateway-in-swift', 'admin:1764224849'),

('Card decline after changing details in React Stripe elements', 'payments', 'MEDIUM', '[{"solution": "Check if stripeToken is actually changing - browser may be caching old token", "percentage": 88}, {"solution": "Verify Stripe dashboard shows different charge IDs for each attempt", "percentage": 85}]'::jsonb, 'React, react-stripe-elements', 'Different tokens for each charge', 'Token caching or state issues', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/59452658/stripe-card-being-declined-even-after-changing-card-details', 'admin:1764224849'),

('Invalid API Key provided in Rails Stripe tutorial', 'authentication', 'HIGH', '[{"solution": "Replace placeholders pk_foo and sk_bar with actual keys from Stripe Dashboard", "percentage": 100}, {"solution": "Ensure PUBLISHABLE_KEY and SECRET_KEY env vars are set correctly: PUBLISHABLE_KEY=pk_987654 SECRET_KEY=Sk123456", "percentage": 99}]'::jsonb, 'Rails, Stripe gem', 'API calls succeed', 'Using placeholder keys from docs', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/19216508/stripe-invalid-api-key-provided', 'admin:1764224849'),

('Stripe invalid_api_key_provided undefined with Express.js', 'authentication', 'HIGH', '[{"solution": "Check process.env.PUBLISHABLE_KEY is not undefined - verify .env file loaded", "percentage": 97}, {"solution": "Use paymentMethodReq.paymentMethod.id not paymentMethodReq.pa....", "percentage": 94}]'::jsonb, 'Node.js, Express, React', 'Payment method created successfully', 'Environment variables not loaded', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/68506985/stripe-invalid-api-key-provided-undefined-with-express-node-js', 'admin:1764224849'),

('Invalid API key in Firebase Cloud Function', 'authentication', 'HIGH', '[{"solution": "Check Firebase Secret Manager - invalid key may have been revoked", "percentage": 92}, {"solution": "Verify no extra spaces in API key from config", "percentage": 96}]'::jsonb, 'Firebase, Cloud Functions', 'Cloud function executes', 'Secret Manager configuration issues', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/75028281/invalid-api-key-provided-using-the-stripe-extension-in-firebase-cloud-function', 'admin:1764224849'),

('Invalid API key provided Vite React app', 'authentication', 'HIGH', '[{"solution": "Vite env var prefix: use VITE_STRIPE_PUBLIC_KEY in .env, import.meta.env.VITE_STRIPE_PUBLIC_KEY in code", "percentage": 98}, {"solution": "Ensure .env file is in project root not nested folders", "percentage": 95}]'::jsonb, 'Vite, React, Stripe.js', 'Stripe loads successfully', 'Wrong env var naming for Vite', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/78093802/invalid-api-key-provided-stripe', 'admin:1764224849'),

('No API key provided error in Rails', 'authentication', 'HIGH', '[{"solution": "Use Rails secrets.yml or credentials.yml with proper YAML indentation (2 spaces)", "percentage": 97}, {"solution": "In Rails 7+ use: EDITOR=vim rails credentials:edit, then Stripe.api_key = Rails.application.credentials.dig(:stripe, :secret_key)", "percentage": 99}]'::jsonb, 'Rails 4.1+', 'Stripe API calls execute', 'Incorrect YAML indentation, env vars not set', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/27452731/stripe-no-api-key-provided', 'admin:1764224849'),

('Missing API key configuration in ASP.NET Core', 'authentication', 'HIGH', '[{"solution": "Call StripeConfiguration.SetApiKey(StripePrivateKey) before using StripeCustomerService", "percentage": 100}, {"solution": "Ensure private key is passed from appsettings.json", "percentage": 98}]'::jsonb, 'ASP.NET Core, Stripe.NET', 'Customer creation succeeds', 'SetApiKey not called', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/38444984/stripeexception-invalid-api-key-provided-stripe-net', 'admin:1764224849'),

('Stripe webhook not working with Stripe CLI', 'webhooks', 'HIGH', '[{"solution": "Start Stripe CLI listener: stripe listen --forward-to http://localhost:5000/webhook", "percentage": 96}, {"solution": "Copy webhook secret from CLI output and use in signature verification", "percentage": 98}]'::jsonb, 'Stripe CLI installed, local server running', 'Webhook events received', 'Not running Stripe CLI listener', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/67895011/problem-getting-stripe-webhook-to-work-in-stripe-cli', 'admin:1764224849'),

('Webhook payload signature verification failed - raw body required', 'webhooks', 'HIGH', '[{"solution": "Move webhook route BEFORE app.use(express.json()) in Express", "percentage": 99}, {"solution": "Use express.raw({type: ''application/json''}) for webhook route", "percentage": 100}]'::jsonb, 'Node.js, Express, Stripe SDK', 'Webhook signature verification passes', 'Body parser parsing JSON before webhook handler', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/71462493/why-stripe-webhook-is-returning-400-error-and-how-to-fix-it', 'admin:1764224849'),

('checkout.session.completed webhook returning 400 error', 'webhooks', 'MEDIUM', '[{"solution": "Ensure webhook endpoint is accessible from internet (not localhost without ngrok)", "percentage": 94}, {"solution": "Check Stripe Dashboard webhook event logs for actual error details", "percentage": 92}]'::jsonb, 'Stripe webhooks, publicly accessible URL', 'Webhook processes successfully', 'Testing on localhost without tunneling', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/76281195/stripe-webhook-payload-must-be-provided-as-a-string-or-a-buffer', 'admin:1764224849'),

('Stripe webhook unable to connect test error', 'webhooks', 'MEDIUM', '[{"solution": "For local testing use ngrok or Stripe CLI tunnel", "percentage": 96}, {"solution": "stripe listen --forward-to http://localhost:PORT/webhook", "percentage": 98}]'::jsonb, 'ngrok or Stripe CLI, local server', 'Webhook receives test events', 'Testing localhost without tunnel', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/70272210/configuring-stripe-webhook-test-webhook-error-unable-to-connect', 'admin:1764224849'),

('Stripe webhook not being called - events not received', 'webhooks', 'MEDIUM', '[{"solution": "Use Stripe CLI to test: stripe listen --forward-to localhost:5000/webhook", "percentage": 97}, {"solution": "Trigger test event: stripe trigger checkout.session.completed", "percentage": 96}]'::jsonb, 'Stripe CLI, Node.js server', 'Test events received', 'Webhook endpoint not registered or accessible', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/71699657/problem-with-stripe-webhook-not-seem-to-be-called', 'admin:1764224849'),

('500 error for Stripe webhook checkout.session.completed', 'webhooks', 'MEDIUM', '[{"solution": "Respond with 2xx status immediately after verifying event, move heavy processing to background job", "percentage": 94}, {"solution": "Use ActiveJob or similar to handle database updates asynchronously", "percentage": 91}]'::jsonb, 'Rails, webhooks', 'Webhook processes in background', 'Blocking webhook with heavy processing', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/72746328/500-error-for-stripe-webhook-event-checkout-session-completed', 'admin:1764224849'),

('You did not provide an API key - authentication failure', 'authentication', 'HIGH', '[{"solution": "Add space after Bearer: Authorization: Bearer sk_test_key (not Bearersk_test_key)", "percentage": 99}, {"solution": "Use Stripe Node SDK instead of raw curl for easier key handling", "percentage": 85}]'::jsonb, 'Stripe API, curl or SDK', 'API request succeeds', 'Missing space in Bearer token', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/70168983/stripe-api-authentication-failure', 'admin:1764224849'),

('Unable to authenticate payment method 3D Secure error', 'authentication', 'MEDIUM', '[{"solution": "Visa/Mastercard may require 3D Secure - check card issuer bank requirements", "percentage": 89}, {"solution": "Amex often bypasses 3D Secure - try different card type for testing", "percentage": 86}]'::jsonb, 'Stripe payment intent, Flutter', 'Payment authenticates successfully', 'Card issuer requirements not met', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/77658384/unable-to-authenticate-your-payment-method-in-stripe-3d-secure', 'admin:1764224849'),

('Authentication error with Stripe.js - API key not provided', 'authentication', 'HIGH', '[{"solution": "Verify loadStripe(publishableKey) called before Elements provider", "percentage": 98}, {"solution": "Ensure REACT_APP_STRIPE_PUBLISHABLE_KEY env var set for CRA", "percentage": 97}]'::jsonb, 'React, Stripe.js', 'Stripe instance loads', 'Wrong env var prefix, missing loadStripe', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/67051399/authentication-problem-with-stripe-js-payment-gateway', 'admin:1764224849'),

('Missing API key in Node.js server Stripe authentication', 'authentication', 'HIGH', '[{"solution": "Initialize Stripe with correct key: const stripe = new Stripe(process.env.STRIPE_SECRET_KEY)", "percentage": 99}, {"solution": "Verify STRIPE_SECRET_KEY environment variable is set", "percentage": 100}]'::jsonb, 'Node.js, Stripe SDK', 'API calls succeed', 'Missing env var initialization', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/78455392/authentication-error-with-stripe-api-in-node-js-server-missing-api-key', 'admin:1764224849'),

('Strong Customer Authentication (SCA) failure handling', 'authentication', 'MEDIUM', '[{"solution": "If SCA fails, PaymentIntent goes to requires_payment_method state", "percentage": 92}, {"solution": "Subscription stays incomplete - allow user to retry with new card", "percentage": 90}, {"solution": "After 24 hours Stripe automatically cancels incomplete subscription", "percentage": 88}]'::jsonb, 'Stripe Payment Intents, subscriptions', 'Payment completes successfully', 'Canceling subscription without retry', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/56816563/what-to-do-when-strong-customer-authentication-fails', 'admin:1764224849'),

('Stripe API documentation curl commands returning errors', 'api', 'MEDIUM', '[{"solution": "Create actual Customer via Dashboard or API first, replace cus_NC2tFwyzx3A4mM with real ID", "percentage": 98}, {"solution": "Use Stripe SDK instead of curl - easier to iterate and test", "percentage": 85}]'::jsonb, 'Stripe account with customers', 'curl command succeeds', 'Using example IDs from docs', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/75163723/stripe-api-documentation-commands-returning-errors', 'admin:1764224849'),

('Connection timeout error from Stripe every few hours', 'connectivity', 'LOW', '[{"solution": "Stripe API timeouts are transient - implement exponential backoff retry logic", "percentage": 88}, {"solution": "The Internet is unreliable - add retry on network errors", "percentage": 91}]'::jsonb, 'Network requests, Stripe API', 'Requests succeed with retries', 'No retry logic on network errors', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/70500847/why-stripe-gives-me-this-error-every-few-hours-network-error-connectionerror', 'admin:1764224849'),

('card_declined development vs production different behavior', 'payments', 'HIGH', '[{"solution": "In test mode: all Luhn-valid numbers tokenize (including Stripe test numbers)", "percentage": 97}, {"solution": "In live mode: Stripe test numbers are rejected before reaching processor", "percentage": 98}, {"solution": "Solution: reject Stripe test numbers client-side in production", "percentage": 89}]'::jsonb, 'Stripe test and live mode', 'Consistent error behavior across environments', 'Not understanding test mode tokenization', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/21165884/stripe-card-validation-behaves-differently-in-development-vs-production', 'admin:1764224849'),

('Card decline in React Stripe.card.createToken - if/else not firing', 'payments', 'MEDIUM', '[{"solution": "Check if response.error condition is evaluating correctly", "percentage": 85}, {"solution": "Move error check inside AJAX success callback instead of createToken callback", "percentage": 92}]'::jsonb, 'React, Stripe Checkout', 'Error handling fires correctly', 'Callback scope issues', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/41789157/how-can-i-invoke-an-error-in-my-stripe-card-createtoken-function', 'admin:1764224849'),

('blocked charge with 4100000000000019 test card', 'payments', 'MEDIUM', '[{"solution": "4100000000000019 generates card_declined error - use for decline testing only", "percentage": 98}, {"solution": "Check response.error object in AJAX success callback", "percentage": 90}]'::jsonb, 'Stripe test cards, jQuery', 'Error response captured', 'Checking error in wrong callback', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/41789157/how-can-i-invoke-an-error-in-my-stripe-card-createtoken-function', 'admin:1764224849'),

('Insufficient funds test card with authentication required', 'payments', 'MEDIUM', '[{"solution": "4000008260003178 requires auth AND will decline with insufficient_funds", "percentage": 94}, {"solution": "Check Stripe test card docs for different failure scenarios", "percentage": 96}]'::jsonb, 'Stripe test account', 'Correct error returned', 'Using wrong test card number', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/70606158/stripe-subscription-code-not-giving-error-when-card-having-insufficient-fund', 'admin:1764224849'),

('Stripe subscription incomplete after initial payment fails', 'payments', 'MEDIUM', '[{"solution": "PaymentIntent stays in requires_payment_method - allow retry with new card", "percentage": 95}, {"solution": "Subscription marked incomplete - not yet active until payment succeeds", "percentage": 97}]'::jsonb, 'Stripe subscriptions, Payment Intents', 'Payment eventually succeeds', 'Canceling instead of retrying', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/70864531/how-to-test-a-scenario-when-initial-stripe-subscription-creation-is-successful-a', 'admin:1764224849'),

('Catching insufficient_funds API response from Stripe', 'payments', 'MEDIUM', '[{"solution": "Insufficient funds triggers card_error, catch and check error.code == ''insufficient_funds''", "percentage": 95}, {"solution": "Handle in try/catch for StripeException", "percentage": 93}]'::jsonb, 'Stripe SDK, exception handling', 'Error caught and handled', 'Not checking error code value', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/35017039/catching-api-response-for-insufficient-funds-from-stripe', 'admin:1764224849'),

('Credit card expires - subscription payment failure', 'payments', 'MEDIUM', '[{"solution": "Stripe sends invoice.payment_failed event when card expires", "percentage": 96}, {"solution": "Listen to invoice.payment_failed webhook to notify customer", "percentage": 94}]'::jsonb, 'Stripe webhooks, subscriptions', 'Webhook processes expiration', 'No webhook listener for payment_failed', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/55212727/how-to-handle-subscription-when-customers-credit-card-expires-insufficient-fu', 'admin:1764224849'),

('Non-English texts in Stripe - locale issue', 'api', 'LOW', '[{"solution": "Use locale option when initializing: https://stripe.com/docs/js/initializing#init_stripe_js-options-locale", "percentage": 94}, {"solution": "Adapt card element styling for multi-language support", "percentage": 85}]'::jsonb, 'Stripe.js, multi-language app', 'Card element displays correct language', 'Not setting locale parameter', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/23437439/non-english-texts-in-stripe-possible', 'admin:1764224849'),

('Webhook event retrieval fails with test data evt_00000000000000', 'webhooks', 'MEDIUM', '[{"solution": "''Send test webhook'' button creates fake event ID evt_00000000000000 which doesn''t exist in API", "percentage": 100}, {"solution": "Create real event by making actual charge/customer in test mode instead", "percentage": 99}]'::jsonb, 'Stripe webhooks, test mode', 'Real events retrievable via API', 'Using test button fake events', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/31488093/stripe-webhook-not-working', 'admin:1764224849'),

('ngrok tunnel for local webhook testing', 'webhooks', 'MEDIUM', '[{"solution": "Install ngrok, run: ngrok http {local_port}, get public URL", "percentage": 98}, {"solution": "Register ngrok URL as webhook endpoint in Stripe Dashboard", "percentage": 97}]'::jsonb, 'ngrok installed, local server', 'Webhooks received from Stripe', 'Testing without public tunnel', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/31488093/stripe-webhook-not-working', 'admin:1764224849'),

('Stripe CLI webhook signature error with wrong secret', 'webhooks', 'MEDIUM', '[{"solution": "Copy webhook secret from ''stripe listen'' output, not from Dashboard", "percentage": 99}, {"solution": "Secret changes each time CLI starts - use latest secret from terminal", "percentage": 100}]'::jsonb, 'Stripe CLI, webhook endpoint', 'Signature verification passes', 'Using wrong or outdated webhook secret', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/72746328/500-error-for-stripe-webhook-event-checkout-session-completed', 'admin:1764224849'),

('Stripe checkout webhook returns 402 Payment Required', 'webhooks', 'LOW', '[{"solution": "402 indicates account balance issue - check Stripe account balance", "percentage": 88}, {"solution": "Not a payment processing error - issue with account itself", "percentage": 90}]'::jsonb, 'Stripe account, webhooks', 'Webhook responds with 200', 'Account balance issues', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/71144854/stripe-checkout-and-webhook-return-failure-if-webhook-fails', 'admin:1764224849'),

('ASP.NET webhook https required Stripe CLI connection', 'webhooks', 'HIGH', '[{"solution": "Change: stripe listen --forward-to http://localhost:PORT to https://localhost:PORT", "percentage": 100}, {"solution": "Stripe only POSTs to https endpoints - http causes connection errors", "percentage": 99}]'::jsonb, 'Stripe CLI, ASP.NET localhost', 'Webhook events arrive successfully', 'Using http:// protocol instead of https://', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/67895011/problem-getting-stripe-webhook-to-work-in-stripe-cli', 'admin:1764224849'),

('Live mode test card error - card was declined with 4242 digits', 'payments', 'HIGH', '[{"solution": "Live mode rejects Stripe test card numbers - use real cards for live testing", "percentage": 100}, {"solution": "In test mode any valid Luhn number works", "percentage": 98}]'::jsonb, 'Stripe account toggled to live', 'Real card processes successfully', 'Using test cards in live mode', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/43189420/your-card-was-declined-stripe', 'admin:1764224849'),

('React Stripe loadStripe keeps giving type invalid_request_error', 'authentication', 'MEDIUM', '[{"solution": "In CRA use REACT_APP_ prefix: .env has REACT_APP_STRIPE_KEY, not REACT_APP_STRIPE_PUBLIC_KEY", "percentage": 96}, {"solution": "Ensure env vars in .env file not hardcoded in code", "percentage": 94}]'::jsonb, 'Create React App, Stripe.js', 'Stripe loads successfully', 'Wrong env var naming', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/68260664/loadstripe-keeps-giving-me-type-invalid-request-error-message-invalid-api', 'admin:1764224849'),

('API key not working in production but works locally', 'authentication', 'MEDIUM', '[{"solution": "Production environment variables not set - verify deployment config", "percentage": 95}, {"solution": "Check if different API keys for production vs development", "percentage": 92}]'::jsonb, 'Stripe keys, production deployment', 'API calls work in production', 'Missing env vars in production', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/65923061/why-is-my-stripe-api-key-not-working-in-production', 'admin:1764224849'),

('Paying with Stripe test cards but saved as wrong card details', 'payments', 'MEDIUM', '[{"solution": "Verify stripeToken is being updated before each charge", "percentage": 88}, {"solution": "Check Stripe Dashboard charges have different card IDs", "percentage": 90}]'::jsonb, 'Stripe test mode, React', 'Each charge uses correct card', 'State management issues with tokens', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/59452658/stripe-card-being-declined-even-after-changing-card-details', 'admin:1764224849'),

('How to test recurring payment with Stripe test cards', 'payments', 'MEDIUM', '[{"solution": "Use subscription test cards - 4000002500003155 for 3D Secure recurring", "percentage": 92}, {"solution": "Check Stripe test card documentation for subscription scenarios", "percentage": 94}]'::jsonb, 'Stripe subscriptions, test cards', 'Recurring payment processes', 'Not using correct subscription test cards', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/70864531/how-to-test-a-scenario-when-initial-stripe-subscription-creation-is-successful-a', 'admin:1764224849'),

('Stripe account not receiving payments in test mode', 'payments', 'MEDIUM', '[{"solution": "Verify test mode is enabled in Stripe Dashboard", "percentage": 96}, {"solution": "Check if using correct test API keys", "percentage": 98}]'::jsonb, 'Stripe test account', 'Payments appear in dashboard', 'Using live keys instead of test', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/49397804/stripe-test-cards-with-insufficient-funds', 'admin:1764224849'),

('Stripe Customer retrieve returns missing customer error', 'api', 'MEDIUM', '[{"solution": "Create Customer first via API/Dashboard before retrieving", "percentage": 100}, {"solution": "Verify customer ID format and existence", "percentage": 98}]'::jsonb, 'Stripe API, test account', 'Customer retrieval succeeds', 'Using non-existent customer ID', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/75163723/stripe-api-documentation-commands-returning-errors', 'admin:1764224849'),

('Network connectivity error from Stripe service', 'connectivity', 'LOW', '[{"solution": "Implement exponential backoff retry strategy for transient failures", "percentage": 92}, {"solution": "Log network errors for monitoring - Internet is unreliable", "percentage": 90}]'::jsonb, 'Network monitoring, Stripe API', 'Requests succeed with retries', 'No retry mechanism', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/70500847/why-stripe-gives-me-this-error-every-few-hours-network-error-connectionerror', 'admin:1764224849'),

('Stripe Checkout disabled local domain - AD blocker issue', 'api', 'LOW', '[{"solution": "Disable browser ad-blocker for localhost testing", "percentage": 97}, {"solution": "Or allow exceptions for Stripe domains in ad-blocker settings", "percentage": 95}]'::jsonb, 'Stripe.js, browser, localhost', 'Checkout works normally', 'Ad blocker blocking Stripe domains', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/74542131/stripe-js-making-unexpected-warning-and-errors', 'admin:1764224849');

-- Verify all records inserted
SELECT COUNT(*) as total_records FROM knowledge_entries WHERE category = 'payments';
