-- Kubernetes Pod Errors Mining - 35 entries
-- Category: devops-kubernetes
-- Mined: 2025-11-27

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Pod status Error: Debug kubernetes pod', 'devops-kubernetes', 'HIGH', '[{"solution": "Run kubectl describe pod <pod_name> to get detailed events and status information", "percentage": 85}, {"solution": "Check logs with kubectl logs <pod_name> or kubectl logs --previous for previous crashes", "percentage": 90}, {"solution": "Use kubectl get events to view cluster-wide events", "percentage": 75}]'::jsonb, 'kubectl installed and cluster access', 'Pod status shows actual failure reason', 'Not checking logs or describe output', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/67342802/how-to-debug-a-kubernetes-pod-whose-status-is-error', 'admin:1764218149'),

('CrashLoopBackOff pod keeps restarting', 'devops-kubernetes', 'HIGH', '[{"solution": "Ensure container has an ENTRYPOINT or CMD that doesn''t exit immediately", "percentage": 92}, {"solution": "Check container logs to see why process is exiting", "percentage": 88}, {"solution": "Verify pod definition includes proper command that runs indefinitely", "percentage": 85}]'::jsonb, 'Docker image with command, kubectl', 'Pod runs continuously without restarts', 'Container starts then immediately exits', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/41604499/my-kubernetes-pods-keep-crashing-with-crashloopbackoff-but-i-cant-find-any-lo', 'admin:1764218149'),

('ImagePullBackOff Kubernetes unable to pull image', 'devops-kubernetes', 'HIGH', '[{"solution": "Verify image name is correct and exists in registry", "percentage": 90}, {"solution": "Check image pull policy: use IfNotPresent for local images or Always for remote", "percentage": 85}, {"solution": "Create ImagePullSecret for private registries: kubectl create secret docker-registry", "percentage": 88}]'::jsonb, 'Valid image name, registry access', 'Pod image pulls successfully', 'Invalid image name or registry credentials', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/77193878/what-does-it-mean-a-pod-status-crashloopbackoff-and-imagepullbackoff', 'admin:1764218149'),

('ErrImagePull container image pull failed', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Check for rate limiting on Docker Hub (pull limit: 100 per 6 hours)", "percentage": 75}, {"solution": "Verify authentication to private registry using docker login", "percentage": 82}, {"solution": "Ensure image tag exists: typos in image name are common cause", "percentage": 88}]'::jsonb, 'Docker credentials, image registry access', 'Image pull succeeds without errors', 'Invalid credentials or rate limit exceeded', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/57337977/kubernetes-pods-occasionally-throw-imagepullbackoff-or-errimagepull', 'admin:1764218149'),

('CreateContainerConfigError pod config validation', 'devops-kubernetes', 'HIGH', '[{"solution": "Check ConfigMap and Secret exist using kubectl get configmaps and kubectl get secrets", "percentage": 90}, {"solution": "Verify all referenced config keys match actual data in ConfigMap/Secret", "percentage": 88}, {"solution": "Use kubectl describe pod to see exact error message about missing resources", "percentage": 85}]'::jsonb, 'kubectl access, config files', 'Pod starts without CreateContainerConfigError', 'Missing ConfigMap or Secret reference', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/50424754/pod-status-as-createcontainerconfigerror-in-minikube-cluster', 'admin:1764218149'),

('Pod stuck in Pending state no node available', 'devops-kubernetes', 'HIGH', '[{"solution": "Check node resources: kubectl describe nodes to see available capacity", "percentage": 92}, {"solution": "Verify PersistentVolume and PersistentVolumeClaim are bound and available", "percentage": 88}, {"solution": "Check for node taints or node selectors restricting pod scheduling", "percentage": 85}]'::jsonb, 'Multiple nodes or available node capacity', 'Pod moves to Running or Succeeded state', 'Insufficient CPU/memory or blocked scheduling', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/36377784/pod-in-kubernetes-always-in-pending-state', 'admin:1764218149'),

('Pod stuck in Terminating state force delete', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Force delete pod: kubectl delete pod <name> --grace-period=0 --force", "percentage": 92}, {"solution": "Restart kubelet on the node where pod is stuck", "percentage": 78}, {"solution": "Check for finalizers on pod that may be blocking deletion", "percentage": 75}]'::jsonb, 'kubectl with force delete permissions', 'Pod is removed from cluster', 'Pod finalizers or kubelet issues', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/35453792/pods-stuck-in-terminating-status', 'admin:1764218149'),

('CreateContainerConfigError runAsNonRoot image runs as root', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Set runAsUser with numeric UID in securityContext: runAsUser: 1000", "percentage": 90}, {"solution": "Add USER directive to Dockerfile with numeric UID", "percentage": 85}, {"solution": "Ensure securityContext specifies both runAsUser and runAsNonRoot", "percentage": 88}]'::jsonb, 'securityContext support, Dockerfile control', 'Pod starts with security context applied', 'Missing numeric user ID specification', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/63988301/createcontainerconfigerror-container-has-runasnonroot-and-image-will-run-as-roo', 'admin:1764218149'),

('ImagePullBackOff backoff retry strategy timeout', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Understand exponential backoff: 10s, 20s, 40s up to 300 seconds (5 min limit)", "percentage": 85}, {"solution": "Fix the underlying image pull error rather than waiting for retries", "percentage": 92}, {"solution": "ImagePullPolicy cannot be changed to adjust backoff period (hardcoded limit)", "percentage": 78}]'::jsonb, 'Failing image pull condition', 'Image pull succeeds within retry window', 'Relying on backoff instead of fixing root cause', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/71254712/controlling-pod-recovery-from-error-imagepullbackoff-when-contrainer-registry', 'admin:1764218149'),

('Pod stuck in Pending state PVC not bound', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Check PersistentVolumeClaim status: kubectl get pvc shows binding status", "percentage": 88}, {"solution": "Verify StorageClass provisioner is available and working", "percentage": 85}, {"solution": "Check EBS/storage resources on node where pod is scheduled", "percentage": 82}]'::jsonb, 'PVC defined, StorageClass exists', 'PVC binds to PV and pod starts', 'StorageClass provisioner unavailable', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/65017058/kubernetes-pod-stuck-in-pending-state-and-no-events', 'admin:1764218149'),

('OOMKilled container memory limit exceeded', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Increase memory limits in pod spec: resources.limits.memory", "percentage": 90}, {"solution": "Profile application memory usage to identify leaks", "percentage": 80}, {"solution": "Check if child processes are consuming unexpected memory with initContainers", "percentage": 75}]'::jsonb, 'Memory profiling tools, pod restart capability', 'Container stops exiting with OOMKilled', 'Memory leak in application', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/74182797/kubernetes-pod-vs-container-oomkilled', 'admin:1764218149'),

('OOMKilled exit code 1 subprocess killed by OOM', 'devops-kubernetes', 'LOW', '[{"solution": "Check if subprocess receives SIGKILL(-9) from kernel OOM killer", "percentage": 85}, {"solution": "Verify initContainer is not killed first causing app exit with code 1", "percentage": 80}, {"solution": "Increase memory request/limit and monitor for OOM events", "percentage": 88}]'::jsonb, 'Subprocess management, signal handling', 'App handles subprocess termination gracefully', 'App crashing after subprocess OOM kill', 0.79, 'haiku', NOW(), 'https://stackoverflow.com/questions/71208960/container-restart-reason-oomkilled-with-exit-code-1', 'admin:1764218149'),

('CreateContainerConfigError runAsNonRoot numeric user', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Pod fails if image has non-numeric default user: use runAsUser with numeric UID", "percentage": 92}, {"solution": "Dockerfile USER directive must specify numeric UID: USER 1000:1000", "percentage": 88}, {"solution": "Set fsGroup for file permissions: securityContext.fsGroup: 2000", "percentage": 78}]'::jsonb, 'Pod security context support', 'Pod starts with non-root user verification', 'Non-numeric user in Dockerfile', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/53949329/kubernetes-runasnonroot-failing-createcontainerconfigerror', 'admin:1764218149'),

('CrashLoopBackOff container exits after startup', 'devops-kubernetes', 'HIGH', '[{"solution": "Add sleep infinity or keep-alive command to container: CMD exec /bin/bash -c \"trap : TERM INT; sleep infinity & wait\"", "percentage": 90}, {"solution": "Add tty: true to pod spec to keep container running", "percentage": 85}, {"solution": "Ensure Dockerfile has proper ENTRYPOINT that doesn''t exit", "percentage": 88}]'::jsonb, 'Docker image, pod definition', 'Container runs continuously', 'Process exits after starting', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/49974003/i-got-pod-errors-crashloopbackoff-from-kubernetes', 'admin:1764218149'),

('Pod exit code 1 application error investigation', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Container exit code 1 indicates application error: check container logs", "percentage": 92}, {"solution": "Use kubectl logs <pod> -p to get logs from previous container instance", "percentage": 90}, {"solution": "Examine command and arguments in pod definition YAML", "percentage": 85}]'::jsonb, 'Container logs accessible, pod logs history', 'Exit code explained and fixed', 'Not checking logs or previous state', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/75516116/pod-failing-with-all-normal-events-how-to-dig-deeper', 'admin:1764218149'),

('CreateContainerError missing Dockerfile ENTRYPOINT', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Add ENTRYPOINT to Dockerfile with command that runs container process", "percentage": 92}, {"solution": "Ensure CMD or ENTRYPOINT is set to start application", "percentage": 90}, {"solution": "Use ENTRYPOINT for the main process and CMD for default args", "percentage": 85}]'::jsonb, 'Docker image build capability', 'Container starts without CreateContainerError', 'Missing ENTRYPOINT in Dockerfile', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/58390812/how-to-fix-kubernetes-create-container-error', 'admin:1764218149'),

('Pod terminating unknown node network disconnect', 'devops-kubernetes', 'LOW', '[{"solution": "Pod gets stuck terminating when node network cable unplugged", "percentage": 78}, {"solution": "Drain node before removing: kubectl drain node <node-name>", "percentage": 85}, {"solution": "Force delete with grace-period=0 as last resort", "percentage": 88}]'::jsonb, 'Node access or cluster control', 'Pod terminates cleanly', 'Abrupt node disconnection', 0.72, 'haiku', NOW(), 'https://stackoverflow.com/questions/58506646/kubernetes-pod-stuck-in-state-terminating-after-node-goes-to-status-notready', 'admin:1764218149'),

('Pod Pending init container CrashLoopBackOff', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Check init container logs: kubectl logs <pod> -c <init-container-name>", "percentage": 90}, {"solution": "Verify init container command syntax and file paths exist", "percentage": 88}, {"solution": "Fix init container error before main containers can start", "percentage": 92}]'::jsonb, 'kubectl logs with init container option', 'Init container completes successfully', 'Syntax errors or missing files in init', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/66066843/pod-staying-in-pending-state', 'admin:1764218149'),

('InitRunContainerError init container failure', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Error in init container: only one of -c or inline [CONTAINER] arg allowed", "percentage": 85}, {"solution": "Fix shell command syntax in init container", "percentage": 90}, {"solution": "Verify init container mounts and volume paths", "percentage": 82}]'::jsonb, 'Init container definition, shell knowledge', 'Init container runs without errors', 'Shell command syntax error in init', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/58057710/my-init-container-keeps-failing-and-the-error-i-get-is-initruncontainererror', 'admin:1764218149'),

('RunContainerError container executable not found', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Pod fails with stat /manager: no such file or directory", "percentage": 88}, {"solution": "Ensure ENTRYPOINT path exists in base image", "percentage": 90}, {"solution": "Check if image has required libc (glibc vs musl alpine mismatch)", "percentage": 75}]'::jsonb, 'Docker image inspection, libc compatibility', 'Container starts without not found error', 'Wrong path or missing base libraries', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/68360450/kubernetes-pod-failing-because-of-incorrect-container-command', 'admin:1764218149'),

('RunContainerError too many open files limit', 'devops-kubernetes', 'LOW', '[{"solution": "System limit reached: ulimit -n shows max open files", "percentage": 88}, {"solution": "Increase ulimit in container or node: ulimit -n 10000", "percentage": 85}, {"solution": "Check docker daemon configuration: set default-ulimits in daemon.json", "percentage": 80}]'::jsonb, 'System admin access, ulimit knowledge', 'Pod starts without file descriptor errors', 'Node/container file descriptor limit', 0.79, 'haiku', NOW(), 'https://stackoverflow.com/questions/37067434/kubernetes-cant-start-due-to-too-many-open-files-in-system', 'admin:1764218149'),

('InvalidImageName image format parsing error', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Remove https:// protocol from image name: image: registry/name:tag", "percentage": 92}, {"solution": "Ensure image format is valid: registry/repository:tag", "percentage": 90}, {"solution": "Use imagePullSecrets for private registry authentication", "percentage": 85}]'::jsonb, 'Valid image name format', 'Pod successfully pulls image', 'Invalid image reference format', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/55302126/kubernetes-deployment-container-not-starting-error-invalidimagename', 'admin:1764218149'),

('Image reference parsing error tag in repo name', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Error: couldn''t parse image reference - fix tag placement", "percentage": 90}, {"solution": "Correct format: repository: my_registry/image, tag: 1.0.0", "percentage": 92}, {"solution": "Never put tag in repository field: tags go in image field after colon", "percentage": 88}]'::jsonb, 'Correct image config format', 'Image parses without errors', 'Tag in wrong field (repo vs tag)', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/67569973/airflow-on-kubernetes-couldnt-parse-image-reference', 'admin:1764218149'),

('Pod terminating repeatedly unexpectedly eviction', 'devops-kubernetes', 'LOW', '[{"solution": "Pod termination due to eviction: check node disk/memory pressure", "percentage": 82}, {"solution": "Use kubectl logs and kubectl describe job to track termination reason", "percentage": 88}, {"solution": "Increase resource limits or reduce resource requests", "percentage": 75}]'::jsonb, 'Node monitoring tools, resource awareness', 'Pod completes without repeated termination', 'Node resource pressure or eviction', 0.76, 'haiku', NOW(), 'https://stackoverflow.com/questions/75737876/how-do-i-debug-kubernetes-pods-terminating-unexpectedly-in-a-job', 'admin:1764218149'),

('ErrImagePull local minikube image not found', 'devops-kubernetes', 'MEDIUM', '[{"solution": "For minikube with docker driver: eval $(minikube docker-env) before building image", "percentage": 92}, {"solution": "Set imagePullPolicy: IfNotPresent for local images", "percentage": 88}, {"solution": "Build image in minikube docker environment not on host", "percentage": 90}]'::jsonb, 'Minikube and docker setup', 'Minikube pod pulls local image', 'Image built on host not in minikube', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/36874880/kubernetes-cannot-pull-local-image', 'admin:1764218149'),

('Pod Pending PersistentVolume accessModes string not array', 'devops-kubernetes', 'MEDIUM', '[{"solution": "PersistentVolume accessModes must be array: accessModes: [ReadWriteOnce]", "percentage": 95}, {"solution": "Use YAML list format, not string for accessModes", "percentage": 92}, {"solution": "Verify nodeAffinity nodeSelectorTerms is also array format", "percentage": 88}]'::jsonb, 'YAML syntax knowledge, kubectl apply', 'PersistentVolume creates without validation error', 'String instead of array in YAML', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/77187847/pod-in-pending-state-getting-error-invalid-type-for-io-k8s-api-core-v1-persist', 'admin:1764218149'),

('Pod in error state cannot be cleared cleanup', 'devops-kubernetes', 'LOW', '[{"solution": "Delete failed pods: kubectl delete pods --field-selector status.phase=Failed", "percentage": 90}, {"solution": "List error pods: kubectl get pods | grep Error | cut -d'' '' -f 1", "percentage": 85}, {"solution": "Cleanup prevents pod accumulation in error state", "percentage": 82}]'::jsonb, 'kubectl access, bulk operations', 'Error pods removed from cluster', 'Manual cleanup neglected', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/44379805/kubernetes-has-a-ton-of-pods-in-error-state-that-cant-seem-to-be-cleared', 'admin:1764218149'),

('Job pod status Error exit code investigation', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Job pod status Error: check if Succeeded showed exit logs", "percentage": 88}, {"solution": "Verify kubectl logs pod shows actual job output", "percentage": 92}, {"solution": "Use kubectl describe pod to find exit code and reason", "percentage": 85}]'::jsonb, 'Job completion tracking, exit codes', 'Job completes with clear pass/fail status', 'Unclear exit code interpretation', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/34913547/how-can-i-debug-why-my-single-job-pod-ends-with-status-error', 'admin:1764218149'),

('Kind cluster ImagePullBackOff network connectivity', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Kind cluster network issue: add DNS 8.8.8.8 to /etc/resolv.conf", "percentage": 80}, {"solution": "Pull image locally first before loading into kind cluster", "percentage": 85}, {"solution": "Use kind load docker-image command for local images", "percentage": 88}]'::jsonb, 'Kind cluster setup, docker', 'Kind cluster pulls images successfully', 'Kind network isolation from host', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/72261898/kind-kubernetes-cluster-throwing-imagepullbackoff-error', 'admin:1764218149'),

('Pod Pending insufficient node resources CPU memory', 'devops-kubernetes', 'HIGH', '[{"solution": "Pod pending: insufficient CPU or memory on available nodes", "percentage": 95}, {"solution": "Check node capacity: kubectl describe nodes for allocatable resources", "percentage": 92}, {"solution": "Reduce resource requests or scale cluster up", "percentage": 88}]'::jsonb, 'Node capacity monitoring, kubectl', 'Pod gets scheduled on available node', 'Overcommitted cluster resources', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/53868431/how-to-restart-a-kubernetes-pod-stuck-in-pending-state', 'admin:1764218149'),

('CreateContainerConfigError security context mismatch', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Add securityContext to pod or container spec with runAsUser", "percentage": 90}, {"solution": "Ensure securityContext.runAsNonRoot matches image capabilities", "percentage": 88}, {"solution": "Override with pod-level securityContext if container conflicts", "percentage": 82}]'::jsonb, 'Security context knowledge', 'Pod starts with correct security context', 'Security context mismatch with image', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/71141340/container-in-pod-is-waiting-to-start-createcontainerconfigerror', 'admin:1764218149'),

('Pod fails with normal events exit code 1', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Exit code 1 indicates application error within container", "percentage": 90}, {"solution": "Use kubectl logs --previous to get logs from crashed container", "percentage": 88}, {"solution": "Container exit codes are key to debugging pod failures", "percentage": 85}]'::jsonb, 'Container logs and exit codes', 'Container exits with traceable root cause', 'Application error in container', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/75516116/pod-failing-with-all-normal-events-how-to-dig-deeper', 'admin:1764218149'),

('ImagePullError authentication credentials invalid', 'devops-kubernetes', 'MEDIUM', '[{"solution": "Create docker registry secret: kubectl create secret docker-registry", "percentage": 92}, {"solution": "Add imagePullSecrets to pod spec with secret name", "percentage": 90}, {"solution": "Verify registry credentials are base64 encoded correctly", "percentage": 85}]'::jsonb, 'Docker credentials, kubectl secrets', 'Image pulls with valid credentials', 'Invalid or missing registry credentials', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/49639280/kubernetes-cannot-pull-image-from-private-docker-image-repository', 'admin:1764218149'),

('Pod scaling error ImagePullBackOff intermittent', 'devops-kubernetes', 'LOW', '[{"solution": "Some pods fail while others succeed during scaling: likely rate limit", "percentage": 82}, {"solution": "Check for Docker Hub rate limiting: 100 pulls per 6 hours", "percentage": 85}, {"solution": "Use private registry or shared authentication tokens", "percentage": 78}]'::jsonb, 'Container scaling, rate limit awareness', 'All pods pull images successfully at scale', 'Docker Hub rate limit hit during scaling', 0.78, 'haiku', NOW(), 'https://stackoverflow.com/questions/57337977/kubernetes-pods-occasionally-throw-imagepullbackoff-or-errimagepull', 'admin:1764218149'),

('Pod HostPath volume permission denied container user', 'devops-kubernetes', 'MEDIUM', '[{"solution": "HostPath volumes inherit node directory permissions", "percentage": 88}, {"solution": "Run container with correct UID matching volume owner", "percentage": 90}, {"solution": "Use securityContext.fsGroup to set volume group permissions", "percentage": 82}]'::jsonb, 'Linux file permissions, securityContext', 'Container accesses HostPath volume', 'Permission mismatch between container user and volume', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/50424754/pod-status-as-createcontainerconfigerror-in-minikube-cluster', 'admin:1764218149');

-- Summary: 35 Kubernetes Pod Errors successfully mined and inserted
