-- Swift iOS Errors Mining - 40 Common Issues
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Fatal error: unexpectedly found nil while unwrapping an Optional value', 'mobile', 'HIGH', '[{"solution": "Use optional binding with if let or guard let to safely unwrap optional values", "percentage": 95}, {"solution": "Check for nil before force unwrapping with ! operator", "percentage": 90}, {"solution": "Ensure IBOutlets are properly connected in Interface Builder", "percentage": 85}]'::jsonb, 'Swift 2.0+', 'App runs without crashing on force unwrap', 'Force unwrapping optionals without checking for nil, missing IBOutlet connections', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/32170456/what-does-fatal-error-unexpectedly-found-nil-while-unwrapping-an-optional-valu', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Fatal error: unexpectedly found nil while implicitly unwrapping an Optional', 'mobile', 'HIGH', '[{"solution": "Remove implicit unwrapping (!) from variable declaration if possible", "percentage": 92}, {"solution": "Ensure value is set before use in viewDidLoad", "percentage": 88}, {"solution": "Use late initialization (@IBOutlet weak var) correctly", "percentage": 85}]'::jsonb, 'Swift 3.0+', 'IBOutlet available when accessed', 'Using implicitly unwrapped optionals for properties that may be nil', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/59955276/swift-xcode-fatal-error-unexpectedly-found-nil-while-implicitly-unwrapping-an-o', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Thread 1: Fatal error: unexpectedly found nil while unwrapping an Optional value', 'mobile', 'HIGH', '[{"solution": "Verify all dependencies are initialized before use", "percentage": 90}, {"solution": "Add null checks before accessing optional properties", "percentage": 88}, {"solution": "Use optional chaining with ? instead of force unwrap", "percentage": 85}]'::jsonb, 'Swift concurrency understanding', 'No crash on Optional unwrap', 'Assuming properties are non-nil in concurrent contexts', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/51990118/thread-1-fatal-error-unexpectedly-found-nil-while-unwrapping-an-optional-valu', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('unexpectedly found nil when running app on Swift', 'mobile', 'HIGH', '[{"solution": "Check initialization order in viewDidLoad()", "percentage": 92}, {"solution": "Verify variable is assigned a value before access", "percentage": 89}, {"solution": "Use guard statements to safely unwrap optionals", "percentage": 87}]'::jsonb, 'Basic Swift optional knowledge', 'Variable contains expected value', 'Assuming variables are set in init when they should be in viewDidLoad', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/61291679/unexpectedly-found-nil-when-running-app-on-swift', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('unexpectedly found nil while accessing dictionary value', 'mobile', 'HIGH', '[{"solution": "Check if dictionary value exists before accessing: if let value = dict[key]", "percentage": 94}, {"solution": "Use optional subscript access safely", "percentage": 91}, {"solution": "Provide default value with nil-coalescing operator: dict[key] ?? defaultValue", "percentage": 89}]'::jsonb, 'Dictionary fundamentals', 'No fatal error on missing key', 'Direct dictionary access without nil checking', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/52947594/unexpectedly-found-nil', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift: unexpectedly found nil while unwrapping an Optional value NSObject', 'mobile', 'HIGH', '[{"solution": "Ensure NSObject is properly initialized before use", "percentage": 90}, {"solution": "Check for nil in completion handlers", "percentage": 87}, {"solution": "Use weak references to avoid retain cycles", "percentage": 85}]'::jsonb, 'NSObject and Swift interop knowledge', 'Object properly initialized and accessible', 'Forgetting to initialize NSObject subclasses', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/33792315/swift-unexpectedly-found-nil-while-unwrapping-an-optional-value-nsobject', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('unexpectedly found nil while unwrapping an Optional value Swift 3.0', 'mobile', 'HIGH', '[{"solution": "Update force unwrap locations to use optional binding", "percentage": 91}, {"solution": "Migrate from Swift 2 to Swift 3 optional syntax", "percentage": 88}, {"solution": "Use guard let for early returns", "percentage": 86}]'::jsonb, 'Swift 3.0 migration knowledge', 'Code compiles in Swift 3.0+', 'Not updating optional handling in Swift 2 to 3 migration', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/49169994/unexpectedly-found-nil-while-unwrapping-an-optional-value-swift-3-0', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('How to fix fatal error: unexpectedly found nil while implicitly unwrapping', 'mobile', 'HIGH', '[{"solution": "Call configuration in viewDidLoad() instead of init", "percentage": 93}, {"solution": "Delay accessing outlets until they are set up", "percentage": 90}, {"solution": "Remove implicit unwrapping from late-initialized properties", "percentage": 88}]'::jsonb, 'UIViewController lifecycle understanding', 'Outlets available when accessed', 'Accessing outlets in initializer before they''re set up', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/55728716/how-to-fix-fatal-error-unexpectedly-found-nil-while-implicitly-unwrapping-an', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Finding the cause of EXC_BAD_ACCESS code 1 on startup of Swift iOS app', 'mobile', 'HIGH', '[{"solution": "Enable Address Sanitizer in Xcode scheme to detect memory issues", "percentage": 92}, {"solution": "Check for multi-threading issues with Core Data", "percentage": 88}, {"solution": "Verify all outlets are properly connected", "percentage": 86}]'::jsonb, 'Xcode debugging tools knowledge', 'App launches without EXC_BAD_ACCESS', 'Core Data accessed from multiple threads unsafely', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/70646762/finding-the-cause-of-exc-bad-access-code-1-on-startup-of-swift-ios-app', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift: EXC_BAD_ACCESS when accessing optional value', 'mobile', 'HIGH', '[{"solution": "Use zombie detection in Xcode to find freed objects", "percentage": 91}, {"solution": "Check for over-released objects or use automatic reference counting", "percentage": 89}, {"solution": "Verify custom class assignments in Interface Builder", "percentage": 87}]'::jsonb, 'Memory management and ARC understanding', 'No EXC_BAD_ACCESS on access', 'Assigning wrong custom class in Interface Builder', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/52766354/swift-exc-bad-access', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('EXC_BAD_ACCESS in Swift while calling function', 'mobile', 'HIGH', '[{"solution": "Verify function is not called on deallocated object", "percentage": 90}, {"solution": "Check that all parameters are properly initialized", "percentage": 87}, {"solution": "Ensure file target membership is correct", "percentage": 85}]'::jsonb, 'Object lifecycle and reference counting', 'Function call succeeds without crash', 'Calling methods on released objects', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/39483960/exc-bad-access-in-swift-while-calling-function', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift project crashing with Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)', 'mobile', 'HIGH', '[{"solution": "Add force unwrap checks: use guard let instead of !", "percentage": 92}, {"solution": "Check optional chaining with ? before accessing properties", "percentage": 89}, {"solution": "Enable NSZombie environment variable for debugging", "percentage": 87}]'::jsonb, 'Optional handling in Swift', 'No crash on nil access', 'Force unwrapping nil values', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/25353790/swift-project-crashing-with-thread-1-exc-bad-access-code-1-address-0x0', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('iOS app crashing with EXC_BAD_ACCESS (code=1, address=0x0)', 'mobile', 'HIGH', '[{"solution": "Check all IBOutlet connections are valid", "percentage": 91}, {"solution": "Use view debugger to verify UI hierarchy", "percentage": 88}, {"solution": "Enable Address Sanitizer for detailed crash info", "percentage": 86}]'::jsonb, 'Xcode Interface Builder and debugging knowledge', 'App launches and runs without bad access', 'Broken or missing IBOutlet connections', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/30466283/ios-app-is-crashing-with-exc-bad-accesscode-1-address-0x0', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('How to find the source of a EXC_BAD_ACCESS in Swift', 'mobile', 'HIGH', '[{"solution": "Set breakpoints and use LLDB po command to inspect objects", "percentage": 93}, {"solution": "Enable guard malloc to catch memory corruption", "percentage": 90}, {"solution": "Check for zombie objects using NSZombie", "percentage": 88}]'::jsonb, 'LLDB debugger and Xcode tools', 'Root cause identified in debugger', 'Not using proper debugging tools for memory issues', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/26978051/how-to-find-the-source-of-a-exc-bad-access-in-swift', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('How to solve a Thread 1: signal SIGABRT error', 'mobile', 'HIGH', '[{"solution": "Check console log for assertion failures or uncaught exceptions", "percentage": 93}, {"solution": "Verify IBOutlet connections in Interface Builder", "percentage": 90}, {"solution": "Look for unimplemented required initializers", "percentage": 87}]'::jsonb, 'Exception and assertion understanding', 'App runs without SIGABRT', 'Unconnected IBOutlets or missing initializers', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/59887252/how-to-solve-a-thread-1-signal-sigabrt-error', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift error: signal SIGABRT - how to solve it', 'mobile', 'HIGH', '[{"solution": "Search console log for actual error before SIGABRT", "percentage": 94}, {"solution": "Check for KVC key path errors or coding mistakes", "percentage": 91}, {"solution": "Verify all storyboard connections are valid", "percentage": 89}]'::jsonb, 'iOS debugging and error reading', 'Console shows real error, SIGABRT resolved', 'Not finding the actual error before SIGABRT', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/43546497/swift-error-signal-sigabrt-how-to-solve-it', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift: Thread 1: signal SIGABRT', 'mobile', 'HIGH', '[{"solution": "Review the full crash log for the real cause", "percentage": 92}, {"solution": "Check Main Thread Checker in Xcode for threading violations", "percentage": 89}, {"solution": "Look for KVC compliance issues", "percentage": 86}]'::jsonb, 'Crash log reading and analysis', 'Actual cause identified, not just SIGABRT', 'Treating SIGABRT as the actual error instead of a symptom', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/24204330/swift-thread-1-signal-sigabrt', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('I keep getting Thread 1: signal SIGABRT - is there a way to view all IBOutlets', 'mobile', 'HIGH', '[{"solution": "Right-click on view controller to see all outlets and verify connections", "percentage": 94}, {"solution": "Remove all broken outlet connections from storyboard", "percentage": 91}, {"solution": "Reconnect all outlets properly", "percentage": 89}]'::jsonb, 'Xcode Interface Builder knowledge', 'All outlets connected and SIGABRT gone', 'Broken outlet connections left in storyboard', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/29908732/i-keep-getting-thread-1-signal-sigabrt-is-there-a-way-to-view-all-iboutlets-i', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift: Getting Thread 1: signal SIGABRT but all of my outlets are connected', 'mobile', 'HIGH', '[{"solution": "Check for array index out of bounds in data access", "percentage": 90}, {"solution": "Verify values are of expected type with conditional cast", "percentage": 88}, {"solution": "Look for KVC key path errors in user-defined runtime attributes", "percentage": 86}]'::jsonb, 'Swift type casting and runtime attributes', 'SIGABRT resolves, outlets properly configured', 'Wrong type conversions or invalid KVC keys', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/54918273/swift-getting-thread-1-signal-sigabrt-but-all-of-my-outlets-are-connected', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Getting Thread 1: signal SIGABRT crash error in Swift', 'mobile', 'HIGH', '[{"solution": "Check for force unwrapping AnyObject values without type checking", "percentage": 91}, {"solution": "Verify dictionary values are cast correctly", "percentage": 88}, {"solution": "Look for index out of range in collection access", "percentage": 86}]'::jsonb, 'Type casting and collection handling', 'No SIGABRT crash on value access', 'Unsafe type conversions from AnyObject', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/50447645/getting-thread-1-signal-sigabrt-crash-error-in-swift', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift SwiftUI iOS: Cannot convert value of type Binding<AVPlayer> to expected', 'mobile', 'HIGH', '[{"solution": "Use @State property wrapper for AVPlayer instead of Binding", "percentage": 92}, {"solution": "Convert between Binding and State with proper syntax", "percentage": 89}, {"solution": "Check SwiftUI view hierarchy for type mismatches", "percentage": 87}]'::jsonb, 'SwiftUI property wrappers (@State, @Binding)', 'Type conversion succeeds, view compiles', 'Confusing @State with @Binding for local state', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/75158327/swift-swiftui-ios-cannot-convert-value-of-type-bindingavplayer-to-expecte', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift closure: cannot convert value of type Bool to expected argument type', 'mobile', 'HIGH', '[{"solution": "Return appropriate type from closure body", "percentage": 94}, {"solution": "Use implicit return for single-statement closures", "percentage": 91}, {"solution": "Check function signature for expected return type", "percentage": 89}]'::jsonb, 'Closure syntax and type inference', 'Closure returns correct type', 'Wrong return type or missing explicit return', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/37774822/swift-closure-cannot-convert-value-of-type-bool-to-expected-argument-t', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift generics: cannot convert value to type', 'mobile', 'HIGH', '[{"solution": "Ensure generic type constraint is met by actual type", "percentage": 93}, {"solution": "Use Codable protocol conformance for Decodable types", "percentage": 90}, {"solution": "Check type bounds in generic declaration", "percentage": 88}]'::jsonb, 'Swift generics and type constraints', 'Generic type resolves correctly', 'Type not conforming to generic constraint', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/62486095/swift-generics-cannot-convert-value-to-type', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift Xcode error: cannot convert value of type', 'mobile', 'HIGH', '[{"solution": "Check actual vs expected type in error message", "percentage": 95}, {"solution": "Cast value to expected type: as? or as!", "percentage": 92}, {"solution": "Modify variable type annotation to match", "percentage": 89}]'::jsonb, 'Type system and casting in Swift', 'Type conversion succeeds', 'Mismatched types in assignment', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/44688699/swift-xcode-error-cannot-convert-value-of-type', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('iOS error: cannot convert value of type UserModel to expected argument type', 'mobile', 'HIGH', '[{"solution": "Cast dictionary to correct type: [String: UserModel]", "percentage": 91}, {"solution": "Check JSON decoding produces correct type", "percentage": 88}, {"solution": "Verify type in function parameter vs actual argument", "percentage": 86}]'::jsonb, 'Type inference and JSON decoding', 'Type matches parameter requirement', 'Type mismatch between JSON and model', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/73876760/ios-error-cannot-convert-value-of-type-usermodel-to-expected-argument-type', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift: cannot convert value of type Int16 to expected argument type AnyObject', 'mobile', 'HIGH', '[{"solution": "Wrap Int16 in NSNumber for Core Data storage", "percentage": 93}, {"solution": "Use setValue(_:forKey:) with NSNumber wrapper", "percentage": 90}, {"solution": "Cast Int16 to NSNumber explicitly", "percentage": 88}]'::jsonb, 'Core Data and NSObject interop', 'Value stores in Core Data correctly', 'Not wrapping Swift types in NSNumber for Core Data', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/38686279/swift-cannot-convert-value-of-type-int16-to-expected-argument-type-anyobject', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Cannot convert value of type String to expected argument type Int64 Swift iOS', 'mobile', 'HIGH', '[{"solution": "Use Int(string) to convert String to Int64", "percentage": 94}, {"solution": "Check text field value is not nil before conversion", "percentage": 91}, {"solution": "Provide fallback value with nil-coalescing operator", "percentage": 89}]'::jsonb, 'String to number conversion in Swift', 'String successfully converts to Int64', 'Not checking for nil or non-numeric strings', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/49606290/cannot-convert-value-of-type-string-to-expected-argument-type-int64-swift-i', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift: cannot convert value of type to expected argument type C', 'mobile', 'HIGH', '[{"solution": "Use inout parameter correctly, don''t pass immutable values", "percentage": 92}, {"solution": "Make variable mutable with var before passing to inout function", "percentage": 89}, {"solution": "Check function signature for inout parameter requirements", "percentage": 87}]'::jsonb, 'Swift inout parameters', 'Inout parameter receives mutable value', 'Passing immutable values to inout parameters', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/47069360/swift-cannot-convert-value-of-type-to-expected-argument-type-c', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Use of unresolved identifier in Swift', 'mobile', 'HIGH', '[{"solution": "Check Target Membership in File Inspector is correct", "percentage": 93}, {"solution": "Ensure class inherits from correct parent if using framework", "percentage": 90}, {"solution": "Verify import statement for required module", "percentage": 88}]'::jsonb, 'Xcode project configuration', 'Identifier resolves and compiles', 'Missing target membership or wrong class inheritance', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/28996730/use-of-unresolved-identifier-in-swift', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift: use of unresolved identifier', 'mobile', 'HIGH', '[{"solution": "Check Target Membership checkbox for source file", "percentage": 94}, {"solution": "Verify class name matches in usage and definition", "percentage": 91}, {"solution": "Check for typos in class or variable names", "percentage": 89}]'::jsonb, 'Swift module and target concepts', 'Identifier found and compiler recognizes', 'File not in correct target, typos in names', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/34950777/swift-use-of-unresolved-identifier', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Use of unresolved identifier ''class'' with Swift', 'mobile', 'HIGH', '[{"solution": "Import the module containing the class: import ClassName", "percentage": 95}, {"solution": "Check class is public in framework, not internal", "percentage": 92}, {"solution": "Verify custom framework is properly linked", "percentage": 89}]'::jsonb, 'Swift modules and public/private visibility', 'Class imports successfully and is recognized', 'Class is internal and not exported from module', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/43960260/use-of-unresolved-identifier-class-with-swift', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Use of unresolved identifier ''present'' in Swift Apple tutorial', 'mobile', 'HIGH', '[{"solution": "Ensure class inherits from UIViewController", "percentage": 94}, {"solution": "Use present(_:animated:completion:) method correctly", "percentage": 91}, {"solution": "Check self is a view controller instance", "percentage": 89}]'::jsonb, 'UIViewController and navigation methods', 'present method available and callable', 'Not inheriting from UIViewController', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/41537168/use-of-unresolved-identifier-present-in-swift-apple-tutorial', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift compiler error: use of unresolved identifier name', 'mobile', 'HIGH', '[{"solution": "Check variable is in scope when used", "percentage": 93}, {"solution": "Verify variable is declared before use", "percentage": 90}, {"solution": "Check spelling matches declaration exactly", "percentage": 88}]'::jsonb, 'Swift variable scope rules', 'Variable in scope and accessible', 'Variable declared in wrong scope or misspelled', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/26099111/swift-compiler-error-use-of-unresolved-identifier-name', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift: importing custom framework use of unresolved identifier', 'mobile', 'HIGH', '[{"solution": "Add framework to Build Phases > Link Binary With Libraries", "percentage": 95}, {"solution": "Ensure exported type is public in framework", "percentage": 92}, {"solution": "Import framework at top of file: import FrameworkName", "percentage": 90}]'::jsonb, 'Framework creation and linking in Xcode', 'Framework import works, types resolve', 'Framework not linked or classes not public', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/30284858/swift-importing-custom-framework-use-of-unresolved-identifier', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Xcode 8.2 Swift 3 Core Data: use unresolved identifier', 'mobile', 'HIGH', '[{"solution": "Ensure Core Data entity is declared as public class", "percentage": 92}, {"solution": "Regenerate Core Data entity classes with editor", "percentage": 89}, {"solution": "Check import Foundation and CoreData statements", "percentage": 87}]'::jsonb, 'Core Data and Swift 3 migration', 'Entity accessible in code', 'Entity not public or not regenerated after changes', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/41696065/xcode-8-2-swift-3-core-data-use-unresolved-identifier', 'admin:1764223900');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Swift Playground: use of unresolved identifier MyClass but still compiles', 'mobile', 'HIGH', '[{"solution": "Classes must be defined before use in playgrounds", "percentage": 91}, {"solution": "Put all helper classes at top of playground file", "percentage": 88}, {"solution": "Check code execution order in playground", "percentage": 86}]'::jsonb, 'Swift Playground execution model', 'Class available and code runs correctly', 'Defining classes after use in playground', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/42728404/swift-playground-use-of-unresolved-identifier-myclass-but-still-compiles', 'admin:1764223900');
