-- Preact Errors Mining - 10 entries
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Objects are not valid as a child - async component returns Promise', 'preact', 'HIGH', '[{"solution": "Component function returns Promise instead of JSX. Use useEffect for async operations instead of async component function", "percentage": 95}, {"solution": "Preact render is synchronous - wrap async logic in useEffect hook", "percentage": 90}]'::jsonb, 'Preact/Hooks knowledge', 'Component renders without Objects error', 'Using async/await in component function body', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/63970864/preact-error-objects-are-not-valid-as-a-child-encountered-an-object-with-the', 'admin:1764210632'),

('ReferenceError: h is not defined with preact/compat', 'preact', 'HIGH', '[{"solution": "Add ''import {h} from ''''preact'''';'' to component files explicitly", "percentage": 85}, {"solution": "Configure Babel with automatic runtime: add runtime:''''automatic'''' and importSource:''''preact'''' to JSX plugin", "percentage": 92}, {"solution": "Use @babel/plugin-transform-react-jsx with pragma and pragmaFrag set to h and Fragment", "percentage": 88}]'::jsonb, 'Babel configured, preact/compat installed', 'No ReferenceError on component render', 'Not importing h when using JSX in preact/compat', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/61823598/preact-compat-in-preactx-referenceerror-h-is-not-defined', 'admin:1764210632'),

('Cannot read properties of undefined (reading ''''__H'''') - Hooks conflict in React/Preact widget', 'preact', 'MEDIUM', '[{"solution": "Preact Hooks instance conflict when widget loaded in React app. Ensure preact is single instance or use preact/compat exclusively", "percentage": 85}, {"solution": "Use preact-compat for all components when mixing with React apps", "percentage": 80}]'::jsonb, 'TypeScript/JSX compilation, multiple frameworks', 'Widget loads without hook-related errors', 'Multiple Preact instances or mixing direct preact with preact/compat', 0.78, 'haiku', NOW(), 'https://stackoverflow.com/questions/72068464/invalid-hooks-call-when-using-widget-built-with-preact-inside-react-app', 'admin:1764210632'),

('TypeError: createContext is not a function - styled-components with preact 8.x', 'preact', 'MEDIUM', '[{"solution": "createContext API not supported in Preact 8.x. Upgrade to Preact 10+", "percentage": 96}, {"solution": "Downgrade styled-components from v4 to v3 for Preact 8.x compatibility", "percentage": 85}]'::jsonb, 'styled-components and preact installed', 'styled-components imports without error', 'Using Preact 8 with styled-components v4+', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/54218013/preact-with-styled-components-causes-error-in-browser-console', 'admin:1764210632'),

('Console errors not showing in development after preact upgrade', 'preact', 'MEDIUM', '[{"solution": "Old window.addEventListener(''''error'''') listener suppresses preact/debug errors. Remove competing error listeners", "percentage": 94}, {"solution": "Ensure preact/debug is imported for development mode", "percentage": 88}]'::jsonb, 'preact/debug import, event listeners setup', 'JS errors visible in browser console', 'Conflicting error event listeners, old webpack plugins', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/63016813/debug-is-not-working-propely-after-upgrading-preact-version', 'admin:1764210632'),

('JSX undefined with HOC after switching to preact-compat', 'preact', 'MEDIUM', '[{"solution": "Add webpack resolve alias for react, react-dom, create-react-class, react-dom-factories to preact/compat", "percentage": 90}, {"solution": "Do not compile JSX to React createElement calls - use babel pragma: h", "percentage": 85}]'::jsonb, 'Webpack config, babel setup', 'HOC renders without undefined component name', 'Missing webpack resolve aliases, incorrect babel config', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/54580228/error-with-jsx-in-my-react-library-when-switching-to-preact', 'admin:1764210632'),

('Cannot find module react/jsx-runtime with preact alias', 'preact', 'MEDIUM', '[{"solution": "Use ''preact/compat'' instead of ''preact-compat'' in webpack resolve alias", "percentage": 96}, {"solution": "Ensure TypeScript jsx option is set to ''react-jsx'' and babel has automatic runtime configured", "percentage": 88}]'::jsonb, 'Webpack, TypeScript, Babel configured', 'Build succeeds without jsx-runtime error', 'Outdated migration docs using preact-compat path', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/66963248/aliasing-react-as-preact-throws-cannot-find-module-react-jsx-runtime', 'admin:1764210632'),

('Type ''''Element'''' is not assignable to type ''''ReactNode'''' - framer-motion with Preact', 'preact', 'MEDIUM', '[{"solution": "Remove @types/react from dependencies when using Preact", "percentage": 92}, {"solution": "Add tsconfig.json paths to alias react and react-dom to preact/compat", "percentage": 89}]'::jsonb, 'TypeScript, framer-motion, preact', 'framer-motion motion components render without TS errors', '@types/react installed alongside Preact', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/72271286/preact-children-in-framer-motion-causing-typing-errors', 'admin:1764210632'),

('Cannot find module ''''react'''' - third-party package requires React with Preact', 'preact', 'HIGH', '[{"solution": "Package dependencies require React but not aliased. Use webpack resolve alias or astro integration compat mode", "percentage": 85}, {"solution": "For Astro: enable compat mode in @astrojs/preact config", "percentage": 92}]'::jsonb, 'Build system (webpack/vite/astro), third-party deps', 'Build succeeds without missing react module error', 'Not aliasing react in bundler config, compat mode not enabled', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/76346895/using-preact-but-module-requires-react-failing-to-deploy', 'admin:1764210632'),

('JSX Runtime mismatch - Babel automatic runtime with preact/compat', 'preact', 'MEDIUM', '[{"solution": "Configure Babel with importSource: ''preact'' and runtime: ''automatic''", "percentage": 93}, {"solution": "Use @babel/preset-react v7.17+ with automatic runtime mode", "percentage": 89}]'::jsonb, 'Babel 7.9+, React 17+ JSX transform', 'Components compile without jsx pragma errors', 'Using old Babel JSX transform without automatic runtime config', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/61823598/preact-compat-in-preactx-referenceerror-h-is-not-defined', 'admin:1764210632');
