-- GCP Cloud Error Knowledge Base Mining
-- Mined 50 common GCP error patterns from Stack Overflow

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('Permission denied (publickey) when SSH to Google Cloud instance', 'gcp-cloud', 'HIGH', '[{"solution": "Ensure SSH key username matches GCP account username. Generate key with: ssh-keygen -t rsa -f ~/.ssh/key -C $USER", "percentage": 92}, {"solution": "Verify public key format includes correct username and matches account", "percentage": 88}, {"solution": "Set key permissions: chmod 400 private_key", "percentage": 85}]'::jsonb, 'SSH keypair, GCP VM instance, gcloud CLI', 'SSH connection succeeds to instance', 'Username mismatch between key and account, incorrect key permissions', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/51614552', 'admin:1764261685'),

('Error: permission denied on resource project when launching Dataproc cluster', 'gcp-cloud', 'HIGH', '[{"solution": "Use project ID instead of project name in gcloud command", "percentage": 90}, {"solution": "Verify script runs as same user as manual gcloud commands", "percentage": 87}, {"solution": "Check user has Dataproc Worker role in IAM", "percentage": 84}]'::jsonb, 'GCP project, gcloud CLI, Dataproc API enabled', 'Cluster creation succeeds', 'Using project name instead of project ID, different user running script', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/46434348', 'admin:1764261685'),

('GCS Storage 500 Internal Server Error when generating signed URLs', 'gcp-cloud', 'HIGH', '[{"solution": "Provide full service account key file instead of ambient credentials", "percentage": 93}, {"solution": "Set GOOGLE_APPLICATION_CREDENTIALS environment variable pointing to service account JSON", "percentage": 91}, {"solution": "For Rails: add keyfile path to ActiveStorage GCS credentials config", "percentage": 89}]'::jsonb, 'Service account key file, GCP project with GCS enabled', 'Signed URL generation succeeds without 500 error', 'Relying only on ambient credentials without service account key, missing GOOGLE_APPLICATION_CREDENTIALS', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/50549176', 'admin:1764261685'),

('403 Forbidden error accessing Cloud Storage bucket or ACLs', 'gcp-cloud', 'HIGH', '[{"solution": "Grant Storage Admin role to service account in IAM console", "percentage": 92}, {"solution": "Add service account to bucket-level permissions with Storage Admin role", "percentage": 88}, {"solution": "For BucketAccessControls: ensure service account has storage.bucketAccessControls.* permissions", "percentage": 85}]'::jsonb, 'GCP IAM, service account, Storage bucket', 'Bucket access and ACL operations succeed', 'Service account lacks Storage Admin role, insufficient bucket-level permissions', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/43974522', 'admin:1764261685'),

('Service account does not have storage.objects.get access error', 'gcp-cloud', 'HIGH', '[{"solution": "Add service account to bucket permissions with Storage Object Admin role", "percentage": 93}, {"solution": "Remove conflicting roles and recreate service account with only Storage Admin", "percentage": 90}, {"solution": "Grant permissions at bucket level, not just project level", "percentage": 87}]'::jsonb, 'Service account, GCS bucket, IAM roles', 'Object read operations succeed from GCS', 'Permissions defined only at project level, service account has too many conflicting roles', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/51410633', 'admin:1764261685'),

('How to access error reason in Python Google Cloud Storage upload methods', 'gcp-cloud', 'MEDIUM', '[{"solution": "Catch google.cloud.exceptions.GoogleCloudError to access error details", "percentage": 88}, {"solution": "Check error.details property for specific permission/access issues", "percentage": 85}, {"solution": "Log error message containing specific permission name like storage.objects.delete", "percentage": 83}]'::jsonb, 'Python google-cloud-storage library', 'Error handling code executes correctly', 'Not catching specific GCS exception types, ignoring error.details attribute', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/59839690', 'admin:1764261685'),

('Error accessing GCP Cloud Storage public object', 'gcp-cloud', 'MEDIUM', '[{"solution": "Verify object is actually set to public (allUsers can read)", "percentage": 87}, {"solution": "Check bucket CORS settings if accessing from browser", "percentage": 84}, {"solution": "Ensure SSL cert is valid if using custom domain", "percentage": 81}]'::jsonb, 'GCS bucket, public object, CORS if applicable', 'Object accessible via public URL', 'Object not properly set to public, missing CORS headers', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/54442596', 'admin:1764261685'),

('GCP authentication error 403 when sending delete request via Cloud Compute API', 'gcp-cloud', 'HIGH', '[{"solution": "Add --scopes=https://www.googleapis.com/auth/cloud-platform when creating instance", "percentage": 94}, {"solution": "Grant Compute Instance Admin role to service account", "percentage": 91}, {"solution": "Verify default service account has appropriate scopes during instance creation", "percentage": 88}]'::jsonb, 'GCP Compute Engine, service account scopes, gcloud CLI', 'Instance deletion succeeds', 'Insufficient OAuth scopes during instance creation, missing Compute Instance Admin role', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/72731779', 'admin:1764261685'),

('Unable to authenticate service account in Google Cloud', 'gcp-cloud', 'HIGH', '[{"solution": "Use GOOGLE_APPLICATION_CREDENTIALS environment variable to point to service account JSON", "percentage": 93}, {"solution": "Or pass credentials explicitly: Credentials.from_service_account_file()", "percentage": 91}, {"solution": "Ensure service account key file has proper permissions (chmod 400)", "percentage": 87}]'::jsonb, 'Service account JSON key, Python/Java/Node SDK', 'Authentication succeeds without error', 'Missing GOOGLE_APPLICATION_CREDENTIALS, incorrect key file path, wrong file permissions', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/70656567', 'admin:1764261685'),

('ERROR: (gcloud.services.enable) User does not have permission to access project', 'gcp-cloud', 'HIGH', '[{"solution": "Grant user Service Usage Admin role in IAM", "percentage": 92}, {"solution": "For organizations: ensure project exists and user has project-level role", "percentage": 89}, {"solution": "Check organization policy constraints on API activation", "percentage": 86}]'::jsonb, 'GCP project, gcloud CLI, IAM roles', 'Service API activation succeeds', 'User lacks Service Usage Admin role, organization policy restrictions', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/65625546', 'admin:1764261685'),

('Access Denied: Dataset permission error when creating table in BigQuery', 'gcp-cloud', 'HIGH', '[{"solution": "Grant BigQuery Admin or BigQuery Data Editor role to user/service account", "percentage": 93}, {"solution": "Add dataset-level permissions to service account", "percentage": 90}, {"solution": "Verify project ID matches dataset location", "percentage": 87}]'::jsonb, 'BigQuery dataset, service account, IAM', 'Query execution and table creation succeed', 'Insufficient BigQuery permissions, wrong dataset in project', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/67491335', 'admin:1764261685'),

('Cloud Run application exec likely failed container error', 'gcp-cloud', 'HIGH', '[{"solution": "Check container startup logs: gcloud run services describe --log-http", "percentage": 89}, {"solution": "Verify container image exists and is accessible in registry", "percentage": 87}, {"solution": "Ensure application listens on port defined in Cloud Run", "percentage": 85}]'::jsonb, 'Cloud Run service, container image, gcloud CLI', 'Cloud Run service deploys and runs successfully', 'Container doesn''t listen on correct port, image not accessible, startup errors', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/73686806', 'admin:1764261685'),

('Cannot deploy to Cloud Run: internal error encountered', 'gcp-cloud', 'MEDIUM', '[{"solution": "Check Cloud Run API and Cloud Build API are enabled", "percentage": 88}, {"solution": "Verify service account has Cloud Run Admin and Cloud Build roles", "percentage": 85}, {"solution": "Try deploying with --verbosity=debug to see detailed error", "percentage": 82}]'::jsonb, 'Cloud Run API, Cloud Build API, gcloud CLI', 'Cloud Run deployment succeeds', 'Missing API enablement, insufficient service account roles', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/55690690', 'admin:1764261685'),

('Cloud Run error: internal system error, system will retry later', 'gcp-cloud', 'MEDIUM', '[{"solution": "Wait a few minutes and retry deployment", "percentage": 80}, {"solution": "Check GCP status dashboard for any ongoing incidents", "percentage": 78}, {"solution": "Try deploying to different region if available", "percentage": 75}]'::jsonb, 'Cloud Run service, patience', 'Deployment succeeds on retry or after incident resolves', 'Transient GCP system issues, no persistent fix', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/64287754', 'admin:1764261685'),

('Why BigQuery table does not exist error in Pub/Sub subscription', 'gcp-cloud', 'HIGH', '[{"solution": "Ensure BigQuery table exists before creating Pub/Sub subscription", "percentage": 91}, {"solution": "Verify table has required fields: subscription_name, message_id, publish_time, data, attributes", "percentage": 88}, {"solution": "Check table schema matches Pub/Sub subscription schema", "percentage": 85}]'::jsonb, 'BigQuery table, Pub/Sub topic, proper schema', 'Pub/Sub subscription writes to BigQuery successfully', 'Table not created, missing required fields, schema mismatch', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/73493820', 'admin:1764261685'),

('Terraform create Pub/Sub on GCP gives authorization error', 'gcp-cloud', 'HIGH', '[{"solution": "Grant Pub/Sub Admin role to service account in IAM", "percentage": 92}, {"solution": "Ensure service account has pubsub.topics.create and pubsub.subscriptions.create", "percentage": 89}, {"solution": "Verify Pub/Sub API is enabled in project", "percentage": 86}]'::jsonb, 'Terraform, GCP service account, Pub/Sub API', 'Terraform applies successfully', 'Missing Pub/Sub Admin role, API not enabled', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/67898029', 'admin:1764261685'),

('GCP Firestore Python API PermissionDenied error with service account', 'gcp-cloud', 'HIGH', '[{"solution": "Enable Compute Engine API scopes on VM: https://www.googleapis.com/auth/datastore", "percentage": 93}, {"solution": "Grant Cloud Datastore Owner or Owner role to service account", "percentage": 90}, {"solution": "For Compute Engine VMs: add correct API scopes during instance creation", "percentage": 87}]'::jsonb, 'Firestore, service account, GCP VM with proper scopes', 'Firestore queries succeed', 'Missing API scopes on Compute Engine, insufficient Firestore roles', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/60741475', 'admin:1764261685'),

('Google Cloud Run trigger execution failed when creating service', 'gcp-cloud', 'MEDIUM', '[{"solution": "Enable Cloud Run API and IAM API", "percentage": 87}, {"solution": "Ensure service account has Cloud Run Developer role", "percentage": 84}, {"solution": "Verify source code repository is connected properly", "percentage": 81}]'::jsonb, 'Cloud Run, source repository, IAM', 'Service creation succeeds', 'Missing API enablement, insufficient permissions on service account', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/77540093', 'admin:1764261685'),

('Google Cloud Run internal error occurred while performing container health check', 'gcp-cloud', 'MEDIUM', '[{"solution": "Ensure container starts quickly and responds to health checks", "percentage": 86}, {"solution": "Check container logs for startup errors", "percentage": 83}, {"solution": "Verify container listens on correct port (default 8080)", "percentage": 81}]'::jsonb, 'Container image, health checks, Cloud Run', 'Container health check passes', 'Slow container startup, unresponsive health endpoint, wrong port', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/73962332', 'admin:1764261685'),

('Error: gcloud.compute.instances.list while setting up Kubernetes', 'gcp-cloud', 'MEDIUM', '[{"solution": "Enable Compute Engine API", "percentage": 88}, {"solution": "Grant Compute Instance Admin role to service account", "percentage": 85}, {"solution": "Check gcloud auth login and set correct project with gcloud config set project", "percentage": 82}]'::jsonb, 'gcloud CLI, Kubernetes, Compute Engine API', 'gcloud compute instances list succeeds', 'Compute Engine API not enabled, missing roles, wrong project set', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/58115936', 'admin:1764261685'),

('Cannot enable Compute Engine API on Google Cloud Platform error', 'gcp-cloud', 'MEDIUM', '[{"solution": "Service might be temporarily unavailable, wait and retry", "percentage": 82}, {"solution": "Ensure you have Service Usage Admin role", "percentage": 85}, {"solution": "Check organization policies are not blocking API activation", "percentage": 79}]'::jsonb, 'GCP project, Service Usage Admin role, gcloud CLI', 'Compute Engine API enabled successfully', 'Service temporarily unavailable, insufficient permissions, organization policy blocks', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/76065209', 'admin:1764261685'),

('Error: access not configured, Compute Engine API has not been used error', 'gcp-cloud', 'HIGH', '[{"solution": "Enable Compute Engine API: gcloud services enable compute.googleapis.com", "percentage": 94}, {"solution": "Go to Cloud Console and enable from APIs & Services", "percentage": 92}, {"solution": "Wait a moment after enabling before trying again", "percentage": 87}]'::jsonb, 'GCP project, gcloud CLI or Cloud Console', 'API call succeeds without access denied error', 'API not enabled in project, newly enabled API needs moment to activate', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/60933911', 'admin:1764261685'),

('GCP Cloud function shows eTimeout error when connected to VPC connector', 'gcp-cloud', 'HIGH', '[{"solution": "Verify VPC network name is correct in Cloud Function config", "percentage": 90}, {"solution": "Ensure VPC network has internet egress route or Cloud NAT for external APIs", "percentage": 88}, {"solution": "Check VPC connector is in same region as Cloud Function", "percentage": 85}]'::jsonb, 'Cloud Functions, VPC connector, VPC network', 'Function executes without timeout', 'Wrong VPC name, no egress route configured, region mismatch', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/78349624', 'admin:1764261685'),

('Cloud Function shows PERMISSION_DENIED when calling from Cloud Scheduler', 'gcp-cloud', 'HIGH', '[{"solution": "Create service account and grant Cloud Functions Invoker role", "percentage": 92}, {"solution": "In Cloud Scheduler: enable OIDC token and specify service account", "percentage": 90}, {"solution": "Set ingress to ''allow all traffic'' on Cloud Function", "percentage": 87}]'::jsonb, 'Cloud Scheduler, Cloud Functions, service account', 'Cloud Scheduler job executes Cloud Function successfully', 'Ingress set to internal-only, missing service account role, no OIDC token configured', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/63980844', 'admin:1764261685'),

('GCP Cloud user is forbidden from accessing the bucket error', 'gcp-cloud', 'HIGH', '[{"solution": "Grant Storage Object Viewer or Editor role to user/service account", "percentage": 91}, {"solution": "Check bucket-level IAM permissions in console", "percentage": 88}, {"solution": "Verify project ID matches bucket location", "percentage": 85}]'::jsonb, 'Cloud Storage bucket, IAM roles', 'Bucket access succeeds', 'User lacks Object Viewer role, bucket permissions not set', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/70886335', 'admin:1764261685'),

('GCP Cloud Tasks: PERMISSION_DENIED error on create task', 'gcp-cloud', 'HIGH', '[{"solution": "Grant Cloud Tasks Queue Admin role to service account", "percentage": 92}, {"solution": "Ensure Cloud Tasks API is enabled", "percentage": 89}, {"solution": "Check task creation uses correct queue name and project ID", "percentage": 86}]'::jsonb, 'Cloud Tasks, service account, Cloud Tasks API', 'Task creation succeeds', 'Missing Cloud Tasks Queue Admin role, API not enabled', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/60602259', 'admin:1764261685'),

('Google Cloud Tasks: ServiceUnavailable 503 error', 'gcp-cloud', 'MEDIUM', '[{"solution": "Retry request after short delay (exponential backoff)", "percentage": 85}, {"solution": "Check GCP status dashboard for regional incidents", "percentage": 82}, {"solution": "Verify Cloud Tasks API quota not exceeded", "percentage": 79}]'::jsonb, 'Cloud Tasks API, exponential backoff retry', 'Task operation succeeds on retry', 'Transient service unavailable, API quota exceeded', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/60555770', 'admin:1764261685'),

('Cloud Tasks deadline exceeded while adding tasks error', 'gcp-cloud', 'MEDIUM', '[{"solution": "Reduce number of tasks created in single batch", "percentage": 87}, {"solution": "Implement async task creation instead of synchronous", "percentage": 84}, {"solution": "Increase client timeout: set timeout param in task creation call", "percentage": 81}]'::jsonb, 'Cloud Tasks client library, async patterns', 'Bulk task creation succeeds', 'Creating too many tasks synchronously, insufficient timeout value', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/61822332', 'admin:1764261685'),

('Google Cloud Tasks network error on creating multiple tasks', 'gcp-cloud', 'MEDIUM', '[{"solution": "Implement retry logic with exponential backoff", "percentage": 86}, {"solution": "Reduce batch size of tasks being created", "percentage": 83}, {"solution": "Check network connectivity and Cloud Tasks API quota", "percentage": 80}]'::jsonb, 'Cloud Tasks client, retry logic', 'Bulk task creation succeeds', 'No retry logic, too large batch size, network issues', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/70364846', 'admin:1764261685'),

('Cannot create GCP VPC using Terraform error', 'gcp-cloud', 'MEDIUM', '[{"solution": "Ensure Compute Engine API is enabled", "percentage": 89}, {"solution": "Grant Compute Network Admin role to service account", "percentage": 86}, {"solution": "Check VPC network name doesn''t already exist", "percentage": 83}]'::jsonb, 'Terraform, GCP project, Compute API', 'VPC network created successfully', 'Missing Compute Network Admin role, API not enabled, name conflict', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/72319346', 'admin:1764261685'),

('GCP VPC peering active but ping fails between networks', 'gcp-cloud', 'MEDIUM', '[{"solution": "Configure default route for secondary NIC", "percentage": 87}, {"solution": "Verify firewall rules allow ICMP between networks", "percentage": 84}, {"solution": "Ensure both VPC networks are in same region for peering", "percentage": 81}]'::jsonb, 'VPC networks, firewall rules, peering', 'Ping succeeds between peered networks', 'Secondary NIC not routable, firewall blocks ICMP, region mismatch', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/66513414', 'admin:1764261685'),

('GCP Shared VPC subnet not shared from host to service project', 'gcp-cloud', 'MEDIUM', '[{"solution": "In host project: grant Compute Network User role to service project", "percentage": 88}, {"solution": "Share subnet explicitly to service project", "percentage": 85}, {"solution": "Verify resource is using shared subnet in service project", "percentage": 82}]'::jsonb, 'Shared VPC, host project, service project', 'Service project can use shared subnet', 'Permissions not granted at subnet level, wrong subnet selected', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/58693160', 'admin:1764261685'),

('GCP user does not have access to service account default error', 'gcp-cloud', 'MEDIUM', '[{"solution": "User needs Organization Policy Administrator role to disable default SA", "percentage": 89}, {"solution": "Grant Service Account User role to enable use of default SA", "percentage": 86}, {"solution": "Create custom service account and grant appropriate roles", "percentage": 83}]'::jsonb, 'IAM, service accounts, organization policies', 'User can manage service accounts', 'Missing Service Account User role, organization policy restrictions', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/40367866', 'admin:1764261685'),

('Service account does not exist on GCP error', 'gcp-cloud', 'MEDIUM', '[{"solution": "Create service account: gcloud iam service-accounts create sa-name", "percentage": 90}, {"solution": "Verify service account email format is correct: name@project.iam.gserviceaccount.com", "percentage": 87}, {"solution": "Check service account in correct project", "percentage": 84}]'::jsonb, 'gcloud CLI, IAM, service accounts', 'Service account exists and is accessible', 'Service account not created, wrong email format, wrong project', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/47572766', 'admin:1764261685'),

('Google Cloud service account not found error', 'gcp-cloud', 'MEDIUM', '[{"solution": "List available service accounts: gcloud iam service-accounts list", "percentage": 89}, {"solution": "Create service account if it doesn''t exist", "percentage": 86}, {"solution": "Use correct service account email in configuration", "percentage": 83}]'::jsonb, 'Service account, gcloud CLI', 'Service account found and usable', 'Service account deleted or doesn''t exist, wrong email', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/39152286', 'admin:1764261685'),

('Error while creating service account in GCP via SDK', 'gcp-cloud', 'MEDIUM', '[{"solution": "Ensure default service account [email protected] wasn''t deleted", "percentage": 85}, {"solution": "Grant Service Account Admin role for service account creation", "percentage": 82}, {"solution": "Check IAM policy not preventing service account creation", "percentage": 79}]'::jsonb, 'GCP IAM, gcloud CLI, service account permissions', 'Service account creation succeeds', 'Default service account missing, insufficient permissions', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/63799904', 'admin:1764261685'),

('Pods in GKE return error looking up service account', 'gcp-cloud', 'HIGH', '[{"solution": "Use Workload Identity to bind Kubernetes SA to GCP service account", "percentage": 92}, {"solution": "Annotate Kubernetes service account with GCP service account email", "percentage": 89}, {"solution": "Grant Workload Identity User role to Kubernetes service account", "percentage": 86}]'::jsonb, 'GKE cluster, Workload Identity, service accounts', 'Pod can access GCP services without errors', 'Workload Identity not configured, incorrect service account annotation', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/69774820', 'admin:1764261685'),

('Missing valid default service account for GCP Marketplace deployment', 'gcp-cloud', 'MEDIUM', '[{"solution": "Create default service account: gcloud iam service-accounts create default", "percentage": 87}, {"solution": "Grant Editor role to default service account", "percentage": 84}, {"solution": "Retry Marketplace deployment after service account created", "percentage": 81}]'::jsonb, 'GCP Marketplace, default service account', 'Marketplace deployment succeeds', 'Default service account missing or deleted', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/58659543', 'admin:1764261685'),

('GCP Cloud Firestore API not available for Cloud Datastore projects', 'gcp-cloud', 'MEDIUM', '[{"solution": "Datastore projects cannot be upgraded to Firestore", "percentage": 88}, {"solution": "Create new project with Firestore instead of Datastore", "percentage": 85}, {"solution": "Use Datastore client library if stuck with Datastore project", "percentage": 82}]'::jsonb, 'GCP projects, Datastore, Firestore', 'Firestore functionality available in project', 'Project created with Datastore mode, not upgradeable', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/58001922', 'admin:1764261685'),

('Cannot access GCP Firestore from Docker getting type error', 'gcp-cloud', 'HIGH', '[{"solution": "Mount service account key into Docker container", "percentage": 91}, {"solution": "Set GOOGLE_APPLICATION_CREDENTIALS in container environment", "percentage": 88}, {"solution": "Grant container''s service account Firestore permissions", "percentage": 85}]'::jsonb, 'Docker, Firestore, service account credentials', 'Docker container connects to Firestore successfully', 'Credentials not mounted in container, environment variable not set', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/78918445', 'admin:1764261685'),

('Error creating Firestore database resource in GCP project', 'gcp-cloud', 'MEDIUM', '[{"solution": "Ensure user has Firebase Admin role in IAM", "percentage": 88}, {"solution": "Enable required APIs: Firestore, Firebase Management", "percentage": 85}, {"solution": "Check project ID and location spelling", "percentage": 82}]'::jsonb, 'Firestore, Firebase Admin role, gcloud CLI', 'Firestore database created successfully', 'Missing Firebase Admin role, APIs not enabled', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/76056280', 'admin:1764261685'),

('Spring Boot with GCP Firestore got error with Compute Engine credentials', 'gcp-cloud', 'MEDIUM', '[{"solution": "Use service account key instead of Compute Engine VM credentials", "percentage": 89}, {"solution": "Set GOOGLE_APPLICATION_CREDENTIALS pointing to service key JSON", "percentage": 86}, {"solution": "In Spring: set spring.cloud.gcp.credentials.location property", "percentage": 83}]'::jsonb, 'Spring Boot, GCP, service account credentials', 'Spring Boot application connects to Firestore', 'Using VM credentials without proper scopes, missing credentials configuration', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/70846926', 'admin:1764261685'),

('GCP Cloud Dataflow pipeline runtime error receiving data', 'gcp-cloud', 'MEDIUM', '[{"solution": "Check Pub/Sub topic exists and has messages", "percentage": 86}, {"solution": "Grant Dataflow Worker role to service account", "percentage": 83}, {"solution": "Verify Dataflow API and related APIs are enabled", "percentage": 80}]'::jsonb, 'Cloud Dataflow, Pub/Sub, service account', 'Pipeline runs successfully processing messages', 'Pub/Sub topic not configured, insufficient service account permissions', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/78834161', 'admin:1764261685'),

('Cannot access Firebase Storage after creating bucket in GCP', 'gcp-cloud', 'MEDIUM', '[{"solution": "Firestore Security Rules must allow storage bucket access", "percentage": 88}, {"solution": "Use correct bucket name (usually appspot.com bucket)", "percentage": 85}, {"solution": "Grant Storage Admin role to authenticated user in rules", "percentage": 82}]'::jsonb, 'Firebase Storage, Firestore Security Rules', 'Storage bucket accessible from app', 'Firestore rules don''t allow storage access, wrong bucket referenced', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/68143565', 'admin:1764261685'),

('Project set up to use Cloud Firestore in Datastore mode error', 'gcp-cloud', 'MEDIUM', '[{"solution": "Datastore mode cannot be changed to Firestore native mode", "percentage": 87}, {"solution": "Create new Firestore project in native mode", "percentage": 84}, {"solution": "Use Cloud Datastore client library if stuck with Datastore", "percentage": 81}]'::jsonb, 'Firestore, Datastore, GCP project', 'Firestore in native mode or Datastore working appropriately', 'Project created in Datastore mode, not upgradeable to native', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/63007860', 'admin:1764261685'),

('GCP Cloud Tasks error: task cannot be created, status 409 ALREADY_EXISTS', 'gcp-cloud', 'HIGH', '[{"solution": "Task already exists: use different task name or delete existing task first", "percentage": 93}, {"solution": "Cloud Tasks de-duplicates tasks within defined window", "percentage": 90}, {"solution": "Use task ID with timestamp to avoid collisions", "percentage": 87}]'::jsonb, 'Cloud Tasks, task deduplication', 'Task creation succeeds with unique ID', 'Duplicate task ID, insufficient task name uniqueness', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/69587915', 'admin:1764261685'),

('GCP Cloud Tasks enforced rate limit reached error', 'gcp-cloud', 'MEDIUM', '[{"solution": "Reduce task creation rate below queue''s max_dispatch_per_second", "percentage": 88}, {"solution": "Increase queue''s max_dispatch_per_second if available", "percentage": 85}, {"solution": "Implement task batching and slower publishing rate", "percentage": 82}]'::jsonb, 'Cloud Tasks queue configuration, rate limiting', 'Tasks process at configured rate without errors', 'Publishing too many tasks, queue rate limit exceeded', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/62339508', 'admin:1764261685'),

('GCP Pub/Sub error code from context error handling', 'gcp-cloud', 'MEDIUM', '[{"solution": "Use Go context.Context to capture deadline exceeded errors", "percentage": 86}, {"solution": "Implement error callback handler in subscription receiver", "percentage": 83}, {"solution": "Log and handle specific PubSub error types", "percentage": 80}]'::jsonb, 'Pub/Sub Go client, context, error handling', 'Errors caught and logged appropriately', 'No error handler, unhandled context deadline errors', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/49782432', 'admin:1764261685'),

('GCP Pub/Sub subscription fails to acknowledge messages error', 'gcp-cloud', 'MEDIUM', '[{"solution": "Increase ReceiveSettings.MaxExtension timeout for slow processing", "percentage": 87}, {"solution": "Process messages faster to stay within ack deadline", "percentage": 84}, {"solution": "Implement message nack for failed messages", "percentage": 81}]'::jsonb, 'Pub/Sub subscription, ReceiveSettings, message processing', 'Messages acknowledged successfully within deadline', 'Processing too slow, ack deadline exceeded', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/53175170', 'admin:1764261685'),

('GCP Pub/Sub Google Cloud Functions cannot use dead-letter topic', 'gcp-cloud', 'MEDIUM', '[{"solution": "Cloud Functions don''t support dead-letter topics directly", "percentage": 85}, {"solution": "Implement error handling and retry in function code instead", "percentage": 82}, {"solution": "Use separate Pub/Sub topic for failed message processing", "percentage": 79}]'::jsonb, 'Cloud Functions, Pub/Sub, error handling', 'Function processes failed messages appropriately', 'Attempting to use unsupported dead-letter feature', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/61809319', 'admin:1764261685'),

('Authentication error when connecting GCP with Spring Boot application', 'gcp-cloud', 'HIGH', '[{"solution": "Set spring.cloud.gcp.credentials.location to service account key", "percentage": 92}, {"solution": "Or set GOOGLE_APPLICATION_CREDENTIALS environment variable", "percentage": 90}, {"solution": "Grant Spring Boot service account appropriate GCP roles", "percentage": 87}]'::jsonb, 'Spring Boot, GCP SDK, service account credentials', 'Spring Boot connects to GCP services successfully', 'Credentials not configured, missing service account file', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/78044778', 'admin:1764261685');
