-- Angular Migration Errors Knowledge Base
-- Mined from Stack Overflow on 2025-11-26

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Upgrading large scale angular app from 6 to 17 third party libraries incompatibility', 'angular', 'HIGH', '[{"solution": "Do not upgrade version-by-version. Jump directly to target version (e.g., 6 to 17). Maintain backup of legacy code. Use hybrid routing approach where old system handles specific features while new system handles others. Identify deprecated dependencies beforehand and find replacements. Focus on stability before adding new features.", "percentage": 92}, {"solution": "If jumping seems risky, upgrade to Angular 12 first (relatively stable ecosystem period), then to 17. This is faster than upgrading through every intermediate version.", "percentage": 78}]'::jsonb, 'Large codebase with 50+ third-party dependencies, understanding of Angular ecosystem changes 2016-2023, automated test coverage', 'Project builds and runs without breaking changes. All deprecated libraries replaced with modern alternatives. Hybrid routing works correctly if implemented.', 'Attempting version-by-version upgrade on badly outdated projects (6+ versions behind). Including new features during migration. Not testing against live data. Not maintaining fallback to legacy system.', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/77325388/how-to-upgrade-badly-outdated-angular-project', 'admin:1764191836'),

('Angular 8 to 9 migration: Package @angular/material is already up to date but imports not fixed', 'angular', 'HIGH', '[{"solution": "Use ng update command instead of npm install. Run ng update @angular/core@9 @angular/cli@9 and ng update @angular/material@9. Rollback Angular 8 first if you manually installed v9. The ng update command triggers migration scripts that automatically fix imports.", "percentage": 95}, {"solution": "If using newer Angular versions, use command format: ng update @angular/core@11 @angular/cli@11 and ng update @angular/material@11 respectively.", "percentage": 88}]'::jsonb, 'Angular 8 project, npm and Angular CLI installed, material dependencies in package.json', 'ng update completes without errors. All Material imports automatically updated. Project runs and Material components display correctly. No import-related build errors.', 'Using npm install directly instead of ng update. Installing packages one-by-one manually. Already having v9 installed before running ng update. Not verifying package.json after migration.', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/77326181/migration-angular-8-to-9', 'admin:1764191836'),

('Angular 13 to 14 migration: CLI version mismatch error "This version of CLI is only compatible with Angular versions ^13.0.0"', 'angular', 'HIGH', '[{"solution": "Fix version mismatch by downgrading build tools to 13 first: npm i @angular-devkit/schematics@13 @schematics/angular@13. Then run: npm run ng update @angular/cli@14 @angular/core@14 using the project''s local CLI (not global). Let Angular CLI download compatible version automatically.", "percentage": 96}, {"solution": "Use the Official Angular Update Guide at https://angular.dev/update-guide. Select from/to versions and follow step-by-step instructions provided.", "percentage": 89}]'::jsonb, 'Angular 13 project, Node 18+, npm 10+, Angular CLI and core v13 initially installed', 'Angular CLI version matches Angular core version. ng version output shows consistent versioning. Project builds and runs without version compatibility errors.', 'Installing Angular CLI globally first. Not running update through project''s local CLI. Mixing v13 and v14 package versions. Not using npm run ng update syntax.', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/78816080/migrating-from-angular-version-13-to-version-14', 'admin:1764191836'),

('Migrating Angular 1.5 application to Angular 18: Complete rewrite vs incremental migration', 'angular', 'HIGH', '[{"solution": "Copying Angular 1.5 code directly into Angular 18 is NOT feasible. Angular 1.5 (AngularJS) and Angular 2+ (modern Angular) are fundamentally different frameworks. You MUST rewrite the code. Plan for complete redesign of components, services, and application architecture.", "percentage": 100}, {"solution": "If rewriting is unavoidable, consider using the upgrade module for incremental migration if still on Angular versions that support it. However, for 1.5 to 18 jump, full rewrite is the only viable path.", "percentage": 45}]'::jsonb, 'AngularJS 1.5 and Angular 18 knowledge, understanding of framework differences (controllers vs components, dependency injection syntax, module system)', 'New Angular 18 code compiles and runs. Original AngularJS functionality replicated in modern Angular patterns. Tests pass for migrated features.', 'Expecting minimal changes or one-to-one code copy. Not accounting for fundamental syntax differences between AngularJS and Angular 2+. Underestimating effort required for framework paradigm shift.', 0.30, 'haiku', NOW(), 'https://stackoverflow.com/questions/78450624/what-is-the-best-feasible-way-migrate-from-angular-1-5-to-angular-17', 'admin:1764191836'),

('Angular 15 to 16 migration: Avoiding standalone components while staying with module-based approach', 'angular', 'HIGH', '[{"solution": "No action needed. Standalone components are optional in Angular 16 and 17. Module-based components continue to work without changes. Standalone becomes default only in Angular 19+. To future-proof, set standalone: false in angular.json schematics config to ensure new components use modules.", "percentage": 98}, {"solution": "When upgrading to Angular 19+, add standalone: false to each component to maintain module-based approach. Consider gradually adopting standalone components for performance benefits in new features.", "percentage": 82}]'::jsonb, 'Angular 15 project with module-based components, angular.json configuration file, understanding of component declarations', 'Project upgrades to v16 without code changes required. Module-based components work identically. No deprecation warnings for module syntax. angular.json properly configured.', 'Forcing standalone migration before Angular 19. Not setting standalone: false in angular.json. Confusing optional vs mandatory features. Prematurely rewriting working module code.', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/79234340/migration-angular-15-to-16', 'admin:1764191836'),

('Angular v14 to v15 migration: Material v14 legacy modules not working after Angular Material upgrade to v15', 'angular', 'HIGH', '[{"solution": "Angular Material v15 requires Angular v15 due to peer dependencies. Update @angular/material to v15 simultaneously with Angular core. Add typography configuration to custom theme: @use ''@angular/material'' as mat; and include mat.define-typography-config() in theme definition. Legacy modules require proper typography setup in v15.", "percentage": 94}, {"solution": "Verify peer dependencies are satisfied: @angular/material v15 requires @angular/core ^15.0.0, @angular/common ^15.0.0, @angular/forms ^15.0.0, and @angular/cdk 15.x. All must be updated together.", "percentage": 91}]'::jsonb, 'Angular v14 project with Material v14, SCSS theme files, understanding of Material peer dependencies', 'Material components render correctly after v15 upgrade. UI no longer broken. Custom theme applies properly with typography. No peer dependency errors in npm output.', 'Using Angular Material v14 with Angular v15 (mismatched versions). Not adding typography to custom theme. Ignoring peer dependency requirements. Using old legacy modules without updating theme setup.', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/74992484/can-angular-v15-work-without-material-migration', 'admin:1764191836');
