INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('No Access-Control-Allow-Origin header present', 'web', 'HIGH', '[{"solution": "Add header to server response: Access-Control-Allow-Origin: * (or specific domain)", "percentage": 98}, {"solution": "For credentials requests, use specific origin instead of wildcard: Access-Control-Allow-Origin: https://example.com", "percentage": 95}]'::jsonb, 'Server-side code access', 'CORS request succeeds without error', 'Using wildcard (*) with credentials mode', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/72084470/how-to-solve-cors-error-while-fetching-an-external-api', 'admin:1764224036'),

('CORS header missing on non-200 response codes', 'web', 'HIGH', '[{"solution": "Send Access-Control-Allow-Origin header on error responses (401, 422, etc)", "percentage": 96}, {"solution": "Server must include CORS headers on ALL response codes, not just 200", "percentage": 94}]'::jsonb, 'Server-side error handling', 'Error response received with CORS headers', 'Only adding CORS headers for success responses', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/26695017/how-to-handle-running-into-cors-error-codes', 'admin:1764224036'),

('Preflight request fails with 403 Forbidden', 'web', 'MEDIUM', '[{"solution": "Ensure OPTIONS method is allowed: Access-Control-Allow-Methods: GET, POST, OPTIONS", "percentage": 94}, {"solution": "Remove conflicting request mapping that interferes with Spring CORS processor", "percentage": 85}]'::jsonb, 'OPTIONS request handling', 'Preflight request returns 200 OK', 'Custom request mapping overriding CORS configuration', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/41253228/preflight-or-cors-error-on-every-request', 'admin:1764224036'),

('Response for preflight is invalid (redirect)', 'web', 'MEDIUM', '[{"solution": "Add trailing slash to request URL: http://example.com/api/endpoint/ instead of /endpoint", "percentage": 92}, {"solution": "Ensure OPTIONS requests are not redirected - return 200 directly", "percentage": 90}]'::jsonb, 'Server redirect handling', 'Preflight OPTIONS request returns 200', 'Missing trailing slash causing 3xx redirect', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/42168773/how-to-resolve-preflight-is-invalid-redirect-or-redirect-is-not-allowed-for', 'admin:1764224036'),

('Cannot use wildcard in Access-Control-Allow-Origin with credentials', 'web', 'HIGH', '[{"solution": "Use specific origin instead of wildcard when credentials mode is include: Access-Control-Allow-Origin: https://example.com", "percentage": 97}, {"solution": "Set Access-Control-Allow-Credentials: true alongside specific origin", "percentage": 95}]'::jsonb, 'Credentials-based requests', 'Fetch with credentials succeeds without CORS error', 'Using * with withCredentials: true', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/19743396/cors-cannot-use-wildcard-in-access-control-allow-origin-when-credentials-flag-i', 'admin:1764224036'),

('Access-Control-Allow-Credentials header must be true for credentials requests', 'web', 'HIGH', '[{"solution": "Set Access-Control-Allow-Credentials: true in server response when using withCredentials: true", "percentage": 97}, {"solution": "Use cors middleware with credentials option: cors({credentials: true, origin: ''https://example.com''})", "percentage": 94}]'::jsonb, 'Requests with credentials', 'Fetch request with credentials works without error', 'Forgetting to set credentials: true in CORS middleware', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/57206675/how-to-fix-cors-error-with-credentials-include', 'admin:1764224036'),

('OPTIONS request returns 405 Method Not Allowed', 'web', 'MEDIUM', '[{"solution": "Explicitly handle OPTIONS requests in router: if(req.method === ''OPTIONS'') res.sendStatus(200)", "percentage": 96}, {"solution": "Add OPTIONS to Access-Control-Allow-Methods header", "percentage": 93}]'::jsonb, 'API server configuration', 'OPTIONS request accepted and returns 200', 'GraphQL or API server not handling OPTIONS method', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/48139612/405-method-not-allowed-despite-cors', 'admin:1764224036'),

('Access-Control-Allow-Methods does not include requested method', 'web', 'MEDIUM', '[{"solution": "Add missing method to Access-Control-Allow-Methods: POST,GET,PUT,DELETE,PATCH", "percentage": 96}, {"solution": "Verify allowed methods match actual request method being sent", "percentage": 94}]'::jsonb, 'HTTP method configuration', 'Request method allowed and succeeds', 'Typo in methods header (e.g., ''Method'' instead of ''Methods'')', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/31265580/cors-request-method-put-is-not-allowed-by-access-control-allow-methods', 'admin:1764224036'),

('Access-Control-Allow-Headers does not include custom header', 'web', 'MEDIUM', '[{"solution": "List all custom headers in Access-Control-Allow-Headers: Authorization, Content-Type, X-Custom-Header", "percentage": 97}, {"solution": "Use wildcard for headers when possible: Access-Control-Allow-Headers: *", "percentage": 85}]'::jsonb, 'Custom header handling', 'Preflight response includes all request headers', 'Forgetting to include application-specific headers', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/12630231/how-do-cors-and-access-control-allow-headers-work', 'admin:1764224036'),

('CORS headers missing on actual request (not just preflight)', 'web', 'HIGH', '[{"solution": "Include CORS headers on both OPTIONS preflight AND actual request responses", "percentage": 98}, {"solution": "Server must send Access-Control-Allow-Origin on POST/PUT/DELETE not just preflight", "percentage": 96}]'::jsonb, 'Server response headers', 'Actual request succeeds with CORS headers present', 'Only adding headers to OPTIONS response', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/46785318/the-cors-header-access-control-allow-origin-is-missing', 'admin:1764224036'),

('Preflight OPTIONS request fails, actual request blocked', 'web', 'MEDIUM', '[{"solution": "Respond to OPTIONS with 200 OK status: if(req.method===''OPTIONS'') return res.status(200).send()", "percentage": 96}, {"solution": "Include all required headers in preflight: Access-Control-Allow-Origin, Methods, Headers, Credentials", "percentage": 94}]'::jsonb, 'Preflight response handling', 'Both preflight and actual requests succeed', 'Incomplete preflight response headers', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/53298478/has-been-blocked-by-cors-policy-response-to-preflight-request-doesn-t-pass-acce', 'admin:1764224036'),

('withCredentials true but credentials header missing from server', 'web', 'HIGH', '[{"solution": "Set Access-Control-Allow-Credentials: true in server response when using withCredentials: true in request", "percentage": 98}, {"solution": "For axios: use axios.defaults.withCredentials = true AND configure CORS with credentials: true", "percentage": 96}]'::jsonb, 'Axios/fetch configuration', 'Credentials transmitted successfully in request', 'Mismatch between client withCredentials and server header', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/75584082/cors-policy-issue-when-adding-withcredentials-true-to-axios-headers-javascri', 'admin:1764224036'),

('Custom headers trigger preflight request', 'web', 'LOW', '[{"solution": "Either remove custom headers or handle OPTIONS preflight request", "percentage": 94}, {"solution": "Use only simple headers (Accept, Accept-Language, Content-Language, Content-Type) to avoid preflight", "percentage": 80}]'::jsonb, 'Custom header usage', 'Custom headers sent without preflight errors', 'Adding non-simple headers triggers unnecessary preflights', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/41679725/preflight-request-is-sent-with-all-methods', 'admin:1764224036'),

('Browser caches preflight response causing stale CORS headers', 'web', 'LOW', '[{"solution": "Use Access-Control-Max-Age header to control preflight cache: Access-Control-Max-Age: 3600", "percentage": 85}, {"solution": "Clear browser cache in DevTools to test fresh preflight", "percentage": 98}]'::jsonb, 'Browser cache management', 'Fresh preflight request received with latest headers', 'Cached preflight response preventing header updates', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/23543719/cors-access-control-max-age-is-ignored', 'admin:1764224036'),

('Access-Control-Max-Age limits differ between browsers', 'web', 'LOW', '[{"solution": "Set Access-Control-Max-Age to value supported by all browsers (max 600 seconds for Chrome)", "percentage": 88}, {"solution": "Note: Firefox caps at 24 hours, Chromium at 10 minutes", "percentage": 90}]'::jsonb, 'CORS caching configuration', 'Preflight request cached appropriately', 'Setting too high Access-Control-Max-Age value', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/40731465/access-control-max-age-vs-cache-control', 'admin:1764224036'),

('Authorization header requires explicit allow in CORS', 'web', 'HIGH', '[{"solution": "Add Authorization to Access-Control-Allow-Headers: Content-Type,Authorization", "percentage": 98}, {"solution": "Include both Access-Control-Allow-Credentials: true and specific origin for token requests", "percentage": 96}]'::jsonb, 'Token-based authentication', 'Authorization header sent successfully', 'Missing Authorization from Access-Control-Allow-Headers', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/25064158/how-to-make-get-cors-request-with-authorization-header', 'admin:1764224036'),

('CORS error with API key in custom header', 'web', 'MEDIUM', '[{"solution": "Add custom header to Access-Control-Allow-Headers: X-API-KEY,Content-Type,Accept", "percentage": 96}, {"solution": "Server must explicitly allow custom API headers in CORS config", "percentage": 94}]'::jsonb, 'API key header handling', 'API key header accepted without preflight errors', 'Custom API headers not listed in CORS configuration', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/46785318/the-cors-header-access-control-allow-origin-is-missing', 'admin:1764224036'),

('Request body formatting error misidentified as CORS error', 'web', 'MEDIUM', '[{"solution": "Check actual error response in Network tab - may be JSON parsing error not CORS", "percentage": 95}, {"solution": "Ensure request body format matches server expectations (object vs string)", "percentage": 96}]'::jsonb, 'Request debugging', 'Correct error identified and fixed', 'Assuming CORS error without checking actual response', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/71948888/cors-why-do-i-get-successful-preflight-options-but-still-get-cors-error-with-p', 'admin:1764224036'),

('multipart/form-data Content-Type triggers preflight', 'web', 'LOW', '[{"solution": "Add Content-Type to Access-Control-Allow-Headers if using multipart", "percentage": 93}, {"solution": "multipart/form-data is NOT a simple content type and always requires preflight", "percentage": 96}]'::jsonb, 'Form data handling', 'File upload completes without CORS errors', 'Using complex Content-Type without preflight handling', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/12630231/how-do-cors-and-access-control-allow-headers-work', 'admin:1764224036'),

('Spring CORS configuration conflicts with request mapping', 'web', 'MEDIUM', '[{"solution": "Use @CrossOrigin annotation instead of manual @RequestMapping for OPTIONS", "percentage": 96}, {"solution": "Or use global CorsRegistry.addMapping() with WebMvcConfigurer instead of manual handlers", "percentage": 94}]'::jsonb, 'Spring Framework configuration', 'CORS requests work with @CrossOrigin annotation', 'Multiple CORS configurations interfering with each other', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/38507370/cors-preflight-request-fails-due-to-a-standard-header', 'admin:1764224036');
