-- Fiber error mining - 10 stack overflow errors
-- Category: go-fiber, golang, web-framework

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('Handler type mismatch - cannot use controller method as fiber.Handler', 'fiber', 'HIGH', '[{"solution": "Use dependency injection pattern: pass controller instance to route function instead of method reference", "percentage": 95}, {"solution": "Accept *fiber.Ctx as first parameter in method signature to match handler type", "percentage": 85}]'::jsonb, 'Go fiber v2, struct receivers understanding', 'Route accepts handler without type error', 'Using method value instead of injected instance', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/75371429', 'admin:1764210361'),

('FiberError - fiber called across threads', 'fiber', 'HIGH', '[{"solution": "Avoid using non-thread-safe enumerators/iterators (e.g. RandomWord.nouns) in fiber context", "percentage": 92}, {"solution": "Use Queue or other thread-safe collection to initialize data once at app startup", "percentage": 88}, {"solution": "Access shared resources through mutex-protected locks", "percentage": 85}]'::jsonb, 'Ruby fibers, threading concepts, thread safety', 'No FiberError in subsequent page loads', 'Accessing module-level enumerators across fiber boundaries', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/28951261', 'admin:1764210361'),

('Panic recovery middleware does not override response in client', 'fiber', 'HIGH', '[{"solution": "Create custom middleware wrapping recover functionality to control error response", "percentage": 90}, {"solution": "Use defer with recover() directly in handler instead of recover middleware", "percentage": 88}, {"solution": "Ensure custom error handler is called before response is sent", "percentage": 85}]'::jsonb, 'Go error handling, middleware pattern, panic recovery', 'Custom error message shown to client', 'Attempting to modify response after panic already triggered', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/79682013', 'admin:1764210361'),

('CORS middleware has no effect when applied after routes', 'fiber', 'MEDIUM', '[{"solution": "Always call app.Use(cors.New(...)) BEFORE defining routes", "percentage": 96}, {"solution": "Never place CORS middleware after app.Mount() calls", "percentage": 94}, {"solution": "Apply CORS at app initialization, before any route setup", "percentage": 92}]'::jsonb, 'CORS protocol, HTTP preflight requests, middleware ordering', 'Preflight OPTIONS requests accepted from browser', 'Adding CORS middleware after routes are registered', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/73272736', 'admin:1764210361'),

('Type assertion error - app.Group() returns fiber.Router not *fiber.Group', 'fiber', 'MEDIUM', '[{"solution": "Change function parameter type from *fiber.Group to fiber.Router interface", "percentage": 98}, {"solution": "Use Route() method instead of Group() for modular routing", "percentage": 85}, {"solution": "Cast return value: router := app.Group(\"/path\") as fiber.Router", "percentage": 80}]'::jsonb, 'Go interfaces, type assertions, fiber routing', 'Routes defined in separate files without type error', 'Assuming Group() returns concrete type instead of interface', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/71043030', 'admin:1764210361'),

('Server listening on HOST[::]  instead of localhost', 'fiber', 'LOW', '[{"solution": "Use app.Listen(\"localhost:3000\") with explicit host", "percentage": 97}, {"solution": "Use app.Listen(\"127.0.0.1:3000\") for IPv4-only binding", "percentage": 93}, {"solution": "Check for port conflicts with lsof -i :3000 and switch ports", "percentage": 88}]'::jsonb, 'Fiber listen method, IPv6 vs IPv4, port binding', 'Server accessible at localhost:3000 or 127.0.0.1:3000', 'Assuming default Listen() binds to localhost without port conflict', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/62904360', 'admin:1764210361'),

('npm install fibers build fails - missing build tools', 'fiber', 'MEDIUM', '[{"solution": "Install windows-build-tools globally: npm install --global --production windows-build-tools", "percentage": 92}, {"solution": "Install node-gyp globally for native module compilation: npm install --global node-gyp", "percentage": 90}, {"solution": "Ensure Node version matches fibers requirements (4.x-6.x for older versions)", "percentage": 85}]'::jsonb, 'npm, native modules, build tools, gyp', 'fibers package installed without ELIFECYCLE error', 'Missing make utility or incompatible Node version', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/24649549', 'admin:1764210361'),

('Middleware permission check causes 404 on superuser routes', 'fiber', 'MEDIUM', '[{"solution": "Separate superuser check from permission check logic - return c.Next() immediately for superusers", "percentage": 89}, {"solution": "Ensure HasPermissionMiddleware returns c.Next() for all valid cases, not just superusers", "percentage": 87}, {"solution": "Check order of middleware in route chain - AuthMiddleware must run before permission checks", "percentage": 84}]'::jsonb, 'Fiber middleware, permission handling, conditional authorization', 'Superuser routes return proper response without 404', 'Mixing user permission validation with access control flow', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/77639785', 'admin:1764210361'),

('JWT claims middleware returns empty token', 'fiber', 'HIGH', '[{"solution": "Apply Protected() middleware to all protected routes before accessing ctx.Locals(\"user\")", "percentage": 94}, {"solution": "Verify JWT token is being sent in Authorization header with Bearer prefix", "percentage": 91}, {"solution": "Check middleware order - JWT validation must occur before accessing token in Locals", "percentage": 88}]'::jsonb, 'JWT authentication, fiber middleware, context locals', 'Claims extracted without nil pointer exception', 'Accessing token from Locals without JWT middleware validation', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/73261520', 'admin:1764210361'),

('Middleware returns original route pattern /:id instead of actual path', 'fiber', 'LOW', '[{"solution": "Use c.OriginalURL() instead of c.Path() to get route pattern", "percentage": 96}, {"solution": "c.Path() returns matched URL path - c.OriginalURL() returns full original request URI", "percentage": 94}, {"solution": "For pattern matching use c.Route() or access route definition directly", "percentage": 85}]'::jsonb, 'Fiber context methods, path handling, routing patterns', 'Middleware displays route pattern /user/:id not actual path', 'Confusing Path() and OriginalURL() methods', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/73742452', 'admin:1764210361');
