-- Mining run: General Other errors (10 entries)
-- Generated: 2025-11-26
-- Miner: haiku-1764191638

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Svelte SyntaxError: Cannot use import statement outside a module', 'general', 'HIGH', '[{"solution": "Add \"type\": \"module\" to package.json to enable ES modules", "percentage": 85}, {"solution": "Rename svelte.config.js to svelte.config.mjs", "percentage": 70}, {"solution": "Use require() instead of import statements in config files", "percentage": 60}]'::jsonb, 'svelte.config.js file exists, package.json file', 'svelte.config.js loads without errors, project builds successfully', 'Forgetting quotes around \"type\": \"module\", using import instead of require for CommonJS', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/70588096/error-in-svelte-config-js-syntax-error-cannot-use-import-statement-outside-a-mo', 'admin:1764191638'),

('TanStack Query hydration mismatch error with React Server Components', 'general', 'HIGH', '[{"solution": "Wrap Table component with dynamic import to disable SSR: const Table = dynamic(() => import(''./Table''), { ssr: false })", "percentage": 90}, {"solution": "Use useEffect hook to ensure client-side rendering after hydration", "percentage": 80}, {"solution": "Check that server and client data states are identical before rendering", "percentage": 75}]'::jsonb, 'React 18+, Next.js 13+ with app directory, @tanstack/react-table installed', 'Table renders correctly on client side, no hydration warnings in console', 'Passing props during SSR that cause state mismatch, using different data sources on server vs client', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/78250870/hydration-failed-because-the-initial-ui-does-not-match-what-was-rendered-on-the', 'admin:1764191638'),

('SolidJS createResource TypeError: "tmpl is not a function"', 'general', 'MEDIUM', '[{"solution": "Access resource state with data.loading, data.error, and data.state === ''ready'' before calling data()", "percentage": 92}, {"solution": "Guard resource access with Show component from solid-js to prevent accessing undefined", "percentage": 88}, {"solution": "Ensure promises in createResource are properly resolved before accessing result", "percentage": 85}]'::jsonb, 'SolidJS 1.4+, createResource API usage', 'Resource loads correctly, no errors in browser console, data displays properly', 'Attempting to call data() when loading or error state is true, accessing unresolved promise', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/76112713/solidjs-crashes-with-tmpl-not-a-function', 'admin:1764191638'),

('Svelte EPERM: operation not permitted error in node_modules', 'general', 'HIGH', '[{"solution": "Delete node_modules and package-lock.json, then run npm install again", "percentage": 88}, {"solution": "Run Visual Studio Code as Administrator to grant proper file permissions", "percentage": 75}, {"solution": "Disable antivirus temporarily during npm operations, then re-enable for affected folders", "percentage": 70}]'::jsonb, 'Windows OS, npm installed, Svelte/SvelteKit project', 'npm install completes without errors, node_modules folder accessible', 'Antivirus software blocking npm, insufficient folder permissions, file locks from other processes', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/78263241/how-to-solve-error-eperm-operation-not-permitted-in-visual-studio-code-with-sv', 'admin:1764191638'),

('"x is not a function" TypeError in JavaScript', 'general', 'HIGH', '[{"solution": "Ensure function is defined before calling it - check for missing script tags or library imports", "percentage": 95}, {"solution": "For object methods, declare with this.method = function() {} syntax instead of nested functions", "percentage": 88}, {"solution": "Check scope of function - it must be accessible from where it''s called", "percentage": 85}]'::jsonb, 'JavaScript execution environment, function definition', 'Function executes without TypeError, return value is correct', 'Function declared in wrong scope, typo in function name, missing library import', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/9825071/javascript-error-is-not-a-function', 'admin:1764191638'),

('SolidJS resource Uncaught Error in Promise with failed API requests', 'general', 'MEDIUM', '[{"solution": "Check resource state with data.state === ''errored'' before accessing data()", "percentage": 91}, {"solution": "Wrap data() access in Show component: <Show when={data.state === ''ready''}>{data()}</Show>", "percentage": 89}, {"solution": "Handle 401 errors inside createResource callback instead of trying to access undefined data", "percentage": 86}]'::jsonb, 'SolidJS 1.4+, createResource for API calls, error handling', 'No unhandled promise rejections, error state is properly detected', 'Not guarding against error state before accessing data(), accessing data() during error', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/72789994/solidjs-create-resource-uncaught-error-in-promise', 'admin:1764191638'),

('SolidJS html tag SyntaxError: Unexpected token when using solid-js/html', 'general', 'MEDIUM', '[{"solution": "Don''t use html`` template tag for string HTML - use innerHTML instead: const el = document.createElement(''div''); el.innerHTML = output; return el;", "percentage": 90}, {"solution": "If output is already an HTMLElement, render it directly without html`` tag", "percentage": 88}, {"solution": "Use solid-js html templates only for known static HTML, not for dynamic string content", "percentage": 80}]'::jsonb, 'SolidJS project with solid-js/html import', 'Template renders without SyntaxError, HTML content displays correctly', 'Using html`` tag with string interpolation of HTML, mixing template syntax with string HTML', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/74913171/uncaught-error-unexpected-token-in-solid-js-for-using-solid-js-html', 'admin:1764191638'),

('TanStack Router hydration mismatch with Vite SSR and renderToString', 'general', 'MEDIUM', '[{"solution": "Ensure server and client routers are initialized with same path and data state", "percentage": 89}, {"solution": "Use dehydrate/hydrate from @tanstack/react-query to sync server state to client", "percentage": 87}, {"solution": "Add Suspense boundaries to ensure server rendering waits for data before sending HTML", "percentage": 84}]'::jsonb, 'TanStack Router v1+, Vite SSR setup, @tanstack/react-query', 'Hydration completes without mismatches, client renders identically to server', 'Different QueryClient instances on server and client, async operations not awaited', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/79643003/vite-tanstackrouter-ssr', 'admin:1764191638'),

('ESLint react-hooks/exhaustive-deps warning for useEffect dependencies', 'general', 'MEDIUM', '[{"solution": "Disable warning locally with // eslint-disable-next-line react-hooks/exhaustive-deps above useEffect", "percentage": 88}, {"solution": "Add all dependencies to dependency array to fix the underlying bug", "percentage": 90}, {"solution": "Refactor to move non-essential dependencies outside useEffect", "percentage": 82}]'::jsonb, 'ESLint configured, React hooks plugin enabled', 'No exhaustive-deps warnings, useEffect behavior is correct', 'Disabling rule without understanding the bug, adding unnecessary dependencies', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/65704653/how-do-i-configure-eslint-rules-to-ignore-react-hooks-exhaustive-deps-globally', 'admin:1764191638'),

('EACCES Permission denied error when installing npm packages outside home directory', 'general', 'HIGH', '[{"solution": "Fix partition mount permissions: change mount options from ''users'' to ''defaults'' in /etc/fstab", "percentage": 92}, {"solution": "Use sudo npm install if mount permissions cannot be changed", "percentage": 80}, {"solution": "Change npm prefix to home directory instead of /usr", "percentage": 75}]'::jsonb, 'Linux OS, npm installed, directory outside home mounted as users', 'npm install completes successfully, binaries in node_modules/.bin are executable', 'Partition mounted with incorrect permissions, npm prefix set to restricted directory', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/75239018/npm-install-eaccess-when-try-to-install-outside-of-home-dir-on-linux', 'admin:1764191638');
