-- Batch 5: Testing & ORM Errors - Official Docs Mining
-- Sources: Jest, ESLint, Prisma, GraphQL official documentation
-- Mined: 2025-11-25

-- =====================================================
-- JEST TESTING ERRORS (12 entries)
-- Source: jestjs.io/docs/troubleshooting
-- =====================================================

INSERT INTO knowledge_entries (
    query, category, hit_frequency, solutions, prerequisites, success_indicators,
    common_pitfalls, success_rate, claude_version, last_verified, source_url
) VALUES
(
    'Jest error: Cannot find module or its corresponding type declarations',
    'jest',
    'CRITICAL',
    $$[{"solution": "Check that the module is installed and listed in package.json dependencies. Run npm install or yarn install to ensure all dependencies are present.", "percentage": 92, "note": "Most common cause is missing dependency"}, {"solution": "Verify moduleNameMapper in jest.config.js maps aliases correctly to actual paths", "percentage": 88, "note": "Path aliases need explicit Jest configuration"}]$$::jsonb,
    'Jest installed, package.json present, node_modules populated',
    'Test runs without module resolution errors, imports resolve correctly',
    'Forgetting to install devDependencies, incorrect path mapping syntax, missing @ alias configuration',
    0.91,
    'sonnet-4',
    NOW(),
    'https://jestjs.io/docs/troubleshooting'
),
(
    'Jest error: Test suite failed to run - SyntaxError unexpected token',
    'jest',
    'CRITICAL',
    $$[{"solution": "Add babel-jest and @babel/preset-env to transform ES6/ESM syntax. Configure babel.config.js with presets for your environment", "percentage": 94, "note": "Jest needs Babel to transform modern JS"}, {"solution": "For TypeScript, install ts-jest and configure transform in jest.config.js: transform: { '^.+\\.tsx?$': 'ts-jest' }", "percentage": 90, "note": "TypeScript requires ts-jest transformer"}]$$::jsonb,
    'Jest installed, Babel or TypeScript configured',
    'Test suite runs without syntax errors, ES6/TS code executes correctly',
    'Missing Babel presets, incorrect transform configuration, mixing ESM and CommonJS',
    0.92,
    'sonnet-4',
    NOW(),
    'https://jestjs.io/docs/troubleshooting'
),
(
    'Jest error: Timeout - Async callback was not invoked within timeout',
    'jest',
    'HIGH',
    $$[{"solution": "Increase timeout with jest.setTimeout(30000) at top of test file or in setupFilesAfterEnv. Default is 5000ms", "percentage": 90, "note": "Some async operations need more time"}, {"solution": "Ensure async test returns promise or uses done() callback correctly. Check for unresolved promises or missing await keywords", "percentage": 88, "note": "Forgotten await is common cause"}]$$::jsonb,
    'Jest async tests, understanding of Promises and async/await',
    'Async tests complete within timeout, no timeout errors in output',
    'Forgetting to return promise, missing await, not calling done() in callback tests',
    0.89,
    'sonnet-4',
    NOW(),
    'https://jestjs.io/docs/troubleshooting'
),
(
    'Jest error: Cannot spy on primitive value or read-only property',
    'jest',
    'HIGH',
    $$[{"solution": "Use jest.mock() to mock the entire module instead of spying on individual exports. Mock at module level before imports", "percentage": 91, "note": "ES modules have read-only exports"}, {"solution": "For object methods, ensure the object is not frozen. Use jest.spyOn(object, 'method') only on mutable object properties", "percentage": 85, "note": "Object.freeze prevents spying"}]$$::jsonb,
    'Understanding of Jest mocking API, ES module structure',
    'Spy or mock applies correctly, test assertions on mock pass',
    'Trying to spy on const exports, spying on frozen objects, incorrect mock hoisting',
    0.88,
    'sonnet-4',
    NOW(),
    'https://jestjs.io/docs/troubleshooting'
),
(
    'Jest error: ReferenceError - document/window is not defined',
    'jest',
    'HIGH',
    $$[{"solution": "Set testEnvironment to jsdom in jest.config.js: testEnvironment: 'jsdom'. Install jest-environment-jsdom if not present", "percentage": 95, "note": "Jest defaults to node environment"}, {"solution": "Add @jest-environment jsdom comment at top of test file for per-file environment override", "percentage": 88, "note": "Per-file override available"}]$$::jsonb,
    'Jest installed, testing DOM-dependent code',
    'DOM APIs (document, window) available in tests, no ReferenceError',
    'Forgetting to install jest-environment-jsdom separately (Jest 28+), mixing node and jsdom tests',
    0.93,
    'sonnet-4',
    NOW(),
    'https://jestjs.io/docs/troubleshooting'
),
(
    'Jest error: Matcher error - received value must be a mock or spy function',
    'jest',
    'MEDIUM',
    $$[{"solution": "Use jest.fn() to create mock function before passing to component/function. Assign mock to variable for assertion", "percentage": 93, "note": "toHaveBeenCalled only works on mocks"}, {"solution": "Use jest.spyOn() to wrap existing function before testing. Remember to restore with mockRestore()", "percentage": 89, "note": "Spies need explicit creation"}]$$::jsonb,
    'Understanding of Jest mock functions and matchers',
    'Mock assertions pass, toHaveBeenCalled works correctly',
    'Passing regular function to toHaveBeenCalled, forgetting jest.fn() wrapper',
    0.91,
    'sonnet-4',
    NOW(),
    'https://jestjs.io/docs/troubleshooting'
),
(
    'Jest error: Exceeded timeout of 5000ms for a hook (beforeAll/afterAll)',
    'jest',
    'MEDIUM',
    $$[{"solution": "Pass timeout as second argument to hook: beforeAll(async () => {...}, 30000). Increase for slow setup operations", "percentage": 90, "note": "Hooks have separate timeout from tests"}, {"solution": "Move slow operations outside Jest or use globalSetup/globalTeardown for one-time expensive operations", "percentage": 85, "note": "Global setup runs once for all tests"}]$$::jsonb,
    'Jest test lifecycle hooks, async setup requirements',
    'Hooks complete within timeout, setup/teardown executes successfully',
    'Not passing timeout to hook, putting database setup in beforeEach instead of beforeAll',
    0.88,
    'sonnet-4',
    NOW(),
    'https://jestjs.io/docs/troubleshooting'
),
(
    'Jest error: Cannot read properties of undefined (reading mock)',
    'jest',
    'HIGH',
    $$[{"solution": "Ensure jest.mock() is called before importing the module. Move mock declarations to top of file or use jest.doMock() for dynamic mocking", "percentage": 92, "note": "Mock hoisting is critical"}, {"solution": "Check that mock factory returns the correct shape. Default export needs { default: mockFn } structure", "percentage": 87, "note": "Default exports need special handling"}]$$::jsonb,
    'Understanding of Jest mock hoisting and module system',
    'Mock is defined and accessible, mock properties readable',
    'Importing before mocking, incorrect mock factory return shape, missing default key',
    0.89,
    'sonnet-4',
    NOW(),
    'https://jestjs.io/docs/troubleshooting'
),
(
    'Jest error: Your test suite must contain at least one test',
    'jest',
    'MEDIUM',
    $$[{"solution": "Add at least one test() or it() block to the file. Check for conditional test blocks that may be skipped", "percentage": 95, "note": "Empty test files cause this error"}, {"solution": "Verify testMatch or testRegex in jest.config.js matches your test file naming pattern", "percentage": 88, "note": "Files may not match test pattern"}]$$::jsonb,
    'Jest test file structure, configuration understanding',
    'Test suite runs with at least one test, no empty suite errors',
    'Commenting out all tests, describe block without tests, wrong file extension',
    0.93,
    'sonnet-4',
    NOW(),
    'https://jestjs.io/docs/troubleshooting'
),
(
    'Jest error: Jest encountered unexpected token - import statement outside module',
    'jest',
    'CRITICAL',
    $$[{"solution": "Configure transformIgnorePatterns in jest.config.js to transform node_modules that ship ESM: transformIgnorePatterns: ['/node_modules/(?!problematic-package)']", "percentage": 91, "note": "Some packages need transformation"}, {"solution": "Set transform to use babel-jest for .js files and ensure @babel/preset-env targets your Node version", "percentage": 89, "note": "Babel must transform ESM to CommonJS"}]$$::jsonb,
    'Jest with ES modules, Babel configuration',
    'All imports resolve correctly, no unexpected token errors',
    'Not excluding specific packages from transformIgnorePatterns, outdated Babel config',
    0.90,
    'sonnet-4',
    NOW(),
    'https://jestjs.io/docs/troubleshooting'
),
(
    'Jest error: Snapshots do not match - received vs stored',
    'jest',
    'MEDIUM',
    $$[{"solution": "If change is intentional, run jest --updateSnapshot or jest -u to update snapshots. Review diff to confirm change is expected", "percentage": 94, "note": "Snapshots need updating when UI changes"}, {"solution": "For dynamic content (dates, IDs), use expect.any() matchers or snapshot serializers to handle variable data", "percentage": 88, "note": "Dynamic data breaks snapshots"}]$$::jsonb,
    'Jest snapshot testing, understanding of snapshot workflow',
    'Snapshots match after update, no false positive failures',
    'Blindly updating snapshots without reviewing, not handling dynamic content',
    0.92,
    'sonnet-4',
    NOW(),
    'https://jestjs.io/docs/troubleshooting'
),
(
    'Jest error: Coverage directory not found or coverage report empty',
    'jest',
    'MEDIUM',
    $$[{"solution": "Run jest --coverage flag to generate coverage. Configure collectCoverageFrom in jest.config.js to specify which files to collect", "percentage": 90, "note": "Coverage must be explicitly enabled"}, {"solution": "Check coverageDirectory path exists and is writable. Default is ./coverage in project root", "percentage": 85, "note": "Directory permissions can cause issues"}]$$::jsonb,
    'Jest coverage configuration, file system access',
    'Coverage report generated in coverage directory, HTML report accessible',
    'Missing collectCoverageFrom patterns, excluding source files accidentally, wrong directory path',
    0.88,
    'sonnet-4',
    NOW(),
    'https://jestjs.io/docs/troubleshooting'
),

-- =====================================================
-- ESLINT ERRORS (12 entries)
-- Source: eslint.org/docs/user-guide/troubleshooting
-- =====================================================

(
    'ESLint error: Parsing error - Unexpected token',
    'eslint',
    'CRITICAL',
    $$[{"solution": "Install and configure @babel/eslint-parser for modern JS syntax. Set parser in eslintrc: parser: '@babel/eslint-parser'", "percentage": 93, "note": "Default parser does not support all modern syntax"}, {"solution": "For TypeScript, install @typescript-eslint/parser and set as parser with parserOptions.project pointing to tsconfig.json", "percentage": 91, "note": "TypeScript needs its own parser"}]$$::jsonb,
    'ESLint installed, Babel or TypeScript in project',
    'ESLint parses all files without syntax errors',
    'Missing parser dependency, incorrect parserOptions, mismatched parser and syntax',
    0.92,
    'sonnet-4',
    NOW(),
    'https://eslint.org/docs/user-guide/troubleshooting'
),
(
    'ESLint error: Definition for rule was not found',
    'eslint',
    'HIGH',
    $$[{"solution": "Install the plugin that provides the rule. Format is plugin-name/rule-name, so install eslint-plugin-[plugin-name]", "percentage": 94, "note": "Rules come from plugins"}, {"solution": "Check that plugin is listed in plugins array in eslintrc. Plugins must be both installed and declared", "percentage": 90, "note": "Plugin must be declared to use its rules"}]$$::jsonb,
    'ESLint configuration file, npm/yarn for package installation',
    'Rule loads and applies correctly, no definition not found errors',
    'Forgetting to add plugin to plugins array, typo in rule name, plugin not installed',
    0.93,
    'sonnet-4',
    NOW(),
    'https://eslint.org/docs/user-guide/troubleshooting'
),
(
    'ESLint error: Cannot find module eslint-config-*',
    'eslint',
    'HIGH',
    $$[{"solution": "Install the shareable config: npm install eslint-config-[name] --save-dev. Common ones: airbnb, standard, prettier", "percentage": 95, "note": "Configs are separate packages"}, {"solution": "Check extends array uses correct format. Shorthand 'airbnb' expands to 'eslint-config-airbnb'", "percentage": 88, "note": "Shorthand format available"}]$$::jsonb,
    'ESLint with extends configuration, npm access',
    'Config loads successfully, extended rules apply to linting',
    'Using full package name instead of shorthand in extends, missing peer dependencies',
    0.94,
    'sonnet-4',
    NOW(),
    'https://eslint.org/docs/user-guide/troubleshooting'
),
(
    'ESLint error: ESLint could not find configuration file',
    'eslint',
    'HIGH',
    $$[{"solution": "Create .eslintrc.js, .eslintrc.json, or .eslintrc.yml in project root. Run npx eslint --init for guided setup", "percentage": 96, "note": "Config file is required"}, {"solution": "For ESLint 9+, create eslint.config.js (flat config) instead of .eslintrc. New format is default in v9", "percentage": 88, "note": "Flat config is new default"}]$$::jsonb,
    'ESLint installed, project directory access',
    'ESLint finds and uses configuration, linting runs without config errors',
    'Wrong file extension, config in wrong directory, mixing flat and legacy config',
    0.95,
    'sonnet-4',
    NOW(),
    'https://eslint.org/docs/user-guide/troubleshooting'
),
(
    'ESLint error: Conflicting rules - Prettier and ESLint formatting conflicts',
    'eslint',
    'CRITICAL',
    $$[{"solution": "Install eslint-config-prettier and add 'prettier' as last item in extends array. This disables conflicting formatting rules", "percentage": 95, "note": "Prettier config disables conflicts"}, {"solution": "Remove formatting rules from ESLint config (quotes, semi, indent) and let Prettier handle all formatting", "percentage": 90, "note": "Single source of truth for formatting"}]$$::jsonb,
    'ESLint and Prettier both installed, understanding of tool responsibilities',
    'No conflicting rule errors, consistent formatting from Prettier',
    'Not putting prettier last in extends, keeping formatting rules in ESLint config',
    0.93,
    'sonnet-4',
    NOW(),
    'https://eslint.org/docs/user-guide/troubleshooting'
),
(
    'ESLint error: Unable to resolve path to module - import/no-unresolved',
    'eslint',
    'HIGH',
    $$[{"solution": "Configure eslint-import-resolver-typescript or eslint-import-resolver-alias for path aliases. Add to settings.import/resolver in eslintrc", "percentage": 92, "note": "Import resolver handles path resolution"}, {"solution": "Ensure tsconfig paths match eslint resolver configuration. Both must agree on alias mappings", "percentage": 88, "note": "Configs must be synchronized"}]$$::jsonb,
    'eslint-plugin-import installed, path aliases in project',
    'Import paths resolve correctly, no-unresolved rule passes',
    'Mismatched resolver and tsconfig paths, forgetting to install resolver package',
    0.90,
    'sonnet-4',
    NOW(),
    'https://eslint.org/docs/user-guide/troubleshooting'
),
(
    'ESLint error: Parsing error - parserOptions.project has been set but cannot be found',
    'eslint',
    'HIGH',
    $$[{"solution": "Verify parserOptions.project path is correct relative to eslintrc location. Use './tsconfig.json' for same directory", "percentage": 93, "note": "Path must be relative to eslintrc"}, {"solution": "For monorepos, use array of tsconfig paths or set tsconfigRootDir to __dirname", "percentage": 88, "note": "Monorepos need multiple configs"}]$$::jsonb,
    '@typescript-eslint/parser configured, tsconfig.json present',
    'TypeScript files parse correctly, type-aware rules work',
    'Incorrect relative path, missing tsconfig, tsconfigRootDir not set in monorepo',
    0.91,
    'sonnet-4',
    NOW(),
    'https://eslint.org/docs/user-guide/troubleshooting'
),
(
    'ESLint error: File ignored because of matching ignore pattern',
    'eslint',
    'MEDIUM',
    $$[{"solution": "Check .eslintignore file and ignorePatterns in config. Remove file pattern from ignore list if it should be linted", "percentage": 92, "note": "Ignore patterns may be overly broad"}, {"solution": "Use --no-ignore flag to lint ignored files for debugging. Helps identify which pattern is matching", "percentage": 85, "note": "Debug with no-ignore flag"}]$$::jsonb,
    'ESLint ignore configuration, file to lint identified',
    'File is linted, no longer shows ignored warning',
    'Ignoring entire directories accidentally, node_modules pattern too broad, gitignore sync issues',
    0.90,
    'sonnet-4',
    NOW(),
    'https://eslint.org/docs/user-guide/troubleshooting'
),
(
    'ESLint error: Environment key is unknown - env setting not recognized',
    'eslint',
    'MEDIUM',
    $$[{"solution": "Use valid env keys: browser, node, es2021, jest, mocha, etc. Check ESLint docs for full list of environments", "percentage": 94, "note": "Only predefined envs are valid"}, {"solution": "For custom globals, use globals config instead of env. globals: { myGlobal: 'readonly' }", "percentage": 88, "note": "Globals for custom variables"}]$$::jsonb,
    'ESLint env configuration, understanding of environment presets',
    'Environment recognized, appropriate globals available',
    'Typo in env name, using custom name as env, outdated env name',
    0.92,
    'sonnet-4',
    NOW(),
    'https://eslint.org/docs/user-guide/troubleshooting'
),
(
    'ESLint error: Plugin was loaded from different locations - version mismatch',
    'eslint',
    'MEDIUM',
    $$[{"solution": "Delete node_modules and package-lock.json, then run npm install. Ensures single version of plugin", "percentage": 91, "note": "Clean install resolves duplicates"}, {"solution": "Check for duplicate plugin in dependencies and devDependencies. Remove duplicate and use single version", "percentage": 87, "note": "Only one location for plugin"}]$$::jsonb,
    'npm/yarn package manager, access to delete node_modules',
    'Single plugin version loads, no version mismatch warnings',
    'Multiple packages depending on different plugin versions, forgetting to delete lock file',
    0.89,
    'sonnet-4',
    NOW(),
    'https://eslint.org/docs/user-guide/troubleshooting'
),
(
    'ESLint error: No files matching pattern found - nothing to lint',
    'eslint',
    'MEDIUM',
    $$[{"solution": "Check file extensions in ESLint command. Add --ext .js,.jsx,.ts,.tsx for multiple extensions", "percentage": 93, "note": "Extensions must be specified"}, {"solution": "Verify glob pattern matches files. Use quotes around pattern: eslint 'src/**/*.js'", "percentage": 89, "note": "Shell may expand globs incorrectly"}]$$::jsonb,
    'Files to lint present, correct ESLint command',
    'Files are found and linted, output shows linting results',
    'Wrong directory path, missing file extensions, shell glob expansion issues',
    0.91,
    'sonnet-4',
    NOW(),
    'https://eslint.org/docs/user-guide/troubleshooting'
),
(
    'ESLint error: Maximum call stack size exceeded during linting',
    'eslint',
    'HIGH',
    $$[{"solution": "Check for circular extends in config. Configs should not extend each other in a loop", "percentage": 88, "note": "Circular config causes stack overflow"}, {"solution": "Reduce plugin complexity. Some plugin rules with complex AST analysis can cause memory issues on large files", "percentage": 82, "note": "Large files may need rule exclusions"}]$$::jsonb,
    'ESLint configuration review, understanding of extends chain',
    'ESLint runs without stack overflow, files lint successfully',
    'Circular extends chain, too many complex rules on large codebase, outdated plugins',
    0.85,
    'sonnet-4',
    NOW(),
    'https://eslint.org/docs/user-guide/troubleshooting'
),

-- =====================================================
-- PRISMA ORM ERRORS (12 entries)
-- Source: prisma.io/docs/reference/api-reference/error-reference
-- =====================================================

(
    'Prisma error: P1001 - Cannot reach database server',
    'prisma',
    'CRITICAL',
    $$[{"solution": "Verify DATABASE_URL in .env is correct and database server is running. Check host, port, username, and password", "percentage": 94, "note": "Most common cause is incorrect connection string"}, {"solution": "Ensure database server is accessible from your network. Check firewall rules and security groups for cloud databases", "percentage": 90, "note": "Network access must be allowed"}]$$::jsonb,
    'Database server installed/provisioned, .env file with DATABASE_URL',
    'prisma db push or migrate succeeds, connection established',
    'Typo in connection string, database not started, wrong port, firewall blocking connection',
    0.93,
    'sonnet-4',
    NOW(),
    'https://www.prisma.io/docs/reference/api-reference/error-reference'
),
(
    'Prisma error: P1002 - Database server was reached but timed out',
    'prisma',
    'HIGH',
    $$[{"solution": "Increase connection timeout in DATABASE_URL: ?connect_timeout=30. Default may be too short for slow networks", "percentage": 88, "note": "Timeout is configurable"}, {"solution": "Check database server load and performance. May need to scale up database resources or optimize queries", "percentage": 85, "note": "Server may be overloaded"}]$$::jsonb,
    'Database reachable, network connectivity established',
    'Connection succeeds within timeout, queries execute',
    'Insufficient timeout for network latency, database overloaded, connection pool exhausted',
    0.86,
    'sonnet-4',
    NOW(),
    'https://www.prisma.io/docs/reference/api-reference/error-reference'
),
(
    'Prisma error: P1008 - Operations timed out',
    'prisma',
    'HIGH',
    $$[{"solution": "Add ?pool_timeout=30 to DATABASE_URL to increase pool timeout. Consider connection_limit parameter too", "percentage": 89, "note": "Pool timeout is separate from connect timeout"}, {"solution": "Reduce concurrent database operations or increase connection pool size with connection_limit parameter", "percentage": 85, "note": "Pool may be exhausted"}]$$::jsonb,
    'Prisma client initialized, database connection working',
    'Operations complete without timeout, queries return results',
    'Too many concurrent connections, pool size too small, long-running transactions blocking pool',
    0.87,
    'sonnet-4',
    NOW(),
    'https://www.prisma.io/docs/reference/api-reference/error-reference'
),
(
    'Prisma error: P2002 - Unique constraint violation',
    'prisma',
    'CRITICAL',
    $$[{"solution": "Check for duplicate value in unique field before insert. Use upsert() instead of create() to handle existing records", "percentage": 93, "note": "Upsert handles duplicates gracefully"}, {"solution": "Verify business logic - if duplicates should not occur, debug why duplicate data is being inserted", "percentage": 88, "note": "May indicate data integrity issue"}]$$::jsonb,
    'Prisma schema with unique constraints, understanding of data model',
    'Records create/update without constraint errors, upsert works correctly',
    'Not checking for existing records, race conditions causing duplicates, incorrect unique fields',
    0.91,
    'sonnet-4',
    NOW(),
    'https://www.prisma.io/docs/reference/api-reference/error-reference'
),
(
    'Prisma error: P2003 - Foreign key constraint violation',
    'prisma',
    'HIGH',
    $$[{"solution": "Ensure referenced record exists before creating record with foreign key. Create parent record first or use connect syntax", "percentage": 92, "note": "Parent must exist before child"}, {"solution": "Check onDelete and onUpdate referential actions in schema. May need Cascade or SetNull for your use case", "percentage": 88, "note": "Referential actions affect behavior"}]$$::jsonb,
    'Prisma schema with relations defined, understanding of foreign keys',
    'Related records create successfully, foreign keys resolve correctly',
    'Creating child before parent, deleting parent with existing children, incorrect relation syntax',
    0.90,
    'sonnet-4',
    NOW(),
    'https://www.prisma.io/docs/reference/api-reference/error-reference'
),
(
    'Prisma error: P2021 - Table does not exist in database',
    'prisma',
    'CRITICAL',
    $$[{"solution": "Run prisma migrate dev to create tables from schema. For existing database, run prisma db pull to sync schema first", "percentage": 95, "note": "Migrations create tables"}, {"solution": "Verify DATABASE_URL points to correct database. Different databases may have different schemas", "percentage": 88, "note": "May be connected to wrong database"}]$$::jsonb,
    'Prisma schema defined, database access',
    'Tables created in database, Prisma queries work',
    'Forgetting to run migrations, pointing to wrong database, schema out of sync',
    0.93,
    'sonnet-4',
    NOW(),
    'https://www.prisma.io/docs/reference/api-reference/error-reference'
),
(
    'Prisma error: P2025 - Record to update/delete not found',
    'prisma',
    'HIGH',
    $$[{"solution": "Use updateMany() or deleteMany() if record may not exist - these return count instead of error", "percentage": 90, "note": "Many variants do not throw on missing"}, {"solution": "Check for record existence first with findUnique() before update/delete if you need to handle missing case", "percentage": 87, "note": "Explicit check provides control"}]$$::jsonb,
    'Prisma client, understanding of update/delete operations',
    'Operations handle missing records gracefully, no unexpected errors',
    'Assuming record exists, race conditions deleting twice, stale IDs from cache',
    0.88,
    'sonnet-4',
    NOW(),
    'https://www.prisma.io/docs/reference/api-reference/error-reference'
),
(
    'Prisma error: Prisma client has not been generated - prisma generate required',
    'prisma',
    'CRITICAL',
    $$[{"solution": "Run npx prisma generate after any schema.prisma changes. This creates the Prisma client in node_modules", "percentage": 96, "note": "Generate required after schema changes"}, {"solution": "Add prisma generate to postinstall script in package.json for automatic generation: \"postinstall\": \"prisma generate\"", "percentage": 92, "note": "Automate generation in CI/CD"}]$$::jsonb,
    'Prisma installed, schema.prisma file present',
    '@prisma/client importable, TypeScript types correct',
    'Forgetting to regenerate after schema change, missing generate in CI pipeline, cached node_modules',
    0.95,
    'sonnet-4',
    NOW(),
    'https://www.prisma.io/docs/reference/api-reference/error-reference'
),
(
    'Prisma error: P3005 - Database schema is not empty - migration baseline required',
    'prisma',
    'HIGH',
    $$[{"solution": "Run prisma migrate dev --name init to baseline existing database. Or use prisma db push for development without migrations", "percentage": 91, "note": "Baseline captures existing schema"}, {"solution": "For existing database with data, use prisma migrate resolve --applied migration_name to mark migrations as applied", "percentage": 87, "note": "Resolve syncs migration state"}]$$::jsonb,
    'Existing database with schema, Prisma migration setup',
    'Migration state synced, new migrations apply correctly',
    'Trying to migrate fresh against existing schema, not baselining existing database',
    0.89,
    'sonnet-4',
    NOW(),
    'https://www.prisma.io/docs/reference/api-reference/error-reference'
),
(
    'Prisma error: PrismaClientInitializationError - engine not found',
    'prisma',
    'HIGH',
    $$[{"solution": "Run npm install to ensure @prisma/client and prisma are installed, then npx prisma generate", "percentage": 93, "note": "Engine binaries download during generate"}, {"solution": "Set binaryTargets in schema.prisma generator block for cross-platform deployment: binaryTargets = [\"native\", \"linux-musl\"]", "percentage": 89, "note": "Different platforms need different binaries"}]$$::jsonb,
    'Prisma packages installed, network access for binary download',
    'Prisma client initializes, engine binaries present in node_modules',
    'Skipping postinstall scripts, wrong binary target for deployment platform, network blocking binary download',
    0.91,
    'sonnet-4',
    NOW(),
    'https://www.prisma.io/docs/reference/api-reference/error-reference'
),
(
    'Prisma error: Migration failed to apply - drift detected',
    'prisma',
    'HIGH',
    $$[{"solution": "Run prisma migrate diff to see differences between schema and database. Resolve drift by pulling or resetting", "percentage": 88, "note": "Diff shows exact differences"}, {"solution": "For development, use prisma migrate reset to reset database to clean state and reapply all migrations", "percentage": 85, "note": "Reset for dev only - destroys data"}]$$::jsonb,
    'Prisma migrations configured, understanding of schema drift',
    'Migrations apply cleanly, schema and database in sync',
    'Manual database changes causing drift, migrations modified after apply, incomplete migration history',
    0.86,
    'sonnet-4',
    NOW(),
    'https://www.prisma.io/docs/reference/api-reference/error-reference'
),
(
    'Prisma error: Invalid prisma.model.field type - schema validation error',
    'prisma',
    'MEDIUM',
    $$[{"solution": "Check Prisma schema syntax - field types must be valid: String, Int, Float, Boolean, DateTime, Json, Bytes, etc.", "percentage": 94, "note": "Use Prisma-specific type names"}, {"solution": "For relations, ensure both sides of relation are defined with @relation directive", "percentage": 90, "note": "Relations need both sides defined"}]$$::jsonb,
    'Prisma schema file, understanding of Prisma schema language',
    'Schema validates successfully, prisma generate completes',
    'Using JavaScript types instead of Prisma types, incomplete relation definitions, missing required fields',
    0.92,
    'sonnet-4',
    NOW(),
    'https://www.prisma.io/docs/reference/api-reference/error-reference'
),

-- =====================================================
-- GRAPHQL ERRORS (11 entries)
-- Source: graphql.org/learn and Apollo docs
-- =====================================================

(
    'GraphQL error: Cannot query field on type - field does not exist',
    'graphql',
    'CRITICAL',
    $$[{"solution": "Check schema definition for exact field name and casing. GraphQL is case-sensitive. Use introspection to verify available fields", "percentage": 94, "note": "Field names are case-sensitive"}, {"solution": "Verify type you are querying has the field. May need to use fragment or inline fragment for interface/union types", "percentage": 89, "note": "Interfaces need fragments for type-specific fields"}]$$::jsonb,
    'GraphQL schema access, query builder or IDE with introspection',
    'Query returns field data, no field not found errors',
    'Typo in field name, querying wrong type, missing fragment for union type fields',
    0.92,
    'sonnet-4',
    NOW(),
    'https://graphql.org/learn/queries/'
),
(
    'GraphQL error: Variable $var was not provided or has invalid type',
    'graphql',
    'HIGH',
    $$[{"solution": "Ensure all declared variables are passed in variables object when executing query. Check variable names match declaration", "percentage": 93, "note": "Variables must be passed to execution"}, {"solution": "Verify variable type matches schema type exactly. Int vs Float, non-null (!) vs nullable", "percentage": 90, "note": "Types must match exactly"}]$$::jsonb,
    'GraphQL client configured, understanding of variable syntax',
    'Variables resolve correctly, query executes with provided values',
    'Missing variable in request, wrong variable type, typo in variable name, passing null to non-null',
    0.91,
    'sonnet-4',
    NOW(),
    'https://graphql.org/learn/queries/'
),
(
    'GraphQL error: Syntax error - expected Name, found }',
    'graphql',
    'HIGH',
    $$[{"solution": "Check for missing field selections in query. Every object type needs at least one field selected inside braces", "percentage": 92, "note": "Cannot query object without selecting fields"}, {"solution": "Verify no trailing commas in field lists. GraphQL does not allow trailing commas", "percentage": 87, "note": "No trailing commas allowed"}]$$::jsonb,
    'GraphQL query syntax knowledge, IDE with GraphQL validation',
    'Query parses without syntax errors, executes successfully',
    'Empty selection set {}, trailing commas, missing closing braces, unclosed strings',
    0.90,
    'sonnet-4',
    NOW(),
    'https://graphql.org/learn/queries/'
),
(
    'GraphQL error: Mutation requires variables but none provided',
    'graphql',
    'HIGH',
    $$[{"solution": "Pass variables object with mutation execution: client.mutate({ mutation, variables: { input } })", "percentage": 94, "note": "Variables passed separately from query string"}, {"solution": "Check mutation declaration matches variable usage. input: $input requires $input variable to be declared", "percentage": 89, "note": "Variables must be declared in operation"}]$$::jsonb,
    'GraphQL client configured for mutations, understanding of variable passing',
    'Mutation executes with provided variables, returns expected result',
    'Forgetting variables object, hardcoding values instead of using variables, type mismatch',
    0.91,
    'sonnet-4',
    NOW(),
    'https://graphql.org/learn/queries/'
),
(
    'GraphQL error: Cannot return null for non-nullable field',
    'graphql',
    'CRITICAL',
    $$[{"solution": "Ensure resolver returns a value for non-null fields. Check database query returns data or handle null case", "percentage": 91, "note": "Non-null fields must return a value"}, {"solution": "If field can legitimately be null, update schema to remove ! non-null modifier", "percentage": 88, "note": "Schema should reflect actual nullability"}]$$::jsonb,
    'GraphQL resolver implementation, schema control',
    'Resolver returns appropriate values, no null violations',
    'Database returning null, resolver not handling missing data, overly strict non-null schema',
    0.89,
    'sonnet-4',
    NOW(),
    'https://graphql.org/learn/execution/'
),
(
    'GraphQL error: Unknown argument on field - argument not defined',
    'graphql',
    'MEDIUM',
    $$[{"solution": "Check schema for valid arguments on the field. Use introspection query to see available arguments", "percentage": 93, "note": "Arguments must be defined in schema"}, {"solution": "Verify argument name spelling and casing. GraphQL arguments are case-sensitive", "percentage": 89, "note": "Case-sensitive argument names"}]$$::jsonb,
    'GraphQL schema access, introspection enabled',
    'Query executes with valid arguments, returns filtered/paginated data',
    'Typo in argument name, using argument from different field, passing argument to field that does not accept it',
    0.91,
    'sonnet-4',
    NOW(),
    'https://graphql.org/learn/queries/'
),
(
    'GraphQL error: Schema must contain uniquely named types',
    'graphql',
    'HIGH',
    $$[{"solution": "Rename duplicate type definitions. Each type name must be unique across entire schema including imported types", "percentage": 92, "note": "Type names are globally unique"}, {"solution": "When merging schemas, use extend type to add fields to existing types instead of redefining", "percentage": 88, "note": "Use extend for schema stitching"}]$$::jsonb,
    'GraphQL schema definition, understanding of type naming',
    'Schema validates with unique type names, server starts',
    'Duplicate type names in separate schema files, importing same type twice, name collision',
    0.90,
    'sonnet-4',
    NOW(),
    'https://graphql.org/learn/schema/'
),
(
    'Apollo Client error: Network error - Failed to fetch',
    'graphql',
    'CRITICAL',
    $$[{"solution": "Verify GraphQL endpoint URL is correct and server is running. Check for CORS issues if client and server on different origins", "percentage": 93, "note": "Network layer issues most common"}, {"solution": "Add CORS headers to GraphQL server: Access-Control-Allow-Origin. Use cors middleware in Express/Apollo", "percentage": 90, "note": "CORS required for cross-origin requests"}]$$::jsonb,
    'Apollo Client configured, GraphQL server running',
    'Queries execute successfully, no network errors',
    'Wrong endpoint URL, server not running, CORS not configured, network firewall issues',
    0.91,
    'sonnet-4',
    NOW(),
    'https://www.apollographql.com/docs/react/data/queries/'
),
(
    'Apollo Client error: Cache data may be lost when replacing field',
    'graphql',
    'MEDIUM',
    $$[{"solution": "Configure merge function in type policies for arrays: typePolicies: { Query: { fields: { items: { merge(existing, incoming) { return incoming } } } } }", "percentage": 89, "note": "Custom merge handles array updates"}, {"solution": "Use fetchPolicy: network-only to bypass cache if cache consistency is not needed", "percentage": 85, "note": "Network-only avoids cache issues"}]$$::jsonb,
    'Apollo Client with caching, understanding of type policies',
    'Cache updates correctly, no data loss warnings',
    'No merge function for array fields, assuming default merge works for lists, stale cache data',
    0.87,
    'sonnet-4',
    NOW(),
    'https://www.apollographql.com/docs/react/caching/cache-field-behavior/'
),
(
    'GraphQL error: Subscription failed - WebSocket connection error',
    'graphql',
    'HIGH',
    $$[{"solution": "Configure WebSocket link with correct subscription endpoint (usually ws:// or wss://). Separate from HTTP endpoint", "percentage": 91, "note": "Subscriptions use WebSocket protocol"}, {"solution": "Split link to use WebSocket for subscriptions and HTTP for queries/mutations using split() function", "percentage": 88, "note": "Different transports for different operations"}]$$::jsonb,
    'Apollo Client subscriptions configured, WebSocket server running',
    'Subscriptions connect and receive updates, no connection errors',
    'Using HTTP URL for WebSocket, not splitting links, WebSocket server not running, firewall blocking WS',
    0.89,
    'sonnet-4',
    NOW(),
    'https://www.apollographql.com/docs/react/data/subscriptions/'
),
(
    'GraphQL error: Maximum query depth exceeded',
    'graphql',
    'MEDIUM',
    $$[{"solution": "Simplify query by reducing nesting levels. Flatten data requirements or use multiple simpler queries", "percentage": 88, "note": "Deep queries indicate potential N+1 issues"}, {"solution": "Request server admin to increase depth limit if query depth is legitimately needed for use case", "percentage": 82, "note": "Depth limits are configurable server-side"}]$$::jsonb,
    'GraphQL query optimization knowledge, understanding of depth limits',
    'Query executes within depth limits, returns required data',
    'Over-fetching nested relations, circular references in query, not understanding depth implications',
    0.85,
    'sonnet-4',
    NOW(),
    'https://www.apollographql.com/docs/apollo-server/security/authentication/'
);
