INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('TimeoutError: Timeout 30000ms exceeded', 'testing', 'HIGH', '[{"solution": "Increase global timeout in playwright.config.ts: globalTimeout: 60000", "percentage": 92}, {"solution": "Set action timeout: await page.click(selector, { timeout: 60000 })", "percentage": 85}, {"solution": "Use expect().toHaveTimeout() with longer duration", "percentage": 78}]'::jsonb, 'Playwright test setup with default timeout', 'Tests complete within timeout, no TimeoutError thrown', 'Not setting adequate timeout for slow operations, async operations not awaited', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77747778/timeouterrortimeouterrortimeout-30000ms-exceeded-playwright', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('TimeoutError when clicking a button in Playwright', 'testing', 'HIGH', '[{"solution": "Wait for element visibility: await page.waitForSelector(selector, { visible: true })", "percentage": 90}, {"solution": "Increase click timeout: await locator.click({ timeout: 10000 })", "percentage": 88}, {"solution": "Use force click if element is technically visible: await locator.click({ force: true })", "percentage": 75}]'::jsonb, 'Playwright with page object and click actions', 'Button click completes without timeout, element visible and clickable', 'Element not visible, lazy loading not awaited, wrong selector', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/78055408/timeouterror-when-clicking-a-button-in-playwright', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright no tests found error', 'testing', 'HIGH', '[{"solution": "Rename test files to *.spec.ts pattern", "percentage": 95}, {"solution": "Update Playwright to latest: npm install @playwright/test@latest", "percentage": 91}, {"solution": "Configure testDir in playwright.config.ts correctly", "percentage": 87}]'::jsonb, 'Playwright test setup with spec files', 'Tests discovered and executed successfully', 'Wrong file naming (not .spec.ts), test directory not configured, dependencies outdated', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/71053528/playwright-no-tests-found-on-simple-copy-of-example-spec-ts', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Protocol error: Browser.getVersion browser closed', 'testing', 'HIGH', '[{"solution": "Increase launch timeout: browserType.launch({ timeout: 30000 })", "percentage": 88}, {"solution": "Check system resources (memory, file descriptors available)", "percentage": 82}, {"solution": "Avoid closing browser in hooks before tests complete", "percentage": 80}]'::jsonb, 'Browser instance management in tests', 'Browser launches and stays open during test execution', 'Browser closed unexpectedly, connection lost, resource exhaustion', 0.75, 'haiku', NOW(), 'https://stackoverflow.com/questions/69431596/error-browsertype-launch-protocol-error-browser-getversion-browser-closed-w', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright error: Target closed after navigation', 'testing', 'HIGH', '[{"solution": "Await page navigation: await page.goto(url)", "percentage": 93}, {"solution": "Do not close browser during active navigation", "percentage": 88}, {"solution": "Use page.waitForNavigation() if needed: await Promise.all([page.waitForNavigation(), page.click(selector)])", "percentage": 82}]'::jsonb, 'Page navigation with browser context management', 'Navigation completes and page remains accessible', 'Browser/context closed during navigation, page goto without await, race condition', 0.8, 'haiku', NOW(), 'https://stackoverflow.com/questions/61933492/playwright-error-target-closed-after-navigation', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright navigation failed: page crashed', 'testing', 'HIGH', '[{"solution": "Increase browser memory: LaunchOptions with increased memory limits", "percentage": 85}, {"solution": "Limit concurrent browser instances: use workers config", "percentage": 83}, {"solution": "Close pages after tests: await page.close()", "percentage": 79}]'::jsonb, 'Complex page interactions and navigation', 'Page navigates without crash, load completes', 'Out of memory, too many concurrent pages, browser crash', 0.72, 'haiku', NOW(), 'https://stackoverflow.com/questions/65731290/navigation-failed-because-page-crashed-javascript-playwright', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright element not visible error', 'testing', 'HIGH', '[{"solution": "Use isVisible() check: if (await locator.isVisible())", "percentage": 91}, {"solution": "Force click with visible check: await locator.click({ timeout: 10000 })", "percentage": 87}, {"solution": "Wait for element stability: await expect(locator).toBeVisible()", "percentage": 85}]'::jsonb, 'Element selection and visibility checks', 'Element visible and interactions succeed', 'Display none, overflow hidden, z-index issues, element off-screen', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/70179441/check-if-element-is-visible-in-playwright', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Strict mode violation: locator matching multiple elements', 'testing', 'HIGH', '[{"solution": "Use .first() or .nth() to specify element: locator.first()", "percentage": 92}, {"solution": "Use more specific selector with unique attributes", "percentage": 89}, {"solution": "Disable strict mode if needed: locator.click({ strict: false })", "percentage": 65}]'::jsonb, 'Selectors and element matching in Playwright', 'Selector matches exactly one element', 'Generic selectors, multiple matching elements, missing unique identifiers', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/75658146/strict-mode-violation-error-happens-when-i-try-select-an-option-which-is-a-subst', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright locator error: strict mode violation', 'testing', 'HIGH', '[{"solution": "Filter locator: page.locator(btn).filter({ has: page.locator(data) })", "percentage": 88}, {"solution": "Use label or testid: locator(data-testid=btn)", "percentage": 90}, {"solution": "Use parent context: locator(xpath=//div[@class=form]//button)", "percentage": 79}]'::jsonb, 'Locator API usage in Playwright', 'Locator selects single unique element, no ambiguity', 'Multiple matching elements, selector too generic', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/76043713/playwright-locator-error-strict-mode-violation', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright target closed error: browser context closed', 'testing', 'HIGH', '[{"solution": "Ensure context not closed: verify close() called only at test end", "percentage": 93}, {"solution": "Use context fixture: test.use({ context: ... })", "percentage": 87}, {"solution": "Catch and ignore target closed errors gracefully", "percentage": 72}]'::jsonb, 'Browser and context lifecycle management', 'Context remains open during test execution', 'Premature context.close(), page operations after context closed', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/75904745/playwright-receiving-error-locator-click-target-page-context-or-browser-has', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright selector timeout: wait for selector error', 'testing', 'HIGH', '[{"solution": "Increase timeout: await page.waitForSelector(selector, { timeout: 10000 })", "percentage": 91}, {"solution": "Verify selector accuracy: use devtools inspector to test", "percentage": 88}, {"solution": "Wait for parent element first if nested: await page.waitForSelector(parent)", "percentage": 81}]'::jsonb, 'DOM waiting and selector matching', 'Selector found and element available within timeout', 'Element not in DOM, wrong selector syntax, timeout too short', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/66490575/how-can-i-handle-the-wait-for-selector-functions-timeouterror-in-playwright-pyt', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright failed to install browser binaries', 'testing', 'HIGH', '[{"solution": "Run: npx playwright install", "percentage": 94}, {"solution": "Check disk space: ensure at least 500MB free", "percentage": 85}, {"solution": "Clear cache: rm -rf ~/.cache/ms-playwright and reinstall", "percentage": 82}]'::jsonb, 'Playwright installation and browser setup', 'Browsers installed and available in cache directory', 'Network issues, insufficient disk space, permission denied', 0.79, 'haiku', NOW(), 'https://stackoverflow.com/questions/78806528/error-while-downloading-playwright-browser-binaries', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ERR_HTTP2_PROTOCOL_ERROR in Playwright', 'testing', 'HIGH', '[{"solution": "Disable HTTP/2: use ignoreHTTPSErrors: true in browser launch", "percentage": 76}, {"solution": "Add to config: acceptInsecureCerts: true", "percentage": 72}, {"solution": "Use specific user agent to avoid HTTP/2 incompatibility", "percentage": 68}]'::jsonb, 'HTTP/2 request handling in Playwright', 'Page loads without protocol errors', 'Server HTTP/2 issues, incorrect content encoding, firewall rules', 0.73, 'haiku', NOW(), 'https://stackoverflow.com/questions/77417256/error-in-playwright-using-python-playwright-impl-api-types-error-neterr-ht', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright force click on hidden element', 'testing', 'HIGH', '[{"solution": "Use force flag: await locator.click({ force: true })", "percentage": 92}, {"solution": "Make element visible first: await page.evaluate(() => element.style.display = block)", "percentage": 85}, {"solution": "Use keyboard interaction instead: await locator.focus(); await page.keyboard.press(Enter)", "percentage": 78}]'::jsonb, 'Hidden element interaction in tests', 'Click succeeds on hidden element without visibility error', 'Using force:true incorrectly, element still not found', 0.8, 'haiku', NOW(), 'https://stackoverflow.com/questions/70124342/playwright-force-click-on-hidden-element-does-not-work', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright wait for selector timeout', 'testing', 'HIGH', '[{"solution": "Try alternative selector: use CSS or XPath validation", "percentage": 87}, {"solution": "Add explicit wait with state: await page.waitForLoadState(networkidle)", "percentage": 84}, {"solution": "Debug with inspector: npx playwright test --debug to find correct selector", "percentage": 82}]'::jsonb, 'Async DOM waiting in Playwright', 'Selector available within specified timeout duration', 'Selector never appears, incorrect selector syntax, race conditions', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/67787470/playwright-js-how-to-globally-define-change-timeout-if-element-selector-not-fo', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright check if element is visible', 'testing', 'HIGH', '[{"solution": "Use isVisible(): const visible = await locator.isVisible()", "percentage": 93}, {"solution": "Use expect: await expect(locator).toBeVisible()", "percentage": 90}, {"solution": "Check with getBoundingBox(): const box = await locator.boundingBox()", "percentage": 77}]'::jsonb, 'Element visibility detection', 'Correctly identify visible vs hidden elements', 'Element in DOM but hidden, CSS visibility vs display, viewport bounds', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/76093014/when-is-playwrights-waitforselector-necessary', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright prevent test timeout after 30 seconds', 'testing', 'HIGH', '[{"solution": "Set global timeout: timeout: 60000 in config", "percentage": 91}, {"solution": "Per-test timeout: test.setTimeout(60000) before test definition", "percentage": 88}, {"solution": "Per-action timeout: await locator.click({ timeout: 60000 })", "percentage": 85}]'::jsonb, 'Test timeout configuration', 'Tests run to completion without timeout interruption', 'Config not applied, wrong scope (test vs action vs global)', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/77035874/prevent-playwright-test-from-timing-out-after-30-seconds', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright page goto navigation failed: page was closed', 'testing', 'HIGH', '[{"solution": "Verify page not closed: check page.isClosed() before operations", "percentage": 89}, {"solution": "Use page fixture: let page; beforeEach(() => { page = ... })", "percentage": 86}, {"solution": "Wrap in try-catch: catch page closed error and recreate if needed", "percentage": 74}]'::jsonb, 'Page lifecycle and navigation management', 'Page remains open throughout navigation sequence', 'Page closed in beforeEach/afterEach hook, context closed prematurely', 0.78, 'haiku', NOW(), 'https://stackoverflow.com/questions/76265206/playwright-page-goto-navigation-failed-because-page-was-closed-on-render', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright how to globally define change timeout if element selector not found', 'testing', 'HIGH', '[{"solution": "Set in config: use: { actionTimeout: 10000 }", "percentage": 90}, {"solution": "Set global default: timeout: 30000 in playwright.config.ts", "percentage": 88}, {"solution": "Per-operation override: waitForSelector(sel, { timeout: 15000 })", "percentage": 81}]'::jsonb, 'Global timeout configuration for selectors', 'All selectors use configured timeout duration', 'Timeout not applied uniformly, action timeout vs wait timeout', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/67787470/playwright-js-how-to-globally-define-change-timeout-if-element-selector-not-fo', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright when is wait for selector necessary', 'testing', 'HIGH', '[{"solution": "Use auto-waiting: locator automatically waits by default", "percentage": 88}, {"solution": "Explicit wait for state: await page.waitForLoadState(domcontentloaded)", "percentage": 84}, {"solution": "Use page condition: await page.waitForFunction(() => document.readyState === complete)", "percentage": 79}]'::jsonb, 'Understanding Playwright waiting strategy', 'Correct use of wait functions in appropriate scenarios', 'Over-waiting, missing necessary waits, wrong wait condition', 0.76, 'haiku', NOW(), 'https://stackoverflow.com/questions/76093014/when-is-playwrights-waitforselector-necessary', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright element found but continues to show as hidden', 'testing', 'HIGH', '[{"solution": "Check parent visibility: await page.locator(:has-text=text).first().isVisible()", "percentage": 86}, {"solution": "Wait for animation: await page.waitForLoadState(networkidle)", "percentage": 81}, {"solution": "Use evaluate to check computed style: getComputedStyle check on element", "percentage": 78}]'::jsonb, 'Element visibility state detection', 'Element found and interactable when visibility confirmed', 'Parent hidden, CSS animations in progress, z-index occlusion', 0.8, 'haiku', NOW(), 'https://stackoverflow.com/questions/77804819/playwright-element-found-but-continues-to-show-as-hidden', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright locator click target page context or browser has been closed', 'testing', 'HIGH', '[{"solution": "Check page open: if (!page.isClosed()) await locator.click()", "percentage": 91}, {"solution": "Ensure proper async handling: await all promises before closing", "percentage": 88}, {"solution": "Use test.after() instead of afterEach() to delay cleanup", "percentage": 79}]'::jsonb, 'Context and page lifecycle handling', 'Click operations succeed without target closed errors', 'Async operation after page closed, context closed in afterEach', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/74457594/playwright-getting-locator-click-target-closed-while-clicking-on-an-element', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright assert that element is not on the page', 'testing', 'HIGH', '[{"solution": "Use toHaveCount(0): await expect(locator).toHaveCount(0)", "percentage": 94}, {"solution": "Use toBeHidden(): await expect(locator).toBeHidden()", "percentage": 89}, {"solution": "Check isVisible(): const visible = await locator.isVisible(); expect false", "percentage": 82}]'::jsonb, 'Assertion of element absence in DOM', 'Correctly verify element not present in page', 'Checking wrong selector, element present but hidden', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/71183099/how-can-i-assert-that-an-element-is-not-on-the-page-in-playwright', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright vscode extension shows no tests found', 'testing', 'HIGH', '[{"solution": "Update extension: install latest from VSCode marketplace", "percentage": 93}, {"solution": "Reload VSCode: Cmd+Shift+P > Developer: Reload Window", "percentage": 90}, {"solution": "Ensure .spec.ts pattern: test files must match testMatch config", "percentage": 87}]'::jsonb, 'Playwright VSCode extension setup', 'VSCode discovers and displays test cases', 'Extension outdated, wrong file pattern, dependency mismatch', 0.79, 'haiku', NOW(), 'https://stackoverflow.com/questions/72100106/playwright-vscode-gives-no-tests-found-message', 'admin:1764226271');
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright browserType.launch() timeout exceeded', 'testing', 'HIGH', '[{"solution": "Increase browser launch timeout: browserType.launch({ timeout: 60000 })", "percentage": 92}, {"solution": "Check system resources and available memory", "percentage": 85}, {"solution": "Use headless: false to debug browser startup issues", "percentage": 78}]'::jsonb, 'Browser launch configuration in Playwright', 'Browser launches successfully within timeout period', 'Browser takes too long to initialize, resource constraints, missing binaries', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/75259681/playwright-error-browsertype-launch-timeout-180000ms-exceeded-at-object-playwr', 'admin:1764226271');
