INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('EXC_BAD_ACCESS SIGSEGV null pointer dereference', 'ios-crashes', 'CRITICAL', '[{"solution": "Use guard statements to check for nil before accessing: guard let obj = myObject else { return }", "percentage": 95}, {"solution": "Enable NSZombieEnabled in scheme to detect use-after-free", "percentage": 90}, {"solution": "Check pointer arithmetic - ensure addresses are valid before dereferencing", "percentage": 85}]'::jsonb, 'Objective-C memory management knowledge', 'App no longer crashes accessing nil memory', 'Forgetting to initialize pointers, not checking nil before messaging', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/7446655/exception-types-in-ios-crash-logs', 'admin:1764217410'),

('EXC_BAD_ACCESS SIGBUS bus error unaligned access', 'ios-crashes', 'HIGH', '[{"solution": "Check memory alignment: use proper data structure alignment with __attribute__((packed)) if needed", "percentage": 88}, {"solution": "Verify pointer points to valid memory address that exists", "percentage": 90}, {"solution": "Use Instruments Memory Graph to detect invalid references", "percentage": 85}]'::jsonb, 'Understanding hardware memory access', 'No SIGBUS crashes on device', 'Attempting to access unmapped memory regions, improper alignment', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/16211757/what-do-the-different-exception-codes-in-os-x-ios-crash-reports-mean', 'admin:1764217410'),

('EXC_CRASH SIGABRT abort signal program termination', 'ios-crashes', 'CRITICAL', '[{"solution": "Use @try @catch blocks to intercept NSExceptions before abort", "percentage": 92}, {"solution": "Check for double-free: use instruments to find premature deallocations", "percentage": 90}, {"solution": "Verify NSAutoreleasePool is not draining prematurely", "percentage": 88}]'::jsonb, 'Exception handling Objective-C', 'NSException caught and handled gracefully', 'Not checking array bounds, releasing objects twice, missing @catch', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/28014031/understanding-ios-crash-sigabrt-abort', 'admin:1764217410'),

('EXC_BREAKPOINT SIGTRAP debugger trap signal', 'ios-crashes', 'MEDIUM', '[{"solution": "Check if debugger is attached - use getpid() to verify execution context", "percentage": 85}, {"solution": "Remove __builtin_trap() calls from production code", "percentage": 90}, {"solution": "Verify breakpoints are cleared from release builds via striped symbols", "percentage": 88}]'::jsonb, 'Xcode debugger experience', 'No unexpected SIGTRAP in production builds', 'Leaving breakpoints in production code, debugger-only traps', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/13980231/list-of-ios-exception-codes', 'admin:1764217410'),

('EXC_RESOURCE WAKEUPS excessive thread wake cycles', 'ios-crashes', 'HIGH', '[{"solution": "Reduce sleep/wake cycle frequency: check timer intervals are >= 1 second", "percentage": 92}, {"solution": "Use GCD queues instead of manual thread management for better efficiency", "percentage": 88}, {"solution": "Replace SemaphoreSlim with AutoResetEvent if synchronizing threads", "percentage": 90}]'::jsonb, 'Grand Central Dispatch threading', 'Thread wake rate under 150/sec confirmed in Instruments', 'Excessive polling loops, tight wait conditions, incorrect locking', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/25848441/app-shutdown-with-exc-resource-wakeups-exception-on-ios-8-gm', 'admin:1764217410'),

('EXC_CRASH SIGKILL watchdog timeout 0x8BADF00D', 'ios-crashes', 'CRITICAL', '[{"solution": "Replace performBlockAndWait with performBlock to avoid main thread blocking", "percentage": 94}, {"solution": "Move long operations to background threads: dispatch_async(dispatch_get_global_queue()...)", "percentage": 96}, {"solution": "Ensure all network calls have proper timeouts and cancellation tokens", "percentage": 90}]'::jsonb, 'Core Data threading, async patterns', 'Scene update completes within 10 second watchdog window', 'Blocking main thread with synchronous operations, unhandled deadlocks', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/72010502/how-to-fix-exc-crash-sigkill-watchdog-termination', 'admin:1764217410'),

('Heap corruption detected malloc free list damaged', 'ios-crashes', 'HIGH', '[{"solution": "Set breakpoint on malloc_error_break in Xcode to trap corruption immediately", "percentage": 92}, {"solution": "Use Address Sanitizer (ASan) to detect buffer overflows: -fsanitize=address", "percentage": 95}, {"solution": "Check for off-by-one errors in array access and string buffers", "percentage": 88}]'::jsonb, 'Memory debugging with Xcode Instruments', 'No malloc errors after Address Sanitizer pass', 'Buffer overflows, writing past array bounds, use-after-free', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/52420160/ios-error-heap-corruption-detected-free-list-is-damaged-and-incorrect-guard-v', 'admin:1764217410'),

('Double free malloc corruption same object freed twice', 'ios-crashes', 'HIGH', '[{"solution": "Use ARC (Automatic Reference Counting) to eliminate manual release: always use strong/weak properties", "percentage": 97}, {"solution": "Enable NSZombieEnabled to detect double-frees in debugger", "percentage": 94}, {"solution": "Audit all [object release] calls - should only appear in dealloc for manual memory", "percentage": 90}]'::jsonb, 'Manual memory management, ARC conversion', 'Zero double-free crashes after ARC migration', 'Multiple release calls, forgetting retain/release semantics', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/971249/how-to-find-the-cause-of-a-malloc-double-free-error', 'admin:1764217410'),

('NSRangeException array index out of bounds', 'ios-crashes', 'HIGH', '[{"solution": "Always check array count before accessing: if (index < array.count)", "percentage": 96}, {"solution": "Use safe accessors: [array firstObject] instead of [array objectAtIndex:0]", "percentage": 95}, {"solution": "Add guard in table data source: return 0 if array is empty in numberOfRowsInSection:", "percentage": 94}]'::jsonb, 'Array bounds checking iOS', 'No NSRangeException crashes in testing', 'Off-by-one errors, not checking empty arrays, race conditions', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/40813605/terminating-app-due-to-uncaught-exception-nsrangeexception-reason-n', 'admin:1764217410'),

('NSInvalidArgumentException nil argument to method', 'ios-crashes', 'HIGH', '[{"solution": "Validate all arguments at method entry: if (!argument) { return NO; }", "percentage": 95}, {"solution": "Break complex one-liners into steps for clarity and null-checking", "percentage": 92}, {"solution": "Check componentsSeparatedByString has non-nil separator before calling", "percentage": 94}]'::jsonb, 'Defensive programming Objective-C', 'All arguments validated before use', 'Passing nil values, not checking IBOutlet connections, missing initialization', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/14163308/ios-app-nsinvalidargumentexception', 'admin:1764217410'),

('EXC_BAD_INSTRUCTION SIGILL illegal processor instruction', 'ios-crashes', 'MEDIUM', '[{"solution": "Check for incompatible SDK calls: verify deployment target matches actual iOS version", "percentage": 92}, {"solution": "Rebuild after clean: rm -rf Build folder, then rebuild from source", "percentage": 88}, {"solution": "Verify app doesn''t call functions only available in newer iOS versions", "percentage": 90}]'::jsonb, 'iOS SDK deployment targets', 'App launches without SIGILL on target iOS version', 'Using newer SDK features on older devices, corrupted binary', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/17669329/app-crashes-with-exc-bad-instruction-sigill', 'admin:1764217410'),

('SIGPIPE broken pipe socket closed', 'ios-crashes', 'HIGH', '[{"solution": "Add signal(SIGPIPE, SIG_IGN) early in main() to globally ignore SIGPIPE", "percentage": 94}, {"solution": "Use setsockopt(sock, SOL_SOCKET, SO_NOSIGPIPE, &value, sizeof(value)) on each socket", "percentage": 96}, {"solution": "Handle network disconnection gracefully: implement timeout handlers and retry logic", "percentage": 90}]'::jsonb, 'POSIX socket programming iOS', 'SIGPIPE handled gracefully on network disconnect', 'Not disabling SIGPIPE, not handling socket disconnection', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/32197319/network-code-stopping-with-sigpipe', 'admin:1764217410'),

('objc_msgSend crash message sent to deallocated object', 'ios-crashes', 'CRITICAL', '[{"solution": "Enable NSZombieEnabled: set NSZombieEnabled=YES in Environment Variables", "percentage": 96}, {"solution": "Check autorelease pool is not draining too early in background threads", "percentage": 92}, {"solution": "Verify strong references prevent premature deallocation of delegates", "percentage": 94}]'::jsonb, 'Xcode memory debugging tools', 'NSZombieEnabled identifies exact object and stack trace', 'Accessing released objects, missing strong references, wrong thread', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/1324868/how-best-to-debug-a-crash-within-objc-msgsend', 'admin:1764217410'),

('KVO observer over-released or smashed', 'ios-crashes', 'MEDIUM', '[{"solution": "Always keep strong reference to observer returned by addObserverForKeyPath:", "percentage": 93}, {"solution": "Call removeObserver in dealloc for legacy KVO observers", "percentage": 91}, {"solution": "Use new @ObservedReading property wrapper in Swift for type-safe KVO", "percentage": 90}]'::jsonb, 'Key-Value Observing iOS 11+', 'No observer-related crashes on iOS 11+', 'Not keeping observer reference, double-removing observer, wrong dealloc', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/50565332/kvo-observer-crash-on-ios-11', 'admin:1764217410'),

('EXC_ARITHMETIC floating point or integer division by zero', 'ios-crashes', 'MEDIUM', '[{"solution": "Always check divisor before division: if (denominator != 0)", "percentage": 98}, {"solution": "Use defensive programming: provide safe defaults if denominator is zero", "percentage": 95}, {"solution": "Add unit tests for boundary conditions: 0, negative, MAX values", "percentage": 93}]'::jsonb, 'Safe arithmetic iOS', 'All division operations verified to not divide by zero', 'Not checking denominator, off-by-one in loop counters', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/7704839/why-am-i-getting-an-exc-arithmetic-error-in-ios-app', 'admin:1764217410'),

('Unrecognized selector sent to instance NSException', 'ios-crashes', 'HIGH', '[{"solution": "Verify @synthesize exists for @property declarations in .m file", "percentage": 94}, {"solution": "Check IBOutlet connections in Interface Builder are properly wired", "percentage": 96}, {"solution": "Ensure class implements the selector method being called", "percentage": 95}]'::jsonb, 'Objective-C properties and selectors', 'Selector found on object without exception', 'Missing @synthesize, broken IBOutlet, typos in method names', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/3861603/unrecognized-selector-sent-to-instance', 'admin:1764217410'),

('SIGFPE floating point exception invalid arithmetic', 'ios-crashes', 'MEDIUM', '[{"solution": "Check for overflow/underflow: use safe arithmetic libraries for large numbers", "percentage": 90}, {"solution": "Validate float operations don''t produce NaN or Inf: use isnan() isfinite()", "percentage": 92}, {"solution": "Use integer arithmetic when possible to avoid float precision issues", "percentage": 88}]'::jsonb, 'Floating point safety', 'No SIGFPE after validation of float operations', 'Integer overflow, unvalidated float operations, NaN propagation', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/10315526/exc-bad-access-automatic-handling', 'admin:1764217410'),

('NSAutoreleasePool drain crashes premature release', 'ios-crashes', 'MEDIUM', '[{"solution": "Use modern ARC instead of manual NSAutoreleasePool management", "percentage": 98}, {"solution": "If using NSAutoreleasePool: create/drain in tight loops to prevent memory bloat", "percentage": 85}, {"solution": "Never hold references to auto-released objects after pool drains", "percentage": 92}]'::jsonb, 'ARC and memory management', 'ARC converted or NSAutoreleasePool drain tested successfully', 'Holding references after drain, releasing in wrong order', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/4357963/iphone-app-crashes-without-any-console-errors-or-crash-logs', 'admin:1764217410'),

('KERN_MEMORY_ERROR page fault unable to get data', 'ios-crashes', 'MEDIUM', '[{"solution": "Check for memory mapping issues: verify mmap calls succeed before access", "percentage": 86}, {"solution": "Handle file descriptor errors gracefully: check open() return value", "percentage": 88}, {"solution": "Ensure file exists and is readable before memory-mapping", "percentage": 90}]'::jsonb, 'Memory mapping and file I/O', 'File access succeeds after error checking', 'Not checking mmap result, file not found, permission denied', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/16211757/what-do-the-different-exception-codes-in-os-x-ios-crash-reports-mean', 'admin:1764217410'),

('NSInvalidArgumentException range beyond string length', 'ios-crashes', 'MEDIUM', '[{"solution": "Validate range before substring: if (range.location + range.length <= string.length)", "percentage": 95}, {"solution": "Use NSRange helper: NSMakeRange with validation of bounds", "percentage": 93}, {"solution": "Check string is not nil and not empty before string range operations", "percentage": 94}]'::jsonb, 'NSString range operations', 'Substring operations validated without exceptions', 'Off-by-one range errors, not checking string length', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/14163308/ios-app-nsinvalidargumentexception', 'admin:1764217410'),

('EXC_RESOURCE CPUMONITOR excessive CPU usage', 'ios-crashes', 'MEDIUM', '[{"solution": "Profile with Instruments CPU Profiler: find hot loops consuming CPU", "percentage": 92}, {"solution": "Add delays to background processing: usleep(100) to yield CPU", "percentage": 88}, {"solution": "Move heavy computation to background threads: dispatch_queue_create()", "percentage": 90}]'::jsonb, 'Xcode Instruments CPU profiling', 'CPU usage under 50% on sustained background activity', 'Busy waiting loops, intensive compute on main thread', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/46600674/iosfatal-exception-nsrangeexception', 'admin:1764217410'),

('NSNotificationCenter observer double removal crash', 'ios-crashes', 'MEDIUM', '[{"solution": "Only remove observer once in dealloc: use try-catch or check if still registered", "percentage": 92}, {"solution": "Use @try @catch around removeObserver to handle already-removed case", "percentage": 90}, {"solution": "Store observer reference and verify not nil before removal", "percentage": 88}]'::jsonb, 'NSNotificationCenter management', 'Observer cleanup succeeds without exceptions', 'Removing observer twice, missing dealloc cleanup', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/40667924/ios-app-crashes-because-kvo-observer-is-not-observing-anymore', 'admin:1764217410'),

('Thread race condition concurrent access to shared state', 'ios-crashes', 'HIGH', '[{"solution": "Use @synchronized(self) { } to protect shared mutable state", "percentage": 91}, {"solution": "Use dispatch_queue_t with serial dispatch for thread-safe access", "percentage": 94}, {"solution": "Use atomic properties: @property (atomic) for primitive types", "percentage": 88}]'::jsonb, 'Concurrency and thread safety', 'All shared state protected by synchronization primitives', 'Concurrent NSMutableArray/Dictionary access, missing locks', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/28014031/understanding-ios-crash-sigabrt-abort', 'admin:1764217410'),

('SIGILL incompatible SDK function not on device iOS', 'ios-crashes', 'MEDIUM', '[{"solution": "Use respondsToSelector: before calling new APIs: if ([object respondsToSelector:@selector(newMethod)])", "percentage": 96}, {"solution": "Check iOS version at runtime: if (@available(iOS 13, *)) { }", "percentage": 97}, {"solution": "Weak-link frameworks in Build Settings if using optional APIs", "percentage": 92}]'::jsonb, 'iOS SDK version compatibility', 'App runs on all target iOS versions without SIGILL', 'Calling iOS 13+ methods on iOS 12 device, weak-link not set', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/21839607/exc-bad-instruction-sigill-crash-after-few-days-running-an-os-x-app', 'admin:1764217410'),

('Memory leak unreleased allocations accumulate', 'ios-crashes', 'MEDIUM', '[{"solution": "Use Xcode Instruments Memory Leaks tool to find unreleased allocations", "percentage": 94}, {"solution": "Check for missing dealloc: use Instruments Allocations to track object lifetime", "percentage": 92}, {"solution": "Enable ARC and verify no strong reference cycles exist", "percentage": 96}]'::jsonb, 'Memory leak detection Instruments', 'Zero memory leaks detected in Instruments Leaks tool', 'Not releasing retained objects, strong reference cycles', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/22616873/how-can-i-solve-this-warning-in-ios-memory-leak', 'admin:1764217410');
