-- AWS Lambda Errors Mining - 35 entries
-- Mined from Stack Overflow on 2025-11-26

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('Runtime.ExitError: Runtime exited with error signal killed', 'aws-lambda', 'HIGH', '[{"solution": "Increase AWS Lambda Memory allocation (increase from 128MB to 512MB or higher)", "percentage": 95}, {"solution": "Reduce parallel S3 transfers by lowering max_concurrency parameter in TransferConfig", "percentage": 85}]'::jsonb, 'AWS Lambda function with file operations', 'Function executes successfully without OOM errors', 'Assuming only code optimization needed without checking memory limits', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/59057934', 'admin:1764217390'),

('Lambda monitoring and error tracking CloudWatch', 'aws-lambda', 'MEDIUM', '[{"solution": "Enable CloudWatch detailed monitoring for Lambda functions", "percentage": 90}, {"solution": "Use CloudWatch Logs Insights for querying error patterns", "percentage": 88}]'::jsonb, 'CloudWatch access and Lambda function deployed', 'Visible error metrics in CloudWatch dashboard', 'Not enabling detailed metrics by default', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/44796133', 'admin:1764217390'),

('Exception handling in AWS Lambda', 'aws-lambda', 'MEDIUM', '[{"solution": "Use try-catch blocks around error-prone code sections", "percentage": 92}, {"solution": "Implement custom error types and error handling middleware", "percentage": 85}]'::jsonb, 'Lambda runtime supports exception handling', 'No unhandled exceptions in CloudWatch logs', 'Catching all exceptions with generic handlers', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/61249222', 'admin:1764217390'),

('How to return errors in AWS Lambda Node.js through API Gateway', 'aws-lambda', 'HIGH', '[{"solution": "Use callback(null, errorResponse) instead of callback(errorResponse, null)", "percentage": 96}, {"solution": "Return properly formatted API Gateway response object with statusCode and body", "percentage": 94}]'::jsonb, 'Lambda with API Gateway integration', 'API returns proper HTTP status codes and error responses', 'Using callback signature in wrong order', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/53345168', 'admin:1764217390'),

('Signal error in AWS Lambda for Java without throwing exception', 'aws-lambda', 'LOW', '[{"solution": "Lambda must exit with explicit error status or throw exception for error signal", "percentage": 90}, {"solution": "Use context.fail() in older Lambda Java runtime versions", "percentage": 80}]'::jsonb, 'Java Lambda runtime environment', 'Function marked as failed in Lambda console', 'Expecting silent error handling without exceptions', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/45108530', 'admin:1764217390'),

('AWS Lambda error source and metrics dashboard', 'aws-lambda', 'MEDIUM', '[{"solution": "Use CloudWatch Metrics dashboard to view Error count and Invocation metrics", "percentage": 91}, {"solution": "Set up CloudWatch alarms on error thresholds", "percentage": 88}]'::jsonb, 'CloudWatch access and Lambda deployed', 'Visible error count metrics in dashboard', 'Not configuring custom metrics or alarms', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/71345893', 'admin:1764217390'),

('Error handling in aws-invoke Lambda', 'aws-lambda', 'MEDIUM', '[{"solution": "Write detailed log messages using console.log for error context", "percentage": 90}, {"solution": "Check FunctionResponseTypes and handle async invocation errors", "percentage": 85}]'::jsonb, 'Lambda SDK and CloudWatch Logs access', 'Errors properly logged and visible in CloudWatch', 'Not checking FunctionResponseTypes for async invocations', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/77840659', 'admin:1764217390'),

('Throw HTTP error code in AWS Lambda with Lambda Proxy', 'aws-lambda', 'HIGH', '[{"solution": "Return object with statusCode, headers, and body for proper HTTP response", "percentage": 96}, {"solution": "Use Lambda Proxy integration format for API Gateway", "percentage": 94}]'::jsonb, 'API Gateway Lambda Proxy integration enabled', 'API Gateway returns correct HTTP status codes', 'Returning raw error objects instead of formatted responses', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/60225185', 'admin:1764217390'),

('No module named lambda in Python Lambda function', 'aws-lambda', 'HIGH', '[{"solution": "Create lambda.py file in deployment package (not lambda.zip)", "percentage": 95}, {"solution": "Ensure handler path matches handler name in console (e.g., lambda.handler)", "percentage": 93}]'::jsonb, 'Python Lambda function deployment', 'Lambda function imports module successfully', 'Naming file as lambda.zip instead of lambda.py', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/35340921', 'admin:1764217390'),

('Runtime.ImportModuleError: Unable to import module ''lambda''', 'aws-lambda', 'HIGH', '[{"solution": "Install requests module in deployment package using pip install -r requirements.txt -t .", "percentage": 97}, {"solution": "Ensure all Python dependencies are included in zip file", "percentage": 95}]'::jsonb, 'Python 3.x Lambda runtime with pip', 'Module imports successfully without ImportModuleError', 'Missing pip dependencies in deployment package', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/72295947', 'admin:1764217390'),

('Cannot import npm package in AWS Lambda function', 'aws-lambda', 'MEDIUM', '[{"solution": "Install Node modules and include node_modules folder in deployment package", "percentage": 92}, {"solution": "Use npm install and zip entire project directory", "percentage": 90}]'::jsonb, 'Node.js Lambda runtime with npm', 'NPM packages import without errors', 'Not including node_modules in zip deployment', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/59183731', 'admin:1764217390'),

('Unable to import module main no module named main', 'aws-lambda', 'HIGH', '[{"solution": "Create lambda_function.py with lambda_handler function for Python 3.8+", "percentage": 96}, {"solution": "Update CDK to latest version (1.136 for v1 or 2.3.0+ for v2)", "percentage": 88}]'::jsonb, 'Python Lambda runtime with CDK deployment', 'Function imports and executes successfully', 'Using outdated CDK version with Python runtime', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/68763000', 'admin:1764217390'),

('AWS Lambda TypeScript Layer Runtime.ImportModuleError', 'aws-lambda', 'MEDIUM', '[{"solution": "For Node 18+, use layers without transpiled JavaScript as runtime lacks transpiler", "percentage": 91}, {"solution": "Pre-compile TypeScript to JavaScript in layers", "percentage": 89}]'::jsonb, 'Node.js 18+ Lambda runtime with TypeScript layers', 'Layer modules import without runtime errors', 'Assuming runtime supports TypeScript natively on Node18+', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/77252344', 'admin:1764217390'),

('AWS Lambda Runtime.ImportModuleError unable to import', 'aws-lambda', 'HIGH', '[{"solution": "Verify lambda_function.py handler function exists and is named correctly", "percentage": 95}, {"solution": "Check deployment package structure matches Lambda runtime expectations", "percentage": 93}]'::jsonb, 'Python Lambda runtime with proper deployment', 'Module imports successfully', 'Handler function name mismatch with Lambda configuration', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/79622536', 'admin:1764217390'),

('AWS CDK Lambda Runtime.ImportModuleError unable to import', 'aws-lambda', 'MEDIUM', '[{"solution": "Specify correct Lambda layer dependencies in CDK configuration", "percentage": 90}, {"solution": "Bundle dependencies using CDK bundling options", "percentage": 88}]'::jsonb, 'AWS CDK v1 or v2 with Lambda layers', 'CDK deployment succeeds with proper imports', 'Missing layer configuration in CDK stack', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/75972844', 'admin:1764217390'),

('Python Lambda Runtime.ImportModuleError CDK downgrade solution', 'aws-lambda', 'LOW', '[{"solution": "Downgrade CDK to 1.136 if using v1 or use 2.3.0-alpha.0 for v2", "percentage": 85}, {"solution": "Update Lambda runtime to latest supported Python version", "percentage": 82}]'::jsonb, 'AWS CDK version management', 'Lambda function executes without version conflicts', 'Using incompatible CDK versions', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/70669870', 'admin:1764217390'),

('Runtime.HandlerNotFound error in AWS Lambda', 'aws-lambda', 'HIGH', '[{"solution": "Match handler name in Lambda configuration to exported function (e.g., index.handler means index.js exports handler function)", "percentage": 96}, {"solution": "Verify exports.handler function exists in deployment package", "percentage": 95}]'::jsonb, 'Lambda function with Node.js runtime', 'Handler function found and executes', 'Handler configuration path mismatch with function name', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/57342817', 'admin:1764217390'),

('Lambda function returning Runtime.HandlerNotFound', 'aws-lambda', 'HIGH', '[{"solution": "Ensure handler export matches Lambda handler setting (exports.handler)", "percentage": 97}, {"solution": "Check Lambda basic settings Handler field in console", "percentage": 95}]'::jsonb, 'Lambda console access and function deployed', 'Handler found and function executes', 'Incorrect handler name in Lambda console settings', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/61856434', 'admin:1764217390'),

('Missing handler error in AWS Lambda', 'aws-lambda', 'MEDIUM', '[{"solution": "Update Lambda function handler setting in basic settings to correct path", "percentage": 93}, {"solution": "Use format: filename.functionname (e.g., index.handler)", "percentage": 91}]'::jsonb, 'Lambda function console access', 'Handler configuration applied successfully', 'Not changing handler setting in Lambda console', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/48266106', 'admin:1764217390'),

('AWS Lambda Runtime.HandlerNotFound Python', 'aws-lambda', 'MEDIUM', '[{"solution": "Create handler function in module matching handler configuration", "percentage": 94}, {"solution": "Ensure Python function exists and is properly exported", "percentage": 92}]'::jsonb, 'Python 3.x Lambda runtime', 'Handler function found and executes', 'Handler function not defined in Python module', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/68679177', 'admin:1764217390'),

('Runtime.HandlerNotFound with TypeScript compiled JavaScript', 'aws-lambda', 'MEDIUM', '[{"solution": "Ensure TypeScript is compiled to JavaScript before packaging", "percentage": 92}, {"solution": "Verify compiled .js files contain handler export", "percentage": 90}]'::jsonb, 'TypeScript Lambda with build process', 'Compiled JavaScript contains handler export', 'Uploading .ts files instead of compiled .js', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/69777338', 'admin:1764217390'),

('AWS Lambda Python handler missing on module', 'aws-lambda', 'HIGH', '[{"solution": "Define handler function in module with correct name matching Lambda handler setting", "percentage": 96}, {"solution": "Use lambda_handler or custom function name matching configuration", "percentage": 94}]'::jsonb, 'Python Lambda runtime with handler configuration', 'Handler function executes without errors', 'Function name not matching Lambda handler configuration', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/40741822', 'admin:1764217390'),

('Runtime.HandlerNotFound AWS Lambda Node.js', 'aws-lambda', 'HIGH', '[{"solution": "Verify exports.handler function exists in index.js (or configured handler file)", "percentage": 97}, {"solution": "Check handler format in Lambda console: filename.functionname", "percentage": 95}]'::jsonb, 'Node.js Lambda runtime with handler configuration', 'Handler function invokes successfully', 'Missing exports or incorrect handler path', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/68301586', 'admin:1764217390'),

('Handler lambda_handler missing on module lambda_function', 'aws-lambda', 'MEDIUM', '[{"solution": "Create lambda_function.py with lambda_handler function definition", "percentage": 95}, {"solution": "Update Lambda handler setting to lambda_function.lambda_handler", "percentage": 93}]'::jsonb, 'Python Lambda runtime with function naming', 'Handler function found and executes', 'Lambda handler name mismatch in configuration', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/69659778', 'admin:1764217390'),

('AWS Lambda task timed out after 15 minutes', 'aws-lambda', 'HIGH', '[{"solution": "Maximum Lambda execution time is 15 minutes (900 seconds) - redesign for shorter execution", "percentage": 90}, {"solution": "Break long-running tasks into smaller Lambda functions with Step Functions", "percentage": 88}]'::jsonb, 'AWS Lambda with long-running processes', 'Function completes within 15 minute limit', 'Attempting operations exceeding 15 minute timeout', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/43577746', 'admin:1764217390'),

('AWS Lambda Task timed out after 3 seconds', 'aws-lambda', 'HIGH', '[{"solution": "Increase timeout in Lambda function configuration (can go up to 15 minutes)", "percentage": 96}, {"solution": "Verify function execution time and optimize slow operations", "percentage": 90}]'::jsonb, 'Lambda function configuration access', 'Function executes and completes within timeout', 'Using default 3 second timeout for long operations', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/62948910', 'admin:1764217390'),

('Serverless Framework Lambda task timed out after 6 seconds', 'aws-lambda', 'MEDIUM', '[{"solution": "Update timeout in serverless.yml configuration file", "percentage": 93}, {"solution": "Increase default timeout for all functions in provider section", "percentage": 91}]'::jsonb, 'Serverless Framework with Lambda', 'Serverless deployment uses updated timeout', 'Not updating serverless.yml timeout settings', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/47594168', 'admin:1764217390'),

('Lambda task timeout after 3 seconds execution', 'aws-lambda', 'HIGH', '[{"solution": "Verify function timeout setting in Lambda console is appropriate", "percentage": 94}, {"solution": "Check if external API calls are causing delays", "percentage": 88}]'::jsonb, 'Lambda execution with external dependencies', 'Function completes before timeout', 'External API latency exceeding timeout threshold', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/71479510', 'admin:1764217390'),

('Catching Lambda timeout errors at code level', 'aws-lambda', 'MEDIUM', '[{"solution": "Use context.getRemainingTimeInMillis() to check remaining time", "percentage": 90}, {"solution": "Implement cleanup handlers before timeout occurs", "percentage": 85}]'::jsonb, 'Lambda runtime context API access', 'Graceful timeout handling with cleanup', 'Not checking remaining execution time', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/53478200', 'admin:1764217390'),

('Lambda task timed out general troubleshooting', 'aws-lambda', 'HIGH', '[{"solution": "Verify RDS/RDS Proxy connection strings are correct and accessible", "percentage": 92}, {"solution": "Use connection pooling to reduce connection overhead", "percentage": 88}]'::jsonb, 'Lambda with database connections', 'Database operations complete within timeout', 'Waiting for slow database connections', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/56748161', 'admin:1764217390'),

('Node.js task timed out after 6 seconds when invoking Lambda', 'aws-lambda', 'MEDIUM', '[{"solution": "Lambda waiting for Internet connection (likely missing VPC routes)", "percentage": 89}, {"solution": "Check VPC configuration and NAT Gateway for outbound Internet access", "percentage": 87}]'::jsonb, 'Lambda in VPC with network configuration', 'Lambda completes network requests successfully', 'Missing Internet route in Lambda VPC configuration', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/56170784', 'admin:1764217390'),

('Lambda task timed out with large S3 data processing', 'aws-lambda', 'MEDIUM', '[{"solution": "Use S3 Select for filtering instead of downloading entire file", "percentage": 91}, {"solution": "Process data with AWS Glue or EMR instead of Lambda for large datasets", "percentage": 85}]'::jsonb, 'Lambda with S3 bucket access and large data', 'Data processing completes within timeout', 'Attempting to process multi-GB files in Lambda', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/64423343', 'admin:1764217390'),

('TooManyRequestsException Lambda concurrency rate exceeded', 'aws-lambda', 'HIGH', '[{"solution": "Increase Lambda reserved concurrency limit in function configuration", "percentage": 94}, {"solution": "Use exponential backoff for API calls to respect rate limits", "percentage": 90}]'::jsonb, 'Lambda with concurrent invocations', 'No TooManyRequestsException errors', 'Exceeding unreserved concurrency quotas', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/36826352', 'admin:1764217390'),

('AWS Lambda SDK TooManyRequestsException error', 'aws-lambda', 'HIGH', '[{"solution": "Implement retry logic with exponential backoff in SDK calls", "percentage": 93}, {"solution": "Check AWS account service quotas and request increases", "percentage": 89}]'::jsonb, 'AWS SDK in Lambda with rate-limited APIs', 'SDK calls succeed without rate limit errors', 'Not implementing backoff for SDK operations', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/77907682', 'admin:1764217390'),

('Lambda TooManyRequestsException concurrent invocations', 'aws-lambda', 'HIGH', '[{"solution": "Reserved concurrency prevents this - set reserved concurrency above expected peak load", "percentage": 95}, {"solution": "Monitor and adjust concurrency settings based on actual usage patterns", "percentage": 92}]'::jsonb, 'Lambda function with concurrency configuration', 'Concurrent invocations succeed without throttling', 'Reserved concurrency set too low for workload', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/36679890', 'admin:1764217390'),

('Boto3 long-running Lambda invocations TooManyRequestsException', 'aws-lambda', 'MEDIUM', '[{"solution": "Use async invocation (InvocationType=Event) instead of synchronous for long operations", "percentage": 91}, {"solution": "Increase reserved concurrency for target Lambda function", "percentage": 88}]'::jsonb, 'Boto3 with Lambda invoke calls', 'Invocations succeed without rate throttling', 'Using synchronous invokes for long-running functions', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/70845281', 'admin:1764217390'),

('TooManyRequestsException Cognito AdminCreateUser in Lambda', 'aws-lambda', 'LOW', '[{"solution": "Move user creation outside of Lambda code - use Cognito triggers instead", "percentage": 88}, {"solution": "Implement request throttling and queue-based processing", "percentage": 82}]'::jsonb, 'AWS Cognito with Lambda integration', 'Users created without rate limit errors', 'Creating users in Lambda code instead of triggers', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/73440677', 'admin:1764217390')

ON CONFLICT DO NOTHING;
