INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('A RenderFlex overflowed by X pixels on the bottom', 'flutter-dart', 'VERY_HIGH', '[{"solution": "Wrap content in SingleChildScrollView to enable scrolling", "percentage": 85}, {"solution": "Use Expanded widget to force children to fit within available space", "percentage": 80}, {"solution": "Use ListView instead of Column for scrollable content", "percentage": 75}]'::jsonb, 'Flutter layout knowledge', 'UI renders without yellow/black striped pattern', 'Trying to fix with fixed heights instead of flexible layouts', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/49480051', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('A RenderFlex overflowed by X pixels on the right', 'flutter-dart', 'VERY_HIGH', '[{"solution": "Wrap Text in Flexible or Expanded widget inside Row", "percentage": 90}, {"solution": "Set maxLines and TextOverflow.ellipsis on Text widget", "percentage": 75}, {"solution": "Constrain the width of child widgets", "percentage": 70}]'::jsonb, 'Flutter flex layout', 'Text wraps and displays ellipsis when needed', 'Using SizedBox with fixed width not working due to flex layout phases', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/52833704', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('setState() called after dispose() error', 'flutter-dart', 'VERY_HIGH', '[{"solution": "Check mounted property before calling setState: if(mounted) setState(...)", "percentage": 95}, {"solution": "Cancel timers in dispose() method", "percentage": 85}, {"solution": "Use FutureBuilder or StreamBuilder instead of setState for async operations", "percentage": 80}]'::jsonb, 'Stateful widget lifecycle', 'No console error when navigating between screens', 'Not canceling async operations before widget is disposed', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/49340116', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('setState() called after dispose() in async flow', 'flutter-dart', 'HIGH', '[{"solution": "Wrap setState in if(mounted) check", "percentage": 95}, {"solution": "Cancel async operations (timers, futures) in dispose()", "percentage": 90}, {"solution": "Use try-catch to handle BuildContext invalidation", "percentage": 60}]'::jsonb, 'Async operations in Flutter', 'Smooth navigation without state errors', 'Calling setState from timer callback without checking mounted', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/65503573', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('MissingPluginException no implementation found', 'flutter-dart', 'HIGH', '[{"solution": "Run flutter pub get and flutter clean", "percentage": 80}, {"solution": "Ensure plugin is properly declared in pubspec.yaml", "percentage": 85}, {"solution": "Rebuild and reinstall the app completely", "percentage": 75}]'::jsonb, 'Flutter platform channels', 'Plugin method calls succeed', 'Not rebuilding app after adding platform-specific code', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/50459272', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('PlatformException sign in canceled', 'flutter-dart', 'MEDIUM', '[{"solution": "Wrap platform calls in try-catch with PlatformException handler", "percentage": 90}, {"solution": "Check error code and message in catch block", "percentage": 85}, {"solution": "Verify Google Sign In configuration in Android/iOS", "percentage": 75}]'::jsonb, 'Platform exception handling', 'Auth dialog closes gracefully', 'Not catching PlatformException separately from other exceptions', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/56080818', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('FormatException unexpected character at character 1', 'flutter-dart', 'HIGH', '[{"solution": "Wrap jsonDecode in try-catch for FormatException", "percentage": 95}, {"solution": "Validate JSON response before parsing", "percentage": 90}, {"solution": "Check for null or empty responses before decode", "percentage": 85}]'::jsonb, 'JSON parsing in Dart', 'API responses parsed without format errors', 'Attempting to decode malformed JSON or null responses', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/55671441', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NoSuchMethodError method ''map'' called on null', 'flutter-dart', 'HIGH', '[{"solution": "Initialize list with empty list [] instead of null", "percentage": 95}, {"solution": "Check if list exists before calling map()", "percentage": 90}, {"solution": "Use null coalescing operator: list ?? []", "percentage": 85}]'::jsonb, 'Null safety in Dart', 'No NoSuchMethodError in debug output', 'Not initializing list variables before using them', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/52898792', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Cannot enable null safety requires non-nullable language feature', 'flutter-dart', 'MEDIUM', '[{"solution": "Update pubspec.yaml to SDK >= 2.12.0", "percentage": 95}, {"solution": "Run dart pub upgrade --null-safety", "percentage": 90}, {"solution": "Run dart migrate to auto-migrate code", "percentage": 80}]'::jsonb, 'Null safety migration', 'Project compiles with null safety enabled', 'Using outdated Dart SDK version', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/64621051', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Cannot run with sound null safety because dependencies dont support', 'flutter-dart', 'MEDIUM', '[{"solution": "Use dependency_overrides in pubspec.yaml to force compatible versions", "percentage": 85}, {"solution": "Update all dependencies with pub upgrade --null-safety", "percentage": 80}, {"solution": "Add --no-sound-null-safety flag to run (temporary fix)", "percentage": 40}]'::jsonb, 'Dependency management', 'Project runs with null safety enabled', 'Having dependencies that haven''t migrated to null safety', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/64917744', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('FAILURE Build failed with an exception Gradle compileFlutterBuildDebug', 'flutter-dart', 'HIGH', '[{"solution": "Run flutter clean to clear build cache", "percentage": 90}, {"solution": "Delete android/app/build folder and rebuild", "percentage": 85}, {"solution": "Run flutter pub get to sync dependencies", "percentage": 80}]'::jsonb, 'Flutter build system', 'App builds and runs successfully', 'Not clearing build cache after major changes', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/72617791', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('FlutterError unable to load asset images/file', 'flutter-dart', 'VERY_HIGH', '[{"solution": "Check pubspec.yaml indentation in assets section (use spaces not tabs)", "percentage": 95}, {"solution": "Verify file paths exactly match pubspec.yaml declarations", "percentage": 95}, {"solution": "Run flutter clean before rebuilding", "percentage": 85}]'::jsonb, 'Asset management', 'Images load from assets without errors', 'Incorrect indentation or wrong file paths in pubspec.yaml', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/53659809', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('AssetImage not displaying in Flutter app', 'flutter-dart', 'HIGH', '[{"solution": "Verify image file exists in assets folder", "percentage": 95}, {"solution": "Check pubspec.yaml has correct asset paths", "percentage": 95}, {"solution": "Try .jpeg extension instead of .jpg", "percentage": 60}]'::jsonb, 'Image loading', 'Images display correctly in app UI', 'File extension mismatch or incorrect folder structure', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/52033603', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Because dependency X conflicts version solving failed', 'flutter-dart', 'HIGH', '[{"solution": "Use dependency_overrides to force compatible version", "percentage": 90}, {"solution": "Use any version constraint instead of specific version", "percentage": 60}, {"solution": "Update conflicting packages to latest versions", "percentage": 75}]'::jsonb, 'Pubspec management', 'flutter pub get succeeds without conflicts', 'Pinning incompatible dependency versions', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/64984277', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Type mismatch String? cannot be assigned to String', 'flutter-dart', 'HIGH', '[{"solution": "Declare variable as nullable: String? varName", "percentage": 95}, {"solution": "Add null check before using: if (val != null)", "percentage": 90}, {"solution": "Use null coalescing: val ?? defaultValue", "percentage": 85}]'::jsonb, 'Null safety type system', 'Code compiles without type errors', 'Mixing nullable and non-nullable types without proper handling', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/67827345', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('SocketException connection failed network unreachable', 'flutter-dart', 'HIGH', '[{"solution": "Replace localhost with actual IP for device testing", "percentage": 95}, {"solution": "Ensure device has network connectivity", "percentage": 90}, {"solution": "Check firewall rules and port availability", "percentage": 75}]'::jsonb, 'Network debugging', 'HTTP requests succeed to backend', 'Using localhost URL when testing on physical device', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/51325758', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('RangeError index out of range no indices valid', 'flutter-dart', 'HIGH', '[{"solution": "Check list length before accessing by index", "percentage": 95}, {"solution": "Use safe access: if (index < list.length)", "percentage": 95}, {"solution": "Validate data before building widgets with list items", "percentage": 90}]'::jsonb, 'List safety', 'App renders lists without range errors', 'Accessing list index without bounds checking', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/66248873', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('UnsupportedError cannot add to unmodifiable list', 'flutter-dart', 'MEDIUM', '[{"solution": "Create mutable copy of list: List.of(immutableList)", "percentage": 95}, {"solution": "Use List<T>.from() or [...list] to create mutable list", "percentage": 95}, {"solution": "Check if list is unmodifiable before adding", "percentage": 80}]'::jsonb, 'Dart collection types', 'List modifications succeed without errors', 'Trying to modify immutable lists from API responses', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/70667422', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Error the name X is defined in ambiguous libraries', 'flutter-dart', 'MEDIUM', '[{"solution": "Use import alias: import ''package:x'' as x", "percentage": 95}, {"solution": "Hide conflicting name: hide X in one import", "percentage": 90}, {"solution": "Specify full package path when using class", "percentage": 75}]'::jsonb, 'Import management', 'Code compiles without import conflicts', 'Importing same class name from multiple packages', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/72838984', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('HTTP error 403 Forbidden access denied', 'flutter-dart', 'HIGH', '[{"solution": "Add authorization headers to request", "percentage": 95}, {"solution": "Check API key or credentials", "percentage": 90}, {"solution": "Verify user permissions for resource", "percentage": 85}]'::jsonb, 'HTTP requests', 'API calls return 200 with data', 'Missing authentication in request headers', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/73711489', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('TimeoutException Future not completed', 'flutter-dart', 'MEDIUM', '[{"solution": "Use Future.wait with timeout parameter", "percentage": 90}, {"solution": "Increase timeout duration for slow operations", "percentage": 85}, {"solution": "Check database/API response times", "percentage": 75}]'::jsonb, 'Async operations', 'Futures complete within timeout', 'Setting timeouts too short for actual operation duration', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/69011992', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('FlutterError widget unmounted state no longer has context', 'flutter-dart', 'HIGH', '[{"solution": "Check mounted property before using context in async code", "percentage": 95}, {"solution": "Cancel async operations in dispose()", "percentage": 90}, {"solution": "Use if(mounted) before setState", "percentage": 95}]'::jsonb, 'Widget lifecycle', 'Context access safe across async gaps', 'Using context after widget disposal', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/75695751', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Container OnTap not working GestureDetector', 'flutter-dart', 'HIGH', '[{"solution": "Wrap Container in GestureDetector with onTap", "percentage": 98}, {"solution": "Use InkWell for material ripple effect", "percentage": 95}, {"solution": "Ensure Container child doesn''t consume tap event", "percentage": 80}]'::jsonb, 'User input handling', 'Container responds to taps with callback', 'Using Container directly without gesture wrapper', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/44317188', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('StreamController dispose properly in Bloc', 'flutter-dart', 'HIGH', '[{"solution": "Create closeStream() method: _streamController?.close()", "percentage": 95}, {"solution": "Override dispose() in StatefulWidget and call closeStream()", "percentage": 95}, {"solution": "Always dispose stream before widget disposal", "percentage": 95}]'::jsonb, 'Stream management', 'No stream errors after widget disposal', 'Not disposing StreamController in dispose() method', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/56921398', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Hot reload not working Flutter changes not applied', 'flutter-dart', 'MEDIUM', '[{"solution": "Refactor main() logic into separate StatelessWidget class", "percentage": 95}, {"solution": "Use hot restart instead (full app reload)", "percentage": 100}, {"solution": "Check for syntax errors preventing hot reload", "percentage": 85}]'::jsonb, 'Development workflow', 'Code changes reflect immediately on save', 'Keeping runApp logic in main() instead of StatelessWidget', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/57127496', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('AnimationController forward called after dispose', 'flutter-dart', 'HIGH', '[{"solution": "Check mounted before calling forward() in Timer", "percentage": 95}, {"solution": "Cancel Timer in dispose() method", "percentage": 95}, {"solution": "Use Future.delayed and check mounted in callback", "percentage": 90}]'::jsonb, 'Animation lifecycle', 'Animations play and dispose without errors', 'Calling forward() on disposed controller from delayed timer', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/62726872', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Future is from dart:async import error', 'flutter-dart', 'LOW', '[{"solution": "Ensure Future return type is correctly imported", "percentage": 100}, {"solution": "Verify no package naming conflicts", "percentage": 90}]'::jsonb, 'Import handling', 'Async code compiles', 'Missing dart:async imports', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/78985179', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Can''t find } to match { classes inside other classes', 'flutter-dart', 'MEDIUM', '[{"solution": "Check for missing closing braces in file", "percentage": 100}, {"solution": "Run flutter analyze to find syntax errors", "percentage": 100}, {"solution": "Move nested classes to top-level", "percentage": 95}]'::jsonb, 'Dart syntax', 'File compiles without brace errors', 'Accidentally nesting class definitions', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/65532763', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('A value of type Future cannot be assigned to variable', 'flutter-dart', 'MEDIUM', '[{"solution": "Add await keyword before Future: await futureFunc()", "percentage": 95}, {"solution": "Ensure function is async if using await", "percentage": 95}, {"solution": "Use FutureBuilder if in synchronous context", "percentage": 85}]'::jsonb, 'Async/await', 'Futures properly awaited', 'Assigning Future without await in async context', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/59723496', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('ModalBottomSheetRoute imported from both flutter and package', 'flutter-dart', 'LOW', '[{"solution": "Update modal_bottom_sheet package to latest version", "percentage": 95}, {"solution": "Use alias for conflicting import: as sheet", "percentage": 90}]'::jsonb, 'Package conflicts', 'Bottom sheet displays without import errors', 'Using outdated version of modal_bottom_sheet package', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/78985179', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Bad state cannot add events after calling close', 'flutter-dart', 'MEDIUM', '[{"solution": "Dispose StreamController properly before reusing", "percentage": 95}, {"solution": "Check if stream is closed before adding events", "percentage": 95}, {"solution": "Create new StreamController instead of reopening closed one", "percentage": 90}]'::jsonb, 'Stream operations', 'Stream listeners receive events properly', 'Attempting to add events to closed StreamController', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/55536461', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Bad state stream has already been listened to', 'flutter-dart', 'MEDIUM', '[{"solution": "Use broadcast stream: StreamController.broadcast()", "percentage": 95}, {"solution": "Create single listener only", "percentage": 90}, {"solution": "Use different stream for each listener", "percentage": 85}]'::jsonb, 'Stream patterns', 'Multiple widgets listen to stream without errors', 'Using single-subscription stream with multiple listeners', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/51396769', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Invalid value only valid value is 0 RangeError', 'flutter-dart', 'LOW', '[{"solution": "Check index bounds before list access", "percentage": 100}, {"solution": "Verify data is loaded before building widget", "percentage": 95}]'::jsonb, 'Data validation', 'Widgets build with valid data', 'Accessing first element without checking list length', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/74374007', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Null check operator used on null value', 'flutter-dart', 'MEDIUM', '[{"solution": "Remove ! operator and use null-safe code instead", "percentage": 95}, {"solution": "Check if value is null before using ! operator", "percentage": 95}, {"solution": "Use ?? to provide default value", "percentage": 90}]'::jsonb, 'Null safety', 'No null reference errors', 'Using ! operator on potentially null values', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/68080364', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Image loading exception network timeout', 'flutter-dart', 'MEDIUM', '[{"solution": "Add timeout parameter to Image.network()", "percentage": 90}, {"solution": "Check network connectivity before loading", "percentage": 85}, {"solution": "Use CachedNetworkImage with timeout configuration", "percentage": 80}]'::jsonb, 'Image loading', 'Images load reliably from network', 'Not handling slow network connections', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/59638309', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Could not find build tools version conflict', 'flutter-dart', 'MEDIUM', '[{"solution": "Run sdkmanager to install missing build tools", "percentage": 95}, {"solution": "Update build.gradle with available build tools version", "percentage": 95}, {"solution": "Check Android SDK Platform tools are installed", "percentage": 90}]'::jsonb, 'Android build setup', 'App builds successfully for Android', 'Missing or outdated Android build tools', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/54244959', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Gradle build failed execution task compileFlutterBuildDebug', 'flutter-dart', 'HIGH', '[{"solution": "Delete android/app/build folder", "percentage": 90}, {"solution": "Run flutter clean && flutter pub get", "percentage": 95}, {"solution": "Sync Gradle in Android Studio", "percentage": 85}]'::jsonb, 'Build system', 'Debug APK builds without errors', 'Stale build artifacts from previous compilation', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/52409592', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Undefined name mounted check State property', 'flutter-dart', 'MEDIUM', '[{"solution": "Use mounted property only in StatefulWidget State classes", "percentage": 100}, {"solution": "For StatelessWidget use Consumer or context.read()", "percentage": 95}]'::jsonb, 'State management', 'Code compiles with proper mounted checks', 'Using mounted in StatelessWidget', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/72667782', 'admin:1764221361');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Build context should not be used across async gaps', 'flutter-dart', 'MEDIUM', '[{"solution": "Check context.mounted before using in async callbacks", "percentage": 95}, {"solution": "Store BuildContext before async operation", "percentage": 85}, {"solution": "Use NavigatorObserver instead of direct context usage", "percentage": 75}]'::jsonb, 'Async context safety', 'No warnings about async context usage', 'Using BuildContext after async operation without checking', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/68096518', 'admin:1764221361');
