-- Mining Rails Errors knowledge entries
-- Mined on 2025-11-26 from Stack Overflow

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('How to add errors to Rails model in before_save', 'rails', 'HIGH', '[{"solution": "Use validate block instead of before_save callback. Validations must happen in validate blocks, not before_save", "percentage": 95}, {"solution": "Place validation logic in validate do...end block to ensure errors are set before save attempt", "percentage": 90}]'::jsonb, 'Rails ActiveRecord knowledge', 'Errors properly caught and displayed in view', 'Using before_save for validation logic, not using validate block', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/17411235/how-to-add-errors-to-rails-model', 'admin:1764210674'),

('errors[:base] << Error message no longer works in Rails 7', 'rails', 'HIGH', '[{"solution": "Use errors.add(:base, \"Error message\") instead of errors[:base] << \"Error message\"", "percentage": 98}, {"solution": "This deprecated pattern worked in Rails 3-6 but is removed in Rails 7+", "percentage": 85}]'::jsonb, 'Rails 7', 'No syntax errors, error messages display correctly', 'Using deprecated array push syntax, not checking Rails version compatibility', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/706533/ruby-on-rails-errors-add-to-base-vs-errors-add', 'admin:1764210674'),

('How to display validation error messages one at a time', 'rails', 'MEDIUM', '[{"solution": "Use @user.errors.full_messages.first to get first error: <%= @user.errors.full_messages.first if @user.errors.any? %>", "percentage": 92}, {"solution": "Use @user.errors.each to iterate: @user.errors.each {|attr, msg| do_stuff}", "percentage": 88}, {"solution": "Access specific attribute errors with @user.errors[:name] to get array of errors for that field", "percentage": 85}]'::jsonb, 'Rails error handling, views templating', 'Single error message displayed without array brackets', 'Attempting to display full errors array without accessing first element', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/7878662/how-do-i-display-ruby-on-rails-form-validation-error-messages-one-at-a-time', 'admin:1764210674'),

('How to get error messages from child resource in Rails validation', 'rails', 'MEDIUM', '[{"solution": "Use validates_associated with manual merging: school.students.each {|s| s.errors.full_messages.each {|msg| errors.add(:base, msg)}}", "percentage": 85}, {"solution": "Use autosave: true on has_many association and errors will bubble up automatically", "percentage": 90}]'::jsonb, 'Rails has_many, validates_associated', 'Child resource error messages appear in parent object errors', 'Using add_to_base instead of add(:base, ...) syntax, not using autosave', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/2680016/ruby-on-rails-how-to-get-error-messages-from-a-child-resource-displayed', 'admin:1764210674'),

('Rendering ActiveRecord errors with attributes and full error messages', 'rails', 'HIGH', '[{"solution": "Use person.errors.to_hash(true) or person.errors.to_json(full_messages: true) to include attribute keys with full messages", "percentage": 94}, {"solution": "For Ruby 2.7+: use errors.group_by_attribute.transform_values {|errors| errors.map(&:full_message)}", "percentage": 88}]'::jsonb, 'Rails 5+, JSON serialization', 'Errors rendered as {attribute: [full_message_text]} for JSON API', 'Using full_messages which loses attribute keys, not using to_hash/to_json with full_messages option', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/68676356/rendering-activerecord-validation-errors-with-attributes-and-full-error-messages', 'admin:1764210674'),

('errors.full_messages returns array with brackets and quotes in flash', 'rails', 'MEDIUM', '[{"solution": "Use .to_sentence on the array: @model.errors.full_messages.to_sentence to convert array to readable string", "percentage": 96}, {"solution": "Alternative: use .join(\", \") to join array elements with commas", "percentage": 90}]'::jsonb, 'Rails views, flash messages', 'Error messages display as readable sentence without brackets', 'Directly interpolating errors array into flash without converting to string', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/15043272/errors-full-messages-format-in-rails-3', 'admin:1764210674'),

('Rails 5 displaying error messages - render vs redirect issue', 'rails', 'HIGH', '[{"solution": "Use render :action instead of redirect_to when displaying form with errors so @object remains available", "percentage": 97}, {"solution": "Instance variables set in controller are lost on redirect - use render to keep them in same request", "percentage": 95}]'::jsonb, 'Rails 5+, form rendering', 'Error partial renders with @object.errors.any? returning true', 'Using redirect_to after failed validation which loses instance variable, errors.any? checking for validation failure', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/43506832/rails-5-displaying-error-messages', 'admin:1764210674'),

('Where is the list of Ruby and Rails exception types', 'rails', 'MEDIUM', '[{"solution": "View active_record/errors.rb in Rails source: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/errors.rb", "percentage": 92}, {"solution": "ActiveRecord exceptions inherit from StandardError - common ones: RecordNotFound, RecordInvalid, StatementInvalid, RecordNotSaved", "percentage": 88}]'::jsonb, 'Ruby exception hierarchy, Rails error handling', 'Correct exception type caught with rescue clause', 'Rescue StandardError too broadly, catching exceptions that should not be rescued', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/31271588/where-is-the-list-of-the-types-of-exceptions', 'admin:1764210674'),

('error_messages_for is deprecated in Ruby Rails - what is replacement', 'rails', 'MEDIUM', '[{"solution": "In Rails 3.0+: use form_for with block syntax and f.error_messages (also deprecated later)", "percentage": 80}, {"solution": "Modern approach: manually iterate @object.errors.full_messages in view", "percentage": 92}, {"solution": "Or use a gem like dynamic_form which provides error_messages_for", "percentage": 75}]'::jsonb, 'Rails 2 to 3 migration, form helpers', 'No deprecation warnings, errors display correctly', 'Using deprecated error_messages_for helper directly without updating', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/11435710/error-messages-for-is-deprecated-in-ruby-how-do-i-find-the-replacement', 'admin:1764210674'),

('Getting error message from model method that is not validation error', 'rails', 'MEDIUM', '[{"solution": "Use errors.add(:base, message) in model method and access via errors.full_messages or render (not redirect) the form", "percentage": 91}, {"solution": "Return false from model method when validation fails, check in controller with if/else and render form", "percentage": 89}]'::jsonb, 'Custom validation, error handling', 'Custom error messages display in view without flash loss', 'Using redirect_to after method call with errors - loses @object context', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/1695245/rails-getting-an-error-message-from-the-model-that-is-not-a-validation-error', 'admin:1764210674');

-- Migration complete
