-- Cypress Error Messages - Official Docs Mining
-- Source: docs.cypress.io/app/references/error-messages
-- Mined: 2025-11-25

INSERT INTO knowledge_entries (
    query, category, hit_frequency, solutions, prerequisites, success_indicators,
    common_pitfalls, success_rate, claude_version, last_verified, source_url
) VALUES (
    'No tests found',
    'cypress',
    'HIGH',
    $$[{"solution": "Write test cases using it() blocks in your test file", "percentage": 95, "note": "Cypress cannot run empty test files"}]$$::jsonb,
    'Test file must exist and be specified in cypress.config.js',
    'Tests appear in Cypress spec list and can be executed',
    'Creating empty test files without it() blocks; forgetting to save changes',
    0.95,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
),
(
    'We found an error preparing your test file',
    'cypress',
    'HIGH',
    $$[{"solution": "Fix syntax errors in test file or dependencies and save - Cypress will auto-rerun", "percentage": 80, "note": "Check for missing imports or typos"}, {"solution": "Verify all dependencies are installed and available", "percentage": 15, "note": "Run npm install or equivalent"}, {"solution": "Check that referenced files exist in project", "percentage": 5, "note": "File path resolution errors"}]$$::jsonb,
    'Test file must be valid JavaScript with proper syntax',
    'Test file appears in spec list and Cypress auto-reruns without error',
    'Ignoring error details; not checking file dependencies; assuming cache is fresh',
    0.90,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
),
(
    'Cypress cannot execute commands outside a running test',
    'cypress',
    'MEDIUM',
    $$[{"solution": "Wrap all cy commands within it(...) test blocks", "percentage": 100, "note": "Commands must be inside test context"}]$$::jsonb,
    'Test file with it() or describe() blocks',
    'Commands execute without "outside running test" error',
    'Placing cy.commands in before/after hooks; executing cy in describe blocks directly; cy in setup code',
    0.98,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
),
(
    'cy...() failed because the page updated',
    'cypress',
    'MEDIUM',
    $$[{"solution": "Break command chains - start new cy chains after each command instead of continuous chaining", "percentage": 100, "note": "Use separate cy statements rather than long chains"}]$$::jsonb,
    'Element removed from DOM during test execution',
    'Commands complete without page update errors',
    'Assuming elements persist across multiple commands; long command chains on dynamic pages',
    0.85,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
),
(
    'cy...() failed because the element cannot be interacted with',
    'cypress',
    'HIGH',
    $$[{"solution": "Use {force: true} option to bypass interaction checks", "percentage": 60, "note": "Use cautiously - bypasses all visibility/coverage checks"}, {"solution": "Guard commands with proper timing and animation handling", "percentage": 35, "note": "Wait for animations and transitions to complete"}, {"solution": "Verify element is visible and not covered by another element", "percentage": 5, "note": "Check DOM and CSS positioning"}]$$::jsonb,
    'Element present in DOM',
    'Command executes and target element responds to interaction',
    'Using force:true as first resort; not accounting for overlays or animations; assuming visibility without checking',
    0.80,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
),
(
    'cy...() failed because the element is currently animating',
    'cypress',
    'MEDIUM',
    $$[{"solution": "Pass {force: true} to disable all element interaction checks", "percentage": 50, "note": "Disables animation detection and visibility checks"}, {"solution": "Pass {waitForAnimations: false} to skip animation waiting", "percentage": 35, "note": "Still performs visibility checks"}, {"solution": "Pass {animationDistanceThreshold: 20} to reduce animation detection sensitivity", "percentage": 15, "note": "Threshold in pixels"}]$$::jsonb,
    'Element in DOM with CSS animations or transitions',
    'Command completes without animation timeout',
    'Using force:true when animation threshold adjustment would work; not tuning animation distance threshold',
    0.85,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
),
(
    'The test has finished but Cypress still has commands in its queue',
    'cypress',
    'MEDIUM',
    $$[{"solution": "Return promises in test functions instead of using done() callback", "percentage": 70, "note": "Async/await or explicit promise return"}, {"solution": "Use async/await properly - ensure all async operations complete before test ends", "percentage": 25, "note": "Avoid callback hell and premature completion"}, {"solution": "Do not use done() callback to terminate tests prematurely", "percentage": 5, "note": "Let Cypress handle completion"}]$$::jsonb,
    'Test function with async/promise operations',
    'All commands execute and test completes without queue error',
    'Using done() callback to end tests early; not returning promises; mixing async/await with done() pattern',
    0.88,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
),
(
    'cy.visit() failed because you are attempting to visit a different origin domain',
    'cypress',
    'MEDIUM',
    $$[{"solution": "For Cypress v12.0.0+: wrap cross-origin commands with cy.origin(\"url\", () => {...})", "percentage": 100, "note": "Multi-domain navigation now supported"}]$$::jsonb,
    'Cypress v12.0.0 or later installed',
    'Cross-origin navigation works with cy.origin wrapper',
    'Using v11 without wrapping cross-origin commands; assuming old behavior still applies in v12+',
    0.92,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
),
(
    'cy.visit() succeeded, but commands are timing out',
    'cypress',
    'MEDIUM',
    $$[{"solution": "Wrap cross-domain commands with cy.origin(\"url\", () => {...}) block", "percentage": 100, "note": "Commands on different domain must be wrapped"}]$$::jsonb,
    'Cypress v12.0.0+ with multi-domain test requirements',
    'Commands on secondary domain execute without timeout',
    'Executing cross-domain commands outside cy.origin wrapper; assuming domain context carries forward',
    0.90,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
),
(
    'Cypress.addParentCommand() / addDualCommand() / addChildCommand() has been removed',
    'cypress',
    'LOW',
    $$[{"solution": "Use Cypress.Commands.add() for all custom command types (parent, dual, and child)", "percentage": 100, "note": "Unified API for all command registration"}]$$::jsonb,
    'Cypress 2.1.0+ with deprecated custom command syntax',
    'Custom commands register and execute without deprecation error',
    'Still using old addParentCommand/addDualCommand syntax; not migrating custom commands',
    0.95,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
),
(
    'You passed the --record flag but did not provide your Record Key',
    'cypress',
    'MEDIUM',
    $$[{"solution": "Pass Record Key via --key flag: cypress run --record --key YOUR_KEY", "percentage": 60, "note": "Direct CLI parameter"}, {"solution": "Set CYPRESS_RECORD_KEY environment variable before running", "percentage": 40, "note": "Persistent across sessions"}]$$::jsonb,
    'Cypress run with --record flag and valid Record Key',
    'Test run records to Cypress Dashboard without authentication error',
    'Forgetting to set environment variable; using wrong key; key not in quotes if contains special chars',
    0.92,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
),
(
    'The cypress ci command has been deprecated',
    'cypress',
    'LOW',
    $$[{"solution": "Replace \"cypress ci abc-key-123\" with \"cypress run --record --key abc-key-123\"", "percentage": 70, "note": "Direct CLI replacement"}, {"solution": "Replace CYPRESS_CI_KEY env var with CYPRESS_RECORD_KEY", "percentage": 30, "note": "Environment variable update"}]$$::jsonb,
    'Legacy Cypress CI setup with deprecated command',
    'Tests run with cypress run --record command successfully',
    'Continuing to use cypress ci command syntax; not updating CI/CD pipelines',
    0.93,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
),
(
    'A Cached Cypress Binary Could not be found',
    'cypress',
    'MEDIUM',
    $$[{"solution": "Run package manager install (npm ci, yarn install, or pnpm install) to cache binary", "percentage": 85, "note": "Fresh install required in CI"}, {"solution": "Verify pnpm config if using pnpm - check pnpmfile.cjs setup", "percentage": 15, "note": "pnpm specific configuration"}]$$::jsonb,
    'CI environment with Cypress dependency defined',
    'Cypress binary cached and available for test runs',
    'Assuming cache persists without install step; using npm install instead of npm ci; incorrect pnpm config',
    0.88,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
),
(
    'Cypress detected a cross-origin error happened on page load',
    'cypress',
    'MEDIUM',
    $$[{"solution": "Avoid clicking external links in tests - assert href attribute instead", "percentage": 50, "note": "Test link attributes not navigation"}, {"solution": "Use cy.request() for SSO redirects instead of direct navigation", "percentage": 40, "note": "For testing auth flows"}, {"solution": "Set chromeWebSecurity: false in config (Chrome-family only, not recommended)", "percentage": 10, "note": "Last resort - disables security checks"}]$$::jsonb,
    'Application with cross-origin redirects or external links',
    'Tests complete without cross-origin errors',
    'Setting chromeWebSecurity: false as first approach; not testing link attributes; navigating to external URLs',
    0.78,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
),
(
    'The browser process running your tests just exited unexpectedly',
    'cypress',
    'MEDIUM',
    $$[{"solution": "Enable experimentalMemoryManagement in config for Chromium browsers", "percentage": 70, "note": "Reduces memory usage during test runs"}, {"solution": "Lower numTestsKeptInMemory value in open mode config", "percentage": 30, "note": "Default 50, reduce if memory constrained"}]$$::jsonb,
    'Chromium-based browser with memory-heavy test suite',
    'Browser stays alive for full test duration without crashes',
    'Not monitoring system resources; assuming browser crash indicates test failure only; ignoring memory warnings',
    0.72,
    'sonnet-4',
    NOW(),
    'https://docs.cypress.io/app/references/error-messages'
);
