-- Mining: Testing CORS errors for clauderepo
-- Miner: haiku-1764192053
-- Date: 2025-11-26

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Testing CORS with SpringBootTest - assertion on Access-Control-Allow-Methods header fails', 'testing', 'HIGH', '[{"solution": "Add Origin and Access-Control-Request-Method headers to mock request. Use options() method instead of get() and include headers: .perform(options(''/test-cors'').header(''Access-Control-Request-Method'', ''GET'').header(''Origin'', ''http://www.someurl.com'')) - both headers required for server to process CORS request", "percentage": 95}, {"solution": "Alternative: Initialize CorsFilter bean directly instead of CorsConfigurationSource - change method to return new CorsFilter(source) instead of just source", "percentage": 85}]'::jsonb, 'SpringBoot application with CORS configuration, MockMvc setup with SecurityMockMvcConfigurers.springSecurity(), dispatchOptions(true) enabled', 'Test performs options() request, response includes Access-Control-Allow-Methods and Access-Control-Allow-Origin headers, assertion passes without CORS error', 'Only using GET request without Origin header - server won''t process CORS, forgetting both Origin and Access-Control-Request-Method headers, using CorsConfigurationSource instead of CorsFilter bean', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/42588692/testing-cors-in-springboottest', 'admin:1764192053');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Testing CORS headers with curl - how to verify Access-Control headers in response', 'testing', 'HIGH', '[{"solution": "Send preflight OPTIONS request with curl including Origin and Access-Control-Request-Method headers: curl -H ''Origin: http://example.com'' -H ''Access-Control-Request-Method: POST'' -H ''Access-Control-Request-Headers: X-Requested-With'' -X OPTIONS --verbose https://api.example.com/endpoint - response should include Access-Control-Allow-Origin, Access-Control-Allow-Methods, Access-Control-Allow-Headers", "percentage": 95}, {"solution": "For simpler verification use curl with --head flag to show only headers: curl -H ''Access-Control-Request-Method: GET'' -H ''Origin: http://localhost'' --head http://www.example.com/", "percentage": 90}]'::jsonb, 'curl installed, target API endpoint accessible, knowledge of preflight requests and CORS headers', 'curl response includes HTTP 200 status, Access-Control-Allow-Origin header present in response, Access-Control-Allow-Methods matches request headers', 'Forgetting Origin header entirely, not using OPTIONS method for preflight, using regular GET/POST without preflight simulation, not checking response headers for missing Access-Control-* headers', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/12173990/how-can-you-debug-a-cors-request-with-curl', 'admin:1764192053');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Jest test failing with CORS error when calling external API during test execution', 'testing', 'HIGH', '[{"solution": "Set testURL in Jest config to match CORS policy of remote API. For Jest v24-v27 use ''testURL'' in jest.config.js: { testURL: ''http://localhost:8080'' } - use the actual URL allowed by CORS at remote API side. For Jest v28+ use testEnvironmentOptions instead", "percentage": 90}, {"solution": "Disable XMLHttpRequest in setup file before axios loads: In jest.config.js add setupTestFrameworkScriptFile: ''./__tests__/setup.js'', then in setup.js add ''global.XMLHttpRequest = undefined;'' - prevents CORS restrictions since no XMLHttpRequest available", "percentage": 85}]'::jsonb, 'Jest testing framework configured, external API calls in test code, axios or fetch library for HTTP requests', 'Test runs without Cross origin http://localhost forbidden error, external API calls succeed in test environment, no CORS policy blocking', 'Using http://localhost default testURL when API expects different origin, not setting testURL at all, XMLHttpRequest not being properly disabled before imports, using jsdom environment without proper CORS configuration', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/58785617/cors-error-error-cross-origin-http-localhost-forbidden-in-reactjs-jest-te', 'admin:1764192053');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Playwright test failing with CORS error when making requests from test to same-origin API', 'testing', 'HIGH', '[{"solution": "Configure Playwright to properly handle CORS headers at server level - ensure API endpoint returns correct Access-Control-Allow-Origin, Access-Control-Allow-Methods, and Access-Control-Allow-Headers in response to preflight OPTIONS requests. The issue occurs in Playwright but not in regular browser when server CORS config differs from Playwright''s strict handling", "percentage": 85}, {"solution": "Add route handler or API mock to intercept requests and add CORS headers: page.route(''**/api/**'', route => { const response = route.response(); // Modify headers if needed }); - bypass CORS checks by mocking API responses in test", "percentage": 80}]'::jsonb, 'Playwright test framework, page object from browser context, target API or mock server, understanding of CORS preflight requests', 'Playwright test completes without ''Access to XMLHttpRequest blocked by CORS policy'' error, page.goto() succeeds without CORS blocking, API requests in test respond successfully', 'Assuming Playwright handles CORS same as browser - it doesn''t, not setting OPTIONS method in Access-Control-Allow-Methods header on server, forgetting CORS headers when running same-origin requests, not mocking or intercepting preflight requests', 0.78, 'haiku', NOW(), 'https://stackoverflow.com/questions/78895259/cors-error-in-playwright-unable-to-access-login-api-from-origin-domain', 'admin:1764192053');
