INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Process completed with exit code 1', 'github-actions', 'HIGH', '[{"solution": "Check the script output to identify which command exited with status 1. Use ''bash -e'' to catch early failures.", "percentage": 95}, {"solution": "Inspect individual command outputs in the workflow log to correlate which step failed", "percentage": 92}]'::jsonb, 'Bash script, set -e flag', 'Workflow completes without exit 1 error', 'Not examining individual command outputs before assuming script failure', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/66626814/github-action-error-process-completed-with-exit-code-1', 'admin:1764221363'),

('An action could not be found at the URI', 'github-actions', 'HIGH', '[{"solution": "Use correct action version tag: use ''actions/checkout@v2'' or ''actions/checkout@v3'' instead of branch names", "percentage": 97}, {"solution": "Verify the action repository exists on GitHub and the ref/tag is correct", "percentage": 94}]'::jsonb, 'GitHub action syntax, actions/checkout', 'Action resolves correctly and job proceeds', 'Using branch names instead of version tags for actions', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/62126024/github-actions-error-an-action-could-not-be-found', 'admin:1764221363'),

('Invalid workflow file - every step must define a uses or run key', 'github-actions', 'HIGH', '[{"solution": "Each step must have either ''uses:'' OR ''run:'' key. Use ''actions/setup-node@v3'' for uses, or ''npm install'' for run.", "percentage": 98}, {"solution": "Check YAML indentation - ''with:'' must be indented under ''uses:'' not as a sibling step", "percentage": 96}]'::jsonb, 'YAML syntax, GitHub workflow', 'Workflow file validates without syntax errors', 'Forgetting run: or uses: in step definition, incorrect with: indentation', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/73225427/github-action-failure', 'admin:1764221363'),

('Job running has exceeded the maximum execution time of 6 hours', 'github-actions', 'HIGH', '[{"solution": "Split long-running job into smaller jobs using ''needs:'' to chain them sequentially", "percentage": 89}, {"solution": "Move to self-hosted runner which has no time limit for job execution", "percentage": 82}]'::jsonb, 'Long-running workflow, timeout configuration', 'Job completes within 6 hour limit', 'Setting timeout-minutes higher than 360 without recognizing platform limit', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/68187987/github-actions-job-timeout', 'admin:1764221363'),

('Permission denied in container workflow', 'github-actions', 'HIGH', '[{"solution": "Add ''options: --user root'' to container configuration to run as root", "percentage": 94}, {"solution": "Use ''sudo'' before commands that need elevated privileges in container", "percentage": 91}]'::jsonb, 'Docker container, GitHub runner', 'Commands execute without permission errors', 'Not providing root access in containerized workflows', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/57830375/github-actions-workflow-error-permission-denied', 'admin:1764221363'),

('Resource not accessible by integration', 'github-actions', 'HIGH', '[{"solution": "Check GITHUB_TOKEN permissions in workflow settings - ensure correct scope is enabled", "percentage": 93}, {"solution": "For pull_request from fork, use ''pull_request_target'' event with checkout ref configuration", "percentage": 89}]'::jsonb, 'GitHub token, repository permissions', 'API calls succeed with proper permissions', 'Token scope too restrictive for API action', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac', 'admin:1764221363'),

('Cannot read property of undefined', 'github-actions', 'MEDIUM', '[{"solution": "Check if array/object exists before accessing: if (arr && arr.length)", "percentage": 94}, {"solution": "Use optional chaining operator: obj?.property?.value", "percentage": 92}]'::jsonb, 'JavaScript, Node.js action', 'No undefined property errors in logs', 'Not null-checking before property access', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/57903836/how-to-fail-a-job-in-github-actions', 'admin:1764221363'),

('Error annotation not showing in workflow output', 'github-actions', 'MEDIUM', '[{"solution": "Use correct syntax: echo ''::error::Message text'' (with :: separator between error and message)", "percentage": 97}, {"solution": "Include filename in error annotation: echo ''::error file=path.js::Error description''", "percentage": 95}]'::jsonb, 'Workflow commands, echo', 'Error annotations appear in GitHub UI', 'Wrong separator format in workflow command', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/71087094/how-to-make-a-github-workflow-error-message-show-up-in-log-and-annotations', 'admin:1764221363'),

('pull_request trigger not firing on forked repository', 'github-actions', 'MEDIUM', '[{"solution": "Enable ''Run workflows from fork pull requests'' in repository settings under Actions/General", "percentage": 96}, {"solution": "For org repos, enable setting in organization settings first, then repository settings", "percentage": 93}]'::jsonb, 'Repository settings, fork PR', 'Workflow triggers on forked PR', 'Repository setting not enabled for fork PRs', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/73314842/unable-to-trigger-github-actions-when-pull-request-comes-from-a-forked-repositor', 'admin:1764221363'),

('pull_request_target not checking out fork code correctly', 'github-actions', 'MEDIUM', '[{"solution": "Use pull_request_target with explicit checkout: uses: actions/checkout@v2 with: ref: ${{github.event.pull_request.head.ref}} repository: ${{github.event.pull_request.head.repo.full_name}}", "percentage": 91}, {"solution": "Consider using pull_request event instead if secrets not needed", "percentage": 87}]'::jsonb, 'Forked PR, checkout action', 'Fork code is checked out in pull_request_target workflow', 'Not explicitly checking out PR branch in pull_request_target', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/64802322/running-github-actions-on-the-code-in-a-pull-request-from-a-fork', 'admin:1764221363'),

('Secrets not available in workflow', 'github-actions', 'MEDIUM', '[{"solution": "If using reusable workflow, add ''secrets: inherit'' to the workflow_call job", "percentage": 94}, {"solution": "Pull request builds from forks don''t receive secrets by default - must be explicitly enabled", "percentage": 91}]'::jsonb, 'GitHub secrets, workflow inheritance', 'Secrets resolve and are accessible in steps', 'Missing secrets: inherit in reusable workflow call', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets', 'admin:1764221363'),

('Self-hosted runner appears offline', 'github-actions', 'MEDIUM', '[{"solution": "Do not run runner as background process with &. Use direct command: ./run.sh without nohup &", "percentage": 93}, {"solution": "Check runner connectivity and ensure runner process is actually running with ps command", "percentage": 89}]'::jsonb, 'Self-hosted runner, runner service', 'Runner shows Idle status in GitHub UI', 'Running runner as background process with &', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/75531482/github-self-hosted-runner-appears-offline-on-codespace-start-up', 'admin:1764221363'),

('workflow_dispatch input validation not enforced', 'github-actions', 'LOW', '[{"solution": "Use ''type: choice'' in inputs to restrict values to dropdown options", "percentage": 95}, {"solution": "Add validation step that checks input values and fails if invalid: if not in [''option1'', ''option2'']", "percentage": 88}]'::jsonb, 'workflow_dispatch, input validation', 'Input values are restricted to valid set', 'Not using type: choice for input validation', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/64919429/can-we-limit-the-inputs-of-a-workflow-dispatch-trigger-to-an-specific-set', 'admin:1764221363'),

('No tag found in ref or input', 'github-actions', 'MEDIUM', '[{"solution": "Set ''fetch-depth: 0'' in actions/checkout to fetch all tags and history", "percentage": 96}, {"solution": "Trigger workflow on ''create'' event with tag filter instead of push event", "percentage": 92}]'::jsonb, 'Checkout action, release action', 'Release action finds tags and creates release', 'Not fetching all git history and tags', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/64876953/github-action-error-undefined-no-tag-found-in-ref-or-input', 'admin:1764221363'),

('Unable to preserve double quotes in bash run step', 'github-actions', 'MEDIUM', '[{"solution": "Use single quotes around YAML value to prevent interpretation: run: ''echo \"$VAR\"''", "percentage": 93}, {"solution": "Escape quotes in YAML by doubling them or using different quote style", "percentage": 90}]'::jsonb, 'YAML quoting, bash variables', 'Variable expansion preserves quotes in output', 'Not properly quoting YAML values with embedded quotes', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/78412927/how-to-preserve-input-with-double-quotes-in-a-run-step-bash-in-github-actions', 'admin:1764221363'),

('Reusable workflow outputs not accessible in caller', 'github-actions', 'MEDIUM', '[{"solution": "Declare outputs in reusable workflow: outputs: varname: value: ${{ jobs.jobid.outputs.output }}", "percentage": 94}, {"solution": "Access outputs in caller using: needs.reusable.outputs.varname", "percentage": 96}]'::jsonb, 'Reusable workflow, job outputs', 'Outputs from reusable workflow accessible in caller', 'Not declaring workflow-level outputs in reusable workflow', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/73702333/github-actions-reuse-outputs-from-other-reusable-workflows', 'admin:1764221363'),

('NPM cache not being saved on Windows', 'github-actions', 'MEDIUM', '[{"solution": "Use actions/setup-node@v2 with ''cache: npm'' parameter instead of manual cache action", "percentage": 96}, {"solution": "For manual caching on Windows, use correct home path: use $env:APPDATA\\npm-cache or setup-node cache", "percentage": 89}]'::jsonb, 'NPM, Windows runner, cache', 'Dependencies restored from cache', 'Using manual cache on Windows with incorrect path', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/69334382/cache-dependencies-in-github-actions-on-windows', 'admin:1764221363'),

('Docker pull failed from private registry', 'github-actions', 'MEDIUM', '[{"solution": "Push private image to container registry (ghcr.io, Docker Hub) - cannot use local images", "percentage": 97}, {"solution": "Configure registry credentials in container.credentials with username and password", "percentage": 94}]'::jsonb, 'Docker, private image, registry', 'Container image pulls successfully', 'Attempting to use local Docker image in container job', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/70332230/github-action-error-docker-pull-failed-with-exit-code-1', 'admin:1764221363'),

('Permission denied when pushing to GHCR', 'github-actions', 'MEDIUM', '[{"solution": "Set job-level permissions: permissions: packages: write", "percentage": 96}, {"solution": "In repo settings Actions > General, enable ''Read and write permissions'' for workflows", "percentage": 93}]'::jsonb, 'Docker push, GHCR, permissions', 'Docker image successfully pushes to registry', 'Missing write permissions for packages', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/75926611/github-workflow-to-push-docker-image-to-ghcr-io', 'admin:1764221363'),

('Action dependencies not installed', 'github-actions', 'MEDIUM', '[{"solution": "For composite actions, include npm install step or bundle dependencies with ncc", "percentage": 88}, {"solution": "For JavaScript actions, include node_modules in repo or use container action", "percentage": 85}]'::jsonb, 'JavaScript action, dependencies', 'Action runs with all dependencies available', 'Not handling dependency installation in custom action', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/70632671/how-to-install-npm-dependencies-of-a-github-action', 'admin:1764221363'),

('Python virtualenv not persisting across steps', 'github-actions', 'MEDIUM', '[{"solution": "Activate virtualenv in every step: . .venv/bin/activate before command", "percentage": 94}, {"solution": "Store PATH in GITHUB_ENV: echo PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH >> $GITHUB_ENV", "percentage": 96}]'::jsonb, 'Python, virtualenv, shell', 'Python packages available in subsequent steps', 'Activating venv only once without persisting PATH', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/74668349/how-to-activate-a-virtualenv-in-a-github-action', 'admin:1764221363'),

('Gradle wrapper not found or not executable', 'github-actions', 'MEDIUM', '[{"solution": "Run ''chmod +x ./gradlew'' before gradle build to make wrapper executable", "percentage": 97}, {"solution": "Ensure gradlew file is committed to repository and not in .gitignore", "percentage": 95}]'::jsonb, 'Gradle, Java, executable', 'Gradle build executes successfully', 'Not setting execute permission on gradlew', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/72134117/github-action-fail-gradle-build', 'admin:1764221363'),

('NPM install fails to find module', 'github-actions', 'MEDIUM', '[{"solution": "Check package.json is in correct directory, run npm install in proper working-directory", "percentage": 92}, {"solution": "Verify private package auth configured if using private npm registry", "percentage": 87}]'::jsonb, 'NPM, package.json, dependencies', 'NPM install completes successfully', 'Wrong working directory when running npm install', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/78340334/github-action-issue-issue-with-npm-install', 'admin:1764221363'),

('Artifact upload step not executing', 'github-actions', 'MEDIUM', '[{"solution": "Use if: always() or if: failure() to run upload even if previous steps fail", "percentage": 94}, {"solution": "Check path is relative to GITHUB_WORKSPACE: use full path like ''robot/tests/report.html''", "percentage": 93}]'::jsonb, 'Upload artifact, path', 'Artifact successfully uploaded and available', 'Path incorrect or step skipped when previous step fails', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/58226636/github-action-not-uploading-artifact', 'admin:1764221363'),

('Environment variable substitution not working in heredoc', 'github-actions', 'LOW', '[{"solution": "Use double-quote syntax in heredoc: <<\"EOF\" to enable variable substitution", "percentage": 95}, {"solution": "For literal text without variables, use <<''EOF'' syntax", "percentage": 92}]'::jsonb, 'Heredoc, bash, environment variable', 'Variables correctly expand in heredoc', 'Using single-quoted heredoc delimiter which prevents variable expansion', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/76423806/substitution-of-environment-variables-not-working-in-github-actions', 'admin:1764221363'),

('Matrix strategy fail-fast not controlled', 'github-actions', 'MEDIUM', '[{"solution": "Set ''strategy: fail-fast: false'' to continue running other matrix jobs when one fails", "percentage": 96}, {"solution": "Remove ''continue-on-error'' and use fail-fast: false instead for proper workflow failure", "percentage": 94}]'::jsonb, 'Matrix strategy, job failure', 'All matrix jobs run and workflow fails only if needed', 'Using continue-on-error instead of fail-fast: false', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/70830094/marking-github-actions-workflow-as-failed-if-a-single-job-fails-in-matrix', 'admin:1764221363'),

('Token scope insufficient for GitHub API calls', 'github-actions', 'MEDIUM', '[{"solution": "Check permissions in workflow: permissions: contents: read id-token: write for OIDC", "percentage": 92}, {"solution": "For release creation, ensure ''contents: write'' permission is set", "percentage": 94}]'::jsonb, 'GITHUB_TOKEN, permissions', 'API calls succeed with adequate token scope', 'Not declaring required permissions in workflow', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/72183048/what-is-the-permission-scope-of-id-token-in-github-action', 'admin:1764221363'),

('PowerShell script in composite action fails', 'github-actions', 'MEDIUM', '[{"solution": "Use absolute path with $env: GITHUB_ACTION_PATH and call operator: & $env:GITHUB_ACTION_PATH/script.ps1", "percentage": 94}, {"solution": "Wrap path in quotes when using variables: & ''$env:GITHUB_ACTION_PATH/script.ps1''", "percentage": 91}]'::jsonb, 'PowerShell, composite action', 'PowerShell script executes correctly', 'Using relative paths instead of $env:GITHUB_ACTION_PATH', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/65100630/creating-a-github-action-which-runs-a-powershell-script-on-a-windows-host', 'admin:1764221363'),

('Shallow clone causing missing git history for operations', 'github-actions', 'MEDIUM', '[{"solution": "Set ''fetch-depth: 0'' to fetch all history for commands like git diff, blame, log", "percentage": 95}, {"solution": "For specific commits, use ''fetch-depth: 2'' or higher number depending on operation", "percentage": 92}]'::jsonb, 'Checkout action, fetch-depth', 'Git operations access full history', 'Using default shallow clone (fetch-depth: 1)', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/60222741/github-actions-and-git-clone-issue', 'admin:1764221363'),

('Secrets masked as empty in pull request from dependabot', 'github-actions', 'MEDIUM', '[{"solution": "Workflows triggered by Dependabot run with only GITHUB_TOKEN read permissions and no other secrets", "percentage": 96}, {"solution": "Use workflow_run trigger on completed workflow to access secrets with full permissions", "percentage": 93}]'::jsonb, 'Dependabot, secrets, workflow_run', 'Secrets accessible in appropriate workflow context', 'Expecting secrets in dependabot-triggered workflows', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/61308519/why-the-action-cannot-access-secrets', 'admin:1764221363'),

('Step output not accessible in following steps', 'github-actions', 'MEDIUM', '[{"solution": "Use correct syntax: ${{ steps.stepid.outputs.varname }} with step id and output key", "percentage": 97}, {"solution": "For job outputs, use needs.jobid.outputs.varname to access across jobs", "percentage": 95}]'::jsonb, 'Step outputs, GITHUB_OUTPUT', 'Output variables accessible in subsequent steps', 'Wrong output reference syntax or missing step id', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/57850553/github-actions-check-steps-status', 'admin:1764221363'),

('Workflow dispatch required inputs not validated', 'github-actions', 'LOW', '[{"solution": "Note: GitHub only validates workflow_dispatch inputs at runtime when runner starts, not in UI", "percentage": 88}, {"solution": "Implement bash validation step if required: if [[ ! ${INPUT} =~ ^(option1|option2)$ ]]; then echo error", "percentage": 85}]'::jsonb, 'Workflow dispatch, input validation', 'User guided to use valid inputs via dropdown', 'Expecting UI-level validation for required inputs', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/68804484/why-are-required-inputs-to-github-actions-not-enforced', 'admin:1764221363'),

('Check step status and conditionally run steps', 'github-actions', 'MEDIUM', '[{"solution": "Use if: steps.stepid.conclusion == ''success'' or if: steps.stepid.outcome == ''success''", "percentage": 94}, {"solution": "Use status check functions: if: success() if: failure() if: always()", "percentage": 96}]'::jsonb, 'Conditional steps, status functions', 'Conditional steps execute based on previous step status', 'Incorrect status check function syntax', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f', 'admin:1764221363'),

('Cannot use env context in job-level if condition', 'github-actions', 'LOW', '[{"solution": "Use github context instead: if: github.ref == ''refs/heads/main'' or github context properties", "percentage": 94}, {"solution": "Move logic to step-level if with env context where it is supported", "percentage": 91}]'::jsonb, 'Job if condition, env context', 'Job-level conditions evaluate correctly', 'Attempting to use env context in job-level if statement', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/76471787/why-is-env-context-not-available-in-github-action-job-level-if-statement', 'admin:1764221363');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Job skipped due to conditional expression evaluating to false', 'github-actions', 'LOW', '[{"solution": "Check ''if:'' condition uses correct syntax: if: github.ref == ''refs/heads/main''", "percentage": 93}, {"solution": "For checking previous step success, use: if: success() or if: steps.stepid.outcome == ''success''", "percentage": 94}]'::jsonb, 'Conditional job, if expression', 'Job runs when condition is true', 'Incorrect if condition syntax or logic', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/70927785/skip-required-check-if-its-not-applicable-in-github-actions', 'admin:1764221363');
