-- NodeJS Error Codes & Error Handling - Mining Session 1764210591
-- 10 high-quality error solutions from Stack Overflow

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Error codes in NodeJS vs status codes', 'nodejs', 'HIGH', '[{"solution": "Use error.code property instead of comparing error.message strings. Error codes were introduced in Node 8.x", "percentage": 95}, {"solution": "Compare error.code == ''ERR_CODE_NAME'' instead of checking message text for better maintainability", "percentage": 92}]'::jsonb, 'Node 8.x+', 'Error is caught and code property exists', 'Comparing error messages as strings causes maintenance issues when messages change', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/54784530/can-some-one-explain-what-are-the-error-codes-in-nodejs-not-status-codes', 'admin:1764210591'),

('Best practice exception handling in NodeJS', 'nodejs', 'HIGH', '[{"solution": "Never throw errors from functions in callbacks. Return error as first argument: callback(err, result)", "percentage": 96}, {"solution": "For promises use .catch() instead of callbacks to avoid pyramid of doom", "percentage": 94}, {"solution": "Use async/await with try-catch for cleaner error handling", "percentage": 91}]'::jsonb, 'JavaScript Promises/Async', 'Error handling code is maintainable and errors dont cause pyramid of doom', 'Mixing throw with callbacks causes unhandled exception issues', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/7310521/node-js-best-practice-exception-handling', 'admin:1764210591'),

('Error object properties in NodeJS', 'nodejs', 'MEDIUM', '[{"solution": "Error object has properties: message, stack, name. Use error.stack for full stack trace", "percentage": 97}, {"solution": "console.log(new Error(''''message'''').stack) to get stack trace", "percentage": 96}, {"solution": "stack property is V8 native object feature, not Express specific", "percentage": 93}]'::jsonb, 'V8 JavaScript engine', 'Stack trace is printed showing error location', 'Assuming Error object is Express-specific when it''s native V8', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/10624873/what-properties-does-node-js-expresss-error-object-expose', 'admin:1764210591'),

('Throwing errors in NodeJS callbacks', 'nodejs', 'MEDIUM', '[{"solution": "Use node-style callbacks: pass error as first argument instead of throwing", "percentage": 95}, {"solution": "Pattern: callback(null, result) on success, callback(error) on failure", "percentage": 94}, {"solution": "Always check if (err) before processing result in callback", "percentage": 93}]'::jsonb, 'Node.js callbacks', 'Error is passed to callback and handled properly', 'Throwing in callbacks instead of passing error as first argument', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/33086247/throwing-an-error-in-node-js', 'admin:1764210591'),

('Uncaught exception handling in NodeJS', 'nodejs', 'HIGH', '[{"solution": "Use process.on(''''uncaughtException'''', function(err) { console.log(err) }) to catch unhandled errors", "percentage": 95}, {"solution": "Unhandled exceptions often indicate severe errors - consider restarting process after logging", "percentage": 89}, {"solution": "Better to handle errors at correct level rather than relying on uncaughtException handler", "percentage": 90}]'::jsonb, 'Node.js process object', 'Unhandled exceptions are logged instead of crashing silently', 'Using uncaughtException as primary error handling instead of proper error handling at each level', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/10338034/how-do-i-see-warning-and-error-messages-in-node-js', 'admin:1764210591'),

('Checking error type in NodeJS', 'nodejs', 'MEDIUM', '[{"solution": "Use instanceof operator: if (e instanceof RangeError) to check error type", "percentage": 94}, {"solution": "Check error.code property for NodeJS specific errors: if (err.code == ''''ERR_AMBIGUOUS_ARGUMENT'''')", "percentage": 96}, {"solution": "Different libraries may use different error types - check library documentation", "percentage": 88}]'::jsonb, 'JavaScript error types', 'Correct error type detected and handled appropriately', 'Checking error message instead of using instanceof or error.code', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/59966250/how-do-i-check-the-type-of-error-in-node-js', 'admin:1764210591'),

('Handling all exceptions in NodeJS application', 'nodejs', 'HIGH', '[{"solution": "Validate request data at route level with try-catch for sync operations", "percentage": 96}, {"solution": "Return appropriate HTTP status (400 for validation errors) instead of crashing", "percentage": 95}, {"solution": "Express automatically catches sync exceptions and passes to error handlers", "percentage": 92}]'::jsonb, 'Express.js, Input validation', 'Invalid input returns 400 status without crashing server', 'Using uncaughtException for validation errors which then crashes server via DDOS', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/19909904/how-to-handle-all-exceptions-in-node-js', 'admin:1764210591'),

('Extending Error class in NodeJS', 'nodejs', 'MEDIUM', '[{"solution": "Extend Error class: class MyError extends Error { constructor(msg) { super(msg); this.name = this.constructor.name } }", "percentage": 94}, {"solution": "Can customize stack property: this.stack = ''''custom text'''' + this.stack for context", "percentage": 89}, {"solution": "For custom error output use uncaughtException handler to override default behavior", "percentage": 88}]'::jsonb, 'ES6 classes, Error inheritance', 'Custom error class is created and properly inherits from Error', 'Trying to modify built-in lazy getter properties or messing with standard Error behavior', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/71571467/custom-throw-new-error-message-in-javascript', 'admin:1764210591'),

('Cannot read property of undefined in NodeJS', 'nodejs', 'CRITICAL', '[{"solution": "Bind method context: router.get(''''/'''', users.createUser.bind(users)) to preserve this", "percentage": 97}, {"solution": "Arrow functions preserve this context automatically: const method = () => { }", "percentage": 95}, {"solution": "Check if object exists before accessing properties: if (obj && obj.prop)", "percentage": 93}]'::jsonb, 'ES6 classes, this binding', 'Method can access class properties without undefined context errors', 'Not binding methods in Express routes or callback functions', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/43402422/nodejs-cannot-read-property-of-undefined', 'admin:1764210591'),

('EADDRINUSE port already in use error in NodeJS', 'nodejs', 'CRITICAL', '[{"solution": "Error means port is already bound. Kill process: killall -9 node or find process with: lsof -i :PORT", "percentage": 98}, {"solution": "Change to different port: server.listen(3001) instead of 3000", "percentage": 96}, {"solution": "For port 80 on Linux may need sudo or use reverse proxy", "percentage": 92}]'::jsonb, 'Node.js net/http module', 'Server starts without EADDRINUSE error', 'Trying to bind to port already in use without killing process or checking listening event', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/9898372/how-to-fix-error-listen-eaddrinuse-while-using-nodejs', 'admin:1764210591');
