-- Mining entry for general null/undefined errors (2025-11-26)

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('Go nil pointer dereference', 'general', 'VERY_HIGH', '[{"solution": "Always check if pointer is nil before dereferencing: if ptr != nil { ... }", "percentage": 98}, {"solution": "Use a getter function that safely handles nil: func (m *MyStruct) GetField() *Type { if m == nil { return nil } return m.Field }", "percentage": 92}]'::jsonb, 'Go 1.13+', 'No panic or nil pointer errors', 'Assuming pointers are never nil, using nil as valid return', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/74806443', 'admin:1764193474'),

('MobX this is null when trying to update store', 'general', 'HIGH', '[{"solution": "Use @action.bound decorator to bind method context: @action.bound change_me() { ... }", "percentage": 96}, {"solution": "Use arrow function property: change_me = () => { ... } instead of method definition", "percentage": 94}, {"solution": "Wrap callback in arrow function: onClick={() => store.change_me()}", "percentage": 88}]'::jsonb, 'MobX 5.0+, React', 'No TypeError on state update', 'Forgetting that arrow functions are needed for event handlers', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/40702028', 'admin:1764193474'),

('Jenkins pipeline undefined variable', 'general', 'HIGH', '[{"solution": "Define variables before using them in pipeline: env.VARIABLE_NAME = ''value''", "percentage": 97}, {"solution": "Use environment block to set variables: environment { VAR = ''value'' }", "percentage": 95}, {"solution": "Use string interpolation correctly: \"${VARIABLE_NAME}\" instead of bare name", "percentage": 90}]'::jsonb, 'Jenkins 2.0+, Groovy', 'Pipeline runs without undefined variable errors', 'Mixing declarative and scripted pipeline syntax, scope issues', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/46806600', 'admin:1764193474'),

('Zustand useStore arg is undefined on re-render', 'general', 'MEDIUM', '[{"solution": "Fix nested set() calls: use set({...ctx}) NOT set((state) => set({...ctx}))", "percentage": 99}, {"solution": "Ensure state initializes before returning void", "percentage": 97}, {"solution": "Use proper Zustand API: set() returns void, don''t nest set calls", "percentage": 96}]'::jsonb, 'Zustand 3.0+', 'Store state persists across renders', 'Double-calling set(), returning void from set callback', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/79298763', 'admin:1764193474'),

('Mocha test variable initialized but is null when used', 'general', 'MEDIUM', '[{"solution": "Use async/await in before hook to ensure promise resolves: before(async function() { ... })", "percentage": 98}, {"solution": "Chain promises properly or use done callback: .end((err, res) => { ... done() })", "percentage": 95}, {"solution": "Wait for async operations before using data in test", "percentage": 93}]'::jsonb, 'Mocha 7.0+, Node.js', 'Tests pass with data available', 'Async operations not completing before test runs', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/57080373', 'admin:1764193474'),

('Nuxt sh: 1: nuxt: not found', 'general', 'HIGH', '[{"solution": "Use full path to nuxt binary: node_modules/nuxt/bin/nuxt.js start instead of nuxt start", "percentage": 97}, {"solution": "Add config path flag: node_modules/nuxt/bin/nuxt.js start -c ./nuxt.config.js", "percentage": 94}, {"solution": "Ensure dependencies installed: npm install before running", "percentage": 90}]'::jsonb, 'Nuxt 2.0+', 'nuxt command executes successfully', 'Missing node_modules, incorrect PATH, deployment environment differences', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/68581567', 'admin:1764193474'),

('Ansible undefined variable in task', 'general', 'VERY_HIGH', '[{"solution": "Include variables file first: include_vars: file: vars/main.yml", "percentage": 98}, {"solution": "Use vars_files at play level to load variables", "percentage": 96}, {"solution": "Check indentation - with_items must align with task module, not nested under it", "percentage": 95}, {"solution": "Use loop keyword instead of with_items: loop: \"{{ services }}\"", "percentage": 92}]'::jsonb, 'Ansible 2.5+', 'Task executes without undefined variable error', 'Variables not loaded, incorrect indentation, with_items nested wrongly', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/59318382', 'admin:1764193474'),

('Qwik document of undefined accessing in component', 'general', 'MEDIUM', '[{"solution": "Use useVisibleTask$ hook instead of component$: useVisibleTask$(() => { const el = document.getElementById(...) })", "percentage": 99}, {"solution": "Only access document in client-side functions, not in server render", "percentage": 98}, {"solution": "Ensure DOM is ready before accessing it in Qwik", "percentage": 95}]'::jsonb, 'Qwik 1.0+', 'Document access works without undefined errors', 'Using document in server-side code, wrong lifecycle hook', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/75849270', 'admin:1764193474'),

('DynamoDB null value in put item request', 'general', 'HIGH', '[{"solution": "Use NULL data type: { NULL: true } in DynamoDB format", "percentage": 98}, {"solution": "Or use DELETE action to remove null attributes: { Action: ''DELETE'' }", "percentage": 96}, {"solution": "Check if field exists before adding: if (field) { ... add to params ... }", "percentage": 94}]'::jsonb, 'DynamoDB, AWS SDK 2.0+', 'Items store correctly with null values', 'Confusing empty string with null, using wrong attribute format', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/31156101', 'admin:1764193474'),

('Go nil pointer exception panic recovery', 'general', 'MEDIUM', '[{"solution": "Check bounds before accessing: if i < len(list) { ... }", "percentage": 99}, {"solution": "Use recover() to catch panics: defer func() { if r := recover(); r != nil { ... } }()", "percentage": 94}, {"solution": "Prefer explicit checks over panic recovery - always validate indices first", "percentage": 96}]'::jsonb, 'Go 1.13+', 'No panic from nil pointer access', 'Relying on panic/recover instead of checks, unchecked array access', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/24856953', 'admin:1764193474');
