INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Test that Sentry is reporting errors', 'monitoring', 'HIGH', '[{"solution": "Attach error to HTML element: <h1 onClick=\"throw new Error(''Test'')\">Click me</h1>", "percentage": 98}, {"solution": "Use setTimeout: setTimeout(() => { throw new Error(''Sentry Test Error''); });", "percentage": 95}]'::jsonb, 'Sentry SDK initialized with DSN', 'Error appears in Sentry dashboard', 'Testing directly in console doesn''t trigger Sentry - must use DOM element or setTimeout', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/47333846', 'admin:1764225275'),

('How does Sentry intercept unhandled exceptions', 'monitoring', 'MEDIUM', '[{"solution": "Sentry listens to window.onerror event for uncaught exceptions", "percentage": 92}, {"solution": "Monitors unhandledrejection event for promise rejections", "percentage": 90}]'::jsonb, 'JavaScript/Node.js', 'Uncaught errors automatically captured', 'Assuming try-catch errors are auto-captured - they aren''t unless explicitly logged', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/57162795', 'admin:1764225275'),

('How to log errors in catch statement with Sentry', 'monitoring', 'HIGH', '[{"solution": "Use Sentry.captureException(error) in catch block", "percentage": 97}, {"solution": "Wrap in Sentry.withScope() for additional context", "percentage": 93}]'::jsonb, 'Sentry SDK imported and initialized', 'Caught exceptions appear in Sentry', 'Forgetting to call captureException - caught errors don''t auto-report', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/66503228', 'admin:1764225275'),

('Invalid DSN: bad URI(is not URI?)', 'configuration', 'MEDIUM', '[{"solution": "Remove quotation marks from .env file: SENTRY_DSN=http://public:private@host/id (no quotes)", "percentage": 98}, {"solution": "Validate DSN format matches: https://public:private@host:port/project-id", "percentage": 96}]'::jsonb, 'DSN from Sentry dashboard', 'No URI parsing errors', 'Using quotes around DSN in .env files', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/49137482', 'admin:1764225275'),

('Error creating valid DSN from invalid format', 'configuration', 'MEDIUM', '[{"solution": "Copy DSN directly from Sentry project settings - don''t manually construct it", "percentage": 99}, {"solution": "Validate that DSN includes both public and private keys separated by colon", "percentage": 95}]'::jsonb, 'Access to Sentry project settings', 'SentryClientFactory creates client without InvalidDsnException', 'Manually constructing DSN format - use copy-paste from dashboard', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/54093129', 'admin:1764225275'),

('Non-Error promise rejection captured with value: undefined', 'error-handling', 'HIGH', '[{"solution": "Pass error message to reject(): reject(new Error(''message'')) instead of reject()", "percentage": 96}, {"solution": "Convert plain objects to Error: if (!(e instanceof Error)) e = new Error(JSON.stringify(e))", "percentage": 92}]'::jsonb, 'Promise rejection handler', 'Promise rejections appear with proper error messages', 'Calling reject() without arguments or with plain objects', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/71837472', 'admin:1764225275'),

('Non-Error exception captured with plain object', 'error-handling', 'HIGH', '[{"solution": "Convert plain objects to Error instances before passing to Sentry", "percentage": 97}, {"solution": "Use Error constructor: new Error(JSON.stringify(plainObject))", "percentage": 93}]'::jsonb, 'Error handling code', 'All errors logged with proper Error objects', 'Passing plain objects to Sentry.captureException()', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/75536442', 'admin:1764225275'),

('Ignoring Sentry errors from third party libraries', 'configuration', 'MEDIUM', '[{"solution": "Use allowUrls option in Sentry.init() to whitelist your domain only", "percentage": 88}, {"solution": "Note: allowUrls only checks stack frame URLs, not errors without stack traces", "percentage": 85}]'::jsonb, 'Sentry SDK with allowUrls configuration', 'Third party errors filtered from dashboard', 'allowUrls doesn''t filter errors without stack traces', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/76944171', 'admin:1764225275'),

('Source maps not working in Next.js with Sentry', 'debugging', 'MEDIUM', '[{"solution": "Use @sentry/webpack-plugin in next.config.js to upload source maps during build", "percentage": 98}, {"solution": "Enable automatic source map uploads via Sentry Next.js SDK (wizard recommended)", "percentage": 96}]'::jsonb, 'Next.js project with TypeScript', 'Source maps resolve to original files in Sentry', 'Relying on JavaScript source fetching instead of uploading maps', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/61011281', 'admin:1764225275'),

('HTTP Error 429: Rate limiting quota exceeded', 'quota', 'HIGH', '[{"solution": "Enable Spike Protection in Sentry dashboard to auto-protect during error spikes", "percentage": 94}, {"solution": "Reduce tracesSampleRate to lower sampling: tracesSampleRate: 0.1", "percentage": 91}]'::jsonb, 'Sentry account with quota management', 'Events accepted without 429 errors', 'Sending full traces during infrastructure incidents', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/71058862', 'admin:1764225275'),

('Rate limiting error: Creation of this event was denied', 'quota', 'MEDIUM', '[{"solution": "Check Quota Management settings and adjust allowlist/blocklist rules", "percentage": 89}, {"solution": "Disable browser extensions that might be triggering Sentry events", "percentage": 85}]'::jsonb, 'Sentry project with rate limiting', 'POST requests complete without 429 responses', 'Invalid DSN or missing project configuration', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/56221684', 'admin:1764225275'),

('Sentry not capturing errors without explicit try-catch', 'monitoring', 'MEDIUM', '[{"solution": "Sentry only auto-captures unhandled exceptions - wrap risky code in try-catch and use captureException()", "percentage": 93}, {"solution": "Use ErrorBoundary in React to catch component rendering errors", "percentage": 91}]'::jsonb, 'Sentry SDK initialized', 'All application errors appear in Sentry', 'Expecting Sentry to capture all errors without explicit logging', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/58239228', 'admin:1764225275'),

('Please check if your DSN is set properly in config', 'configuration', 'HIGH', '[{"solution": "Verify DSN is set in environment variable or Sentry.init() config", "percentage": 98}, {"solution": "Test event to confirm configuration: Use Test button in Sentry project settings", "percentage": 96}]'::jsonb, 'Sentry project created with DSN', 'Test event succeeds and appears in dashboard', 'DSN null or empty, DSN copied incorrectly from dashboard', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/68004379', 'admin:1764225275'),

('Handling error spikes gracefully with Sentry', 'quota', 'MEDIUM', '[{"solution": "Enable Spike Protection to dynamically filter abnormal event volumes", "percentage": 95}, {"solution": "Implement exponential backoff for retrying failed operations", "percentage": 88}]'::jsonb, 'Sentry SDK configured with spike protection', 'Quota preserved during infrastructure incidents', 'Relying only on sample rate without dynamic protection', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/56848811', 'admin:1764225275'),

('Sentry tracing causes HTTP 429 rate limit errors in Lambda', 'quota', 'MEDIUM', '[{"solution": "Set tracesSampleRate: 0 to disable tracing and reduce load", "percentage": 94}, {"solution": "Use lower tracesSampleRate (0.01-0.1) instead of 1.0", "percentage": 92}]'::jsonb, 'AWS Lambda with Sentry integration', 'Lambda executes without rate limiting errors', 'Using tracesSampleRate: 1.0 on high-volume Lambda functions', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/71058862', 'admin:1764225275'),

('Apply rate limiting when Sentry server overloaded', 'quota', 'LOW', '[{"solution": "Use Dynamic sampling in Sentry to automatically adjust sample rates", "percentage": 87}, {"solution": "Implement SDK-level filtering before sending events", "percentage": 84}]'::jsonb, 'Sentry SDK with filtering capabilities', 'Events filtered dynamically based on server load', 'Hardcoding sample rates without dynamic adjustment', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/77021507', 'admin:1764225275'),

('Sentry Raven client not properly configured in development', 'configuration', 'LOW', '[{"solution": "Set DSN to nil/null in development: dsn: ENV[''SENTRY_DSN'']", "percentage": 91}, {"solution": "Use environment-based configuration: only init Sentry in production", "percentage": 89}]'::jsonb, 'Raven client configured', 'Development environment doesn''t spam Sentry', 'Sending all development errors to production Sentry account', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/35888806', 'admin:1764225275'),

('Event CustomEvent unhandled rejection error spike', 'error-handling', 'LOW', '[{"solution": "Filter CustomEvent errors in ignoreErrors config", "percentage": 79}, {"solution": "Identify source of CustomEvent rejections and fix root cause", "percentage": 88}]'::jsonb, 'Event handler code with CustomEvent', 'CustomEvent errors either filtered or resolved', 'Ignoring the underlying issue causing CustomEvent rejections', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/tagged/unhandled-promise-rejection', 'admin:1764225275'),

('Source maps not resolving in NestJS application', 'debugging', 'LOW', '[{"solution": "Use webpack compiler: nest build --webpack to generate proper source maps", "percentage": 92}, {"solution": "Upload source maps explicitly via Sentry CLI or webpack plugin", "percentage": 89}]'::jsonb, 'NestJS project with source maps enabled', 'Stack traces resolve to original TypeScript files', 'Not using webpack compiler or not uploading maps', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/63615262', 'admin:1764225275');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Sentry setup not capturing Flask exceptions', 'configuration', 'MEDIUM', '[{"solution": "Import and use Raven Client with logging handler: from raven import Client; sentry_client = Client(dsn=''...''); handler = SentryHandler(sentry_client)", "percentage": 93}, {"solution": "Set up logging handler with setup_logging() and attach to logger", "percentage": 91}]'::jsonb, 'Flask app with DSN from Sentry', 'Flask exceptions appear in Sentry dashboard', 'Using Sentry(app) without proper logging handler setup - DSN alone is insufficient', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/50831205', 'admin:1764225275');
