-- iOS Core Data Errors Migration
-- Mined from Stack Overflow and official documentation
-- Covers NSManagedObjectValidationError, NSValidationMissingMandatoryPropertyError, migration errors, etc.

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('NSManagedObjectValidationError: Generic validation error', 'ios-coredata', 'HIGH', '[{"solution": "Check error userInfo for NSValidationErrorKey and NSValidationErrorObject to identify which attribute failed validation", "percentage": 95}, {"solution": "Implement switch statement to handle specific validation error codes: NSValidationMissingMandatoryPropertyError, NSValidationNumberTooLargeError, etc.", "percentage": 85}]'::jsonb, 'iOS Core Data, NSManagedObject subclass', 'Validation error details displayed to user, handled gracefully', 'Ignoring detailed error userInfo, missing mandatory property validation', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/2262704/iphone-core-data-production-error-handling', 'admin:1764216790'),

('NSValidationMissingMandatoryPropertyError: The operation couldn''t be completed. (Cocoa error 1570.)', 'ios-coredata', 'HIGH', '[{"solution": "Make the attribute optional in Core Data model, or provide a default value in the mapping model during migration", "percentage": 98}, {"solution": "In migration, use NSPropertyMappingPolicy to assign a default value to non-optional attributes", "percentage": 90}, {"solution": "Check that all mandatory attributes are set before calling save on NSManagedObjectContext", "percentage": 95}]'::jsonb, 'Core Data model with mandatory attributes, NSMigrationError context', 'Migration completes successfully, objects save without validation errors', 'Forgetting to set default values for new mandatory attributes in migrations', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/23428813/core-data-migration-fails-but-whats-happening', 'admin:1764216790'),

('NSPersistentStoreIncompatibleSchemaError: This NSPersistentStoreCoordinator has no persistent stores (schema mismatch or migration failure)', 'ios-coredata', 'CRITICAL', '[{"solution": "Create a new model version instead of editing existing model: Editor > Add Model Version in Xcode", "percentage": 99}, {"solution": "Set the new model version as Current in File Inspector after creating new version", "percentage": 98}, {"solution": "Enable lightweight migration with NSMigratePersistentStoresAutomaticallyOption and NSInferMappingModelAutomaticallyOption keys set to YES", "percentage": 96}]'::jsonb, 'Xcode project with Core Data model, must have old and new model versions', 'Persistent store loads successfully, app launches without schema errors', 'Editing existing xcdatamodel instead of creating new version, missing migration options', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/36130416/this-nspersistentstorecoordinator-has-no-persistent-stores-schema-mismatch-or-m', 'admin:1764216790'),

('NSPersistentStoreSaveError: Failed to save persistent store', 'ios-coredata', 'HIGH', '[{"solution": "Check NSError userInfo for NSUnderlyingError to see the root cause (validation, constraint, or SQLite error)", "percentage": 92}, {"solution": "Verify all mandatory relationships and attributes are set before save", "percentage": 88}, {"solution": "Check disk space and file permissions for the SQLite database file", "percentage": 85}]'::jsonb, 'NSManagedObjectContext with unsaved changes, error handling setup', 'Save operation succeeds, objects persisted to Core Data store', 'Not checking userInfo for underlying errors, ignoring validation errors', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/22378399/proper-way-for-handling-core-data-save-error', 'admin:1764216790'),

('NSMigrationError: Persistent store migration failed, missing source managed object model', 'ios-coredata', 'CRITICAL', '[{"solution": "Ensure all model versions used in migrations are included in app bundle and marked as Compiled", "percentage": 97}, {"solution": "Use Core Data debugging: -com.apple.CoreData.SQLDebug 1 to see migration process and model hashes", "percentage": 88}, {"solution": "Do not merge models; let Core Data automatically discover source model during migration", "percentage": 94}]'::jsonb, 'Multiple Core Data model versions, at least 2 xcdatamodel files', 'Migration completes, persistent store loads with new model', 'Merging models manually with modelByMergingModels, missing source model in bundle', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/2492103/core-data-migration-problem-persistent-store-migration-failed-missing-source', 'admin:1764216790'),

('NSMigrationConstraintViolationError: Cannot migrate store in-place: constraint violation during attempted migration', 'ios-coredata', 'CRITICAL', '[{"solution": "Add uniqueness constraint in new model version instead of old version to avoid constraint violations during migration", "percentage": 96}, {"solution": "If constraint exists, remove it before migration and re-add after migration completes", "percentage": 92}, {"solution": "Use a mapping model instead of lightweight migration when constraints change", "percentage": 90}]'::jsonb, 'Core Data models with uniqueness constraints, migration version setup', 'Migration succeeds without constraint violation errors, data preserves uniqueness', 'Adding constraints to existing data that violates new constraint rules', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/39378379/coredata-crash-on-migration-with-nsmigrationconstraintviolationerror-134111-er', 'admin:1764216790'),

('NSSQLiteError: duplicate column name ZCOLUMN during migration', 'ios-coredata', 'CRITICAL', '[{"solution": "Verify new model version doesn''t have duplicate column additions - check xcdatamodel XML", "percentage": 95}, {"solution": "Delete old migration destination files (.sqlite.migrationdestination) from app sandbox", "percentage": 93}, {"solution": "Create clean new model version from scratch instead of copying old version", "percentage": 90}]'::jsonb, 'iOS 13+, Core Data model changes, SQLite persistent store', 'Migration completes on iOS 13+, no duplicate column errors, data persists', 'Adding same column twice in model mapping, stale migration destination files', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/58215343/an-error-occurring-during-core-data-persistent-store-migration-in-ios-13', 'admin:1764216790'),

('NSInvalidArgumentException: executeFetchRequest:error: is not a valid NSFetchRequest', 'ios-coredata', 'HIGH', '[{"solution": "Use NSFetchRequest(entityName:) constructor instead of [[NSFetchRequest alloc] init] for implicit entity specification", "percentage": 94}, {"solution": "Ensure NSFetchRequest is initialized with entity name or entity description before executing fetch", "percentage": 96}, {"solution": "In Swift, use EntityName.fetchRequest() if generated NSManagedObject subclass provides this method", "percentage": 97}]'::jsonb, 'iOS Core Data, NSManagedObject subclass, fetch request setup', 'Fetch request executes without exception, returns results array', 'Creating bare NSFetchRequest without specifying entity, incorrect initialization', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/41214124/fetch-request-error-core-data-swift-3', 'admin:1764216790'),

('NSValidationStringTooShortError: String attribute length validation failed', 'ios-coredata', 'MEDIUM', '[{"solution": "Set minimum length constraint in Core Data model editor for string attributes", "percentage": 98}, {"solution": "Validate string length in view controller before passing to Core Data", "percentage": 96}, {"solution": "Use validateValue:forKey:error: method to check validation before saving context", "percentage": 92}]'::jsonb, 'iOS Core Data model, string attribute with length constraints', 'String validation passes, Core Data save succeeds without length errors', 'Not validating string length before Core Data save, ignoring model constraints', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/21166466/how-to-get-a-meaningful-error-message-back-to-the-view-controller-with-core-data', 'admin:1764216790'),

('NSValidationStringTooLongError: String attribute exceeds maximum length', 'ios-coredata', 'MEDIUM', '[{"solution": "Set maximum length constraint in Core Data model editor, use reasonable limits like 255 chars", "percentage": 98}, {"solution": "Truncate user input to max length before assigning to managed object", "percentage": 95}, {"solution": "Display validation error message to user with max length requirement", "percentage": 92}]'::jsonb, 'iOS Core Data, NSManagedObject with constrained string properties', 'String assignment succeeds within max length, no validation errors on save', 'Allowing unlimited user input, not enforcing max length constraints', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/21166466/how-to-get-a-meaningful-error-message-back-to-the-view-controller-with-core-data', 'admin:1764216790'),

('NSValidationNumberTooLargeError: Numeric value exceeds maximum constraint', 'ios-coredata', 'MEDIUM', '[{"solution": "Set max value constraint in Core Data model editor for numeric attributes", "percentage": 97}, {"solution": "Validate numeric input range before assignment to managed object", "percentage": 95}, {"solution": "Use NSDecimalNumber instead of NSNumber for precise numeric storage and validation", "percentage": 88}]'::jsonb, 'Core Data numeric attribute, value range constraints defined', 'Numeric values accepted within range, save completes without validation errors', 'Not validating numeric ranges, exceeding max values in model constraints', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/21166466/how-to-get-a-meaningful-error-message-back-to-the-view-controller-with-core-data', 'admin:1764216790'),

('NSValidationNumberTooSmallError: Numeric value below minimum constraint', 'ios-coredata', 'MEDIUM', '[{"solution": "Set minimum value constraint in Core Data model editor", "percentage": 97}, {"solution": "Validate that numeric values meet minimum requirement before Core Data assignment", "percentage": 94}, {"solution": "Use default values in model to prevent minimum constraint violations", "percentage": 91}]'::jsonb, 'Core Data model with numeric min value constraints', 'Numeric values meet minimum requirements, save succeeds', 'Assigning values below minimum threshold without validation', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/21166466/how-to-get-a-meaningful-error-message-back-to-the-view-controller-with-core-data', 'admin:1764216790'),

('NSValidationDateTooLateError: Date value exceeds maximum date constraint', 'ios-coredata', 'LOW', '[{"solution": "Set max date constraint in Core Data model editor for date attributes", "percentage": 96}, {"solution": "Validate date range before assigning to managed object", "percentage": 93}, {"solution": "Use reasonable date limits (e.g., today for most apps, future date for scheduling)", "percentage": 90}]'::jsonb, 'Core Data date attribute with max date constraint', 'Date assignment succeeds within allowed range, validation passes', 'Not enforcing date constraints, allowing dates beyond business logic limits', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/21166466/how-to-get-a-meaningful-error-message-back-to-the-view-controller-with-core-data', 'admin:1764216790'),

('NSValidationDateTooEarlyError: Date value earlier than minimum date constraint', 'ios-coredata', 'LOW', '[{"solution": "Set minimum date constraint in Core Data model editor", "percentage": 96}, {"solution": "Validate date meets minimum requirement before Core Data save", "percentage": 94}, {"solution": "Use NSDate or Calendar to compute valid date ranges for validation", "percentage": 89}]'::jsonb, 'Core Data model with date min constraint', 'Date values meet minimum requirement, save completes', 'Assigning dates before minimum threshold without validation', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/21166466/how-to-get-a-meaningful-error-message-back-to-the-view-controller-with-core-data', 'admin:1764216790'),

('NSValidationRelationshipLacksMinimumCountError: Relationship doesn''t have enough entries', 'ios-coredata', 'MEDIUM', '[{"solution": "Set minimum count constraint in Core Data model for relationships", "percentage": 96}, {"solution": "Ensure minimum number of related objects are added before save", "percentage": 94}, {"solution": "Lazy-load relationships and verify count before context save", "percentage": 91}]'::jsonb, 'Core Data many-to-one relationship with minimum count constraint', 'Relationship satisfies minimum count requirement, save succeeds', 'Not validating relationship count before save, insufficient related objects', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/2262704/iphone-core-data-production-error-handling', 'admin:1764216790'),

('NSValidationRelationshipExceedsMaximumCountError: Relationship has too many entries', 'ios-coredata', 'MEDIUM', '[{"solution": "Set maximum count constraint in Core Data model for relationships", "percentage": 97}, {"solution": "Check relationship count before adding new related objects", "percentage": 95}, {"solution": "Remove excess related objects or increase max count in model if business logic allows", "percentage": 90}]'::jsonb, 'Core Data relationship with max count constraint', 'Relationship stays within max count limit, add operations succeed', 'Not enforcing max relationship count, adding too many related objects', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/2262704/iphone-core-data-production-error-handling', 'admin:1764216790'),

('NSValidationRelationshipDeniedDeleteError: Cannot delete object, relationship must be empty first', 'ios-coredata', 'HIGH', '[{"solution": "Clear all relationships to object before deletion by removing from related collections", "percentage": 98}, {"solution": "Set delete rule to Cascade in model if you want automatic deletion of related objects", "percentage": 96}, {"solution": "Check NSDeleteRuleOptions: Cascade, Deny, Nullify, No Action", "percentage": 94}]'::jsonb, 'Core Data object with relationships, delete operation requested', 'Object deletion succeeds after clearing relationships, cascade rules work', 'Trying to delete object with active relationships without clearing them first', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/2262704/iphone-core-data-production-error-handling', 'admin:1764216790'),

('NSValidationMultipleErrorsError: Multiple validation errors occurred on save', 'ios-coredata', 'HIGH', '[{"solution": "Access NSDetailedErrorsKey in error userInfo to get array of individual validation errors", "percentage": 98}, {"solution": "Loop through all errors and display each validation issue to user", "percentage": 96}, {"solution": "Validate all properties using validateValue:forKey:error: before save attempt", "percentage": 94}]'::jsonb, 'Core Data object with multiple validation constraints', 'All validation errors identified, user presented with complete error summary', 'Only checking first error, not iterating through NSDetailedErrorsKey array', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/2262704/iphone-core-data-production-error-handling', 'admin:1764216790'),

('NSMappingError: Persistent store migration failed, missing mapping model', 'ios-coredata', 'CRITICAL', '[{"solution": "Create custom mapping model when lightweight migration cannot handle the change", "percentage": 98}, {"solution": "Ensure mapping model source and destination entities match data models exactly", "percentage": 96}, {"solution": "Use Editor > Create Mapping Model in Xcode when automatic inference fails", "percentage": 95}]'::jsonb, 'Complex Core Data model changes, custom mapping model required', 'Migration completes with mapping model, data transforms correctly', 'Relying only on lightweight migration for complex changes, missing mapping model', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/48851805/coredata-lightweight-migration-fails', 'admin:1764216790'),

('Core Data error when fetching: NSFetchRequest missing entity specification', 'ios-coredata', 'HIGH', '[{"solution": "Always specify entity in NSFetchRequest: [[NSFetchRequest alloc] initWithEntityName:@\"EntityName\"]", "percentage": 98}, {"solution": "Use Entity.fetchRequest() in Swift for proper initialization with entity context", "percentage": 97}, {"solution": "Verify NSFetchRequest is not nil and entity description is set before execution", "percentage": 95}]'::jsonb, 'iOS Core Data, NSManagedObjectContext ready to fetch', 'Fetch request executes successfully, returns expected results', 'Creating NSFetchRequest without entity name, executing incomplete requests', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/36107488/core-data-error-when-fetching', 'admin:1764216790'),

('Core Data mutation during enumeration: Collection was mutated while being enumerated', 'ios-coredata', 'CRITICAL', '[{"solution": "Don''t modify NSSet/NSArray while enumerating: copy to temp array first before modifying", "percentage": 98}, {"solution": "Use makeIterator() or convert to Array before modifying collection in observer", "percentage": 97}, {"solution": "Check NSManagedObjectContextObjectsDidChangeNotification observers for mutations", "percentage": 95}]'::jsonb, 'NSManagedObjectContext with change observers, KVO notifications enabled', 'Change notifications processed without crashes, context mutations safe', 'Modifying managed object set/array during change notification enumeration', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/47936235/having-an-error-when-fetching-request-of-core-data', 'admin:1764216790'),

('Type mismatch error: Cannot assign NSManagedObject to custom class type', 'ios-coredata', 'HIGH', '[{"solution": "Ensure entity name matches NSManagedObject subclass exactly in model", "percentage": 98}, {"solution": "Use generated NSManagedObject subclass types from Entity+CoreDataClass.swift files", "percentage": 97}, {"solution": "Declare fetch results with correct type: [EntityClass]() not [CustomClass]()", "percentage": 96}]'::jsonb, 'Core Data with NSManagedObject subclasses, type-safe fetching', 'Fetch results match declared type, type casting succeeds', 'Mismatching entity name and class name, incorrect type casting', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/49352179/swift-coredata-error-and-how-to-set-up-entities-and-datamodels', 'admin:1764216790'),

('Core Data framework linking error: _OBJC_CLASS_$_NSFetchedResultsController not found', 'ios-coredata', 'MEDIUM', '[{"solution": "Add CoreData.framework to Build Phases > Link Binary With Libraries", "percentage": 99}, {"solution": "Verify CoreData framework is available in Target > General > Frameworks and Libraries", "percentage": 98}, {"solution": "Run Clean Build Folder (Cmd+Shift+K) after adding framework", "percentage": 96}]'::jsonb, 'Xcode iOS project using Core Data classes', 'Project compiles successfully, Core Data symbols resolved', 'Missing CoreData framework in build phases, linker symbol errors', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/5346341/errors-from-core-data-in-ipad-app', 'admin:1764216790'),

('NSPersistentStoreSaveError: SQLite error 10 - disk I/O error', 'ios-coredata', 'MEDIUM', '[{"solution": "Check available disk space, ensure minimum 10MB free for SQLite operations", "percentage": 97}, {"solution": "Verify file permissions on application Documents directory", "percentage": 95}, {"solution": "Use try-catch to catch and log NSError with NSSQLiteErrorDomain for debugging", "percentage": 92}]'::jsonb, 'iOS app with Core Data SQLite store, file system access', 'Save operations succeed with adequate disk space and permissions', 'Running on device with low disk space, invalid file permissions on store', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/39155955/ios-core-data-savecontext-method-is-unsuccessful-due-to-nssqliteerrordomain-10', 'admin:1764216790'),

('NSPersistentStoreSaveError: SQLite error 11 - database file too large', 'ios-coredata', 'MEDIUM', '[{"solution": "Implement periodic cleanup to delete old data and reduce store size", "percentage": 94}, {"solution": "Archive data to separate SQLite database if size exceeds platform limits", "percentage": 91}, {"solution": "Monitor store file size in MB, consider pagination if exceeds 100MB", "percentage": 88}]'::jsonb, 'iOS Core Data with large datasets, SQLite store optimization', 'Save operations succeed, store remains within platform size limits', 'Never cleaning old data, allowing SQLite file to grow unbounded', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/8948509/ios-core-data-and-disk-space', 'admin:1764216790'),

('NSCoreDataError: The managed object model version used to open persistent store is incompatible', 'ios-coredata', 'CRITICAL', '[{"solution": "Create new model version and set as Current Version in model file properties", "percentage": 99}, {"solution": "Always create version before making ANY changes to existing model", "percentage": 98}, {"solution": "Enable automatic lightweight migration in NSPersistentStoreCoordinator options", "percentage": 97}]'::jsonb, 'Core Data model with version control, persistent store file exists', 'Store opens successfully with compatible model version, no incompatibility errors', 'Editing model directly without creating new version, incompatible schema on device', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/43279438/nspersistentstorecoordinator-has-no-persistent-storesschema-mismatch-or-migrati', 'admin:1764216790'),

('NSFetchRequest parsing error: Invalid fetch request - missing or invalid predicate', 'ios-coredata', 'MEDIUM', '[{"solution": "Check NSPredicate syntax for fetch request, use proper KVC key paths", "percentage": 96}, {"solution": "Test predicate with sample data to verify it returns expected results", "percentage": 94}, {"solution": "Use @try-catch to capture detailed NSError with predicate parsing issues", "percentage": 91}]'::jsonb, 'iOS Core Data fetch with NSPredicate filters', 'Fetch with predicates returns correct filtered results', 'Invalid predicate syntax, incorrect KVC key paths in predicates', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/23520014/why-does-context-executefetchrequest-request-error-error-fail-to-get-data-s', 'admin:1764216790'),

('Core Data aggregate query error: HAVING clause without GROUP BY', 'ios-coredata', 'MEDIUM', '[{"solution": "Add GROUP BY to @count/@sum/@avg aggregate queries if using HAVING", "percentage": 98}, {"solution": "Use returnsDistinctResults property correctly for aggregate functions", "percentage": 96}, {"solution": "Verify resultType is set to DictionaryResultType for aggregate queries", "percentage": 95}]'::jsonb, 'Core Data aggregate fetch requests with GROUP BY/HAVING clauses', 'Aggregate queries execute successfully, return correct group results', 'Using HAVING without GROUP BY, incorrect aggregate query setup', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/57082773/core-data-exception-error-invalid-fetch-request-having-with-no-group-by-with', 'admin:1764216790'),

('NSInternalInconsistencyException: Serious application error - Core Data change processing failed', 'ios-coredata', 'HIGH', '[{"solution": "Check observers of NSManagedObjectContextObjectsDidChangeNotification for bugs", "percentage": 98}, {"solution": "Avoid modifying managed objects in notifications - use dispatch_async to defer changes", "percentage": 97}, {"solution": "Verify thread safety - access Core Data only from correct thread/queue", "percentage": 95}]'::jsonb, 'iOS Core Data with change notifications and observers', 'Change notifications process without exception, context state consistent', 'Modifying Core Data in change notification observers, thread safety violations', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/47936235/having-an-error-when-fetching-request-of-core-data', 'admin:1764216790'),

('NSMigrationError: Cannot migrate store in-place due to SQL syntax error', 'ios-coredata', 'CRITICAL', '[{"solution": "Verify model mapping - check for invalid default values or expressions", "percentage": 96}, {"solution": "Delete stale migration destination files from app container", "percentage": 94}, {"solution": "Create fresh new model version from scratch instead of copying previous version", "percentage": 92}]'::jsonb, 'Core Data migration in progress, model versions defined', 'Migration completes successfully, data transfers without SQL errors', 'Invalid expressions in mapping model, duplicate column definitions', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/75488717/an-error-occurred-during-persistent-store-migration-cannot-migrate-store-in-pla', 'admin:1764216790'),

('NSPropertyMappingError: Source property missing or invalid during migration mapping', 'ios-coredata', 'HIGH', '[{"solution": "Verify property names in mapping model match source and destination models exactly", "percentage": 98}, {"solution": "Use Xcode mapping model editor to match all entity and property mappings correctly", "percentage": 97}, {"solution": "Check for renamed attributes - use mapping model to handle renamed properties", "percentage": 96}]'::jsonb, 'Core Data migration with custom mapping model', 'Migration completes, all properties map correctly, data preserves', 'Mismatched property names in mapping, deleted source properties not handled', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/2492103/core-data-migration-problem-persistent-store-migration-failed-missing-source', 'admin:1764216790'),

('NSManagedObjectClassNotFoundError: Cannot find NSManagedObject subclass for entity', 'ios-coredata', 'HIGH', '[{"solution": "Generate NSManagedObject subclass from entity: Editor > Create NSManagedObject Subclass", "percentage": 99}, {"solution": "Ensure generated subclass files are added to Target membership in File Inspector", "percentage": 98}, {"solution": "Check that NSManagedObject class name matches entity name in model", "percentage": 97}]'::jsonb, 'Core Data entity without corresponding NSManagedObject subclass', 'Entity has generated subclass, can instantiate and use properly', 'Missing NSManagedObject subclass generation, entity class name mismatch', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/49352179/swift-coredata-error-and-how-to-set-up-entities-and-datamodels', 'admin:1764216790'),

('NSConstraintValidationError: Uniqueness constraint violation in Core Data', 'ios-coredata', 'HIGH', '[{"solution": "Set Unique constraint in model editor only for attributes that should be unique", "percentage": 98}, {"solution": "Check for duplicate values before insert, query existing with NSFetchRequest", "percentage": 97}, {"solution": "Use Upsert pattern: fetch existing, update if found, insert if not", "percentage": 95}]'::jsonb, 'Core Data entity with unique attribute constraint', 'Objects with unique values save successfully, duplicates rejected with error', 'Allowing duplicate values for constrained attributes, ignoring uniqueness', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/39378379/coredata-crash-on-migration-with-nsmigrationconstraintviolationerror-134111-er', 'admin:1764216790'),

('Core Data lightweight migration fails: Cannot infer mapping model automatically', 'ios-coredata', 'HIGH', '[{"solution": "Use custom mapping model for complex changes: attribute type changes, relationship changes", "percentage": 97}, {"solution": "Try simpler changes first: add optional attributes, delete attributes, rename with mapping", "percentage": 95}, {"solution": "Enable SQL debugging to see exact migration SQL and identify problem", "percentage": 92}]'::jsonb, 'Core Data models with complex structural changes', 'Migration completes using mapping model, data integrity preserved', 'Complex changes without mapping model, relying on automatic inference', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/48851805/coredata-lightweight-migration-fails', 'admin:1764216790'),

('NSFetchedResultsController error: Unable to initialize with fetch request', 'ios-coredata', 'MEDIUM', '[{"solution": "Ensure NSFetchRequest has valid entity and sortDescriptors before NSFetchedResultsController init", "percentage": 98}, {"solution": "Always provide at least one NSSortDescriptor for section ordering", "percentage": 96}, {"solution": "Verify managedObjectContext is valid and connected to persistent store", "percentage": 95}]'::jsonb, 'iOS table view with NSFetchedResultsController, fetch request configured', 'FetchedResultsController initializes and tracks changes, performs fetches', 'Missing entity specification, no sort descriptors, invalid context', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/34618305/adding-a-breakpoint-to-breakpoint-navigator-for-a-core-data-error', 'admin:1764216790'),

('NSPersistentStoreUbiquitousContentNameMismatchError: iCloud Core Data sync mismatch', 'ios-coredata', 'MEDIUM', '[{"solution": "Use same ubiquitous content name consistently across app versions", "percentage": 97}, {"solution": "Disable iCloud sync, clear ubiquitous container, re-enable to reset sync state", "percentage": 94}, {"solution": "Monitor com.apple.CoreData.ConcurrencyDebug logging for sync conflicts", "percentage": 88}]'::jsonb, 'iOS app with iCloud Core Data sync enabled', 'iCloud sync works consistently, no content name mismatches', 'Changing ubiquitousContentName mid-deployment, syncing old cloud data', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/36107488/core-data-error-when-fetching', 'admin:1764216790');
