-- Mining: 35 Webpack Errors for clauderepo
-- Mined from Stack Overflow on 2025-11-27
-- Covers: Module resolution, configuration, loaders, HMR, memory, tree shaking, source maps

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('Module not found: Error: Cannot resolve module', 'bundler', 'CRITICAL', '[{"solution": "Add resolve.extensions to webpack.config.js with required extensions like .js, .jsx, .ts", "percentage": 95}, {"solution": "Check if file path is correct and case-sensitive (paths are case-sensitive on Linux/Mac)", "percentage": 90}, {"solution": "Add resolve.modules to tell webpack where to look for modules", "percentage": 85}]'::jsonb, 'Webpack configured with loaders', 'Module resolves without errors', 'Missing file extension handling, case-sensitivity issues', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/46850288/webpack-module-not-found-even-though-module-exists', 'admin:1764227303'),

('Cannot resolve with relative path webpack', 'bundler', 'HIGH', '[{"solution": "Add missing file extensions to resolve.extensions: [.js, .jsx, .ts, .tsx]", "percentage": 88}, {"solution": "Check folder name case sensitivity - ''Container'' vs ''container''", "percentage": 92}, {"solution": "Verify relative path syntax is correct with ../ prefix", "percentage": 80}]'::jsonb, 'Webpack with ES6 imports', 'Imports resolve successfully', 'Not checking filesystem case sensitivity, wrong relative paths', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/45968302/webpack-module-not-found-error-cant-resolve-with-relative-path', 'admin:1764227303'),

('Cannot resolve util webpack 5', 'bundler', 'HIGH', '[{"solution": "Install util package: npm install util", "percentage": 98}, {"solution": "Add resolve.fallback for Node.js core modules in webpack.config.js", "percentage": 85}, {"solution": "Configure: resolve.fallback: { util: require.resolve(\"util/\") }", "percentage": 90}]'::jsonb, 'Webpack 5+, Node.js environment', 'util module loads without error', 'Using Webpack 5 without polyfill configuration', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/64402821/module-not-found-error-cant-resolve-util-in-webpack', 'admin:1764227303'),

('Invalid configuration object webpack has been initialised', 'bundler', 'CRITICAL', '[{"solution": "Change ''loaders'' to ''rules'' in webpack config (Webpack 2+ syntax)", "percentage": 97}, {"solution": "Ensure webpack version matches config format - check package.json", "percentage": 88}, {"solution": "Remove invalid properties like ''postcss'', use LoaderOptionsPlugin instead", "percentage": 80}]'::jsonb, 'Webpack 2+, configuration file', 'Webpack builds without validation errors', 'Using old Webpack 1 config format with Webpack 2+', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/42060243/invalid-configuration-object-webpack-has-been-initialised-using-a-configuration', 'admin:1764227303'),

('Invalid configuration devServer in wrong location', 'bundler', 'HIGH', '[{"solution": "Move devServer object outside of module.rules - it should be at root level", "percentage": 99}, {"solution": "Correct structure: { entry, output, devServer, module }", "percentage": 98}]'::jsonb, 'Webpack dev-server, configuration file', 'devServer configuration accepted', 'Nesting devServer inside module object', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/51288398/invalid-configuration-object-webpack-has-been-initialized-using-a-configuration', 'admin:1764227303'),

('[HMR] Update failed: Error: Failed to fetch update manifest', 'bundler', 'HIGH', '[{"solution": "Import bundled JS file on same port as webpack-dev-server in HTML script tag", "percentage": 94}, {"solution": "Ensure publicPath in webpack config matches script src protocol and port", "percentage": 88}, {"solution": "Remove writeToDisk: true if causing file accumulation - not needed with proper setup", "percentage": 75}]'::jsonb, 'Webpack dev-server, hot module replacement enabled', 'HMR updates apply without manual page reload', 'Script tag importing from different port than dev-server', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/67131863/webpack-dev-server-hmr-update-failed-error-failed-to-fetch-update-manifest', 'admin:1764227303'),

('Webpack tree shaking not working unused exports', 'bundler', 'MEDIUM', '[{"solution": "Configure tsconfig.json to preserve ES6 module syntax - set module to ES6 or ESNext", "percentage": 96}, {"solution": "Set optimization.usedExports: true and sideEffects: false in package.json", "percentage": 92}, {"solution": "Ensure babel-loader is not transpiling to CommonJS", "percentage": 88}]'::jsonb, 'TypeScript, ES6 modules, production mode', 'Unused exports removed from bundle', 'tsconfig transpiling to CommonJS, breaking tree-shaking', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/71679366/webpack5-does-not-seem-to-tree-shake-unused-exports', 'admin:1764227303'),

('Module build failed from babel-loader cannot find preset', 'bundler', 'HIGH', '[{"solution": "Install Babel 7: npm install @babel/core @babel/preset-env", "percentage": 95}, {"solution": "Update .babelrc to use @babel/preset-env instead of babel-preset-env", "percentage": 98}, {"solution": "Ensure babel and babel-loader versions match (both major versions)", "percentage": 92}]'::jsonb, 'Babel configured, package.json with loaders', 'Babel presets load and transpile successfully', 'Babel 6/7 version mismatch, missing preset installation', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/56098779/how-to-fix-module-build-failed-from-node-modules-babel-loader-lib-index-js', 'admin:1764227303'),

('Output path needs to be an absolute path', 'bundler', 'CRITICAL', '[{"solution": "Use path.join(__dirname, \"dist\") instead of relative paths", "percentage": 99}, {"solution": "Require path module at top: const path = require(''path'')", "percentage": 100}, {"solution": "Alternative: path.resolve(__dirname, \"dist\")", "percentage": 98}]'::jsonb, 'Node.js project, webpack dev-server', 'webpack-dev-server starts without path errors', 'Using relative paths like \"dist/js\" instead of absolute', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/42166492/getting-error-output-path-needs-to-be-an-absolute-path-or', 'admin:1764227303'),

('JavaScript heap out of memory webpack', 'bundler', 'MEDIUM', '[{"solution": "Increase Node heap size: node --max-old-space-size=8192 node_modules/webpack/bin/webpack.js", "percentage": 96}, {"solution": "Set NODE_OPTIONS environment variable: NODE_OPTIONS=--max_old_space_size=8192", "percentage": 94}, {"solution": "Optimize webpack build - check for circular dependencies, large bundles", "percentage": 70}]'::jsonb, 'Webpack build with large number of modules', 'Build completes without memory errors', 'Default Node.js heap too small for large projects', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/51536623/webpack-out-of-memory', 'admin:1764227303'),

('Cannot resolve babel-loader webpack', 'bundler', 'HIGH', '[{"solution": "Install babel-loader: npm install --save-dev babel-loader", "percentage": 99}, {"solution": "Ensure webpack and babel-loader are compatible versions", "percentage": 88}, {"solution": "Check node_modules - reinstall if broken: npm install", "percentage": 92}]'::jsonb, 'Webpack with Babel transpilation', 'Babel-loader found and configured', 'Missing babel-loader installation or corrupted node_modules', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/45806392/error-cant-resolve-babel-loader', 'admin:1764227303'),

('Webpack CSS loader syntax error cannot resolve', 'bundler', 'HIGH', '[{"solution": "Remove quotes from regex: test: /\\.css$/ not test: \"/\\.css$/\"", "percentage": 97}, {"solution": "Ensure style-loader and css-loader are installed and in correct order", "percentage": 95}, {"solution": "Import CSS in entry point: import ''./style.css''", "percentage": 80}]'::jsonb, 'Webpack with CSS files, style and css loaders', 'CSS files processed without syntax errors', 'Regex pattern in quotes, wrong loader order', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/49950908/error-loading-css-file-in-webpack', 'admin:1764227303'),

('Cannot resolve file-loader for images webpack', 'bundler', 'MEDIUM', '[{"solution": "Install file-loader: npm install --save-dev file-loader", "percentage": 98}, {"solution": "Webpack 5+: Use Asset Modules instead - type: ''asset''", "percentage": 85}, {"solution": "Set url-loader limit high enough if using url-loader fallback", "percentage": 75}]'::jsonb, 'Webpack with image assets', 'Images load correctly in bundled app', 'file-loader not installed, broken installation', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/34352929/webpack-cannot-resolve-module-file-loader', 'admin:1764227303'),

('Webpack is not failing on TypeScript error', 'bundler', 'MEDIUM', '[{"solution": "Install fork-ts-checker-webpack-plugin: npm install --save-dev fork-ts-checker-webpack-plugin", "percentage": 93}, {"solution": "Add plugin to webpack config plugins array", "percentage": 95}, {"solution": "Check ts-loader version - update if known to have bugs", "percentage": 60}]'::jsonb, 'Webpack 5+ with TypeScript, ts-loader', 'TypeScript errors reported on compilation', 'Missing fork-ts-checker-webpack-plugin, ts-loader bugs', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/64592611/webpack-is-not-failing-on-typescript-error', 'admin:1764227303'),

('Circular dependency warning webpack', 'bundler', 'MEDIUM', '[{"solution": "Separate circular imports into different files - refactor module structure", "percentage": 85}, {"solution": "Extract shared logic to independent file without circular refs", "percentage": 90}, {"solution": "Use index files cautiously - may introduce circular deps", "percentage": 70}]'::jsonb, 'Webpack bundler, ES6 modules', 'No circular dependency warnings', 'Poor file organization causing circular imports', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/70667723/circular-dependency-in-webpack', 'admin:1764227303'),

('Module build failed webpack react babel presets', 'bundler', 'MEDIUM', '[{"solution": "Install babel presets: npm install --save-dev babel-preset-react babel-preset-env", "percentage": 96}, {"solution": "Add query to loader: query: {presets: [''env'', ''react'']} in webpack config", "percentage": 94}, {"solution": "Delete node_modules and package-lock.json, run npm install fresh", "percentage": 80}]'::jsonb, 'Webpack, React, Babel configuration', 'React JSX transpiles without errors', 'Missing babel presets, version conflicts', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/33621866/module-build-failed-webpack-react-babel', 'admin:1764227303'),

('Entrypoint undefined html-webpack-plugin', 'bundler', 'MEDIUM', '[{"solution": "Use older html-webpack-plugin version (< 4.0) or update to compatible version", "percentage": 80}, {"solution": "Ensure entry point filename matches what plugin expects", "percentage": 70}, {"solution": "Check if using multiple entry points - html-webpack-plugin may need adjustment", "percentage": 65}]'::jsonb, 'Webpack with html-webpack-plugin', 'HTML generated with correct entry points', 'Version incompatibility between webpack and html-webpack-plugin', 0.75, 'haiku', NOW(), 'https://stackoverflow.com/questions/52013133/entrypoint-undefined-index-html-using-htmlwebpackplugin', 'admin:1764227303'),

('Loading chunk failed webpack code splitting', 'bundler', 'HIGH', '[{"solution": "Set correct publicPath in webpack output - ensure assets load from correct URL", "percentage": 96}, {"solution": "Use magic comment /* webpackMode: \"eager\" */ to avoid lazy chunk loading", "percentage": 70}, {"solution": "Implement retry logic for failed chunk loads in app", "percentage": 80}]'::jsonb, 'Webpack code splitting, dynamic imports', 'Chunks load on demand without failures', 'Incorrect publicPath, missing chunk files', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/53704950/webpack-code-splitting-loading-chunk-failed-error-wrong-file-path', 'admin:1764227303'),

('Webpack dev-server source map not generating', 'bundler', 'MEDIUM', '[{"solution": "Set devtool: ''cheap-module-source-map'' for dev, avoid old eval methods", "percentage": 92}, {"solution": "Ensure SourceMapDevToolPlugin is configured if custom setup", "percentage": 85}, {"solution": "Check webpack version - source map handling changed between versions", "percentage": 75}]'::jsonb, 'Webpack dev-server, development mode', 'Source maps generate and load in devtools', 'Wrong devtool option, missing SourceMapDevToolPlugin', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/32296967/webpack-dev-server-doesnt-generate-source-maps', 'admin:1764227303'),

('Webpack loader order chain configuration', 'bundler', 'MEDIUM', '[{"solution": "Loaders execute right-to-left: css-loader then style-loader", "percentage": 98}, {"solution": "Correct order: use: [''style-loader'', ''css-loader'', ''sass-loader'']", "percentage": 97}, {"solution": "Document loader chain in comments for clarity", "percentage": 70}]'::jsonb, 'Webpack with multiple loaders, CSS/SASS', 'Loaders process files correctly in sequence', 'Incorrect loader order in rules array', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/32234329/what-is-the-loader-order-for-webpack', 'admin:1764227303'),

('URL loader limit causing file-loader fallback error', 'bundler', 'MEDIUM', '[{"solution": "Set url-loader limit to large value or omit to avoid file-loader dependency", "percentage": 94}, {"solution": "Ensure file-loader is installed as fallback for url-loader", "percentage": 96}, {"solution": "Use Asset Modules in Webpack 5+ instead of url/file loaders", "percentage": 80}]'::jsonb, 'Webpack with url-loader for images', 'Images load without errors', 'url-loader limit too small, file-loader not installed', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/52219401/webpack-style-loader-css-loader-url-path-resolution-not-working', 'admin:1764227303'),

('Webpack source map from data URL parse failed', 'bundler', 'LOW', '[{"solution": "Ignore source map warnings if not critical for development", "percentage": 75}, {"solution": "Disable source maps in libraries causing issues if not needed", "percentage": 70}, {"solution": "Update affected library to newer version with proper source map support", "percentage": 60}]'::jsonb, 'Webpack with source maps, third-party libraries', 'Build completes despite warnings', 'Malformed source maps in dependencies', 0.68, 'haiku', NOW(), 'https://stackoverflow.com/questions/63195843/webpack-module-warning-failed-to-parse-source-map-from-data-url', 'admin:1764227303'),

('You may need appropriate loader to handle file type', 'bundler', 'HIGH', '[{"solution": "Add rule for file type: {test: /\\.type$/, use: ''loader-name''}", "percentage": 98}, {"solution": "Install required loader: npm install --save-dev loader-name", "percentage": 99}, {"solution": "Check webpack version for correct loader syntax (rules vs loaders)", "percentage": 88}]'::jsonb, 'Webpack with file imports', 'File type processed by correct loader', 'Missing loader for file type, old syntax', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/33469929/you-may-need-an-appropriate-loader-to-handle-this-file-type-with-webpack-and-b', 'admin:1764227303'),

('Webpack extract-text-plugin entrypoint undefined', 'bundler', 'MEDIUM', '[{"solution": "Use MiniCssExtractPlugin instead (extract-text deprecated in Webpack 4+)", "percentage": 95}, {"solution": "Ensure CSS chunk has proper entry point configuration", "percentage": 85}]'::jsonb, 'Webpack 4+, CSS extraction', 'CSS extracts to separate file without warnings', 'Using deprecated extract-text-webpack-plugin', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/50202908/entrypoint-undefined-extract-text-webpack-plugin-output-filename-in-webpack-4', 'admin:1764227303'),

('Webpack pug loader entrypoint undefined', 'bundler', 'LOW', '[{"solution": "Use pug-loader compatible with webpack version", "percentage": 80}, {"solution": "Ensure pug template imports are in entry chain", "percentage": 75}]'::jsonb, 'Webpack with Pug templating', 'Pug templates compile without errors', 'Old pug-loader version incompatibility', 0.73, 'haiku', NOW(), 'https://stackoverflow.com/questions/64227391/why-does-webpack-pug-generate-an-entrypoint-undefined-index-html-error', 'admin:1764227303'),

('Webpack stat collector error building', 'bundler', 'LOW', '[{"solution": "Check webpack configuration for stat collector setup", "percentage": 65}, {"solution": "Verify bundle analyzer or stat plugins are correctly configured", "percentage": 70}]'::jsonb, 'Webpack with bundle analysis tools', 'Stats collected without errors', 'Misconfigured stat collection plugin', 0.62, 'haiku', NOW(), 'https://stackoverflow.com/questions/42411794/webpack-build-error', 'admin:1764227303'),

('Webpack typescript tsconfig.json compilation error', 'bundler', 'MEDIUM', '[{"solution": "Set tsconfig lib to match target environment: lib: [''ES6'', ''DOM'']", "percentage": 88}, {"solution": "Ensure ts-loader resolveJsonModule: true if importing JSON", "percentage": 82}, {"solution": "Update TypeScript version to compatible with webpack version", "percentage": 75}]'::jsonb, 'Webpack with TypeScript, ts-loader', 'TypeScript files compile to JavaScript', 'tsconfig mismatch with webpack target', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/38727442/typescript-error-on-compilation-with-webpack', 'admin:1764227303'),

('Webpack typescript production build fails', 'bundler', 'MEDIUM', '[{"solution": "Ensure TypeScript strict mode compatible with codebase", "percentage": 80}, {"solution": "Use webpack.DefinePlugin to set NODE_ENV=production", "percentage": 85}, {"solution": "Check ts-loader skipLibCheck option for faster builds", "percentage": 75}]'::jsonb, 'Webpack TypeScript, production build', 'Production build succeeds with no type errors', 'Strict TypeScript settings incompatibility', 0.79, 'haiku', NOW(), 'https://stackoverflow.com/questions/58538056/webpack-typescript-production-build-fails', 'admin:1764227303'),

('Webpack React lazy code splitting error', 'bundler', 'MEDIUM', '[{"solution": "Ensure Suspense component wraps lazy components with fallback UI", "percentage": 92}, {"solution": "Use React.lazy() properly with proper error boundaries", "percentage": 88}, {"solution": "Check webpack output.chunkFilename format for lazy chunks", "percentage": 75}]'::jsonb, 'React with code splitting, lazy loading', 'Lazy components load asynchronously without errors', 'Missing Suspense wrapper, improper error handling', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/70328100/webpack-4-code-splitting-not-working-with-react-lazy', 'admin:1764227303'),

('Webpack mode development production difference tree shaking', 'bundler', 'MEDIUM', '[{"solution": "Set mode: ''production'' to enable tree shaking and minification", "percentage": 98}, {"solution": "Webpack tree shaking requires mode or explicit optimization config", "percentage": 96}, {"solution": "Development mode disables optimizations by default", "percentage": 99}]'::jsonb, 'Webpack 4+, production optimization', 'Unused code removed in production build', 'Using development mode for production bundle', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/56350947/what-is-different-between-webpack-production-and-development-regarding-tree-shak', 'admin:1764227303'),

('Webpack library distribution tree shaking configuration', 'bundler', 'MEDIUM', '[{"solution": "Configure package.json: ''sideEffects'': false to enable tree shaking", "percentage": 94}, {"solution": "Build library as ES6 modules, not CommonJS", "percentage": 92}, {"solution": "Document library entry point clearly for consumer tools", "percentage": 80}]'::jsonb, 'Library package, ES6 modules export', 'Library consumers can tree shake unused code', 'CommonJS export, missing sideEffects declaration', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/69322424/how-to-provide-webpack-tree-shaking-for-the-usage-of-library-distributing-as-es2', 'admin:1764227303'),

('Webpack dynamic import chunk failed error handling', 'bundler', 'MEDIUM', '[{"solution": "Implement error boundary for dynamic imports catching chunk load errors", "percentage": 88}, {"solution": "Use try-catch with import() to handle load failures gracefully", "percentage": 92}, {"solution": "Implement retry logic with exponential backoff for chunk loads", "percentage": 75}]'::jsonb, 'Webpack dynamic imports, code splitting', 'Failed chunks handled with user-friendly errors', 'No error handling for dynamic import failures', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/62048737/how-do-i-disable-webpack-4-code-splitting', 'admin:1764227303'),

('Webpack HTML plugin script tag injection', 'bundler', 'LOW', '[{"solution": "html-webpack-plugin injects scripts by default - no manual injection needed", "percentage": 90}, {"solution": "Remove manual script tags when using html-webpack-plugin", "percentage": 95}, {"solution": "Set inject: true in plugin options to auto-inject bundles", "percentage": 98}]'::jsonb, 'Webpack html-webpack-plugin, HTML generation', 'Bundle scripts auto-injected into HTML', 'Manual script tags conflicting with plugin injection', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/58796669/entrypoint-undefined-content-not-from-webpack-what-wrong-in-my-config', 'admin:1764227303'),

('Webpack resolve fallback lodash not tree shakeable', 'bundler', 'LOW', '[{"solution": "Import specific lodash methods: import map from ''lodash/map''", "percentage": 95}, {"solution": "Use lodash-es for ES6 modules if available", "percentage": 88}, {"solution": "Accept larger bundle with lodash or use alternative utility library", "percentage": 60}]'::jsonb, 'Webpack with lodash dependency', 'Bundle size optimized with lodash imports', 'Importing entire lodash namespace', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/58741044/why-webpack-doesnt-tree-shake-the-lodash-when-using-import-as', 'admin:1764227303');
