-- Express.js Error Handling Knowledge Base v2 - Mined from Stack Overflow
-- 10 critical error patterns and solutions

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Cannot capture top-level exceptions in Express', 'express', 'HIGH', '[{"solution": "Use process.uncaughtException event, but prefer running app under process monitor like forever", "percentage": 85}, {"solution": "Express errorHandler middleware captures thrown errors and next(err) calls", "percentage": 90}, {"solution": "Implement error handler as last middleware with (err, req, res, next) signature", "percentage": 95}]'::jsonb, 'Express 4.0+, Node.js process management', 'Process crashes handled gracefully, errors logged correctly', 'Placing error handler before route definitions, not using return with next(err)', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/9228582/how-to-handle-errors-in-node-js-using-express', 'admin:1764210300'),

('How to send error HTTP response from Express controller', 'express', 'HIGH', '[{"solution": "Use res.status(code).send({message: error})", "percentage": 97}, {"solution": "In Angular/client, catch in promise rejection handler and read response.data.message", "percentage": 92}, {"solution": "Return early from function after sending status to prevent multiple responses", "percentage": 88}]'::jsonb, 'Express HTTP methods, REST API design', 'Client receives correct status code and error object', 'Forgetting return statement after res.status/send, sending response twice', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/35864088/how-to-send-error-http-response-in-express-node-js', 'admin:1764210300'),

('Express throw error vs next(error) - which to use', 'express', 'CRITICAL', '[{"solution": "Use next(error) for async/callback scenarios where throw won''t be caught", "percentage": 98}, {"solution": "Throw only in synchronous code, express wraps in try/catch", "percentage": 89}, {"solution": "In async callbacks (fs.readFile), must use next(err) not throw", "percentage": 96}]'::jsonb, 'Understanding async JavaScript, Express middleware', 'Error reaches error handler middleware, no UnhandledPromiseRejection', 'Using throw in async callbacks, forgetting return with next()', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/27794750/node-js-with-express-throw-error-vs-nexterror', 'admin:1764210300'),

('Express error handler middleware not catching thrown errors', 'express', 'HIGH', '[{"solution": "Place error handler last in middleware stack, after app.use(app.router)", "percentage": 94}, {"solution": "Error handler must have 4 parameters: (err, req, res, next)", "percentage": 99}, {"solution": "Use return next(err) not next(err) to prevent headers already sent error", "percentage": 91}]'::jsonb, 'Express 3.x/4.x architecture, middleware ordering', 'Error page renders correctly without headers already sent error', 'Placing error handler before routes, having middleware continue after next(err)', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/15684130/express-js-error-handling', 'admin:1764210300'),

('Express error: Can''t set headers after they are sent', 'express', 'CRITICAL', '[{"solution": "Always use return next(new Error(...)) not just next(new Error(...))", "percentage": 97}, {"solution": "Ensure only one res.send/render call per request, check all code paths", "percentage": 95}, {"solution": "For 404: use return with next() in conditional, don''t fall through to send()", "percentage": 93}]'::jsonb, 'HTTP response lifecycle, middleware control flow', 'Single response sent, no headers conflict error', 'Sending response after next(err), missing return statements, async race conditions', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/7716691/how-to-properly-handle-errors-in-express', 'admin:1764210300'),

('UnhandledPromiseRejection in async Express middleware', 'express', 'CRITICAL', '[{"solution": "Wrap async middleware with asyncHandler function that catches rejections: Promise.resolve(fn()).catch(next)", "percentage": 98}, {"solution": "Use try/catch inside async handler and call next(err) on catch", "percentage": 96}, {"solution": "Use express-async-errors package: require(''express-async-errors'') at app start", "percentage": 94}]'::jsonb, 'ES6 Promises, async/await, Express 5.0+', 'Async errors reach error handler without UnhandledPromiseRejection warning', 'Forgetting try/catch in async routes, not awaiting promises properly', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/51391080/handling-errors-in-express-async-middleware', 'admin:1764210300'),

('Express best practice: centralized error handling vs try/catch everywhere', 'express', 'HIGH', '[{"solution": "Create one error handler middleware at end of app.use stack with (err,req,res,next) signature", "percentage": 96}, {"solution": "Define custom error classes (BadRequest, NotFound) extending Error with getCode() method", "percentage": 88}, {"solution": "Route handlers pass errors with next(err), never catch/respond individually", "percentage": 92}]'::jsonb, 'Error class design patterns, Express middleware architecture', 'Single source of error responses, no duplicated error logic in routes', 'Inconsistent error format across endpoints, try/catch in every route', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/72716474/what-is-the-best-practice-to-handle-errors-in-express', 'admin:1764210300'),

('Express: handle multiple HTTP error codes (404, 401, 403, 500) in one middleware', 'express', 'HIGH', '[{"solution": "Use switch(err.status) in error handler to map custom error objects to HTTP codes", "percentage": 94}, {"solution": "Create RouteError class extending Error with status property for type safety", "percentage": 89}, {"solution": "Return after res.send in error handler, never call next(err) after sending response", "percentage": 97}]'::jsonb, 'HTTP status codes, error classification, Express error handler signature', 'Correct status codes for 404/401/403/500 scenarios, no multiple response sends', 'Calling next(err) in error handler after send(), not returning status codes', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/72749190/how-to-handle-specific-errors-with-expressjs', 'admin:1764210300'),

('Express middleware: throw new Error vs next(new Error) - when to use each', 'express', 'CRITICAL', '[{"solution": "Synchronous code: can use either throw or next(), express wraps throw in try/catch", "percentage": 92}, {"solution": "Async code (callbacks, promises): MUST use next(err), throw won''t be caught", "percentage": 99}, {"solution": "For async functions: use asyncHandler wrapper that returns Promise.resolve().catch(next)", "percentage": 96}]'::jsonb, 'Synchronous vs asynchronous execution, error propagation', 'All errors reach error handler middleware, no UnhandledPromiseRejection', 'Using throw in async context, not understanding promise rejection vs thrown errors', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/74935812/error-handling-in-expressjs-middlewares-next-vs-throw', 'admin:1764210300'),

('Express: order matters - why 404 handler runs before error handler', 'express', 'HIGH', '[{"solution": "Error handlers have 4 parameters (err,req,res,next), regular middlewares have 3 (req,res,next)", "percentage": 99}, {"solution": "Place 404 handler after all routes, error handler after 404 handler", "percentage": 95}, {"solution": "Express examines function.length to distinguish error vs regular middleware", "percentage": 88}]'::jsonb, 'Express middleware signature, route ordering', 'Requests reach correct handler, 404s handled before error handler', 'Confusion about middleware ordering, putting error handler first', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/45787747/express-middleware-error-handler', 'admin:1764210300');
