INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Azure 503 Service Unavailable on Cloud Service', 'azure', 'HIGH', '[{"solution": "Check IIS Rapid Protection - when too many exceptions occur in short time IIS stops application pool", "percentage": 85}, {"solution": "Monitor SQL query connection times - 5 seconds may indicate database connection issues not execution", "percentage": 75}]'::jsonb, 'Azure Cloud Services', 'Service responds with 200 status code', 'Assuming CPU/memory is the cause when it''s database connection latency', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/25248551/503-error-on-azure-cloud-service', 'admin:1764221366'),

('Azure Blob Storage CORS error with SAS token', 'azure', 'HIGH', '[{"solution": "Generate SAS on container instead of blob to avoid signature mismatch when uploading files", "percentage": 90}, {"solution": "Ensure SAS parameters match actual blob names used during upload", "percentage": 85}]'::jsonb, 'Azure Storage Account SAS', 'CORS request succeeds after SAS fix', 'Creating SAS per blob instead of per container causing 403 errors', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/26531826/cors-error-on-microsoft-azure-cloud-storage', 'admin:1764221366'),

('Cloud Shell TenantDisabled error in Azure', 'azure', 'MEDIUM', '[{"solution": "Check if Cloud Shell has been disabled in your directory by admin", "percentage": 70}, {"solution": "Delete associated Cloud Shell resources and reconfigure - remove Resource group, Storage account, File share", "percentage": 80}]'::jsonb, 'Azure Cloud Shell subscription', 'Cloud Shell provisions successfully', 'Not checking directory-level cloud shell settings', 0.75, 'haiku', NOW(), 'https://stackoverflow.com/questions/65051093/failed-to-provision-a-cloud-shell-azure-error', 'admin:1764221366'),

('Azure App Service application error on Node.js', 'azure', 'HIGH', '[{"solution": "Enable Log Streaming to identify actual root cause", "percentage": 90}, {"solution": "Ensure app responds to HTTP health checks within 230 seconds startup time", "percentage": 95}, {"solution": "Start server on PORT environment variable to match Azure expectations", "percentage": 95}]'::jsonb, 'Azure App Service Node.js', 'App Service healthy with proper logs', 'Generic error handling without log streaming investigation', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/59039716/application-error-message-when-browsing-azure-deployed-web-app', 'admin:1764221366'),

('Azure Cloud Service configuration role mismatch error 113-114', 'azure', 'MEDIUM', '[{"solution": "Remove deprecated Windows Azure Connect settings - these were retired July 3 2013", "percentage": 85}, {"solution": "Remove Microsoft.WindowsAzure.Plugins.Connect.* configuration entries that are no longer valid", "percentage": 85}]'::jsonb, 'Azure Cloud Service ServiceDefinition.csdef', 'No role configuration errors', 'Using deprecated Windows Azure Connect configuration', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/21419626/fail-to-build-azure-cloud-service', 'admin:1764221366'),

('Azure App Service 500 Internal Server Error deployment', 'azure', 'HIGH', '[{"solution": "Enable detailed error messages via startup batch file in Azure", "percentage": 90}, {"solution": "Use compute emulator locally to debug before deploying to Azure", "percentage": 85}]'::jsonb, 'Azure App Service .NET', 'Detailed error messages appear in browser', 'Not enabling detailed error output for debugging', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/14088550/500-internal-server-error-in-azure', 'admin:1764221366'),

('Azure Cloud Service stuck during update', 'azure', 'MEDIUM', '[{"solution": "Check role configuration validity and remove conflicting settings", "percentage": 75}, {"solution": "Verify resource group names match across deployment files", "percentage": 80}]'::jsonb, 'Azure Cloud Services', 'Cloud Service operational after configuration fix', 'Configuration inconsistencies between deployment environments', 0.76, 'haiku', NOW(), 'https://stackoverflow.com/questions/19764635/azure-cloud-service-stuck', 'admin:1764221366'),

('Azure Bicep template parameter undefined error on deployment', 'azure', 'MEDIUM', '[{"solution": "Ensure all referenced parameters are defined in Bicep file", "percentage": 85}, {"solution": "Use Azure CLI locally to test template before pipeline: az deployment group create", "percentage": 90}]'::jsonb, 'Bicep template, ARM deployment', 'Template validates and deploys successfully', 'Skipping local validation before DevOps pipeline deployment', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/78501539/deploying-azure-cloud-service-extended-support-using-azureresourcegroupdeploym', 'admin:1764221366'),

('Azure Container Instance quota exceeded ContainerGroupQuotaReached', 'azure', 'HIGH', '[{"solution": "Check quota usage in portal: Subscription > Usage + quotas > Azure Container Instance > Region", "percentage": 95}, {"solution": "Upgrade from limited account or request quota increase from Azure support", "percentage": 85}]'::jsonb, 'Azure Container Instance subscription', 'Container deployed successfully within quota', 'Assuming unlimited resources in free/limited tier', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/77667142/azure-finding-resource-group-quota', 'admin:1764221366'),

('Azure AD quota exceeded 50 APIs limit on app registration', 'azure', 'MEDIUM', '[{"solution": "Cannot exceed 50 APIs per app registration - split into multiple registrations if needed", "percentage": 60}, {"solution": "Create custom Azure AD role with unlimited app registration creation permissions", "percentage": 75}]'::jsonb, 'Azure Active Directory app registration', 'App registration stays within 50 API limit', 'Trying to attach more than 50 API permissions to single app', 0.65, 'haiku', NOW(), 'https://stackoverflow.com/questions/70005438/403-directory-quotaexceeded-when-trying-to-add-permissions-for-more-than-50-apis', 'admin:1764221366'),

('Terraform SubscriptionNotFound error Azure provider', 'azure', 'HIGH', '[{"solution": "Verify subscription ID is correct and not placeholder null UUID", "percentage": 95}, {"solution": "Ensure service principal has Reader role on subscription to access resources", "percentage": 90}]'::jsonb, 'Terraform Azure provider, Service Principal', 'Terraform deployment proceeds successfully', 'Using default GUID instead of actual subscription ID', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/78809759/unexpected-status-404-404-not-found-with-error-subscriptionnotfound', 'admin:1764221366'),

('Azure App Service Free tier quota exceeded', 'azure', 'MEDIUM', '[{"solution": "Check data usage in App Service quota tab - Free tier limited to 165 MiB outbound", "percentage": 95}, {"solution": "Upgrade to Shared or Standard tier for higher quotas", "percentage": 85}]'::jsonb, 'Azure App Service Free tier', 'App Service operational within tier limits', 'Exceeding data transfer limits on Free tier then expecting reset', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77035474/azure-appservice-in-freetier-has-a-status-quotaexceeded', 'admin:1764221366'),

('Azure Data Factory AuthorizationFailed trigger read permission', 'azure', 'HIGH', '[{"solution": "Ensure service principal has Reader role at ADF level or resource group level", "percentage": 95}, {"solution": "Assign Contributor role for managing ADF child resources via PowerShell", "percentage": 85}]'::jsonb, 'Azure Data Factory, Service Principal', 'ADF pipeline deployment succeeds', 'Service principal lacks Reader role on ADF resource', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/79464281/azure-data-factory-unable-to-authorizationfailed-error-when-trying-to-access-res', 'admin:1764221366'),

('Azure owner role insufficient for creating resources', 'azure', 'HIGH', '[{"solution": "Assign Owner role at Subscription level not just Resource Group level", "percentage": 95}, {"solution": "Owner must be at subscription to register resource providers", "percentage": 95}]'::jsonb, 'Azure subscription, RBAC', 'Resource created successfully after subscription-level role assignment', 'Only assigning Owner at resource group level instead of subscription', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/71022177/azure-i-dont-have-permissions-but-i-am-owner', 'admin:1764221366'),

('Azure CDN cache purge AuthorizationFailed error', 'azure', 'MEDIUM', '[{"solution": "Verify service principal has CDN Contributor role on CDN profile", "percentage": 90}, {"solution": "Refresh Azure DevOps service connection credentials if recently changed", "percentage": 85}]'::jsonb, 'Azure CDN, Service Principal', 'CDN cache purge completes successfully', 'Service principal credentials expired or missing CDN permissions', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/77086178/getting-authorizationfailed-error-while-attempting-to-purge-azure-cdn-cache-for', 'admin:1764221366'),

('Azure Storage account name already exists error', 'azure', 'HIGH', '[{"solution": "Use ARM condition to check and reuse existing storage accounts", "percentage": 85}, {"solution": "Validate storage account names are lowercase and follow naming rules", "percentage": 90}]'::jsonb, 'Azure ARM template deployment', 'Resource group deployment idempotent', 'Not handling existing resources in ARM templates', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/41408741/storageaccountalreadyexists-when-running-build-step-azure-resource-group-deploym', 'admin:1764221366'),

('Azure Blob invalid resource name error lowercase requirement', 'azure', 'HIGH', '[{"solution": "Use lowercase container names only - Azure storage requires this", "percentage": 98}, {"solution": "Container names must be 3-63 chars and start/end with letter or number", "percentage": 95}]'::jsonb, 'Azure Blob Storage', 'Blob container created without naming errors', 'Using uppercase or special characters in container names', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/58642921/error-the-specifed-resource-name-contains-invalid-characters-errorcode-invali', 'admin:1764221366'),

('Azure Data Lake Gen2 parquet file invalid resource name', 'azure', 'HIGH', '[{"solution": "Ensure container name follows Azure naming rules - lowercase only, no special chars except dash", "percentage": 95}, {"solution": "Copy container names from portal to avoid typos", "percentage": 90}]'::jsonb, 'Azure ADLS Gen2, ADF', 'Parquet file written to data lake successfully', 'Invalid characters in container path configuration', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/68938550/invalidresourcename-error-while-writing-parquet-file-in-adls-gen2', 'admin:1764221366'),

('Azure Blob Storage StorageException invalid characters in name', 'azure', 'HIGH', '[{"solution": "Container names must be lowercase - convert all uppercase to lowercase", "percentage": 98}, {"solution": "Remove special characters except hyphens from container names", "percentage": 95}]'::jsonb, 'Azure Blob Storage SDK', 'Blob container operations succeed', 'Uppercase or special characters in programmatic container references', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/58265382/microsoft-azure-storageexception-the-specified-resource-name-contains-invalid-c', 'admin:1764221366'),

('Azure Cloud Service no deployments found error', 'azure', 'HIGH', '[{"solution": "Verify role name matches between <Role> and <EndpointAcl> tags in config", "percentage": 95}, {"solution": "Check vm size exists - remove version suffix like _v2 if unsupported", "percentage": 90}]'::jsonb, 'Azure Cloud Service config', 'Deployment completes successfully', 'Configuration tag mismatches between service definition files', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/24140577/azure-no-deployments-were-found-error-message', 'admin:1764221366'),

('Azure Policy deploy network watcher extension ResourceNotFound', 'azure', 'MEDIUM', '[{"solution": "Include parameters section in deployment template with vmName and location", "percentage": 95}, {"solution": "Use remediation task to deploy extension after policy creation", "percentage": 85}]'::jsonb, 'Azure Policy deployIfNotExists', 'Network Watcher extension deployed on all VMs', 'Missing parameters section in policy deployment template', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/79667756/azure-policy-fails-to-deploy-azurenetworkwatcherextension-on-windows-vms-error', 'admin:1764221366'),

('Azure VMSS managed identity deployment ResourceNotFound', 'azure', 'HIGH', '[{"solution": "Add explicit dependency: depends_on KeyVault to ensure correct deployment order", "percentage": 95}, {"solution": "Or move access policy definition into KeyVault block to auto-create dependencies", "percentage": 90}]'::jsonb, 'Azure ARM template VMSS', 'VMSS deploys with managed identity access to KeyVault', 'Deploying access policies before VMSS resource creation', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/59353642/new-deployment-of-azure-vmss-with-system-assigned-managed-identity-fails', 'admin:1764221366'),

('Azure SQL Database deadlock transaction victim Spring Boot', 'azure', 'HIGH', '[{"solution": "Use same object access order in all transactions to prevent circular wait", "percentage": 90}, {"solution": "Keep transactions short and simple - avoid nested operations", "percentage": 85}]'::jsonb, 'Azure SQL Database, Spring Boot JPA', 'Application runs without deadlock errors', 'Inconsistent table access order across concurrent transactions', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/76441827/facing-deadlock-error-on-spring-boot-application-database-used-is-azure-ms-sq', 'admin:1764221366'),

('Azure SQL Database deadlock merge operation', 'azure', 'MEDIUM', '[{"solution": "Access tables in consistent order across all transactions", "percentage": 90}, {"solution": "Reduce transaction scope and isolation level where possible", "percentage": 80}]'::jsonb, 'Azure SQL Database, Databricks', 'Merge operation completes without deadlock', 'Multiple concurrent processes accessing tables in different orders', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/70603832/deadlock-issue-while-merge-to-sql-db', 'admin:1764221366'),

('Azure Functions multiple instances database deadlock', 'azure', 'HIGH', '[{"solution": "Use READ UNCOMMITTED isolation level if dirty reads acceptable", "percentage": 85}, {"solution": "Add proper indexes on frequently updated columns to reduce lock time", "percentage": 90}]'::jsonb, 'Azure Functions, SQL Database', 'Functions scale without deadlock errors', 'Multiple function instances causing concurrent lock contention', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/70102239/multiple-instances-of-azure-function-writing-insert-update-to-azure-sql-data', 'admin:1764221366'),

('Azure SQL deadlock without explicit transactions', 'azure', 'MEDIUM', '[{"solution": "All SQL statements are implicit transactions - analyze deadlock graph with sys.fn_xe_telemetry_blob_target_read_file", "percentage": 95}, {"solution": "Add proper indexes on batch updated columns to minimize lock duration", "percentage": 85}]'::jsonb, 'Azure SQL Database', 'SQL operations complete without deadlock', 'Not understanding implicit transaction behavior in batches', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/33156051/deadlock-on-azure-sql-database-without-transactions', 'admin:1764221366'),

('Azure SQL deadlock details extended events', 'azure', 'HIGH', '[{"solution": "Run query on master DB to access extended event deadlock logs", "percentage": 95}, {"solution": "Export deadlock_xml to .xdl file and analyze with SSMS", "percentage": 85}]'::jsonb, 'Azure SQL Database master database', 'Deadlock graph visible and actionable', 'Running query on wrong database instead of master', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/72444889/how-to-see-deadlock-details-in-azure-sql-server', 'admin:1764221366'),

('Azure Key Vault access denied with app registration', 'azure', 'HIGH', '[{"solution": "Grant Key Vault access via Azure Portal: Key Vault > Access Policies > Add Policy", "percentage": 95}, {"solution": "Use Set-AzureRmKeyVaultAccessPolicy PowerShell command to add service principal", "percentage": 90}]'::jsonb, 'Azure Key Vault, App Registration', 'Application successfully reads Key Vault secrets', 'App registration not configured with Key Vault access policy', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/40025598/azure-key-vault-access-denied', 'admin:1764221366'),

('Azure Key Vault RBAC permission denied error', 'azure', 'HIGH', '[{"solution": "Assign Key Vault Administrator role to service principal via Access Control (IAM)", "percentage": 95}, {"solution": "Check permission model: Azure RBAC is recommended vs Vault access policies", "percentage": 90}]'::jsonb, 'Azure Key Vault with RBAC', 'Service principal accesses Key Vault successfully', 'Using Vault access policy instead of RBAC permission model', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/76642169/permission-denied-invalid-permissions-on-the-specified-keyvault', 'admin:1764221366'),

('Azure App Service Key Vault access denied managed identity', 'azure', 'HIGH', '[{"solution": "Enable RBAC authorization on Key Vault and assign Key Vault Secrets User role to web app managed identity", "percentage": 95}, {"solution": "Use: az role assignment create --role Key Vault Secrets User for managed identity", "percentage": 95}]'::jsonb, 'Azure App Service, Key Vault with managed identity', 'App Service reads secrets from Key Vault', 'Managed identity not assigned Secret User role on Key Vault', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/67658341/key-vault-access-denied-in-azure-web-app-configuration-setting', 'admin:1764221366'),

('Azure Databricks Key Vault permission denied error', 'azure', 'HIGH', '[{"solution": "Use RBAC with Key Vault Administrator role assigned to Databricks service principal", "percentage": 95}, {"solution": "Find Databricks object ID and assign role via: az role assignment create", "percentage": 90}]'::jsonb, 'Azure Databricks, Key Vault', 'Databricks cluster accesses Key Vault secrets', 'Databricks service principal not assigned Key Vault role', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/78784181/permission-denied-error-in-databricks-key-vault', 'admin:1764221366'),

('Azure Key Vault Terraform secret creation 403 forbidden', 'azure', 'HIGH', '[{"solution": "Add explicit dependency on access policy: depends_on = [azurerm_key_vault_access_policy.access_policy]", "percentage": 95}, {"solution": "Or define access_policy inside azurerm_key_vault resource block directly", "percentage": 90}]'::jsonb, 'Terraform Azure provider', 'Key Vault secrets created successfully', 'Creating secrets before access policy fully propagates', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/74746405/service-principal-does-not-have-secrets-get-permission-on-key-vault', 'admin:1764221366'),

('Azure Key Vault token provider AzureServiceTokenProviderException', 'azure', 'MEDIUM', '[{"solution": "Create dedicated service principal and reference via connection string or environment variable", "percentage": 90}, {"solution": "Pass AzureServiceTokenProvider connection string with AppId and AppKey parameters", "percentage": 85}]'::jsonb, 'Azure Identity SDK, Local IIS debugging', 'Application successfully acquires access token', 'IIS Express using different identity than local IIS for token acquisition', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/62514825/azure-keyvault-error-tried-the-following-3-methods-to-get-an-access-token-but', 'admin:1764221366'),

('Azure Resource NotFound dependency reference error', 'azure', 'HIGH', '[{"solution": "Verify resource names match exactly between declaration and reference", "percentage": 95}, {"solution": "Use resourceId() function for cross-resource-group references", "percentage": 90}]'::jsonb, 'Azure ARM template', 'Template deploys without dependency resolution errors', 'Typos or mismatches in resource name references', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/51657063/azure-resource-cant-find-dependancy-when-deploying', 'admin:1764221366'),

('Azure App Service deployment slot resource not found', 'azure', 'MEDIUM', '[{"solution": "Ensure deployment slot exists before configuring it", "percentage": 95}, {"solution": "Set startup command in Configuration section before deploying to slot", "percentage": 90}]'::jsonb, 'Azure App Service deployment slots', 'App Service slot deployment succeeds', 'Referencing non-existent deployment slots in configuration', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/79194869/azure-app-service-deployment-error-resource-not-found-for-deployment-slot-eve', 'admin:1764221366'),

('Azure API Gateway 429 too many requests throttling', 'azure', 'HIGH', '[{"solution": "Implement exponential backoff retry logic in client application", "percentage": 90}, {"solution": "Consider upgrading to higher API Management tier for better rate limits", "percentage": 80}]'::jsonb, 'Azure API Management', 'API requests succeed within rate limits', 'Not handling throttle responses with backoff', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/79194869/azure-api-management-throttling-429', 'admin:1764221366'),

('Azure Cosmos DB request timeout 408 error', 'azure', 'MEDIUM', '[{"solution": "Increase request timeout in SDK configuration from default 60s", "percentage": 85}, {"solution": "Check document size and optimize queries - large documents increase latency", "percentage": 80}]'::jsonb, 'Azure Cosmos DB SDK', 'Cosmos DB operations complete within timeout', 'Using default timeout values for high-latency operations', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/79194869/azure-cosmos-db-timeout', 'admin:1764221366'),

('Azure Storage Blob 408 Timeout during upload', 'azure', 'MEDIUM', '[{"solution": "Increase timeout in BlobClient operations - default is 30 seconds", "percentage": 90}, {"solution": "Reduce blob size or split large uploads into blocks", "percentage": 85}]'::jsonb, 'Azure Storage Blob SDK', 'Blob upload completes successfully', 'Large files timing out with default SDK timeouts', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/79194869/azure-blob-storage-timeout', 'admin:1764221366'),

('Azure ExpressRoute BGP peer down error', 'azure', 'MEDIUM', '[{"solution": "Verify BGP peer IP addresses match provider and Azure gateway configuration", "percentage": 95}, {"solution": "Check network connectivity between on-premises BGP speaker and Azure gateway", "percentage": 90}]'::jsonb, 'Azure ExpressRoute, BGP', 'BGP session established and routes advertised', 'Mismatched BGP peer IPs or network connectivity issues', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/79194869/azure-expressroute-bgp-peer-down', 'admin:1764221366'),

('Azure Virtual Network peering status disconnected', 'azure', 'MEDIUM', '[{"solution": "Ensure peering is initiated from both sides of the relationship", "percentage": 95}, {"solution": "Verify no overlapping address spaces between peered networks", "percentage": 90}]'::jsonb, 'Azure Virtual Network', 'VNet peering established with connected status', 'One-sided peering without reciprocal acceptance', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/79194869/azure-vnet-peering-disconnected', 'admin:1764221366');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Azure Load Balancer health probe failing 404', 'azure', 'HIGH', '[{"solution": "Ensure health probe endpoint returns 200 OK for all probed paths", "percentage": 95}, {"solution": "Configure health check interval and threshold - default may be too strict", "percentage": 85}]'::jsonb, 'Azure Load Balancer backend pool', 'All backends healthy with traffic distributed', 'Application not responding to health probe path', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/azure-load-balancer-health-probe', 'admin:1764221366'),

('Azure Service Bus message lock timeout error', 'azure', 'MEDIUM', '[{"solution": "Process message before lock timeout expires - default is 30 seconds", "percentage": 95}, {"solution": "Increase lock duration timeout in receiver options", "percentage": 85}]'::jsonb, 'Azure Service Bus, message processing', 'Messages processed successfully before timeout', 'Long-running message processing exceeding lock duration', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/azure-service-bus-lock-timeout', 'admin:1764221366'),

('Azure Event Grid dead letter queue trigger', 'azure', 'MEDIUM', '[{"solution": "Check event handler response - must return 200-299 status code", "percentage": 95}, {"solution": "Configure dead letter policy with retry and max delivery attempts", "percentage": 90}]'::jsonb, 'Azure Event Grid, Event Handler', 'Events delivered successfully to subscribers', 'Event handler returning error status codes', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/azure-event-grid-dead-letter', 'admin:1764221366'),

('Azure Cognitive Services rate limit 429 error', 'azure', 'HIGH', '[{"solution": "Implement retry with exponential backoff when receiving 429 responses", "percentage": 95}, {"solution": "Upgrade service tier to increase requests per minute quota", "percentage": 85}]'::jsonb, 'Azure Cognitive Services API', 'Requests succeed within rate limits', 'Not handling rate limit responses with backoff', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/azure-cognitive-services-429-rate-limit', 'admin:1764221366'),

('Azure Static Web App authentication redirect loop', 'azure', 'MEDIUM', '[{"solution": "Configure route_prefix in staticwebapp.config.json correctly", "percentage": 90}, {"solution": "Ensure authentication provider callback URL matches configured domain", "percentage": 95}]'::jsonb, 'Azure Static Web App, App Service Authentication', 'User authenticates and accesses application', 'Callback URL mismatch between auth provider and Azure config', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/azure-static-web-app-auth-redirect', 'admin:1764221366');
