INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Error: Failed to launch the browser process', 'browser-management', 'CRITICAL', '[{"solution": "Install chromium-browser: apt-get install chromium-browser", "percentage": 85}, {"solution": "Add missing system dependencies for Ubuntu", "percentage": 80}, {"solution": "Specify executablePath to existing Chrome installation", "percentage": 90}]'::jsonb, 'Linux/Ubuntu system with required libraries', 'Browser launches without error', 'Missing system dependencies, incorrect executable path', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/59979188/error-failed-to-launch-the-browser-process-puppeteer', 'admin:1764226301'),

('Error: Protocol error (Page.navigate): Target closed', 'protocol-errors', 'CRITICAL', '[{"solution": "Remove --single-process flag from launch args", "percentage": 92}, {"solution": "Increase available memory for browser instance", "percentage": 88}, {"solution": "Avoid using --use-gl=swiftshader argument", "percentage": 85}]'::jsonb, 'Puppeteer browser instance, proper launch args', 'Page navigates successfully without target closed error', 'Using --single-process or --use-gl=swiftshader, insufficient memory', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/51629151/puppeteer-protocol-error-page-navigate-target-closed', 'admin:1764226301'),

('TimeoutError: Navigation timeout of 30000 ms exceeded', 'timeout-errors', 'CRITICAL', '[{"solution": "Increase navigation timeout: page.goto(url, {timeout: 60000})", "percentage": 90}, {"solution": "Use setDefaultNavigationTimeout: page.setDefaultNavigationTimeout(0)", "percentage": 88}, {"solution": "Check if target URL is actually reachable and responsive", "percentage": 85}]'::jsonb, 'Page.goto() with URL', 'Page loads within extended timeout', 'Page load takes longer than timeout, unreachable URL', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/70487251/webscraping-timeouterror-navigation-timeout-of-30000-ms-exceeded', 'admin:1764226301'),

('Error: Node is detached from document', 'dom-errors', 'HIGH', '[{"solution": "Re-query elements after page navigation: grab href and create new page instead", "percentage": 93}, {"solution": "Get element reference before navigation, not after goBack()", "percentage": 91}, {"solution": "Use page.evaluate to extract data before navigating", "percentage": 89}]'::jsonb, 'ElementHandle from page.$$() or page.$()', 'Element operations work without detached errors', 'Using elements after page navigation or goBack()', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/58905844/how-to-click-an-array-of-links-in-puppeteer', 'admin:1764226301'),

('Error: Evaluation failed: ReferenceError', 'evaluation-errors', 'HIGH', '[{"solution": "Check variable is defined before evaluating: const var = document.querySelector()", "percentage": 94}, {"solution": "Check for Istanbul coverage code: use /* istanbul ignore next */", "percentage": 87}, {"solution": "Pass variables as function parameters to page.evaluate()", "percentage": 92}]'::jsonb, 'page.evaluate() with JavaScript function', 'Evaluate executes without reference errors', 'Undefined variable in evaluate function, coverage instrumentation', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/55467333/evaluation-failed-error-in-puppeteer-error-handling', 'admin:1764226301'),

('Error: net::ERR_FAILED - request interception redirect', 'request-errors', 'HIGH', '[{"solution": "Catch net::ERR_FAILED in try/catch block for redirections", "percentage": 90}, {"solution": "Continue redirected requests instead of aborting them", "percentage": 88}, {"solution": "Use redirectChain() to detect and handle properly", "percentage": 85}]'::jsonb, 'page.setRequestInterception(true)', 'Requests complete without ERR_FAILED', 'Aborting main navigation request, blocking redirects', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/67081474/puppeteer-request-interceptor-causes-neterr-failed-errors-with-http-30x-redire', 'admin:1764226301'),

('Error: Session closed. Most likely the page has been closed', 'session-errors', 'CRITICAL', '[{"solution": "Check if page was closed before calling methods on it", "percentage": 93}, {"solution": "Wrap operations in try/catch to handle page closure", "percentage": 91}, {"solution": "Avoid calling methods after browser.close()", "percentage": 95}]'::jsonb, 'Active Puppeteer page instance', 'Page methods execute without session closed error', 'Calling methods on closed page, premature browser close', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/64472147/puppeteer-session-closed-most-likely-the-page-has-been-closed', 'admin:1764226301'),

('Error: Protocol error (Runtime.callFunctionOn): Execution context was destroyed', 'execution-errors', 'HIGH', '[{"solution": "Wait for page.waitForNavigation() before evaluating", "percentage": 92}, {"solution": "Increase waitFor timeout to allow DOM mutations to complete", "percentage": 89}, {"solution": "Disable CSS/images loading to speed up page rendering", "percentage": 87}]'::jsonb, 'page.evaluate() during page navigation', 'Evaluate executes after page fully loads', 'Evaluating during navigation, page reloading, slow DOM mutations', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/49806081/puppeteer-evaluate-results-in-context-destroyed', 'admin:1764226301'),

('Error: Protocol error (Page.printToPDF): Printing failed', 'pdf-errors', 'HIGH', '[{"solution": "Increase timeout for large documents: timeout: 600000", "percentage": 88}, {"solution": "Use --disable-2d-canvas-clip-aa flag in launch args", "percentage": 85}, {"solution": "Reduce HTML complexity and table sizes", "percentage": 84}]'::jsonb, 'page.pdf() with large HTML content', 'PDF generates without printing failure', 'Large tables (1400+ pages), complex CSS, timeout too low', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/73898137/puppeteer-protocol-error-page-printtopdf-printing-failed', 'admin:1764226301'),

('Error: Protocol error (Page.captureScreenshot): Target closed', 'screenshot-errors', 'HIGH', '[{"solution": "Use proper async/await for all operations before screenshot", "percentage": 93}, {"solution": "Wrap screenshot in try/catch and retry on failure", "percentage": 89}, {"solution": "Ensure page completes loading before taking screenshot", "percentage": 91}]'::jsonb, 'page.screenshot() after page navigation', 'Screenshot captures without target closed error', 'Improper async/await, target closed before screenshot', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/54595614/puppeteer-error-protocol-error-page-capturescreenshot-target-closed', 'admin:1764226301'),

('Error: page.type() does not type in input field', 'input-errors', 'MEDIUM', '[{"solution": "Wait for element visibility: page.waitForSelector(selector, {visible: true})", "percentage": 94}, {"solution": "Focus element before typing: page.focus(selector)", "percentage": 91}, {"solution": "Use page.evaluate() to set value directly as workaround", "percentage": 88}]'::jsonb, 'Input element exists in DOM', 'Text appears in input field correctly', 'Element hidden, not focused, or not visible', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/59185073/puppeteer-page-type-doesnt-work-but-element-setattribute-does', 'admin:1764226301'),

('TargetCloseError: Protocol error (Network.getCookies): Target closed', 'target-errors', 'HIGH', '[{"solution": "Use puppeteer-page-proxy with proxyChain instead of other proxy libraries", "percentage": 90}, {"solution": "Pass proxy via launch args: --proxy-server=URL", "percentage": 88}, {"solution": "Ensure all async operations are properly awaited", "percentage": 91}]'::jsonb, 'Puppeteer browser with proxy configuration', 'Network operations complete without target closed', 'Using puppeteer-page-proxy package, unhandled promises', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/76614478/puppeteer-uncatchable-target-closed-error', 'admin:1764226301'),

('Error: Cannot read property ''length'' of undefined', 'javascript-errors', 'MEDIUM', '[{"solution": "Check if element exists before accessing properties: if (element && element.length)", "percentage": 95}, {"solution": "Use optional chaining: element?.length", "percentage": 93}, {"solution": "Initialize array/object before using", "percentage": 94}]'::jsonb, 'Array or object property access', 'Property access returns value without error', 'Accessing property of null/undefined without checking', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/14636536/error-cannot-read-property', 'admin:1764226301'),

('Error: Navigation failed because browser has disconnected', 'connection-errors', 'HIGH', '[{"solution": "Upgrade App Engine instance size (F1 -> F4 for 1GB memory)", "percentage": 90}, {"solution": "Remove --use-gl=swiftshader from launch args", "percentage": 88}, {"solution": "Add --disable-dev-shm-usage but be aware of timeout issues", "percentage": 82}]'::jsonb, 'Puppeteer on Google App Engine or limited memory environment', 'Navigation completes without disconnect error', 'Insufficient memory, multiple instances spawning, problematic args', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/62891633/puppeteer-error-navigation-failed-because-browser-has-disconnected', 'admin:1764226301'),

('TypeError: Cannot read property ''click'' of null', 'element-errors', 'MEDIUM', '[{"solution": "Check selector exists with waitForSelector before clicking", "percentage": 96}, {"solution": "Use page.click(selector) instead of element.click()", "percentage": 92}, {"solution": "Verify selector is correct and element is in viewport", "percentage": 94}]'::jsonb, 'Element selector query result', 'Element found and clicked successfully', 'Element not found by selector, null result from page.$()', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/52346651/puppeteer-throwing-custom-error-message', 'admin:1764226301'),

('Error: Cannot find module ''puppeteer''', 'module-errors', 'MEDIUM', '[{"solution": "Install puppeteer: npm install --save puppeteer", "percentage": 96}, {"solution": "Check NODE_PATH includes node_modules directory", "percentage": 88}, {"solution": "Resolve version conflicts between puppeteer and puppeteer-core", "percentage": 85}]'::jsonb, 'Node.js project with package.json', 'Puppeteer module imports successfully', 'Missing npm install, NODE_PATH not set, version conflicts', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/53764902/cannot-find-module-puppeteer', 'admin:1764226301'),

('Error: page.on(''console'') does not capture all console errors', 'console-errors', 'MEDIUM', '[{"solution": "Register handlers for pageerror and requestfailed events", "percentage": 90}, {"solution": "Use dumpio: true option in puppeteer.launch() to see browser output", "percentage": 88}, {"solution": "Call page.on() handlers BEFORE page.goto()", "percentage": 92}]'::jsonb, 'Puppeteer page instance with event listeners', 'All console messages and errors are captured', 'Handler registered after navigation, incomplete message filtering', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/47539043/how-to-get-all-console-messages-with-puppeteer', 'admin:1764226301'),

('Error: Memory leak - browser consuming excessive memory', 'performance-errors', 'MEDIUM', '[{"solution": "Close pages after use: await page.close()", "percentage": 94}, {"solution": "Use browser pool (puppeteer-cluster) for multiple pages", "percentage": 91}, {"solution": "Regularly restart browser instances to clear memory", "percentage": 87}]'::jsonb, 'Long-running Puppeteer process', 'Memory usage stays constant over time', 'Not closing pages, keeping browser open indefinitely', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/51971760/managing-puppeteer-for-memory-and-performance', 'admin:1764226301'),

('Error: localhost connection refused when accessing headless Chrome', 'connection-errors', 'MEDIUM', '[{"solution": "Use correct host/port for Docker container", "percentage": 90}, {"solution": "Expose port in Dockerfile and docker-compose", "percentage": 92}, {"solution": "Check firewall rules allow Chrome DevTools connection", "percentage": 88}]'::jsonb, 'Puppeteer connecting to remote Chrome', 'Connection established to Chrome instance', 'Docker network misconfiguration, wrong port, firewall blocking', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/51016497/localhost-connection-refused-when-accessing-headless-chrome', 'admin:1764226301'),

('Error: page.waitForNavigation() timeout in loop', 'async-errors', 'HIGH', '[{"solution": "Use Promise.all([page.waitForNavigation(), element.click()])", "percentage": 93}, {"solution": "Re-query elements after each navigation", "percentage": 91}, {"solution": "Increase timeout for slow pages", "percentage": 89}]'::jsonb, 'Page navigation with element interaction', 'Navigation completes and next element loads successfully', 'Element reference stale after navigation, missing Promise.all', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/58905844/how-to-click-an-array-of-links-in-puppeteer', 'admin:1764226301'),

('Error: Uncatchable unhandledRejection from page.on() handler', 'error-handling', 'HIGH', '[{"solution": "Use Promise.race with error promise from handlers", "percentage": 88}, {"solution": "Reject in page.on handler and wrap in new Promise", "percentage": 86}, {"solution": "Add process.on(''unhandledRejection'') handler", "percentage": 85}]'::jsonb, 'Page error handlers (pageerror, error events)', 'All errors caught and handled properly', 'Not handling asynchronous errors from event handlers', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/76146302/do-we-need-to-add-error-and-pageerror-handlers', 'admin:1764226301'),

('Error: Element not found or timing out with page.waitForSelector', 'selector-errors', 'HIGH', '[{"solution": "Verify selector is correct and element exists in DOM", "percentage": 95}, {"solution": "Increase timeout: page.waitForSelector(selector, {timeout: 10000})", "percentage": 92}, {"solution": "Check if element is inside iframe (requires frame.waitForSelector)", "percentage": 88}]'::jsonb, 'CSS selector for element in page', 'Element found and operations succeed', 'Incorrect selector, insufficient timeout, element in iframe', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/52346651/puppeteer-throwing-custom-error-message', 'admin:1764226301'),

('Error: page.requestfailed not capturing 404 and failed requests', 'request-errors', 'MEDIUM', '[{"solution": "Register page.on(''requestfailed'') handler before navigation", "percentage": 92}, {"solution": "Check response.status() separately for 4xx/5xx codes", "percentage": 90}, {"solution": "Log request.failure().errorText for error details", "percentage": 91}]'::jsonb, 'Page with request interception or event handlers', 'Failed requests are logged and handled', 'Handler registered too late, status code confusion', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/50531779/puppeteer-cant-catch-failing-request-errors', 'admin:1764226301'),

('Error: Protocol error (Page.navigate): Invalid referrerPolicy', 'validation-errors', 'LOW', '[{"solution": "Use valid referrerPolicy values: ''no-referrer'', ''same-origin'', etc.", "percentage": 95}, {"solution": "Remove invalid referrerPolicy from page.goto options", "percentage": 94}, {"solution": "Check Puppeteer version supports referrerPolicy parameter", "percentage": 89}]'::jsonb, 'page.goto() with referrerPolicy option', 'Navigation succeeds with valid referrerPolicy', 'Invalid referrerPolicy value, outdated Puppeteer version', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/79671811/puppeteer-protocol-error-page-navigate-invalid-referrerpolicy', 'admin:1764226301'),

('Error: Cannot navigate to invalid URL', 'url-errors', 'LOW', '[{"solution": "Ensure URL is properly formatted with protocol (http/https)", "percentage": 96}, {"solution": "Validate URL before passing to page.goto()", "percentage": 95}, {"solution": "Check URL is not null or undefined", "percentage": 97}]'::jsonb, 'Valid URL string', 'Page navigates successfully to URL', 'Malformed URL, missing protocol, null/undefined URL', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/68376719/puppeteer-protocol-error-page-navigate', 'admin:1764226301'),

('Error: page.evaluate() returns unexpected object type', 'type-errors', 'MEDIUM', '[{"solution": "Ensure evaluate function returns serializable data (no DOM nodes)", "percentage": 94}, {"solution": "Convert DOM elements to strings before returning", "percentage": 93}, {"solution": "Handle Promise return values in evaluate", "percentage": 91}]'::jsonb, 'page.evaluate() function returning data', 'Evaluate returns expected data type', 'Returning non-serializable objects, DOM nodes, unresolved promises', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/68417670/node-js-puppeteer-evaluate-returning-unexpected-objects', 'admin:1764226301'),

('Error: UnhandledPromiseRejectionWarning in async operations', 'async-errors', 'HIGH', '[{"solution": "Properly await all async functions: await page.goto(), await page.close()", "percentage": 95}, {"solution": "Use try/catch blocks around all async operations", "percentage": 93}, {"solution": "Avoid mixing callbacks with async/await", "percentage": 92}]'::jsonb, 'Asynchronous Puppeteer operations', 'All promises resolve without unhandled rejections', 'Missing await, no try/catch, callback mixing', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/49921817/puppeteer-is-unable-to-take-a-screenshot', 'admin:1764226301');
