-- Vue Connection Errors Mining (2025-11-26)

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('connect ECONNREFUSED ::1:3000 after updating Node v17', 'vue', 'HIGH', '[{"solution": "Use IPv4 address instead of localhost. Change proxy target from http://localhost:3000 to http://127.0.0.1:3000 in vite.config.js. Node v17+ prefers IPv6 (::1) which causes ECONNREFUSED when backend only listens on IPv4.", "percentage": 95}, {"solution": "Configure backend service to listen on ::1 (IPv6) instead of 127.0.0.1", "percentage": 85}]'::jsonb, 'Node.js v17+, Vite proxy configuration', 'Proxy requests succeed without ECONNREFUSED errors in vite dev server logs', 'Using localhost instead of explicit IPv4 127.0.0.1, not checking Node version after upgrades', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/74491876/vite-proxy-econnrefused-with-node-v17', 'admin:1764191895'),

('Error: connect ECONNREFUSED 127.0.0.1:8080 in Docker Compose with Cypress', 'vue', 'HIGH', '[{"solution": "In docker-compose.yml, change cypress baseUrl from http://localhost:8080 to http://my-app:8080 (use service name instead of localhost). Containers see localhost as themselves, not the host.", "percentage": 96}, {"solution": "Add network_mode: host to cypress service and ensure Node app binds to 0.0.0.0 instead of localhost", "percentage": 88}, {"solution": "Verify the Node app in my-app service is listening on 0.0.0.0:8080, not just 127.0.0.1:8080", "percentage": 85}]'::jsonb, 'Docker Compose setup, Vue app in container, Cypress tests', 'Cypress connects to app without ECONNREFUSED errors, tests run successfully', 'Using localhost in container context, not understanding Docker virtual networking, forgetting to bind app to 0.0.0.0', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/68709392/error-connect-econnrefused-127-0-0-18080-inside-dockerized-vue-application', 'admin:1764191895'),

('GET http://192.168.1.13:8080/sockjs-node/info net::ERR_CONNECTION_TIMED_OUT', 'vue', 'HIGH', '[{"solution": "Create vue.config.js and set devServer.host to localhost instead of 0.0.0.0. This fixes sockjs connection timeout issues in development.", "percentage": 93}, {"solution": "Update devServer configuration to specify explicit host: ''localhost'' and ensure port 8080 is accessible from your machine", "percentage": 87}]'::jsonb, 'Vue CLI 3+, development server running', 'sockjs successfully connects without timeout errors, HMR works properly', 'Using IP address instead of localhost for devServer configuration, network isolation issues', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/52581143/why-am-i-getting-err-connection-timed-out-in-vue-js', 'admin:1764191895'),

('GET http://localhost:8080/socket.io/?EIO=3&transport=polling 404 with vue-socket-io', 'vue', 'HIGH', '[{"solution": "Create a separate Node/Express server running on port 4113 with socket.io initialized. Vue-socket.io client must connect to http://localhost:4113 where the actual socket.io server is listening, not to the Vue dev server port.", "percentage": 94}, {"solution": "Ensure socket.io server is properly initialized with ''io.on(''''connection'''')'' handler before Vue app tries to connect", "percentage": 89}, {"solution": "Verify socket.io server is running on the port specified in Vue.use(VueSocketio, ''http://localhost:PORT'')", "percentage": 86}]'::jsonb, 'Express server with socket.io, vue-socket-io library, Vue 2', 'Socket connects successfully, connect event fires, real-time communication works', 'Pointing socket.io client to wrong port, confusing Vue dev server port with socket.io server port, forgetting to run socket.io server', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/47187916/vuejs-with-vue-socket-io-integration-connection-refused-error', 'admin:1764191895'),

('POST http://127.0.0.1:8000/admin/auth/user/ net::ERR_CONNECTION_REFUSED in axios', 'vue', 'HIGH', '[{"solution": "Backend API server at http://127.0.0.1:8000 is not running or not accessible. Start the backend server (Django, Flask, etc.) on port 8000 before making axios requests from Vue.", "percentage": 95}, {"solution": "If backend is remote, ensure CORS headers are configured correctly and the backend server is accessible from the frontend origin. Use a proxy in vue.config.js for development.", "percentage": 88}, {"solution": "Check firewall rules or network connectivity to 127.0.0.1:8000. Use curl or Postman to verify backend is responding before debugging axios", "percentage": 85}]'::jsonb, 'Backend API server (Django/Flask/etc), Vue frontend, axios installed', 'axios POST requests complete successfully with 200+ status codes, token received in response', 'Backend server not running, wrong port/hostname, CORS not configured, network blocked', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/67310120/how-do-i-fix-post-http-127-0-0-18000-admin-auth-user-neterr-connection-re', 'admin:1764191895');
