INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Hydration mismatch on Svelte app when head and body are empty', 'svelte', 'HIGH', '[{"solution": "Use svelte:head instead of <head> tags in components. Head and body tags can only be in app.html", "percentage": 98}]'::jsonb, 'SvelteKit app.html structure', 'No hydration mismatch warnings', 'Adding <head> or <body> tags in page/layout components', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/79453268', 'admin:1764255642'),

('SvelteKit error handling not working - error() not catching in components', 'sveltekit', 'HIGH', '[{"solution": "Use error() only in load functions, not in component code. For client-side errors use svelte:boundary or manual try/catch", "percentage": 92}]'::jsonb, 'SvelteKit load functions', 'Errors properly routed to +error.svelte', 'Attempting to throw error() from component code', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/79474193', 'admin:1764255642'),

('Svelte store data not reactive when component changes data', 'svelte', 'HIGH', '[{"solution": "Use $store syntax for automatic subscription instead of manual subscribe(). Bind directly to $data.property", "percentage": 97}]'::jsonb, 'Writable stores', 'Store updates trigger component re-renders', 'Using local variable copy of store value with binding', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/70457545', 'admin:1764255642'),

('page in load functions has been replaced by url and params', 'sveltekit', 'CRITICAL', '[{"solution": "Replace page.params with params directly in load function argument. Use params instead of page", "percentage": 99}]'::jsonb, 'SvelteKit load function', 'Load function executes without error', 'Using page object instead of destructuring params', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/70826183', 'admin:1764255642'),

('Svelte 5 bind value - complex binding behavior with props', 'svelte', 'MEDIUM', '[{"solution": "Use $effect or $derived for prop synchronization. Cannot use bind on non-reactive prop values", "percentage": 85}]'::jsonb, 'Svelte 5 runes', 'Prop changes reflected in child component', 'Attempting bind:data={data.prop} on non-reactive props', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/79233212', 'admin:1764255642'),

('Svelte transition not applying on mount or with timing issues', 'svelte', 'MEDIUM', '[{"solution": "Add delay on in: transition if using both in: and out: transitions. Stagger animations with delay property", "percentage": 88}]'::jsonb, 'Svelte transitions', 'Smooth in and out animations play', 'Missing delay on in: when using both in/out transitions', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/74660584', 'admin:1764255642'),

('Svelte context is undefined when accessed in child components', 'svelte', 'HIGH', '[{"solution": "Move setContext call outside of onMount. Use stores for cross-component state. Context only works for direct children", "percentage": 93}]'::jsonb, 'Svelte context API', 'Child components can access context values', 'Calling setContext inside onMount or using non-string keys', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/63226808', 'admin:1764255642'),

('SvelteKit form action not returning success - form stays null', 'sveltekit', 'HIGH', '[{"solution": "Move form to +page.svelte not component. Ensure ssr is not false in parent. Use named actions with ?/actionName", "percentage": 89}]'::jsonb, 'SvelteKit form actions', '$page.form updates with action response', 'Form component in child instead of page. ssr disabled', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/75857043', 'admin:1764255642'),

('Svelte derived store returns empty array or incorrect value', 'svelte', 'MEDIUM', '[{"solution": "Do not mutate store arrays with splice(). Use slice() instead. Ensure derived dependencies are reactive", "percentage": 91}]'::jsonb, 'Svelte derived stores', 'Derived store returns expected values', 'Mutating array store with splice(). Missing return statement', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/72090176', 'admin:1764255642'),

('Cannot find package @sveltejs/adapter-auto', 'sveltekit', 'CRITICAL', '[{"solution": "Run npm install or pnpm install in terminal before opening in VS Code. Install adapter with npm i @sveltejs/adapter-auto", "percentage": 98}]'::jsonb, 'Node package management', 'No adapter-auto errors. Build completes', 'Not running npm install. Opening project in IDE first', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/72355832', 'admin:1764255642'),

('Svelte TypeScript error for event listener - type incompatibility', 'svelte', 'MEDIUM', '[{"solution": "Change Node type to HTMLElement. Define custom event types in .d.ts file using svelte.JSX", "percentage": 90}]'::jsonb, 'TypeScript, Svelte event handlers', 'Event handler types compile without error', 'Using Node instead of HTMLElement for element type', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/73182246', 'admin:1764255642'),

('Svelte 5 props are undefined after unmount - closure bug', 'svelte', 'MEDIUM', '[{"solution": "Copy prop values to local variables before creating closures. Props are getters revoked on unmount", "percentage": 82}]'::jsonb, 'Svelte 5 runes, closures', 'Closures capture prop values correctly', 'Props accessed in closures without copying to local vars', 0.78, 'haiku', NOW(), 'https://stackoverflow.com/questions/79446266', 'admin:1764255642'),

('TypeError: fetch failed in SvelteKit SSR - unclear stack trace', 'sveltekit', 'MEDIUM', '[{"solution": "Enable sourcemaps in vite.config.ts. Run with --enable-source-maps flag. Use handleFetch hook for error logging", "percentage": 84}]'::jsonb, 'SvelteKit SSR, Node debugging', 'Readable stack traces with source file names', 'Missing sourcemaps. Not enabling source maps in Node', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/75137950', 'admin:1764255642'),

('Reactive statement not triggering when variable changes', 'svelte', 'HIGH', '[{"solution": "Ensure variable is reassigned (x = newValue) not mutated. Use $: to track dependencies correctly", "percentage": 94}]'::jsonb, 'Svelte reactivity', 'Reactive statement runs when dependency changes', 'Mutating object/array instead of reassigning. Wrong syntax', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/63934543', 'admin:1764255642'),

('Slot not rendering in Svelte component', 'svelte', 'MEDIUM', '[{"solution": "Use <svelte:fragment> for fragments. Check slot name matches. Use slot props correctly in loop", "percentage": 86}]'::jsonb, 'Svelte slots', 'Slot content appears in component output', 'Wrong slot names. Wrapping in wrong element', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/76133906', 'admin:1764255642'),

('Cannot prerender pages with form actions in SvelteKit', 'sveltekit', 'HIGH', '[{"solution": "Set export const prerender = false on pages with actions. Use fallback option or remove prerender on action routes", "percentage": 95}]'::jsonb, 'SvelteKit prerender config', 'Prerender succeeds or correctly uses fallback', 'Prerendering pages with form actions without export', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/75044874', 'admin:1764255642'),

('Global client-side error handling in SvelteKit not working', 'sveltekit', 'HIGH', '[{"solution": "Use <svelte:window on:error={handleError}/> in +layout.svelte. Add window.onerror handler", "percentage": 87}]'::jsonb, 'SvelteKit error handling', 'Unhandled errors caught and logged globally', 'Not using svelte:window. Missing error event listener', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/76141595', 'admin:1764255642'),

('Function called outside component initialization', 'svelte', 'CRITICAL', '[{"solution": "Remove context=module from script. Lifecycle hooks only work in component scope. Use onMount for module-level code", "percentage": 96}]'::jsonb, 'Svelte lifecycle', 'Component compiles and initializes correctly', 'Using lifecycle hooks in module context. Wrong script scope', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/78883102', 'admin:1764255642'),

('SvelteKit load function must return a plain object', 'sveltekit', 'CRITICAL', '[{"solution": "Return plain object {props, data}. Do not return functions or complex objects. Spread result correctly", "percentage": 97}]'::jsonb, 'SvelteKit load patterns', 'Load function returns proper data', 'Returning function instead of object. Wrong structure', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/75341763', 'admin:1764255642'),

('SvelteKit routes conflict with dynamic segments', 'sveltekit', 'MEDIUM', '[{"solution": "Use route groups () to organize overlapping routes. Static routes before dynamic [param] routes", "percentage": 85}]'::jsonb, 'SvelteKit routing', 'Routes resolve correctly without conflicts', 'Overlapping static and dynamic routes. Wrong order', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/78301961', 'admin:1764255642'),

('Bind not working with custom elements and customelement=true', 'svelte', 'MEDIUM', '[{"solution": "Two-way binding not supported with customelement. Use event handlers and properties instead", "percentage": 79}]'::jsonb, 'Svelte custom elements', 'Custom element handles data updates', 'Attempting bind: with customelement=true', 0.76, 'haiku', NOW(), 'https://stackoverflow.com/questions/62186324', 'admin:1764255642'),

('Svelte input binding breaks with reference type reactive value', 'svelte', 'MEDIUM', '[{"solution": "Use number type on input for numbers. Reassign reactive value instead of mutating. Check binding updates", "percentage": 88}]'::jsonb, 'Svelte reactivity, forms', 'Input binding updates reactive variable correctly', 'Not reassigning reference types. Wrong input type', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/60825553', 'admin:1764255642'),

('Cannot bind variable declared with let directive', 'svelte', 'MEDIUM', '[{"solution": "Cannot bind directly to let-declared variables in template. Create reactive state instead with $state rune", "percentage": 81}]'::jsonb, 'Svelte runes, state', 'Variable binding works in templates', 'Attempting bind: to let directive. Using wrong declaration', 0.78, 'haiku', NOW(), 'https://stackoverflow.com/questions/56817063', 'admin:1764255642'),

('SvelteKit adapter-node build not working for official examples', 'sveltekit', 'MEDIUM', '[{"solution": "Use createRequire for ESM modules. Configure build output correctly. Check Node version compatibility", "percentage": 83}]'::jsonb, 'SvelteKit adapter-node', 'Build runs and server starts', 'ESM module issues. Wrong import syntax', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/75039452', 'admin:1764255642'),

('Cannot read property length of undefined in Svelte', 'svelte', 'HIGH', '[{"solution": "Check if array exists before accessing. Use optional chaining (arr?.length) or null coalescing", "percentage": 96}]'::jsonb, 'JavaScript basics', 'No TypeError on array access', 'Not checking for null/undefined before property access', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/14636536', 'admin:1764255642'),

('Reactive statement not triggering asynchronously', 'svelte', 'MEDIUM', '[{"solution": "Reactive statements run synchronously. Use $effect for async operations. Await before reactive triggers", "percentage": 84}]'::jsonb, 'Svelte reactivity', 'Async operations run when dependencies change', 'Using $: with async code. Not using $effect', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/75459675', 'admin:1764255642'),

('Svelte transition seems to finish too soon', 'svelte', 'MEDIUM', '[{"solution": "Adjust duration parameter. Use out:transition before in:transition. Check animation timing", "percentage": 82}]'::jsonb, 'Svelte transitions', 'Animations run with expected duration', 'Wrong duration value. Animation order incorrect', 0.79, 'haiku', NOW(), 'https://stackoverflow.com/questions/70916105', 'admin:1764255642'),

('Bind to imported state in Svelte 5 - constant binding error', 'svelte', 'MEDIUM', '[{"solution": "Cannot bind to imported state. Use local reactive copy. Sync with $effect if needed", "percentage": 80}]'::jsonb, 'Svelte 5 runes', 'State synchronizes between components', 'Binding to imported state directly. Wrong pattern', 0.77, 'haiku', NOW(), 'https://stackoverflow.com/questions/79296004', 'admin:1764255642'),

('Form action handler error - cannot prerender with actions', 'sveltekit', 'HIGH', '[{"solution": "Disable prerender on routes with form actions. Use +page.server.ts for actions", "percentage": 94}]'::jsonb, 'SvelteKit forms, prerender', 'Form actions work. Prerender respects config', 'Attempting prerender on action routes', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/76037679', 'admin:1764255642'),

('Hydration failed - initial UI does not match rendered', 'svelte', 'CRITICAL', '[{"solution": "Ensure server and client render identically. Check for Math.random(), date values, timers. Use browser check", "percentage": 95}]'::jsonb, 'SvelteKit SSR', 'No hydration mismatch warnings', 'Non-deterministic values in render. Browser-only code in server render', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/79741264', 'admin:1764255642'),

('SvelteKit named slots - how to use with routes', 'svelte', 'MEDIUM', '[{"solution": "Use slot name= attribute. Wrap content in svelte:fragment or elements with slot= attribute", "percentage": 87}]'::jsonb, 'Svelte slots, SvelteKit layouts', 'Named slots render content correctly', 'Wrong slot naming. Missing slot wrapper elements', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/71668489', 'admin:1764255642');
