INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('SCSS file not compiling anymore Sass stops watch', 'css', 'HIGH', '[{"solution": "Run compass clean to remove .sass-cache files, then restart compass --watch", "percentage": 85}, {"solution": "Verify file is imported in main style.scss - simple missing @import statement", "percentage": 75}]'::jsonb, 'Sass/Compass installed', 'File compiles successfully', 'Forgetting to import file in main stylesheet', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/13766178', 'admin:1764227183'),

('node-sass error indented Sass syntax with .scss file extension', 'css', 'HIGH', '[{"solution": "Change file extension from .scss to .sass if using indented syntax", "percentage": 95}, {"solution": "Convert indented syntax to SCSS syntax with braces and semicolons", "percentage": 90}]'::jsonb, 'node-sass npm package', 'File compiles without errors', 'Mixing file extension with wrong syntax type', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/48464799', 'admin:1764227183'),

('File to import not found or unreadable container.scss', 'css', 'HIGH', '[{"solution": "Check if file exists and verify path is correct", "percentage": 90}, {"solution": "Remember @import does not need .scss extension - Sass resolves it automatically", "percentage": 85}]'::jsonb, 'SCSS @import statements', 'Import statement resolves correctly', 'Typo in filename or incorrect path reference', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/46625610', 'admin:1764227183'),

('Undefined variable Sass SCSS error using @use instead of @import', 'css', 'HIGH', '[{"solution": "Variables loaded with @use are only visible in that file - use namespace.variableName syntax", "percentage": 88}, {"solution": "Use @forward rule to make variables available globally", "percentage": 82}, {"solution": "Switch to @import instead (deprecated but works)", "percentage": 78}]'::jsonb, '@use or @import declarations', 'Variable accessed with namespace prefix', 'Forgetting namespace prefix with @use', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/64980432', 'admin:1764227183'),

('Properties are only allowed within rules directives mixin includes', 'css', 'MEDIUM', '[{"solution": "Verify mixin is called inside a CSS selector or @content block", "percentage": 92}, {"solution": "Add underscore to filename like _mixins.scss to ensure proper compilation order", "percentage": 80}]'::jsonb, 'Sass mixin definitions', 'Mixin includes properly nested', 'Calling @include outside CSS selector context', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/48558206', 'admin:1764227183'),

('Undefined mixin error when mixins in separate folder', 'css', 'MEDIUM', '[{"solution": "Import the mixin file first before using @include - use @import ./path/_mixins", "percentage": 89}, {"solution": "Ensure underscore prefix on partial file names", "percentage": 85}]'::jsonb, 'Mixin SCSS files', 'Mixin @include statement works', 'Missing @import statement for mixin file', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/29591196', 'admin:1764227183'),

('node-sass usage is deprecated will be removed future version', 'css', 'HIGH', '[{"solution": "Uninstall node-sass and install sass package instead", "percentage": 98}, {"solution": "Run npm uninstall node-sass && npm install -D sass", "percentage": 97}]'::jsonb, 'npm or yarn installed', 'Sass works with new sass package', 'Using outdated node-sass instead of sass', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/65594119', 'admin:1764227183'),

('The legacy JS API is deprecated dart-sass 2.0.0', 'css', 'MEDIUM', '[{"solution": "Migrate to new Sass API - update function signatures and imports", "percentage": 85}, {"solution": "Update build tool configuration to use new dart-sass API", "percentage": 82}]'::jsonb, 'dart-sass 1.x installed', 'Code compatible with dart-sass 2.0+', 'Using deprecated legacy JS API methods', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/78997907', 'admin:1764227183'),

('Sass error unmached bracket unmatched closing brace', 'css', 'MEDIUM', '[{"solution": "Check nesting and add missing closing brace - nested selectors need closing for each level", "percentage": 93}]'::jsonb, 'SCSS file with nesting', 'Matching braces for all nested rules', 'Missing closing brace in nested selector', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/25511857', 'admin:1764227183'),

('Sass argument $color of darken must be a color', 'css', 'MEDIUM', '[{"solution": "Pass actual color value not CSS variable - var(--color) is runtime, darken needs compile-time color", "percentage": 90}, {"solution": "Use actual color hex or rgb value instead of var()", "percentage": 88}]'::jsonb, 'SCSS with color functions', 'darken/lighten function accepts color', 'Using CSS variables with Sass color functions', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/58490138', 'admin:1764227183'),

('@extend must be used with %placeholder selector warning', 'css', 'MEDIUM', '[{"solution": "Convert to placeholder selectors using % prefix for reusable patterns", "percentage": 85}, {"solution": "Define pattern as %placeholder-name then @extend %placeholder-name", "percentage": 82}]'::jsonb, 'Sass linter configured', 'Using %placeholder selectors with @extend', 'Extending normal CSS selectors instead of placeholders', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/54084022', 'admin:1764227183'),

('Illegal nesting only properties may be nested beneath properties', 'css', 'MEDIUM', '[{"solution": "Verify SCSS nesting structure - only properties go in properties", "percentage": 88}, {"solution": "Use media queries properly with media features not property nesting", "percentage": 85}]'::jsonb, 'SCSS nesting structure', 'Proper SCSS nesting without errors', 'Nesting rules in property declarations', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/30696069', 'admin:1764227183'),

('Sass calc interpolation - invalid CSS syntax', 'css', 'MEDIUM', '[{"solution": "Do not interpolate variable in calc - use direct variable: calc(100% - #{$var})", "percentage": 89}, {"solution": "Use strip-unit function to remove units before math operations", "percentage": 86}]'::jsonb, 'SCSS with calc() function', 'calc() produces valid CSS', 'Interpolating entire variable instead of just using it', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/42248345', 'admin:1764227183'),

('Sass for-each loop color value not a color error', 'css', 'MEDIUM', '[{"solution": "Use rgb() function for color values instead of comma-separated numbers", "percentage": 90}, {"solution": "Store complete rgb() or hex colors in variables, not component values", "percentage": 87}]'::jsonb, 'SCSS @each loop with colors', 'Loop iterates without color errors', 'Splitting RGB values instead of complete color format', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/69709482', 'admin:1764227183'),

('Sass map is not a map for map-get error - using join instead', 'css', 'MEDIUM', '[{"solution": "Use map-merge() function instead of join() to merge maps", "percentage": 92}, {"solution": "join() converts map to list causing type error - use map-merge()", "percentage": 90}]'::jsonb, 'SCSS map operations', 'map-get() retrieves correct values', 'Using list join() function instead of map-merge()', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/27413854', 'admin:1764227183'),

('Sass map.get() does not work but map-get() does', 'css', 'MEDIUM', '[{"solution": "Use map-get() function not map.get() - Sass uses hyphenated names", "percentage": 95}]'::jsonb, 'SCSS with map functions', 'map-get() function works correctly', 'Using dot notation instead of hyphenated function name', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/64210390', 'admin:1764227183'),

('Sass placeholder selector scope undefined extend error', 'css', 'LOW', '[{"solution": "Placeholder selectors have global scope - define at top level, not nested", "percentage": 88}, {"solution": "Use separate partial file for placeholders to avoid nesting issues", "percentage": 84}]'::jsonb, 'SCSS with @extend and %', 'Placeholder extends properly across files', 'Defining placeholder selectors inside nested scopes', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/62203440', 'admin:1764227183'),

('Sass interpolation invalid CSS after - expected class name', 'css', 'MEDIUM', '[{"solution": "Check interpolation syntax - use #{$variable} not #$variable", "percentage": 92}, {"solution": "Verify interpolated value produces valid CSS identifier", "percentage": 88}]'::jsonb, 'SCSS with string interpolation', 'Interpolation produces valid CSS', 'Wrong interpolation syntax or invalid output', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/37920372', 'admin:1764227183'),

('Undefined variable in nested @use scope with Sass modules', 'css', 'MEDIUM', '[{"solution": "Import variables file with @use in each file that needs them", "percentage": 89}, {"solution": "Use @forward rule to export variables from central location", "percentage": 85}]'::jsonb, '@use rule with variables', 'Variables accessible with namespace', 'Not importing @use in nested files', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/62127255', 'admin:1764227183'),

('Sass @for loop index variable syntax error range', 'css', 'LOW', '[{"solution": "Use @for $i from 1 through 10 syntax with through keyword", "percentage": 91}, {"solution": "Use to instead of through if excluding end value", "percentage": 88}]'::jsonb, '@for loop in SCSS', 'Loop iterates correct number of times', 'Wrong keyword or incorrect range syntax', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/41631643', 'admin:1764227183'),

('Sass function does not return value returns undefined', 'css', 'MEDIUM', '[{"solution": "Add @return statement in @function with explicit value", "percentage": 94}, {"solution": "Ensure all code paths in function have return statement", "percentage": 91}]'::jsonb, 'SCSS @function definition', 'Function returns expected value', 'Missing @return statement in function', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/33477415', 'admin:1764227183'),

('Sass function returns string containing function name undefined', 'css', 'LOW', '[{"solution": "Verify function is declared or properly imported before use", "percentage": 93}, {"solution": "Check import path if function in separate file", "percentage": 89}]'::jsonb, 'SCSS with custom functions', 'Function executes and returns value', 'Function not declared or import missing', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/27588136', 'admin:1764227183'),

('Sass deprecation warning @import rules deprecated will phase out', 'css', 'MEDIUM', '[{"solution": "Migrate from @import to @use and @forward rules", "percentage": 85}, {"solution": "Update Sass version to latest and use new module system", "percentage": 82}]'::jsonb, 'Sass 1.0+ installed', 'Code uses @use instead of @import', 'Continuing to use deprecated @import', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/79229008', 'admin:1764227183'),

('Sass compilation error invalid CSS after expected selector', 'css', 'MEDIUM', '[{"solution": "Check for syntax errors - missing selector or misplaced properties", "percentage": 89}, {"solution": "Verify all selectors have valid CSS syntax", "percentage": 86}]'::jsonb, 'SCSS file with CSS syntax', 'File compiles to valid CSS', 'Invalid selector syntax or misplaced declarations', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/18517228', 'admin:1764227183'),

('Sass nested mixin include scope variable accessibility issue', 'css', 'LOW', '[{"solution": "Pass variables as mixin arguments instead of relying on scope", "percentage": 88}, {"solution": "Use !global flag to make variable accessible (deprecated), better to pass as parameter", "percentage": 82}]'::jsonb, 'SCSS with mixins and nesting', 'Nested mixin accesses variables correctly', 'Assuming nested scope shares parent variables', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/44249019', 'admin:1764227183');