INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('MongoNetworkError: failed to connect to server on first connect', 'koa', 'HIGH', '[{"solution": "Use centralized error handler middleware at the top of your Koa app to catch database connection errors", "percentage": 88}, {"solution": "Add error event listener with app.on(''error'', (err, ctx) => {...}) for logging", "percentage": 85}]'::jsonb, 'Koa.js + Mongoose', 'Connection errors logged and handled gracefully', 'Not using try/catch in middleware, forgetting error event listener', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/51420298/koa-js-centralized-error-handling', 'admin:1764210487'),

('ctx.throw() returns text/plain instead of application/json', 'koa', 'MEDIUM', '[{"solution": "Set ctx.type = ''json'' before throwing error", "percentage": 92}, {"solution": "Use custom error handler middleware that sets ctx.type = ''json'' and ctx.status = err.statusCode", "percentage": 90}]'::jsonb, 'Koa error handling middleware', 'Error response has Content-Type: application/json header', 'Not setting ctx.type before throwing', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/52623644/how-to-make-koa-ctx-throw-use-application-json-rather-than-text-plain', 'admin:1764210487'),

('Error handler middleware doesn''t catch thrown errors in routes', 'koa', 'MEDIUM', '[{"solution": "Ensure all route handlers are async functions that properly await next()", "percentage": 89}, {"solution": "Use async (ctx, next) => {...} syntax instead of generator functions for Koa 2", "percentage": 87}]'::jsonb, 'Koa 2 + TypeScript async/await', 'Errors properly caught by try/catch in middleware', 'Using generator functions in Koa 2, missing async keyword on route handlers', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/39068002/typescript-and-koa-2-async-await-issue-with-global-error-handler', 'admin:1764210487'),

('UnhandledPromiseRejectionWarning in Koa application', 'koa', 'HIGH', '[{"solution": "Add process.on(''unhandledRejection'', (reason) => {...}) handler at app startup", "percentage": 86}, {"solution": "Wrap unhandled rejections in custom error class and throw to error handler middleware", "percentage": 84}]'::jsonb, 'Koa.js + Promise handling', 'Process no longer shows unhandled rejection warnings', 'Relying only on middleware error handler, not handling process-level errors', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/51420298/koa-js-centralized-error-handling', 'admin:1764210487'),

('How to test custom Koa error middleware with unit tests', 'koa', 'LOW', '[{"solution": "Mock context object and use co.wrap() to test generator-based middleware", "percentage": 80}, {"solution": "For Koa 2, mock ctx and next() to simulate error throwing", "percentage": 82}]'::jsonb, 'Koa middleware testing, chai/mocha', 'Unit tests pass and error handling logic is covered', 'Not mocking context properly, trying to test generator functions directly', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/40870237/how-do-i-test-custom-koa-middleware-for-error-handling', 'admin:1764210487'),

('Error object is array instead of Error class instance', 'koa', 'MEDIUM', '[{"solution": "Always throw Error objects or custom Error subclass: throw new Error(message)", "percentage": 93}, {"solution": "Check that database/validation libraries throw proper Error instances, not arrays or plain objects", "percentage": 88}]'::jsonb, 'JavaScript error handling, Koa', 'err.message exists and is a string, err.status is reliable', 'Throwing arrays or objects from validation libraries instead of Error instances', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/47595754/getting-error-message-with-koa-js-axios', 'admin:1764210487'),

('Cannot read property ''message'' of undefined in error handler', 'koa', 'HIGH', '[{"solution": "Create custom error class that extends Error with statusCode property", "percentage": 89}, {"solution": "Always check error object properties exist: err.status || err.statusCode || 500", "percentage": 87}]'::jsonb, 'Koa error handling, custom errors', 'Error message is always defined, status code defaults to 500', 'Passing undefined to ctx.throw(), not validating error object properties', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/47595754/getting-error-message-with-koa-js-axios', 'admin:1764210487'),

('Custom error page not displaying, shows default ''Internal Server Error''', 'koa', 'MEDIUM', '[{"solution": "Use async/await syntax: app.use(async (ctx, next) => { await next(); ... })", "percentage": 90}, {"solution": "Set ctx.body after catching error: ctx.body = customErrorTemplate.render({error: err})", "percentage": 88}]'::jsonb, 'Koa 2 error handler, template rendering', 'Custom error page renders with custom message', 'Using return instead of await in Koa 2, middleware not being async function', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/33875660/display-custom-page-when-error-happens-in-koa', 'admin:1764210487'),

('Koa process crashes on unexpected error despite error handler', 'koa', 'LOW', '[{"solution": "Ensure error handler middleware is first in app.use() chain before routes", "percentage": 91}, {"solution": "Emit error to app with ctx.app.emit(''error'', err, ctx) for logging without crashing", "percentage": 85}]'::jsonb, 'Koa 2 error handling, process management', 'Unexpected errors are caught and logged without process exit', 'Error handler middleware not positioned first, process.exit() being called', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/39915316/how-to-deal-with-unexpected-errors-with-koa', 'admin:1764210487'),

('ctx.status not updating after error thrown in route', 'koa', 'MEDIUM', '[{"solution": "In error handler, explicitly set ctx.status before ctx.body: ctx.status = err.status || 500", "percentage": 89}, {"solution": "Ensure error handler is async function that awaits next(): await next()", "percentage": 87}]'::jsonb, 'Koa middleware, error handling', 'Error responses have correct HTTP status code', 'Setting ctx.body without setting ctx.status first, using synchronous middleware in Koa 2', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/49228366/koa2-error-handling', 'admin:1764210487');
