-- Prisma Errors Mining - 40 entries
INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('PrismaClientValidationError: Invalid prisma.tableName.create() invocation - Argument user: Got invalid value', 'orm', 'HIGH', '[{"solution": "Use proper type for relation field - use connectOrCreate instead of nested create with string value", "percentage": 88}, {"solution": "Run npx prisma generate after schema changes", "percentage": 85}]'::jsonb, 'Prisma client generated', 'Record created successfully without type errors', 'Passing wrong type to relation field, not regenerating client', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/75078929/how-to-handle-prisma-errors-and-send-a-valid-message-to-client', 'admin:1764227325'),

('Error P1001: Can''t reach database server at localhost:5432 - Connection refused in Docker', 'orm', 'CRITICAL', '[{"solution": "Use container service name instead of localhost - change to postgres:5432", "percentage": 92}, {"solution": "Add connect_timeout=300 to DATABASE_URL", "percentage": 78}]'::jsonb, 'Docker Compose setup with Prisma', 'Database connection successful', 'Using localhost inside container, wrong host resolution', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/71663204/docker-prisma-error-p1001-cant-reach-database-server-at-postgres5432', 'admin:1764227325'),

('Error P1001: Can''t reach database server at db.xocheossqzkirwnhzxxm.supabase.co:5432 - Supabase IPv6', 'orm', 'CRITICAL', '[{"solution": "Use IPv4 network connection option in Supabase, or use pooler endpoint", "percentage": 85}, {"solution": "Check password contains no special characters", "percentage": 72}]'::jsonb, 'Supabase PostgreSQL + Prisma', 'Migration runs successfully', 'IPv6 only connection attempt, missing credentials', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/73866587/prisma-error-p1001-cant-reach-database-server-at-db-xocheossqzkirwnhzxxm-sup', 'admin:1764227325'),

('PrismaClientValidationError: Invalid prisma.user.create() invocation Unknown arg profile in data.profile', 'orm', 'HIGH', '[{"solution": "Run npx prisma generate to refresh client after schema changes", "percentage": 95}, {"solution": "Restart Node server after schema updates", "percentage": 88}]'::jsonb, 'Prisma schema updated with new relations', 'prisma.user.create() accepts profile field', 'Not regenerating client, server not restarted after schema change', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/68246739/prismaclientvalidationerror-invalid-prisma-user-create-invocation', 'admin:1764227325'),

('Error P1001: Can''t reach database server at aws-0-eu-central-2.pooler.supabase.com - Pooler connection failure', 'orm', 'CRITICAL', '[{"solution": "Update Prisma to latest version", "percentage": 80}, {"solution": "Use directUrl for migrations and DATABASE_URL for runtime", "percentage": 82}]'::jsonb, 'Supabase PostgreSQL with Prisma 4.x+', 'prisma migrate dev completes successfully', 'Outdated Prisma version, missing directUrl configuration', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/79677685/prisma-cant-connect-to-supabase-postgresql-p1001-error', 'admin:1764227325'),

('PrismaClientKnownRequestError: Invalid prisma.favorite.create() invocation P2003 - Foreign key constraint failed', 'orm', 'HIGH', '[{"solution": "Verify userId exists in User table before creating relation", "percentage": 90}, {"solution": "Log userId to confirm it matches existing records in Clerk", "percentage": 85}]'::jsonb, 'User model with Clerk auth', 'Favorite created and associated with valid User', 'Using deleted or invalid userId, token mismatch with Clerk', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/77942137/why-am-i-getting-a-p2003-foreign-key-constraint-prisma-error', 'admin:1764227325'),

('Error P2025: Record to delete does not exist - prisma.post.delete() invocation', 'orm', 'HIGH', '[{"solution": "Add export const dynamic = ''force-dynamic'' in Next.js route to prevent caching", "percentage": 88}, {"solution": "Verify record exists before deletion", "percentage": 85}]'::jsonb, 'Next.js with Prisma in production', 'Delete operation succeeds on first attempt', 'ISR caching in Next.js, stale data from static generation', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77193562/error-prismaclientknownrequesterror-invalid-prisma-post-delete-invocation', 'admin:1764227325'),

('PrismaClientValidationError: Invalid prisma.user.create() invocation - Unique constraint failed tagId_unique', 'orm', 'HIGH', '[{"solution": "Check if record with same unique field already exists in database", "percentage": 92}, {"solution": "Use upsert instead of create for idempotent operations", "percentage": 88}]'::jsonb, 'MySQL with unique constraints', 'Data inserted or upserted without duplicate errors', 'Duplicate value in unique field, not handling existing records', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/70328744/issue-with-prisma-and-mysql', 'admin:1764227325'),

('PrismaClientKnownRequestError: Unique constraint failed on the constraint - connectOrCreate race condition', 'orm', 'HIGH', '[{"solution": "Catch P2002 error and retry failed queries", "percentage": 80}, {"solution": "Create all genres first with skipDuplicates, then connect movies", "percentage": 85}]'::jsonb, 'Concurrent transactions with connectOrCreate', 'Records created and relations established without conflicts', 'Race condition in parallel connectOrCreate, missing retry logic', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/68579354/prisma-multiple-create-queries-with-nested-connectorcreate-throws-unique-constra', 'admin:1764227325'),

('PrismaClientKnownRequestError: Transaction failed due to a write conflict or a deadlock', 'orm', 'MEDIUM', '[{"solution": "Detach children first with updateMany before deleteMany", "percentage": 90}, {"solution": "Simplify delete operations to avoid circular dependencies", "percentage": 85}]'::jsonb, 'Self-referential relations in Navigation model', 'All records deleted without deadlock', 'Trying to delete parent/child with foreign key constraints, no retry', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/78216269/prisma-error-transaction-failed-due-to-a-write-conflict-or-a-deadlock-please-r', 'admin:1764227325'),

('PrismaClientUnknownRequestError: prepared statement s0 already exists - Database pooling issue', 'orm', 'CRITICAL', '[{"solution": "Set directUrl in Prisma schema for migrations to bypass pooler", "percentage": 88}, {"solution": "Restart Supabase project from settings page", "percentage": 75}]'::jsonb, 'Supabase with connection pooling', 'Queries execute without prepared statement conflicts', 'Using pooler for migrations, IPv6 connection issues, stale connections', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/71026259/prisma-postres-error-prepared-statement-s0-already-exists', 'admin:1764227325'),

('PrismaClientValidationError: Invalid prisma.user.findMany() invocation Unknown field sheets for include statement', 'orm', 'HIGH', '[{"solution": "Run npx prisma migrate dev after schema changes", "percentage": 92}, {"solution": "Restart Node server to reload generated client", "percentage": 88}]'::jsonb, 'Prisma 2+ with new relations added to schema', 'findMany with include returns all related fields', 'Not running migrate or generate, server not restarted', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/64731810/unable-to-solve-prisma-1-1-and-1-n-relation-error', 'admin:1764227325'),

('PrismaClientValidationError: Invalid prisma.products.findMany() - name property does not exist in manufacturersArgs', 'orm', 'MEDIUM', '[{"solution": "Use select with where clause instead of include for nested filtering", "percentage": 88}, {"solution": "Use hasSome or hasEvery for scalar list filters instead of in", "percentage": 82}]'::jsonb, 'Prisma with nested relations and filters', 'Query filters nested relations correctly with proper syntax', 'Using include instead of select for nested where, wrong filter operators', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/73102171/prisma-typescript-where-clause-inside-include', 'admin:1764227325'),

('TypeError: Cannot read property ''length'' of undefined - Array access without null check', 'orm', 'HIGH', '[{"solution": "Check if array exists before accessing: if (arr && arr.length)", "percentage": 95}, {"solution": "Use optional chaining: arr?.length", "percentage": 90}]'::jsonb, 'JavaScript with Prisma queries', 'No TypeError thrown, array operations succeed', 'Not handling null/undefined arrays, missing safety checks', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/75078929/how-to-handle-prisma-errors-and-send-a-valid-message-to-client', 'admin:1764227325'),

('PrismaClientValidationError: Invalid prisma.product.create() invocation - custom model undefined', 'orm', 'MEDIUM', '[{"solution": "Run npx prisma generate to regenerate client", "percentage": 92}, {"solution": "Specify custom output path in generator if using custom client", "percentage": 80}]'::jsonb, 'Prisma with custom client output paths', 'All models available and properly typed', 'Not regenerating client after schema changes, wrong import path', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/67774292/how-to-fix-prisma-client-getting-undefined-for-custom-model', 'admin:1764227325'),

('Error P2002: Unique constraint failed on the constraint User_Account_userId_key', 'orm', 'HIGH', '[{"solution": "Delete conflicting records from database before seeding", "percentage": 85}, {"solution": "Use upsert in seed with proper where clause", "percentage": 88}]'::jsonb, 'Database seeding with Prisma', 'Seed completes without unique constraint violations', 'Existing data conflicts, not using proper upsert, race conditions', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/69886884/unique-constraint-failed-on-the-constraint-user-account-userid-key-in-prisma', 'admin:1764227325'),

('PrismaClientValidationError: Invalid prisma.user.create() invocation with Clerk events', 'orm', 'MEDIUM', '[{"solution": "Validate payload shape before creating record", "percentage": 88}, {"solution": "Add logging to check Clerk webhook data structure", "percentage": 82}]'::jsonb, 'Clerk webhooks + Prisma + Next.js', 'User records created successfully from webhook events', 'Missing or invalid fields in webhook payload, wrong field names', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/79767875/prisma-user-create-and-user-delete-throwing-errors-with-clerk-inngest-events', 'admin:1764227325'),

('Error: groupBy does not support include relations - Prisma limitation', 'orm', 'MEDIUM', '[{"solution": "Make two separate queries: groupBy then findMany", "percentage": 85}, {"solution": "Use raw SQL with queryRaw for complex aggregations", "percentage": 80}]'::jsonb, 'Prisma aggregation with relations', 'Aggregation query returns all required fields', 'Trying to use include/select with groupBy, expecting unsupported feature', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/70431807/prisma-how-to-select-or-include-on-a-group-by', 'admin:1764227325'),

('Error in Prisma Client request: Invalid `f=e.match() - Prisma Studio syntax error', 'orm', 'LOW', '[{"solution": "Check Prisma Studio version and update if necessary", "percentage": 75}, {"solution": "Clear browser cache and reload Prisma Studio", "percentage": 70}]'::jsonb, 'Prisma Studio with complex queries', 'Prisma Studio query executes without errors', 'Browser cache issues, outdated Prisma Studio version', 0.72, 'haiku', NOW(), 'https://stackoverflow.com/questions/78452499/why-does-yarn-prisma-studio-error-with-error-in-prisma-client-request', 'admin:1764227325'),

('PrismaClientKnownRequestError: Invalid prisma.post.delete() invocation - Record to update not found', 'orm', 'MEDIUM', '[{"solution": "Check record exists with findUnique before updating", "percentage": 88}, {"solution": "Handle P2025 error explicitly in try-catch", "percentage": 85}]'::jsonb, 'Next.js API routes with Prisma', 'Update operation succeeds on valid records', 'Assuming record exists without verification, stale data from cache', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/77223996/record-to-update-not-found-nextjs-prisma', 'admin:1764227325'),

('Error code P2032: The provided value for the column is too long', 'orm', 'MEDIUM', '[{"solution": "Reduce string length to fit column definition", "percentage": 90}, {"solution": "Change column type from String to Text in schema", "percentage": 85}]'::jsonb, 'Prisma with strict column length constraints', 'Data inserted successfully within column limits', 'String exceeds VARCHAR length, wrong data type for field', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/75600901/error-code-p2032-using-prisma-orm-on-sql-db', 'admin:1764227325'),

('PrismaClientValidationError: Invalid prisma.fight.delete() invocation - Foreign key constraint violation', 'orm', 'HIGH', '[{"solution": "Delete related records first before deleting parent", "percentage": 92}, {"solution": "Use onDelete: Cascade in relation to auto-delete children", "percentage": 88}]'::jsonb, 'Prisma with foreign key relations', 'Parent record deleted after children handled', 'Deleting parent before children, missing CASCADE policy', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/70527741/how-to-delete-a-record-and-any-relationship-records-in-an-explicit-many-to-many', 'admin:1764227325'),

('PrismaClientValidationError: Invalid prisma.user.updateMany() invocation - Missing required field', 'orm', 'HIGH', '[{"solution": "Include all required fields in update data", "percentage": 92}, {"solution": "Use partial updates with nullable fields", "percentage": 88}]'::jsonb, 'Prisma update operations', 'Update succeeds with all required fields', 'Omitting mandatory fields, incorrect field types', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/78329193/how-to-deal-with-prismaclientvalidationerror', 'admin:1764227325'),

('Error: PrismaClientKnownRequestError - Invalid `this.prisma.user.updateMany()` invocation', 'orm', 'MEDIUM', '[{"solution": "Verify where clause targets existing records", "percentage": 88}, {"solution": "Check data transformation before update", "percentage": 85}]'::jsonb, 'NestJS with Prisma auth service', 'Update operation completes successfully', 'Invalid where clause, wrong data format for update', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/74726049/typescript-mysql-logging-prisma-errors', 'admin:1764227325'),

('PrismaClientValidationError: Unexpected field in data - Typo in field name', 'orm', 'HIGH', '[{"solution": "Check field name spelling in schema", "percentage": 95}, {"solution": "Use Prisma Studio to verify correct field names", "percentage": 90}]'::jsonb, 'Prisma with typed operations', 'Query executes with correct field names', 'Field name typo, wrong casing, missing field definitions', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/75078929/how-to-handle-prisma-errors-and-send-a-valid-message-to-client', 'admin:1764227325'),

('Error P1008: Operations timed out after 5000ms - Query execution timeout', 'orm', 'MEDIUM', '[{"solution": "Add timeout parameter to Prisma query: timeout: 10000", "percentage": 80}, {"solution": "Optimize database indexes and query complexity", "percentage": 85}]'::jsonb, 'Large database queries with Prisma', 'Query completes within timeout window', 'Unindexed queries, missing timeout configuration, slow database', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/71663204/docker-prisma-error-p1001-cant-reach-database-server-at-postgres5432', 'admin:1764227325'),

('PrismaClientValidationError: Invalid relation field - Field not found error', 'orm', 'MEDIUM', '[{"solution": "Verify relation exists in schema and matches field name", "percentage": 90}, {"solution": "Run npx prisma generate after schema changes", "percentage": 88}]'::jsonb, 'Prisma schema with relations', 'Relation queries execute without field errors', 'Schema mismatch, relation not defined, client not regenerated', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/76853049/prisma-errors-fieldnotfounderror-in-a-field-that-does-exist-in-a-table', 'admin:1764227325'),

('Error: migrations in the database are more than locally - Migration conflict', 'orm', 'HIGH', '[{"solution": "Run npx prisma migrate resolve --rolled-back <migration>", "percentage": 85}, {"solution": "Resolve schema conflicts and run prisma migrate dev", "percentage": 88}]'::jsonb, 'Prisma migration system with multiple environments', 'Migrations sync between local and database', 'Schema conflict, diverged migration history, not synced', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/60691027/prisma2-migrate-error-there-are-more-migrations-in-the-database-than-locally', 'admin:1764227325'),

('PrismaClientValidationError: Invalid invoke invocation - Argument error', 'orm', 'MEDIUM', '[{"solution": "Pass correct argument type to function", "percentage": 92}, {"solution": "Check function signature in Prisma docs", "percentage": 88}]'::jsonb, 'Prisma client method invocations', 'All method calls use correct argument types', 'Type mismatch, wrong argument shape, missing required args', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/77193562/error-prismaclientknownrequesterror-invalid-prisma-post-delete-invocation', 'admin:1764227325'),

('Error: Cannot connect to Docker Postgres from localhost - Host resolution issue', 'orm', 'HIGH', '[{"solution": "Use service name from docker-compose instead of localhost", "percentage": 92}, {"solution": "Add connect_timeout to DATABASE_URL for reliability", "percentage": 80}]'::jsonb, 'Docker + Prisma + PostgreSQL setup', 'Prisma successfully connects to database', 'Using localhost inside container, network misconfiguration', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/71663204/docker-prisma-error-p1001-cant-reach-database-server-at-postgres5432', 'admin:1764227325'),

('PrismaClientValidationError: Argument name: required string at index 0 not provided', 'orm', 'HIGH', '[{"solution": "Provide all required arguments to Prisma method", "percentage": 93}, {"solution": "Check parameter documentation for optional vs required", "percentage": 90}]'::jsonb, 'Prisma Client with required arguments', 'All required arguments supplied to methods', 'Missing required parameter, skipped mandatory field', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/75078929/how-to-handle-prisma-errors-and-send-a-valid-message-to-client', 'admin:1764227325'),

('Error: Invalid configuration in prisma schema - Generator or datasource error', 'orm', 'MEDIUM', '[{"solution": "Verify provider is valid (postgresql, mysql, sqlite, etc)", "percentage": 92}, {"solution": "Check DATABASE_URL environment variable is set", "percentage": 88}]'::jsonb, 'Prisma schema configuration', 'Prisma schema validates without errors', 'Invalid provider, missing env variable, syntax error in schema', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/75078929/how-to-handle-prisma-errors-and-send-a-valid-message-to-client', 'admin:1764227325'),

('PrismaClientUnknownRequestError: An unknown error occurred - Unexpected database error', 'orm', 'MEDIUM', '[{"solution": "Enable debug logging with DEBUG=* environment variable", "percentage": 80}, {"solution": "Check database server logs for detailed errors", "percentage": 85}]'::jsonb, 'Prisma with database connection issues', 'Detailed error message logged and resolved', 'Insufficient logging, missing database debugging', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/70849017/prisma-failed-queries-dont-return-proper-errors', 'admin:1764227325'),

('Error: Prisma migrate failed - Prepared statement already exists', 'orm', 'CRITICAL', '[{"solution": "Use directUrl for migrations with pgBouncer enabled", "percentage": 88}, {"solution": "Update database connection configuration", "percentage": 82}]'::jsonb, 'Supabase with PgBouncer + Prisma migrations', 'Migration completes without statement conflicts', 'Using pooler for migrations, missing directUrl, stale connections', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/71026259/prisma-postres-error-prepared-statement-s0-already-exists', 'admin:1764227325'),

('PrismaClientValidationError: Cannot use include and select together', 'orm', 'HIGH', '[{"solution": "Choose either include or select, not both", "percentage": 95}, {"solution": "Use select with nested select for granular control", "percentage": 92}]'::jsonb, 'Prisma query construction with relations', 'Query uses either include or select, not both', 'Mixing include and select in same query', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/69679956/nestjs-prisma-orm-using-select-versus-include-when-fetching-data-records', 'admin:1764227325'),

('Error P2014: Required relation violation - Attempting to unset required relation', 'orm', 'HIGH', '[{"solution": "Make relation optional with ? in schema if null allowed", "percentage": 88}, {"solution": "Always provide required relation when creating record", "percentage": 90}]'::jsonb, 'Prisma schema with required relations', 'Relations properly maintained or made optional', 'Removing required relation, not providing mandatory relation', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/75078929/how-to-handle-prisma-errors-and-send-a-valid-message-to-client', 'admin:1764227325'),

('PrismaClientRustPanicError: Database connection pool exhausted', 'orm', 'CRITICAL', '[{"solution": "Increase connection pool size in DATABASE_URL", "percentage": 85}, {"solution": "Implement connection pooling middleware", "percentage": 82}]'::jsonb, 'High-concurrency Prisma applications', 'Connections available for all concurrent requests', 'Too many concurrent connections, exhausted pool, no pooling', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/71663204/docker-prisma-error-p1001-cant-reach-database-server-at-postgres5432', 'admin:1764227325'),

('Error: prisma migrate resolve - Manual migration state correction needed', 'orm', 'MEDIUM', '[{"solution": "Use prisma migrate resolve --rolled-back <migration> to fix state", "percentage": 88}, {"solution": "Manually delete from _prisma_migrations table if migration broken", "percentage": 75}]'::jsonb, 'Prisma migration troubleshooting', 'Migration state synchronized, future migrations succeed', 'Corrupted migration state, conflicting migration history', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/68853597/prisma-migration-is-bad-state', 'admin:1764227325');
