INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Permission denied /usr/local/Homebrew/.git/config', 'package-manager', 'HIGH', '[{"solution": "Remove Homebrew and reinstall without sudo: sudo rm -rf /usr/local/Homebrew && /bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\"", "percentage": 92}]'::jsonb, 'macOS with Homebrew installed', 'Homebrew installs and updates successfully', 'Using sudo during installation', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/56180888/homebrew-installation-in-mac-is-giving-error', 'admin:1764224654'),
('brew link step did not complete successfully', 'package-manager', 'HIGH', '[{"solution": "Check ownership: sudo chown -R $(whoami) /usr/local && brew link <package>", "percentage": 88}, {"solution": "For High Sierra+: sudo chown -R $(whoami) $(brew --prefix)/*", "percentage": 85}]'::jsonb, 'macOS with installed package', 'Package symlinks correctly to /usr/local/bin', 'Not fixing ownership first', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/12607155/error-the-brew-link-step-did-not-complete-successfully', 'admin:1764224654'),
('Could not symlink /usr/local/bin is not writable', 'package-manager', 'HIGH', '[{"solution": "Fix ownership: sudo chown -R $(whoami) /usr/local", "percentage": 90}, {"solution": "Create directory with proper permissions: sudo mkdir -p /usr/local/bin && sudo chown $(whoami) /usr/local/bin", "percentage": 85}]'::jsonb, 'Installed package with failed symlink', 'brew link succeeds without errors', 'Using sudo unnecessarily', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/26647412/homebrew-could-not-symlink-usr-local-bin-is-not-writable', 'admin:1764224654'),
('/usr/local/Cellar is not writable', 'package-manager', 'HIGH', '[{"solution": "Fix Cellar permissions: sudo chown -R $(whoami) /usr/local/Cellar", "percentage": 93}, {"solution": "Complete reinstall: uninstall and reinstall Homebrew without sudo", "percentage": 88}]'::jsonb, 'macOS with Homebrew installation issues', 'brew install commands succeed', 'Multiple sudo usage during setup', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/40713805/homebrew-error-usr-local-cellar-is-not-writable', 'admin:1764224654'),
('homebrew-core is a shallow clone', 'package-manager', 'MEDIUM', '[{"solution": "Run: git -C $(brew --repo homebrew/core) fetch --unshallow", "percentage": 95}, {"solution": "Alternative: remove and re-clone: cd /usr/local/Homebrew/Library/Taps/homebrew && rm -rf homebrew-core && git clone https://github.com/Homebrew/homebrew-core.git", "percentage": 88}]'::jsonb, 'Homebrew with core tap', 'brew update completes without warnings', 'Not waiting for unshallow to complete (can take 10+ minutes)', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/45782694/how-to-remove-the-shallow-clone-warning-from-homebrew', 'admin:1764224654'),
('Error: No available formula with the name', 'package-manager', 'MEDIUM', '[{"solution": "Update Homebrew first: brew update", "percentage": 90}, {"solution": "Search for formula in taps: brew search <formula>", "percentage": 92}, {"solution": "Install from specific tap: brew install <tap>/<formula>", "percentage": 85}]'::jsonb, 'Homebrew installed and working', 'Package installs successfully', 'Not running brew update before install', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/37635486/why-cant-brew-find-a-specific-known-formula', 'admin:1764224654'),
('Could not create /usr/local/Cellar permission to write', 'package-manager', 'HIGH', '[{"solution": "Create directory manually: sudo mkdir -p /usr/local/Cellar && sudo chown -R $(whoami) /usr/local/Cellar", "percentage": 91}, {"solution": "Check permissions on /usr/local/lib", "percentage": 87}]'::jsonb, 'macOS with Homebrew initialization', 'Cellar directory exists with proper ownership', 'Directory permissions corrupted', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/47256429/there-is-no-cellar-file-in-my-usr-local-dir-for-brew', 'admin:1764224654'),
('brew update failed untracked working tree files would be overwritten', 'package-manager', 'MEDIUM', '[{"solution": "Reset git: cd $(brew --prefix) && git fetch origin && git reset --hard origin/master", "percentage": 93}, {"solution": "Alternative: chown and reset: chown -R $(whoami) $(brew --prefix)/.git && git reset --hard origin/master", "percentage": 88}]'::jsonb, 'Homebrew with git state issues', 'brew update succeeds and completes', 'Incomplete git resets', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/14113427/brew-update-failed-untracked-working-tree-files-would-be-overwritten-by-merge', 'admin:1764224654'),
('No such keg /usr/local/Cellar', 'package-manager', 'MEDIUM', '[{"solution": "Force uninstall: brew uninstall --force <formula>", "percentage": 89}, {"solution": "Manual cleanup: rm -rf /usr/local/Cellar/<package> && brew cleanup", "percentage": 86}]'::jsonb, 'Broken Homebrew installation', 'Package uninstalls and reinstalls cleanly', 'Orphaned keg references', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/28225045/no-such-keg-usr-local-cellar-git', 'admin:1764224654'),
('Error: No available formula or cask', 'package-manager', 'MEDIUM', '[{"solution": "Check if formula moved: brew tap --list-pinned", "percentage": 88}, {"solution": "Re-add tap: brew tap <tap-name>", "percentage": 90}]'::jsonb, 'Homebrew with installed taps', 'Package searches and installs successfully', 'Outdated or incorrect tap references', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/65673543/why-is-homebrew-not-finding-a-formula', 'admin:1764224654'),
('Permission denied rb_system when attempt to install', 'package-manager', 'MEDIUM', '[{"solution": "Fix directory ownership: sudo chown -R $(whoami) /usr/local", "percentage": 89}, {"solution": "For specific directory: sudo chown $(whoami) <directory-path>", "percentage": 87}]'::jsonb, 'Homebrew installation in progress', 'Package installs without permission errors', 'Previous sudo usage corrupting permissions', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/50827320/permission-denied-rb-system-when-attempt-to-install-httpd-using-homebrew', 'admin:1764224654'),
('fatal: Unable to find remote helper for https', 'package-manager', 'MEDIUM', '[{"solution": "Reinstall git: brew install git", "percentage": 92}, {"solution": "Check git installation: which git && git --version", "percentage": 88}]'::jsonb, 'Homebrew with git errors', 'brew update completes successfully', 'Corrupted git installation', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/37216073/homebrew-update-failure-on-mac', 'admin:1764224654'),
('brew cannot find command', 'package-manager', 'MEDIUM', '[{"solution": "Add to PATH: export PATH=/usr/local/bin:$PATH (Intel) or export PATH=/opt/homebrew/bin/:$PATH (Apple Silicon)", "percentage": 94}, {"solution": "Check Xcode: gcc --version && ruby -e $(curl -fsSL ...)", "percentage": 87}]'::jsonb, 'Homebrew installed', 'brew commands run without path issues', 'Missing PATH configuration', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/14288682/error-installing-homebrew-brew-command-not-found', 'admin:1764224654'),
('brew doctor errors /usr/local/include not writable', 'package-manager', 'MEDIUM', '[{"solution": "Fix ownership: sudo chown -R $(whoami) /usr/local", "percentage": 91}, {"solution": "Alternative for High Sierra: sudo chown -R $(whoami) $(brew --prefix)/*", "percentage": 88}]'::jsonb, 'macOS with Homebrew', 'brew doctor shows no warnings', 'Previous sudo make install conflicts', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/16462949/homebrew-brew-doctor-throwing-up-a-lot-of-errors-how-can-i-fix-them', 'admin:1764224654'),
('PHP not found after homebrew install on Monterey', 'package-manager', 'MEDIUM', '[{"solution": "Check PATH includes brew bin: echo $PATH | grep $(brew --prefix)/bin", "percentage": 89}, {"solution": "Relink PHP: brew unlink php && brew link --overwrite --force php@7.4", "percentage": 85}]'::jsonb, 'macOS Monterey with Homebrew PHP', 'php command runs and returns version', 'Missing PATH configuration', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/72194785/using-php-on-macos-monterey-many-homebrew-errors-on-reinstall-after-updating-o', 'admin:1764224654'),
('Cannot install in Homebrew on ARM processor in Intel default prefix', 'package-manager', 'HIGH', '[{"solution": "For Apple Silicon: reinstall Homebrew to /opt/homebrew or use: arch -x86_64 /bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)\"", "percentage": 93}, {"solution": "Check current arch: uname -m", "percentage": 88}]'::jsonb, 'Mac with Apple Silicon after Intel migration', 'brew installs to correct architecture path', 'Time Machine restore from Intel Mac', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/72890277/i-cant-uninstall-brew-on-macos-apple-silicon', 'admin:1764224654'),
('Homebrew installation failed already installed', 'package-manager', 'MEDIUM', '[{"solution": "Uninstall completely: /bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)\"", "percentage": 90}, {"solution": "Remove directories manually: sudo rm -rf /usr/local/Homebrew /opt/homebrew", "percentage": 85}]'::jsonb, 'Partially broken Homebrew installation', 'Fresh Homebrew install and update', 'Incomplete uninstallation leaving stale files', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/32858262/homebrew-failed-on-installation-but-now-wont-uninstall', 'admin:1764224654'),
('Broken symlinks found run brew prune', 'package-manager', 'LOW', '[{"solution": "Clean broken symlinks: brew cleanup --prune-prefix", "percentage": 88}, {"solution": "Manual cleanup: brew prune (deprecated but may still work)", "percentage": 82}]'::jsonb, 'Homebrew with orphaned symlinks', 'brew doctor shows no symlink warnings', 'Not running cleanup after uninstalling packages', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/52610026/how-to-fix-brews-symlink-errors-when-brew-thinks-the-link-already-exists/53517921', 'admin:1764224654'),
('Installed package just not linked', 'package-manager', 'MEDIUM', '[{"solution": "Link package: brew link <package>", "percentage": 94}, {"solution": "Force overwrite: brew link --overwrite --force <package>", "percentage": 89}]'::jsonb, 'Homebrew with installed but unlinked package', 'Package symlinks into /usr/local/bin', 'Conflicting symlinks from previous installs', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/29422345/installed-just-not-linked', 'admin:1764224654'),
('Formulae found in multiple taps conflict', 'package-manager', 'LOW', '[{"solution": "Untap conflicting tap: brew untap <conflicting-tap>", "percentage": 91}, {"solution": "Specify tap explicitly: brew install <tap>/<formula>", "percentage": 88}]'::jsonb, 'Multiple taps with duplicate formulas', 'Single tap provides formula without conflicts', 'Multiple taps enabled with overlapping packages', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/41989504/how-do-i-fix-homebrew-error-message-about-no-available-formula', 'admin:1764224654'),
('Linking step did not complete successfully memcached', 'package-manager', 'MEDIUM', '[{"solution": "Uninstall dependency: brew uninstall <dependency> && brew install <package>", "percentage": 89}, {"solution": "Fix ownership: sudo chown -R $(whoami) /usr/local", "percentage": 87}]'::jsonb, 'Homebrew with package installation failure', 'Package links and is accessible', 'Corrupted dependency ownership', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/11237048/homebrew-symlink-error', 'admin:1764224654'),
('brew update --debug verbose hanging doing nothing', 'package-manager', 'MEDIUM', '[{"solution": "Run with debug output: brew update --debug --verbose", "percentage": 87}, {"solution": "Check git status: cd /usr/local/Homebrew && git status", "percentage": 85}]'::jsonb, 'Homebrew on macOS Sierra or later', 'brew update completes in reasonable time', 'Network connectivity issues', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/20133587/brew-update-not-working-after-mac-10-9', 'admin:1764224654'),
('Error No such keg already linked unlink first', 'package-manager', 'MEDIUM', '[{"solution": "Use force uninstall: brew uninstall --force git && brew cleanup -s git && brew cleanup --prune-prefix", "percentage": 92}, {"solution": "Reinstall: brew install git", "percentage": 88}]'::jsonb, 'Broken Homebrew package with orphaned links', 'Package uninstalls and reinstalls cleanly', 'Corrupted package metadata', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/36135172/homebrew-no-such-keg', 'admin:1764224654'),
('Could not symlink lib/pkgconfig not writable', 'package-manager', 'MEDIUM', '[{"solution": "Fix directory permissions: chmod 755 /usr/local/lib/pkgconfig && brew link <package>", "percentage": 88}, {"solution": "Fix ownership: sudo chown -R $(whoami) /usr/local/lib", "percentage": 86}]'::jsonb, 'Homebrew with linking issues', 'Package symlinks successfully', 'Incorrect directory permissions', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/29422345/installed-just-not-linked', 'admin:1764224654');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Warning you have unlinked kegs in your cellar', 'package-manager', 'MEDIUM', '[{"solution": "Remove unlinked packages: brew remove <package-name> for each unlinked keg", "percentage": 90}, {"solution": "Force link: brew link --overwrite <package>", "percentage": 85}]'::jsonb, 'Homebrew with orphaned packages', 'brew doctor shows no unlinked keg warnings', 'Leaving outdated packages unremoved', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/30976312/unlinked-kegs-in-your-cellar-how-do-i-remove-them', 'admin:1764224654');
