INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Error: Server Functions cannot be called during initial render', 'react-server-components', 'HIGH', '[{"solution": "Use useEffect to call server functions after component mounts instead of during render", "percentage": 95}, {"solution": "Remove ''use server'' directive from functions called during render", "percentage": 90}]'::jsonb, 'Next.js 13+, server actions defined', 'Server function called only in useEffect or event handlers', 'Calling server actions directly in render phase', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/76761493/react-server-component-error-server-functions-can-not-be-called-during-initial', 'admin:1764259597'),

('Error: You''re importing a component that needs useEffect. It only works in a Client Component but none of its parents are marked with ''use client''', 'react-server-components', 'HIGH', '[{"solution": "Add ''use client'' directive to the component file containing useEffect", "percentage": 98}, {"solution": "Mark parent component with ''use client'' to allow all children to use hooks", "percentage": 95}]'::jsonb, 'React 18+, Next.js 13+ with App Router', 'No compilation errors, useEffect executes correctly', 'Forgetting to add ''use client'' directive', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/77143709/issue-with-react-server-components-in-next-js-reactservercomponentserror', 'admin:1764259597'),

('Error: React Context is unavailable in Server Components', 'react-server-components', 'HIGH', '[{"solution": "Use getServerSession from next-auth instead of useSession in server components", "percentage": 92}, {"solution": "Create a separate Client Component provider wrapper for SessionProvider", "percentage": 88}]'::jsonb, 'next-auth v4+, Next.js 13+', 'Context accessible in client components or via getServerSession', 'Using useContext or useSession in server components', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/76882764/error-react-context-is-unavailable-in-server-components', 'admin:1764259597'),

('Error: You''re importing a component that needs useState. It only works in a Client Component but none of its parents are marked with ''use client''', 'react-server-components', 'HIGH', '[{"solution": "Add ''use client'' to the file containing useState", "percentage": 97}, {"solution": "Move state to a child component and mark it with ''use client''", "percentage": 92}]'::jsonb, 'Next.js 13+, React 18+', 'useState works without errors in client components', 'Using useState without Client Component boundary', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/76195439/why-i-cannot-use-usestate-in-a-child-component-in-next-js-13', 'admin:1764259597'),

('Error: Failed to fetch RSC payload. Falling back to browser navigation', 'react-server-components', 'MEDIUM', '[{"solution": "Add event.preventDefault() to form submit handlers to prevent default navigation", "percentage": 85}, {"solution": "Ensure server route handlers return proper responses for all status codes", "percentage": 80}]'::jsonb, 'Next.js 13+ with form handlers', 'No navigation errors, form submits correctly', 'Form submit triggering page refresh instead of RSC fetch', 0.82, 'haiku', NOW(), 'https://stackoverflow.com/questions/76989456/error-failed-to-fetch-rsc-payload-falling-back-to-browser-navigation', 'admin:1764259597'),

('Error: Hydration failed because the initial UI does not match what was rendered on the server', 'react-server-components', 'HIGH', '[{"solution": "Move conditional renders into useEffect to ensure server and client match", "percentage": 91}, {"solution": "Check for invalid HTML structure like <p> containing <div>", "percentage": 88}]'::jsonb, 'React 18+, Next.js 13+', 'No hydration errors in console, UI renders consistently', 'Server rendering different content than client-side render', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/71706064/react-18-hydration-failed-because-the-initial-ui-does-not-match-what-was-render', 'admin:1764259597'),

('Error: This Suspense boundary received an update before it finished hydrating', 'react-server-components', 'MEDIUM', '[{"solution": "Use useTransition with startTransition for state updates during Suspense load", "percentage": 87}, {"solution": "Move data fetching outside of Suspense boundary to prevent updates during hydration", "percentage": 82}]'::jsonb, 'React 18+, Suspense boundaries', 'Suspense renders without hydration conflicts', 'Updating state while Suspense component is loading', 0.84, 'haiku', NOW(), 'https://stackoverflow.com/questions/72491998/this-suspense-boundary-received-an-update-before-it-finished-hydrating-error', 'admin:1764259597'),

('Error: The server did not finish this Suspense boundary: The server used ''renderToString'' which does not support Suspense', 'react-server-components', 'MEDIUM', '[{"solution": "Use renderToPipeableStream instead of renderToString for server-side rendering", "percentage": 93}, {"solution": "Move Suspense boundaries to client components or wrap in Error Boundary", "percentage": 85}]'::jsonb, 'React 18+, custom SSR setup', 'Suspense works without server timeout errors', 'Using renderToString with Suspense components in Gatsby or custom SSR', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/73927497/suspense-boundary-error-of-rendertostring-with-gatsbyjs-and-react-18-on-producti', 'admin:1764259597'),

('Error: Props must be serializable for components in the ''use client'' entry file', 'react-server-components', 'HIGH', '[{"solution": "Use function signature instead of arrow function type for function props", "percentage": 89}, {"solution": "Remove ''use client'' from child components that don''t need it", "percentage": 92}]'::jsonb, 'Next.js 13+, TypeScript', 'Props serialize correctly, no TS warnings', 'Passing non-serializable objects or function expressions as props', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/78471921/props-must-be-serializable-for-components-in-the-use-client-entry-file-setsh', 'admin:1764259597'),

('Error: Failed to find Server Action ''null''. This request might be from an older or newer deployment', 'react-server-components', 'MEDIUM', '[{"solution": "Ensure server actions are defined with ''use server'' directive and properly exported", "percentage": 85}, {"solution": "Clear Next.js build cache and rebuild with same server action IDs", "percentage": 80}]'::jsonb, 'Next.js 13.4+, server actions', 'Server actions execute without ''null'' reference errors', 'Mismatched server action references between builds', 0.81, 'haiku', NOW(), 'https://stackoverflow.com/questions/78262514/nextjs-failed-to-find-server-action-null', 'admin:1764259597'),

('Error: You have a Server Component that imports a hook that only works in Client Components (useRouter)', 'react-server-components', 'HIGH', '[{"solution": "Use useRouter from ''next/navigation'' only in ''use client'' components", "percentage": 96}, {"solution": "Move routing logic to client component children or use props", "percentage": 90}]'::jsonb, 'Next.js 13+ App Router', 'useRouter works without errors in client components', 'Using useRouter in server components', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/76206772/i-am-using-the-new-app-router-in-nextjs-getting-erroruserouter-only-works-in-c', 'admin:1764259597'),

('Error: window is not defined in server component', 'react-server-components', 'HIGH', '[{"solution": "Wrap window access in useEffect to ensure client-side execution", "percentage": 94}, {"solution": "Use dynamic import with ssr: false for components using window", "percentage": 91}]'::jsonb, 'Next.js 13+, browser APIs', 'Window object accessible without ReferenceError', 'Accessing window directly in component render logic', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/75692116/next-js-13-window-is-not-defined', 'admin:1764259597'),

('Error: Getting dynamic server usage when importing dynamic component with ssr: false', 'react-server-components', 'MEDIUM', '[{"solution": "Ensure dynamic import is only in client components or use ssr: true if possible", "percentage": 83}, {"solution": "Move dynamic import to after component hydration in useEffect", "percentage": 79}]'::jsonb, 'Next.js 13+, dynamic imports', 'No dynamic server usage warnings, components load correctly', 'Using dynamic() with ssr: false in server component context', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/76225377/getting-dynamic-server-usage-when-importing-dynamic-component-with-ssr-false-i', 'admin:1764259597'),

('Error: async/await is not yet supported in Client Components, only Server Components', 'react-server-components', 'MEDIUM', '[{"solution": "Move async logic to useEffect hook for client components", "percentage": 90}, {"solution": "Convert client component to server component if async logic is needed at top level", "percentage": 85}]'::jsonb, 'Next.js 13.4+, client components', 'Async data fetching works without errors', 'Using await at top level of client component', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/77742713/how-to-use-async-await-inside-client-component-in-next-js', 'admin:1764259597'),

('Error: Cannot use useCallback in server components', 'react-server-components', 'MEDIUM', '[{"solution": "Remove useCallback or convert component to ''use client''", "percentage": 95}, {"solution": "Use useCallback only in client components as server components don''t re-render", "percentage": 92}]'::jsonb, 'Next.js 13+, React 18+', 'useCallback works without errors in client components', 'Using useCallback in server component', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/79117030/can-i-use-usecallback-or-usememo-in-a-server-component', 'admin:1764259597'),

('Error: Cannot use useRef hook in server components', 'react-server-components', 'HIGH', '[{"solution": "Add ''use client'' directive to component using useRef", "percentage": 97}, {"solution": "Move useRef usage to a custom hook that''s called in client component", "percentage": 93}]'::jsonb, 'Next.js 13+, React 18+', 'useRef creates references without errors', 'Using useRef in server component without ''use client''', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/74497541/error-occuring-while-using-useref-in-nextjs13', 'admin:1764259597'),

('Error: Cannot use useSearchParams without Suspense boundary in client component', 'react-server-components', 'MEDIUM', '[{"solution": "Wrap component using useSearchParams in Suspense boundary", "percentage": 88}, {"solution": "Use useSearchParams hook with suspense: true option", "percentage": 84}]'::jsonb, 'Next.js 13+, dynamic routing', 'useSearchParams returns correct values without errors', 'Using useSearchParams in client component without Suspense wrapper', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/79630338/why-do-i-still-get-this-error-usesearchparams-should-be-wrapped-in-a-suspense', 'admin:1764259597'),

('Error: React Context cannot be accessed in server components', 'react-server-components', 'HIGH', '[{"solution": "Move context consumer to client components", "percentage": 94}, {"solution": "Use server-only data passing instead of Context for server components", "percentage": 88}]'::jsonb, 'Next.js 13+, React Context', 'Context values accessible in client component trees', 'Using useContext or accessing context directly in server components', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/76680547/is-it-possible-to-use-context-values-in-server-components', 'admin:1764259597'),

('Error: Attempted to call the default export of a client component from the server', 'react-server-components', 'MEDIUM', '[{"solution": "Render client component instead of calling it as a function", "percentage": 91}, {"solution": "Move client logic to a separate client component file", "percentage": 87}]'::jsonb, 'Next.js 13+, RSC boundaries', 'Client components render without invocation errors', 'Directly invoking client component functions instead of rendering as JSX', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/77837395/implementing-segment-analytics-on-next-js-14-with-nextauth', 'admin:1764259597'),

('Error: Invalid RSC payload structure or missing next-action header', 'react-server-components', 'MEDIUM', '[{"solution": "Ensure proper server action invocation with correct serialization", "percentage": 82}, {"solution": "Check that server action exports are properly defined with ''use server''", "percentage": 80}]'::jsonb, 'Next.js 13.4+, server actions', 'Server actions execute with valid payload headers', 'Malformed or missing RSC payload in server action responses', 0.80, 'haiku', NOW(), 'https://stackoverflow.com/questions/78262514/nextjs-failed-to-find-server-action-null', 'admin:1764259597'),

('Error: Mixed server and client component nesting causes hydration issues', 'react-server-components', 'MEDIUM', '[{"solution": "Use children props to pass server components to client components", "percentage": 89}, {"solution": "Structure tree with server components at top level when possible", "percentage": 85}]'::jsonb, 'Next.js 13+, component composition', 'Proper hydration with no mismatch warnings', 'Incorrectly nesting client components inside server components', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/76195439/why-i-cannot-use-usestate-in-a-child-component-in-next-js-13', 'admin:1764259597'),

('Error: Cannot serialize function props from server to client component', 'react-server-components', 'HIGH', '[{"solution": "Pass server actions instead of regular functions as props", "percentage": 90}, {"solution": "Move function to client component or define as server action", "percentage": 88}]'::jsonb, 'Next.js 13+, component props', 'Functions correctly passed as server actions', 'Attempting to serialize regular functions across server/client boundary', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/74789536/passing-function-from-server-to-client-component-next-13', 'admin:1764259597'),

('Error: useEffect hook runs on server side causing hydration mismatch', 'react-server-components', 'HIGH', '[{"solution": "Remember useEffect only runs on client side, not during SSR", "percentage": 95}, {"solution": "Use server-side data fetching with async components instead", "percentage": 91}]'::jsonb, 'React 18+, Next.js', 'useEffect executes only after hydration on client', 'Expecting useEffect to run during server-side rendering', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/77457425/how-to-implement-useeffect-in-the-server-in-next-js-14', 'admin:1764259597'),

('Error: Invalid hook call when using hooks outside of render', 'react-server-components', 'MEDIUM', '[{"solution": "Ensure hooks are called at top level of component function, not in callbacks", "percentage": 92}, {"solution": "Verify component is properly marked with ''use client''", "percentage": 88}]'::jsonb, 'React 18+, hooks rules', 'Hooks execute without Invalid hook call error', 'Calling hooks conditionally or inside callbacks', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/79054427/can-we-use-a-hook-on-react-server-component', 'admin:1764259597'),

('Error: Cannot read property of undefined when accessing server component result', 'react-server-components', 'MEDIUM', '[{"solution": "Ensure async server components are properly awaited before accessing properties", "percentage": 89}, {"solution": "Add null checks and default values for async component results", "percentage": 85}]'::jsonb, 'Next.js 13+, async components', 'Properties accessible without undefined errors', 'Not awaiting async server components or assuming sync behavior', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/77457425/how-to-implement-useeffect-in-the-server-in-next-js-14', 'admin:1764259597'),

('Error: Client component used without ''use client'' directive in app directory', 'react-server-components', 'HIGH', '[{"solution": "Add ''use client'' at the top of files using client-only features", "percentage": 97}, {"solution": "Move client logic to separate file with proper directive", "percentage": 94}]'::jsonb, 'Next.js 13+ App Router', 'Client features work without errors', 'Using hooks or browser APIs without ''use client'' directive', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/75831268/next-js-13-server-and-client-components-confusion', 'admin:1764259597'),

('Error: Cannot import server component into another server component as async wrapper', 'react-server-components', 'LOW', '[{"solution": "Import and render server component directly without async wrapper", "percentage": 88}, {"solution": "Use server-side imports at the module level", "percentage": 84}]'::jsonb, 'Next.js 13+, server components', 'Server components import and render correctly', 'Wrapping server component imports in async IIFE', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/77977157/using-a-react-server-component-in-the-root-layout-causes-all-my-pages-to-be-dyna', 'admin:1764259597'),

('Error: Segment analytics not called on server-side signIn', 'react-server-components', 'LOW', '[{"solution": "Use client-side useSession hook to detect sign-in in client component", "percentage": 85}, {"solution": "Move analytics.identify() call to a client component post-login", "percentage": 82}]'::jsonb, 'next-auth, Next.js 14+', 'Analytics identify called correctly on login', 'Trying to call client-side analytics from server-side next-auth events', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/77837395/implementing-segment-analytics-on-next-js-14-with-nextauth', 'admin:1764259597'),

('Error: Streaming rendering failed for Suspense boundary', 'react-server-components', 'MEDIUM', '[{"solution": "Ensure all async operations complete before stream closes", "percentage": 81}, {"solution": "Wrap long-running operations in Suspense with fallback UI", "percentage": 78}]'::jsonb, 'Next.js 13+, streaming responses', 'Streaming completes without errors, UI updates correctly', 'Streaming cuts off before Suspense resolves', 0.79, 'haiku', NOW(), 'https://stackoverflow.com/questions/76345474/why-am-i-getting-a-connection-closed-error-when-using-nextjs-13-4s-streaming', 'admin:1764259597'),

('Error: Segment export config requires runtime property change', 'react-server-components', 'LOW', '[{"solution": "Change ''api.runtime'' property instead of using old ''runtime'' property", "percentage": 89}, {"solution": "Use ''nodejs'' or ''edge'' as runtime value in export const config", "percentage": 86}]'::jsonb, 'Next.js 12+, Edge Runtime', 'Segment export config validates without errors', 'Using deprecated ''runtime'' property in segment config', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/76397306/export-const-config-please-change-runtime-property-to-segment-export-config', 'admin:1764259597'),

('Error: useMemo not available in server components', 'react-server-components', 'MEDIUM', '[{"solution": "Remove useMemo or convert to ''use client'' component", "percentage": 96}, {"solution": "Use useMemo only in client components for memoization", "percentage": 93}]'::jsonb, 'React 18+, Next.js 13+', 'Memoization works in client components', 'Using useMemo in server component', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/79117030/can-i-use-usecallback-or-usememo-in-a-server-component', 'admin:1764259597'),

('Error: Children props hydration mismatch between server and client', 'react-server-components', 'MEDIUM', '[{"solution": "Ensure children rendered from server component are identical on client", "percentage": 87}, {"solution": "Use suppressHydrationWarning for dynamic content if necessary", "percentage": 79}]'::jsonb, 'React 18+, server/client boundaries', 'Children render identically on server and client', 'Server and client render different children content', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/71706064/react-18-hydration-failed-because-the-initial-ui-does-not-match-what-was-render', 'admin:1764259597'),

('Error: useLayoutEffect not supported in server components', 'react-server-components', 'MEDIUM', '[{"solution": "Use useEffect instead of useLayoutEffect or mark as client component", "percentage": 94}, {"solution": "Move layout effect logic to client-side only", "percentage": 90}]'::jsonb, 'React 18+, client components', 'Layout side effects execute correctly in client', 'Using useLayoutEffect in server component', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/70669619/if-usestate-is-not-supported-by-react-server-components-how-do-we-assign-compone', 'admin:1764259597'),

('Error: Cannot destructure session from useSession in server component', 'react-server-components', 'HIGH', '[{"solution": "Use getServerSession with authOptions instead of useSession", "percentage": 95}, {"solution": "Move useSession to client component wrapper", "percentage": 92}]'::jsonb, 'next-auth v4+, Next.js 13+', 'Session accessible without destructuring errors', 'Using useSession in server component', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/76882764/error-react-context-is-unavailable-in-server-components', 'admin:1764259597'),

('Error: Invalid component type returned from dynamic import', 'react-server-components', 'MEDIUM', '[{"solution": "Ensure dynamic import returns valid React component", "percentage": 88}, {"solution": "Use .then() to extract component from module correctly", "percentage": 85}]'::jsonb, 'Next.js 13+, dynamic imports', 'Dynamic components render without type errors', 'Returning wrong export or malformed module from dynamic import', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/75692116/next-js-13-window-is-not-defined', 'admin:1764259597'),

('Error: useState renders correctly but state never updates in server component', 'react-server-components', 'HIGH', '[{"solution": "Remember useState is for client components only", "percentage": 96}, {"solution": "Convert component to ''use client'' if state management needed", "percentage": 94}]'::jsonb, 'React 18+, Next.js 13+', 'State updates trigger re-renders in client components', 'Using useState in server component and expecting state to update', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/73523550/can-i-use-usestate-with-server-side-rendering', 'admin:1764259597'),

('Error: dangerouslySetInnerHTML not serializable for server to client transfer', 'react-server-components', 'LOW', '[{"solution": "Mark component with ''use client'' before using dangerouslySetInnerHTML", "percentage": 91}, {"solution": "Pass HTML content as prop instead of generating in server component", "percentage": 87}]'::jsonb, 'Next.js 13+, client components', 'HTML renders safely without serialization warnings', 'Using dangerouslySetInnerHTML with server component props', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/59630554/dangerouslysetinnerhtml-in-react-application-not-working-for-including-segment-i', 'admin:1764259597'),

('Error: Cannot use array spread on server component JSX', 'react-server-components', 'MEDIUM', '[{"solution": "Spread props inside component return, not at definition", "percentage": 85}, {"solution": "Spread server component children manually instead of using spread operator on JSX", "percentage": 81}]'::jsonb, 'React 18+, JSX syntax', 'Props spread correctly without errors', 'Attempting to spread server component JSX attributes', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/76195439/why-i-cannot-use-usestate-in-a-child-component-in-next-js-13', 'admin:1764259597'),

('Error: Cannot use event handlers in server components', 'react-server-components', 'HIGH', '[{"solution": "Move event handler logic to client component", "percentage": 96}, {"solution": "Use server actions wrapped in client component handlers", "percentage": 93}]'::jsonb, 'Next.js 13+, event handling', 'Event handlers work without errors in client components', 'Adding onClick or other event handlers to server components', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/75831268/next-js-13-server-and-client-components-confusion', 'admin:1764259597'),

('Error: Boundary for async component must be wrapped in Suspense', 'react-server-components', 'MEDIUM', '[{"solution": "Wrap async server component in Suspense with fallback UI", "percentage": 90}, {"solution": "Use Error boundary alongside Suspense for error handling", "percentage": 86}]'::jsonb, 'React 18+, async components', 'Async components render with proper fallback UI', 'Using async component without Suspense wrapper', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/73927497/suspense-boundary-error-of-rendertostring-with-gatsbyjs-and-react-18-on-producti', 'admin:1764259597'),

('Error: Cannot import client-only module in server component', 'react-server-components', 'HIGH', '[{"solution": "Check module exports and move client code to separate file", "percentage": 91}, {"solution": "Use server-only module wrapper or conditional imports", "percentage": 87}]'::jsonb, 'Next.js 13+, module boundaries', 'Modules import correctly with proper boundaries', 'Importing browser-only packages in server components', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/74151552/es-modules-may-not-assign-module-exports-or-exports-in-module-with-import', 'admin:1764259597'),

('Error: useContext cannot read context value in server component', 'react-server-components', 'HIGH', '[{"solution": "Move useContext to client component within provider tree", "percentage": 94}, {"solution": "Pass context data as props instead of using useContext", "percentage": 89}]'::jsonb, 'React Context, Next.js 13+', 'Context values accessible in client component subtrees', 'Using useContext in server component outside provider', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/76680547/is-it-possible-to-use-context-values-in-server-components', 'admin:1764259597'),

('Error: Prop serialization fails with Date objects in server to client transfer', 'react-server-components', 'MEDIUM', '[{"solution": "Convert Date to ISO string before passing as prop", "percentage": 92}, {"solution": "Serialize Date objects in server component before sending", "percentage": 89}]'::jsonb, 'Next.js 13+, serialization', 'Dates transfer correctly as strings without serialization errors', 'Passing Date objects directly as props from server to client', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/78552115/hydration-completed-but-contains-mismatches-using-veevalidate-and-pinia-in-nuxt', 'admin:1764259597'),

('Error: Async function assigned to props cannot be serialized', 'react-server-components', 'MEDIUM', '[{"solution": "Use server actions instead of regular async functions in props", "percentage": 91}, {"solution": "Move async logic to client component or server action handler", "percentage": 87}]'::jsonb, 'Next.js 13.4+, server actions', 'Server actions pass correctly as props to client components', 'Assigning async functions directly to props', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/76029385/pass-a-server-side-prop-to-a-client-side-component', 'admin:1764259597'),

('Error: useReducer hook cannot be used in server components', 'react-server-components', 'MEDIUM', '[{"solution": "Convert component to ''use client'' to use useReducer", "percentage": 95}, {"solution": "Move state management to client component child", "percentage": 91}]'::jsonb, 'React 18+, state management', 'useReducer manages state correctly in client components', 'Using useReducer in server component', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/70669619/if-usestate-is-not-supported-by-react-server-components-how-do-we-assign-compone', 'admin:1764259597'),

('Error: Client component instantiated with class component breaks RSC rendering', 'react-server-components', 'LOW', '[{"solution": "Convert class components to functional components for RSC compatibility", "percentage": 88}, {"solution": "Wrap class component in functional wrapper with ''use client''", "percentage": 84}]'::jsonb, 'React 18+, Next.js 13+', 'Components render without class/functional conversion errors', 'Using older class components in RSC boundary', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/79054427/can-we-use-a-hook-on-react-server-component', 'admin:1764259597'),

('Error: Promise cannot be serialized as prop from server to client', 'react-server-components', 'HIGH', '[{"solution": "Await promise before sending as prop", "percentage": 95}, {"solution": "Use server action to handle promise and pass result", "percentage": 92}]'::jsonb, 'Next.js 13+, async operations', 'Promises resolve and data passes correctly as props', 'Passing unresolved promises as props from server to client', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/75665733/how-to-import-async-server-components-into-client-components-in-nextjs-13', 'admin:1764259597'),

('Error: Module exports assignment conflicts with RSC serialization', 'react-server-components', 'MEDIUM', '[{"solution": "Use ES6 export syntax instead of module.exports", "percentage": 93}, {"solution": "Separate server and client exports into different files", "percentage": 89}]'::jsonb, 'Next.js 13+, ES modules', 'Modules export correctly using ES6 syntax', 'Mixing module.exports with ES6 exports in server components', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/74151552/es-modules-may-not-assign-module-exports-or-exports-in-module-with-import', 'admin:1764259597'),

('Error: Dynamic segment import in server component causes routing issues', 'react-server-components', 'MEDIUM', '[{"solution": "Use params from async component props instead of dynamic import", "percentage": 87}, {"solution": "Access route parameters through function arguments in server component", "percentage": 84}]'::jsonb, 'Next.js 13+, dynamic routing', 'Route parameters accessible in server components', 'Attempting to dynamically import route segments in server components', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/76578186/how-to-get-dynamic-segment-in-next-js-13-app-router', 'admin:1764259597'),

('Error: Conditional rendering in server component causes mismatch with client', 'react-server-components', 'MEDIUM', '[{"solution": "Move conditional render logic to client component for dynamic content", "percentage": 89}, {"solution": "Use Suspense boundaries to isolate dynamic sections", "percentage": 85}]'::jsonb, 'React 18+, Next.js 13+', 'Conditional content renders identically on server and client', 'Server and client render different branches of conditionals', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/71706064/react-18-hydration-failed-because-the-initial-ui-does-not-match-what-was-render', 'admin:1764259597'),

('Error: Non-JSON-serializable object in server component response', 'react-server-components', 'MEDIUM', '[{"solution": "Convert objects to JSON-serializable format before sending", "percentage": 91}, {"solution": "Use toJSON method or custom serialization for complex objects", "percentage": 88}]'::jsonb, 'Next.js 13+, serialization', 'All data serializes to JSON without errors', 'Passing functions, symbols, or non-serializable objects', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/42262925/javascript-servicestack-client-serialization-error', 'admin:1764259597'),

('Error: Server component cannot render async children without proper boundary', 'react-server-components', 'MEDIUM', '[{"solution": "Wrap async children in Suspense boundary", "percentage": 92}, {"solution": "Ensure parent component is also async and awaits children", "percentage": 88}]'::jsonb, 'React 18+, async components', 'Async children render with proper Suspense fallback', 'Rendering async components without Suspense wrapper', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/73927497/suspense-boundary-error-of-rendertostring-with-gatsbyjs-and-react-18-on-producti', 'admin:1764259597'),

('Error: Invalid hook order when hooks called conditionally in client component', 'react-server-components', 'MEDIUM', '[{"solution": "Move hook calls outside of conditionals to top level", "percentage": 96}, {"solution": "Use custom hook wrapper if conditional logic needed", "percentage": 92}]'::jsonb, 'React 18+, hooks rules', 'Hooks execute in consistent order without errors', 'Calling hooks inside conditionals or loops', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/63652894/useref-invalid-hook-call', 'admin:1764259597'),

('Error: Stale closure in server component prop functions', 'react-server-components', 'LOW', '[{"solution": "Use server action instead of closure for consistent behavior", "percentage": 88}, {"solution": "Ensure prop functions have access to latest data context", "percentage": 84}]'::jsonb, 'Next.js 13+, server actions', 'Functions access current data without stale values', 'Prop functions closing over outdated values', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/76761493/react-server-component-error-server-functions-can-not-be-called-during-initial', 'admin:1764259597'),

('Error: Fragment children not serializable in server to client transfer', 'react-server-components', 'LOW', '[{"solution": "Wrap fragments in div or other container element", "percentage": 90}, {"solution": "Flatten fragment children before passing as props", "percentage": 86}]'::jsonb, 'React 18+, JSX', 'Children structure serializes correctly', 'Passing React.Fragment children as props', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/77015023/if-i-pass-a-server-component-to-a-client-component-via-the-children-prop-will-i', 'admin:1764259597'),

('Error: Custom hook using hooks in server component context', 'react-server-components', 'HIGH', '[{"solution": "Ensure custom hook is called in client component or ''use client'' file", "percentage": 95}, {"solution": "Create server-only version of custom hook without hooks", "percentage": 90}]'::jsonb, 'React 18+, custom hooks', 'Custom hooks work correctly in client components', 'Calling custom hook containing hooks in server component', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/75053770/nextjs13-how-can-i-use-a-custom-hook-in-a-server-component', 'admin:1764259597'),

('Error: Map or Set object cannot be serialized as prop', 'react-server-components', 'MEDIUM', '[{"solution": "Convert Map/Set to array or object before passing as prop", "percentage": 93}, {"solution": "Use plain JavaScript objects instead of Map/Set for serialization", "percentage": 90}]'::jsonb, 'Next.js 13+, serialization', 'Collections pass as objects without serialization errors', 'Passing Map or Set objects directly as props', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/35534806/module-exports-not-working', 'admin:1764259597'),

('Error: useImperativeHandle not available in server components', 'react-server-components', 'LOW', '[{"solution": "Use useImperativeHandle only in forwardRef client components", "percentage": 94}, {"solution": "Convert component to client component if imperative handle needed", "percentage": 91}]'::jsonb, 'React 18+, ref forwarding', 'Imperative handles work in client components', 'Using useImperativeHandle in server component', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/70669619/if-usestate-is-not-supported-by-react-server-components-how-do-we-assign-compone', 'admin:1764259597'),

('Error: useId hook gives different values on server and client renders', 'react-server-components', 'MEDIUM', '[{"solution": "Ensure useId is only called on client side or use suppressHydrationWarning", "percentage": 89}, {"solution": "Use useId in client component only, not server", "percentage": 86}]'::jsonb, 'React 18+, hooks', 'useId generates consistent values without warnings', 'Using useId in server component causing mismatch', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/78552115/hydration-completed-but-contains-mismatches-using-veevalidate-and-pinia-in-nuxt', 'admin:1764259597'),

('Error: Big integers not serializable in server to client response', 'react-server-components', 'LOW', '[{"solution": "Convert BigInt to string before serialization", "percentage": 92}, {"solution": "Use string representation for large numbers", "percentage": 89}]'::jsonb, 'Next.js 13+, numeric types', 'BigInt values convert to strings without errors', 'Attempting to serialize BigInt as JSON', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/42262925/javascript-servicestack-client-serialization-error', 'admin:1764259597'),

('Error: useTransition cannot be used in server components', 'react-server-components', 'MEDIUM', '[{"solution": "Move useTransition to client component", "percentage": 96}, {"solution": "Convert component to ''use client'' to use transitions", "percentage": 93}]'::jsonb, 'React 18+, transitions', 'useTransition manages state transitions in client components', 'Using useTransition in server component', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/72491998/this-suspense-boundary-received-an-update-before-it-finished-hydrating-error', 'admin:1764259597'),

('Error: useDeferredValue not available in server components', 'react-server-components', 'MEDIUM', '[{"solution": "Use useDeferredValue only in client components", "percentage": 95}, {"solution": "Mark component with ''use client'' to defer values", "percentage": 92}]'::jsonb, 'React 18+, performance', 'useDeferredValue defers value updates in client components', 'Using useDeferredValue in server component', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/72491998/this-suspense-boundary-received-an-update-before-it-finished-hydrating-error', 'admin:1764259597'),

('Error: ErrorBoundary does not catch errors in server components', 'react-server-components', 'MEDIUM', '[{"solution": "Use try-catch in server components instead of Error Boundary", "percentage": 90}, {"solution": "Wrap server component in Error Boundary as client component", "percentage": 86}]'::jsonb, 'React 18+, error handling', 'Errors caught by Error Boundary in client components', 'Using Error Boundary to catch server component errors', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/70654847/with-react-18-and-suspense-how-to-display-specific-errors-not-just-fallback-in', 'admin:1764259597'),

('Error: Server component imports client-only module causing build error', 'react-server-components', 'HIGH', '[{"solution": "Use ''server-only'' module wrapper to prevent client imports", "percentage": 92}, {"solution": "Separate server and client code into different files", "percentage": 89}]'::jsonb, 'Next.js 13+, module boundaries', 'Modules import correctly with proper server/client separation', 'Accidentally importing browser-specific modules in server components', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/74151552/es-modules-may-not-assign-module-exports-or-exports-in-module-with-import', 'admin:1764259597'),

('Error: Layout component cannot access dynamic data directly', 'react-server-components', 'MEDIUM', '[{"solution": "Use async layout component or pass data from child", "percentage": 87}, {"solution": "Fetch layout data in async function called at top level", "percentage": 84}]'::jsonb, 'Next.js 13+, layouts', 'Layout has access to necessary data without errors', 'Expecting layout to access dynamic route parameters', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/75171987/how-do-i-get-my-layout-component-to-remain-static-in-next13-app-folder', 'admin:1764259597'),

('Error: Invalid JSX in client component after server boundary', 'react-server-components', 'MEDIUM', '[{"solution": "Ensure JSX is valid in component marked with ''use client''", "percentage": 94}, {"solution": "Check for unescaped characters or malformed tags", "percentage": 91}]'::jsonb, 'React 18+, JSX syntax', 'JSX renders without syntax errors', 'Invalid JSX syntax in client component', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/75831268/next-js-13-server-and-client-components-confusion', 'admin:1764259597'),

('Error: Server action handler receives undefined parameters', 'react-server-components', 'MEDIUM', '[{"solution": "Ensure FormData or parameters are properly serialized when calling action", "percentage": 89}, {"solution": "Verify server action receives parameters from form submission", "percentage": 86}]'::jsonb, 'Next.js 13.4+, server actions', 'Server action receives correct parameters without undefined errors', 'Form data not properly passed to server action handler', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/78576467/using-server-action-to-call-api-is-not-working', 'admin:1764259597'),

('Error: Nested server component nesting deeply causes memory issues', 'react-server-components', 'LOW', '[{"solution": "Avoid deeply nested server components, use props instead", "percentage": 85}, {"solution": "Flatten component hierarchy to reduce nesting depth", "percentage": 81}]'::jsonb, 'Next.js 13+, performance', 'Components render efficiently without memory overhead', 'Creating deeply nested server component trees', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/77977157/using-a-react-server-component-in-the-root-layout-causes-all-my-pages-to-be-dyna', 'admin:1764259597'),

('Error: useContext hook conflicts with multiple providers in server boundary', 'react-server-components', 'MEDIUM', '[{"solution": "Ensure all context providers are on client side of boundary", "percentage": 91}, {"solution": "Use separate client component wrapper for context providers", "percentage": 88}]'::jsonb, 'React Context, Next.js 13+', 'Context providers work correctly in client subtree', 'Multiple providers fighting over context values across boundaries', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/76680547/is-it-possible-to-use-context-values-in-server-components', 'admin:1764259597');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Error: Render function callback props cannot serialize in server component', 'react-server-components', 'MEDIUM', '[{"solution": "Use server actions for callbacks instead of render function props", "percentage": 88}, {"solution": "Move callback logic to client component or use useCallback", "percentage": 85}]'::jsonb, 'Next.js 13+, callbacks', 'Callbacks execute without serialization errors', 'Passing render function callbacks as props', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/76640252/useeffect-in-react-server-components', 'admin:1764259597'),

('Error: useOptimistic not available in all React versions', 'react-server-components', 'LOW', '[{"solution": "Ensure React 18.3+ is installed for useOptimistic", "percentage": 94}, {"solution": "Implement optimistic updates manually with useState and useEffect", "percentage": 89}]'::jsonb, 'React 18.3+, optimistic updates', 'Optimistic updates work without errors', 'Using useOptimistic with older React version', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/79322031/suspense-with-use-hook-and-server-action-wanting-useeffect', 'admin:1764259597'),

('Error: Symbol type cannot be serialized from server to client', 'react-server-components', 'LOW', '[{"solution": "Avoid using Symbol types in props between server and client", "percentage": 91}, {"solution": "Convert Symbols to strings before serialization", "percentage": 88}]'::jsonb, 'JavaScript, serialization', 'Data transfers without Symbol serialization errors', 'Passing Symbol values as props', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/42262925/javascript-servicestack-client-serialization-error', 'admin:1764259597'),

('Error: Regex pattern not serializable in props', 'react-server-components', 'LOW', '[{"solution": "Convert Regex to string source and flags before passing", "percentage": 90}, {"solution": "Pass validation function instead of regex pattern", "percentage": 86}]'::jsonb, 'JavaScript, patterns', 'Regex validation works without serialization errors', 'Passing Regex objects directly as props', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/42262925/javascript-servicestack-client-serialization-error', 'admin:1764259597'),

('Error: WeakMap or WeakSet cannot be serialized', 'react-server-components', 'LOW', '[{"solution": "Use regular Map or Set instead of Weak variants", "percentage": 92}, {"solution": "Avoid weak collections for props that need serialization", "percentage": 89}]'::jsonb, 'JavaScript data structures', 'Collection data serializes correctly', 'Using WeakMap or WeakSet in serializable props', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/42262925/javascript-servicestack-client-serialization-error', 'admin:1764259597'),

('Error: Function with closure cannot be serialized from server action', 'react-server-components', 'MEDIUM', '[{"solution": "Extract function logic to top level or use server action directly", "percentage": 87}, {"solution": "Pass data instead of closed-over functions between boundaries", "percentage": 84}]'::jsonb, 'Next.js 13.4+, closures', 'Functions transfer correctly without closure serialization', 'Returning function with closure from server action', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/76761493/react-server-component-error-server-functions-can-not-be-called-during-initial', 'admin:1764259597'),

('Error: Circular reference in object props causes infinite loop', 'react-server-components', 'MEDIUM', '[{"solution": "Break circular references before serialization", "percentage": 89}, {"solution": "Use custom toJSON method to handle circular references", "percentage": 85}]'::jsonb, 'JavaScript, object references', 'Objects serialize without infinite loops', 'Passing objects with circular references', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/42262925/javascript-servicestack-client-serialization-error', 'admin:1764259597'),

('Error: Form action handler not receiving FormData correctly', 'react-server-components', 'MEDIUM', '[{"solution": "Ensure form submit passes FormData to server action", "percentage": 88}, {"solution": "Use client component wrapper for forms to pass FormData", "percentage": 85}]'::jsonb, 'Next.js 13.4+, form handling', 'FormData transfers correctly to server action', 'Form not properly submitting to server action handler', 0.86, 'haiku', NOW(), 'https://stackoverflow.com/questions/78576467/using-server-action-to-call-api-is-not-working', 'admin:1764259597'),

('Error: Blob or File object cannot be serialized in props', 'react-server-components', 'MEDIUM', '[{"solution": "Convert Blob/File to base64 string before passing", "percentage": 89}, {"solution": "Use FormData to handle file uploads from client", "percentage": 86}]'::jsonb, 'Next.js 13+, file handling', 'Files transfer correctly via FormData', 'Passing Blob or File objects as props directly', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/35094806/module-exports-not-working', 'admin:1764259597'),

('Error: AbortController signal not serializable across boundary', 'react-server-components', 'LOW', '[{"solution": "Create AbortController on client side only for cancellation", "percentage": 91}, {"solution": "Don''t pass AbortSignal in props between boundaries", "percentage": 88}]'::jsonb, 'Next.js 13+, async operations', 'Abort signals work without serialization errors', 'Passing AbortSignal in props from server to client', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/42262925/javascript-servicestack-client-serialization-error', 'admin:1764259597'),

('Error: Performance observer or other browser API objects not serializable', 'react-server-components', 'LOW', '[{"solution": "Create browser API objects in client component useEffect only", "percentage": 93}, {"solution": "Don''t pass browser API instances as props", "percentage": 90}]'::jsonb, 'Next.js 13+, browser APIs', 'Browser APIs initialize correctly in client components', 'Passing browser API objects as props', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/42262925/javascript-servicestack-client-serialization-error', 'admin:1764259597');
