-- Batch 4: Next.js + npm + Vercel + TypeScript + Webpack Combined Migration
-- Sources: Official docs from each technology
-- Mined: 2025-11-25
-- Categories: nextjs, npm, vercel, typescript, webpack

-- ============================================
-- NEXT.JS ERRORS (15 entries)
-- ============================================

INSERT INTO knowledge_entries (
    query, category, hit_frequency, solutions, prerequisites, success_indicators,
    common_pitfalls, success_rate, claude_version, last_verified, source_url
) VALUES (
    'Next.js error: React hydration mismatch',
    'nextjs',
    'CRITICAL',
    $$[{"solution": "Ensure server and client render identical content. Use useEffect with clientOnly flag for dynamic content. Check for date/timestamp rendering differences.", "percentage": 92, "note": "Text content mismatch between server and client"}]$$::jsonb,
    'Next.js app with SSR/SSG',
    'No hydration warnings in console',
    'Using Date.now(), random values, browser APIs during render, conditional rendering based on client state',
    0.92,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/react-hydration-error'
),
(
    'Next.js error: DynamicServerError during static generation',
    'nextjs',
    'CRITICAL',
    $$[{"solution": "Remove dynamic API calls (cookies, headers, searchParams) from getStaticProps. Use getServerSideProps or dynamic rendering instead. Mark routes with dynamic functions as non-static.", "percentage": 88, "note": "Static page generation attempted with dynamic server calls"}]$$::jsonb,
    'Next.js app with static generation',
    'Build completes without dynamic server errors',
    'Using cookies(), headers(), searchParams in SSG, not catching DynamicServerError properly',
    0.88,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/dynamic-server-error'
),
(
    'Next.js error: app/ Static to Dynamic conversion error',
    'nextjs',
    'CRITICAL',
    $$[{"solution": "Wrap dynamic API calls in try-catch or isPrerendering check. Use fallback patterns. Ensure fallback: true for ISR. Migrate to dynamic route handling.", "percentage": 85, "note": "Route marked static but accessed dynamic values at runtime"}]$$::jsonb,
    'Next.js app with App Router',
    'Routes properly render with or without dynamic values',
    'Accessing cookies/headers after static prerendering, missing fallback handling',
    0.85,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/app-static-to-dynamic-error'
),
(
    'Next.js error: Client-side exception occurred',
    'nextjs',
    'HIGH',
    $$[{"solution": "Add error boundary in app/error.js. Use try-catch in event handlers. Use useErrorHandler hook from react-error-boundary. Log to error tracking service.", "percentage": 80, "note": "Uncaught client error in production"}]$$::jsonb,
    'Next.js app with error handling',
    'Errors caught and logged with error.js boundary',
    'Uncaught exceptions, async errors not in error boundary, missing error logging',
    0.80,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/client-side-exception-occurred'
),
(
    'Next.js error: next/image unconfigured host',
    'nextjs',
    'HIGH',
    $$[{"solution": "Add image domain to next.config.js remotePatterns or domains array. Match protocol (http/https). Include all necessary subdomains and paths.", "percentage": 87, "note": "External image source not authorized"}]$$::jsonb,
    'Next.js app with next/image',
    'Images load without warnings',
    'Wrong protocol (https vs http), missing subdomain config, relative URLs without domain config',
    0.87,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/next-image-unconfigured-host'
),
(
    'Next.js error: Invalid next.config.js options',
    'nextjs',
    'MEDIUM',
    $$[{"solution": "Check next.config.js for typos and unknown fields. Validate option types. Use TypeScript config for validation. Check official docs for valid options.", "percentage": 90, "note": "Config parsing error or invalid field names"}]$$::jsonb,
    'Next.js project with next.config.js',
    'Build succeeds without config warnings',
    'Typos in field names, deprecated options, wrong data types, experimental flags without proper syntax',
    0.90,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/invalid-next-config'
),
(
    'Next.js error: Module not found',
    'nextjs',
    'HIGH',
    $$[{"solution": "Run npm install or yarn install for missing dependency. Check import path spelling. Verify file exists at referenced path. Check tsconfig.json paths.", "percentage": 93, "note": "Missing dependency or incorrect import path"}]$$::jsonb,
    'Next.js app with dependencies',
    'All imports resolve without errors',
    'Typos in import paths, missing node_modules, incorrect relative paths, missing dependencies',
    0.93,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/module-not-found'
),
(
    'Next.js error: Page without valid React component export',
    'nextjs',
    'MEDIUM',
    $$[{"solution": "Ensure page/route exports default React component. Check component is valid JSX/TSX. Add default export if missing. Validate component returns valid JSX.", "percentage": 91, "note": "Page file does not export valid component"}]$$::jsonb,
    'Next.js app with route files',
    'Page renders without component errors',
    'Missing default export, exporting non-component, invalid JSX syntax, empty files',
    0.91,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/page-without-valid-component'
),
(
    'Next.js error: Conflicting public file and page',
    'nextjs',
    'MEDIUM',
    $$[{"solution": "Rename public file or page to avoid path conflict. Ensure unique URL paths for static files and routes. Move file to different directory.", "percentage": 89, "note": "Same path exists in both public/ and routes"}]$$::jsonb,
    'Next.js app with App Router',
    'No conflicting files at same URL paths',
    'Same filename in public/ and pages/, path collisions, overwrite conflicts',
    0.89,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/conflicting-public-file-page'
),
(
    'Next.js error: NextRouter was not mounted',
    'nextjs',
    'MEDIUM',
    $$[{"solution": "Import useRouter from next/router only in pages/ directory. Use next/compat/router for migration. Use next/navigation in App Router. Ensure component is mounted.", "percentage": 86, "note": "Using pages/ Router in App Router context"}]$$::jsonb,
    'Next.js app transitioning between routers',
    'Router hooks work in correct directory context',
    'Using next/router in App Router, using next/navigation in Pages Router, calling hook outside mounted component',
    0.86,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/next-router-not-mounted'
),
(
    'Next.js error: Prerender error during build',
    'nextjs',
    'HIGH',
    $$[{"solution": "Fix errors in page component render logic. Remove dynamic API calls from SSG. Check console for specific error message. Use fallback or ISR.", "percentage": 82, "note": "Error during static page generation at build time"}]$$::jsonb,
    'Next.js app with static generation',
    'Build completes with all pages prerendered',
    'Unhandled errors in components, infinite loops, missing data during generation',
    0.82,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/prerender-error'
),
(
    'Next.js error: getServerSideProps with static export',
    'nextjs',
    'MEDIUM',
    $$[{"solution": "Remove getServerSideProps and use getStaticProps instead. Remove next export/output:export from config. Use next start for server-rendered routes.", "percentage": 88, "note": "getServerSideProps incompatible with static export"}]$$::jsonb,
    'Next.js app with export/Pages Router',
    'Build succeeds without SSR requirement',
    'Using getServerSideProps with output: export, static build with server-side rendering',
    0.88,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/gssp-export'
),
(
    'Next.js error: Invalid PostCSS configuration',
    'nextjs',
    'LOW',
    $$[{"solution": "Add postcss.config.js or postcss config in next.config.js. Use correct PostCSS shape: object with plugins property. Install postcss if missing.", "percentage": 91, "note": "PostCSS config in unsupported format"}]$$::jsonb,
    'Next.js app with CSS-in-JS',
    'CSS compiles without PostCSS warnings',
    'Wrong config format, missing postcss package, incorrect plugins property shape',
    0.91,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/postcss-shape'
),
(
    'Next.js error: next.config.js loading error',
    'nextjs',
    'MEDIUM',
    $$[{"solution": "Check syntax of next.config.js file. Verify all required modules are installed. Use valid JavaScript/TypeScript. Test require() calls in Node.js.", "percentage": 89, "note": "Syntax or module loading error in config file"}]$$::jsonb,
    'Next.js project with next.config.js',
    'Config loads successfully on build',
    'Syntax errors, missing dependencies in config, circular requires, invalid Node.js APIs',
    0.89,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/next-config-error'
),
(
    'Next.js error: Empty generateStaticParams with Cache',
    'nextjs',
    'MEDIUM',
    $$[{"solution": "Return at least one parameter set from generateStaticParams. Use fallback: true for ISR. Remove dynamic API calls or use dynamic rendering.", "percentage": 84, "note": "generateStaticParams returns empty with dynamic functions"}]$$::jsonb,
    'Next.js app with dynamic routes',
    'Static params generate successfully',
    'Empty array from generateStaticParams, accessing cookies/headers without fallback, missing param sets',
    0.84,
    'sonnet-4',
    NOW(),
    'https://nextjs.org/docs/messages/empty-generate-static-params'
);

-- ============================================
-- NPM ERRORS (14 entries)
-- ============================================

INSERT INTO knowledge_entries (
    query, category, hit_frequency, solutions, prerequisites, success_indicators,
    common_pitfalls, success_rate, claude_version, last_verified, source_url
) VALUES (
    'npm error: EACCES permission denied',
    'npm',
    'CRITICAL',
    $$[{"solution": "Fix npm permissions: mkdir ~/.npm-global && npm config set prefix ~/.npm-global && export PATH=~/.npm-global/bin:$PATH", "percentage": 95, "note": "Never use sudo with npm"}]$$::jsonb,
    'npm installed, user shell access',
    'npm install succeeds without sudo',
    'Using sudo npm install, running npm as root',
    0.95,
    'sonnet-4',
    NOW(),
    'https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally'
),
(
    'npm error: ELIFECYCLE command failed',
    'npm',
    'CRITICAL',
    $$[{"solution": "Delete node_modules and package-lock.json, then run npm cache clean --force && npm install", "percentage": 80, "note": "Check npm-debug.log for underlying issue"},{"solution": "Update Node.js and npm to latest stable versions", "percentage": 15}]$$::jsonb,
    'npm installed, Node.js installed',
    'npm scripts execute without ELIFECYCLE error',
    'Incomplete package cleanup, outdated npm/Node versions',
    0.80,
    'sonnet-4',
    NOW(),
    'https://docs.npmjs.com/common-errors/'
),
(
    'npm error: ENOTFOUND DNS lookup failed',
    'npm',
    'HIGH',
    $$[{"solution": "Check internet connection and DNS: ping 8.8.8.8", "percentage": 60},{"solution": "Configure npm registry: npm config set registry https://registry.npmjs.org/", "percentage": 25},{"solution": "Check npm-debug.log for actual registry URL", "percentage": 15}]$$::jsonb,
    'npm installed, internet access',
    'npm can resolve registry domain',
    'Misconfigured registry, network issues',
    0.70,
    'sonnet-4',
    NOW(),
    'https://docs.npmjs.com/common-errors/'
),
(
    'npm error: ECONNREFUSED connection refused',
    'npm',
    'HIGH',
    $$[{"solution": "Verify npm registry is accessible and not down", "percentage": 50},{"solution": "Check firewall/proxy settings: npm config set proxy null && npm config set https-proxy null", "percentage": 35},{"solution": "Try alternate registry or wait for npm registry recovery", "percentage": 15}]$$::jsonb,
    'npm installed, network access',
    'npm can connect to registry',
    'Proxy misconfiguration, registry outage',
    0.65,
    'sonnet-4',
    NOW(),
    'https://docs.npmjs.com/common-errors/'
),
(
    'npm error: EINTEGRITY package integrity mismatch',
    'npm',
    'CRITICAL',
    $$[{"solution": "Delete package-lock.json and node_modules, run npm cache clean --force && npm install", "percentage": 85, "note": "Validates packages on fresh install"},{"solution": "Use npm audit fix to correct dependency versions", "percentage": 10}]$$::jsonb,
    'npm installed, file system access',
    'npm install completes with valid package hashes',
    'Corrupted cache, partial downloads, network interruption',
    0.85,
    'sonnet-4',
    NOW(),
    'https://docs.npmjs.com/common-errors/'
),
(
    'npm error: ERR_SOCKET_HANG_UP socket hang up',
    'npm',
    'HIGH',
    $$[{"solution": "Increase npm timeout: npm config set fetch-timeout 120000", "percentage": 70, "note": "Useful for slow networks"},{"solution": "Retry install with --verbose flag to diagnose", "percentage": 20},{"solution": "Check network stability", "percentage": 10}]$$::jsonb,
    'npm installed, network access',
    'npm install succeeds with increased timeout',
    'Slow network, registry overload, short default timeout',
    0.75,
    'sonnet-4',
    NOW(),
    'https://docs.npmjs.com/common-errors/'
),
(
    'npm error: EAUDITNOLOCK no lock file for audit',
    'npm',
    'MEDIUM',
    $$[{"solution": "Generate package-lock.json: npm install --package-lock-only", "percentage": 95, "note": "Required before running npm audit"}]$$::jsonb,
    'npm installed, package.json exists',
    'package-lock.json created, npm audit runs',
    'Missing package-lock.json, running audit without lock',
    0.95,
    'sonnet-4',
    NOW(),
    'https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities/'
),
(
    'npm error: SSL UNABLE_TO_VERIFY_LEAF_SIGNATURE',
    'npm',
    'HIGH',
    $$[{"solution": "Update Node.js to version 0.8 or above (current minimum)", "percentage": 60},{"solution": "Workaround: npm config set ca \"\" or npm config set strict-ssl false", "percentage": 35, "note": "Only as temporary workaround"}]$$::jsonb,
    'Node.js installed, npm installed',
    'SSL certificate verification succeeds',
    'Outdated Node.js version, disabled SSL in production',
    0.70,
    'sonnet-4',
    NOW(),
    'https://docs.npmjs.com/common-errors/'
),
(
    'npm error: code 1 gyp build failure',
    'npm',
    'HIGH',
    $$[{"solution": "Install build tools: apt-get install build-essential python3 on Linux, or install XCode Command Line Tools on macOS", "percentage": 80, "note": "Required for native module compilation"},{"solution": "Update node-gyp: npm install -g node-gyp@latest", "percentage": 15}]$$::jsonb,
    'npm installed, Node.js with native module',
    'Package with native bindings installs successfully',
    'Missing build tools, outdated node-gyp, Python not in PATH',
    0.80,
    'sonnet-4',
    NOW(),
    'https://docs.npmjs.com/common-errors/'
),
(
    'npm error: ENOENT spawn failed',
    'npm',
    'MEDIUM',
    $$[{"solution": "Verify required executables exist in PATH: which <executable>", "percentage": 75},{"solution": "Check package.json scripts syntax for correct command names", "percentage": 20}]$$::jsonb,
    'npm installed, package.json with scripts',
    'npm run <script> executes without ENOENT',
    'Missing executable in PATH, typos in script names',
    0.75,
    'sonnet-4',
    NOW(),
    'https://docs.npmjs.com/common-errors/'
),
(
    'npm error: EAI_AGAIN getaddrinfo network error',
    'npm',
    'HIGH',
    $$[{"solution": "Check DNS and internet connectivity: ping registry.npmjs.org", "percentage": 60},{"solution": "Wait for temporary network issue to resolve", "percentage": 25},{"solution": "Retry with increased timeout settings", "percentage": 15}]$$::jsonb,
    'npm installed, network access',
    'npm can resolve registry hostname',
    'Temporary network issues, DNS misconfiguration',
    0.70,
    'sonnet-4',
    NOW(),
    'https://docs.npmjs.com/common-errors/'
),
(
    'npm error: 404 registry returned 401',
    'npm',
    'MEDIUM',
    $$[{"solution": "Verify npm authentication: npm login", "percentage": 70, "note": "Check .npmrc for valid token"},{"solution": "Check package scope and registry configuration", "percentage": 20},{"solution": "Ensure package exists in registry", "percentage": 10}]$$::jsonb,
    'npm installed, npm account',
    'npm can authenticate and access packages',
    'Expired or invalid auth token, wrong registry',
    0.75,
    'sonnet-4',
    NOW(),
    'https://docs.npmjs.com/common-errors/'
),
(
    'npm error: HTTP 402 scoped packages not paid',
    'npm',
    'MEDIUM',
    $$[{"solution": "Use --access=public flag: npm publish --access=public", "percentage": 85, "note": "For scoped packages without paid account"},{"solution": "Upgrade to paid npm account for private scoped packages", "percentage": 15}]$$::jsonb,
    'npm installed, npm account, scoped package',
    'npm publish succeeds with public access',
    'Attempting private scoped package without payment',
    0.85,
    'sonnet-4',
    NOW(),
    'https://docs.npmjs.com/common-errors/'
),
(
    'npm error: deprecated package warning',
    'npm',
    'LOW',
    $$[{"solution": "Check npm-debug.log for package name and update to recommended version", "percentage": 80, "note": "Not always breaking, but update recommended"},{"solution": "Use npm audit to find alternatives", "percentage": 20}]$$::jsonb,
    'npm installed, npm audit access',
    'Package updates to non-deprecated version',
    'Ignoring deprecation warnings in production',
    0.80,
    'sonnet-4',
    NOW(),
    'https://docs.npmjs.com/common-errors/'
);

-- ============================================
-- VERCEL ERRORS (12 entries)
-- ============================================

INSERT INTO knowledge_entries (
    query, category, hit_frequency, solutions, prerequisites, success_indicators,
    common_pitfalls, success_rate, claude_version, last_verified, source_url
) VALUES (
    'Vercel error: Build failed - command exited with code 1',
    'vercel',
    'CRITICAL',
    $$[{"solution": "Check build logs for specific error message. Run npm run build locally first to replicate issue. Verify all environment variables are set in Vercel dashboard under Project Settings → Environment Variables.", "percentage": 92, "note": "The last error line is often not the root cause; look several lines above in logs"}]$$::jsonb,
    'Vercel project configured, local build working',
    'Deployment succeeds, site accessible',
    'Missing environment variables, different Node/npm versions between local and Vercel, incorrect build command',
    0.92,
    'sonnet-4',
    NOW(),
    'https://vercel.com/docs/deployments/troubleshoot-a-build'
),
(
    'Vercel error: Function invocation failed with timeout',
    'vercel',
    'HIGH',
    $$[{"solution": "Check function execution time in logs. Optimize code to complete within time limit. For serverless: typical timeout 10s, for Edge Runtime use appropriate limits.", "percentage": 85}, {"solution": "Verify function dependencies are lightweight. Remove unnecessary packages that increase cold start time.", "percentage": 78}]$$::jsonb,
    'Function deployed to Vercel, access logs available',
    'Function executes and returns response within timeout',
    'Heavy dependencies causing slow cold starts, infinite loops in function code, external API calls without timeouts',
    0.85,
    'sonnet-4',
    NOW(),
    'https://vercel.com/docs/errors'
),
(
    'Vercel error: Module not found - build time syntax error',
    'vercel',
    'HIGH',
    $$[{"solution": "Verify import paths use correct case (case-sensitive on Linux/Vercel). Check file actually exists in project. Run npm ls to audit dependency tree.", "percentage": 88}, {"solution": "Ensure all dependencies in package.json are installed. Run npm install locally and redeploy with fresh cache using vercel --force.", "percentage": 81}]$$::jsonb,
    'Project builds locally successfully, package.json configured',
    'Build completes without module resolution errors',
    'Incorrect import case sensitivity, missing dependencies in package.json, circular dependencies, symlink issues',
    0.88,
    'sonnet-4',
    NOW(),
    'https://vercel.com/docs/deployments/troubleshoot-a-build'
),
(
    'Vercel error: Memory or disk space exceeded during build',
    'vercel',
    'MEDIUM',
    $$[{"solution": "Review framework and dependency memory usage. Reduce JavaScript bundle size by auditing heavy packages. Set VERCEL_BUILD_SYSTEM_REPORT=1 to identify culprits.", "percentage": 79}, {"solution": "Switch to more efficient bundlers (esbuild vs webpack). Remove unused dependencies and media files. Consider upgrading to Enterprise for custom limits.", "percentage": 72}]$$::jsonb,
    'Vercel build logs accessible, ability to modify vercel.json',
    'Build completes within resource limits, deployment succeeds',
    'Large media files in src directory, monorepo with multiple builds, undeclared devDependencies counted in build',
    0.79,
    'sonnet-4',
    NOW(),
    'https://vercel.com/docs/deployments/troubleshoot-a-build'
),
(
    'Vercel error: Build exceeded 45 minute timeout limit',
    'vercel',
    'MEDIUM',
    $$[{"solution": "Optimize Next.js build time: analyze with next/bundle-analyzer, enable swcMinify in next.config.js, split large bundles into dynamic chunks.", "percentage": 83}, {"solution": "Reduce dependencies by removing unused packages. Enable build caching by ensuring stable framework preset. Use pnpm for faster installs.", "percentage": 76}]$$::jsonb,
    'Next.js or framework project, ability to modify build config',
    'Build completes in under 30 minutes, deployment succeeds',
    'Unnecessary TypeScript checks, large build artifacts, unoptimized images, redundant dependencies',
    0.83,
    'sonnet-4',
    NOW(),
    'https://vercel.com/docs/deployments/troubleshoot-a-build'
),
(
    'Vercel error: Invalid vercel.json configuration',
    'vercel',
    'MEDIUM',
    $$[{"solution": "Validate vercel.json JSON syntax using jsonlint or IDE. Check for typos in top-level keys like buildCommand, installCommand, outputDirectory.", "percentage": 94}, {"solution": "Reference official schema at vercel.com/docs/project-configuration. Ensure environment variable names match exactly.", "percentage": 90}]$$::jsonb,
    'vercel.json file exists in project root',
    'Build logs appear and build proceeds past configuration validation',
    'JSON syntax errors (missing commas/brackets), incorrect key names, invalid environment variable references',
    0.94,
    'sonnet-4',
    NOW(),
    'https://vercel.com/docs/deployments/troubleshoot-a-build'
),
(
    'Vercel error: Build cache hit but deployment still fails',
    'vercel',
    'MEDIUM',
    $$[{"solution": "Skip build cache using Redeploy button with cache unchecked. Or use CLI: vercel --force. Or set VERCEL_FORCE_NO_BUILD_CACHE=1 environment variable.", "percentage": 87}, {"solution": "Verify framework preset matches actual framework. Cache key depends on preset selection. Change preset then redeploy to invalidate cache.", "percentage": 79}]$$::jsonb,
    'Deployment has previously succeeded, git repository configured',
    'Fresh build completes without cache, deployment succeeds',
    'Stale cache from previous successful deploy, framework preset mismatch between deployments',
    0.87,
    'sonnet-4',
    NOW(),
    'https://vercel.com/docs/deployments/troubleshoot-a-build'
),
(
    'Vercel error: DNS hostname not found / 502 Bad Gateway',
    'vercel',
    'HIGH',
    $$[{"solution": "Verify custom domain DNS records point to Vercel nameservers or CNAME. Check DNS propagation at nslookup or dig. Allow 24-48 hours for full propagation.", "percentage": 86}, {"solution": "If using external target routing, verify target API endpoint is accessible. Check CORS headers if calling from browser.", "percentage": 73}]$$::jsonb,
    'Domain registered and DNS access available',
    'Custom domain resolves to Vercel deployment, site loads without errors',
    'Incorrect CNAME records, DNS not yet propagated, external API target down or unreachable',
    0.86,
    'sonnet-4',
    NOW(),
    'https://vercel.com/docs/errors'
),
(
    'Vercel error: Git clone failed or deployment not triggered',
    'vercel',
    'MEDIUM',
    $$[{"solution": "Verify GitHub/GitLab authentication in Vercel account settings under Authentication. Re-authenticate if token expired. Check repository permissions.", "percentage": 89}, {"solution": "Ensure commit hook configuration is correct. Verify branch protection rules allow Vercel deployment checks. Check that commits are on configured branch (main/master).", "percentage": 81}]$$::jsonb,
    'Git repository configured in Vercel, account authenticated',
    'Commits trigger deployments automatically, build logs appear within seconds',
    'Expired OAuth tokens, incorrect branch configuration, repository no longer accessible, disabled webhook',
    0.89,
    'sonnet-4',
    NOW(),
    'https://vercel.com/guides/why-aren-t-commits-triggering-deployments-on-vercel'
),
(
    'Vercel error: Request header too large / URL too long',
    'vercel',
    'LOW',
    $$[{"solution": "Reduce custom header size and number. For URL too long: use POST requests with body instead of query parameters. Split long URLs into separate requests.", "percentage": 91}, {"solution": "Check for Authorization headers or cookies exceeding limits. Compress request payloads. Use URL shortening for tracking parameters.", "percentage": 84}]$$::jsonb,
    'Application handling HTTP requests, ability to modify request patterns',
    'Requests accepted and processed, no 431 or 414 errors in logs',
    'Large authentication tokens in headers, excessive query parameters, large cookie sets',
    0.91,
    'sonnet-4',
    NOW(),
    'https://vercel.com/docs/errors'
),
(
    'Vercel error: Missing build script in package.json',
    'vercel',
    'MEDIUM',
    $$[{"solution": "Add build script to package.json: npm run build must compile application to output directory. For Next.js use: \"build\": \"next build\".", "percentage": 95}, {"solution": "Verify framework preset is set correctly in Vercel dashboard. If preset is Other, build command cannot be empty. Set custom build command or select correct framework.", "percentage": 88}]$$::jsonb,
    'package.json file exists, framework installed as dependency',
    'Build script executes successfully, output directory created',
    'Build script not in package.json, using dev command instead of build command, incorrect output directory',
    0.95,
    'sonnet-4',
    NOW(),
    'https://vercel.com/docs/deployments/troubleshoot-a-build'
),
(
    'Vercel error: Environment variable not available at build time',
    'vercel',
    'HIGH',
    $$[{"solution": "Set environment variables in Vercel dashboard under Project Settings → Environment Variables. Select which environments (Production/Preview/Development) need the variable.", "percentage": 93}, {"solution": "For Next.js: prefix public variables with NEXT_PUBLIC_. Redeploy after adding variables. Use vercel env pull to sync to local .env.local.", "percentage": 89}]$$::jsonb,
    'Project deployed on Vercel, access to project settings',
    'Variables available during build, application builds without undefined variable errors',
    'Variables set only for Production when needed in Preview, private vars exposed to client, missing NEXT_PUBLIC_ prefix',
    0.93,
    'sonnet-4',
    NOW(),
    'https://vercel.com/docs/projects/environment-variables'
);

-- ============================================
-- TYPESCRIPT ERRORS (14 entries)
-- ============================================

INSERT INTO knowledge_entries (
    query, category, hit_frequency, solutions, prerequisites, success_indicators,
    common_pitfalls, success_rate, claude_version, last_verified, source_url
) VALUES (
    'TypeScript error: TS2322 Type X is not assignable to type Y',
    'typescript',
    'CRITICAL',
    $$[{"solution": "Check type definitions match. Use type assertion if certain: value as Type. Add proper type annotations to variables.", "percentage": 88, "note": "Most common TS error"}]$$::jsonb,
    'TypeScript project, tsconfig.json configured',
    'tsc compiles without type errors',
    'Using any type to bypass, ignoring strict mode',
    0.88,
    'sonnet-4',
    NOW(),
    'https://www.typescriptlang.org/docs/handbook/2/everyday-types.html'
),
(
    'TypeScript error: TS2339 Property does not exist on type',
    'typescript',
    'CRITICAL',
    $$[{"solution": "Verify property name spelling. Check object type definition. Add missing properties to interface. Use optional chaining (?.) for potentially undefined values.", "percentage": 85, "note": "Property access error"}]$$::jsonb,
    'TypeScript project with strict property checking',
    'Property access resolves without errors',
    'Typos in property names, missing type definitions',
    0.85,
    'sonnet-4',
    NOW(),
    'https://www.typescriptlang.org/docs/handbook/2/everyday-types.html'
),
(
    'TypeScript error: TS2345 Argument of type X is not assignable to parameter of type Y',
    'typescript',
    'CRITICAL',
    $$[{"solution": "Check function parameter types match arguments. Use correct types for function calls. Add type annotations to parameters. Use function overloads for multiple signatures.", "percentage": 82, "note": "Function argument mismatch"}]$$::jsonb,
    'TypeScript project with function type checking',
    'Function calls compile without type errors',
    'Passing wrong types to functions, missing parameter types',
    0.82,
    'sonnet-4',
    NOW(),
    'https://www.typescriptlang.org/docs/handbook/2/functions.html'
),
(
    'TypeScript error: TS2307 Cannot find module or namespace',
    'typescript',
    'CRITICAL',
    $$[{"solution": "Check import paths are correct. Verify module exists. Install missing packages. Update tsconfig paths. Check case sensitivity in filenames.", "percentage": 80, "note": "Module resolution error"}]$$::jsonb,
    'TypeScript project with module resolution configured',
    'All imports resolve successfully',
    'Wrong import paths, missing node_modules, case sensitivity issues',
    0.80,
    'sonnet-4',
    NOW(),
    'https://www.typescriptlang.org/docs/handbook/module-resolution.html'
),
(
    'TypeScript error: TS1005 Expected declaration or statement',
    'typescript',
    'HIGH',
    $$[{"solution": "Check for syntax errors like missing semicolons or braces. Verify proper function/class declaration syntax. Look for mismatched parentheses or brackets.", "percentage": 78, "note": "Syntax error"}]$$::jsonb,
    'TypeScript file with proper compiler setup',
    'File parses without syntax errors',
    'Missing semicolons, unclosed brackets, malformed declarations',
    0.78,
    'sonnet-4',
    NOW(),
    'https://www.typescriptlang.org/docs/handbook/2/basic-types.html'
),
(
    'TypeScript error: TS2748 Type parameter has no default type',
    'typescript',
    'HIGH',
    $$[{"solution": "Provide type argument explicitly or add default type to generic. Use <Type> syntax when calling generic functions. Define default in type parameter declaration.", "percentage": 76, "note": "Generic type error"}]$$::jsonb,
    'TypeScript project using generics',
    'Generic functions and classes resolve correctly',
    'Missing type arguments, incomplete generic declarations',
    0.76,
    'sonnet-4',
    NOW(),
    'https://www.typescriptlang.org/docs/handbook/2/generics.html'
),
(
    'TypeScript error: TS2564 Property has no initializer and is not definitely assigned',
    'typescript',
    'HIGH',
    $$[{"solution": "Initialize property in constructor. Use definite assignment assertion (!). Add optional property marker (?). Enable strictNullChecks to verify.", "percentage": 81, "note": "Property initialization error"}]$$::jsonb,
    'TypeScript with strictPropertyInitialization enabled',
    'All properties properly initialized',
    'Skipping constructor initialization, undefined property access',
    0.81,
    'sonnet-4',
    NOW(),
    'https://www.typescriptlang.org/docs/handbook/2/classes.html'
),
(
    'TypeScript error: TS2655 Object does not have property with matching type',
    'typescript',
    'MEDIUM',
    $$[{"solution": "Verify object property exists and matches type. Use keyof operator for type-safe property access. Check mapped types. Use type guards.", "percentage": 73, "note": "Index signature mismatch"}]$$::jsonb,
    'TypeScript with index signatures and mapped types',
    'Object property access compiles without errors',
    'Accessing non-existent mapped properties, type mismatches',
    0.73,
    'sonnet-4',
    NOW(),
    'https://www.typescriptlang.org/docs/handbook/2/objects.html'
),
(
    'TypeScript error: TS2371 Cannot reassign const variable',
    'typescript',
    'MEDIUM',
    $$[{"solution": "Use let instead of const for mutable variables. Create new variable with different name. Use object spread to modify immutable objects.", "percentage": 90, "note": "Variable mutability error"}]$$::jsonb,
    'TypeScript project with variable declarations',
    'Variable assignments work as expected',
    'Attempting to reassign const, confusion between let/const/var',
    0.90,
    'sonnet-4',
    NOW(),
    'https://www.typescriptlang.org/docs/handbook/2/everyday-types.html'
),
(
    'TypeScript error: TS2430 Interface declares a non-method property that must be initialized',
    'typescript',
    'MEDIUM',
    $$[{"solution": "Initialize property in constructor. Make property optional with ?. Use readonly keyword. Move to class instead of interface.", "percentage": 79, "note": "Interface property initialization"}]$$::jsonb,
    'TypeScript with interface definitions',
    'Classes implementing interfaces compile successfully',
    'Interface properties without initialization, missing constructor',
    0.79,
    'sonnet-4',
    NOW(),
    'https://www.typescriptlang.org/docs/handbook/2/objects.html'
),
(
    'TypeScript error: TS2559 Type has no properties in common with type',
    'typescript',
    'MEDIUM',
    $$[{"solution": "Check types are compatible. Use intersection (&) to combine types. Add shared properties. Use union (|) carefully. Verify inheritance chain.", "percentage": 75, "note": "Type incompatibility error"}]$$::jsonb,
    'TypeScript with structural typing',
    'Type assignments work as expected',
    'Incompatible type assignments, missing property overlap',
    0.75,
    'sonnet-4',
    NOW(),
    'https://www.typescriptlang.org/docs/handbook/2/types-from-types.html'
),
(
    'TypeScript error: TS2367 This comparison appears to be unintentional',
    'typescript',
    'MEDIUM',
    $$[{"solution": "Use correct comparison operators (=== not ==). Fix typos in comparisons. Add type assertions if intentional. Enable strictNullChecks.", "percentage": 84, "note": "Logic error detection"}]$$::jsonb,
    'TypeScript with strict equality checking',
    'Comparisons are logically correct',
    'Using == instead of ===, typos in boolean checks',
    0.84,
    'sonnet-4',
    NOW(),
    'https://www.typescriptlang.org/docs/handbook/2/narrowing.html'
),
(
    'TypeScript error: TS2769 Overload not found matching call signature',
    'typescript',
    'MEDIUM',
    $$[{"solution": "Add matching function overload. Check parameter types against all overloads. Use type assertions carefully. Verify call matches one overload signature.", "percentage": 71, "note": "Function overload mismatch"}]$$::jsonb,
    'TypeScript with function overloads',
    'Function calls match available overloads',
    'Missing overload signatures, type mismatches in overloads',
    0.71,
    'sonnet-4',
    NOW(),
    'https://www.typescriptlang.org/docs/handbook/2/functions.html'
),
(
    'TypeScript error: TS7015 Element implicitly has type any when index expression is of type any',
    'typescript',
    'HIGH',
    $$[{"solution": "Add explicit type annotation for index. Use string or number literals for keys. Avoid dynamic indexing with any. Enable noImplicitAny setting.", "percentage": 77, "note": "Implicit any detection"}]$$::jsonb,
    'TypeScript with noImplicitAny enabled',
    'Array and object indexing type-safe',
    'Using any for indexing, missing key type definitions',
    0.77,
    'sonnet-4',
    NOW(),
    'https://www.typescriptlang.org/docs/handbook/2/basic-types.html'
);

-- ============================================
-- WEBPACK ERRORS (12 entries)
-- ============================================

INSERT INTO knowledge_entries (
    query, category, hit_frequency, solutions, prerequisites, success_indicators,
    common_pitfalls, success_rate, claude_version, last_verified, source_url
) VALUES (
    'Webpack error: Cannot resolve module - Module not found',
    'webpack',
    'CRITICAL',
    $$[{"solution": "Check import path spelling and capitalization. Verify module is installed with npm install. Add file extensions in imports (.js, .json). Configure resolve.extensions in webpack.config.js", "percentage": 92, "note": "Most common webpack error"}]$$::jsonb,
    'Webpack configured, package.json exists',
    'Webpack build succeeds without module resolution errors',
    'Wrong file path, missing file extension, typo in import path, module not installed',
    0.92,
    'sonnet-4',
    NOW(),
    'https://webpack.js.org/configuration/resolve/'
),
(
    'Webpack error: Unknown file extension .ts in webpack.config.ts',
    'webpack',
    'CRITICAL',
    $$[{"solution": "Run webpack with ts-node ESM loader: NODE_OPTIONS=\"--loader ts-node/esm\" npx webpack. Alternatively, rename config to .js and use require() or use a TypeScript loader setup", "percentage": 88, "note": "TypeScript config loading error"}]$$::jsonb,
    'TypeScript installed, webpack-cli v6+, Node 18.12.0+',
    'Webpack config loads without file extension errors',
    'Missing ts-node, incompatible Node version, incorrect tsconfig.json',
    0.88,
    'sonnet-4',
    NOW(),
    'https://webpack.js.org/api/cli/'
),
(
    'Webpack error: All exit codes and configuration issues',
    'webpack',
    'HIGH',
    $$[{"solution": "Exit code 0 = success, Exit code 1 = webpack compilation errors, Exit code 2 = CLI/config errors. Check webpack.config.js syntax, verify Node version meets minimum (18.12.0+), ensure webpack and webpack-cli versions match", "percentage": 85}]$$::jsonb,
    'webpack-cli v6.0.0+, Node v18.12.0+, webpack v5.82.0+',
    'Build runs and returns appropriate exit code',
    'Incompatible versions, syntax errors in config, outdated dependencies',
    0.85,
    'sonnet-4',
    NOW(),
    'https://webpack.js.org/api/cli/'
),
(
    'Webpack error: Loader configuration and parser errors',
    'webpack',
    'HIGH',
    $$[{"solution": "Ensure loaders are in correct order (right-to-left execution). Check loader package is installed. Verify test regex matches files. Configure parser options correctly: true enables, false disables. Use Rule.parser to target specific modules", "percentage": 87}]$$::jsonb,
    'Webpack configured with module rules, loaders installed',
    'Loaders execute without parse errors, files transform correctly',
    'Wrong loader order, loader not installed, incorrect test regex, parser conflicts',
    0.87,
    'sonnet-4',
    NOW(),
    'https://webpack.js.org/configuration/module/'
),
(
    'Webpack error: Output path contains exclamation mark or special characters',
    'webpack',
    'MEDIUM',
    $$[{"solution": "Remove special characters (especially !) from output.path. Use absolute paths with path.resolve(__dirname, ...). Do not use tokens like [hash] in output.path, only in output.filename", "percentage": 90}]$$::jsonb,
    'webpack.config.js exists with output configuration',
    'Bundles emit to correct output directory without errors',
    'Path with ! character, relative paths instead of absolute, special characters in path',
    0.90,
    'sonnet-4',
    NOW(),
    'https://webpack.js.org/configuration/output/'
),
(
    'Webpack error: publicPath not set correctly for CDN or subdirectory',
    'webpack',
    'MEDIUM',
    $$[{"solution": "Set output.publicPath to the public URL of your assets: publicPath: \"/assets/\" for subdirectory or publicPath: \"https://cdn.example.com/\" for CDN. Trailing slash required. Test with browser DevTools Network tab", "percentage": 84}]$$::jsonb,
    'Application deployed or running locally, webpack configured',
    'Assets load correctly in browser, Network tab shows correct URLs',
    'Missing trailing slash, wrong domain, relative path instead of absolute',
    0.84,
    'sonnet-4',
    NOW(),
    'https://webpack.js.org/configuration/output/'
),
(
    'Webpack error: Dev server not starting or connection issues',
    'webpack',
    'HIGH',
    $$[{"solution": "Verify webpack-dev-server v5+ installed. Check port is available (default 9000). Enable HMR: hot: true in config. Check devServer.static.directory points to valid path. Use npx webpack serve to start server", "percentage": 86}]$$::jsonb,
    'webpack-dev-server v5.0.0+, webpack v5+, Node 18.12.0+',
    'Dev server starts and accepts requests on specified port',
    'Port already in use, wrong directory path, HMR misconfigured, outdated dev-server',
    0.86,
    'sonnet-4',
    NOW(),
    'https://webpack.js.org/configuration/dev-server/'
),
(
    'Webpack error: Code splitting chunks exceed maxSize threshold',
    'webpack',
    'MEDIUM',
    $$[{"solution": "Configure splitChunks.maxSize to split large chunks. Set minSize below maxSize. Use cacheGroups to separate vendor code: test: /[\\\\/]node_modules[\\\\/]/. Reduce bundle size by removing unused dependencies", "percentage": 82}]$$::jsonb,
    'Webpack configured with optimization.splitChunks',
    'Chunks generated under maxSize threshold, build succeeds',
    'maxSize smaller than minSize, modules impossible to split further, large dependencies',
    0.82,
    'sonnet-4',
    NOW(),
    'https://webpack.js.org/plugins/split-chunks-plugin/'
),
(
    'Webpack error: Cache directory permissions or corruption',
    'webpack',
    'MEDIUM',
    $$[{"solution": "Clear cache: rm -rf node_modules/.cache/webpack. Verify write permissions on cache directory. Set cache.type: \"filesystem\" with valid cacheDirectory path. Check available disk space. Use cache.compression: \"gzip\" to reduce size", "percentage": 88}]$$::jsonb,
    'Webpack configured with cache option, node_modules writable',
    'Cache writes successfully, builds faster on second run',
    'No write permissions, full disk, corrupted cache files, incompatible Node version',
    0.88,
    'sonnet-4',
    NOW(),
    'https://webpack.js.org/configuration/cache/'
),
(
    'Webpack error: Plugin configuration or lifecycle hooks',
    'webpack',
    'HIGH',
    $$[{"solution": "Install plugin package: npm install plugin-name. Check plugin documentation for correct configuration options. Ensure plugin is added to plugins array. Verify plugin is compatible with webpack version. Check plugin runs on correct compiler hook", "percentage": 85}]$$::jsonb,
    'Webpack configured, plugins array exists, plugin package available',
    'Plugins execute without errors, expected transformations applied',
    'Plugin not installed, wrong configuration format, incompatible webpack version, wrong hook',
    0.85,
    'sonnet-4',
    NOW(),
    'https://webpack.js.org/plugins/'
),
(
    'Webpack error: Resolve alias or module resolution failing',
    'webpack',
    'MEDIUM',
    $$[{"solution": "Configure resolve.alias with path.resolve: alias: { Utilities: path.resolve(__dirname, \"src/utilities/\") }. Use absolute paths. Test with import statements. Check resolve.modules includes node_modules. Verify extensions in resolve.extensions", "percentage": 89}]$$::jsonb,
    'Webpack configured with resolve options',
    'Imports resolve correctly with aliases, no module not found errors',
    'Relative paths in alias, wrong directory, missing resolve.extensions, typo in alias name',
    0.89,
    'sonnet-4',
    NOW(),
    'https://webpack.js.org/configuration/resolve/'
),
(
    'Webpack error: Source map configuration or generation failure',
    'webpack',
    'MEDIUM',
    $$[{"solution": "Set devtool to source map option: \"source-map\" for production, \"eval-source-map\" for development. Check permissions on output directory. Verify devtoolModuleFilenameTemplate if needed. Disable in production for performance", "percentage": 83}]$$::jsonb,
    'Webpack configured with devtool option',
    'Source maps generate and map errors to original source, debugging works',
    'Wrong devtool value, missing output directory, production build too large',
    0.83,
    'sonnet-4',
    NOW(),
    'https://webpack.js.org/configuration/output/'
);
