INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('migration error: found 21 errors in 11 files', 'orm', 'HIGH', '[{"solution": "Update drizzle-orm dependencies to latest version using npm update --save", "percentage": 95}, {"solution": "Set skipLibCheck: true in tsconfig.json as temporary workaround (not recommended)", "percentage": 40}]'::jsonb, 'drizzle-orm and drizzle-kit installed', 'Migration completes without type errors', 'Not updating dependencies; importing schema incorrectly', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/78491501/drizzle-postgres-migration-gives-lots-of-type-errors', 'admin:1764228519'),

('Property does not exist on type Record<string, unknown>', 'orm', 'HIGH', '[{"solution": "Pass schema definition when declaring drizzle type: ReturnType<typeof drizzle<typeof schema>>", "percentage": 98}, {"solution": "Use spread operator when importing schema: import * as schema from path", "percentage": 95}]'::jsonb, 'TypeScript 4.5+, drizzle-orm', 'No type errors on schema access', 'Directly instantiating db without schema type parameter', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/79548764/why-does-drizzle-orm-with-typescript-not-recognize-my-schema-and-show-missing-pr', 'admin:1764228519'),

('TypeError: Cannot read property of undefined with zod validation', 'orm', 'MEDIUM', '[{"solution": "Use z.merge() to override field types: baseSchema.merge(z.object({amount: z.number().optional()}))", "percentage": 92}, {"solution": "Use safeParse instead of parse to avoid stripping unspecified properties", "percentage": 88}]'::jsonb, 'Zod v3+, drizzle-orm', 'Zod validation passes, field is optional or required correctly', 'Not understanding Zod parse behavior; trying to remove fields instead of making optional', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/76813492/typescript-type-error-with-drizzle-orm-and-zod-validation', 'admin:1764228519'),

('ERESOLVE could not resolve - peer dependency conflict with react', 'orm', 'MEDIUM', '[{"solution": "Run npm update --save && npm update --save-dev, then npm install drizzle-orm", "percentage": 96}, {"solution": "Update react to ^18.3.1 and react-dom to ^18.3.1 in package.json", "percentage": 94}]'::jsonb, 'npm 7+, Node.js 16+', 'npm install completes without ERESOLVE errors', 'Using --legacy-peer-deps instead of updating dependencies', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/78412358/i-am-getting-an-error-when-install-the-drizzle-orm-npm-package-in-a-nextjs-14-a', 'admin:1764228519'),

('Auto rollback not working - transaction not rolling back on error', 'orm', 'MEDIUM', '[{"solution": "Drizzle auto-rollbacks on uncaught exceptions; throw error without calling tx.rollback()", "percentage": 98}, {"solution": "Ensure error is thrown within transaction try-catch block", "percentage": 96}]'::jsonb, 'drizzle-orm 0.25+, PostgreSQL driver', 'Transaction rolls back when error is thrown', 'Manually calling tx.rollback() then throwing error (redundant)', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/78784936/does-drizzle-orm-auto-rollbacks-when-there-is-an-exception-or-do-i-need-to-call', 'admin:1764228519'),

('PostgresError: Tenant or user not found when running drizzle push', 'orm', 'MEDIUM', '[{"solution": "Use simple connectionString in drizzle.config without host/port/user details: url: process.env.DATABASE_URL", "percentage": 97}, {"solution": "Include schema name in DATABASE_URL: postgres://user:pass@host:port/db-name", "percentage": 95}]'::jsonb, 'Supabase PostgreSQL, drizzle-kit 0.20+', 'drizzle push command succeeds', 'Overspecifying connection details instead of using connection string', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/78602935/having-issues-with-drizzle-kit-and-postgress-push-command', 'admin:1764228519'),

('Unterminated comment error - drizzle migration with block comments', 'orm', 'MEDIUM', '[{"solution": "Convert /* */ block comments to -- line comments in migration files", "percentage": 99}, {"solution": "Remove auto-generated comment block at top of migration file before running", "percentage": 87}]'::jsonb, 'drizzle-orm 0.25+, PostgreSQL', 'Migration executes without syntax errors', 'Using block comments in generated migrations; not removing auto-generated comment section', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/78576278/how-can-i-tell-drizzle-if-a-migration-is-considered-done-when-migrating-from', 'admin:1764228519'),

('No schema has been selected to create in', 'orm', 'MEDIUM', '[{"solution": "Include database schema in connectionString: postgres://user@host/schema", "percentage": 96}, {"solution": "Explicitly specify schema in pool config or connection string", "percentage": 94}]'::jsonb, 'drizzle-orm 0.25+, PostgreSQL', 'Tables created successfully in target schema', 'Using incomplete connection string without schema name', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/76095697/drizzle-orm-with-postgres-error-unhandledrejection-error-no-schema-has-been', 'admin:1764228519'),

('Self-reference foreign key TypeScript error implicitly has type any', 'orm', 'MEDIUM', '[{"solution": "Use AnyPgColumn type for self-reference: .references((): AnyPgColumn => contractsTable.id)", "percentage": 96}, {"solution": "Define foreign key in table callback: foreignKey({columns: [table.id], foreignColumns: [table.id]})", "percentage": 94}]'::jsonb, 'TypeScript 4.5+, drizzle-orm 0.25+', 'Self-referencing FK compiles without type errors', 'Direct table reference in FK before table fully defined', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/78329576/how-to-declare-self-referencing-foreign-key-with-drizzle-orm', 'admin:1764228519'),

('Foreign key constraints are not allowed - PlanetScale/Vitess limitation', 'orm', 'MEDIUM', '[{"solution": "Use ULID instead of auto-increment IDs for sharded databases", "percentage": 89}, {"solution": "Remove foreign key constraints and implement referential integrity in application layer", "percentage": 85}]'::jsonb, 'PlanetScale MySQL, drizzle-orm 0.25+', 'Schema deploys without FK constraint errors', 'Using auto-increment IDs with foreign keys on sharded database', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/76559107/foreign-key-constraints-not-allowed-using-drizzle-orm', 'admin:1764228519'),

('Foreign key column type mismatch - text vs uuid', 'orm', 'MEDIUM', '[{"solution": "Ensure FK column type matches referenced column type exactly: userId uuid matches users.id uuid", "percentage": 98}, {"solution": "Check all related tables for type consistency in FK relationships", "percentage": 96}]'::jsonb, 'PostgreSQL 12+, drizzle-orm 0.25+', 'Schema push succeeds without type mismatch errors', 'Mixing text and uuid types in related FK columns', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/78056425/drizzle-orm-cannot-push-schema-due-to-fk-type-mismatch', 'admin:1764228519'),

('Cannot read properties of undefined reading referencedTable', 'orm', 'HIGH', '[{"solution": "Import relations in schema object: schema: { ...schema, ...relations }", "percentage": 97}, {"solution": "Use import * as schema from path and pass as single schema object", "percentage": 98}]'::jsonb, 'drizzle-orm 0.25+', 'Relational queries execute without undefined errors', 'Not importing relation definitions into drizzle config; spreading tables only', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/78685124/drizzle-creating-relational-queries-and-undefined-referencedtable-error', 'admin:1764228519'),

('Relation name mismatch in query - query uses different relation name than schema', 'orm', 'HIGH', '[{"solution": "Use exact relation name from schema definition: if schema defines permission, use with: {permission: true}", "percentage": 99}, {"solution": "Verify plural vs singular relation names match between schema and query", "percentage": 98}]'::jsonb, 'drizzle-orm 0.25+', 'Relational query executes and returns related data', 'Mismatching relation names between definitions and queries', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/77780541/how-to-declare-and-query-with-relations-using-drizzle', 'admin:1764228519'),

('Cannot read property findMany of empty object', 'orm', 'HIGH', '[{"solution": "Import relations in db config: schema: {...schema, ...relations}", "percentage": 97}, {"solution": "Define relation with correct table references before querying", "percentage": 96}]'::jsonb, 'drizzle-orm 0.25+', 'db.query.tableName.findMany() returns results', 'Missing relation imports in drizzle initialization', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/78177831/drizzle-db-query-throwing-undefined-is-not-an-object-evaluating-relation-refe', 'admin:1764228519'),

('Relation fields mismatch - wrong field in relation definition', 'orm', 'MEDIUM', '[{"solution": "Ensure relation fields point to correct columns: fields: [users.id], references: [permissions.userId]", "percentage": 98}, {"solution": "Verify relation name in query matches relation name in schema", "percentage": 97}]'::jsonb, 'drizzle-orm 0.25+', 'Relational query loads related records successfully', 'Mismatching field references in relation definition', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/77698366/how-to-resolve-drizzle-orm-mysql-relations-type-error', 'admin:1764228519'),

('Bind message supplies parameters but prepared statement requires different count', 'orm', 'MEDIUM', '[{"solution": "Remove quotes around template variables: sql`condition = ${param}` not sql`condition = ''${param}''`", "percentage": 99}, {"solution": "Use sql template tag correctly - parameters are auto-parameterized", "percentage": 98}]'::jsonb, 'drizzle-orm 0.25+, PostgreSQL', 'Query executes with correct parameter binding', 'Over-quoting template variables in sql tagged templates', 0.98, 'haiku', NOW(), 'https://stackoverflow.com/questions/78253923/drizzle-orm-postgres-error-bind-message-supplies-1-parameters-but-prepared-st', 'admin:1764228519'),

('HASH index not supported - cannot create HASH index with Drizzle', 'orm', 'LOW', '[{"solution": "Use sql raw definition for custom index types: sql`CREATE INDEX ... USING HASH`", "percentage": 85}, {"solution": "Upgrade to drizzle-orm 0.31+ for advanced index support", "percentage": 90}]'::jsonb, 'drizzle-orm 0.25+, PostgreSQL', 'Custom index creates successfully in database', 'Using unsupported index method; not upgrading Drizzle version', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/78549337/drizzle-orm-creating-hash-index-on-table', 'admin:1764228519'),

('No unique or exclusion constraint matching ON CONFLICT specification', 'orm', 'MEDIUM', '[{"solution": "Use uniqueIndex() not unique(): uniqueIndex(''name'').on(col1, col2)", "percentage": 97}, {"solution": "Pass column array to onConflictDoUpdate target: target: [table.col1, table.col2]", "percentage": 96}]'::jsonb, 'PostgreSQL 15+, drizzle-orm 0.25+', 'onConflictDoUpdate executes without constraint errors', 'Using unique() instead of uniqueIndex(); wrong target syntax', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/78233343/drizzleorm-use-a-unique-index-in-conflict-updates', 'admin:1764228519'),

('TypeError: Could not determine data type of parameter', 'orm', 'MEDIUM', '[{"solution": "Use sql template tag for string interpolation instead of plain quotes: sql`%''||${search}||''%`", "percentage": 94}, {"solution": "Ensure parameter types match expected SQL types", "percentage": 92}]'::jsonb, 'PostgreSQL 12+, drizzle-orm 0.25+', 'Query executes and returns results with correct type inference', 'Mixing template variables with raw SQL strings incorrectly', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/78850094/getting-error-could-not-determine-data-type-of-parameter-1-when-using-drizzl', 'admin:1764228519'),

('Type safety issue on insert with optional columns', 'orm', 'MEDIUM', '[{"solution": "Mark optional columns with .notNull() or provide default values on all columns", "percentage": 92}, {"solution": "Use .optional() on schema definition for truly optional insert fields", "percentage": 90}]'::jsonb, 'TypeScript 4.7+, drizzle-orm 0.25+', 'Insert operations type-check correctly', 'Leaving required columns undefined in insert values', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/78601814/type-safety-issue-when-trying-to-insert-into-a-table-using-drizzle', 'admin:1764228519'),

('No database connection string provided to neon()', 'orm', 'HIGH', '[{"solution": "Add DATABASE_URL environment variable to .env file: DATABASE_URL=postgres://user:pass@host/db", "percentage": 99}, {"solution": "Initialize drizzle before querying: const db = drizzle(neon(process.env.DATABASE_URL))", "percentage": 98}]'::jsonb, 'Neon PostgreSQL, drizzle-orm 0.25+', 'Database connection establishes successfully', 'Missing environment variable; not passing connection string to driver', 0.99, 'haiku', NOW(), 'https://stackoverflow.com/questions/78685124/drizzle-creating-relational-queries-and-undefined-referencedtable-error', 'admin:1764228519'),

('Column already exists error on migration', 'orm', 'MEDIUM', '[{"solution": "Roll back tables and reapply entire migration with new changes included", "percentage": 94}, {"solution": "Manually remove conflicting column before applying migration", "percentage": 85}]'::jsonb, 'PostgreSQL 12+, drizzle-kit 0.20+', 'Migration applies without column already exists errors', 'Running migrations with duplicate column additions without cleanup', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/78735892/drizzle-kit-migration-and-pushing', 'admin:1764228519'),

('Password authentication failed for user postgres', 'orm', 'MEDIUM', '[{"solution": "Use correct credentials in DATABASE_URL: correct username, password, and host", "percentage": 98}, {"solution": "Migrate to correct database instance (use prod/staging URL not local)", "percentage": 96}]'::jsonb, 'PostgreSQL 12+, drizzle-orm 0.25+', 'Migration connects and completes successfully', 'Using wrong database credentials or targeting wrong instance', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/78174364/error-password-authentication-failed-for-user-postgres-drizzle-migration', 'admin:1764228519');
