-- Auth Deadlock Knowledge Base Entries
-- Mined from Stack Overflow - 2025-11-26

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Deadlock found when trying to get lock; try restarting transaction - oauth_access_token', 'authentication', 'HIGH', '[{"solution": "Add unique constraint on token_id in oauth_access_token table to prevent concurrent duplicate tokens. Extend JdbcTokenStore with error handling to catch and clean up corrupted records.", "percentage": 95}, {"solution": "Implement request-level locking mechanism to serialize oauth/token requests", "percentage": 75}, {"solution": "Use database connection pooling with appropriate transaction isolation levels", "percentage": 70}]'::jsonb, 'Spring Security OAuth2, MySQL database, understanding of JDBC token store', 'Deadlock exceptions no longer occur when multiple concurrent /oauth/token requests hit different server nodes. Token counts remain stable without duplicates.', 'Not adding unique constraint and just retrying the transaction. Ignoring the concurrent request timing issue. Not extending error handling in token store cleanup.', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/47870548/spring-oauth2-concurrent-request-deadlock', 'admin:1764191954');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Application deadlock while acquiring token for Azure AD - AcquireTokenByIntegratedWindowsAuth', 'authentication', 'HIGH', '[{"solution": "Wrap token acquisition in a separate Thread instead of calling Task.Result directly on async method. Use Thread.Join() to wait for completion.", "percentage": 90}, {"solution": "Use async all the way - avoid .Result on async calls which causes deadlock", "percentage": 88}, {"solution": "Implement token caching with background refresh to avoid blocking main thread", "percentage": 75}]'::jsonb, 'MSAL library for Azure AD, understanding of async/await and Task deadlock patterns', 'Token is acquired without application freeze. Subsequent requests complete normally without deadlock. Authorization header is set correctly on HttpClient.', 'Using Task.Result directly on async methods. Not implementing token expiration checks. Creating multiple PublicClientApplication instances without caching.', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/73622571/deadlock-while-acquiring-azure-ad-token', 'admin:1764191954');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('SQL Error 1213 SQLState 40001 Deadlock found - Keycloak federated user role management', 'authentication', 'HIGH', '[{"solution": "Serialize concurrent role queries by implementing request-level locks on user entities. Avoid parallel /role-mappings API calls for same user.", "percentage": 89}, {"solution": "Use database connection pooling with READ_UNCOMMITTED isolation to reduce lock contention", "percentage": 72}, {"solution": "Batch role queries into single endpoint call instead of 4+ parallel requests", "percentage": 85}]'::jsonb, 'Keycloak 12.0.2+, MySQL, User Storage SPI implementation, understanding of Hibernate transaction handling', 'Role mappings can be queried and updated without deadlock errors. User entity updates complete successfully. Admin console role management tab responds normally.', 'Allowing client to send parallel role-mapping requests. Not implementing server-side request batching. Using default transaction isolation levels without adjustment.', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/66229088/keycloak-db-deadlock-when-managing-roles-for-federated-users', 'admin:1764191954');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Zend session locked during long-running processes - hasIdentity triggers session_start', 'authentication', 'HIGH', '[{"solution": "Switch from file-based sessions to database-backed sessions using Zend_Session_SaveHandler_DbTable to eliminate file locks", "percentage": 92}, {"solution": "Use memcached for session storage instead of files - eliminates lock contention entirely", "percentage": 90}, {"solution": "Explicitly call session_write_close() after auth check, then session_start() when needed in controller", "percentage": 70}]'::jsonb, 'Zend Framework, PHP sessions, understanding of file locking behavior', 'Multiple concurrent requests complete without blocking. Session data persists across requests. Long-running processes don''t lock other requests.', 'Relying on file-based sessions for high-concurrency scenarios. Not closing sessions after auth checks. Trying to resume sessions without proper restart sequence.', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/3760926/zend-auth-locked-session', 'admin:1764191954');

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES
('Deadlock while acquiring OAuth token - Salesforce login loop after Heroku account link', 'authentication', 'MEDIUM', '[{"solution": "Break OAuth redirect loop by implementing state parameter validation and session-based login flow instead of multi-step redirects", "percentage": 87}, {"solution": "Cache OAuth token with refresh token to avoid re-requesting on every auth check", "percentage": 82}, {"solution": "Implement exponential backoff retry logic for OAuth token acquisition failures", "percentage": 75}]'::jsonb, 'Heroku OAuth, Salesforce login integration, understanding of OAuth state parameter, session management', 'Heroku account access restored without login loop. OAuth flow completes in single redirect. User session maintains across Salesforce and Heroku domains.', 'Attempting multiple simultaneous OAuth token requests. Not validating state parameter between redirects. Not caching tokens between requests.', 0.83, 'haiku', NOW(), 'https://stackoverflow.com/questions/79662139/cannot-access-heroku-account-due-to-salesforce-login-loop-oauth-deadlock-after', 'admin:1764191954');
