-- tRPC Errors Mining - 20 entries
-- Mined from Stack Overflow with detailed solutions

INSERT INTO knowledge_entries (query, category, hit_frequency, solutions, prerequisites, success_indicators, common_pitfalls, success_rate, claude_version, last_verified, source_url, contributor_email) VALUES

('TRPCError: Middleware errors not caught by next() function', 'api', 'HIGH', '[{"solution": "Use next() return value with ok/error properties instead of try-catch. Check resp.ok before throwing.", "percentage": 95}, {"solution": "Access error details via resp.error.cause to detect specific error types like GaxiosError.", "percentage": 90}]'::jsonb, 'tRPC middleware pattern, async/await', 'Error caught and handled in middleware', 'Using traditional try-catch around next()', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/77489779', 'admin:1764228545'),

('TRPCError: UNAUTHORIZED - Error not received on client side', 'api', 'HIGH', '[{"solution": "Ensure TRPCError is thrown with proper code property, not standard Error class.", "percentage": 98}, {"solution": "Verify fetchRequestHandler or adapter is configured correctly with onError handler.", "percentage": 85}]'::jsonb, 'tRPC client/server setup', 'Client receives error object with code property', 'Throwing Error instead of TRPCError', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/77333318', 'admin:1764228545'),

('TRPCError: Code must be a valid error code like UNAUTHORIZED not standard Error', 'api', 'MEDIUM', '[{"solution": "Use TRPCError with code property: throw new TRPCError({code: ''UNAUTHORIZED''})", "percentage": 100}, {"solution": "Import TRPCError from @trpc/server correctly.", "percentage": 95}]'::jsonb, '@trpc/server imports, TypeScript', 'Error displays with correct status code', 'Using Error class instead of TRPCError', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/77214842', 'admin:1764228545'),

('TRPCError: Cannot modify or format error in onError function correctly', 'api', 'MEDIUM', '[{"solution": "Use errorFormatter in initTRPC config, not onError. errorFormatter receives shape parameter.", "percentage": 92}, {"solution": "In onError, throw new TRPCError to replace error before sending to client.", "percentage": 88}]'::jsonb, 'Error formatter setup, error handling', 'Custom error message sent to client', 'Modifying error.message in onError', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/76722810', 'admin:1764228545'),

('TRPCError: UNAUTHORIZED thrown in middleware but redirect not triggered', 'api', 'MEDIUM', '[{"solution": "Use onError hook on client with retry strategy to check error.data.code === UNAUTHORIZED.", "percentage": 90}, {"solution": "Implement client-side routing logic in onError or use useRouter to handle redirect.", "percentage": 85}]'::jsonb, 'Next.js routing, tRPC hooks', 'Client-side redirect triggered on auth failure', 'Expecting server-side middleware to trigger client redirect', 0.87, 'haiku', NOW(), 'https://stackoverflow.com/questions/75169481', 'admin:1764228545'),

('Zod validation error: Custom error handling in tRPC procedures', 'api', 'HIGH', '[{"solution": "Use errorFormatter with ZodError detection and flatten() method for field-level errors.", "percentage": 93}, {"solution": "Check error.cause instanceof ZodError in onError to customize message.", "percentage": 88}]'::jsonb, 'Zod library, error handler setup', 'Custom field-level validation errors returned', 'Not distinguishing ZodError from other errors', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/75063559', 'admin:1764228545'),

('Input parser error: Input parser must be a ZodObject not union type', 'api', 'MEDIUM', '[{"solution": "Wrap union types in z.object() - trpc-openapi requires object parsers only.", "percentage": 96}, {"solution": "Use z.void() for no input, z.object() for any input type.", "percentage": 94}]'::jsonb, 'trpc-openapi, Zod validation', 'OpenAPI generation succeeds without validation errors', 'Using z.union() directly or z.string() at procedure level', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/76883172', 'admin:1764228545'),

('TRPCClientError: Request header fields too large (ERR_CONNECTION_RESET 431)', 'api', 'LOW', '[{"solution": "Batch multiple mutations instead of calling mutate() in loop on each row.", "percentage": 92}, {"solution": "Split large data uploads into chunks or use streaming instead of single request.", "percentage": 85}]'::jsonb, 'Large data handling, file uploads', 'Large datasets uploaded without connection reset', 'Sending 500+ rows in headers via individual mutations', 0.85, 'haiku', NOW(), 'https://stackoverflow.com/questions/78862013', 'admin:1764228545'),

('TRPCError: 400 BAD_REQUEST - Invalid type expected object received undefined', 'api', 'HIGH', '[{"solution": "Send Postman body as {''json'': {your_schema}} for mutations, not bare object.", "percentage": 97}, {"solution": "For GET queries use ?input={''json'':{...}} in URL not body.", "percentage": 95}]'::jsonb, 'Postman API testing, JSON formatting', 'Postman request accepted with 200 response', 'Sending raw object instead of {json: {...}} wrapper', 0.93, 'haiku', NOW(), 'https://stackoverflow.com/questions/78800979', 'admin:1764228545'),

('TRPCClientError: Unexpected token ''<'' - HTML DOCTYPE instead of JSON', 'api', 'MEDIUM', '[{"solution": "Check environment variables are correctly set (use VITE_ prefix not REACT_APP_ for Vite).", "percentage": 94}, {"solution": "Ensure TRPC endpoint URL is correct and not pointing to HTML page.", "percentage": 91}]'::jsonb, 'Vite environment setup, API configuration', 'Valid JSON response from tRPC endpoint', 'Wrong environment variable naming or endpoint URL', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/75350658', 'admin:1764228545'),

('TRPCClientError: fetch failed - ECONNREFUSED during Next.js build', 'api', 'MEDIUM', '[{"solution": "Avoid calling tRPC client in getStaticProps/getStaticPaths. Use server-side calls directly.", "percentage": 96}, {"solution": "Start backend server before Next.js build if SSR calls are needed.", "percentage": 88}]'::jsonb, 'Next.js SSR, server-side calls', 'Build completes without connection errors', 'Calling tRPC client in getStaticProps', 0.92, 'haiku', NOW(), 'https://stackoverflow.com/questions/78898459', 'admin:1764228545'),

('TRPCError: INTERNAL_SERVER_ERROR 500 - Missing API handler export', 'api', 'MEDIUM', '[{"solution": "Export both GET and POST handlers: export { handler as GET, handler as POST }", "percentage": 99}, {"solution": "Ensure createNextApiHandler or fetchRequestHandler is properly exported from route.", "percentage": 97}]'::jsonb, 'Next.js API routes, tRPC setup', 'API endpoint responds with 200 status', 'Missing export or incorrect handler setup', 0.96, 'haiku', NOW(), 'https://stackoverflow.com/questions/75227309', 'admin:1764228545'),

('Cannot read properties of undefined reading ''_context'' in Client Component', 'api', 'MEDIUM', '[{"solution": "Add ''use client'' directive at top of React component to make it a Client Component.", "percentage": 98}, {"solution": "Ensure tRPC hooks are only called in client components, not server components.", "percentage": 95}]'::jsonb, 'Next.js 13+ App Router, React hooks', 'tRPC hooks work without context errors', 'Using tRPC in server component', 0.94, 'haiku', NOW(), 'https://stackoverflow.com/questions/77918106', 'admin:1764228545'),

('Cannot read properties of undefined reading ''def'' - Duplicate route conflict', 'api', 'LOW', '[{"solution": "Check for duplicate tRPC routes on Express or handler - each route defined once only.", "percentage": 97}, {"solution": "Verify router configuration does not merge conflicting routes.", "percentage": 93}]'::jsonb, 'Express routing, tRPC setup', 'All routes return correct responses', 'Defining same route twice in router', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/75073207', 'admin:1764228545'),

('TRPCError: 500 Internal Server Error on mutation with invalid input schema', 'api', 'MEDIUM', '[{"solution": "Check Prisma schema matches Zod input schema exactly - verify optional vs required fields.", "percentage": 94}, {"solution": "Ensure bcrypt/external service calls are correct and not throwing uncaught errors.", "percentage": 88}]'::jsonb, 'Prisma schema, Zod validation', 'Mutation succeeds with valid input', 'Mismatched input schema vs database schema', 0.89, 'haiku', NOW(), 'https://stackoverflow.com/questions/78404723', 'admin:1764228545'),

('useContext error or type inference failing in nested routers/monorepo', 'api', 'MEDIUM', '[{"solution": "Ensure AppRouter type is exported correctly from server and imported in client.", "percentage": 95}, {"solution": "Clear node_modules and rebuild monorepo dependencies after changing router.", "percentage": 92}]'::jsonb, 'Type exports, monorepo setup', 'Client receives correct types from server', 'Stale type references or missing re-exports', 0.90, 'haiku', NOW(), 'https://stackoverflow.com/questions/74185198', 'admin:1764228545'),

('Stream error: Subscriptions should use wsLink not httpBatchLink', 'api', 'LOW', '[{"solution": "Use splitLink to route subscriptions to wsLink and queries/mutations to httpBatchLink.", "percentage": 98}, {"solution": "Verify WS_URL environment variable is correct (ws:// not http://).", "percentage": 96}]'::jsonb, 'WebSocket setup, splitLink configuration', 'Subscriptions work with proper wsLink', 'Using httpBatchLink for subscriptions', 0.95, 'haiku', NOW(), 'https://stackoverflow.com/questions/78098605', 'admin:1764228545'),

('Input validation: Cannot pass string or array directly, must wrap in object', 'api', 'MEDIUM', '[{"solution": "Wrap any input in z.object(): .input(z.object({value: z.string()}))", "percentage": 99}, {"solution": "Use z.void() when no input needed, never omit .input() entirely.", "percentage": 97}]'::jsonb, 'Zod schema definition', 'Procedure accepts properly wrapped input', 'Passing z.string() or z.array() as root input', 0.97, 'haiku', NOW(), 'https://stackoverflow.com/questions/76631499', 'admin:1764228545'),

('Multiple input parsers not working - chaining input() calls fails', 'api', 'MEDIUM', '[{"solution": "Chain input parsers in tRPC v10+: procedure.input(z.object(...)).input(z.object(...))", "percentage": 94}, {"solution": "Alternatively merge schemas: procedure.input(z.object({...schema1, ...schema2}))", "percentage": 91}]'::jsonb, 'tRPC v10+, Zod composition', 'Procedure accepts all input parameters', 'Not chaining input() or using old pattern', 0.88, 'haiku', NOW(), 'https://stackoverflow.com/questions/73675427', 'admin:1764228545'),

('Query invalidation or refetch not triggering in tRPC React Query integration', 'api', 'MEDIUM', '[{"solution": "Use useUtils() hook: const utils = trpc.useUtils(); await utils.query.invalidate();", "percentage": 96}, {"solution": "useContext() is deprecated - migrate to useUtils() for React Query v5+.", "percentage": 93}]'::jsonb, 'React Query v5+, tRPC hooks', 'Query refetches and displays fresh data', 'Using deprecated useContext or manual refetch', 0.91, 'haiku', NOW(), 'https://stackoverflow.com/questions/74715825', 'admin:1764228545');
