INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'Python Packaging - Create distributable packages with proper structure, setup, and PyPI publishing',
  'python-development',
  'skill',
  '[{"solution": "Setup project structure with src layout", "cli": {"macos": "mkdir -p src/my_package tests && touch src/my_package/__init__.py", "linux": "mkdir -p src/my_package tests && touch src/my_package/__init__.py", "windows": "mkdir src\\my_package tests && type nul > src\\my_package\\__init__.py"}, "manual": "Create src/package_name structure with pyproject.toml and README.md", "note": "Source layout prevents accidental import of uninstalled package"}, {"solution": "Create modern pyproject.toml", "cli": {"macos": "cat > pyproject.toml << ''END''\n[build-system]\nrequires = [\"setuptools>=61.0\"]\nbuild-backend = \"setuptools.build_meta\"\n[project]\nname = \"my-package\"\nversion = \"0.1.0\"\nEND", "linux": "cat > pyproject.toml << ''END''\n[build-system]\nrequires = [\"setuptools>=61.0\"]\nbuild-backend = \"setuptools.build_meta\"\n[project]\nname = \"my-package\"\nversion = \"0.1.0\"\nEND", "windows": "echo. > pyproject.toml"}, "manual": "Include build-system, project metadata, dependencies, and optional extras", "note": "Use PEP 621 format for modern Python packaging"}, {"solution": "Build distribution packages", "cli": {"macos": "pip install build && python -m build", "linux": "pip install build && python -m build", "windows": "pip install build && python -m build"}, "manual": "Create wheel and source distribution for PyPI", "note": "Generates .whl and .tar.gz files in dist/ directory"}, {"solution": "Publish to PyPI", "cli": {"macos": "pip install twine && twine upload dist/*", "linux": "pip install twine && twine upload dist/*", "windows": "pip install twine && twine upload dist/*"}, "manual": "Create PyPI account, setup API token in ~/.pypirc, run twine upload", "note": "Test on TestPyPI first before publishing to production"}, {"solution": "Create CLI entry points", "cli": {"macos": "pip install -e .[dev]", "linux": "pip install -e .[dev]", "windows": "pip install -e .[dev]"}, "manual": "Add [project.scripts] section to pyproject.toml with CLI commands", "note": "Enables command-line tools after pip installation"}]'::jsonb,
  'script',
  'Python 3.8+, pip and build tools, PyPI account for publishing, basic Python knowledge',
  'Using flat layout for libraries, not pinning build backend versions, forgetting to include LICENSE and README, hardcoding version numbers instead of using dynamic versioning',
  'Package builds without errors, wheel installs correctly in clean environment, CLI tools work if defined, TestPyPI installation succeeds, metadata displays correctly on PyPI',
  'Master modern Python packaging with src layout, pyproject.toml configuration, and automated PyPI publishing',
  'https://skillsmp.com/skills/wshobson-agents-plugins-python-development-skills-python-packaging-skill-md',
  'admin:HAIKU_SKILL_1764289624_86615'
);
