INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'Cloud Cost Optimization - Reduce cloud expenses through rightsizing, reserved instances, and tagging strategies',
  'claude-code',
  'skill',
  '[{"solution": "Implement cost allocation tagging strategy across all cloud resources", "cli": {"macos": "aws ec2 create-tags --resources i-1234567890abcdef0 --tags Key=CostCenter,Value=engineering", "linux": "aws ec2 create-tags --resources i-1234567890abcdef0 --tags Key=CostCenter,Value=engineering", "windows": "aws ec2 create-tags --resources i-1234567890abcdef0 --tags Key=CostCenter,Value=engineering"}, "note": "Use consistent tags: Environment, Project, Owner, CostCenter"}, {"solution": "Purchase Reserved Instances or Savings Plans for predictable workloads", "cli": {"macos": "aws ec2 describe-reserved-instances-offerings --query ''ReservedInstancesOfferings''", "linux": "aws ec2 describe-reserved-instances-offerings --query ''ReservedInstancesOfferings''", "windows": "aws ec2 describe-reserved-instances-offerings --query ''ReservedInstancesOfferings''"}, "note": "AWS: 30-72% savings; Azure: up to 72%; GCP: up to 57%"}, {"solution": "Implement S3 lifecycle policies to transition data to cheaper storage tiers", "cli": {"macos": "aws s3api put-bucket-lifecycle-configuration --bucket mybucket --lifecycle-configuration file://lifecycle.json", "linux": "aws s3api put-bucket-lifecycle-configuration --bucket mybucket --lifecycle-configuration file://lifecycle.json", "windows": "aws s3api put-bucket-lifecycle-configuration --bucket mybucket --lifecycle-configuration file://lifecycle.json"}, "note": "Transition: STANDARD -> STANDARD_IA (30 days) -> GLACIER (90 days) -> DEEP_ARCHIVE"}, {"solution": "Right-size instances by analyzing CloudWatch CPU and memory utilization", "cli": {"macos": "aws ce get-dimension-values --time-period Start=2024-01-01,End=2024-01-31 --dimension InstanceType", "linux": "aws ce get-dimension-values --time-period Start=2024-01-01,End=2024-01-31 --dimension InstanceType", "windows": "aws ce get-dimension-values --time-period Start=2024-01-01,End=2024-01-31 --dimension InstanceType"}, "note": "Target: 60-70% average CPU utilization"}, {"solution": "Set up budget alerts and cost anomaly detection for continuous monitoring", "cli": {"macos": "aws budgets create-budget --account-id 123456789 --budget file://budget.json", "linux": "aws budgets create-budget --account-id 123456789 --budget file://budget.json", "windows": "aws budgets create-budget --account-id 123456789 --budget file://budget.json"}, "note": "Alert at 80% threshold; enable anomaly detection"}]'::jsonb,
  'script',
  'AWS/Azure/GCP account access, Cloud CLI tools, Cost Management service access',
  'Purchasing RIs without analyzing commitment requirements; not tagging resources consistently; missing lifecycle policies; ignoring auto-scaling opportunities; over-provisioning without utilization analysis; forgetting to delete unused EBS volumes and snapshots',
  'Monthly cloud costs reduced by 20-40%; all resources properly tagged; cost allocation clear by project/team; budget alerts configured; RIs/Savings Plans in use for 80%+ of compute; unused resources cleaned up',
  'Systematically reduce cloud spending through resource rightsizing, reserved capacity, tagging, and continuous monitoring',
  'https://skillsmp.com/skills/wshobson-agents-plugins-cloud-infrastructure-skills-cost-optimization-skill-md',
  'admin:HAIKU_SKILL_1764289639_88230'
);
