INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'FastAPI Project Templates - Create production-ready FastAPI projects with async patterns, dependency injection, and comprehensive error handling',
  'claude-code',
  'skill',
  '[{"solution": "Project Structure Setup", "manual": "Create directories: app/api/v1/endpoints, app/core, app/models, app/schemas, app/services, app/repositories. Use async SQLAlchemy with AsyncSession for database operations.", "note": "Structure enables separation of concerns and scalability"}, {"solution": "Dependency Injection with FastAPI", "manual": "Use Depends() for database sessions, authentication, configuration. Implement get_db() as an async context manager that handles commit/rollback. Create reusable dependency functions for common patterns.", "note": "FastAPI''s DI system integrates directly with route handlers"}, {"solution": "CRUD Repository Pattern", "manual": "Create BaseRepository[ModelType, CreateSchemaType, UpdateSchemaType] with get(), get_multi(), create(), update(), delete(). Subclass for domain-specific repositories like UserRepository. Use SQLAlchemy async select() statements.", "note": "Generic repository pattern reduces code duplication across entities"}, {"solution": "Service Layer Implementation", "manual": "Implement business logic in service classes (e.g., UserService). Services use repositories for data access. Handle validation, password hashing, and business rules in services, not routes.", "note": "Services decouple business logic from HTTP concerns"}, {"solution": "Authentication & JWT", "manual": "Use passlib for password hashing, jose for JWT tokens. Implement OAuth2PasswordBearer for route dependencies. Create create_access_token() and get_current_user() dependency functions. Store SECRET_KEY in environment variables.", "note": "JWT tokens enable stateless, scalable authentication"}, {"solution": "Async Database Operations", "manual": "Use create_async_engine() with AsyncSession. All database calls must be awaited. Use async context managers for session management. Enable echo=True for development debugging.", "note": "Async patterns prevent blocking on I/O operations"}]'::jsonb,
  'steps',
  'Python 3.9+, FastAPI, SQLAlchemy 2.0+, asyncio knowledge, pydantic',
  'Using synchronous database drivers in async code, putting business logic in route handlers, not using type hints, improper session management, skipping tests, tight coupling between layers',
  'Application starts without errors, routes respond with correct status codes and schemas, database operations execute without blocking, authentication tokens validate correctly, tests pass independently for each layer',
  'Production-ready FastAPI architecture with async patterns, DI, CRUD repositories, service layer, and JWT authentication',
  'https://skillsmp.com/skills/wshobson-agents-plugins-api-scaffolding-skills-fastapi-templates-skill-md',
  'admin:HAIKU_SKILL_1764289669_91423'
);
