INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'Swarm Orchestration Skill - Multi-agent swarm coordination with agentic-flow',
  'claude-code',
  'skill',
  '[{"solution": "Initialize mesh topology swarm for peer-to-peer coordination", "cli": {"macos": "npx agentic-flow hooks swarm-init --topology mesh --max-agents 5", "linux": "npx agentic-flow hooks swarm-init --topology mesh --max-agents 5", "windows": "npx agentic-flow hooks swarm-init --topology mesh --max-agents 5"}, "manual": "1. Install agentic-flow v1.5.11+\n2. Run swarm-init with mesh topology\n3. Configure agent count based on task\n4. Enable broadcast communication\n5. Monitor swarm initialization logs", "note": "Mesh topology ideal for equal peer agents with distributed decision-making"}, {"solution": "Setup hierarchical queen-worker topology for centralized coordination", "cli": {"macos": "npx agentic-flow hooks swarm-init --topology hierarchical --queen architect --workers backend-dev,frontend-dev,db-designer", "linux": "npx agentic-flow hooks swarm-init --topology hierarchical --queen architect --workers backend-dev,frontend-dev,db-designer", "windows": "npx agentic-flow hooks swarm-init --topology hierarchical --queen architect --workers backend-dev,frontend-dev,db-designer"}, "manual": "1. Define central coordinator (queen)\n2. Specify worker agents\n3. Configure task dispatch strategy\n4. Set worker communication rules\n5. Enable coordination hooks", "note": "Hierarchical topology suits specialized worker agents"}, {"solution": "Execute parallel multi-agent tasks with automatic load balancing", "cli": {"macos": "npx agentic-flow hooks task-orchestrate --task \"Build REST API with tests\" --mode parallel --enable-load-balancing", "linux": "npx agentic-flow hooks task-orchestrate --task \"Build REST API with tests\" --mode parallel --enable-load-balancing", "windows": "npx agentic-flow hooks task-orchestrate --task \"Build REST API with tests\" --mode parallel --enable-load-balancing"}, "manual": "1. Define task for swarm\n2. Set execution mode (parallel/pipeline/adaptive)\n3. Enable load balancing strategy\n4. Configure timeout limits\n5. Monitor metrics and progress", "note": "Use parallel for independent tasks, pipeline for dependencies"}, {"solution": "Enable fault tolerance with automatic retry and fallback strategies", "cli": {"macos": "npx agentic-flow hooks swarm-configure --resiliency --retry-attempts 3 --fallback reassign-task", "linux": "npx agentic-flow hooks swarm-configure --resiliency --retry-attempts 3 --fallback reassign-task", "windows": "npx agentic-flow hooks swarm-configure --resiliency --retry-attempts 3 --fallback reassign-task"}, "manual": "1. Set retry policy (max attempts, backoff strategy)\n2. Configure fallback behavior\n3. Enable health checks\n4. Setup error monitoring\n5. Test failure scenarios", "note": "Use exponential backoff for transient failures"}]'::jsonb,
  'script',
  'agentic-flow v1.5.11+, Node.js 18+, basic distributed systems knowledge',
  'Not sharing memory across agents causing coordination issues, using wrong topology for task type, insufficient timeouts on parallel tasks, not monitoring swarm metrics, failing to enable hooks for session persistence',
  'Swarm initialized with correct topology, agents spawned and communicating, parallel tasks executing concurrently, shared memory accessible to all agents, metrics showing healthy throughput and success rates',
  'Orchestrate multi-agent swarms with dynamic topology and intelligent task distribution',
  'https://skillsmp.com/skills/ruvnet-claude-flow-claude-skills-swarm-orchestration-skill-md',
  'admin:HAIKU_SKILL_1764290180_35582'
);
