INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'Command Development - Create slash commands for Claude Code workflows',
  'claude-code',
  'skill',
  '[{"solution": "Understand command structure and file format", "manual": "1. Commands are Markdown files (.md) in .claude/commands/ or ~/.claude/commands/\n2. Write commands as instructions FOR Claude, not messages TO users\n3. Optional YAML frontmatter controls behavior\n4. Basic structure: optional frontmatter, then command prompt content\n5. Commands are reusable prompts that can include arguments, file references, and bash execution\n6. File format example: ---\ndescription: Review code for security\nallowed-tools: Read, Bash(git:*)\n---\n\nReview @file for SQL injection, XSS, and authentication issues", "note": "Critical: Commands are instructions FOR Claude, not user-facing messages. Write directives about what Claude should do."}, {"solution": "Configure command behavior with YAML frontmatter", "manual": "1. description - Brief text shown in /help (string, recommended)\n2. allowed-tools - Restrict tool access (string/array): Read, Write, Bash(git:*)\n3. model - Specify model (haiku, sonnet, opus)\n4. argument-hint - Document arguments [pr-number] [priority]\n5. disable-model-invocation - Prevent programmatic calls (boolean)\n6. Start minimal: just description, add fields as needed\n7. All fields optional - only add what''s needed\n8. Use restrictive allowed-tools for security", "note": "YAML fields are optional. Start with just description, add fields only when needed for your command."}, {"solution": "Use dynamic arguments in commands", "manual": "1. $ARGUMENTS - All arguments as single string: /fix-issue 123 → Fix issue #123\n2. $1, $2, $3 - Positional arguments: /deploy api staging → Deploy api to staging\n3. Combine approaches: Deploy $1 to $2 with options: $3\n4. Document in argument-hint: [arg1] [arg2] [arg3]\n5. Validate arguments in prompt: IF($1, action, error message)\n6. Handle missing arguments gracefully\n7. Test with multiple argument counts", "note": "Positional args ($1, $2) for structured use. $ARGUMENTS for simple cases. Always document with argument-hint."}, {"solution": "Reference files and execute bash in commands", "manual": "1. File references: @path/to/file or @$1 for argument-based paths\n2. Multiple files: @file1 and @file2\n3. Static files: @package.json (always available)\n4. Bash execution: !`command here` (requires allowed-tools: Bash)\n5. Examples: !`git status`, !`npm test`, !`node script.js`\n6. Gather dynamic context: git log, environment state, project info\n7. Combine: Files first, then bash, then command prompt\n8. Keep bash commands fast (< 5 seconds)", "note": "File references use @ syntax. Bash uses backtick syntax. Both read-only operations."}]'::jsonb,
  'steps',
  'Understanding of Markdown, basic shell commands, Claude Code familiarity',
  'Writing commands as user-facing messages instead of Claude instructions, hardcoding paths instead of using portable references, not documenting arguments with argument-hint, ignoring file/bash execution security, creating overly complex single commands, not validating arguments and file paths, mixing command logic with error handling',
  'Command appears in /help, arguments work correctly, file references display contents, bash execution runs without errors, command invokes successfully, output matches expected format, arguments documented clearly, security restrictions enforced via allowed-tools',
  'Create slash commands by writing Markdown files with optional YAML frontmatter (description, allowed-tools, model, argument-hint). Use dynamic arguments ($1, $2), file references (@path), and bash execution (!`cmd`). Organize in .claude/commands/ or plugin commands/ directory.',
  'https://skillsmp.com/skills/anthropics-claude-code-plugins-plugin-dev-skills-command-development-skill-md',
  'admin:HAIKU_SKILL_1764289533_81176'
);
