INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'dependency-upgrade - Manage major dependency version upgrades with compatibility analysis, staged rollout, and comprehensive testing',
  'claude-code',
  'skill',
  '[
    {"solution": "Audit current dependencies and identify outdated packages", "cli": {"macos": "npm outdated && npm audit && npx npm-check-updates", "linux": "npm outdated && npm audit && npx npm-check-updates", "windows": "npm outdated && npm audit && npx npm-check-updates"}, "manual": "Run npm outdated to see current vs latest versions. Run npm audit for security issues. Use npm-check-updates to check for major updates. Document findings", "note": "Major versions usually have breaking changes - read changelogs before upgrading"},
    {"solution": "Create upgrade plan and analyze breaking changes", "cli": {"macos": "echo ''Upgrade order: TypeScript, React, React Router, Tests''", "linux": "echo ''Upgrade order: TypeScript, React, React Router, Tests''", "windows": "echo ''Upgrade order: TypeScript, React, React Router, Tests''"}, "manual": "Document upgrade order: tackle dependencies with fewer dependents first. Read CHANGELOG.md and MIGRATION.md in each package. Note breaking changes and required code changes", "note": "Upgrade one major version at a time - never jump multiple major versions"},
    {"solution": "Perform staged incremental upgrades", "cli": {"macos": "git checkout -b upgrade-typescript && npm install typescript@latest && npm run test && npm run build", "linux": "git checkout -b upgrade-typescript && npm install typescript@latest && npm run test && npm run build", "windows": "git checkout -b upgrade-typescript && npm install typescript@latest && npm run test && npm run build"}, "manual": "Create feature branch for each upgrade. Install one package at a time. Run tests and build after each step. Commit incrementally. This allows quick rollback if issues appear", "note": "Testing between steps catches breaking changes early, preventing cascade failures"},
    {"solution": "Update peer dependencies and resolve conflicts", "cli": {"macos": "npm install --legacy-peer-deps || npm install --force", "linux": "npm install --legacy-peer-deps || npm install --force", "windows": "npm install --legacy-peer-deps || npm install --force"}, "manual": "Check npm output for peer dependency warnings. Either update conflicting packages, use --legacy-peer-deps (npm 7+), or --force to override. Update package.json peer dependency ranges", "note": "--legacy-peer-deps ignores peer deps (compatibility mode); --force installs newest versions"},
    {"solution": "Run comprehensive test suite", "cli": {"macos": "npm run test && npm run build", "linux": "npm run test && npm run build", "windows": "npm run test && npm run build"}, "manual": "Execute all test suites: unit tests, integration tests, E2E tests. Build project to catch TypeScript errors. Run visual regression tests to catch UI breakage", "note": "If any test fails, revert and investigate before proceeding to next upgrade"},
    {"solution": "Apply automated codemods for breaking changes", "cli": {"macos": "npx react-codeshift --parser tsx --transform react-codeshift/transforms/rename-unsafe-lifecycles.js src/", "linux": "npx react-codeshift --parser tsx --transform react-codeshift/transforms/rename-unsafe-lifecycles.js src/", "windows": "npx react-codeshift --parser tsx --transform react-codeshift/transforms/rename-unsafe-lifecycles.js src/"}, "manual": "Use package-provided codemods to automatically fix deprecated APIs. Run codemods before manual fixes. Review changes and commit separately from other upgrades", "note": "Codemods handle syntax changes automatically - saves manual refactoring time"},
    {"solution": "Create rollback plan and git tags", "cli": {"macos": "git tag pre-upgrade-v1 && git tag pre-typescript-upgrade", "linux": "git tag pre-upgrade-v1 && git tag pre-typescript-upgrade", "windows": "git tag pre-upgrade-v1 && git tag pre-typescript-upgrade"}, "manual": "Tag commits before major upgrades. If upgrade fails, use git reset to restore. Keep notes of what broke so you can fix it next attempt", "note": "Tags enable fast rollback: git reset --hard pre-typescript-upgrade && npm install"},
    {"solution": "Automate dependency updates with Renovate", "cli": {"macos": "echo ''{\"extends\": [\"config:base\"], \"schedule\": [\"before 3am on Monday\"]}'' > renovate.json", "linux": "echo ''{\"extends\": [\"config:base\"], \"schedule\": [\"before 3am on Monday\"]}'' > renovate.json", "windows": "echo ''{\"extends\": [\"config:base\"], \"schedule\": [\"before 3am on Monday\"]}'' > renovate.json"}, "manual": "Create renovate.json at project root. Configure to auto-merge patch/minor updates, require PR for major. Set schedule to weekly. Renovate creates PRs automatically", "note": "Minor and patch updates are usually safe to auto-merge. Always review major version PRs manually"},
    {"solution": "Verify compatibility matrix and bundle size", "cli": {"macos": "npm run build && npx size-limit", "linux": "npm run build && npx size-limit", "windows": "npm run build && npx size-limit"}, "manual": "Build production bundle and check size. Compare before/after sizes. Use webpack-bundle-analyzer to visualize bundle. Check if new version increases bundle size significantly", "note": "Major version upgrades sometimes add polyfills that bloat bundles - investigate before merging"},
    {"solution": "Update lock file and document changes", "cli": {"macos": "npm ci && npm install --package-lock-only", "linux": "npm ci && npm install --package-lock-only", "windows": "npm ci && npm install --package-lock-only"}, "manual": "Always commit updated package-lock.json. Document upgrade in CHANGELOG or migration notes. Include breaking changes and required code changes for team", "note": "Lock file enables reproducible builds - commit it so others install exact versions"}
  ]'::jsonb,
  'script',
  'Node.js/npm; Git; Semantic versioning understanding; Test infrastructure; TypeScript (optional)',
  'Upgrading all dependencies at once (cascade failures); Not testing between upgrades; Ignoring peer dependency warnings; Forgetting lock file; Not reading breaking changes; Skipping major versions; No rollback plan',
  'npm audit shows no vulnerabilities; All tests pass (unit, integration, E2E); TypeScript compiles successfully; Bundle size acceptable; Lock file updated; Upgrade plan documented; Rollback tags created',
  'Manage major dependency upgrades systematically through staged rollout, compatibility analysis, automated testing, and rollback plans. Includes Renovate/Dependabot automation.',
  'https://skillsmp.com/skills/wshobson-agents-plugins-framework-migration-skills-dependency-upgrade-skill-md',
  'admin:HAIKU_SKILL_1764289684_93067'
);
