INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'secrets-management - Implement secure secrets management for CI/CD pipelines using Vault, AWS, or platform solutions',
  'claude-code',
  'skill',
  '[{"solution": "Choose secrets provider (Vault/AWS/GitHub/GitLab), store credentials securely, retrieve at runtime, mask in logs", "cli": {"macos": "vault server -dev && vault kv put secret/database/config username=admin password=secret", "linux": "vault server -dev && vault kv put secret/database/config username=admin password=secret", "windows": "vault.exe server -dev && vault.exe kv put secret/database/config username=admin password=secret"}, "manual": "1) Decide provider: HashiCorp Vault (centralized, dynamic secrets), AWS Secrets Manager (AWS-native, auto-rotation), Azure Key Vault, Google Secret Manager, or platform-native (GitHub Secrets, GitLab CI variables). 2) For Vault: Enable secrets engine (vault secrets enable -path=secret kv-v2), store secrets (vault kv put secret/path key=value). 3) For AWS: Use aws secretsmanager create-secret, retrieve with aws secretsmanager get-secret-value in CI/CD. 4) For GitHub: Define repository/organization secrets, use ${{secrets.NAME}} in workflows, enable masking with ::add-mask::. 5) For GitLab: Set CI/CD variables as Protected (branches only) and Masked (hidden in logs). 6) Implement rotation: scheduled updates, versioning, old secret revocation. 7) Enable scanning: use TruffleHog or GitGuardian pre-commit hooks to detect accidental commits. 8) Log all access: audit trail for compliance.", "note": "Critical: Never commit secrets to git. Always mask in logs with ::add-mask:: or platform equivalent. Use short-lived tokens (15-60min) for API access. Environment-specific secrets prevent cross-env leaks."}]'::jsonb,
  'script',
  'Understanding of CI/CD platforms (GitHub Actions, GitLab CI, Jenkins), familiarity with at least one secrets provider (Vault, AWS, Azure, GCP), Linux/macOS/Windows command line',
  'Hardcoding secrets in source code or config files, reusing same secret across all environments, forgetting to mask secrets in logs causing exposure, not rotating secrets regularly, using overly broad IAM permissions for secret access, committing .env files with secrets, not implementing audit logging for secret access',
  'Secrets stored and retrieved without exposure in logs, environment-specific secrets preventing cross-env leaks, audit logs tracking all secret access, rotation process automated or well-documented, pre-commit hooks blocking accidental secret commits, masking in CI/CD logs confirmed working, secret scanning integrated into pipeline',
  'Comprehensive guide to secrets management in CI/CD with tools (Vault, AWS, GitHub, GitLab), retrieval patterns, rotation strategies, scanning, and best practices',
  'https://skillsmp.com/skills/wshobson-agents-plugins-cicd-automation-skills-secrets-management-skill-md',
  'admin:HAIKU_SKILL_1764289594_83925'
);
