INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'Agent Development - Create autonomous agents for Claude Code plugins with system prompts, triggering conditions, and structured configuration',
  'claude-code',
  'skill',
  '[
    {"solution": "Understand Agent File Structure - Learn YAML frontmatter format with name, description, model, color, and optional tools fields", "manual": "Agent files use markdown format with YAML frontmatter. Required fields: name (lowercase-hyphens, 3-50 chars), description (10-5000 chars with examples), model (inherit/sonnet/opus/haiku), color (blue/cyan/green/yellow/magenta/red). Optional: tools array to restrict tool access."},
    {"solution": "Write Agent Description with Examples - Define triggering conditions and include <example> blocks showing when agent activates", "manual": "Description format: ''Use this agent when [conditions]. Examples:\\n\\n<example>\\nContext: [situation]\\nuser: \"[request]\"\\nassistant: \"[response]\"\\n<commentary>\\n[why trigger]\\n</commentary>\\nassistant: \"I''ll use the [agent-name] agent...\"\\n</example>''. Include 2-4 examples covering explicit, implicit, and proactive triggering. Each example needs Context, user message, assistant response, and commentary explaining trigger logic."},
    {"solution": "Design Agent System Prompt - Write second-person instructions defining agent role, responsibilities, process, quality standards, output format, and edge cases", "manual": "System prompt structure: ''You are [specific role] specializing in [domain].\\n\\n**Your Core Responsibilities:**\\n1. [Primary task]\\n2. [Secondary task]\\n\\n**[Task Name] Process:**\\n1. [Step]\\n2. [Step]\\n\\n**Quality Standards:**\\n- [Standard with specifics]\\n\\n**Output Format:**\\n[Define expected output structure]\\n\\n**Edge Cases:**\\n- [Case]: [How to handle]''. Keep 500-3000 words. Use second person throughout."},
    {"solution": "Validate Agent Configuration - Use validate-agent.sh script to check file structure, field formats, naming conventions, and system prompt quality", "cli": {"macos": "scripts/validate-agent.sh agents/agent-name.md", "linux": "scripts/validate-agent.sh agents/agent-name.md", "windows": "scripts/validate-agent.sh agents/agent-name.md"}, "manual": "Script validates: YAML frontmatter format (---), required fields presence, name format (alphanumeric-hyphens), description length/examples, model validity, color validity, tools array format, system prompt length/structure. Returns validation pass/fail with detailed error messages."},
    {"solution": "Test Agent Triggering - Create scenarios matching examples to verify agent activates with correct handling and output", "manual": "Test by: 1) Create scenario matching examples in description, 2) Use similar phrasing to examples, 3) Check Claude loads agent, 4) Verify agent provides expected functionality, 5) Test edge cases mentioned in system prompt, 6) Confirm output format matches specification."}
  ]'::jsonb,
  'steps',
  'Understanding of Claude Code plugin architecture, markdown and YAML syntax, basic knowledge of how Claude handles tool usage',
  'Using generic agent names (helper, assistant), omitting <example> blocks, vague triggering conditions without specific scenarios, writing system prompts in first person instead of second person, not including edge case handling, making process steps unclear or non-actionable, forgetting to validate naming conventions',
  'Agent file validates successfully with no errors, description includes 2-4 concrete examples with commentary, system prompt follows structure (responsibilities/process/standards/output/edge-cases), agent triggers correctly when matching example scenarios, output format is unambiguous and measurable, name is 3-50 chars and alphanumeric-hyphens only',
  'Comprehensive guide for creating autonomous Claude Code agents with structured configuration, triggering examples, and system prompt design patterns',
  'https://skillsmp.com/skills/anthropics-claude-code-plugins-plugin-dev-skills-agent-development-skill-md',
  'admin:HAIKU_SKILL_1764288421'
);
