INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'Frontend Design - Create distinctive, production-grade frontend interfaces with high design quality and avoid generic AI aesthetics',
  'claude-code',
  'skill',
  '[
    {"solution": "Understand design context: purpose, audience, aesthetic tone, and constraints", "manual": "Before coding, commit to a BOLD aesthetic direction. Identify: Purpose (what problem does this solve?), Tone (choose an extreme like brutalist, luxury, retro-futuristic, organic, playful, editorial, art deco, soft/pastel, industrial), Technical constraints (framework, performance, accessibility), and Differentiation (what makes this unforgettable?). The key is intentionality - bold maximalism and refined minimalism both work when executed with precision.", "note": "Choose a clear conceptual direction and execute it with precision. This is the foundation for distinctive design."},
    {"solution": "Apply frontend aesthetics guidelines: typography, color, motion, and spatial composition", "manual": "Focus on: Typography - choose distinctive, characterful fonts (avoid Arial, Inter, system defaults). Pair a distinctive display font with refined body font. Color & Theme - commit to cohesive aesthetic using CSS variables. Use dominant colors with sharp accents. Motion - use CSS animations for high-impact moments. Prioritize page load with staggered reveals using animation-delay. Add scroll-triggering and hover states. Spatial Composition - use asymmetry, overlap, diagonal flow, grid-breaking elements, and generous negative space or controlled density.", "note": "Typography and color choices are the quickest way to elevate design. Avoid generic choices."},
    {"solution": "Create atmosphere with backgrounds and visual details", "manual": "Add contextual effects and textures matching the aesthetic. Use gradient meshes, noise textures, geometric patterns, layered transparencies, dramatic shadows, decorative borders, custom cursors, and grain overlays. Create depth and atmosphere rather than defaulting to solid colors. Every visual element should reinforce the overall aesthetic direction.", "note": "Details create the difference between adequate and extraordinary design."},
    {"solution": "Match implementation complexity to aesthetic vision", "manual": "Maximalist designs need elaborate code with extensive animations and effects. Minimalist or refined designs need restraint, precision, and careful attention to spacing, typography, and subtle details. Elegance comes from executing your vision well, not from the intensity of the vision. Production-grade code that is visually striking, cohesive, and meticulously refined in every detail.", "note": "The complexity of the implementation should serve the aesthetic, not the reverse."}
  ]'::jsonb,
  'steps',
  'HTML/CSS/JavaScript knowledge. Familiarity with a frontend framework (React, Vue, etc.) is helpful but optional.',
  'NEVER use generic AI-generated aesthetics: overused fonts (Inter, Roboto, Arial), clichéd color schemes (especially purple gradients on white), predictable layouts, cookie-cutter patterns, or designs lacking context-specific character. Avoid converging on common choices across iterations. Do not hold back on creativity. Show extraordinary work by thinking outside the box and committing to distinctive vision.',
  'User confirms the interface matches the design vision, is production-grade and functional, looks visually striking and memorable, feels cohesive with a clear aesthetic point-of-view, and shows meticulous refinement in details (typography, spacing, animations, color, textures).',
  'Create distinctive, production-grade frontend interfaces by committing to bold aesthetic directions and executing with precision.',
  'https://skillsmp.com/skills/anthropics-claude-code-plugins-frontend-design-skills-frontend-design-skill-md',
  'admin:HAIKU_SKILL_1764288415'
);
