INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'Writing Hookify Rules - Create hooks to watch for patterns and trigger messages',
  'claude-code',
  'skill',
  '[{"solution": "Define rule in .claude/hookify.{name}.local.md with YAML frontmatter", "cli": {"macos": "echo ''---\nname: rule-id\nenabled: true\nevent: bash\npattern: dangerous_pattern\n---\n\nMessage'' > .claude/hookify.myname.local.md", "linux": "echo ''---\nname: rule-id\nenabled: true\nevent: bash\npattern: dangerous_pattern\n---\n\nMessage'' > .claude/hookify.myname.local.md", "windows": "echo. > .claude/hookify.myname.local.md"}, "manual": "1. Create file: .claude/hookify.{descriptive-name}.local.md\n2. Add YAML frontmatter with: name, enabled, event, pattern (or conditions)\n3. Add message body in markdown\n4. Save file - rules load dynamically\n5. Test the rule on next tool use", "note": "Rules reload on each tool use. Use event: bash, file, stop, prompt, or all. Single quotes in messages must be doubled in SQL."}, {"solution": "Write complex rules with multiple conditions", "cli": {"macos": "cat > .claude/hookify.advanced.local.md << ''EOF''\n---\nname: warn-api-keys\nenabled: true\nevent: file\nconditions:\n  - field: file_path\n    operator: regex_match\n    pattern: \\.env$\n  - field: new_text\n    operator: contains\n    pattern: API_KEY\n---\nYou''re editing .env with API_KEY!\nEOF", "linux": "cat > .claude/hookify.advanced.local.md << ''EOF''\n---\nname: warn-api-keys\nenabled: true\nevent: file\nconditions:\n  - field: file_path\n    operator: regex_match\n    pattern: \\.env$\n  - field: new_text\n    operator: contains\n    pattern: API_KEY\n---\nYou''re editing .env with API_KEY!\nEOF", "windows": "Use Notepad to create .claude/hookify.advanced.local.md with conditions syntax"}, "manual": "Use conditions array with field, operator, and pattern. Operators: regex_match, contains, equals, not_contains, starts_with, ends_with. All conditions must match to trigger.", "note": "Complex rules match against specific fields (file_path, new_text, command, user_prompt, etc)."}, {"solution": "Test regex patterns before using in rules", "cli": {"macos": "python3 -c \"import re; result = re.search(r''your_pattern'', ''test_text''); print(''Match'' if result else ''No match'')\"", "linux": "python3 -c \"import re; result = re.search(r''your_pattern'', ''test_text''); print(''Match'' if result else ''No match'')\"", "windows": "python -c \"import re; result = re.search(r''your_pattern'', ''test_text''); print(''Match'' if result else ''No match'')\""}, "manual": "Use regex101.com (Python flavor) to test patterns before adding to rules. Test with exact strings you want to match.", "note": "Common mistake: too broad patterns (pattern: log matches ''login'', ''dialog''). Use boundaries like \\( or \\s"}]'::jsonb,
  'steps',
  '.claude/ directory exists, understand event types (bash, file, stop, prompt), basic regex knowledge',
  'Too broad regex (matches unwanted cases), escaping issues in YAML, wrong event type for use case, forgetting .local in filename',
  'Rule triggers on next tool use after file save, message displays in Claude output, disabled rules show enabled: false',
  'Create Hookify rules to pattern-match tool operations and show messages/block actions',
  'https://skillsmp.com/skills/anthropics-claude-code-plugins-hookify-skills-writing-rules-skill-md',
  'admin:HAIKU_SKILL_1764289548_81336'
);
