INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'Clojure Code Review Skill - Review Clojure and ClojureScript code changes for compliance with Metabase coding standards and style violations',
  'claude-code',
  'skill',
  '[
    {"solution": "Check naming conventions", "cli": {"macos": "grep -r \"snake_case_var\" .", "linux": "grep -r \"snake_case_var\" .", "windows": "findstr /r \"snake_case_var\" ."}, "manual": "Review variable and function names for kebab-case compliance. Pure functions should be named as nouns describing their return value (e.g., ''user'' not ''get-user''). Side-effect functions must end with ''!'' (e.g., ''update-db!''). Check namespace-alias repetition in function names.", "note": "Common naming violations are the most frequent issues found in code reviews"},
    {"solution": "Verify documentation standards", "cli": {"macos": "grep -E \"^\\(defn\" src/ | grep -v \"\\(defn \\^\"", "linux": "grep -E \"^\\(defn\" src/ | grep -v \"\\(defn \\^\"", "windows": "findstr /r \"\\(defn\" src/ && findstr /r \"docstring\" src/"}, "manual": "All public vars in src or enterprise/backend/src must have docstrings. Docstrings should use Markdown conventions and reference other vars using [[var-name]] notation, not backticks. TODO comments must follow format: ;; TODO (Name Date) -- description", "note": "Missing docstrings and improperly formatted TODO comments are frequently flagged"},
    {"solution": "Review code organization", "cli": {"macos": "grep -n \"^\\(defn \" src/ | awk -F: ''length($NF) > 120 {print NR, $0}''", "linux": "grep -n \"^\\(defn \" src/ | awk -F: ''length($NF) > 120 {print NR, $0}''", "windows": "findstr /r \"\\(defn\" src/ > code_review.txt"}, "manual": "Verify all vars are marked ^:private unless used elsewhere. Avoid declare when possible. Keep functions under 20 lines. No blank lines within definition forms except for pairwise constructs in let/cond. Lines must be ≤ 120 characters.", "note": "Line length violations and overly long functions are common organizational issues"},
    {"solution": "Check REST API compliance", "cli": {"macos": "grep -r \"/api/\" src/ | grep -E \"(GET|POST|PUT|DELETE)\"", "linux": "grep -r \"/api/\" src/ | grep -E \"(GET|POST|PUT|DELETE)\"", "windows": "findstr /r \"/api/\" src/"}, "manual": "Response schemas must be present (:- <schema>). Query params use kebab-case, request bodies use snake_case. Routes use singular nouns (e.g., /api/dashboard/:id not /dashboards). GET requests have no side effects except analytics. Malli schemas must be detailed and complete. All new endpoints require tests.", "note": "API naming conventions and missing response schemas are frequently flagged issues"},
    {"solution": "Run style guide compliance scan", "cli": {"macos": "clj-kondo --lint src/", "linux": "clj-kondo --lint src/", "windows": "clj-kondo --lint src/"}, "manual": "Use clj-kondo linter to catch parentheses and syntax issues automatically. Review the Metabase Clojure style guide for comprehensive standards. Check for pattern violations in the provided pattern matching table (e.g., calculate-age vs age, get-user vs user).", "note": "The linter will catch parentheses issues - do not post comments about those"}
  ]'::jsonb,
  'steps',
  'Clojure/ClojureScript code changes, access to Metabase coding standards, knowledge of kebab-case conventions, understanding of Clojure idioms',
  'Congratulating on trivial changes or proper style adherence; posting comments that things "look good"; flagging missing parentheses (linter catches these); posting comments about kondo ignore comments',
  'Code review identifies all style violations against Metabase standards, captures naming violations, documentation gaps, and API endpoint issues. Changes flagged are specific and actionable without congratulatory comments.',
  'Review Clojure and ClojureScript code for Metabase style guide compliance and flag naming, documentation, and API convention violations.',
  'https://skillsmp.com/skills/metabase-metabase-claude-skills-clojure-review-skill-md',
  'admin:HAIKU_SKILL_1764288413'
);
