INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'docs-review - Review documentation changes for Metabase style guide compliance in pull requests and files',
  'claude-code',
  'skill',
  '[
    {"solution": "Step 1: Detect review mode by checking for mcp__github__create_pending_pull_request_review tool availability", "cli": {"macos": "# Tool detection happens automatically during skill execution", "linux": "# Tool detection happens automatically during skill execution", "windows": "# Tool detection happens automatically during skill execution"}, "manual": "Check if the mcp__github__create_pending_pull_request_review tool is available. If available, use PR review mode with pending review workflow. If not available, use local review mode and output issues to conversation.", "note": "Review mode determines how feedback is delivered - PR mode uses GitHub API, local mode uses conversation output"},
    {"solution": "Step 2: Read documentation changes and understand intent", "cli": {"macos": "# Use Read and Glob tools to examine documentation files", "linux": "# Use Read and Glob tools to examine documentation files", "windows": "# Use Read and Glob tools to examine documentation files"}, "manual": "Use the Read tool to read the changed documentation files. Use Grep to examine specific sections. Use Glob to find markdown files being reviewed. Understand the overall intent and scope of the documentation changes.", "note": "Always read changes completely before starting the review process"},
    {"solution": "Step 3: Review against Metabase style guide checklist", "cli": {"macos": "# Checklist verification requires manual inspection - no CLI equivalent", "linux": "# Checklist verification requires manual inspection - no CLI equivalent", "windows": "# Checklist verification requires manual inspection - no CLI equivalent"}, "manual": "Run through the diff against these categories: Tone and voice (formal language, users vs people, excessive exclamation points), Structure and clarity (buried information, verbose text, vague headings, task ordering), Links and references (here links, links in headings), Formatting (backticks on UI elements, ampersands, list consistency), Code and examples (working code, execution order, excessive images), Sentence construction (pronoun overuse). Flag only issues that materially impact readability.", "note": "Use the quick scan table to identify patterns like backticks on UI elements (should be bold), descriptive link text, and condescending qualifiers"},
    {"solution": "Step 4: Number all issues sequentially and format feedback", "cli": {"macos": "# Issue numbering and formatting is a manual process", "linux": "# Issue numbering and formatting is a manual process", "windows": "# Issue numbering and formatting is a manual process"}, "manual": "For each issue found, number them sequentially starting from Issue 1 with no gaps. Format as: **Issue N: [Brief title]** followed by line number, description, and suggested fix. Ensure numbering is non-negotiable and allows efficient referencing.", "note": "ALL issues MUST be numbered sequentially - this is critical for user efficiency and tracking which feedback has been addressed"},
    {"solution": "Step 5: In PR mode, use pending review workflow to post all comments at once", "cli": {"macos": "# Uses mcp__github tools for PR integration", "linux": "# Uses mcp__github tools for PR integration", "windows": "# Uses mcp__github tools for PR integration"}, "manual": "If PR mode: (1) Start a pending review with mcp__github__create_pending_pull_request_review, (2) Get diff with mcp__github__get_pull_request_diff, (3) Collect all issues and number sequentially, (4) Add all review comments in PARALLEL using mcp__github__add_pull_request_review_comment_to_pending_review in single response, (5) Submit with mcp__github__submit_pending_pull_request_review using event type COMMENT without body. If local mode: output formatted numbered issues to conversation.", "note": "CRITICAL: In PR mode, ALL comments must be added in parallel in a single response. Do NOT add them sequentially. Do NOT output summary to conversation in PR mode."}
  ]'::jsonb,
  'steps',
  'Allowed tools: Read, Grep, Bash, Glob. For PR mode: mcp__github tools for pending review workflow. Access to Metabase style guide reference.',
  'Flagging issues that won''t materially impact readability. Using backticks instead of bold for UI elements. Numbering issues non-sequentially or leaving gaps. In PR mode: posting comments one at a time instead of in parallel. Including body text when submitting pending review. Forgetting to number ALL issues.',
  'Documentation review completed with all style guide violations identified and numbered sequentially. In PR mode: pending review submitted with all comments visible as single cohesive review. In local mode: numbered issues list provided in conversation with suggested fixes.',
  'Review documentation changes against Metabase writing style guide and provide sequential numbered feedback on tone, structure, formatting, and code examples.',
  'https://skillsmp.com/skills/metabase-metabase-claude-skills-docs-review-skill-md',
  'admin:HAIKU_SKILL_1764288409'
);
