INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'Add unsigned integer (uint) type support to PyTorch operators by updating AT_DISPATCH macros',
  'claude-code',
  'skill',
  '[
    {"solution": "Step 1: Check if file uses AT_DISPATCH_V2", "cli": {"macos": "grep -n ''AT_DISPATCH_V2'' <file>", "linux": "grep -n ''AT_DISPATCH_V2'' <file>", "windows": "findstr /N ''AT_DISPATCH_V2'' <file>"}, "manual": "Open the file and search for AT_DISPATCH_V2. If using old AT_DISPATCH_ALL_TYPES variants, use the at-dispatch-v2 skill to convert first.", "note": "Must use AT_DISPATCH_V2 format, not old AT_DISPATCH macros"},
    {"solution": "Step 2: Identify all dispatch macro sites in the file", "cli": {"macos": "grep -n ''AT_DISPATCH_V2'' <file> | wc -l", "linux": "grep -n ''AT_DISPATCH_V2'' <file> | wc -l", "windows": "findstr /C:AT_DISPATCH_V2 <file>"}, "manual": "Note all occurrences of AT_DISPATCH_V2 in the file. Some operators have multiple dispatch sites (CPU, CUDA, different functions). Each needs uint support added.", "note": "Apply changes consistently to all dispatch sites"},
    {"solution": "Step 3: Choose the uint addition method based on current type groups", "manual": "Decision tree: (a) If dispatch uses AT_EXPAND(AT_INTEGRAL_TYPES), replace with AT_EXPAND(AT_INTEGRAL_TYPES_V2). (b) If dispatch uses AT_EXPAND(AT_ALL_TYPES) or other patterns, add AT_EXPAND(AT_BAREBONES_UNSIGNED_TYPES) to the type list. Method 2 (AT_INTEGRAL_TYPES_V2) is cleaner when AT_INTEGRAL_TYPES is present.", "note": "Method 1 (explicit AT_BAREBONES_UNSIGNED_TYPES) is more explicit about adding uint support. Method 2 (AT_INTEGRAL_TYPES_V2 substitution) is cleaner."},
    {"solution": "Step 4: Apply Method 1 - Add AT_BAREBONES_UNSIGNED_TYPES explicitly", "manual": "For patterns with AT_EXPAND(AT_ALL_TYPES) or separate FLOATING_TYPES: Add a new line with AT_EXPAND(AT_BAREBONES_UNSIGNED_TYPES) to the dispatch macro. Example: AT_DISPATCH_V2(dtype, \"op\", AT_WRAP([&]() { kernel<scalar_t>(); }), AT_EXPAND(AT_ALL_TYPES), AT_EXPAND(AT_BAREBONES_UNSIGNED_TYPES), kHalf, kBFloat16);", "note": "Use Method 1 when you want to be explicit about adding uint support or when AT_INTEGRAL_TYPES is not present"},
    {"solution": "Step 5: Apply Method 2 - Replace with AT_INTEGRAL_TYPES_V2", "manual": "If dispatch uses AT_EXPAND(AT_INTEGRAL_TYPES), replace it with AT_EXPAND(AT_INTEGRAL_TYPES_V2). This automatically includes kUInt16, kUInt32, kUInt64. Example: Before: AT_EXPAND(AT_INTEGRAL_TYPES). After: AT_EXPAND(AT_INTEGRAL_TYPES_V2)", "note": "Only applicable if AT_INTEGRAL_TYPES is already in the dispatch macro"},
    {"solution": "Step 6: Verify all dispatch sites have been updated", "manual": "Go through each AT_DISPATCH_V2 site identified in Step 2. Ensure either: (a) AT_BAREBONES_UNSIGNED_TYPES was added (Method 1), or (b) AT_INTEGRAL_TYPES was replaced with AT_INTEGRAL_TYPES_V2 (Method 2). All relevant sites should have consistent unsigned type support.", "note": "Missing even one dispatch site means the operator won''t fully support uint types"},
    {"solution": "Step 7: Validate the changes", "manual": "Check that: (1) AT_DISPATCH_V2 format is used throughout (not old AT_DISPATCH). (2) Unsigned types are added via one of the two methods. (3) All relevant dispatch sites are updated. (4) Type groups use AT_EXPAND(). (5) Arguments are properly formatted and comma-separated. (6) File syntax is correct C++.", "note": "Invalid syntax will cause compilation failures"}
  ]'::jsonb,
  'steps',
  'PyTorch repository access, understanding of AT_DISPATCH macros, C++ knowledge',
  'Not applying changes to all dispatch sites in a file (operators have multiple sites), confusing kByte (uint8) with the unsigned type groups (uint16, uint32, uint64), adding uint support to floating-point-only operators, not converting old AT_DISPATCH variants to V2 first',
  'Operator accepts uint16, uint32, and uint64 tensor inputs without type errors. AT_DISPATCH_V2 macros either use AT_INTEGRAL_TYPES_V2 or include AT_EXPAND(AT_BAREBONES_UNSIGNED_TYPES). Code compiles successfully.',
  'Add unsigned integer type support (uint16, uint32, uint64) to PyTorch operators by updating AT_DISPATCH macros via two methods: explicit AT_BAREBONES_UNSIGNED_TYPES addition or AT_INTEGRAL_TYPES_V2 substitution.',
  'https://skillsmp.com/skills/pytorch-pytorch-claude-skills-add-uint-support-skill-md',
  'admin:HAIKU_SKILL_1764288025'
);
