INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'uv-package-manager - Master the uv package manager for fast Python dependency management, virtual environments, and modern Python project workflows',
  'claude-code',
  'skill',
  '[
    {"solution": "Install uv package manager", "cli": {"macos": "brew install uv", "linux": "curl -LsSf https://astral.sh/uv/install.sh | sh", "windows": "powershell -c \"irm https://astral.sh/uv/install.ps1 | iex\""}, "manual": "Visit https://docs.astral.sh/uv/ and follow installation instructions for your platform", "note": "Verify with: uv --version"},
    {"solution": "Initialize new Python project with uv", "cli": {"macos": "uv init my-project && cd my-project", "linux": "uv init my-project && cd my-project", "windows": "uv init my-project && cd my-project"}, "manual": "Run uv init to create project structure with pyproject.toml, .python-version, and README.md", "note": "Creates automatic virtual environment setup"},
    {"solution": "Add and manage dependencies", "cli": {"macos": "uv add requests pandas && uv add --dev pytest black ruff", "linux": "uv add requests pandas && uv add --dev pytest black ruff", "windows": "uv add requests pandas && uv add --dev pytest black ruff"}, "manual": "Use uv add to add packages with constraints, uv remove to remove, uv sync to install from lock", "note": "Automatically updates pyproject.toml and uv.lock"},
    {"solution": "Create and manage virtual environments", "cli": {"macos": "uv venv && source .venv/bin/activate", "linux": "uv venv && source .venv/bin/activate", "windows": "uv venv && .venv\\Scripts\\activate.ps1"}, "manual": "Use uv venv to create venv, then source activate. Or use uv run for automatic activation", "note": "uv run python script.py auto-activates without manual activation"},
    {"solution": "Set up Python version management", "cli": {"macos": "uv python install 3.12 && uv python pin 3.12", "linux": "uv python install 3.12 && uv python pin 3.12", "windows": "uv python install 3.12 && uv python pin 3.12"}, "manual": "Install specific Python versions with uv python install, pin with uv python pin VERSION", "note": "Creates .python-version file for project"},
    {"solution": "CI/CD integration with GitHub Actions", "cli": {"macos": "uv sync --all-extras --dev && uv run pytest", "linux": "uv sync --all-extras --dev && uv run pytest", "windows": "uv sync --all-extras --dev && uv run pytest"}, "manual": "Use astral-sh/setup-uv@v2 action, then run uv sync and uv run commands. Use --frozen flag in production CI", "note": "--frozen installs exact versions from lock file without re-resolving"},
    {"solution": "Docker container integration", "cli": {"macos": "COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv", "linux": "COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv", "windows": "COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv"}, "manual": "Use multi-stage Dockerfile: builder stage installs dependencies, runtime stage copies .venv from builder", "note": "Multi-stage build reduces image size significantly"},
    {"solution": "Migrate from pip/poetry/pip-tools", "cli": {"macos": "uv init && uv add -r requirements.txt", "linux": "uv init && uv add -r requirements.txt", "windows": "uv init && uv add -r requirements.txt"}, "manual": "Initialize uv project and add dependencies from existing requirements.txt. For poetry, uv reads pyproject.toml directly", "note": "uv is compatible with existing pyproject.toml formats"},
    {"solution": "Monorepo workspace setup", "cli": {"macos": "uv sync", "linux": "uv sync", "windows": "uv sync"}, "manual": "Configure [tool.uv.workspace] in root pyproject.toml with members pattern. Use uv sync to install all workspace packages", "note": "Enables dependency sharing across multiple packages"},
    {"solution": "Performance optimization and caching", "cli": {"macos": "uv cache clean && uv sync --frozen --offline", "linux": "uv cache clean && uv sync --frozen --offline", "windows": "uv cache clean && uv sync --frozen --offline"}, "manual": "uv automatically uses global cache (~/.cache/uv on Linux, ~/Library/Caches/uv on macOS). Use --frozen for reproducible installs from lock file", "note": "Global cache is reused across projects for maximum speed"}
  ]'::jsonb,
  'script',
  'Rust-based package manager; Cross-platform support; Python 3.8+',
  'Not activating venv when needed; Forgetting to commit uv.lock; Using pip when uv is faster; Not using --frozen in CI; Mixing uv and pip commands',
  'uv --version displays version; uv init creates project structure; pyproject.toml contains dependencies; uv.lock generated; uv run executes commands successfully',
  'Ultra-fast Python package manager (10-100x faster than pip) with drop-in compatibility. Handles venv creation, Python version management, lockfiles, and CI/CD workflows.',
  'https://skillsmp.com/skills/wshobson-agents-plugins-python-development-skills-uv-package-manager-skill-md',
  'admin:HAIKU_SKILL_1764289684_93067'
);
