INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'Analyzing AgentScope Library - Retrieve and analyze AgentScope library information',
  'claude-code',
  'skill',
  '[{"solution": "Search for guidance in AgentScope tutorial", "cli": {"macos": "ls docs/tutorials/", "linux": "ls docs/tutorials/", "windows": "dir docs\\tutorials\\"}, "note": "View tutorial files using ls or cat commands. Located in docs/tutorials folder of cloned agentscope repository"}, {"solution": "Search for official examples", "cli": {"macos": "git clone -b main https://github.com/agentscope-ai/agentscope && ls examples/", "linux": "git clone -b main https://github.com/agentscope-ai/agentscope && ls examples/", "windows": "git clone -b main https://github.com/agentscope-ai/agentscope && dir examples"}, "note": "Use ls/cat commands to navigate tree structure by functionality. Avoid find command as filenames may not directly relate to functionality"}, {"solution": "View targeted modules", "cli": {"macos": "python view_agentscope_module.py --module agentscope", "linux": "python view_agentscope_module.py --module agentscope", "windows": "python view_agentscope_module.py --module agentscope"}, "note": "Retrieves function/class signatures, docstrings, and source code references. Start with agentscope as root, then specify submodule"}, {"solution": "Install AgentScope if needed", "cli": {"macos": "pip install agentscope", "linux": "pip install agentscope", "windows": "pip install agentscope"}, "note": "Verify installation with: pip list | grep agentscope"}, {"solution": "Decide which script to use", "manual": "How-to questions: use guidance script (tutorials). How-to-implement: search examples first, then guides. How-to-initialize: search tutorials first, then modules/classes/functions"}]'::jsonb,
  'script',
  'Python 3.7+, AgentScope library installed, view_agentscope_module.py script in working directory, agentscope repository cloned for examples/tutorials',
  'Using find command to search examples (filenames dont relate to functionality); not cloning repository before accessing examples; skipping permission request to clone repo or install package; assuming module names without checking actual API',
  'Module information displayed with full signature and docstring; class methods listed with parameters; function signatures match actual API; source code references point to correct file line ranges',
  'AgentScope library analysis tool for retrieving functions, classes, examples, and guidance documentation',
  'https://skillsmp.com/skills/agentscope-ai-agentscope-examples-functionality-agent-skill-skill-analyzing-agentscope-library-skill-md',
  'admin:HAIKU_SKILL_1764289895_16090'
);
