INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'NFT Standards - Implement ERC-721, ERC-1155 with metadata, royalties, and marketplace integration',
  'blockchain-web3',
  'skill',
  '[{"solution": "Implement ERC-721 (single NFT)", "cli": {"macos": "npm install @openzeppelin/contracts", "linux": "npm install @openzeppelin/contracts", "windows": "npm install @openzeppelin/contracts"}, "manual": "Extend ERC721URIStorage and ERC721Enumerable from OpenZeppelin, implement mint() function", "note": "Use ERC721A for gas-optimized batch minting"}, {"solution": "Implement ERC-1155 (multi-token)", "cli": {"macos": "npm install @openzeppelin/contracts", "linux": "npm install @openzeppelin/contracts", "windows": "npm install @openzeppelin/contracts"}, "manual": "Extend ERC1155, implement mint/mintBatch for multiple token types", "note": "Single contract manages multiple token IDs with shared functions"}, {"solution": "Setup IPFS metadata storage", "cli": {"macos": "npm install nft.storage", "linux": "npm install nft.storage", "windows": "npm install nft.storage"}, "manual": "Upload JSON metadata to IPFS using pinning service, return IPFS hash in tokenURI()", "note": "Follow OpenSea metadata standard with name, description, image, attributes"}, {"solution": "Implement EIP-2981 royalties", "cli": {"macos": "npm install @openzeppelin/contracts", "linux": "npm install @openzeppelin/contracts", "windows": "npm install @openzeppelin/contracts"}, "manual": "Extend IERC2981, implement royaltyInfo() returning recipient and percentage", "note": "Marketplaces automatically enforce royalties on secondary sales"}, {"solution": "Create soulbound tokens (non-transferable)", "cli": {"macos": "npm install @openzeppelin/contracts", "linux": "npm install @openzeppelin/contracts", "windows": "npm install @openzeppelin/contracts"}, "manual": "Override _beforeTokenTransfer() to block transfers except burn/mint", "note": "User can burn their SBT but cannot transfer it"}]'::jsonb,
  'script',
  'Solidity programming, OpenZeppelin library, IPFS/Pinata knowledge, Hardhat/Truffle testing, web3.js or ethers.js',
  'Not implementing royalties for ERC-721, forgetting IPFS pinning causing metadata loss, incorrect metadata JSON format, gas-inefficient minting without ERC721A, missing access control on mint',
  'Contract deploys successfully, mint transactions succeed, metadata resolves via IPFS gateway, marketplace recognizes royalties, enumeration functions work, burn/transfer logic correct',
  'Build production-grade NFT contracts supporting ERC-721/1155 with IPFS metadata, EIP-2981 royalties, and marketplace compatibility',
  'https://skillsmp.com/skills/wshobson-agents-plugins-blockchain-web3-skills-nft-standards-skill-md',
  'admin:HAIKU_SKILL_1764289624_86615'
);
