INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'Kubernetes Security Policies - Implement NetworkPolicy, PodSecurityPolicy, RBAC, and Pod Security Standards',
  'claude-code',
  'skill',
  '[{"solution": "Configure Pod Security Standards with namespace labels for enforce/audit/warn", "cli": {"macos": "kubectl label namespace production pod-security.kubernetes.io/enforce=restricted", "linux": "kubectl label namespace production pod-security.kubernetes.io/enforce=restricted", "windows": "kubectl label namespace production pod-security.kubernetes.io/enforce=restricted"}, "note": "Use restricted for production, baseline for compatibility"}, {"solution": "Implement NetworkPolicy with default-deny-all and explicit allow rules", "cli": {"macos": "kubectl apply -f network-policy-template.yaml", "linux": "kubectl apply -f network-policy-template.yaml", "windows": "kubectl apply -f network-policy-template.yaml"}, "note": "Ensure CNI plugin supports NetworkPolicy (Calico, Cilium, Weave)"}, {"solution": "Configure RBAC with least-privilege access: create Role, ClusterRole, and RoleBinding", "cli": {"macos": "kubectl create role pod-reader --verb=get,list,watch --resource=pods -n production", "linux": "kubectl create role pod-reader --verb=get,list,watch --resource=pods -n production", "windows": "kubectl create role pod-reader --verb=get,list,watch --resource=pods -n production"}, "note": "Always specify resourceNames for fine-grained access control"}, {"solution": "Run pods securely with SecurityContext: non-root, read-only filesystem, dropped capabilities", "cli": {"macos": "kubectl apply -f secure-pod.yaml", "linux": "kubectl apply -f secure-pod.yaml", "windows": "kubectl apply -f secure-pod.yaml"}, "note": "Set runAsNonRoot=true and drop ALL capabilities"}, {"solution": "Enforce policies with OPA Gatekeeper or Kyverno for admission control", "cli": {"macos": "kubectl apply -f constraint-template.yaml && kubectl apply -f constraint.yaml", "linux": "kubectl apply -f constraint-template.yaml && kubectl apply -f constraint.yaml", "windows": "kubectl apply -f constraint-template.yaml && kubectl apply -f constraint.yaml"}, "note": "Validate policies before enforcement"}]'::jsonb,
  'script',
  'Kubernetes 1.24+, kubectl CLI, CNI plugin supporting NetworkPolicy, understanding of RBAC concepts',
  'Starting with restrictive policies before understanding workload requirements; NetworkPolicy rules that are too permissive or missing DNS egress; RBAC roles with wildcard permissions; running containers as root; forgetting to audit policies before enforcing them',
  'Namespace enforces Pod Security Standards; NetworkPolicy rules restrict traffic as intended; RBAC permissions verified with kubectl auth can-i; pods run as non-root with dropped capabilities; audit logging shows policy violations',
  'Implement defense-in-depth Kubernetes security using network policies, RBAC, pod security standards, and admission control',
  'https://skillsmp.com/skills/wshobson-agents-plugins-kubernetes-operations-skills-k8s-security-policies-skill-md',
  'admin:HAIKU_SKILL_1764289639_88230'
);
