INSERT INTO knowledge_entries (query, category, type, solutions, executable_type, prerequisites, common_pitfalls, success_indicators, preview_summary, source_url, contributor_email)
VALUES (
  'MCP Integration - Add MCP servers to Claude Code plugins for external service integration',
  'claude-code',
  'skill',
  '[{"solution": "Create .mcp.json with stdio server for local tools", "cli": {"macos": "cat > .mcp.json << ''EOF''\n{\n  \"my-server\": {\n    \"command\": \"npx\",\n    \"args\": [\"-y\", \"@modelcontextprotocol/server-filesystem\", \"/path\"],\n    \"env\": {\"LOG_LEVEL\": \"info\"}\n  }\n}\nEOF", "linux": "cat > .mcp.json << ''EOF''\n{\n  \"my-server\": {\n    \"command\": \"npx\",\n    \"args\": [\"-y\", \"@modelcontextprotocol/server-filesystem\", \"/path\"],\n    \"env\": {\"LOG_LEVEL\": \"info\"}\n  }\n}\nEOF", "windows": "Create .mcp.json file with stdio server configuration"}, "manual": "1. Create .mcp.json at plugin root\n2. Define server with command, args, env\n3. Use ${CLAUDE_PLUGIN_ROOT} for portable paths\n4. Add environment variables for configuration\n5. Test with /mcp command to verify server connects", "note": "stdio servers are child processes. Best for local tools, NPM packages, custom servers."}, {"solution": "Configure SSE or HTTP server with OAuth/tokens", "cli": {"macos": "cat > .mcp.json << ''EOF''\n{\n  \"cloud-service\": {\n    \"type\": \"sse\",\n    \"url\": \"https://mcp.example.com/sse\",\n    \"headers\": {\"X-API-Key\": \"${API_KEY}\"}\n  }\n}\nEOF", "linux": "cat > .mcp.json << ''EOF''\n{\n  \"cloud-service\": {\n    \"type\": \"sse\",\n    \"url\": \"https://mcp.example.com/sse\",\n    \"headers\": {\"X-API-Key\": \"${API_KEY}\"}\n  }\n}\nEOF", "windows": "Create .mcp.json with type (sse/http/ws) and authentication headers"}, "manual": "1. Choose server type: sse (OAuth/hosted), http (REST/tokens), ws (WebSocket)\n2. Provide URL and authentication headers\n3. Use environment variables for tokens: ${API_TOKEN}\n4. Document required env vars in README\n5. Test with /mcp command to verify connection", "note": "SSE best for OAuth services (Asana, GitHub). HTTP for REST APIs with tokens."}, {"solution": "Pre-allow MCP tools in commands for security", "cli": {"macos": "cat > command.md << ''EOF''\n---\nallowed-tools: [\n  \"mcp__plugin_name_server__tool_one\",\n  \"mcp__plugin_name_server__tool_two\"\n]\n---\n\nCommand content\nEOF", "linux": "cat > command.md << ''EOF''\n---\nallowed-tools: [\n  \"mcp__plugin_name_server__tool_one\",\n  \"mcp__plugin_name_server__tool_two\"\n]\n---\n\nCommand content\nEOF", "windows": "Add allowed-tools array in command YAML frontmatter"}, "manual": "1. List specific MCP tool names in allowed-tools array\n2. Tool naming: mcp__plugin_<name>_<server>__<tool>\n3. Pre-allow only necessary tools (security)\n4. Avoid wildcards unless required\n5. Use /mcp command to discover available tool names", "note": "Pre-allowing is security best practice. Wildcards (mcp__plugin_*__*) available but not recommended."}]'::jsonb,
  'steps',
  'Claude Code plugin structure, understanding MCP server types (stdio/SSE/HTTP/ws), basic JSON',
  'Hardcoding tokens instead of environment variables, forgetting HTTPS/WSS for secure connections, wrong tool naming format in allowed-tools, not documenting required environment variables',
  'MCP server appears in /mcp output, tools listed with correct naming, authentication succeeds, tool calls work in commands',
  'Integrate Model Context Protocol servers to provide external service tools in Claude Code plugins',
  'https://skillsmp.com/skills/anthropics-claude-code-plugins-plugin-dev-skills-mcp-integration-skill-md',
  'admin:HAIKU_SKILL_1764289548_81336'
);
